{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/597ee0b/test-utils-annotations-597ee0b.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "597ee0b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js.klib",
          "url": "test-utils-annotations-js-597ee0b.klib",
          "size": 9629,
          "sha512": "8a3cbc5845d3ca74607f2fee19a306bfb0990c5e4d0a7355a54a78b03c3d9bf067e0574603d622206b91139c041f71e7a5dc9490b01b82310712804bbee66280",
          "sha256": "7bc7646f0fda63a830aad910b0c264ef8474916159796dc0cfa9a5aabb518f2b",
          "sha1": "8eeb4c5c4f70c85b1804722ff9779979a472aef5",
          "md5": "bd3242b20316002c0fcdcf3e4ac0d285"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js.klib",
          "url": "test-utils-annotations-js-597ee0b.klib",
          "size": 9629,
          "sha512": "8a3cbc5845d3ca74607f2fee19a306bfb0990c5e4d0a7355a54a78b03c3d9bf067e0574603d622206b91139c041f71e7a5dc9490b01b82310712804bbee66280",
          "sha256": "7bc7646f0fda63a830aad910b0c264ef8474916159796dc0cfa9a5aabb518f2b",
          "sha1": "8eeb4c5c4f70c85b1804722ff9779979a472aef5",
          "md5": "bd3242b20316002c0fcdcf3e4ac0d285"
        }
      ]
    }
  ]
}
