{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/8066bd0/test-utils-annotations-junit4-8066bd0.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "8066bd0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-androidnativex86-8066bd0.klib",
          "size": 11369,
          "sha512": "562e99ac2e355f89617869275368e6c41c50f89060229daf0236c28d4787b84daf9dc9d0206c0a703549e6459a429dc70cabbe95a2c6b6f3b61e344a09980d2f",
          "sha256": "1848afed56bcde7fd4be28bd369297fd0b4e4e377719ed62303b1cf0ce3ff9d4",
          "sha1": "42e32bb1b255a332a47a11695db11236b684d5b6",
          "md5": "644f6d90e91b5fc4cb6dde636b79c434"
        }
      ]
    }
  ]
}
