{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "98f5a1d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-metadata-98f5a1d-all.jar",
          "url": "test-utils-98f5a1d-all.jar",
          "size": 9814,
          "sha512": "ac3258e82e48fa0ac2235d2ad4a26f5a14204fa7a175bf64ed904750750d509b2522251f721f2e74cff55028327085f1f1be211f729f17834d85713f1d280dcc",
          "sha256": "893dfe2fe3f1ae5e97554238388e765a1288a265e0dce4cd6b413b2c89b30d92",
          "sha1": "89c02f583abc1ec695f078b26c940827c579769b",
          "md5": "4ca4c7d0dc6d13c0bec3488a336779c6"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-98f5a1d.jar",
          "url": "test-utils-98f5a1d.jar",
          "size": 3985,
          "sha512": "4da9fabeedc9461c78e2c7556cabbec4b0dec884a1033a5c1b9ea26aeef42921ab660a8136cb6a836146cf19ca04189469ced3f14ded6a0a785b356f4efe7b17",
          "sha256": "14106e40ff93298fccb498001e2b0177d5d721eb2507fc36e2631450925f1321",
          "sha1": "197199c4c46c10a5eb5afb8be12808ec0bf60edc",
          "md5": "34e6447e3974203d571322e48dd91d6c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/98f5a1d/test-utils-android-98f5a1d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "98f5a1d"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/98f5a1d/test-utils-android-98f5a1d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "98f5a1d"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosarm64/98f5a1d/test-utils-iosarm64-98f5a1d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosarm64",
        "version": "98f5a1d"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosarm64/98f5a1d/test-utils-iosarm64-98f5a1d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosarm64",
        "version": "98f5a1d"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iossimulatorarm64/98f5a1d/test-utils-iossimulatorarm64-98f5a1d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iossimulatorarm64",
        "version": "98f5a1d"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iossimulatorarm64/98f5a1d/test-utils-iossimulatorarm64-98f5a1d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iossimulatorarm64",
        "version": "98f5a1d"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosx64/98f5a1d/test-utils-iosx64-98f5a1d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosx64",
        "version": "98f5a1d"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosx64/98f5a1d/test-utils-iosx64-98f5a1d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosx64",
        "version": "98f5a1d"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-js/98f5a1d/test-utils-js-98f5a1d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-js",
        "version": "98f5a1d"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-js/98f5a1d/test-utils-js-98f5a1d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-js",
        "version": "98f5a1d"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/98f5a1d/test-utils-jvm-98f5a1d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "98f5a1d"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/98f5a1d/test-utils-jvm-98f5a1d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "98f5a1d"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-linuxx64/98f5a1d/test-utils-linuxx64-98f5a1d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-linuxx64",
        "version": "98f5a1d"
      }
    }
  ]
}
