{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosarm64-0.1.1-SNAPSHOT.klib",
          "size": 195666,
          "sha512": "d731398a304669c1b84dca7f9e871f17e3365436e028abbc8d53d16ba6e41a22abc6ab7f6e374b19f7b308d6bcf0a5659e613591d928923e84a4478002fecc2f",
          "sha256": "0f548133b2d0830ea02acde9d09caf33dde925ca5a2de50dc874a13b7ba15209",
          "sha1": "23a88bc5ba0799b76062a13615f32c7f8be1dfbf",
          "md5": "801e379244e18d1327eaf07b4cef073b"
        }
      ]
    }
  ]
}
