{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/56c4547/test-utils-annotations-junit5-56c4547.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "56c4547",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-macosx64-56c4547.klib",
          "size": 7050,
          "sha512": "a17acbea12d977f4f28ebbf5f18e23c0c27fb354ccbe569e09ad9bbf969431103a66006aef7eaf0ceddaf11828c14b3ca766c2e73f2ff818f30fe751fd396a4b",
          "sha256": "7956f67a59f38a3b3c69dc9748e14bc1d3ca4b48c9b12b61c1f7ea86bf70406a",
          "sha1": "0cda7c8e43b80a838c697be24988c5f8c2d3bc17",
          "md5": "926054f5ad8f619189bcdf19cfef0601"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-macosx64-56c4547-metadata.jar",
          "url": "test-utils-annotations-junit5-macosx64-56c4547-metadata.jar",
          "size": 261,
          "sha512": "6902ff841ccb9d2f1f2b6f0c2b27485e3861ade78533e41128ef6b7381139d1c20260c3fdf178a845f182aa22c36b3e8847c7773dd530b5febf029034e72a8fc",
          "sha256": "5155538f2fc802cbcbc3aff832bbef1a633132d05cb4f526ec4c94c0c460d6b7",
          "sha1": "443b8fb2f01648590b9df73d940d1b73a6b33c62",
          "md5": "93f730f0528aed3929339df4f6c76640"
        }
      ]
    }
  ]
}
