{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/c3e5acf/test-utils-annotations-c3e5acf.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "c3e5acf",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm-c3e5acf.jar",
          "url": "test-utils-annotations-jvm-c3e5acf.jar",
          "size": 10872,
          "sha512": "a59506ed26b6254eed389195ad9b18eaa13d2ff819c9b886ee67ea0cbe31b682206b5846fafae6fbba87acf3565b2e23c14f6a25f79b690eb19201c01e4ee4b9",
          "sha256": "5f4c70d3c67dd034a818644427c36875598ca7420bebdea5eaeb6942afa088d3",
          "sha1": "a81dd2192318e78947e087173d686b1752592c82",
          "md5": "0034246c792ba0f253663f46d2c636f2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm-c3e5acf.jar",
          "url": "test-utils-annotations-jvm-c3e5acf.jar",
          "size": 10872,
          "sha512": "a59506ed26b6254eed389195ad9b18eaa13d2ff819c9b886ee67ea0cbe31b682206b5846fafae6fbba87acf3565b2e23c14f6a25f79b690eb19201c01e4ee4b9",
          "sha256": "5f4c70d3c67dd034a818644427c36875598ca7420bebdea5eaeb6942afa088d3",
          "sha1": "a81dd2192318e78947e087173d686b1752592c82",
          "md5": "0034246c792ba0f253663f46d2c636f2"
        }
      ]
    }
  ]
}
