{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "ae101dc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-ae101dc.jar",
          "url": "antibytes-gradle-utils-ae101dc.jar",
          "size": 11392,
          "sha512": "664c27026475677140f94c57f65e1dd37f7fdf255f9caf3088a53fc3d473bd7a97ddb23c74052c728380edaba4d6af3a4f57ba85cc5c76d11fa3b5264cb9b23b",
          "sha256": "461b9f0448ea2685e6e61f0ce6e20f3da7c05d0c6c5cdf046d469fae18b8ba66",
          "sha1": "3259b47f6ae5928d9f1c6d0a51fcff811e4d48c1",
          "md5": "37cbe3a110f1d1d4557afd4eb2d73b9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-ae101dc.jar",
          "url": "antibytes-gradle-utils-ae101dc.jar",
          "size": 11392,
          "sha512": "664c27026475677140f94c57f65e1dd37f7fdf255f9caf3088a53fc3d473bd7a97ddb23c74052c728380edaba4d6af3a4f57ba85cc5c76d11fa3b5264cb9b23b",
          "sha256": "461b9f0448ea2685e6e61f0ce6e20f3da7c05d0c6c5cdf046d469fae18b8ba66",
          "sha1": "3259b47f6ae5928d9f1c6d0a51fcff811e4d48c1",
          "md5": "37cbe3a110f1d1d4557afd4eb2d73b9f"
        }
      ]
    }
  ]
}
