{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "183d5f4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-183d5f4.jar",
          "url": "antibytes-dependency-helper-183d5f4.jar",
          "size": 69711,
          "sha512": "fe6a45c2949625e5560826a13ffafd5258051eea45eab2d1d448644030cc3a3f302e88989b368a7b7c21d53d2dbc299bc536678b27b68d6c61f886b3738d1bb7",
          "sha256": "8ce90e73cce9fed02c78d295c09d2b6241ab6b55a93289a4c5cd76b6f35d151b",
          "sha1": "be8b53b866719e0faf9170bfd1141d763ceaa043",
          "md5": "bf78e774d7aa3ebc10af9ff3b191e705"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.49.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "183d5f4"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-183d5f4.jar",
          "url": "antibytes-dependency-helper-183d5f4.jar",
          "size": 69711,
          "sha512": "fe6a45c2949625e5560826a13ffafd5258051eea45eab2d1d448644030cc3a3f302e88989b368a7b7c21d53d2dbc299bc536678b27b68d6c61f886b3738d1bb7",
          "sha256": "8ce90e73cce9fed02c78d295c09d2b6241ab6b55a93289a4c5cd76b6f35d151b",
          "sha1": "be8b53b866719e0faf9170bfd1141d763ceaa043",
          "md5": "bf78e774d7aa3ebc10af9ff3b191e705"
        }
      ]
    }
  ]
}
