{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1-SNAPSHOT/core-0.3.1-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.3.1-SNAPSHOT.klib",
          "url": "core-js-0.3.1-SNAPSHOT.klib",
          "size": 134545,
          "sha512": "ae9b78164d52ae0cb9527ed038ab9ecea50ba3f2efd4648979fc6c00a19202dcc90f6539ee8801baab8dc1d931801ca44b5e61bef775db82e7957806675d643b",
          "sha256": "0c951d3429ffc15349ce3b8cf1bf5e537d255cabba194c66a56ef7bf40096015",
          "sha1": "6e8d7d1b7e1dc84e6cda200123ad0792c26feb8f",
          "md5": "6b41c6a1bf4de7737ae7173a47ea244e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.3.1-SNAPSHOT.klib",
          "url": "core-js-0.3.1-SNAPSHOT.klib",
          "size": 134545,
          "sha512": "ae9b78164d52ae0cb9527ed038ab9ecea50ba3f2efd4648979fc6c00a19202dcc90f6539ee8801baab8dc1d931801ca44b5e61bef775db82e7957806675d643b",
          "sha256": "0c951d3429ffc15349ce3b8cf1bf5e537d255cabba194c66a56ef7bf40096015",
          "sha1": "6e8d7d1b7e1dc84e6cda200123ad0792c26feb8f",
          "md5": "6b41c6a1bf4de7737ae7173a47ea244e"
        }
      ]
    }
  ]
}
