{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1-SNAPSHOT/core-0.3.1-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.3.1-SNAPSHOT.klib",
          "url": "core-js-0.3.1-SNAPSHOT.klib",
          "size": 134545,
          "sha512": "e0821514e19f8d6c2e16124f4ab86c3fcc86837218968b0ffdc9957780b9d84a53a7dfa6833214070000ab0d7f0b98fe34f817cf857fae24c36dca798797d126",
          "sha256": "c98577d7398e0c577910f71f902aa161ff8d55b7ebabc2b2028d73eecd5227f9",
          "sha1": "0354128c76d26e9f13a37166520629aea5f99041",
          "md5": "ac0f833a079e9dd3559151e33c6ce2af"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.3.1-SNAPSHOT.klib",
          "url": "core-js-0.3.1-SNAPSHOT.klib",
          "size": 134545,
          "sha512": "e0821514e19f8d6c2e16124f4ab86c3fcc86837218968b0ffdc9957780b9d84a53a7dfa6833214070000ab0d7f0b98fe34f817cf857fae24c36dca798797d126",
          "sha256": "c98577d7398e0c577910f71f902aa161ff8d55b7ebabc2b2028d73eecd5227f9",
          "sha1": "0354128c76d26e9f13a37166520629aea5f99041",
          "md5": "ac0f833a079e9dd3559151e33c6ce2af"
        }
      ]
    }
  ]
}
