{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "42d3d0a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-42d3d0a.jar",
          "url": "antibytes-android-application-configuration-42d3d0a.jar",
          "size": 56574,
          "sha512": "3328ece2af1be65d0e6c0dbc18b5808c9888cbf35da5912e0f87b581b29901bebb4493f1460957ce92745350c691458b0e5820ee38bd3ad5a2bece670a173683",
          "sha256": "9b2f23adda0a91a6a03bc662a2e12dfa1aeb5b1392d8a21b60a83b70c2398ac8",
          "sha1": "f551b958eeea8ecb384093752567fa4d259064b1",
          "md5": "60d528015287892a41e8aec753c4b963"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "42d3d0a"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-42d3d0a.jar",
          "url": "antibytes-android-application-configuration-42d3d0a.jar",
          "size": 56574,
          "sha512": "3328ece2af1be65d0e6c0dbc18b5808c9888cbf35da5912e0f87b581b29901bebb4493f1460957ce92745350c691458b0e5820ee38bd3ad5a2bece670a173683",
          "sha256": "9b2f23adda0a91a6a03bc662a2e12dfa1aeb5b1392d8a21b60a83b70c2398ac8",
          "sha1": "f551b958eeea8ecb384093752567fa4d259064b1",
          "md5": "60d528015287892a41e8aec753c4b963"
        }
      ]
    }
  ]
}
