{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/3948768/test-utils-fixture-3948768.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "3948768",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm-3948768.jar",
          "url": "test-utils-fixture-jvm-3948768.jar",
          "size": 68983,
          "sha512": "3190394a295398403aec005bae4effe6e9c2cf952f138119bf866854bddc4e499c1f044508c1fbac5c47f2f07b1e01f307be6dc981d5db5ce2ec948e153b1a3a",
          "sha256": "9fd384db67df26c07a53fa6ac614b1cf95fefbb0df780fd0aae507eb27b6563f",
          "sha1": "ff081bab5d26d84c452103a580ce71560556ad27",
          "md5": "6c6de4e0acc8086eaf083a36dff2a57e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm-3948768.jar",
          "url": "test-utils-fixture-jvm-3948768.jar",
          "size": 68983,
          "sha512": "3190394a295398403aec005bae4effe6e9c2cf952f138119bf866854bddc4e499c1f044508c1fbac5c47f2f07b1e01f307be6dc981d5db5ce2ec948e153b1a3a",
          "sha256": "9fd384db67df26c07a53fa6ac614b1cf95fefbb0df780fd0aae507eb27b6563f",
          "sha1": "ff081bab5d26d84c452103a580ce71560556ad27",
          "md5": "6c6de4e0acc8086eaf083a36dff2a57e"
        }
      ]
    }
  ]
}
