{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/e99bb93/test-utils-ktor-e99bb93.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "e99bb93",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm-e99bb93.jar",
          "url": "test-utils-ktor-jvm-e99bb93.jar",
          "size": 26407,
          "sha512": "fe4d6aac38e550c5dc8ca12667d167fdf9902dbbae8b90a04513a0296e0c6536ce96c363d3a43e59248aade97a19cd90885b41bdade4ef9b7ae908241fef38a2",
          "sha256": "4486f487eb7d9aee7065253e0c5f2821ba02071176ec723d2546095cc907aa84",
          "sha1": "5417dcab9acbd9c546289a250fec2800ac0da21b",
          "md5": "899473b8e0c8d5f68beafc095ed698fe"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-e99bb93.jar",
          "url": "test-utils-ktor-jvm-e99bb93.jar",
          "size": 26407,
          "sha512": "fe4d6aac38e550c5dc8ca12667d167fdf9902dbbae8b90a04513a0296e0c6536ce96c363d3a43e59248aade97a19cd90885b41bdade4ef9b7ae908241fef38a2",
          "sha256": "4486f487eb7d9aee7065253e0c5f2821ba02071176ec723d2546095cc907aa84",
          "sha1": "5417dcab9acbd9c546289a250fec2800ac0da21b",
          "md5": "899473b8e0c8d5f68beafc095ed698fe"
        }
      ]
    }
  ]
}
