{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "5bbfded",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-5bbfded.toml",
          "url": "antibytes-dependency-catalog-5bbfded.toml",
          "size": 230879,
          "sha512": "cde24894b0af4c21c557e190133143d308122e6fb5d15251a0d4d686c5a4badf230abbcdbec78e6a1272e11281065e1431f0895e3571b653b6db603d6908a92e",
          "sha256": "45132531a27c4d94e15fb9ffcc41ef21e14ae33860c40134d0becf347643585b",
          "sha1": "36b4005a3fe4858e45526193b4ca372c3dd042fd",
          "md5": "631e14a0fea483b43f607fcc78cf5f3b"
        }
      ]
    }
  ]
}
