{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-watchosarm32-0.4.0-SNAPSHOT.klib",
          "size": 105871,
          "sha512": "15f433215238fd539763e12c39180ba6d4467558426b2ec74efd46538eac53aaa2119c4dc7f532f6d67c40c587b8ca233303955a58b57b97ceffbd972d46905b",
          "sha256": "7bb24ab9548c98329cb067d45919be5b024b4d2bcc27c1963e6170be77237746",
          "sha1": "e4ba4d4b9033c5635955248aa46ca1ef9ca7c0fb",
          "md5": "88176f7c5deaa4609744a2c8e1a4ef20"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchosarm32-0.4.0-SNAPSHOT-metadata.jar",
          "url": "core-watchosarm32-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "f483c6a299b25521d45213ad8d5e443ae8ddb61745447e26eb34ab0dd6199a2e6642b920356b8701b8d8dec6f64c08cfe1278c670d7d3c10f42d280258f5a22f",
          "sha256": "add30337c4a439d179686b6850bccaa36e8497c0093d8be4323f6f4774b4bc9f",
          "sha1": "c6dbdcf86b325237b5ee8267ad38266e161fc04f",
          "md5": "9c515af6868037bdcf6ec856d133376e"
        }
      ]
    }
  ]
}
