{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "4e1c621",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-4e1c621.toml",
          "url": "antibytes-dependency-catalog-4e1c621.toml",
          "size": 232720,
          "sha512": "554607a2884a26f16e8ace4f2de05bbd68129a98d5b4cf6c5f4b72bc3eba0768ff62f25076804083f7563b652d07d4c00b4adaa70fca272c3769cce6ccd5e8f7",
          "sha256": "3a63e52775b13aee79ae9a629affbc2b86ae08873afd905a47a8f248fa8f1509",
          "sha1": "b3f214d177e492284cb030c8527fe2787b7bd6f4",
          "md5": "3e577f3cdcb4854caa53a186ffad343e"
        }
      ]
    }
  ]
}
