{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.dokka",
    "module": "antibytes-dokka-configuration",
    "version": "b5d11da",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dokka-configuration-b5d11da.jar",
          "url": "antibytes-dokka-configuration-b5d11da.jar",
          "size": 8108,
          "sha512": "8a553d3366156d1e9ee7f39cddd4038c08d87bc1a6a1dc0b8f53c3d15c028ad56fe669cd3883e48b8301a0348c5d40bfede80e623b5896098251e95f2ed9418f",
          "sha256": "72972e57e06820c7c6bb9c097853d3eb467275db3b89a47b01548d2738201b1a",
          "sha1": "20552a779c00d1517005bf8f15e352e5bd3cd489",
          "md5": "7e95eefd71fd6612032056867c656353"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "b5d11da"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dokka-configuration-b5d11da.jar",
          "url": "antibytes-dokka-configuration-b5d11da.jar",
          "size": 8108,
          "sha512": "8a553d3366156d1e9ee7f39cddd4038c08d87bc1a6a1dc0b8f53c3d15c028ad56fe669cd3883e48b8301a0348c5d40bfede80e623b5896098251e95f2ed9418f",
          "sha256": "72972e57e06820c7c6bb9c097853d3eb467275db3b89a47b01548d2738201b1a",
          "sha1": "20552a779c00d1517005bf8f15e352e5bd3cd489",
          "md5": "7e95eefd71fd6612032056867c656353"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dokka-configuration-b5d11da-javadoc.jar",
          "url": "antibytes-dokka-configuration-b5d11da-javadoc.jar",
          "size": 261,
          "sha512": "4ada1b51030113308765f131b4b87b3eb73d9222356dfcab307d057777bf5e5d620e0583672d2c3a0170c288e50135b116c580292b269c633a7fa19cae268571",
          "sha256": "34b33ec56f859b29f7dfe29d532ad6f53062a5ad9f404f14981df79c165807d9",
          "sha1": "08236e1b0cef1eaa301dcbe29d32dde6c57ba1cb",
          "md5": "e6fd6c03c223768d829703913d97b940"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dokka-configuration-b5d11da-sources.jar",
          "url": "antibytes-dokka-configuration-b5d11da-sources.jar",
          "size": 2499,
          "sha512": "9dd1736f4987d579c1cbb514c888b0435cf4c47dc612e5ed28695b746dbf83a869081089e947e70535b2fdc70e9c32947f317cd44cc725f14934edc422a84684",
          "sha256": "4d6b25e60d41feaddf49e30a901e32972ed0e79241167803e123092032016e37",
          "sha1": "4f007bde257218aa227a86de9ba4011e1060e553",
          "md5": "9f84dd57ed13aecd2791d7041bf768ec"
        }
      ]
    }
  ]
}
