{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "87f0ce6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-87f0ce6.jar",
          "url": "antibytes-grammar-tools-87f0ce6.jar",
          "size": 59182,
          "sha512": "0994d3379eb28e7d917a9b8668f90954eb1b67ddcd5ec45990faccf90e56142551f38ff7f6be1d6b677b71c2053cffd04754401e0050cf95773fad4dbc0652a2",
          "sha256": "27d93355188e6fc3e66c7a52c9bcc6f7bb066af5b1a120792497e44dfce68895",
          "sha1": "1ec06ef6b352ee48c2ca2577eda217063189b19c",
          "md5": "2a347b7bfe36e7fad563d33fc4d59717"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-87f0ce6.jar",
          "url": "antibytes-grammar-tools-87f0ce6.jar",
          "size": 59182,
          "sha512": "0994d3379eb28e7d917a9b8668f90954eb1b67ddcd5ec45990faccf90e56142551f38ff7f6be1d6b677b71c2053cffd04754401e0050cf95773fad4dbc0652a2",
          "sha256": "27d93355188e6fc3e66c7a52c9bcc6f7bb066af5b1a120792497e44dfce68895",
          "sha1": "1ec06ef6b352ee48c2ca2577eda217063189b19c",
          "md5": "2a347b7bfe36e7fad563d33fc4d59717"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-87f0ce6-javadoc.jar",
          "url": "antibytes-grammar-tools-87f0ce6-javadoc.jar",
          "size": 261,
          "sha512": "81e334b4b0e42bc2d70b1af9d9cdb36e3f24b7d3291cfba6c47c4c224a5622c3bf8ac8460781a519bba12937d2160b0c111fe8f4ab35fb8efa637e3f8b8e1fa4",
          "sha256": "24a682257e90785851f00491472ceeb40d81684edc0eadd13445c84f614e5f34",
          "sha1": "c3fda6289462bd4fc729fedd5981a85171f1958d",
          "md5": "6dbf4dce8359e82e8062389ed32e1285"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-87f0ce6-sources.jar",
          "url": "antibytes-grammar-tools-87f0ce6-sources.jar",
          "size": 12245,
          "sha512": "3a2ac6d5eb0e0ec3dadc19f99e3e835f2131bc00720eea0fbf3432756c282dbd04c147c3e35114d28156d20e3fb8de2ff4dcaf67790afd2f4d441609c879a86a",
          "sha256": "bb8e5324ce2de33a7cef3830c68ced6cbc164e4afcaeb8e6fd1055b5df0c453f",
          "sha1": "9e4cfc1f85ed18583d16ce4772e37228be9657fc",
          "md5": "9f7b6b9977bd1d9dfaaa432cc6739ff9"
        }
      ]
    }
  ]
}
