{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "f12714d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-f12714d.jar",
          "url": "antibytes-dependency-f12714d.jar",
          "size": 59502,
          "sha512": "fb5944e47b235e87e96a33c7a7bc06fbda9e4e66175a9f045413b433a8762ac416d41f4c919f2f38c06c6968f8149a3e7b46ffe3d738d596d85ae3996d0cf78a",
          "sha256": "e51e5e5ed03aefc06e6007d451b24b005da8c83f19abf34c29c43d885751e781",
          "sha1": "4230da6f2a29e3479cdecfe088d437cc76c6fa12",
          "md5": "55ec8d433df2102218ffab912d25e7f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-gradle-plugin",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "6.5.3"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.3.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "f12714d"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-f12714d.jar",
          "url": "antibytes-dependency-f12714d.jar",
          "size": 59502,
          "sha512": "fb5944e47b235e87e96a33c7a7bc06fbda9e4e66175a9f045413b433a8762ac416d41f4c919f2f38c06c6968f8149a3e7b46ffe3d738d596d85ae3996d0cf78a",
          "sha256": "e51e5e5ed03aefc06e6007d451b24b005da8c83f19abf34c29c43d885751e781",
          "sha1": "4230da6f2a29e3479cdecfe088d437cc76c6fa12",
          "md5": "55ec8d433df2102218ffab912d25e7f2"
        }
      ]
    }
  ]
}
