{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/8b81c5a/test-utils-fixture-8b81c5a.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "8b81c5a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture.klib",
          "url": "test-utils-fixture-iosarm64-8b81c5a.klib",
          "size": 32832,
          "sha512": "7fe6ef6bc2cf9e6974c6beb95a44df0b7cdcd56affe7d34956aa7ddd8ce8ee98c7f53a0f32e137cd5524fc4a252dd7f8d62c267dcad2b5defdbf80cd8f661094",
          "sha256": "2767a1291f6b0e75624eb854bd6af15718fc74a53555f6635760ca4b3b2c7f18",
          "sha1": "bd18e8ef92b1e6cc6d0088bf3cc1cccc7fe652ac",
          "md5": "15f35e361e2c65b029f047f1db8796c9"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-iosarm64-8b81c5a-metadata.jar",
          "url": "test-utils-fixture-iosarm64-8b81c5a-metadata.jar",
          "size": 261,
          "sha512": "78546d344a2fee0cb4e8936cd60191735c8b95c47059b73039ad950801b527a24c85a9e7666f7b3f9d6907abef2825aca9009ade39f8cedf23921ebdfc8d20cd",
          "sha256": "7785ab41dd8353021def501c0b5090ea9deb0060ff0136ec4392f296f6e44917",
          "sha1": "c05bec6be19a6cddb6978267c987bed1e1f6da54",
          "md5": "071e4e171e51a15805f50040399805c7"
        }
      ]
    }
  ]
}
