{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/766ba9c/test-utils-766ba9c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "766ba9c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-766ba9c.jar",
          "url": "test-utils-jvm-766ba9c.jar",
          "size": 4570,
          "sha512": "f2f58171777f6387965658cf5441e18ff4c0c04e7f65430737991f405043f9032cbd2377dff9875c4202c28d9a6d871b8d0c1cb2f8fe4a6a7244ac14e212dd9d",
          "sha256": "f11811a070b97da2a3b13b694fb0f16f5115d557167862246a2cb82878b98161",
          "sha1": "2b9311e45e801e978bd5d27d4bbb51a409be660e",
          "md5": "ab3a1b41116153f506ecb08723df4af5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-766ba9c.jar",
          "url": "test-utils-jvm-766ba9c.jar",
          "size": 4570,
          "sha512": "f2f58171777f6387965658cf5441e18ff4c0c04e7f65430737991f405043f9032cbd2377dff9875c4202c28d9a6d871b8d0c1cb2f8fe4a6a7244ac14e212dd9d",
          "sha256": "f11811a070b97da2a3b13b694fb0f16f5115d557167862246a2cb82878b98161",
          "sha1": "2b9311e45e801e978bd5d27d4bbb51a409be660e",
          "md5": "ab3a1b41116153f506ecb08723df4af5"
        }
      ]
    }
  ]
}
