{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/27ceceb/test-utils-27ceceb.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "27ceceb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm-27ceceb.jar",
          "url": "test-utils-jvm-27ceceb.jar",
          "size": 8776,
          "sha512": "6be4efbd291c3f6ed5144b0ab08c57f9c25d6caf62130effeeb659b42f91aa91b8eb5ed961417ab4240e937b5a6864d5e202b551e9d58913fedd300b905225dd",
          "sha256": "1369db51307d16dac4b04c424639366ceece4f210349ad760c424df577793e77",
          "sha1": "19390ed67eb931e7249b9b3c373781db49778443",
          "md5": "c144b4d276ddd1fac211e94adc92155f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-27ceceb.jar",
          "url": "test-utils-jvm-27ceceb.jar",
          "size": 8776,
          "sha512": "6be4efbd291c3f6ed5144b0ab08c57f9c25d6caf62130effeeb659b42f91aa91b8eb5ed961417ab4240e937b5a6864d5e202b551e9d58913fedd300b905225dd",
          "sha256": "1369db51307d16dac4b04c424639366ceece4f210349ad760c424df577793e77",
          "sha1": "19390ed67eb931e7249b9b3c373781db49778443",
          "md5": "c144b4d276ddd1fac211e94adc92155f"
        }
      ]
    }
  ]
}
