{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.coverage",
    "module": "antibytes-coverage",
    "version": "2a2dbc6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-2a2dbc6.jar",
          "url": "antibytes-coverage-2a2dbc6.jar",
          "size": 135187,
          "sha512": "9fd19ddae7ca50a198b97771c302722b8fe66a21e73f009f81979ae6ad820f5e45731abef828d01232a1794d460da11f06da34ffea3531dfcdcada2c72e4891f",
          "sha256": "d61b5c1b30db2035d77113fbf4be16151470fa541e3e5414492233d60a1df6f7",
          "sha1": "7bfa13b4f4e1bd9156792724929a3db2fa7a3f40",
          "md5": "01fad2a105e5c523fb4c9464404de043"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "2a2dbc6"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-2a2dbc6.jar",
          "url": "antibytes-coverage-2a2dbc6.jar",
          "size": 135187,
          "sha512": "9fd19ddae7ca50a198b97771c302722b8fe66a21e73f009f81979ae6ad820f5e45731abef828d01232a1794d460da11f06da34ffea3531dfcdcada2c72e4891f",
          "sha256": "d61b5c1b30db2035d77113fbf4be16151470fa541e3e5414492233d60a1df6f7",
          "sha1": "7bfa13b4f4e1bd9156792724929a3db2fa7a3f40",
          "md5": "01fad2a105e5c523fb4c9464404de043"
        }
      ]
    }
  ]
}
