{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/b5aaed7/test-utils-b5aaed7.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "b5aaed7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosx64-b5aaed7.klib",
          "size": 7944,
          "sha512": "25f3a71877f32cf043dac487ebbb53d8da138e0ff58242b257dacc6cf1bffda14f850caf2c5713010be077c95100cdb40bb5033d18e37f52a1886c97a016e47d",
          "sha256": "619be0373b05e0e14ec541377c98618efb15f0cd650e2d89149c0d6ec2a582a7",
          "sha1": "55dd25723d1e0c3bf49f99524aff65c338fdf96a",
          "md5": "8e559a5c6968296c38bd2f011da07083"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosx64-b5aaed7-metadata.jar",
          "url": "test-utils-iosx64-b5aaed7-metadata.jar",
          "size": 261,
          "sha512": "590b3b00468d3d46b5d3be7001292e78fa941d27ee94bd6b377e81a753011a07217859304d18ab9ff227e9f7ef3d0a2da566e153dbb6ea91a9c525bf53a40ca9",
          "sha256": "a8f5553254f7ecff0327abafcbfec648413c39a33044f3d06266fdae5bee1538",
          "sha1": "96edef85b56b998f1141f036c307967385336b6f",
          "md5": "d81203732383dc88d2fdc6ce2c77756b"
        }
      ]
    }
  ]
}
