{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "7121db5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-coroutine-metadata.jar",
          "url": "test-utils-coroutine-7121db5.jar",
          "size": 2149,
          "sha512": "e0c21b9b223d5cb260183c3797d798e9df90fc74d033e203381118153596641c45204b6ab858649a43b8b60d24bc6c6efd3f256251fd2daaa955727e2b1d9099",
          "sha256": "00bd936b204ae9bb9654d9ce5ec6176236488bc521961f353b22f39e84f2c78c",
          "sha1": "903681eb873c715d6fd48b66397bf20bfac0cd4b",
          "md5": "d57dfb3e77d162f0b1c6e9dd75a82aa6"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/7121db5/test-utils-coroutine-android-7121db5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "7121db5"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/7121db5/test-utils-coroutine-android-7121db5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "7121db5"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/7121db5/test-utils-coroutine-jvm-7121db5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "7121db5"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/7121db5/test-utils-coroutine-jvm-7121db5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "7121db5"
      }
    }
  ]
}
