{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/f384302/test-utils-f384302.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "f384302",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-watchosarm32-f384302.klib",
          "size": 7996,
          "sha512": "1975281765ac841c5fc8b2ec87604946a8db52e9a0dd33fb89ac6cdcbafe7cccdfef54b1c28abd2fc6f2caa325a56727d851d959786b5d6fb00da05a6cd297cd",
          "sha256": "db9db4ac6c5f286d389ab7b463d7dc80be9cfe03ebf0c5449693b222fe5709e6",
          "sha1": "53fef8b61249ddf8eb28e7da09d9e791be091e0d",
          "md5": "5763fb77f879aa8e919947a4be235080"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-watchosarm32-f384302-metadata.jar",
          "url": "test-utils-watchosarm32-f384302-metadata.jar",
          "size": 261,
          "sha512": "985b9efda6f6d2a46afa7357da8e33971a9a856f6e2bce58130ed562de571d55ee56623fbb23e370daf67fdc74cd40c6ae8aafea069d98921bb224af4f4ac61a",
          "sha256": "edf7090eb87a5cd91eaa349a6d0c5dbc16bf0058cf8cf531064e4e8e222799c7",
          "sha1": "e023ed101cf8afb9dcea072838711f6f46a2bd19",
          "md5": "5dd097d6641cb0b54ab0724fec3349bf"
        }
      ]
    }
  ]
}
