{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "c005b75",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-c005b75.jar",
          "url": "kmock-gradle-c005b75.jar",
          "size": 33287,
          "sha512": "8a8b1471e636dc15e289745c0f212325b2056d2d172c9dbddf355ddea07609293e736788a363789832d75bed14c3e598a6b30fabf7ed754159e2db9e6bd975b4",
          "sha256": "f3525be57be4fbf0df0962185fcc94ed67122e6de7eb92bfb36bd0486ccaf19e",
          "sha1": "5a666c3ad756ba94a56b90be1d791f6a83d82fbc",
          "md5": "5d4aab4b7f35537a75c78f1184fb2966"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "bb22160"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-c005b75.jar",
          "url": "kmock-gradle-c005b75.jar",
          "size": 33287,
          "sha512": "8a8b1471e636dc15e289745c0f212325b2056d2d172c9dbddf355ddea07609293e736788a363789832d75bed14c3e598a6b30fabf7ed754159e2db9e6bd975b4",
          "sha256": "f3525be57be4fbf0df0962185fcc94ed67122e6de7eb92bfb36bd0486ccaf19e",
          "sha1": "5a666c3ad756ba94a56b90be1d791f6a83d82fbc",
          "md5": "5d4aab4b7f35537a75c78f1184fb2966"
        }
      ]
    }
  ]
}
