{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/f25b461/test-utils-annotations-f25b461.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "f25b461",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-iosarm64-f25b461.klib",
          "size": 11334,
          "sha512": "6af6cbd9eff8184c553b5cec5f703b6616fb50a5a30ed48fe004e17491b3fd6de014821615af26a44897bfcca46085629a3e4d65b3e3d57f62f2041aa6803830",
          "sha256": "2fe3461e8b110c9fbc4f0af49ff00046b9e2b94b085f8d68461a2cdf5c53cb49",
          "sha1": "7fb6dc5db6305619a7fe527055e8cbab8b5103b2",
          "md5": "4e432e4026f3051b27c0faa0f057466c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-iosarm64-f25b461-metadata.jar",
          "url": "test-utils-annotations-iosarm64-f25b461-metadata.jar",
          "size": 261,
          "sha512": "441367daa0bd315672b4aaf2e5567c691fb025da23ca14ff6aeaf68cdb5597395dafea0a06d69f2eab0fd0f0332e911e05c89bb10413be1533609c15c465d6e1",
          "sha256": "f5eb958b1d24bbc2e083a1d396749fdf4cc5152c0d51fba2e4015d1693965b88",
          "sha1": "e8b40c177cff708e14c0dbb287231553c5418815",
          "md5": "80a3f350d1db541a3de730ab0e443231"
        }
      ]
    }
  ]
}
