{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "54a39ff",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-metadata-54a39ff.jar",
          "url": "kmock-54a39ff.jar",
          "size": 21090,
          "sha512": "cb830bc33e6ac3113e9851986cefeb53b313c194f3b902ef65bf067fcf17e82a78257d931fc183b1388da81276d10677d8675bc654e62e1b8a77262ae38ddfdb",
          "sha256": "60bb046e1b743dfb53c85c2a6c3b0d3de9ae7160c634f9e5bf91b17a9e482389",
          "sha1": "c43b06073ed973c9f6d8aa5f553b6a2c54b6e16e",
          "md5": "25f598b6efa67ecde9fec77ab10d8e30"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/54a39ff/kmock-android-54a39ff.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "54a39ff"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/54a39ff/kmock-android-54a39ff.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "54a39ff"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/54a39ff/kmock-iosarm64-54a39ff.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "54a39ff"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/54a39ff/kmock-iosx64-54a39ff.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "54a39ff"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/54a39ff/kmock-js-54a39ff.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "54a39ff"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/54a39ff/kmock-js-54a39ff.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "54a39ff"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/54a39ff/kmock-jvm-54a39ff.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "54a39ff"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/54a39ff/kmock-jvm-54a39ff.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "54a39ff"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/54a39ff/kmock-linuxx64-54a39ff.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "54a39ff"
      }
    }
  ]
}
