{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "9e2ffe9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-9e2ffe9.jar",
          "url": "antibytes-gradle-utils-9e2ffe9.jar",
          "size": 9568,
          "sha512": "8f9c24a820f0079b07c246b90126d013e4a7d57b6fab7bab3a6fead3e7aca9dc2f278734cf985154bfeabc3e6a85ef2c578296dfe01cb36e76baefcdc2aca3b6",
          "sha256": "a2d443c5631b596c8e42f51b6f648c21564c645b943dedbfaf581c1e4781a948",
          "sha1": "fd9d5fbecc68a6845071ebaba66a7c8c7d55e1b3",
          "md5": "48684db260dadbe2bad83ff05a2d240e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-9e2ffe9.jar",
          "url": "antibytes-gradle-utils-9e2ffe9.jar",
          "size": 9568,
          "sha512": "8f9c24a820f0079b07c246b90126d013e4a7d57b6fab7bab3a6fead3e7aca9dc2f278734cf985154bfeabc3e6a85ef2c578296dfe01cb36e76baefcdc2aca3b6",
          "sha256": "a2d443c5631b596c8e42f51b6f648c21564c645b943dedbfaf581c1e4781a948",
          "sha1": "fd9d5fbecc68a6845071ebaba66a7c8c7d55e1b3",
          "md5": "48684db260dadbe2bad83ff05a2d240e"
        }
      ]
    }
  ]
}
