{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/b5aaed7/test-utils-annotations-junit5-b5aaed7.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "b5aaed7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-iossimulatorarm64-b5aaed7.klib",
          "size": 7135,
          "sha512": "11d345fc64f6e9dec68c63102b2576443704c52100e65b33faaf3b8b08337be245f194456ea51e65cfabe34feef1add181af829ce7885a7977d5d41005286531",
          "sha256": "7aad63ef12408ddf057d9a90d3cd85bbde21ba77747fb5fd197ec32db68a5fd7",
          "sha1": "795460f85c22927d3586a3b92de139e140806fa2",
          "md5": "a422756344bc796618ae9c6a89dd1ed7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-iossimulatorarm64-b5aaed7-metadata.jar",
          "url": "test-utils-annotations-junit5-iossimulatorarm64-b5aaed7-metadata.jar",
          "size": 261,
          "sha512": "5463594af102db5e516365ea6f689530de42f12ebcb7b40d672f56872493c1c475c20f18573c557562152a766e1044a1b377e649410c7660b97e06b01aa4f182",
          "sha256": "15ece635af22445929639d6c8ecc834b31ed9a674b9af757bcde78f214bfca24",
          "sha1": "8edfdba537357445b4256baa3f3710dd5c93cec4",
          "md5": "a62e55b7776c466f8dafe5c1b9f3b369"
        }
      ]
    }
  ]
}
