{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "2a2dbc6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-2a2dbc6.jar",
          "url": "antibytes-dependency-helper-2a2dbc6.jar",
          "size": 68554,
          "sha512": "de3511a034fe697ccd1dbcdf726153aeff0f3c33df0140b67346fdafa51b606b4dd468e8b93a90118fb6c140adb774a9b744321aec5822f4840590b153d5bc52",
          "sha256": "7e0d3bbfbd516c12a37c06d3ef56d31c1ab30471a432b5da9ef63bb5e6601e65",
          "sha1": "58307469382d72be68d2d07a1c0422182ab55980",
          "md5": "26cfbf90ad2ff48aca1f4601794b5b16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "2a2dbc6"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-2a2dbc6.jar",
          "url": "antibytes-dependency-helper-2a2dbc6.jar",
          "size": 68554,
          "sha512": "de3511a034fe697ccd1dbcdf726153aeff0f3c33df0140b67346fdafa51b606b4dd468e8b93a90118fb6c140adb774a9b744321aec5822f4840590b153d5bc52",
          "sha256": "7e0d3bbfbd516c12a37c06d3ef56d31c1ab30471a432b5da9ef63bb5e6601e65",
          "sha1": "58307469382d72be68d2d07a1c0422182ab55980",
          "md5": "26cfbf90ad2ff48aca1f4601794b5b16"
        }
      ]
    }
  ]
}
