{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "ca7bdaf",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-ca7bdaf.jar",
          "url": "antibytes-dependency-helper-ca7bdaf.jar",
          "size": 70760,
          "sha512": "9610a39d5c2bd0109a479c7d826fb1443694735eae708f7d77e9f1b5581eba41123572ad6c14ea1538a0e61e28d1c15cc4b94f3efc0fd48b92b518a3e1133517",
          "sha256": "15d5956b636bbcf7aa12cfdc5714e1887224d506e9567cf0ea7ac27286c747d4",
          "sha1": "ee56529e014d4daa54febfc0763ed05a95cabcf7",
          "md5": "116a4bde70c0e87824065782c8b1d146"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "ca7bdaf"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-ca7bdaf.jar",
          "url": "antibytes-dependency-helper-ca7bdaf.jar",
          "size": 70760,
          "sha512": "9610a39d5c2bd0109a479c7d826fb1443694735eae708f7d77e9f1b5581eba41123572ad6c14ea1538a0e61e28d1c15cc4b94f3efc0fd48b92b518a3e1133517",
          "sha256": "15d5956b636bbcf7aa12cfdc5714e1887224d506e9567cf0ea7ac27286c747d4",
          "sha1": "ee56529e014d4daa54febfc0763ed05a95cabcf7",
          "md5": "116a4bde70c0e87824065782c8b1d146"
        }
      ]
    }
  ]
}
