{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "e45307c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-e45307c.jar",
          "url": "antibytes-custom-component-e45307c.jar",
          "size": 16172,
          "sha512": "e86bcdb363b68944752851ad7f091c692f73698979c171a6f1ddb39aa75b7c8c33e32d795b0d1e2d018b73b211208dc962b8c938f2ec273f5b8ff48a0758ad38",
          "sha256": "983f717b82f51b6ef541c4c49c0ea9a18c0e7178a413eb1217f4c741a0193992",
          "sha1": "a486eaec4ed457438b3f22ff181e5fcf2068ef84",
          "md5": "c1c29d4d70512830f8c967793b528fac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-e45307c.jar",
          "url": "antibytes-custom-component-e45307c.jar",
          "size": 16172,
          "sha512": "e86bcdb363b68944752851ad7f091c692f73698979c171a6f1ddb39aa75b7c8c33e32d795b0d1e2d018b73b211208dc962b8c938f2ec273f5b8ff48a0758ad38",
          "sha256": "983f717b82f51b6ef541c4c49c0ea9a18c0e7178a413eb1217f4c741a0193992",
          "sha1": "a486eaec4ed457438b3f22ff181e5fcf2068ef84",
          "md5": "c1c29d4d70512830f8c967793b528fac"
        }
      ]
    }
  ]
}
