{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/2949521/fixture-2949521.module",
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "2949521",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture.klib",
          "url": "fixture-iosarm64-2949521.klib",
          "size": 47162,
          "sha512": "73a561d7a54feded408e72a7f0c4631cff13579cfacf5b85cb296874461e830591cff6007f84901d2b2d6c6a29e7b35fa08143bf1501d4482ea8f4f523aa4ef8",
          "sha256": "466143d0eb193abcfac883309b5dc4de53d9dd88f9cf0d55ce48b211bc57c99e",
          "sha1": "3a41e6ef323b3a78e454d7da0ff9635979ade7ef",
          "md5": "e609bbc37ab05f1d4221b6dcc6342467"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-iosarm64-2949521-metadata.jar",
          "url": "fixture-iosarm64-2949521-metadata.jar",
          "size": 261,
          "sha512": "82cee95a83eb9d4443533ca7a9e5a8dff619733eb0a1029d35954445db3525c04056ac934849643b471ecb90b1da84257e0a728675187dcc0a1cd965a1157673",
          "sha256": "83267d2881b61fd09394ffbda822bd5c8cdfdbe20e8902a4b3d2cbdd4186ea31",
          "sha1": "f32485f5904262973dc3849b660eb31ec259e5bb",
          "md5": "33fa112475c2e752c4ba02949ee88b6e"
        }
      ]
    }
  ]
}
