{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/e99bb93/test-utils-e99bb93.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "e99bb93",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iossimulatorarm64-e99bb93.klib",
          "size": 14402,
          "sha512": "6ccf77678659d6aa7a19d5804f04f15e1ffbb19da6f07aa411fc20dc8fb1d25a8ae544f9b5c38b895f230349b93bab81bfaa1679d7e96de9aea56cbb9c293f6f",
          "sha256": "2842406ee09b5960ca932349a9dd9f950c7a6972f99b0664f413038235605023",
          "sha1": "f2bdb6636ad7f58af21706f085e0000c009b3b7a",
          "md5": "2653a2e2afd8371c43126d57e0d0ac8a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iossimulatorarm64-e99bb93-metadata.jar",
          "url": "test-utils-iossimulatorarm64-e99bb93-metadata.jar",
          "size": 261,
          "sha512": "0fbe1238acf9b70b140fce6b56ea53e71e419f682fe4acf5564ab83a47f14fca061e2dd580ec9b57bdbde757ee0da9bd5ba7cead572cc303ae0e4f7ba41bbeb1",
          "sha256": "57553dc253d70d68163257b7f3240a39b45490710716b82352b981e38cec3428",
          "sha1": "27fa204a0854d4ddfd1fa53dbe8a120c916272ae",
          "md5": "b77072d0b1b8d28e8a0db1f2ca9b71d0"
        }
      ]
    }
  ]
}
