{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/4f11117/test-utils-resourceloader-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-tvossimulatorarm64-4f11117.klib",
          "size": 12959,
          "sha512": "e4edff09b9074c1a8d77ce3faa6a04fc3106ce784dc518dd78e92ec4008daaa5735f5b195f3ed9a828ce12c28ddd30cf0cf540858012c9ead59457b0f74ea585",
          "sha256": "aff61896fad65cfed826ce369c425ab6674fc4fa5f5adb4a10d935c4f15af017",
          "sha1": "2db2a0152667fe748afb19b89952153048b481cd",
          "md5": "0d7d3762fe3b97807be16322c036e27d"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-tvossimulatorarm64-4f11117-metadata.jar",
          "url": "test-utils-resourceloader-tvossimulatorarm64-4f11117-metadata.jar",
          "size": 261,
          "sha512": "68aa07124f764a1f9e36af4cc384f3a0dd1ffcfd015d75d11a4a216236163405cfbe6489b4386b24744cea1b37972cb201314905ea3c96c4c07752672a8a1cb0",
          "sha256": "0efc6b0bfff5a4928e44025690eab2e49d91fe951b1b2dab9f9ae7a56cdd62c1",
          "sha1": "c48c235a8b3ff7a8a4e3abf3c4002d81bc18fd5b",
          "md5": "30ea089d68c7a9f83a3bfe811c4948f9"
        }
      ]
    }
  ]
}
