{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/f384302/test-utils-annotations-junit4-f384302.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "f384302",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-jvm-f384302.jar",
          "url": "test-utils-annotations-junit4-jvm-f384302.jar",
          "size": 10931,
          "sha512": "4f140bbe7b3156d3b10fa6f4675753cf5588762bab7b60239685383cf09efeb7526967b1dca7d09a3ea3670265b58b8da0a9dcde6fbcf8af40ecae2e8a11eb65",
          "sha256": "506faa70afd7c7eb39a406e327fcaefcf877d3934f21bfaaea0d289662b8bba0",
          "sha1": "df11f7b7dbdced2464ee6230621e8477f4ce52fd",
          "md5": "7c942e2ecb284a7500a5293db1b36a59"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-jvm-f384302.jar",
          "url": "test-utils-annotations-junit4-jvm-f384302.jar",
          "size": 10931,
          "sha512": "4f140bbe7b3156d3b10fa6f4675753cf5588762bab7b60239685383cf09efeb7526967b1dca7d09a3ea3670265b58b8da0a9dcde6fbcf8af40ecae2e8a11eb65",
          "sha256": "506faa70afd7c7eb39a406e327fcaefcf877d3934f21bfaaea0d289662b8bba0",
          "sha1": "df11f7b7dbdced2464ee6230621e8477f4ce52fd",
          "md5": "7c942e2ecb284a7500a5293db1b36a59"
        }
      ]
    }
  ]
}
