{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/f384302/test-utils-resourceloader-f384302.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "f384302",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iosarm32-f384302.klib",
          "size": 12865,
          "sha512": "5a8ac5177999f36a9f792458cedfca27ed47400614d2cf281428b18a15cdbdf32f0b91329fee953a88f5ab99f0d2c018fbde234c059918a1d083841a21d9a546",
          "sha256": "a9fe627527db48e41aa2d23e030e351eb3e5f6302fd02a862e877a3eb5e74997",
          "sha1": "b55a7ecadd5d128eb7be3ee96a4db353abe910f9",
          "md5": "ab8011c45f13c249c3c7cc1f1cc71dc0"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iosarm32-f384302-metadata.jar",
          "url": "test-utils-resourceloader-iosarm32-f384302-metadata.jar",
          "size": 261,
          "sha512": "65664b59a7e5b384379ae066e8b283d1160dace81fd452f32cb35deaa6d5d86b9fc5e40cfc4a050d9f6be4ab76a3e117c1d32625d7cb0b3650b0db6544ed0d15",
          "sha256": "3523387f12bb72033232acb4fbabe5b117f7b58d617cab070cc16a2bf0d93677",
          "sha1": "a7a10071d41f069d9757eb480a323d77dd61c0b7",
          "md5": "af851e812895d04084cf19494d9cd974"
        }
      ]
    }
  ]
}
