{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/0a268dd/test-utils-ktor-0a268dd.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "0a268dd",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-linuxx64-0a268dd.klib",
          "size": 14414,
          "sha512": "6efea066791bda2a1ce0c97ca790dce3dac5c208ba553207ca7ca1539515e9c9b50c0a2e0d2168b818141798d0ea4fb56c58cd5c9e1a1d62dfe957c7ef0666ba",
          "sha256": "3584ad86b4248fdc653ce392240fd5a61a6c1b83ce547bd8f580121c0259d0fd",
          "sha1": "b825eecac0902c5574e461de52039537323f5935",
          "md5": "0a7a9445fa035741e8172a3b70e1c9e3"
        }
      ]
    }
  ]
}
