{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "8609980",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-8609980.jar",
          "url": "antibytes-grammar-tools-8609980.jar",
          "size": 39371,
          "sha512": "768c145f103a4a94a39b8a7cccff8267c1a264ec2484d30e63ad65ba7f261b0a23a366bda31fddf3fe80f2781428e373f6e081b01b6139cb1024068ad31b4aa9",
          "sha256": "1d1e2949fb1ebde52df45f9f0194ee05b252a35760732d00af91d64b2333c9ed",
          "sha1": "725e20fee88849d58bbc5250cc0dcfe82c9ab014",
          "md5": "200d8425cc2111908998bea50a1ef1a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-8609980.jar",
          "url": "antibytes-grammar-tools-8609980.jar",
          "size": 39371,
          "sha512": "768c145f103a4a94a39b8a7cccff8267c1a264ec2484d30e63ad65ba7f261b0a23a366bda31fddf3fe80f2781428e373f6e081b01b6139cb1024068ad31b4aa9",
          "sha256": "1d1e2949fb1ebde52df45f9f0194ee05b252a35760732d00af91d64b2333c9ed",
          "sha1": "725e20fee88849d58bbc5250cc0dcfe82c9ab014",
          "md5": "200d8425cc2111908998bea50a1ef1a8"
        }
      ]
    }
  ]
}
