{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/1d9e81e/kmock-1d9e81e.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "1d9e81e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "c3e5acf"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-linuxx64-1d9e81e.klib",
          "size": 100072,
          "sha512": "61033314ceb1dcc30d85561d5bf10a58d6a7018d77d39fca312bfe33346d98da4a1b98c3362c76cefd4a0b851ba9235b2751c514a9e9737d11bf2199ca5f0e53",
          "sha256": "93aca722379b0893e6e68dad88325ab91ea9130ab6677d0a5681a33c4a9aebae",
          "sha1": "54b527d57c0c36454a5a191cac8ba7d5ec314f68",
          "md5": "bfe9123d55d72f5337323bb481a3aa0c"
        }
      ]
    }
  ]
}
