{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.settings",
    "module": "antibytes-dependency-settings",
    "version": "5cd8a47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "5cd8a47"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-5cd8a47.jar",
          "url": "antibytes-dependency-settings-5cd8a47.jar",
          "size": 78433756,
          "sha512": "f14394ad573a57fc1c7f3598118d93e9bb4a2f81ed01facbb1a60ff7540a04f35265e157d8f64e2572ceb4c49c5c7e2a06afae336e82889a000e4ce12559b56a",
          "sha256": "047893a7cdb9549045ad71884f15d249f5c0ee479dd2a0ea15e6479adcb9e14e",
          "sha1": "dc8b85c2593cd82e7069db50147f29b1473a57cf",
          "md5": "5cbed6f0f0c15054557b25cd161b94d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "5cd8a47"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-5cd8a47.jar",
          "url": "antibytes-dependency-settings-5cd8a47.jar",
          "size": 78433756,
          "sha512": "f14394ad573a57fc1c7f3598118d93e9bb4a2f81ed01facbb1a60ff7540a04f35265e157d8f64e2572ceb4c49c5c7e2a06afae336e82889a000e4ce12559b56a",
          "sha256": "047893a7cdb9549045ad71884f15d249f5c0ee479dd2a0ea15e6479adcb9e14e",
          "sha1": "dc8b85c2593cd82e7069db50147f29b1473a57cf",
          "md5": "5cbed6f0f0c15054557b25cd161b94d3"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-settings-5cd8a47.jar",
          "url": "antibytes-dependency-settings-5cd8a47.jar",
          "size": 78433756,
          "sha512": "f14394ad573a57fc1c7f3598118d93e9bb4a2f81ed01facbb1a60ff7540a04f35265e157d8f64e2572ceb4c49c5c7e2a06afae336e82889a000e4ce12559b56a",
          "sha256": "047893a7cdb9549045ad71884f15d249f5c0ee479dd2a0ea15e6479adcb9e14e",
          "sha1": "dc8b85c2593cd82e7069db50147f29b1473a57cf",
          "md5": "5cbed6f0f0c15054557b25cd161b94d3"
        }
      ]
    }
  ]
}
