{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-0.1.0.jar",
          "url": "antibytes-grammar-tools-0.1.0.jar",
          "size": 39371,
          "sha512": "db54d557dfddbaf49a0a6a4068339f91bd8d1b2345eddd6fab886ca4e910faa5d94402feb08bd82c4285d84e97acc1fe7ebd039a78d342358d6e8e2bf88e53f1",
          "sha256": "63d83fc1c2a438024aeb882eb8fe764f383842d2c8d6edb08485e24a48619bf5",
          "sha1": "ecc3e8a4a59fa08f1887f98c408ee1344992fd83",
          "md5": "23414bb8e51477301f776fb0ddf1331f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-0.1.0.jar",
          "url": "antibytes-grammar-tools-0.1.0.jar",
          "size": 39371,
          "sha512": "db54d557dfddbaf49a0a6a4068339f91bd8d1b2345eddd6fab886ca4e910faa5d94402feb08bd82c4285d84e97acc1fe7ebd039a78d342358d6e8e2bf88e53f1",
          "sha256": "63d83fc1c2a438024aeb882eb8fe764f383842d2c8d6edb08485e24a48619bf5",
          "sha1": "ecc3e8a4a59fa08f1887f98c408ee1344992fd83",
          "md5": "23414bb8e51477301f776fb0ddf1331f"
        }
      ]
    }
  ]
}
