{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/8066bd0/test-utils-coroutine-8066bd0.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "8066bd0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-tvossimulatorarm64-8066bd0.klib",
          "size": 10224,
          "sha512": "67b9afb3de4989604adcda803ac78c5263287c8dc32834364aaa494c0b191dd3daccc1ba6c4ca1710552e32c00b378d80672c00eb2f78ee0a5d05311b416a476",
          "sha256": "e5da7b7e3afc44718502718ace5081edeb450f97719752a26ce0a2c6394bad0b",
          "sha1": "1e8865e53ddb339bccd2f15be1549387a19039a4",
          "md5": "5929f0aa784f33c7e13a228aa4a83689"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-tvossimulatorarm64-8066bd0-metadata.jar",
          "url": "test-utils-coroutine-tvossimulatorarm64-8066bd0-metadata.jar",
          "size": 261,
          "sha512": "23ae31f3302a0b64714c433a0a552fe14b230dde3fa4ce91af67b0ac94ec899088442cc65f97d4fe3449daeb7767d2444575fd9ffd225eeee263bcd28de00372",
          "sha256": "37f09de99d058e06fe37b61df1abb58eec3cdf466557ce4f5b5c28a11a32d886",
          "sha1": "d0f6828b625ad3bf99abfb1777bdecfe03c93059",
          "md5": "125a47141937aeef21d57c5300c9f544"
        }
      ]
    }
  ]
}
