{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "f163e11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-metadata-f163e11-all.jar",
          "url": "test-utils-f163e11-all.jar",
          "size": 9796,
          "sha512": "daa76e2e62e1db063a439088c1bb82632444522e552035996ecd19fb73877ce2a6511c1263938cb33551e5f7b24d14400713a02a4833ef256445d58055fb587d",
          "sha256": "fc39c02f8071ce46d06584360787117c0054a836de8acc1bd3234b60e4bd7f6a",
          "sha1": "06dcde0df90d06395667588e5abc2d48ebbb0cc6",
          "md5": "c7ccb361033150900886fa5481585d04"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-f163e11.jar",
          "url": "test-utils-f163e11.jar",
          "size": 3985,
          "sha512": "5d6c2f1e15bf61d742dafe6ea9bb752f6bcb323f5514fa4dc401252ae33c25aeb637ebea39c8bbc0bcee57d424eed6c60a01dc8da0685a58b722705ee43286e9",
          "sha256": "730981e17167097ba36e744cb1e823478054b77f061eb353f8a6fe02099f50d7",
          "sha1": "0a4f7a08366eedeef5de3ad41fbfe0aefb0f8208",
          "md5": "0f71e29ec530ec924a5f18f995fc1208"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/f163e11/test-utils-android-f163e11.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "f163e11"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/f163e11/test-utils-android-f163e11.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "f163e11"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosarm64/f163e11/test-utils-iosarm64-f163e11.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosarm64",
        "version": "f163e11"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosarm64/f163e11/test-utils-iosarm64-f163e11.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosarm64",
        "version": "f163e11"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosx64/f163e11/test-utils-iosx64-f163e11.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosx64",
        "version": "f163e11"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosx64/f163e11/test-utils-iosx64-f163e11.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosx64",
        "version": "f163e11"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-js/f163e11/test-utils-js-f163e11.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-js",
        "version": "f163e11"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-js/f163e11/test-utils-js-f163e11.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-js",
        "version": "f163e11"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/f163e11/test-utils-jvm-f163e11.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "f163e11"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/f163e11/test-utils-jvm-f163e11.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "f163e11"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-linuxx64/f163e11/test-utils-linuxx64-f163e11.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-linuxx64",
        "version": "f163e11"
      }
    }
  ]
}
