{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-bridge",
    "version": "2ebcd5b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-bridge-2ebcd5b.jar",
          "url": "antibytes-dependency-bridge-2ebcd5b.jar",
          "size": 39856,
          "sha512": "122c7038eead3fa41bcfa650536cace9a4499cf3e8b11810786ec12aace69729ee4a1bc1d75b798fe1aa4781dd57d61d603728f38034e31f1d7ca3a47d4e6772",
          "sha256": "994e0143cb8adf7e5338291685fa8150fc25cb7d6a41ad71f4afda22fa36b774",
          "sha1": "faf5088a33995d7dbf78b3ef07732a090836fd53",
          "md5": "490dfc2c8eb54614e3b55192fc8daa3e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "2ebcd5b"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-bridge-2ebcd5b.jar",
          "url": "antibytes-dependency-bridge-2ebcd5b.jar",
          "size": 39856,
          "sha512": "122c7038eead3fa41bcfa650536cace9a4499cf3e8b11810786ec12aace69729ee4a1bc1d75b798fe1aa4781dd57d61d603728f38034e31f1d7ca3a47d4e6772",
          "sha256": "994e0143cb8adf7e5338291685fa8150fc25cb7d6a41ad71f4afda22fa36b774",
          "sha1": "faf5088a33995d7dbf78b3ef07732a090836fd53",
          "md5": "490dfc2c8eb54614e3b55192fc8daa3e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-bridge-2ebcd5b-javadoc.jar",
          "url": "antibytes-dependency-bridge-2ebcd5b-javadoc.jar",
          "size": 261,
          "sha512": "a2ed10554a954f8a176fad806987bd3504bd0abcf8b29d004d62c365f666387ba9566c0341b30c18b7ecbdb65a936233f2cb227b01c243211a4d137bf8e2c60f",
          "sha256": "387c6dfe3208a1bfad3a4ac80f533fa7f61122dc89e649912443ab859f5985dc",
          "sha1": "812d9475f3acc58a64b000b4d2cf7564512e33bd",
          "md5": "7fd19d1f521346995498c3c4dfef0aa1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-bridge-2ebcd5b-sources.jar",
          "url": "antibytes-dependency-bridge-2ebcd5b-sources.jar",
          "size": 5989,
          "sha512": "85fba25313c1d6984d84f0cde14837db8df154bd3873569f8a8d877e7d9fb840f15b3b6c97d05b9787672474948392406c26005d68616c0f5a355a9c3980646d",
          "sha256": "17efdc4c8d3edd041cbc065e085e1413f3abddcd5703779b85829478760a8fcf",
          "sha1": "cebb8039fb779c142e905ddf5db20a74c9fb0332",
          "md5": "9ec67b8b943d71aa74c61789fae8c5b8"
        }
      ]
    }
  ]
}
