{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/a7a030d/test-utils-fixture-a7a030d.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "a7a030d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm.jar",
          "url": "test-utils-fixture-jvm-a7a030d.jar",
          "size": 41804,
          "sha512": "781a66ae0cecf1dbb0cb43bd01c4427e4a12305e541b58c55dc363faadfc2dc735003da2f8121a913552e9b9f2d47edef43134127786e6723d5f358f3c1f7fdc",
          "sha256": "3f0ab257bf15f538f8f22c44956616012f65a5bbefc5706f9d5601675272eb50",
          "sha1": "4fc408033ac74ec35b61db920b35e2767549284d",
          "md5": "19ec91e6c8e33597a7fc70535d783b32"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm.jar",
          "url": "test-utils-fixture-jvm-a7a030d.jar",
          "size": 41804,
          "sha512": "781a66ae0cecf1dbb0cb43bd01c4427e4a12305e541b58c55dc363faadfc2dc735003da2f8121a913552e9b9f2d47edef43134127786e6723d5f358f3c1f7fdc",
          "sha256": "3f0ab257bf15f538f8f22c44956616012f65a5bbefc5706f9d5601675272eb50",
          "sha1": "4fc408033ac74ec35b61db920b35e2767549284d",
          "md5": "19ec91e6c8e33597a7fc70535d783b32"
        }
      ]
    }
  ]
}
