{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "9388cf9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-9388cf9.jar",
          "url": "antibytes-grammar-tools-9388cf9.jar",
          "size": 39410,
          "sha512": "7cdb98a64dc327111da8dc9da30961f423ace020df30d9a886997443963f2a998ec19c421471a984a6dd3386789aad5ac4c80afa2e051d388968afd9ce8feb36",
          "sha256": "84b5d92f0d220f974cff4f86aa68b26f2ebf803e34ecfb1bddf346dc27f46987",
          "sha1": "ff2c74354769009124b1daec27af107e84e640ea",
          "md5": "92c10502b177d0dafbafce902af3920c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-9388cf9.jar",
          "url": "antibytes-grammar-tools-9388cf9.jar",
          "size": 39410,
          "sha512": "7cdb98a64dc327111da8dc9da30961f423ace020df30d9a886997443963f2a998ec19c421471a984a6dd3386789aad5ac4c80afa2e051d388968afd9ce8feb36",
          "sha256": "84b5d92f0d220f974cff4f86aa68b26f2ebf803e34ecfb1bddf346dc27f46987",
          "sha1": "ff2c74354769009124b1daec27af107e84e640ea",
          "md5": "92c10502b177d0dafbafce902af3920c"
        }
      ]
    }
  ]
}
