{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "9388cf9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-9388cf9.jar",
          "url": "antibytes-dependency-9388cf9.jar",
          "size": 58507,
          "sha512": "40d93b2510e54e033c52b65f8322392c231703bbab29b279796686fa8b7a87ce2298d5d38a82e1b72f778f17ec10f3c09c8fadff4c74d3c2a591846b3d9bdbef",
          "sha256": "a524c1a2e9484c0c4d20c35a12ceaf67e12f4b56e93b2ee49046a8b44ced78df",
          "sha1": "e5c150332942f4547d40af33d40626df01d37df4",
          "md5": "117bd2e7eda7b0218e2bc902b7ca18a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "6.5.3"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.3.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "9388cf9"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-9388cf9.jar",
          "url": "antibytes-dependency-9388cf9.jar",
          "size": 58507,
          "sha512": "40d93b2510e54e033c52b65f8322392c231703bbab29b279796686fa8b7a87ce2298d5d38a82e1b72f778f17ec10f3c09c8fadff4c74d3c2a591846b3d9bdbef",
          "sha256": "a524c1a2e9484c0c4d20c35a12ceaf67e12f4b56e93b2ee49046a8b44ced78df",
          "sha1": "e5c150332942f4547d40af33d40626df01d37df4",
          "md5": "117bd2e7eda7b0218e2bc902b7ca18a8"
        }
      ]
    }
  ]
}
