{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "7456350",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-7456350.jar",
          "url": "antibytes-grammar-tools-7456350.jar",
          "size": 39373,
          "sha512": "cb667a17859c7a179b0372acd2c592cbf45de56f3891078bf392871e9801cc27cc70d6f3dd213a1f940141960ea273c228b15eb826fe7c307fe80482f9dab67f",
          "sha256": "cc71afbd2f2c7c9da8aeb54ed278558b7d2d305dc2c6257a7172d35cb88cfb46",
          "sha1": "c0b40bbbc49ab532a3aa6bf8a2c8a5e286b28860",
          "md5": "ef7112abe05d0f61fc19b54fbb9bf196"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-7456350.jar",
          "url": "antibytes-grammar-tools-7456350.jar",
          "size": 39373,
          "sha512": "cb667a17859c7a179b0372acd2c592cbf45de56f3891078bf392871e9801cc27cc70d6f3dd213a1f940141960ea273c228b15eb826fe7c307fe80482f9dab67f",
          "sha256": "cc71afbd2f2c7c9da8aeb54ed278558b7d2d305dc2c6257a7172d35cb88cfb46",
          "sha1": "c0b40bbbc49ab532a3aa6bf8a2c8a5e286b28860",
          "md5": "ef7112abe05d0f61fc19b54fbb9bf196"
        }
      ]
    }
  ]
}
