{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/f163e11/test-utils-ktor-f163e11.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "f163e11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iosarm64-f163e11.klib",
          "size": 14830,
          "sha512": "bd7406a5fca33e6df98a56161cb2582114fa2ced0580821ce46ee5d6a0134cde74ed3a178355b1496937476ebaf2a06a9ceb6b173d76160610e3f64a5c9717b1",
          "sha256": "09acb6a01ff2527865f96fef8a0b70cfe59d6a883497dd9ef0c7e468af63345f",
          "sha1": "15f0ffc3a574aa1fc69d10da1e94b0e60c673b11",
          "md5": "952a7893a3e50a89d44f3dc8de80c713"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iosarm64-f163e11-metadata.jar",
          "url": "test-utils-ktor-iosarm64-f163e11-metadata.jar",
          "size": 261,
          "sha512": "f990061966bbd66a85701a8357421e86a78abaa49fce979e684f2327cbc08207d8d47b481cd5badfdd19ce2193c879479920d2bd6867aa2871f917c2f5969fe3",
          "sha256": "0454ed445fdf565ee28087d7b35e7c5d4633f70f020042d53296ba3cbc4defbc",
          "sha1": "1ec57f96a01a242406988ea754c0fc16bfcb8974",
          "md5": "c3b7999be0a13a575c6df8da9d6ed109"
        }
      ]
    }
  ]
}
