{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "4e1c621",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-4e1c621.jar",
          "url": "antibytes-dependency-helper-4e1c621.jar",
          "size": 68558,
          "sha512": "68f14f6f6e8bfb507cd68aac8004d0d3b5d3a9f6b8cf6e101c864a886ce69bfe006c443a7b67a0346fcd1bd87e081993c1d0a484ec1f2d7835418d3ed81b6956",
          "sha256": "d905c7ed9056121f365ce7d114b8c2e875ce780817da2e173b07aa703564dfc8",
          "sha1": "aab8689a2993eda4b8732abb340c01d279f21fdd",
          "md5": "7b985918c56d1283be54fa7bd6b33f36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "4e1c621"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-4e1c621.jar",
          "url": "antibytes-dependency-helper-4e1c621.jar",
          "size": 68558,
          "sha512": "68f14f6f6e8bfb507cd68aac8004d0d3b5d3a9f6b8cf6e101c864a886ce69bfe006c443a7b67a0346fcd1bd87e081993c1d0a484ec1f2d7835418d3ed81b6956",
          "sha256": "d905c7ed9056121f365ce7d114b8c2e875ce780817da2e173b07aa703564dfc8",
          "sha1": "aab8689a2993eda4b8732abb340c01d279f21fdd",
          "md5": "7b985918c56d1283be54fa7bd6b33f36"
        }
      ]
    }
  ]
}
