{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/f384302/test-utils-ktor-f384302.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "f384302",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-watchosarm64-f384302.klib",
          "size": 15061,
          "sha512": "d91136e0ae8b936f77f4e1f5c15dc114ec73cc2fffc5d93be97eb66df334bb2d8b25ef04b17faec9d61e1c446b07a9628c5338a39474dc5867b68c0d7e416d80",
          "sha256": "d1cdb7e08a69a4ff6cd4a19eec296287510cab4fe503b9fb9e7289ee61bc3c7a",
          "sha1": "18fea3431d6a0c6c4ec22e789c11b1528a0c7589",
          "md5": "69c11fbfaf79b13ff172384dbddb08bf"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-watchosarm64-f384302-metadata.jar",
          "url": "test-utils-ktor-watchosarm64-f384302-metadata.jar",
          "size": 261,
          "sha512": "ee3866c7b226861230c666155dd9bd4356ff891827be0fb23c456ca7de99cccbd6c319122aa880f9f73e081f13ba61f16338a4f9a2b2356b5bc1230013daa11e",
          "sha256": "b1c9c63cd668b8bd5664cfc6908e5fdb0e96f2f337927a7d645d576d4a65050c",
          "sha1": "e37707e3f1b8c50e9c671dd17c0916c2557392b4",
          "md5": "1cf8639fb65c773368f73ded23477707"
        }
      ]
    }
  ]
}
