{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "a1b98b8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-a1b98b8.jar",
          "url": "antibytes-android-application-configuration-a1b98b8.jar",
          "size": 64017,
          "sha512": "9f7a80a32125d327c832303f4add3e8f1bec4995f1aa57d3398cff1169d56074bc5df20edaf329837a2a17bab4f14ec3eb810d50cba57eb0ac6d2d7230e94df9",
          "sha256": "1b255492a28bc989da610ebcc4822c4cafe7d13c9b753a3edf68665940499c4c",
          "sha1": "9cfd81407968c828a37365b59181815b80da0de1",
          "md5": "1f7a80d2777621e35679cb5fc17cf852"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "a1b98b8"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-a1b98b8.jar",
          "url": "antibytes-android-application-configuration-a1b98b8.jar",
          "size": 64017,
          "sha512": "9f7a80a32125d327c832303f4add3e8f1bec4995f1aa57d3398cff1169d56074bc5df20edaf329837a2a17bab4f14ec3eb810d50cba57eb0ac6d2d7230e94df9",
          "sha256": "1b255492a28bc989da610ebcc4822c4cafe7d13c9b753a3edf68665940499c4c",
          "sha1": "9cfd81407968c828a37365b59181815b80da0de1",
          "md5": "1f7a80d2777621e35679cb5fc17cf852"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-a1b98b8-javadoc.jar",
          "url": "antibytes-android-application-configuration-a1b98b8-javadoc.jar",
          "size": 261,
          "sha512": "da1799226b840b3d8f9f62900ac3cc23481f06889189a7c85b38b7b533671441027d8ca62161992c57cbeba930aa90c7547a1511f1ee45a827c3e465411d9450",
          "sha256": "5e5a1d5d2882624a91c0d5b60ec42d7c3206f1bbee1628d670584721f638602a",
          "sha1": "ab3e9eed4557e70891504e5e9b8c7ab2a9c8e12d",
          "md5": "2d5036b2fbc1d44fb95b77b84d760a48"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-a1b98b8-sources.jar",
          "url": "antibytes-android-application-configuration-a1b98b8-sources.jar",
          "size": 12876,
          "sha512": "5c82bbba39e3f7e65e8e3d51ef3b94c2736e6c9f8141972447a10b77d975b17dc3b13a1ab8a89a211f888644b07bf0c5d8ce498530fad835ce1d4a9e426074ab",
          "sha256": "e30686f59676c1652ea957250dd7370592b98423648c8de952a643093f7e6f6d",
          "sha1": "daa508b58ab96d30c1b3bff16745c4df173ea482",
          "md5": "88c14db9c5a128c8bff57929a78d555a"
        }
      ]
    }
  ]
}
