{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "597ee0b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-ktor-metadata-all.jar",
          "url": "test-utils-ktor-597ee0b-all.jar",
          "size": 5014,
          "sha512": "faa2caa8df62f43b9b0f9ed7c607dd53080d71d97a84286bb282f1afd06fb4c22e03d946fddeba219485b3766b6b64c83afe64c4f25f433b13793c31dd2833ee",
          "sha256": "16dc04be4c4354092e28f47f4f4fb6e61beb716138ea4529e1d80d06c72b10ee",
          "sha1": "41c54ffbec49caa459150d188e1c790587c8ad96",
          "md5": "cdf9562d8c61467c8cb354a049b65080"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-ktor.jar",
          "url": "test-utils-ktor-597ee0b.jar",
          "size": 2522,
          "sha512": "3933536ee1a690cdcc1b63a7ad64404422f3ec03f06f229e37021fb42c1c42cbc6e1ad259f7952018a91baedbfc88e3bccd2cc8fdaef8747bb1fad05b647f66b",
          "sha256": "2aa5d616875a3cce3aed3cba2587aaa6766b13f22ca7050e6af3386a6976c254",
          "sha1": "8abc09dd0434fd0b805277fb00838bc7a4bc8c95",
          "md5": "01235fc51c0b138bb7be956a3b099a70"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/597ee0b/test-utils-ktor-android-597ee0b.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "597ee0b"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/597ee0b/test-utils-ktor-android-597ee0b.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "597ee0b"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-ktor-js/597ee0b/test-utils-ktor-js-597ee0b.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-js",
        "version": "597ee0b"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-ktor-js/597ee0b/test-utils-ktor-js-597ee0b.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-js",
        "version": "597ee0b"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/597ee0b/test-utils-ktor-jvm-597ee0b.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "597ee0b"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/597ee0b/test-utils-ktor-jvm-597ee0b.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "597ee0b"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-linuxx64/597ee0b/test-utils-ktor-linuxx64-597ee0b.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-linuxx64",
        "version": "597ee0b"
      }
    }
  ]
}
