{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/c1aadb7/kmock-c1aadb7.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "c1aadb7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-c1aadb7.aar",
          "size": 226915,
          "sha512": "e34db7fc1a2f4ddf8b577f4eed690038b5da756ed3cfe0be4c0440d6a09db15f2ba496a8680c1c6296315450d66e3566e2c35ae82a4c40d61de0906629bc7a0a",
          "sha256": "31eaac18f57620f8dceca0eb9821e9d14c67aebf42a9443efb24fa33e66c03ff",
          "sha1": "3ebf4fc17e152df95aa3327006ee9a585a535c5c",
          "md5": "a791c20b2e1824976d7ea42afe12f3ef"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-c1aadb7.aar",
          "size": 226915,
          "sha512": "e34db7fc1a2f4ddf8b577f4eed690038b5da756ed3cfe0be4c0440d6a09db15f2ba496a8680c1c6296315450d66e3566e2c35ae82a4c40d61de0906629bc7a0a",
          "sha256": "31eaac18f57620f8dceca0eb9821e9d14c67aebf42a9443efb24fa33e66c03ff",
          "sha1": "3ebf4fc17e152df95aa3327006ee9a585a535c5c",
          "md5": "a791c20b2e1824976d7ea42afe12f3ef"
        }
      ]
    }
  ]
}
