{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-SNAPSHOT/ktx-datetime-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iossimulatorarm64-0.4.0-SNAPSHOT.klib",
          "size": 34735,
          "sha512": "7cfd92b026de0784530e54ec149bc4151bed98cd358e27c88a1605cb1a39f879fcbefb6dadd1e83fbde39654020f7c341906bd5c92618919b7cf936656ed5d5f",
          "sha256": "6016ede928cb105c7982af27ae9f49bbaacd82b78c002ef08d130d1eda03b380",
          "sha1": "e7d253954bc0e09e4897ccc551a850e9e788238d",
          "md5": "ba43fcbef624e7375b94f6ec0fa39365"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iossimulatorarm64-0.4.0-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iossimulatorarm64-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b60b52eb50a5116d9d88b2454ba35107605e4ab9f6a1256245b68b2573b7dbfabdba4a0ffa197b8025d41a28029897a038ece569e2bdf1d8aa46b827c9defd9a",
          "sha256": "5a060b628c14bd30f29375a0f8d6597dfcf9d0a3165603425dbf8a4f1a7789c9",
          "sha1": "d07c770bc0145174ef4d7a4c85e1881a5fe2f834",
          "md5": "2112f46fec5a4785ac59f177c0f80bef"
        }
      ]
    }
  ]
}
