{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/4f11117/test-utils-ktor-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-tvossimulatorarm64-4f11117.klib",
          "size": 15121,
          "sha512": "2f5bd7683dc964aac7148995482b8c6f09c6d79e59b395a6d35337c2d0f16d9ece788ba9505790ef714f4fd9e2d1c5c018e3a975cce2f6ff018053878d390f99",
          "sha256": "249bf53a465116948e17a1187f9d7c4c61dd616e69dea857c14dcd397a5c81c5",
          "sha1": "39bb869db1da5eddd7dd6ef8224e55d5590261a4",
          "md5": "4ef00b871b3b2fffd3796ace53eae6b9"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-tvossimulatorarm64-4f11117-metadata.jar",
          "url": "test-utils-ktor-tvossimulatorarm64-4f11117-metadata.jar",
          "size": 261,
          "sha512": "57159147fdffeb9dde3822c3ab8378d88c3219569f9c2039708103471a7deed4abfd20bc3a5f136ae5ecaa679b145f845b1c15fd286d4642fd9c8c575c563384",
          "sha256": "538417aab31ac931c22e749db3df8d589d898bf9da8fa017e05e1bf278efc4c7",
          "sha1": "d5a87da25dc899d17d7e8abb2c2bcde32cd0783f",
          "md5": "cbf0a8704fccddf5811a8fa48eccddcc"
        }
      ]
    }
  ]
}
