{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.2.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.2.0-rc01-SNAPSHOT.jar",
          "url": "kmock-processor-0.2.0-rc01-SNAPSHOT.jar",
          "size": 383668,
          "sha512": "5a4da91be4eb63e278dd27bec6375f8b7e42e68ac54b85f356e4f2e832bb1207deaf7d5bf134107de1c4c97221d0086b3d782a38b87fb0152945dd288867f5fe",
          "sha256": "5f47239fef391775070d87e7e0c711dde3ed2e3a8daf7faad6e8db34ecd950cc",
          "sha1": "bb17b4018ad31d80c7a10cab9f037266fd9d43fc",
          "md5": "e7b8f8afc0da626bfc96dfa123eacf0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.2.0-rc01-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.2.0-rc01-SNAPSHOT.jar",
          "url": "kmock-processor-0.2.0-rc01-SNAPSHOT.jar",
          "size": 383668,
          "sha512": "5a4da91be4eb63e278dd27bec6375f8b7e42e68ac54b85f356e4f2e832bb1207deaf7d5bf134107de1c4c97221d0086b3d782a38b87fb0152945dd288867f5fe",
          "sha256": "5f47239fef391775070d87e7e0c711dde3ed2e3a8daf7faad6e8db34ecd950cc",
          "sha1": "bb17b4018ad31d80c7a10cab9f037266fd9d43fc",
          "md5": "e7b8f8afc0da626bfc96dfa123eacf0c"
        }
      ]
    }
  ]
}
