{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.2.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.2.0-rc01-SNAPSHOT.jar",
          "url": "kmock-processor-0.2.0-rc01-SNAPSHOT.jar",
          "size": 356037,
          "sha512": "619bd427f13722af59f8f46bd21b34123c755a5a5f7815a6c0fc0e59e0bf06ac432df1bd8280b38e286b77421dfe003de12b15cdadedc8beeff5b57d10de6ce0",
          "sha256": "de7950c981ed4e0eb5f6c2d6b16e237ce0625cf47562327d8c46e4495b1037ee",
          "sha1": "1de493e9fb0ec34338ab2e882cdf23e72ead7d7c",
          "md5": "ac829ebdf054ef55b53d0be45d375b13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.2.0-rc01-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.2.0-rc01-SNAPSHOT.jar",
          "url": "kmock-processor-0.2.0-rc01-SNAPSHOT.jar",
          "size": 356037,
          "sha512": "619bd427f13722af59f8f46bd21b34123c755a5a5f7815a6c0fc0e59e0bf06ac432df1bd8280b38e286b77421dfe003de12b15cdadedc8beeff5b57d10de6ce0",
          "sha256": "de7950c981ed4e0eb5f6c2d6b16e237ce0625cf47562327d8c46e4495b1037ee",
          "sha1": "1de493e9fb0ec34338ab2e882cdf23e72ead7d7c",
          "md5": "ac829ebdf054ef55b53d0be45d375b13"
        }
      ]
    }
  ]
}
