{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/25e268f/test-utils-coroutine-25e268f.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "25e268f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosarm64-25e268f.klib",
          "size": 10123,
          "sha512": "10c9db4f0c9b4635abbaaff580006a3f64bf8194ac79491fc55f3b844fca94679282b33c38e59715b35dd2b35cb9a3af3f1ebda5a4980f0bd78ec2cfc5fca7dd",
          "sha256": "72564496fea31c8d738cff0910d76580b18684e25e71aa3277d7e20ad4334d2b",
          "sha1": "e1f1ffd87962052fd9a1f50fee397285144fcaeb",
          "md5": "dc1e56df809dc42d2927a364000c8274"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosarm64-25e268f-metadata.jar",
          "url": "test-utils-coroutine-iosarm64-25e268f-metadata.jar",
          "size": 261,
          "sha512": "b426de8706b7c8bac4b6ab2e97e971a2fdaf41ef54a5c5a1101d60ae1f029b9c32c805a6ec2aebd5ff89804eb58552bc232ced8d686fa1b89903844dc475dc91",
          "sha256": "3dc04f71da3be6f0d711798fa79fe8555a0a6e1cde5add80e0048e2843391858",
          "sha1": "86d334bb00705a906d9c9e7f58a23a3cd666d553",
          "md5": "e4ff7a1957021fefc2a56124a502eff7"
        }
      ]
    }
  ]
}
