{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/dbba7bb/test-utils-annotations-junit5-dbba7bb.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "dbba7bb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-iosarm32-dbba7bb.klib",
          "size": 7049,
          "sha512": "a6dd9a3a567969fd9905cf0dc9f50114fc03c7a85b8f938d941aa9665506cfc3db3835ae1a64349083578a4cb8e1de347ad7a490a65b3894a93dcf9bd2e8083e",
          "sha256": "ca0e705b9ff325a7b3e27229d3ab104d7c6721214f280317d76ed3103f0dc2e1",
          "sha1": "367df46f17bb68f601df4927fd31b10bc95274b8",
          "md5": "5ed3b3657b59e066ccc9e2a8a6934bed"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-iosarm32-dbba7bb-metadata.jar",
          "url": "test-utils-annotations-junit5-iosarm32-dbba7bb-metadata.jar",
          "size": 261,
          "sha512": "907de237434240123de45d6ec8984804b506ea46ba9b2146f1ed4a7f59fa632078ca84dd90135924206ccd0f7b919813f076f6df61c30d70c2d68d8919283df5",
          "sha256": "1ac7c6a7e8dbadcc143a2f6ecaafa604a33905bdebe935c176c06a8133c9e7d7",
          "sha1": "18d11d1e13f2177b7ff20c2eeba9a8d9aaa5aaa1",
          "md5": "9f1eaf70a24b129ce95aa58f17b5a1d0"
        }
      ]
    }
  ]
}
