{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/7008207/test-utils-fixture-7008207.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "7008207",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture.klib",
          "url": "test-utils-fixture-iosx64-7008207.klib",
          "size": 32815,
          "sha512": "4fe06d3c62af18070a7cfa5a583d433e3139001bdfee0634759f2173eef59dbdcfeb92cf73874b43fddc05fe0aba5afdd460e8264c26cc9e6345b80bbb02bb16",
          "sha256": "eb9ece9e15ceac3a88e4f105c9b1fe90c496ca0ccc30b7dbc1c80b9768f44505",
          "sha1": "75389e64bb69be17aca362cd9ffd023a84b76238",
          "md5": "fb8e6af45c8838c679174c6b903aa42f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-iosx64-7008207-metadata.jar",
          "url": "test-utils-fixture-iosx64-7008207-metadata.jar",
          "size": 261,
          "sha512": "0083379723c58848fa28a6918f508a48ef0f0f50800c3a8d9d7792ede0ca694b3aecc0cde043c4fb3b6d56f3fb9bbf35753ec45fc3a637ac9d1d514e9c311153",
          "sha256": "acd4ccb13e44caf221fe24a092e72587bca34334fa3213775c13d6110c403651",
          "sha1": "d71ec7de2300a2d9b746bdc4a6132818d9715cf8",
          "md5": "096b8229a3c9a9cb65ccc47aadbdd4cc"
        }
      ]
    }
  ]
}
