{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "d50fcae",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "d50fcae"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-d50fcae.jar",
          "url": "antibytes-mkdocs-d50fcae.jar",
          "size": 11930,
          "sha512": "2bf8227a822ba548b7106b06011c6b31d494e8a0264fb254f20e05e89ff9810ac4505e44e61a5ebc4dc4e93ce51dd2ca7f2b9ed13c50f1c94c761f88576261f2",
          "sha256": "4973df6f4db26b268e2d50974b73c24635b04a289a38839ba5a6075ef78b9310",
          "sha1": "b10ccfbdda1a3f5f4bbfbb2b7f68de7be682a9ef",
          "md5": "f124905168b3056f38268d250fe451f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "d50fcae"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "d50fcae"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-d50fcae.jar",
          "url": "antibytes-mkdocs-d50fcae.jar",
          "size": 11930,
          "sha512": "2bf8227a822ba548b7106b06011c6b31d494e8a0264fb254f20e05e89ff9810ac4505e44e61a5ebc4dc4e93ce51dd2ca7f2b9ed13c50f1c94c761f88576261f2",
          "sha256": "4973df6f4db26b268e2d50974b73c24635b04a289a38839ba5a6075ef78b9310",
          "sha1": "b10ccfbdda1a3f5f4bbfbb2b7f68de7be682a9ef",
          "md5": "f124905168b3056f38268d250fe451f6"
        }
      ]
    }
  ]
}
