{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/3948768/test-utils-3948768.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "3948768",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosx64-3948768.klib",
          "size": 14297,
          "sha512": "b2a60f82d7d49e65182861281bac176425ea6cd314ea6d5734aaa89001fae3876106ae1b1d3fa36318b1cd60a2139736611e4bb12fecab89bdf692cdb8b541a5",
          "sha256": "c8d56e34fbef56e6e988e17cf2efe0223f8ab9966497b527415b25eb7924e0f3",
          "sha1": "71413c7535c784cd5c63450f6a50c7832aee5809",
          "md5": "53dbe616f8bc3fdb80fb577fac10a62c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosx64-3948768-metadata.jar",
          "url": "test-utils-iosx64-3948768-metadata.jar",
          "size": 261,
          "sha512": "0ed258bdd845e436ded8abd1e42b50f84626b42724ae790e2a7ce26e6d1b960cfda4fe7d102d70f0fc04101f5cbfd36e177525477d2703cc868a5e8f7e1c7db3",
          "sha256": "26db2741f05515899b0869896e8bc7251c94fa7949a952efb941a45ba967fb73",
          "sha1": "1264e97feecb95b76ab0dad63e80be2189b4c326",
          "md5": "0c44108f63b1a7ab0731773c03e662b1"
        }
      ]
    }
  ]
}
