{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "d8e1636",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-d8e1636.jar",
          "url": "antibytes-coverage-d8e1636.jar",
          "size": 128053,
          "sha512": "1fca53d28836ba8ef2b8efdb335761bf5fc072fc1c20a9a088571a0fb1e9be23c573d5892c52fbe3dd465143e56c9efd6e95075780b300507dff0f5d1dcd8975",
          "sha256": "ac619697b548e374849d9ce54d665a43cf342d4e5d25b95a2043a431c942c43c",
          "sha1": "844e1961d5bb30c6a629759a872bce959b68f26a",
          "md5": "fb2ef46ede48e3616b8b4a0379a96128"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-d8e1636.jar",
          "url": "antibytes-coverage-d8e1636.jar",
          "size": 128053,
          "sha512": "1fca53d28836ba8ef2b8efdb335761bf5fc072fc1c20a9a088571a0fb1e9be23c573d5892c52fbe3dd465143e56c9efd6e95075780b300507dff0f5d1dcd8975",
          "sha256": "ac619697b548e374849d9ce54d665a43cf342d4e5d25b95a2043a431c942c43c",
          "sha1": "844e1961d5bb30c6a629759a872bce959b68f26a",
          "md5": "fb2ef46ede48e3616b8b4a0379a96128"
        }
      ]
    }
  ]
}
