{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "80c1464",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-80c1464.jar",
          "url": "antibytes-gradle-test-utils-80c1464.jar",
          "size": 15105,
          "sha512": "50b82cb06c1f088ad53c9d355192aeabddcc16b36260a7254f81cb4900928b5a93d44e9c3f5c485ea322f263abfcf1dff7d8423be84ef386e432295c690c8830",
          "sha256": "7fde64c879debe9b82e685d9ca4e89570f6c7b7c8bf61766ee18c5608d12c31c",
          "sha1": "f25cb477fa74d2b9cacfce0906b0dcaf51ca44bd",
          "md5": "350014d6821f6267c663457e0c5cea18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-80c1464.jar",
          "url": "antibytes-gradle-test-utils-80c1464.jar",
          "size": 15105,
          "sha512": "50b82cb06c1f088ad53c9d355192aeabddcc16b36260a7254f81cb4900928b5a93d44e9c3f5c485ea322f263abfcf1dff7d8423be84ef386e432295c690c8830",
          "sha256": "7fde64c879debe9b82e685d9ca4e89570f6c7b7c8bf61766ee18c5608d12c31c",
          "sha1": "f25cb477fa74d2b9cacfce0906b0dcaf51ca44bd",
          "md5": "350014d6821f6267c663457e0c5cea18"
        }
      ]
    }
  ]
}
