{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/c926cf7/fixture-c926cf7.module",
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "c926cf7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-js-c926cf7.klib",
          "url": "fixture-js-c926cf7.klib",
          "size": 54398,
          "sha512": "c10015ef4e3fcaf7a29c62b05b9b4a84e7cc732f8897c8d224a8411ea2c612bcfbc6c179346dcdc3c31fc376d86496f8b4e6250dd3919477c774d7794e648286",
          "sha256": "53e7c6b278053c1249f307c67efd010fc3e9f3fb5e70198ab2210f1a3e6f0912",
          "sha1": "770ec1e15d5e4a29f884b78bf9577c04376499fc",
          "md5": "0d6bbe15aa4b61326b5800a6b1f05839"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-js-c926cf7.klib",
          "url": "fixture-js-c926cf7.klib",
          "size": 54398,
          "sha512": "c10015ef4e3fcaf7a29c62b05b9b4a84e7cc732f8897c8d224a8411ea2c612bcfbc6c179346dcdc3c31fc376d86496f8b4e6250dd3919477c774d7794e648286",
          "sha256": "53e7c6b278053c1249f307c67efd010fc3e9f3fb5e70198ab2210f1a3e6f0912",
          "sha1": "770ec1e15d5e4a29f884b78bf9577c04376499fc",
          "md5": "0d6bbe15aa4b61326b5800a6b1f05839"
        }
      ]
    }
  ]
}
