{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "41c21f2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-41c21f2.jar",
          "url": "antibytes-configuration-41c21f2.jar",
          "size": 59750,
          "sha512": "41159ff9bc390eecf5b9e560d29726ae89a44d5153bdfbf96164c93d893c54c5b0a7299b1b2187bc5e0011c10910c5ef4fadb5616f72b91ac9d8837ce2fb0fb4",
          "sha256": "6a27bbb755685a19e35eaa4726e97982c556a0f282ad7e142f6e7ae8f66392bf",
          "sha1": "922c37e413935467f82ac69eec666aee8dcb9e6e",
          "md5": "fd0020e4372ebe31a3095a6acf429538"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "41c21f2"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-41c21f2.jar",
          "url": "antibytes-configuration-41c21f2.jar",
          "size": 59750,
          "sha512": "41159ff9bc390eecf5b9e560d29726ae89a44d5153bdfbf96164c93d893c54c5b0a7299b1b2187bc5e0011c10910c5ef4fadb5616f72b91ac9d8837ce2fb0fb4",
          "sha256": "6a27bbb755685a19e35eaa4726e97982c556a0f282ad7e142f6e7ae8f66392bf",
          "sha1": "922c37e413935467f82ac69eec666aee8dcb9e6e",
          "md5": "fd0020e4372ebe31a3095a6acf429538"
        }
      ]
    }
  ]
}
