{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.1.0-SNAPSHOT/core-0.1.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.1.0-SNAPSHOT.klib",
          "size": 50835,
          "sha512": "c77e6bd66431abfd303a4f481af99f8e606068df17bc3989fcbae900f4255da4a16d692da719d748640409377f2c0191a4ca09033d837187830ecd815c66dc3d",
          "sha256": "3e5b638dc8a49f74f748a26c3e2af4a0168a3dad580cfdb84b0e773f18a9b66a",
          "sha1": "20d835c13d30da617a16712f626314302ca60ec7",
          "md5": "09b7918c6898d900bc2899ac3731e730"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.1.0-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.1.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "fa8909d7bda39c064f1c854d3e1396ac0a62ecbb7b889b5c757b7f1bb4cc68226cf8d0f839d1e2fd70af35550d1791aa06d671c7072f9a491df87b923dc58a92",
          "sha256": "6fcdae4d576dbe653dfeede957313ef0314fb002d052c0b3bb343dc08c86263e",
          "sha1": "8ac42174e4c0e5fbcd5662cbdebfc4d87ebe4fae",
          "md5": "160daf23cc16e975555921ff4b31d049"
        }
      ]
    }
  ]
}
