{
  "formatVersion": "1.1",
  "component": {
    "url": "../../banana-i18n/7973915/banana-i18n-7973915.module",
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "7973915",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "banana-i18n-release.aar",
          "url": "banana-i18n-android-7973915.aar",
          "size": 79477,
          "sha512": "43fa82fd824b66a4e4baa5dc33bfdfb56ec6c81fdc65fe0db6d0c28bf7cfdf1053a56dbaf4f8fccc0c4711dba486c62145c9854c82389ac9382b993e0473156a",
          "sha256": "f7d0169c8c62306fc11334f51166986c590d236c24c49375fe84f3314cf3a987",
          "sha1": "595c38aee645129af0dc8e0dce9343c6d679da23",
          "md5": "66cff38d7039ff1f85b2f0d2cb6f1883"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "banana-i18n-release.aar",
          "url": "banana-i18n-android-7973915.aar",
          "size": 79477,
          "sha512": "43fa82fd824b66a4e4baa5dc33bfdfb56ec6c81fdc65fe0db6d0c28bf7cfdf1053a56dbaf4f8fccc0c4711dba486c62145c9854c82389ac9382b993e0473156a",
          "sha256": "f7d0169c8c62306fc11334f51166986c590d236c24c49375fe84f3314cf3a987",
          "sha1": "595c38aee645129af0dc8e0dce9343c6d679da23",
          "md5": "66cff38d7039ff1f85b2f0d2cb6f1883"
        }
      ]
    }
  ]
}
