{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "10714ef",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-10714ef.jar",
          "url": "kmock-gradle-10714ef.jar",
          "size": 49792,
          "sha512": "59658809f7a05b5a0906a0c511af05e8730d88e9ffacdc02f4e9bd35822343f17fe0164fa4b6dd6402de6fbf934629d50588532543a339a34bb2339a0168fa73",
          "sha256": "ef55f3eb67665b227779ac1b47c8fe545e44adbac5bbddf5de2e82924593dc44",
          "sha1": "00e623501aa5aa449f8a1862d5a4bd51b2296a23",
          "md5": "1df483bde9c297f03d3401b3d2a2d548"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-10714ef.jar",
          "url": "kmock-gradle-10714ef.jar",
          "size": 49792,
          "sha512": "59658809f7a05b5a0906a0c511af05e8730d88e9ffacdc02f4e9bd35822343f17fe0164fa4b6dd6402de6fbf934629d50588532543a339a34bb2339a0168fa73",
          "sha256": "ef55f3eb67665b227779ac1b47c8fe545e44adbac5bbddf5de2e82924593dc44",
          "sha1": "00e623501aa5aa449f8a1862d5a4bd51b2296a23",
          "md5": "1df483bde9c297f03d3401b3d2a2d548"
        }
      ]
    }
  ]
}
