{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "fefa0c6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-fefa0c6.jar",
          "url": "antibytes-grammar-tools-fefa0c6.jar",
          "size": 39373,
          "sha512": "07dc1b5a1d0a6e731b6d3fc7302c6e54b85f35f14338036d8f18488f15500f90fd25db1ce281aa4334ef847063d2b2830f8ee99873554b21ebe88559e02877c3",
          "sha256": "87d5f19f950381bbdc166c9ea819b0398ab7f515e9e246c3a1097c4d26c97a0d",
          "sha1": "faa10da12464e26d2a9da9af48a8685aaaabc800",
          "md5": "96fdbc8a7661e392a1421a8c7528c1f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-fefa0c6.jar",
          "url": "antibytes-grammar-tools-fefa0c6.jar",
          "size": 39373,
          "sha512": "07dc1b5a1d0a6e731b6d3fc7302c6e54b85f35f14338036d8f18488f15500f90fd25db1ce281aa4334ef847063d2b2830f8ee99873554b21ebe88559e02877c3",
          "sha256": "87d5f19f950381bbdc166c9ea819b0398ab7f515e9e246c3a1097c4d26c97a0d",
          "sha1": "faa10da12464e26d2a9da9af48a8685aaaabc800",
          "md5": "96fdbc8a7661e392a1421a8c7528c1f6"
        }
      ]
    }
  ]
}
