{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.coverage",
    "module": "antibytes-coverage",
    "version": "8419fcc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-8419fcc.jar",
          "url": "antibytes-coverage-8419fcc.jar",
          "size": 146046,
          "sha512": "0ab485ae1bca27da4b5fa27e92bd02411c05054f8d073328ffeda510875ae53957f86cba3b77d1e510ca327b1adddb5d421ac263aacfa8ef5699ce4d0bc8d49c",
          "sha256": "2cf0481e599699f322eee3013f69ef88c67ce831575f76c1421fe89d6244bdf5",
          "sha1": "6f775993af264feb204b7c104d96236c55d64d1d",
          "md5": "d9fe4a0a9054ca5d1adc9441afada81c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "8419fcc"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-8419fcc.jar",
          "url": "antibytes-coverage-8419fcc.jar",
          "size": 146046,
          "sha512": "0ab485ae1bca27da4b5fa27e92bd02411c05054f8d073328ffeda510875ae53957f86cba3b77d1e510ca327b1adddb5d421ac263aacfa8ef5699ce4d0bc8d49c",
          "sha256": "2cf0481e599699f322eee3013f69ef88c67ce831575f76c1421fe89d6244bdf5",
          "sha1": "6f775993af264feb204b7c104d96236c55d64d1d",
          "md5": "d9fe4a0a9054ca5d1adc9441afada81c"
        }
      ]
    }
  ]
}
