{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/56c4547/test-utils-coroutine-56c4547.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "56c4547",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-macosx64-56c4547.klib",
          "size": 10130,
          "sha512": "5a6ab194b6c3284be8ad1e4f57767f5c2a525e067c4dfdf6b494bda61ad281a89049559ab581d486e23a1aa2382193effffb2e5af59d56290f56799762431480",
          "sha256": "c6b37ecc31cf890ec079f7b59f41d7c66aeec4dfad2d536ef0b9c1707845395a",
          "sha1": "c3db072fdbde7d1876815c54816d2507a0bdcaaf",
          "md5": "d979b6dc2d9c46e3ea79981ce3e7b7d2"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-macosx64-56c4547-metadata.jar",
          "url": "test-utils-coroutine-macosx64-56c4547-metadata.jar",
          "size": 261,
          "sha512": "b04ffd97bada3756a1797e7f86db3effa780680dd8753d31a2cc564dde640ea8cd03ed1f37327ca3fe17fe13bba3b5ef89f420b3aadb6aa892a009400b14d4b4",
          "sha256": "777f0c9b6fb006ef549cf4467d457c73cade8948ca832ae12f5d4e9ab401f7e1",
          "sha1": "5004d353aa7bafca597a2237d4970485ea43e3b5",
          "md5": "73e27b1f7739018d7c72340ec9992a52"
        }
      ]
    }
  ]
}
