{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "ae101dc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-ae101dc.jar",
          "url": "antibytes-versioning-ae101dc.jar",
          "size": 24286,
          "sha512": "5dc5ba1572f3c50a5d10a33579b759c6ab9cca633358544224772c377b9e9695a7eb4abe6db4456514f9b32137d7299e1850148743d2c2aa5d8650ddf696f14e",
          "sha256": "a9c69cecb33ebdcfb8fdf7b1af454ab3a3e36e8d8da768d89d4f45912cee96e0",
          "sha1": "4b530962b4f8c9f17f62b6398c7b5a3d972f693e",
          "md5": "a62a8ce589b5dbf4c61bc8e14386e967"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-ae101dc.jar",
          "url": "antibytes-versioning-ae101dc.jar",
          "size": 24286,
          "sha512": "5dc5ba1572f3c50a5d10a33579b759c6ab9cca633358544224772c377b9e9695a7eb4abe6db4456514f9b32137d7299e1850148743d2c2aa5d8650ddf696f14e",
          "sha256": "a9c69cecb33ebdcfb8fdf7b1af454ab3a3e36e8d8da768d89d4f45912cee96e0",
          "sha1": "4b530962b4f8c9f17f62b6398c7b5a3d972f693e",
          "md5": "a62a8ce589b5dbf4c61bc8e14386e967"
        }
      ]
    }
  ]
}
