{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc07-SNAPSHOT/kmock-0.3.0-rc07-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc07-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-tvosx64-0.3.0-rc07-SNAPSHOT.klib",
          "size": 203005,
          "sha512": "31123bfb0f561642ebd46d42f6091a46966a859c2bc11f90a89dc85163dea9fe70484303aa691f43d3bebd16c81383a72796f18925927763c54516a82221cbb7",
          "sha256": "1b31ee75427012aa16729fcfb7ad49c8fa0c21ac3055a2e452bb50dfd0f708a6",
          "sha1": "a2052998ba9ef8ec02bfe46d22d98fc3379f9bb7",
          "md5": "a0ac4fb35982e1096b30ff00a6551425"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-tvosx64-0.3.0-rc07-SNAPSHOT-metadata.jar",
          "url": "kmock-tvosx64-0.3.0-rc07-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "cb969b07651ec918a1d211b354f4c3bd783ecd469fea1c09375f3a9e9a2e8ab38dcafb1d189d25e9b9e24f0943e07831098d7909804e6b94a9ad09d098ea8008",
          "sha256": "ead481fca1b300e4ae11b45394ebc851272add41fb57ce266512aaf87bed753c",
          "sha1": "9b7b513d50120af86a7a4ec9cc8b3b39c4e4a98d",
          "md5": "c234151e4044627b59cd6344f0d21661"
        }
      ]
    }
  ]
}
