{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "99d57d1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-99d57d1.jar",
          "url": "antibytes-android-application-configuration-99d57d1.jar",
          "size": 63996,
          "sha512": "c729af4227b05c2dc12410f4a77fbbad1a694b063ed6d934b68ebcc5fddd579343a579af128da27f45cca54a675a3a45a406da4535a7ae0a66ef7e2b5a2f8fd1",
          "sha256": "ebbf01df29d09e0aa07b27c8a7342c802eb9df011382c29a813e14a3b5d6196c",
          "sha1": "1903464133bed63b42de9c2485a5d9a5fac4b3f5",
          "md5": "92ef99220be7a5279259497f9c77b119"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "99d57d1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-99d57d1.jar",
          "url": "antibytes-android-application-configuration-99d57d1.jar",
          "size": 63996,
          "sha512": "c729af4227b05c2dc12410f4a77fbbad1a694b063ed6d934b68ebcc5fddd579343a579af128da27f45cca54a675a3a45a406da4535a7ae0a66ef7e2b5a2f8fd1",
          "sha256": "ebbf01df29d09e0aa07b27c8a7342c802eb9df011382c29a813e14a3b5d6196c",
          "sha1": "1903464133bed63b42de9c2485a5d9a5fac4b3f5",
          "md5": "92ef99220be7a5279259497f9c77b119"
        }
      ]
    }
  ]
}
