{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/7ef26b1/test-utils-fixture-7ef26b1.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "7ef26b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm.jar",
          "url": "test-utils-fixture-jvm-7ef26b1.jar",
          "size": 41196,
          "sha512": "2fdb2d4746a7716184f51f53f7b97a2427137f391f6eb87d4af8f829c25114cb5c52179482fe28f943cad77ae002ca3a5789b29a1661b2c20fdca00ec162bdf8",
          "sha256": "4e6aecaf003aefa9e9ac693658dfbac6996bfa757455a2453b0873d19ff7b580",
          "sha1": "608157d88ae23c877276c166bafb896cb6f448de",
          "md5": "f327e6ef172064e51a0a59fb392bf88d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm.jar",
          "url": "test-utils-fixture-jvm-7ef26b1.jar",
          "size": 41196,
          "sha512": "2fdb2d4746a7716184f51f53f7b97a2427137f391f6eb87d4af8f829c25114cb5c52179482fe28f943cad77ae002ca3a5789b29a1661b2c20fdca00ec162bdf8",
          "sha256": "4e6aecaf003aefa9e9ac693658dfbac6996bfa757455a2453b0873d19ff7b580",
          "sha1": "608157d88ae23c877276c166bafb896cb6f448de",
          "md5": "f327e6ef172064e51a0a59fb392bf88d"
        }
      ]
    }
  ]
}
