{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/8066bd0/test-utils-annotations-junit4-8066bd0.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "8066bd0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-watchosx64-8066bd0.klib",
          "size": 11372,
          "sha512": "b527b53e533ee39fcac8e8721a0d7dbec16101daaf26675a65690433d8d24d173b72cf7df711477d613d16906580151033b7767612729f473dee2ae0a9df6480",
          "sha256": "e67b7755a4c73a82cf3031b0c6c89f7e79be9db48e6c449e95bff337672d9255",
          "sha1": "5e82811f7e22758f2ff0c06526766ce4461c967e",
          "md5": "b3516db1495328659f94e0245473bfa4"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-watchosx64-8066bd0-metadata.jar",
          "url": "test-utils-annotations-junit4-watchosx64-8066bd0-metadata.jar",
          "size": 261,
          "sha512": "653c92591cef524dd9cbd3d9e4361166a8401aa67005d2cfbd5d72f9de78b949310d9f4226d6bd50a4eed229d20a10a1d3c65ae0356d59c20f7c410873590555",
          "sha256": "a45911cbb72c3e28613cd2c58dbf5e07f07aa48f5caa2b2d1d63db7acece66cd",
          "sha1": "501d349a7120918a649fcc4c76a8c2923cdf8764",
          "md5": "0a6245c87c09ed4b4d91445d01aaaea3"
        }
      ]
    }
  ]
}
