{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.coverage",
    "module": "antibytes-coverage",
    "version": "0638349",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-0638349.jar",
          "url": "antibytes-coverage-0638349.jar",
          "size": 135187,
          "sha512": "ad13c3e54b03db1627251153c7a8d3c1b13668fcd5b5b991915fe4348bab85395891784804bca4a5487620e39f5b47e088e79a4bd833d561d6df4b8a547d5839",
          "sha256": "33fc99b488b14adeee240cbc0da1bb86c9a1a5d672c5153ded0ee1d6fe1840a5",
          "sha1": "023d1819ea2b514837c92e4860d2c71b160b62e5",
          "md5": "481ad1073b7354c052394e84f7512a0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "0638349"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-0638349.jar",
          "url": "antibytes-coverage-0638349.jar",
          "size": 135187,
          "sha512": "ad13c3e54b03db1627251153c7a8d3c1b13668fcd5b5b991915fe4348bab85395891784804bca4a5487620e39f5b47e088e79a4bd833d561d6df4b8a547d5839",
          "sha256": "33fc99b488b14adeee240cbc0da1bb86c9a1a5d672c5153ded0ee1d6fe1840a5",
          "sha1": "023d1819ea2b514837c92e4860d2c71b160b62e5",
          "md5": "481ad1073b7354c052394e84f7512a0b"
        }
      ]
    }
  ]
}
