{
  "formatVersion": "1.1",
  "component": {
    "url": "../../banana-i18n/d012c62/banana-i18n-d012c62.module",
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "d012c62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-d012c62.jar",
          "size": 85515,
          "sha512": "2763363b3f97d70431236fb68973ae6ac107bcb51dc966159c9532f09ec28061250c1c5480532b712f4640bde228d6f0fbe09232f9c1649255719db906822498",
          "sha256": "603f6ed2ef8d53c51b2bb27f74f843eeebe06e532fbe98e54369cae17f27e2a1",
          "sha1": "a9f4281985d77fbe13e2211af2fc6528d12848ca",
          "md5": "22f09cc6a98d1cbebdeb7f60d40e5d41"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-d012c62.jar",
          "size": 85515,
          "sha512": "2763363b3f97d70431236fb68973ae6ac107bcb51dc966159c9532f09ec28061250c1c5480532b712f4640bde228d6f0fbe09232f9c1649255719db906822498",
          "sha256": "603f6ed2ef8d53c51b2bb27f74f843eeebe06e532fbe98e54369cae17f27e2a1",
          "sha1": "a9f4281985d77fbe13e2211af2fc6528d12848ca",
          "md5": "22f09cc6a98d1cbebdeb7f60d40e5d41"
        }
      ]
    }
  ]
}
