{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/fc88d6a/test-utils-annotations-junit4-fc88d6a.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "fc88d6a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-iosarm32-fc88d6a.klib",
          "size": 11352,
          "sha512": "3ad9cb0e72beb24f5b8a1b6e0851dad8d64d1f71079bda7a81588206ec6780f5f42e10dad5312c5bb25ff4bd05adaa1f57c6ec6cffe65b3399e9d45aad272391",
          "sha256": "c8c4dbff304e696658164f74ba6b4eec241104f9df423031a6d3b563ed4c1271",
          "sha1": "619a85e64390d97b73d89f6a06e3be3fbd32f4f1",
          "md5": "323b544f76d35e9a59b34e2ebf611627"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-iosarm32-fc88d6a-metadata.jar",
          "url": "test-utils-annotations-junit4-iosarm32-fc88d6a-metadata.jar",
          "size": 261,
          "sha512": "679257d7374b15a8679872dd24b9b5fe1f0c100aa518398f4291d81709d026eb1036ac65baef04e34292aa6ecd43de31023bf04b28223969a878cb7ff3965084",
          "sha256": "a82fc3320e07c52adef853d242d58d480698f03dcde3564ceeab8cb4b0ee13da",
          "sha1": "e3b6e33c12ea94f0e401aeedeb8d968798687271",
          "md5": "8c8aa0486dd8f5c7a533f6720d704026"
        }
      ]
    }
  ]
}
