{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/9525479/core-9525479.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "9525479",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-9525479.klib",
          "size": 50697,
          "sha512": "87ab0bfc6e8d903423c3be3510c17346d5c6eb32c3e561afb093fa62e10ec1278f5ea5f2492cd5bc26a27c1fa415b727a4cfa28ced6fd4ca2ac37fdb04ee47e6",
          "sha256": "dce5e6c07b8cc6828cd72cefd3e1a1093f30fcdc3cbd9e64a55f0dbdaf89198d",
          "sha1": "e0fc0161455b59a13dc26f03f9c235a9411d5abf",
          "md5": "123ed70abcc8d622409ac4d1021195e8"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-9525479-metadata.jar",
          "url": "core-iosarm64-9525479-metadata.jar",
          "size": 261,
          "sha512": "e8c8d8cb2b5ca760d82b6afc8921054f71398af5e33c0f9af84e3a25ceea638a69456717586365ea10ce4e9f284c65e634b6316c8fa4112dc5d4d23620fbc164",
          "sha256": "41d1e20f2c2f8159ba53acab22ed4227984aa62666e9723d0bda56dcac1e4391",
          "sha1": "0b201feb309a5cbb11bf39c428c03202859eef1c",
          "md5": "27212919118dc0e8c9437dc9a7777a31"
        }
      ]
    }
  ]
}
