{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/dbba7bb/test-utils-dbba7bb.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "dbba7bb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-macosarm64-dbba7bb.klib",
          "size": 7979,
          "sha512": "15e92c13a1d1ae285f45bf1ea47a10e833b2d6f12612e4c9e502c433f0a8c52ff4903b3a18630036724c80daac130514ab51d38be91075450c34bf8ba5c65986",
          "sha256": "b994feb1ea8fbb7cb457946a928be9c906e127d48dc0f20bfe08793f76275e2d",
          "sha1": "d3cd45bb90e4a83ca73866fd990a312ae3714d34",
          "md5": "6e7b509f66492f0a753db72e822f5918"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-macosarm64-dbba7bb-metadata.jar",
          "url": "test-utils-macosarm64-dbba7bb-metadata.jar",
          "size": 261,
          "sha512": "848d326e193ba572cb5bf5e68ef30ecd8f0daad8b15deada0d049516be7ee3fed96096a44fb6c214b421e362b55a778c08eb543f0a45883e5b31e9643076bd28",
          "sha256": "fe1f090316c8bf2309b1e2c89c2caf078c07e668ad79a9d49ed88fed6a47fe2e",
          "sha1": "6feeedd948c25953baa2fbf33406c6eb9532a340",
          "md5": "b27f76476368976b70a9400af13ec9a2"
        }
      ]
    }
  ]
}
