{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "f6a864b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-f6a864b.jar",
          "url": "antibytes-grammar-tools-f6a864b.jar",
          "size": 59182,
          "sha512": "78e178275c971ff15a6e04c635ee2143452de22bda5ad1e2530fdaf1e43c0fc8e22c4f27c32abc4de197bd1d26e75361e5aff8e09a652a9c5028562f03e0671a",
          "sha256": "c31ad4d350c697bbfb8739d7fd04821d30fd5613ce164e8030e528a84e7db23d",
          "sha1": "5543468a5655df4e4665560fed25ed2b8df48191",
          "md5": "0f19897504ba9835be11b81b8ae200e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-f6a864b.jar",
          "url": "antibytes-grammar-tools-f6a864b.jar",
          "size": 59182,
          "sha512": "78e178275c971ff15a6e04c635ee2143452de22bda5ad1e2530fdaf1e43c0fc8e22c4f27c32abc4de197bd1d26e75361e5aff8e09a652a9c5028562f03e0671a",
          "sha256": "c31ad4d350c697bbfb8739d7fd04821d30fd5613ce164e8030e528a84e7db23d",
          "sha1": "5543468a5655df4e4665560fed25ed2b8df48191",
          "md5": "0f19897504ba9835be11b81b8ae200e4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-f6a864b-javadoc.jar",
          "url": "antibytes-grammar-tools-f6a864b-javadoc.jar",
          "size": 261,
          "sha512": "92942486a1a7ec136973eea225cc080bcbbd78aad0a90edce5a967b181e3a4123712a899e4ec9804f4ea56e2b3cdabc212fc33635cc508ff727fe43ca539d935",
          "sha256": "baa7427d48287ff96f71b567dcb04c8aa10a988b62098f6b1c65e289f214589c",
          "sha1": "bbd46bf15a98ecf9d486e9b94af7a09893a1d697",
          "md5": "8d0cd573d79174344bbeb2b787282a7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-f6a864b-sources.jar",
          "url": "antibytes-grammar-tools-f6a864b-sources.jar",
          "size": 12245,
          "sha512": "7c1cd327aa33888db8554c7579e45fea6e9b767ce8d36f8a8243767a074065828d01428eee4fce2724f04fcbd40a11b4f91664710b089f70506df19ddd210c6a",
          "sha256": "8da1f4a913dc358e3884053815788467551a7d50b4dbba2c7205145d240cfe09",
          "sha1": "4c30e804bd4bb6702716cea37c94e4ce2459ee1b",
          "md5": "228eacb885d0efb37e0c267b203311c8"
        }
      ]
    }
  ]
}
