{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "ccc6cc9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-ccc6cc9.jar",
          "url": "antibytes-configuration-ccc6cc9.jar",
          "size": 38257,
          "sha512": "a11c53e20def7985e4789a675e4290f8ddea7ba8987a3c125d9962300b6f1d7da4f623d5802a062472b6df39a315da6fea2dfd2ccdf24777b454ef04c76bb84a",
          "sha256": "3b96d410a668d4b3d8cc5bd301169c6aa027fef31fef918ad4e86d119e3e765e",
          "sha1": "68cc4fc9191624a40ee15c56748ca5933dc41dac",
          "md5": "7cdb6459fc7bdabde29b2bd8a153d6e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "ccc6cc9"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-ccc6cc9.jar",
          "url": "antibytes-configuration-ccc6cc9.jar",
          "size": 38257,
          "sha512": "a11c53e20def7985e4789a675e4290f8ddea7ba8987a3c125d9962300b6f1d7da4f623d5802a062472b6df39a315da6fea2dfd2ccdf24777b454ef04c76bb84a",
          "sha256": "3b96d410a668d4b3d8cc5bd301169c6aa027fef31fef918ad4e86d119e3e765e",
          "sha1": "68cc4fc9191624a40ee15c56748ca5933dc41dac",
          "md5": "7cdb6459fc7bdabde29b2bd8a153d6e4"
        }
      ]
    }
  ]
}
