{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "6be4f13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-metadata-6be4f13-all.jar",
          "url": "test-utils-fixture-6be4f13-all.jar",
          "size": 15419,
          "sha512": "8cf74d70999aa3530a0b85d2bd005c5ec0e281282b37e5e5f904c7361a1da217b7f97a57ffc9eb6a246fbf12eb132392d2b826286bc44eff4bfb69eca3f00c53",
          "sha256": "d51a37fdcf26093700770bb108a9b37938d119dbaf80096cfe383ad07af621e5",
          "sha1": "4329c53494d04764f0887f0ddc1eac9ec9cbc5bd",
          "md5": "c974fdd08aa22abb8bd12edfba3366ca"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-fixture-6be4f13.jar",
          "url": "test-utils-fixture-6be4f13.jar",
          "size": 15466,
          "sha512": "47aade87804c7c98a0246a5aec616698fbcd4089e7aeec2901afe7b0bd69d04512d0e14ba9c34f1da49e0295e81fc0e3d348d7df56e3f6f79026b11153342b92",
          "sha256": "e82d8ac26fce440037cc06b641c087cd02a059746aaa9a04f3d591b45215e166",
          "sha1": "19d8b825febf19e1749f840db866beab4609a656",
          "md5": "192fb80806e0a009b3322e40972b5d52"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-android/6be4f13/test-utils-fixture-android-6be4f13.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-android",
        "version": "6be4f13"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-android/6be4f13/test-utils-fixture-android-6be4f13.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-android",
        "version": "6be4f13"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iosarm64/6be4f13/test-utils-fixture-iosarm64-6be4f13.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iosarm64",
        "version": "6be4f13"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iosarm64/6be4f13/test-utils-fixture-iosarm64-6be4f13.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iosarm64",
        "version": "6be4f13"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iossimulatorarm64/6be4f13/test-utils-fixture-iossimulatorarm64-6be4f13.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iossimulatorarm64",
        "version": "6be4f13"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iossimulatorarm64/6be4f13/test-utils-fixture-iossimulatorarm64-6be4f13.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iossimulatorarm64",
        "version": "6be4f13"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iosx64/6be4f13/test-utils-fixture-iosx64-6be4f13.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iosx64",
        "version": "6be4f13"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iosx64/6be4f13/test-utils-fixture-iosx64-6be4f13.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iosx64",
        "version": "6be4f13"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-fixture-js/6be4f13/test-utils-fixture-js-6be4f13.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-js",
        "version": "6be4f13"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-fixture-js/6be4f13/test-utils-fixture-js-6be4f13.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-js",
        "version": "6be4f13"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-jvm/6be4f13/test-utils-fixture-jvm-6be4f13.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-jvm",
        "version": "6be4f13"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-jvm/6be4f13/test-utils-fixture-jvm-6be4f13.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-jvm",
        "version": "6be4f13"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-linuxx64/6be4f13/test-utils-fixture-linuxx64-6be4f13.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-linuxx64",
        "version": "6be4f13"
      }
    }
  ]
}
