{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "1e70de2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-1e70de2.jar",
          "url": "antibytes-dependency-1e70de2.jar",
          "size": 30441,
          "sha512": "d7b95efea567b7368db16aa81067949bc7e440b308ae5192c0acca4771fd113a1d263d99af0599046c996bbd326e1d6b3a2713bf9b7e4bccac92f623d738334c",
          "sha256": "c3a252eb05f454d04bb84f9ad564f1fc0a9a83d6157d11252b82501ab1a917a8",
          "sha1": "7fa6eb49e72295e28a70af1b2d58d0cacd980a7b",
          "md5": "2f666911c1e858eca90ff535d43f8a2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.39.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-1e70de2.jar",
          "url": "antibytes-dependency-1e70de2.jar",
          "size": 30441,
          "sha512": "d7b95efea567b7368db16aa81067949bc7e440b308ae5192c0acca4771fd113a1d263d99af0599046c996bbd326e1d6b3a2713bf9b7e4bccac92f623d738334c",
          "sha256": "c3a252eb05f454d04bb84f9ad564f1fc0a9a83d6157d11252b82501ab1a917a8",
          "sha1": "7fa6eb49e72295e28a70af1b2d58d0cacd980a7b",
          "md5": "2f666911c1e858eca90ff535d43f8a2c"
        }
      ]
    }
  ]
}
