{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "b1373c3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-b1373c3.jar",
          "url": "antibytes-dependency-node-b1373c3.jar",
          "size": 20143,
          "sha512": "22a49fa78424e359cbc53b17d0d9b7860463e9e0a9670d91ef487c896100991870115ee874b8447aade869ac5db5e3bedd5e23d5ca2a630260ca3792952607fe",
          "sha256": "84269c2c734a5d1f0e915b40bcbefc247996954c7c65621420aedbe1fefd6365",
          "sha1": "62b468137d2dbac8e9496c02eec2dc06c87724f5",
          "md5": "1692028f3a1f61e0b79a8c0d64ca57a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-b1373c3.jar",
          "url": "antibytes-dependency-node-b1373c3.jar",
          "size": 20143,
          "sha512": "22a49fa78424e359cbc53b17d0d9b7860463e9e0a9670d91ef487c896100991870115ee874b8447aade869ac5db5e3bedd5e23d5ca2a630260ca3792952607fe",
          "sha256": "84269c2c734a5d1f0e915b40bcbefc247996954c7c65621420aedbe1fefd6365",
          "sha1": "62b468137d2dbac8e9496c02eec2dc06c87724f5",
          "md5": "1692028f3a1f61e0b79a8c0d64ca57a3"
        }
      ]
    }
  ]
}
