{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "bf5cf3e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-bf5cf3e.jar",
          "url": "antibytes-android-application-configuration-bf5cf3e.jar",
          "size": 63996,
          "sha512": "49b35cce117510b002b3874e8111f3ba0177decb9c6bb44bb217224533e2556e82f13d60f637776d5f5653a0413c1a0ae9df41627303a1f5ac72862878077ac0",
          "sha256": "bc0027d3fc9831fc909e25fd1d8d03d0d888ffd9839559c3fe21b90ea15d29a7",
          "sha1": "71c829fcfbfb14f63678f44729cf48b5daccd9eb",
          "md5": "e6135362f11f1a0105737f5903ee64c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "bf5cf3e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-bf5cf3e.jar",
          "url": "antibytes-android-application-configuration-bf5cf3e.jar",
          "size": 63996,
          "sha512": "49b35cce117510b002b3874e8111f3ba0177decb9c6bb44bb217224533e2556e82f13d60f637776d5f5653a0413c1a0ae9df41627303a1f5ac72862878077ac0",
          "sha256": "bc0027d3fc9831fc909e25fd1d8d03d0d888ffd9839559c3fe21b90ea15d29a7",
          "sha1": "71c829fcfbfb14f63678f44729cf48b5daccd9eb",
          "md5": "e6135362f11f1a0105737f5903ee64c6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-bf5cf3e-javadoc.jar",
          "url": "antibytes-android-application-configuration-bf5cf3e-javadoc.jar",
          "size": 261,
          "sha512": "53f14149833bf416569bf51733af89e63a93db7d4d02e46c52c5a96e4057407d8c958884dd86bd6ce34a72e76acbcb025f312f79ae58841884f635cc21e8ba26",
          "sha256": "8da6f2e4f844fbdf2347304518d9a387012d743b0a59063aa0cc79f5616e568f",
          "sha1": "0434b2fd585a28a9c906ff7bf163382379f7de3a",
          "md5": "aab90479759e3d6c74492c45a6a10ea2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-bf5cf3e-sources.jar",
          "url": "antibytes-android-application-configuration-bf5cf3e-sources.jar",
          "size": 12867,
          "sha512": "d0cbb170197a76400876fc76734e5e9c8e474cee971b28c3c7fa795a78fa9423659f34d3ecf9e11cf6dcddbc770ca52080a5875fccf65aef77e97e052d18dcbd",
          "sha256": "5d547f179c7e3bb08f1225607416a01920924726274c2cc7466dfbdb97bab260",
          "sha1": "59dd7f1e7c90cfd2349142758c3b2b14ed9c22c4",
          "md5": "3c23ac11649a3827f4a9d97fa45c0fd1"
        }
      ]
    }
  ]
}
