{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-versioning",
    "version": "cfe7e33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-cfe7e33.jar",
          "url": "antibytes-versioning-cfe7e33.jar",
          "size": 16029,
          "sha512": "620b4bd12e0fe419b1c02a84ac7a6afe54fd568d52b254f64ef6451cc1cac32c7f74a7106ed8bb25012ac99b89c9650e9b2c4101c10922974aa446d009f16491",
          "sha256": "ca756eaeeb2d3c32e10633935d43fa55db91ab155b762a0a7fef927d93a49394",
          "sha1": "eb3f74b4032f5d0b019185173145ba483646f4fb",
          "md5": "bde0895b00f62ecb69105fc67733fb69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-cfe7e33.jar",
          "url": "antibytes-versioning-cfe7e33.jar",
          "size": 16029,
          "sha512": "620b4bd12e0fe419b1c02a84ac7a6afe54fd568d52b254f64ef6451cc1cac32c7f74a7106ed8bb25012ac99b89c9650e9b2c4101c10922974aa446d009f16491",
          "sha256": "ca756eaeeb2d3c32e10633935d43fa55db91ab155b762a0a7fef927d93a49394",
          "sha1": "eb3f74b4032f5d0b019185173145ba483646f4fb",
          "md5": "bde0895b00f62ecb69105fc67733fb69"
        }
      ]
    }
  ]
}
