{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/fc88d6a/test-utils-fc88d6a.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "fc88d6a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-watchosarm32-fc88d6a.klib",
          "size": 7996,
          "sha512": "1975281765ac841c5fc8b2ec87604946a8db52e9a0dd33fb89ac6cdcbafe7cccdfef54b1c28abd2fc6f2caa325a56727d851d959786b5d6fb00da05a6cd297cd",
          "sha256": "db9db4ac6c5f286d389ab7b463d7dc80be9cfe03ebf0c5449693b222fe5709e6",
          "sha1": "53fef8b61249ddf8eb28e7da09d9e791be091e0d",
          "md5": "5763fb77f879aa8e919947a4be235080"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-watchosarm32-fc88d6a-metadata.jar",
          "url": "test-utils-watchosarm32-fc88d6a-metadata.jar",
          "size": 261,
          "sha512": "084635e5e58ab60adc6db7967b2a033f72bc1367cbbad9f6b49dc8e94e27b40fd3db0cdccf2f51e767bd0fc9415df6f11fa44a75c7e078450ba3375652e15632",
          "sha256": "f9d392e2e5acced06a95a89fb4e64d432345ba66edba041178637a49cac5de7a",
          "sha1": "cda2268953cc27ee7cfebfefdc963c5f322c32f3",
          "md5": "778f75771c22b43f28cc5dc052860b61"
        }
      ]
    }
  ]
}
