{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/766ba9c/test-utils-coroutine-766ba9c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "766ba9c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-766ba9c.jar",
          "url": "test-utils-coroutine-jvm-766ba9c.jar",
          "size": 11975,
          "sha512": "026f9b0342b975922b5a50e30f9635f2fa056214d4b8bcc0612866e490a8b912aa896fd2bcf404aaa34d2e763da5487007615f3ff0ef2645a3654aa45aa53d19",
          "sha256": "3861bc9fdd6555a6225af274c779b73cefcb470a4221f3248928843c79cd8e4d",
          "sha1": "a7008b81b36dbe7e42a97d486cfe5b84ec78d9ae",
          "md5": "3faeebeea7749a2a55a0b181b7e12d7b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-766ba9c.jar",
          "url": "test-utils-coroutine-jvm-766ba9c.jar",
          "size": 11975,
          "sha512": "026f9b0342b975922b5a50e30f9635f2fa056214d4b8bcc0612866e490a8b912aa896fd2bcf404aaa34d2e763da5487007615f3ff0ef2645a3654aa45aa53d19",
          "sha256": "3861bc9fdd6555a6225af274c779b73cefcb470a4221f3248928843c79cd8e4d",
          "sha1": "a7008b81b36dbe7e42a97d486cfe5b84ec78d9ae",
          "md5": "3faeebeea7749a2a55a0b181b7e12d7b"
        }
      ]
    }
  ]
}
