{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "dda2add",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-dda2add.jar",
          "url": "antibytes-versioning-dda2add.jar",
          "size": 24286,
          "sha512": "6451ea4f0161a2039542224786e2bb0a269f0a4a323cbdff505b493b5ed5ff8f66c4b8fff7350f730726aec383b6af05d9a09b4e1c620bb09982e9747710d7f7",
          "sha256": "79176ccefd18649e45395bed10c074ee5bfa0d88efa7b852669b6fac5d97f6d3",
          "sha1": "ff9fcdb4cfeb7547976033429ce6474c18149f36",
          "md5": "ccda48e39fa0fd364c57bdeeccdd1110"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-dda2add.jar",
          "url": "antibytes-versioning-dda2add.jar",
          "size": 24286,
          "sha512": "6451ea4f0161a2039542224786e2bb0a269f0a4a323cbdff505b493b5ed5ff8f66c4b8fff7350f730726aec383b6af05d9a09b4e1c620bb09982e9747710d7f7",
          "sha256": "79176ccefd18649e45395bed10c074ee5bfa0d88efa7b852669b6fac5d97f6d3",
          "sha1": "ff9fcdb4cfeb7547976033429ce6474c18149f36",
          "md5": "ccda48e39fa0fd364c57bdeeccdd1110"
        }
      ]
    }
  ]
}
