{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/b9030f2/test-utils-resourceloader-b9030f2.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "b9030f2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-js-b9030f2.klib",
          "url": "test-utils-resourceloader-js-b9030f2.klib",
          "size": 12789,
          "sha512": "692a69258c838265ae2c1620ea5a40d9cc45c9355a9e0395fa19293240fe8fb434d45d5599911440999a0aa2387abd67be4352b2391dcfad693395a24b1ee4b8",
          "sha256": "e9d2114f636028fd74f896a462ef6c79fec5e62bd22c0a4e0ee6f2f1de97266c",
          "sha1": "0458b480f2e6f8926ead7fcd21a6c6ef21ff47f6",
          "md5": "ac3f2b7cc88226b827f9961610b23512"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-js-b9030f2.klib",
          "url": "test-utils-resourceloader-js-b9030f2.klib",
          "size": 12789,
          "sha512": "692a69258c838265ae2c1620ea5a40d9cc45c9355a9e0395fa19293240fe8fb434d45d5599911440999a0aa2387abd67be4352b2391dcfad693395a24b1ee4b8",
          "sha256": "e9d2114f636028fd74f896a462ef6c79fec5e62bd22c0a4e0ee6f2f1de97266c",
          "sha1": "0458b480f2e6f8926ead7fcd21a6c6ef21ff47f6",
          "md5": "ac3f2b7cc88226b827f9961610b23512"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-js-b9030f2-sources.jar",
          "url": "test-utils-resourceloader-js-b9030f2-sources.jar",
          "size": 4271,
          "sha512": "2503ae731867855e3ed286fe6f630541d9faca0745b35536afb51ced7c0e4d1c3966bdab25e935f527aa92f06759f83e4cf7266890b1a7bd1852132e71ea5aff",
          "sha256": "c17ff9c086db0769eaffc7bbd2ad9ca7e6cea52462056c8117f2268fe18716d9",
          "sha1": "922a0e16e4c902a63c31d5f3f021daca1b35d0bc",
          "md5": "a3e3bf4b2266c408a916b09deae46932"
        }
      ]
    }
  ]
}
