{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-SNAPSHOT/ktx-datetime-0.3.1-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iosarm64-0.3.1-SNAPSHOT.klib",
          "size": 32807,
          "sha512": "dee248c88646e6a889bc4ac83ab4698de4e6d91ba4fc631d1af41feedec79df7fff5cad59e0507883950ba1d7cd5b516c4518f029f3c10249ad5d1993ae2c535",
          "sha256": "7af80a9094d5ca4a7a9c183a58972dfaa0433a1b12c50963cee1876493bb5497",
          "sha1": "d81ad8a70448442c3ce9a9a3f15570b90dafa1c6",
          "md5": "b86e06588ae6dee4fa848bea7bb96c79"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iosarm64-0.3.1-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iosarm64-0.3.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d08f40b08d682f6862b66d3a150c4afb9aba0f7cdcd58982a0aa35e4f4fb7fad47bfe2f8fddea28f4e989c7f9f2200a784cd8b1b722dace015a9335c4e8e4371",
          "sha256": "2e1dbee8e9043467803fc047fa57770743720d8632b614fbc43cab3b5e6dcd9d",
          "sha1": "7a7d708935c168f0d868499c3526fdf96bec8133",
          "md5": "1fcac8da355f3289c6463d689c1825a3"
        }
      ]
    }
  ]
}
