{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-SNAPSHOT/ktx-datetime-0.3.1-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iosarm64-0.3.1-SNAPSHOT.klib",
          "size": 34700,
          "sha512": "4e6e63a1280edd24731208db185207b3e32c8f468aa792ddff68834c261c94c19895c0c1ad720e44c4d3a4c741ce79261fa5befd35936c169dd7697da7633a25",
          "sha256": "57c307e57fe3914a46433eb713c8a3a58233beb481dd6afb7a59bc8259b25dc2",
          "sha1": "dd68411fcc361e03792d63096d349ab6e0a009f9",
          "md5": "958e861da164188bdf55170df1d61328"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iosarm64-0.3.1-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iosarm64-0.3.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "c3279230ebf5bb98026fd3545314113dcc4b6fcb723901bb2f2d2c5086dc9cdaca87b2d71c4f69d81dd56391ae887a2499f8c212b655b15f94ea96f5f62a3a94",
          "sha256": "a149e0c78fe8c7d5bd9a85c45e92169a9678e4b70b3e5a3195a176acceb02caf",
          "sha1": "3ba6097c879923686b77e89019af1ad5cd017d77",
          "md5": "60f0ef01e7d6128452f46d282d26f894"
        }
      ]
    }
  ]
}
