{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-SNAPSHOT/ktx-datetime-0.3.1-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iosarm64-0.3.1-SNAPSHOT.klib",
          "size": 34700,
          "sha512": "4e6e63a1280edd24731208db185207b3e32c8f468aa792ddff68834c261c94c19895c0c1ad720e44c4d3a4c741ce79261fa5befd35936c169dd7697da7633a25",
          "sha256": "57c307e57fe3914a46433eb713c8a3a58233beb481dd6afb7a59bc8259b25dc2",
          "sha1": "dd68411fcc361e03792d63096d349ab6e0a009f9",
          "md5": "958e861da164188bdf55170df1d61328"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iosarm64-0.3.1-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iosarm64-0.3.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e34ab3b25ae355b8f350d738dcd093b958029ab12ec905ccc2598e0238b319b58efa195770fec8657d81d2bf89bf0b2f9782c5bc233902853e8b26521a1481d6",
          "sha256": "b074f37b9a0c9ced93a99551bffb01ad11962d4f59c4fc1d0997c2a748fbd240",
          "sha1": "d80153a8a6007862c9f2fbaa9d5cfd0683f9844b",
          "md5": "3a62e098f6573d72e5d828edbf984516"
        }
      ]
    }
  ]
}
