{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "b5d11da",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-b5d11da.jar",
          "url": "antibytes-dependency-helper-b5d11da.jar",
          "size": 69703,
          "sha512": "5ec9e662275a83b208db4a67e73bef0e60dbb2df5bf42b8c581a01e5471a99c5a8818da91e3b8aad0e715356b42ef12df75d2833e290aae637140a11a6ce6bcb",
          "sha256": "0196fc9ae0fd8d3840a89f6563f06e879ddb01f7da8471e1f45c0b377d098216",
          "sha1": "3976e691ce61785e7f4829f832b7112f5e1f6d96",
          "md5": "369d93401b5cb252a8c76dc7926f5cf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.51.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "9.0.9"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "b5d11da"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-b5d11da.jar",
          "url": "antibytes-dependency-helper-b5d11da.jar",
          "size": 69703,
          "sha512": "5ec9e662275a83b208db4a67e73bef0e60dbb2df5bf42b8c581a01e5471a99c5a8818da91e3b8aad0e715356b42ef12df75d2833e290aae637140a11a6ce6bcb",
          "sha256": "0196fc9ae0fd8d3840a89f6563f06e879ddb01f7da8471e1f45c0b377d098216",
          "sha1": "3976e691ce61785e7f4829f832b7112f5e1f6d96",
          "md5": "369d93401b5cb252a8c76dc7926f5cf3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-b5d11da-javadoc.jar",
          "url": "antibytes-dependency-helper-b5d11da-javadoc.jar",
          "size": 261,
          "sha512": "a93a00e07da9e019204ec0759eac20a16f41809751a8c2c1016a30abeab6e71493db5afd0831c94b820a91a5e9a395ba1b2c87f834548b82fcbd1301746ab51f",
          "sha256": "23bfadc1ca530fe0e03dcee52cc2ef018e7b20e3dfe51ab2807340d47f554e7b",
          "sha1": "de9dc4cf2df0adc562cb39d6215a9aa880438c2b",
          "md5": "3ab218f39ed2c258ee345691da43b286"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-b5d11da-sources.jar",
          "url": "antibytes-dependency-helper-b5d11da-sources.jar",
          "size": 9186,
          "sha512": "a95fd5a707864b741e91b8cdd857c868ab154239173e281d5f2e5d54ab61c36fd32e195a499648ea6d61d7e031a73295274f9e1e6ca3692900df69b56fcd4227",
          "sha256": "b133af8c0e1dcf46c40c9b332f16546acf74f04650620a9c68ffabca4e95c03d",
          "sha1": "27070f644ec2a0e686b12a4e2e8a77bdb4de76b1",
          "md5": "1e7b38dc41d5df97d5d17909740d4920"
        }
      ]
    }
  ]
}
