{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "47c16f9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-metadata-47c16f9.jar",
          "url": "kmock-47c16f9.jar",
          "size": 21090,
          "sha512": "263fc8f3f5ab152e477d9f7c0cac9b1049c27c1843ca67262ff692f1d0842771ea2aa9950b138f8d1292b5d02ecf4861834d0bfb22782975f4e7ebc80b39da97",
          "sha256": "354ec6d02ffdfb144643ea8dd024461f87a281bd20b2ce0ed7ace7e4018f1b58",
          "sha1": "ccbd9e646095c323c6ed7746c3a4f393f4ddb2d2",
          "md5": "0e3fb6ac7e7bab913fd0418f8c3bff1a"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/47c16f9/kmock-android-47c16f9.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "47c16f9"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/47c16f9/kmock-android-47c16f9.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "47c16f9"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/47c16f9/kmock-iosarm64-47c16f9.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "47c16f9"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/47c16f9/kmock-iosx64-47c16f9.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "47c16f9"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/47c16f9/kmock-js-47c16f9.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "47c16f9"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/47c16f9/kmock-js-47c16f9.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "47c16f9"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/47c16f9/kmock-jvm-47c16f9.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "47c16f9"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/47c16f9/kmock-jvm-47c16f9.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "47c16f9"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/47c16f9/kmock-linuxx64-47c16f9.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "47c16f9"
      }
    }
  ]
}
