{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "141b24a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-141b24a.jar",
          "url": "antibytes-gradle-test-utils-141b24a.jar",
          "size": 16830,
          "sha512": "202d5494e0e3c88dd936fedf8f43c4961cc3ccf89b375a2d384a16282321463cfedcee1bb20902166468db5448fc8af6a83594bb0159b4ff96fe876ee5b3691e",
          "sha256": "97996dce2d424b7df5bfebde96d98738d693ab4fbc2939e20755333505ec9c02",
          "sha1": "6ef4e6fb8569c4298749eccbd2ff7d7aac2958aa",
          "md5": "6cc3292ad08868fbd49f5f2d7802cc7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-141b24a.jar",
          "url": "antibytes-gradle-test-utils-141b24a.jar",
          "size": 16830,
          "sha512": "202d5494e0e3c88dd936fedf8f43c4961cc3ccf89b375a2d384a16282321463cfedcee1bb20902166468db5448fc8af6a83594bb0159b4ff96fe876ee5b3691e",
          "sha256": "97996dce2d424b7df5bfebde96d98738d693ab4fbc2939e20755333505ec9c02",
          "sha1": "6ef4e6fb8569c4298749eccbd2ff7d7aac2958aa",
          "md5": "6cc3292ad08868fbd49f5f2d7802cc7f"
        }
      ]
    }
  ]
}
