{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-SNAPSHOT/ktx-datetime-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-linuxx64-0.4.0-SNAPSHOT.klib",
          "size": 36912,
          "sha512": "0757c59644a3beccc6c70ff60519990eecaaf49a725baf4d767561b1d6bf8e7890301220d9aacd88ce82bff01e18a740080f636a6e101dd94e1fe1559a0783b1",
          "sha256": "afa1249254381f51a08dc168efef26eaf7723490228b536050ff727afb5e085f",
          "sha1": "72c8dbc29314d421d705f8cb6797a3c70d3ee00f",
          "md5": "217b9491e818fdbaac06603f15afcfef"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktx-datetime-linuxx64-0.4.0-SNAPSHOT-sources.jar",
          "url": "ktx-datetime-linuxx64-0.4.0-SNAPSHOT-sources.jar",
          "size": 16088,
          "sha512": "2fd1093b4f66fb86460e0e5fc46d3c82d6d649e51f6fa67d86c49ee2405d528475c31f450f406b1a2be2e691d1f52d71036cf571bf342b1c7bbfdb18aacafc58",
          "sha256": "ddfeada0f92e68af51cd57f3ddcf63f5349e6ad12c9b5c93c0313015c5cc3e8e",
          "sha1": "e3f7b5b02498f31f31ff09a28221f9502399b3a2",
          "md5": "b2ce74b02e7d0b4b4cf6bb0c3c064bd4"
        }
      ]
    }
  ]
}
