{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "40ef555",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-40ef555.jar",
          "url": "antibytes-dependency-node-40ef555.jar",
          "size": 21501,
          "sha512": "d62021730186609a12e1d75a68597f816f85b7861ba92f31a8fdfb1e7574a473870ed6ea6b291f050217da9f06f795ac775a24c7ec2ff99982b1cb002078e6d9",
          "sha256": "5c1fa2936efe662abf4966b929506b12f406de8768010511387ceff826828752",
          "sha1": "52231a400c23a9ea9345b2a17f73e58403e588ab",
          "md5": "e98907b6dc8d463c423c7d616b4202ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-40ef555.jar",
          "url": "antibytes-dependency-node-40ef555.jar",
          "size": 21501,
          "sha512": "d62021730186609a12e1d75a68597f816f85b7861ba92f31a8fdfb1e7574a473870ed6ea6b291f050217da9f06f795ac775a24c7ec2ff99982b1cb002078e6d9",
          "sha256": "5c1fa2936efe662abf4966b929506b12f406de8768010511387ceff826828752",
          "sha1": "52231a400c23a9ea9345b2a17f73e58403e588ab",
          "md5": "e98907b6dc8d463c423c7d616b4202ca"
        }
      ]
    }
  ]
}
