{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "384f364",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-384f364.jar",
          "url": "antibytes-dependency-node-384f364.jar",
          "size": 21473,
          "sha512": "3ea2c2624ef419ce30f02ee27071008492664d4a6d44d22549b81e43ac1cf2505d29f290df4909609e709572e0f5f5ecd6f3e8fd4980238beeed1c411e623fd1",
          "sha256": "a7552f23a338efc1811138e55fb7e0591ea1eb74106a68514caf1d4460efac53",
          "sha1": "4eafc220d2e5186a3dc29c61d18cbd1a1f0eb415",
          "md5": "533e60d87ef393ce9dc1c5390e86db9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-384f364.jar",
          "url": "antibytes-dependency-node-384f364.jar",
          "size": 21473,
          "sha512": "3ea2c2624ef419ce30f02ee27071008492664d4a6d44d22549b81e43ac1cf2505d29f290df4909609e709572e0f5f5ecd6f3e8fd4980238beeed1c411e623fd1",
          "sha256": "a7552f23a338efc1811138e55fb7e0591ea1eb74106a68514caf1d4460efac53",
          "sha1": "4eafc220d2e5186a3dc29c61d18cbd1a1f0eb415",
          "md5": "533e60d87ef393ce9dc1c5390e86db9b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-384f364-javadoc.jar",
          "url": "antibytes-dependency-node-384f364-javadoc.jar",
          "size": 261,
          "sha512": "6fc79d7d7359d1adb69361b712553d020a1eda7e192933188c233a2c908fb2ea01e63b28d799e9768156952522bfa7c0bcc37c5e1d53842d056df683795db4d9",
          "sha256": "f8c00991504bde17d5434943f14e03211f13dd1c084f3fe64ebc731749274772",
          "sha1": "782ccb933fac51ac1e3c482b9e5bf9b0c196f8fc",
          "md5": "22eb624a179632010984e59649bdc3e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-384f364-sources.jar",
          "url": "antibytes-dependency-node-384f364-sources.jar",
          "size": 4172,
          "sha512": "5ee5745ec089689f391556db907b4fc45cca34276931c95f83c85310e62c0be7f73ab1292523a2dc9e7444df05d10031e0a28f9e08d385e890443b10b603107e",
          "sha256": "a498937c2034f087116757c995d327976340f29039f7f119d377cdfd9d6751b9",
          "sha1": "e87b6182c48506d3d78f18dbdc5af3a37ba80d0a",
          "md5": "3e480da959fc90dd0171fcead8cb1fd6"
        }
      ]
    }
  ]
}
