{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "40ef555",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-40ef555.jar",
          "url": "antibytes-gradle-test-utils-40ef555.jar",
          "size": 17888,
          "sha512": "1b801d6e32fa4c4aa3753bd451a1e4b5b24f7d086d4525ad948a26256ccf62b182a3cbddbf010e2db405b4698d4739506d6830f160ea7db493f39c14a9184737",
          "sha256": "b7eafdfafd0286d1eaa827221596a62e346234b4395ae8f704a901c8a961f259",
          "sha1": "f02b744ae7c9e38a5b0aaf3271f65f79886a7182",
          "md5": "7b1fd35fb655929f707ae2350753779b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.7"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-40ef555.jar",
          "url": "antibytes-gradle-test-utils-40ef555.jar",
          "size": 17888,
          "sha512": "1b801d6e32fa4c4aa3753bd451a1e4b5b24f7d086d4525ad948a26256ccf62b182a3cbddbf010e2db405b4698d4739506d6830f160ea7db493f39c14a9184737",
          "sha256": "b7eafdfafd0286d1eaa827221596a62e346234b4395ae8f704a901c8a961f259",
          "sha1": "f02b744ae7c9e38a5b0aaf3271f65f79886a7182",
          "md5": "7b1fd35fb655929f707ae2350753779b"
        }
      ]
    }
  ]
}
