{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/12815ae/test-utils-coroutine-12815ae.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "12815ae",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-12815ae.jar",
          "url": "test-utils-coroutine-jvm-12815ae.jar",
          "size": 11975,
          "sha512": "7a5f218d26256be7799704b0dbea32be880374f396052e287e914c8e9382e900b95d3e8686ef7251a14293921ba9d27c44ca99568775a6a543cd6a1c9ef88461",
          "sha256": "c46e379b62be594c5795cf60cb22e292ea8cbd818be81ed040531af8fbe5aaf5",
          "sha1": "9a900419969979154bc27e60921f7fc3b3b3f95e",
          "md5": "a052230bc7aa53524e683f26c6c01754"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-12815ae.jar",
          "url": "test-utils-coroutine-jvm-12815ae.jar",
          "size": 11975,
          "sha512": "7a5f218d26256be7799704b0dbea32be880374f396052e287e914c8e9382e900b95d3e8686ef7251a14293921ba9d27c44ca99568775a6a543cd6a1c9ef88461",
          "sha256": "c46e379b62be594c5795cf60cb22e292ea8cbd818be81ed040531af8fbe5aaf5",
          "sha1": "9a900419969979154bc27e60921f7fc3b3b3f95e",
          "md5": "a052230bc7aa53524e683f26c6c01754"
        }
      ]
    }
  ]
}
