{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/597ee0b/test-utils-ktor-597ee0b.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "597ee0b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-597ee0b.jar",
          "size": 23023,
          "sha512": "84a6f95749755ee99217dc51153e5feeb2e7f461083ee7c1689ce7b7daabcf41b2dd644380c738bf7ee0f7a064ee491db385b0ffd300f616b25d1f27a82c1a98",
          "sha256": "81bb299e7916d8bf47e568084cb6abf9549b2337a0a22ebe7e15d550445fcd4e",
          "sha1": "eb9b639fa0d924e18f4632ddb647aac559101058",
          "md5": "3efb169c8dd30d1b94cab2bc3e639442"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "1.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-597ee0b.jar",
          "size": 23023,
          "sha512": "84a6f95749755ee99217dc51153e5feeb2e7f461083ee7c1689ce7b7daabcf41b2dd644380c738bf7ee0f7a064ee491db385b0ffd300f616b25d1f27a82c1a98",
          "sha256": "81bb299e7916d8bf47e568084cb6abf9549b2337a0a22ebe7e15d550445fcd4e",
          "sha1": "eb9b639fa0d924e18f4632ddb647aac559101058",
          "md5": "3efb169c8dd30d1b94cab2bc3e639442"
        }
      ]
    }
  ]
}
