{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/766ba9c/test-utils-766ba9c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "766ba9c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm64-766ba9c.klib",
          "size": 7962,
          "sha512": "4a9c4a745a177b65290a8b6e1f4e45afc70018250e9ae064673b79e21097a78c70fdbb53a13b425478520c3b96d781a60435d7f3e70860d6cf3e70419e57b82c",
          "sha256": "c231e0f0fe7d17b3c8feebc5684c52f4f2e23e8c895ea9c6ab9bb1bafb5817ae",
          "sha1": "bd56568f4ff847bf496cb11403f05f4758bc54ac",
          "md5": "21bf8685971662cd968ba414c97652e7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm64-766ba9c-metadata.jar",
          "url": "test-utils-iosarm64-766ba9c-metadata.jar",
          "size": 261,
          "sha512": "4d8ad050f1e9d5c311e3f0a75cade2e4e880f9a9e8ad1e9ac6bd955e4e30b7ffb997787fe79dbde47a26291b0661262365332117acfb7e000254c363dc4db015",
          "sha256": "1d232508b00fcf24f26e9d80917fb01f0ea0a4f340639f2c711cb320f62fc346",
          "sha1": "72d980e5198985445878e2c2e199de10fb2bd547",
          "md5": "953113de9494382c7467534bea113fb6"
        }
      ]
    }
  ]
}
