{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "fa9f81c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-fa9f81c.jar",
          "url": "antibytes-gradle-test-utils-fa9f81c.jar",
          "size": 17226,
          "sha512": "a3ff85b6bd8c2064ce0899a6cf7e719c6cf8ff43c5ab6aa101420b37a1208a1ed928527b07a629124b290f8e8fba25b871d42b6fe0f48c36528aaffaf8752f92",
          "sha256": "ffbea9afcdb4627438120779c9d20dcd79ffbd7916e8b76e7a7f9f6a00f927a0",
          "sha1": "0eb993c14cd783d4a1eee8ab410c1aecf1b2a2d5",
          "md5": "bcca5d058f11ae4889e3567b48052b94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-fa9f81c.jar",
          "url": "antibytes-gradle-test-utils-fa9f81c.jar",
          "size": 17226,
          "sha512": "a3ff85b6bd8c2064ce0899a6cf7e719c6cf8ff43c5ab6aa101420b37a1208a1ed928527b07a629124b290f8e8fba25b871d42b6fe0f48c36528aaffaf8752f92",
          "sha256": "ffbea9afcdb4627438120779c9d20dcd79ffbd7916e8b76e7a7f9f6a00f927a0",
          "sha1": "0eb993c14cd783d4a1eee8ab410c1aecf1b2a2d5",
          "md5": "bcca5d058f11ae4889e3567b48052b94"
        }
      ]
    }
  ]
}
