{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.2.0-SNAPSHOT.klib",
          "size": 86694,
          "sha512": "694c96335a87f390e6eb325f14752ce52eb276e26138689af9662f2a2f8d03b3d782fcca3b146a7875663713d8dc856e3d79c7a9fd8e6e4b8baacbe8a5ee8213",
          "sha256": "31990ac42578b82eac4335d811f267e9ea13036baaac4088b950460e47530919",
          "sha1": "df01c908732d29fe49250ef902024448c33d2554",
          "md5": "23e89a8fd1b0dc7bf033fca936ca552b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.2.0-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.2.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "40ef11b0103349a7f0f8bee7beec7911f4a9ab1d17b9a18cbe24101bfdcd99efe7e6795cd99d8125406c289875080842022c722cd238f9fe1bd9238d5b276cd3",
          "sha256": "58f026ebf42a92410fe1f304739424c7cc198001e94b6c484ecfeb12792c0242",
          "sha1": "d83035b33e780f12ab5bcefdc40103a0beb84ecd",
          "md5": "dcb0b06cabb9e138e8fd34c04a5e770a"
        }
      ]
    }
  ]
}
