{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.2.0-SNAPSHOT.klib",
          "size": 74394,
          "sha512": "b77f9f0a6d1a3156549120c599a8259c92f49ff1167caccbe08d52b1e259607a368f92903882b0c571570b71b317fbe9cbd14100f2e3be3caf56d246b5656bda",
          "sha256": "26f648de622252345d480c106bd52c81248836c37ab3e82db493c805eaf402a1",
          "sha1": "e862fa6d3a9b3cf1a51011654787781640289179",
          "md5": "8cd771b6ca12f646fc55dec1a4e6468c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.2.0-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.2.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "89fe9e2656addfcd280d3a8d49a98d81b0133116b7624a3069d75e48965a18e47cecf14b206c3f70a24eded777557996754702b2909675972953304467c90a83",
          "sha256": "2e11261e3af7853e9efee77f3a48d73b4cb42aa647d8b87d66971d5d478d03ae",
          "sha1": "eae329b8226789258d15d359a05c4a962a15c189",
          "md5": "45388057a805ab8ba776a4705c9b10b0"
        }
      ]
    }
  ]
}
