{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.2.0-SNAPSHOT.klib",
          "size": 65042,
          "sha512": "2f7efdf3b3657bc893a63103f23bd5351a19e17f256007badfbca2a85703e4aa1787c95a21c088fcff45736262fdb29623d9349455d83d546c317c2e016d5df2",
          "sha256": "7feb71cd33a9f0c62fed3702ef7482bdddd11795f727fb4eabbdbbeb016991f9",
          "sha1": "ae84d6a7f74f31de4b5287236a65410ec7fcfbee",
          "md5": "bdfd2870c5b144b83a0f41fc040a05e6"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.2.0-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.2.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "21be2922f5c8227ff91ba901513050bdca27b33c67d4643616ed1c0a98698e2d916665a7503ee2fe65133139e6afb83e0a9aeee50ff253a0ef67f5afc32225d9",
          "sha256": "91d7a3ea668f397ed3fa49a9e22c87818efea8c8371fc7578231bc0b2a417d8d",
          "sha1": "f5a8bdb52cf3ecdcd5db2e17bf5234bb2addcf00",
          "md5": "38c7ca19e67e553cc0c2b6a856f625da"
        }
      ]
    }
  ]
}
