{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.2.0-SNAPSHOT.klib",
          "size": 79367,
          "sha512": "76d36211207c2f05d3f2071455f1a92d9a3ff4cd187806fe09bff6dabf67dc3486f66d65e5c8ce96dc277d9feb527122832d257501475238ef4b8bb99a9fc345",
          "sha256": "fc121fb50a57e64f1fb305bfb84aef74d32f7e619492c0175ede46208f925020",
          "sha1": "2e7442611e0ece73ab3c607380128bb31c3ffdf4",
          "md5": "884032983b8cde51501fba1704a96521"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.2.0-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.2.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6e1eb5df547330de47293ba4679af3eb3645c94ef38f6a984c77fabc5bfc7be3197c25f33cb93455aba576c9f7292b75e0ba5a17e52db90738eab7486f3cadb4",
          "sha256": "5be768892876249af356ca3b38a9a8deafcfa3339bfc7d1dcf1d47ccb910b2c8",
          "sha1": "e0a2f888c683d42f30727666394b175e6790b11f",
          "md5": "8f7983e879bae2dfb7cf2245f99188f2"
        }
      ]
    }
  ]
}
