{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.2.0-SNAPSHOT.klib",
          "size": 79884,
          "sha512": "2af96a85bc9e88edc1544819c8e19343cd0e7a90349bd429af47726340c3a277d3de0618bca13c1ea0cfaf6502d33d9e40237ee6726b111eb5816d3d2ad807e1",
          "sha256": "dae4ec5c905b8d17a98f2a985ab8d6719cefcf4e2ba731fde110690c8edb0ebe",
          "sha1": "42d136bb9b000efdcca8e8500628068414db6910",
          "md5": "a574dc2712f6883249a17757d23f3086"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.2.0-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.2.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "2a689cfa6f1809416025a2ca7fa31d2dd3cce5d5a058736661f62b495c2776d61116ab4eb431167a97b95e58d179ebdb28befb204693a9e024f5a0711dadfde6",
          "sha256": "75d72150b59fdb46d0c4643f96b0334d6a1c44903b754c0e2718510076ab41df",
          "sha1": "9c80649e6a824506fa9d3db5e69fd364db4a9284",
          "md5": "5f14c5289bbdd0065b548bd5d6c309a4"
        }
      ]
    }
  ]
}
