{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/4f11117/test-utils-annotations-junit5-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-tvosx64-4f11117.klib",
          "size": 7043,
          "sha512": "1c63edc7beff8c107b430a09674c9a667ba69ace1a9f568f10f985c413cdc33d481632a40ef5d0e38dfcca6d01485d99d2c936d31aa1ea1f34ef178857f415a7",
          "sha256": "05b2fbc3bb6638eaacc1657ae62d6e6f3ae7b4ae7d8f82e43a96a9b063fcaa2d",
          "sha1": "a2987b06ed0706c705f5c9b381c121d7da3a580f",
          "md5": "bba78f4957c769222f4b0f86a51e602d"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-tvosx64-4f11117-metadata.jar",
          "url": "test-utils-annotations-junit5-tvosx64-4f11117-metadata.jar",
          "size": 261,
          "sha512": "14be51466729344dd8eac34f0dee90caf0f13ddcade8a77c9282f5eb9a8f036b199b4bb5b47d5c0cbef6c6bcfccda5c5466da43a9fea873baf28bdb078712fb9",
          "sha256": "a5a2b10543b0fd6dc8f3d24878cab1ab413bcd734310339485abb1f5c85f6f0d",
          "sha1": "86cfd6ac826dedbea295bc36fb1fcc057921f7ed",
          "md5": "8a3ed9a8968314fc234762eb219ab3f7"
        }
      ]
    }
  ]
}
