{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/f1aabd0/test-utils-f1aabd0.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "f1aabd0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm-f1aabd0.jar",
          "url": "test-utils-jvm-f1aabd0.jar",
          "size": 8814,
          "sha512": "63ff79a2165205a5e0c20a4734ffaf01d9f975eba585103b6550fbb81939492e07c5e9f9e0ac854f833f6d574df1d3531ebcada7aa82b9798f6cde7e07253fa8",
          "sha256": "b3a0eaf6886a144222e174adee5e31ea9f6e9caac044f608c9b43e4d67323b81",
          "sha1": "855194e128de8e9ff3e151422ca02ecf2e9ff7a4",
          "md5": "74cb126d57e646ab568d0c126224f456"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-f1aabd0.jar",
          "url": "test-utils-jvm-f1aabd0.jar",
          "size": 8814,
          "sha512": "63ff79a2165205a5e0c20a4734ffaf01d9f975eba585103b6550fbb81939492e07c5e9f9e0ac854f833f6d574df1d3531ebcada7aa82b9798f6cde7e07253fa8",
          "sha256": "b3a0eaf6886a144222e174adee5e31ea9f6e9caac044f608c9b43e4d67323b81",
          "sha1": "855194e128de8e9ff3e151422ca02ecf2e9ff7a4",
          "md5": "74cb126d57e646ab568d0c126224f456"
        }
      ]
    }
  ]
}
