{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.dokka",
    "module": "antibytes-dokka-configuration",
    "version": "c189d8a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dokka-configuration-c189d8a.jar",
          "url": "antibytes-dokka-configuration-c189d8a.jar",
          "size": 7894,
          "sha512": "a414c30c7b4a9dd41bb13712fc00e809d3fc24bfda153289522e08514ffb0b8b03ab7bf110cad4e63c7b8cedc0da3bf05bd03540f22bc8ada9f10721d6e28266",
          "sha256": "409aa0e0f7955318cb54f114eb40ec3211fab95e5d002f085795943b53b59739",
          "sha1": "903c4b0a72bb3a3c55e407c51ea0a349554ea7a6",
          "md5": "1e951ad70a3debdce081a3ac58c51226"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "c189d8a"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dokka-configuration-c189d8a.jar",
          "url": "antibytes-dokka-configuration-c189d8a.jar",
          "size": 7894,
          "sha512": "a414c30c7b4a9dd41bb13712fc00e809d3fc24bfda153289522e08514ffb0b8b03ab7bf110cad4e63c7b8cedc0da3bf05bd03540f22bc8ada9f10721d6e28266",
          "sha256": "409aa0e0f7955318cb54f114eb40ec3211fab95e5d002f085795943b53b59739",
          "sha1": "903c4b0a72bb3a3c55e407c51ea0a349554ea7a6",
          "md5": "1e951ad70a3debdce081a3ac58c51226"
        }
      ]
    }
  ]
}
