{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "d1d6651",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-d1d6651.jar",
          "url": "antibytes-gradle-test-utils-d1d6651.jar",
          "size": 15106,
          "sha512": "ac463b84b856be8d19fec634e86120b15d988a7ae85ae55d75fd663e7a7608e5443707dcd4114f119f04f157e9d515274b7d5b0d9f159618495cb5e319dc4283",
          "sha256": "7ac8e2a4fcac13345e405554527a308f3de53f76f6440ebaffb9209ec58b813e",
          "sha1": "5508e883143d21114c4ed2183cbf263c348c5707",
          "md5": "6d1059da8e0463f6aa5379788e5ad6f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.3"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-d1d6651.jar",
          "url": "antibytes-gradle-test-utils-d1d6651.jar",
          "size": 15106,
          "sha512": "ac463b84b856be8d19fec634e86120b15d988a7ae85ae55d75fd663e7a7608e5443707dcd4114f119f04f157e9d515274b7d5b0d9f159618495cb5e319dc4283",
          "sha256": "7ac8e2a4fcac13345e405554527a308f3de53f76f6440ebaffb9209ec58b813e",
          "sha1": "5508e883143d21114c4ed2183cbf263c348c5707",
          "md5": "6d1059da8e0463f6aa5379788e5ad6f9"
        }
      ]
    }
  ]
}
