{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/cba59bc/kmock-cba59bc.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "cba59bc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-cba59bc.jar",
          "url": "kmock-jvm-cba59bc.jar",
          "size": 255257,
          "sha512": "518b601375397944aaf4a3a5973a98c88b0bcce77e2f80f077f110ddfd1f7d9b8cfd929136b3b06c14ac3c254f2438f1bb0ecb6abd254d2b3aa565e21bc99cf1",
          "sha256": "eeeacbe188fa38b1fcfddc594fa559fef42c23ce0c261dec6c9d7831c15d237d",
          "sha1": "3e4c6614cff5da6582f15b07c4a7250b1a265d4b",
          "md5": "6a640ae1571e9e233372871bfb87edc1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-cba59bc.jar",
          "url": "kmock-jvm-cba59bc.jar",
          "size": 255257,
          "sha512": "518b601375397944aaf4a3a5973a98c88b0bcce77e2f80f077f110ddfd1f7d9b8cfd929136b3b06c14ac3c254f2438f1bb0ecb6abd254d2b3aa565e21bc99cf1",
          "sha256": "eeeacbe188fa38b1fcfddc594fa559fef42c23ce0c261dec6c9d7831c15d237d",
          "sha1": "3e4c6614cff5da6582f15b07c4a7250b1a265d4b",
          "md5": "6a640ae1571e9e233372871bfb87edc1"
        }
      ]
    }
  ]
}
