{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/735eeec/test-utils-coroutine-735eeec.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "735eeec",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iossimulatorarm64-735eeec.klib",
          "size": 10207,
          "sha512": "67a84bd839583a7af04524f84d93a94383b5f07448586e3b08a26ef37aec233d9dec4999032e52bc0fc0ce68df71819d88ab2630980877da78f23b3a285c04dc",
          "sha256": "b0f758b401a0e74b573ff24e92ac80ca7ba1a3f365b783c11a4513472f64904d",
          "sha1": "8607c7cd6c78f8ce9cb948cf6cf2d24b98e72bfe",
          "md5": "504a89ab7cc3d05a9b518b00dd4f4c22"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iossimulatorarm64-735eeec-metadata.jar",
          "url": "test-utils-coroutine-iossimulatorarm64-735eeec-metadata.jar",
          "size": 261,
          "sha512": "7be5905fddb8704fd7180a5929f7b6d9bfba674be0da1aa4b557a16afe8ff7aef2db2fee240d4083cf34d2f5bff1fa526a59405ba2f3882632ebf0a790f0deee",
          "sha256": "635fb466a0fa9093d871ce8a0357770bac55fc4333bdf786b15b8f3c05cd0d1a",
          "sha1": "7a26fcb5b44827b23896f120f663f0fed2327ed6",
          "md5": "636cb99ad017899e8f99327a93c18429"
        }
      ]
    }
  ]
}
