{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/f384302/test-utils-annotations-junit5-f384302.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "f384302",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-watchosarm64-f384302.klib",
          "size": 7086,
          "sha512": "5375c934c293382a66ed350449d350206980273045a93130135db1067ee4d254812b2b34ea02d72617f5ff8f82f597b7eab8b7b3f8c4c822bdd3607c34c249a6",
          "sha256": "1432ca394b02f768ce4d7c31117de8116da79ade416cc2a79c33875f09ce239a",
          "sha1": "dccf6ffa23d7083d2b04feaba2746674f7b48b99",
          "md5": "30a4505ceaa9c4c1e2810c9254ef6461"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-watchosarm64-f384302-metadata.jar",
          "url": "test-utils-annotations-junit5-watchosarm64-f384302-metadata.jar",
          "size": 261,
          "sha512": "f098212a6a6cd16badb3e1f38e920f1e63a8db73cfb740c835270a5aa58006078ba375405b2e43d086393fee3d54407bb7d3dc70ad357b4306a2b98f57ebc0aa",
          "sha256": "6d48c2c877eac085fe347ead165a20274af49c2912be9efd0686f94ef9ccd7ce",
          "sha1": "873e0288abe75e1e0c8f26a523dfbe43fcf18670",
          "md5": "8c0ec234faad055626dfb04fdd1892b4"
        }
      ]
    }
  ]
}
