{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "63396e3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n-metadata-all.jar",
          "url": "banana-i18n-63396e3-all.jar",
          "size": 670,
          "sha512": "22c3b540dbc5453c4f217238659c81dc91cc591006cd69b72092a904441465c10581d36877b0b424b240a7b43f8e62d6a9fd5f51dab1b6e3717cca00c583b1d4",
          "sha256": "fb9c2fdf2b4cbd552da63bdf1074bbd5ebd0b04455d560dcc3246ea760728fef",
          "sha1": "c7acf4f3a3a5f58984c742cd4981c96159232596",
          "md5": "4b61119248f9506e501108267c87da2a"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n.jar",
          "url": "banana-i18n-63396e3.jar",
          "size": 13761,
          "sha512": "235641f7a7e76bfa3bd56fe505792a86f0bcc56e1579bc539e785e51744d5723dce7d30dad71c674d4a9d642d5d62a9e85a0df577829bef55c16e0f629fe1bf9",
          "sha256": "98dd5d7c137672bef663e0dd76bfb8aafdb604779dae5c9c796f11495b407c61",
          "sha1": "abfde74ec632db1c69ef584bfad8cd03c3b75bbc",
          "md5": "1b9221ed828f18133294faa2c704ea03"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/63396e3/banana-i18n-android-63396e3.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "63396e3"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/63396e3/banana-i18n-android-63396e3.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "63396e3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/63396e3/banana-i18n-jvm-63396e3.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "63396e3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/63396e3/banana-i18n-jvm-63396e3.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "63396e3"
      }
    }
  ]
}
