{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "65c302e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "65c302e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-65c302e.jar",
          "url": "antibytes-publishing-65c302e.jar",
          "size": 117663,
          "sha512": "65de9b28c385f34b83d4f59e30bc510d0218dc3b5c1e21c6780f469a4d15e8b2472d5933bbb5c458c1cee863c6b7e112b9198462fd2eb9a0ea1eb1a35e1f7e75",
          "sha256": "49870b4a795ff3e22d73ea059908334477cceede7b6d4d9977b2abbd10d32f22",
          "sha1": "fcf1968fc38c6cdf8865fd170347fb46082348f7",
          "md5": "3dff0d4f9df96ee1b6b563c18370f343"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.3.0.202209071007-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "65c302e"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "65c302e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-65c302e.jar",
          "url": "antibytes-publishing-65c302e.jar",
          "size": 117663,
          "sha512": "65de9b28c385f34b83d4f59e30bc510d0218dc3b5c1e21c6780f469a4d15e8b2472d5933bbb5c458c1cee863c6b7e112b9198462fd2eb9a0ea1eb1a35e1f7e75",
          "sha256": "49870b4a795ff3e22d73ea059908334477cceede7b6d4d9977b2abbd10d32f22",
          "sha1": "fcf1968fc38c6cdf8865fd170347fb46082348f7",
          "md5": "3dff0d4f9df96ee1b6b563c18370f343"
        }
      ]
    }
  ]
}
