{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "cfd6317",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-cfd6317.jar",
          "url": "antibytes-grammar-tools-cfd6317.jar",
          "size": 39894,
          "sha512": "dd72abf97832ce124a1733e71256ad46d4692b70888ac762b842fbfff0b42a8801ca7029f600d3548519b5dbf1eeca68008ddd5d4dd03f48469e5d4c38cf119b",
          "sha256": "014ab2a175d5d8a499a2a3f94f14de006bba601148cdb8773c9b50ec12207f07",
          "sha1": "e1b03410ccfc04129ddd58a314cf5bf602c1e492",
          "md5": "aab9608d55bcb798611eff0715c3f151"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-cfd6317.jar",
          "url": "antibytes-grammar-tools-cfd6317.jar",
          "size": 39894,
          "sha512": "dd72abf97832ce124a1733e71256ad46d4692b70888ac762b842fbfff0b42a8801ca7029f600d3548519b5dbf1eeca68008ddd5d4dd03f48469e5d4c38cf119b",
          "sha256": "014ab2a175d5d8a499a2a3f94f14de006bba601148cdb8773c9b50ec12207f07",
          "sha1": "e1b03410ccfc04129ddd58a314cf5bf602c1e492",
          "md5": "aab9608d55bcb798611eff0715c3f151"
        }
      ]
    }
  ]
}
