{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/4f11117/test-utils-annotations-junit5-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-macosx64-4f11117.klib",
          "size": 7050,
          "sha512": "a17acbea12d977f4f28ebbf5f18e23c0c27fb354ccbe569e09ad9bbf969431103a66006aef7eaf0ceddaf11828c14b3ca766c2e73f2ff818f30fe751fd396a4b",
          "sha256": "7956f67a59f38a3b3c69dc9748e14bc1d3ca4b48c9b12b61c1f7ea86bf70406a",
          "sha1": "0cda7c8e43b80a838c697be24988c5f8c2d3bc17",
          "md5": "926054f5ad8f619189bcdf19cfef0601"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-macosx64-4f11117-metadata.jar",
          "url": "test-utils-annotations-junit5-macosx64-4f11117-metadata.jar",
          "size": 261,
          "sha512": "95aa86a1d503e6d4811bc0c6675bca15b723525d6b6a809909d41b75ea198226a1cdf8f5ff4057db37089adb8323411edcfd82c80518c4cbb7a36ed8e856a6d3",
          "sha256": "95663c70b1ad78f6b448c64ff213e77de137b9ba585eb5699da1632bf1628c2d",
          "sha1": "fff6cfbbe6868958aa87b5914afd32163b0b6866",
          "md5": "d1f2286e3d8ef3037df46d7712a4f53c"
        }
      ]
    }
  ]
}
