{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-catalog",
    "version": "03118a6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-03118a6.toml",
          "url": "antibytes-dependency-catalog-03118a6.toml",
          "size": 228942,
          "sha512": "65bc497e8b534ab2e5bc5eaebca8cce00ddb5b339a72151812f9e691542485b1056400c28ba65a3e80068238345170bf59fc472083d79e016a2c32909b238884",
          "sha256": "2c3f339cd4c31792bf60b27890cd93b6c0fe3a57f1fb89d4e2addd901bafa6be",
          "sha1": "cb7faca3cec2785561932e8123cc7067fef46680",
          "md5": "1d66a109b54792a19beccb3b01f82adc"
        }
      ]
    }
  ]
}
