{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "981a535",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-981a535.jar",
          "url": "antibytes-dependency-helper-981a535.jar",
          "size": 68558,
          "sha512": "fd271e1dd7344f1a379294c8c975f2ac0e1161e663d78ddeaabbaa55abd6530c5b793bd71bf27cdc98fd6d116dfcf3350b54a68cf8ebe7f1aeea490ef2005bbe",
          "sha256": "60dc627aaac173f2b7b4e66ba73fe24d0655d1b4934af4c448edeccc9dd77563",
          "sha1": "6bb80c7ea9b9b721a1d42555143262046c37b620",
          "md5": "a9cf1522bd8f8d800173741090aebdf6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "981a535"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-981a535.jar",
          "url": "antibytes-dependency-helper-981a535.jar",
          "size": 68558,
          "sha512": "fd271e1dd7344f1a379294c8c975f2ac0e1161e663d78ddeaabbaa55abd6530c5b793bd71bf27cdc98fd6d116dfcf3350b54a68cf8ebe7f1aeea490ef2005bbe",
          "sha256": "60dc627aaac173f2b7b4e66ba73fe24d0655d1b4934af4c448edeccc9dd77563",
          "sha1": "6bb80c7ea9b9b721a1d42555143262046c37b620",
          "md5": "a9cf1522bd8f8d800173741090aebdf6"
        }
      ]
    }
  ]
}
