{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/cd6e425/kmock-cd6e425.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "cd6e425",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-cd6e425.aar",
          "size": 242237,
          "sha512": "3b8f299fcf034d88a1ff466d9ce22e65478c4c3ecf85d9845834139511d1a11a282b400aa8987b9f25ac8ebc80aec4ba53d81153011698c4210a67303830ce26",
          "sha256": "46817fb95b599599876aa5ea1aae97a61324994bbf4998aa470413ebcdeac2a9",
          "sha1": "c3e9c9f72db64c64467bbeeb10df000c3482315e",
          "md5": "4e47e24ab5b3d53e8b9fe5b8a0fa0c06"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-cd6e425.aar",
          "size": 242237,
          "sha512": "3b8f299fcf034d88a1ff466d9ce22e65478c4c3ecf85d9845834139511d1a11a282b400aa8987b9f25ac8ebc80aec4ba53d81153011698c4210a67303830ce26",
          "sha256": "46817fb95b599599876aa5ea1aae97a61324994bbf4998aa470413ebcdeac2a9",
          "sha1": "c3e9c9f72db64c64467bbeeb10df000c3482315e",
          "md5": "4e47e24ab5b3d53e8b9fe5b8a0fa0c06"
        }
      ]
    }
  ]
}
