{
  "formatVersion": "1.1",
  "component": {
    "url": "../../clientSDK/8b3897f/clientSDK-8b3897f.module",
    "group": "tech.antibytes.awesomecats",
    "module": "clientSDK",
    "version": "8b3897f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result",
          "version": {
            "requires": "05a4d20-customize-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "clientSDK.klib",
          "url": "clientSDK-tvosarm64-8b3897f.klib",
          "size": 45941,
          "sha512": "8d2078b6cc9717e909efca344bd2a1ad5267076ba0148f9f758931d4f553a95cbee09e84187781857923522875a83d5b9da456d17a5e57dd98953836e3775be2",
          "sha256": "bf4032dfae0e2f1ab9c3454a3eabf56663e1bad71c33c5a82e22d0074f99e288",
          "sha1": "397f9b401e3b4536d6dfd7e863c741654041e4ae",
          "md5": "c6ea9c0f00a6708f98a4491dbbd63153"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result",
          "version": {
            "requires": "05a4d20-customize-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "clientSDK-tvosarm64-8b3897f-metadata.jar",
          "url": "clientSDK-tvosarm64-8b3897f-metadata.jar",
          "size": 261,
          "sha512": "fc5a0ab112f40a2637e39defd68df8a420a0a2fb7cefd3ba54b88045ba6339ab4541de5c1de7f9544d5eeedd55c48c8302075e53dee04201fca9ac4282588c51",
          "sha256": "3f6bdc5c10284d66791d4f73d47fe0f689793721e7f00ea7241fa048daa1503d",
          "sha1": "89927a624dccdc7c83faf2b76993437126453ab1",
          "md5": "e3f856982dc65b77e4a38448628a13ad"
        }
      ]
    }
  ]
}
