{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "fa31c9e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-fa31c9e.jar",
          "url": "antibytes-grammar-tools-fa31c9e.jar",
          "size": 39410,
          "sha512": "6903f5eb212fb1976e66212cd365b530e9ed12a9042e4edc0c01d2ff94550e44a89fe6927e03064084b2091386ba9eed292f75b693780639ddc9a6b2193a3169",
          "sha256": "e71c24c20b747efd43f13eacf8bc20782a12df9660456823d1d81227ba105176",
          "sha1": "ffa92c96028c1c6f4b2f06c75b0350c7f7248b35",
          "md5": "d3d68bbb64bc80ecd49849632301547a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-fa31c9e.jar",
          "url": "antibytes-grammar-tools-fa31c9e.jar",
          "size": 39410,
          "sha512": "6903f5eb212fb1976e66212cd365b530e9ed12a9042e4edc0c01d2ff94550e44a89fe6927e03064084b2091386ba9eed292f75b693780639ddc9a6b2193a3169",
          "sha256": "e71c24c20b747efd43f13eacf8bc20782a12df9660456823d1d81227ba105176",
          "sha1": "ffa92c96028c1c6f4b2f06c75b0350c7f7248b35",
          "md5": "d3d68bbb64bc80ecd49849632301547a"
        }
      ]
    }
  ]
}
