{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.2.2-SNAPSHOT/kmock-0.2.2-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.2.2-SNAPSHOT.jar",
          "url": "kmock-jvm-0.2.2-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "df5292f770268f7158030bfcb6855ef057a46e200d5689811eca2f330b8ee204cdcad0e92c72935eb33a283a88571066c4538d1c5e877e48f4564c99fa986c19",
          "sha256": "1f8815c1c706d432eeb104510281e7b8c98effa51e68557713f4298805f4a587",
          "sha1": "52ed1bf6f9f687c249cb992f58d39cbe69658ae6",
          "md5": "d9d8654e559ced2ff513b3dcfaddf949"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.2.2-SNAPSHOT.jar",
          "url": "kmock-jvm-0.2.2-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "df5292f770268f7158030bfcb6855ef057a46e200d5689811eca2f330b8ee204cdcad0e92c72935eb33a283a88571066c4538d1c5e877e48f4564c99fa986c19",
          "sha256": "1f8815c1c706d432eeb104510281e7b8c98effa51e68557713f4298805f4a587",
          "sha1": "52ed1bf6f9f687c249cb992f58d39cbe69658ae6",
          "md5": "d9d8654e559ced2ff513b3dcfaddf949"
        }
      ]
    }
  ]
}
