{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/766ba9c/test-utils-coroutine-766ba9c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "766ba9c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosx64-766ba9c.klib",
          "size": 10112,
          "sha512": "0c9109497ef5116df57d780fb9927fa9a211b8c342a4a7fbb3461b555cfc0a69658dd4d762d29aeb47083f1264b99df98abe9ca148acfe1f7227ae8e67041ad7",
          "sha256": "2da8c8de1522ad369562f0bd2b838eba30fdb3b2eefa319776aab12fff1d9c69",
          "sha1": "3d1c065ed2929a8a21b7209b42256a163e080647",
          "md5": "6e8825ff0ee058c6b2a9aeeefd714a50"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosx64-766ba9c-metadata.jar",
          "url": "test-utils-coroutine-iosx64-766ba9c-metadata.jar",
          "size": 261,
          "sha512": "025d5d4ea7ff7524a25d2079d40f1f7cf91056cce90b0e1b3f4defe38a531468a9767935d39d2e5b46a83920749407ff7af02a9b0887abbbfb1ce667bce92a2a",
          "sha256": "6073b0a7190dcf229fac0e87cb53f1d3670a0b16744a7a505fdb5dca0d8dd718",
          "sha1": "13a0d98b086bfbf1189e1741984ca5ed5503cb8a",
          "md5": "688f1032f941a61e0317b141c5acf80e"
        }
      ]
    }
  ]
}
