{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/cf35c27/test-utils-annotations-cf35c27.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "cf35c27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-iosarm64-cf35c27.klib",
          "size": 11206,
          "sha512": "e9562f03031aa7abee62526f5e739b1858744318b7efbf5e7291e9ae6fa548f953dc83631f1e7dbb0a8bc51fc6252f005a9113601c9698bf609c353c22bce330",
          "sha256": "a5fe8090f5933950ba1733d903ced5a0e277e0cb636ddc304a31159801997823",
          "sha1": "686b666520a4650ae31c0da052e2521774140e78",
          "md5": "a2a22e79f2cafc4d4cbfbde1687a94dc"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-iosarm64-cf35c27-metadata.jar",
          "url": "test-utils-annotations-iosarm64-cf35c27-metadata.jar",
          "size": 261,
          "sha512": "d94ef34f3236d11601f233157c7b95dd38d9fe7d038c55fafef9ff171c4a356e639188b9bba1b1c45035c6ddba6845f2324263173ee09a0ae766d5e10a82c982",
          "sha256": "aae209b78347c37ce6e445522472b03635b36471489d047a58e8187557877b7e",
          "sha1": "25ac6a92f48a0e5a6272f51fbfb62ee7a0da7a01",
          "md5": "25a6aae98bb75c4644c0e671da243062"
        }
      ]
    }
  ]
}
