{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc08-SNAPSHOT/kmock-0.3.0-rc08-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc08-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-tvosx64-0.3.0-rc08-SNAPSHOT.klib",
          "size": 217331,
          "sha512": "7c054ba77b393843d7b7452c339282117ce54ab6d0032ed4dee35d5d71649fb0702323acc2e4e93e957c44fa04ee5f0948f777c350761507dbcc2d20a2c9ecf7",
          "sha256": "1a94085dfcaeae1c864a3dcddb938ef9af77fb8dcd62aab4aef8b9510f3a43cf",
          "sha1": "7cb9b70a3c9b898e70890aca062a1ebca7a323f4",
          "md5": "4e06a316c15520ea471ac7eed270d804"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmock-tvosx64-0.3.0-rc08-SNAPSHOT-sources.jar",
          "url": "kmock-tvosx64-0.3.0-rc08-SNAPSHOT-sources.jar",
          "size": 48100,
          "sha512": "f707cf94d0d475a5c0835acbd9284d064cfa4bb1e121bddb54e4352f09b96d39ec1332895e3bd15192004ac46d03745cc71551e653e16fd6cf100c948b97a755",
          "sha256": "815c70413b4f7941f982cca7eb609a6dfd390eeea9ad52c91e2bef8a5e376132",
          "sha1": "97707ee87f320e64e5d2055ffb8d0afb4b667393",
          "md5": "bb1c1fff293de6ee4509b2e38ad20854"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-tvosx64-0.3.0-rc08-SNAPSHOT-metadata.jar",
          "url": "kmock-tvosx64-0.3.0-rc08-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7f640d498e9868912e8fa18dea31114c8e061196c18de895a60537d8a0f48ee6da030391fc4db8f9d2e6aa1c06ace63d0ca749c689b2a0edc5c6f0ef6527bac9",
          "sha256": "221cb2a58e8e9410223ef135e80c8477a3c20d51eadc4beb630a75765aadcd6b",
          "sha1": "546aba4231147d4f3f8fcadb024e900bf1f3bd8b",
          "md5": "f63304cc75b09760b94fa6e01cceb20b"
        }
      ]
    }
  ]
}
