{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency",
    "module": "antibytes-dependency",
    "version": "158710b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-158710b.jar",
          "url": "antibytes-dependency-158710b.jar",
          "size": 88198,
          "sha512": "bffe51fa91bd51e3d9bc273bf12c228cab43c5da466b9b047bf50357098169be5a3b62dac53e48d938d0a30b131152ec6db922115985b37e96482fb6add84af9",
          "sha256": "1e52d15472f52310f813f57bc2f32e08896ddc8b12ede270fe71dd0c6ac13b9b",
          "sha1": "4dec04adfa034d8ecfcb548237fc7436d4bb24df",
          "md5": "744761633f5515082a5c9e4ffb3d5d47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          },
          "excludes": [
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-xml"
            }
          ]
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "158710b"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-158710b.jar",
          "url": "antibytes-dependency-158710b.jar",
          "size": 88198,
          "sha512": "bffe51fa91bd51e3d9bc273bf12c228cab43c5da466b9b047bf50357098169be5a3b62dac53e48d938d0a30b131152ec6db922115985b37e96482fb6add84af9",
          "sha256": "1e52d15472f52310f813f57bc2f32e08896ddc8b12ede270fe71dd0c6ac13b9b",
          "sha1": "4dec04adfa034d8ecfcb548237fc7436d4bb24df",
          "md5": "744761633f5515082a5c9e4ffb3d5d47"
        }
      ]
    }
  ]
}
