{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "b821e91",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-b821e91.jar",
          "url": "antibytes-grammar-tools-b821e91.jar",
          "size": 39394,
          "sha512": "5a0f33dc84c22f139d8b3589d9866321fa072d9e7cd0de04f04c06a98f7c2a9c938eebac5a7aacf5db67c062c6cf782db73bf96fae8c6daa0423e2eca73818e8",
          "sha256": "bd5944696d09a333ebc2d18e1cf9d7b5d62dcf875bc0fb5ad6e9ca531c155f07",
          "sha1": "488213b454acc62e8bf2b8e1211004258fd8b514",
          "md5": "79b94cfbdf4db8d94149612e6c45f0b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-b821e91.jar",
          "url": "antibytes-grammar-tools-b821e91.jar",
          "size": 39394,
          "sha512": "5a0f33dc84c22f139d8b3589d9866321fa072d9e7cd0de04f04c06a98f7c2a9c938eebac5a7aacf5db67c062c6cf782db73bf96fae8c6daa0423e2eca73818e8",
          "sha256": "bd5944696d09a333ebc2d18e1cf9d7b5d62dcf875bc0fb5ad6e9ca531c155f07",
          "sha1": "488213b454acc62e8bf2b8e1211004258fd8b514",
          "md5": "79b94cfbdf4db8d94149612e6c45f0b4"
        }
      ]
    }
  ]
}
