{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.quality",
    "module": "antibytes-quality",
    "version": "a821fe5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-quality-a821fe5.jar",
          "url": "antibytes-quality-a821fe5.jar",
          "size": 62609,
          "sha512": "664f24cdd04fdebc57fec99b4c592622a7510edaa007cc354a8cb72a4dc76d1a10a44bcb8f505cf1d2322f3bf6c0c0df026c1ca0d2d8f2815de02a213e641dfc",
          "sha256": "00efb99f763ae04c3c90e071402518c16d61e554b42334a1e6883ccd0b276b0b",
          "sha1": "896749752d29aa8531a79281e1abc4a41eae0082",
          "md5": "bb9bf5376e227ce0ce8db80f4680a240"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.21.0"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "a821fe5"
          }
        },
        {
          "group": "tech.antibytes.gradle.dependency.helper",
          "module": "antibytes-dependency-helper",
          "version": {
            "requires": "a821fe5"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-a821fe5.jar",
          "url": "antibytes-quality-a821fe5.jar",
          "size": 62609,
          "sha512": "664f24cdd04fdebc57fec99b4c592622a7510edaa007cc354a8cb72a4dc76d1a10a44bcb8f505cf1d2322f3bf6c0c0df026c1ca0d2d8f2815de02a213e641dfc",
          "sha256": "00efb99f763ae04c3c90e071402518c16d61e554b42334a1e6883ccd0b276b0b",
          "sha1": "896749752d29aa8531a79281e1abc4a41eae0082",
          "md5": "bb9bf5376e227ce0ce8db80f4680a240"
        }
      ]
    }
  ]
}
