{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "8419fcc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "8419fcc"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-8419fcc.jar",
          "url": "antibytes-mkdocs-8419fcc.jar",
          "size": 12083,
          "sha512": "6523320c0243e0c243c166534c23ef477cd58d737f1ff26b762664f353189a4f60b7a073de0c247d92b5d848d23d3d967d00d2143b3de271d8d962b7ee49a177",
          "sha256": "c29943261b77f2ea766b54d95596f81019d299423015aab063949776aa8150ec",
          "sha1": "1b5173d03a10314a8b05765bdeb79b591fe413ce",
          "md5": "c658679bae191391d080413d20f81a54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "8419fcc"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "8419fcc"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-8419fcc.jar",
          "url": "antibytes-mkdocs-8419fcc.jar",
          "size": 12083,
          "sha512": "6523320c0243e0c243c166534c23ef477cd58d737f1ff26b762664f353189a4f60b7a073de0c247d92b5d848d23d3d967d00d2143b3de271d8d962b7ee49a177",
          "sha256": "c29943261b77f2ea766b54d95596f81019d299423015aab063949776aa8150ec",
          "sha1": "1b5173d03a10314a8b05765bdeb79b591fe413ce",
          "md5": "c658679bae191391d080413d20f81a54"
        }
      ]
    }
  ]
}
