{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "65d8995",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-65d8995.toml",
          "url": "antibytes-dependency-catalog-65d8995.toml",
          "size": 232498,
          "sha512": "8a1707604adbff51880a3245d437277f3d26ba798ad9f40410a455323f1524fa90c7bf1bd51707b29015cd9ff5c9e1b390e6c7f41058cacb6c3b2a51739d676d",
          "sha256": "0facd85928c85213f9cc7f75d243e17807b3a932bea7ba3fde7ca869aec12d36",
          "sha1": "e608c0f9c75d5eae035e27ef0726ec7a4243903c",
          "md5": "9fbf88d0a7544cd567dd59634e0e29ea"
        }
      ]
    }
  ]
}
