{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.settings",
    "module": "antibytes-dependency-settings",
    "version": "2ebcd5b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "2ebcd5b"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-2ebcd5b.jar",
          "url": "antibytes-dependency-settings-2ebcd5b.jar",
          "size": 17994,
          "sha512": "e70ebb2d21ba64dc199f2c586092ab3b69935d9136d99c58c703a5d50080ddbae8b98c74ef648b3910a546b9d30b725939a2fc3e1bf30016c19f614832a247d4",
          "sha256": "49782065df33647b4c9adec1b1e11fd81ea5c8f9c17c2478c11b6433760c83e6",
          "sha1": "c354065a1ae16a12b440cfba224c0c4a7ee28171",
          "md5": "a652334e5cc306c852f13335222f1ec6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains",
          "module": "foojay-resolver",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "2ebcd5b"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-2ebcd5b.jar",
          "url": "antibytes-dependency-settings-2ebcd5b.jar",
          "size": 17994,
          "sha512": "e70ebb2d21ba64dc199f2c586092ab3b69935d9136d99c58c703a5d50080ddbae8b98c74ef648b3910a546b9d30b725939a2fc3e1bf30016c19f614832a247d4",
          "sha256": "49782065df33647b4c9adec1b1e11fd81ea5c8f9c17c2478c11b6433760c83e6",
          "sha1": "c354065a1ae16a12b440cfba224c0c4a7ee28171",
          "md5": "a652334e5cc306c852f13335222f1ec6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-settings-2ebcd5b-javadoc.jar",
          "url": "antibytes-dependency-settings-2ebcd5b-javadoc.jar",
          "size": 261,
          "sha512": "eea0e132c79fb36e31a5e501ea7d6b44c656d47d6685edbb6ba09d4d661a36c4d8acfcc5703c4b2b514edb4cd72e3c1bf3a4de79b00d03e8e8bbc2efdcf86387",
          "sha256": "867f33ba293497c52b90107cdb319602bbac30e73935bb8542ff268cab941b6b",
          "sha1": "0ab95a064a5a5e11e50b46906aa3f9e087909ba4",
          "md5": "80cf5a5daf4ee12488af3c92737a75ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-settings-2ebcd5b-sources.jar",
          "url": "antibytes-dependency-settings-2ebcd5b-sources.jar",
          "size": 3873,
          "sha512": "6043c338199d22cc286975f5aefcf028b49aa069ef73a3b7e27de018cae4548f7f8f32a799abf322c7c15d47daf8d2dd8f9ebcf6abba3333c7f47f3f256e34f8",
          "sha256": "a5dff77a1afd4f3e051a3640b1588989ce6985e41bce9dc6186ebfec822b77fa",
          "sha1": "06e839b0d83d64136383b3485309da29945d3c5d",
          "md5": "c65a872b10dfe00bdb1955ec6a8927c1"
        }
      ]
    }
  ]
}
