{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/b6c6e6c/test-utils-resourceloader-b6c6e6c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "b6c6e6c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-js-b6c6e6c.klib",
          "url": "test-utils-resourceloader-js-b6c6e6c.klib",
          "size": 10089,
          "sha512": "f6ae3892f1e61876c8b7e324543292b4a9ba4f555f5296aa62e25a6e9248926745e06dd177dbec79d46cfb4efee2aea2bd5261361b520b3d9bcb9823182c4b2c",
          "sha256": "5dfa8b2918665ad37322ec51f50ae93dcff5f28e0d8964243a2bf6f3ae983ae0",
          "sha1": "10dec5fa64c3c70a809c1fb4b76356501a532be4",
          "md5": "de3fa76be9a16aaf94d7e078cf36bb47"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-js-b6c6e6c.klib",
          "url": "test-utils-resourceloader-js-b6c6e6c.klib",
          "size": 10089,
          "sha512": "f6ae3892f1e61876c8b7e324543292b4a9ba4f555f5296aa62e25a6e9248926745e06dd177dbec79d46cfb4efee2aea2bd5261361b520b3d9bcb9823182c4b2c",
          "sha256": "5dfa8b2918665ad37322ec51f50ae93dcff5f28e0d8964243a2bf6f3ae983ae0",
          "sha1": "10dec5fa64c3c70a809c1fb4b76356501a532be4",
          "md5": "de3fa76be9a16aaf94d7e078cf36bb47"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-js-b6c6e6c-sources.jar",
          "url": "test-utils-resourceloader-js-b6c6e6c-sources.jar",
          "size": 4118,
          "sha512": "10500eca4460314138ffd86b12597eb1f9b715147250d23404b02e41f5a253bd6968cfdca31df6d36fa77940feafa181b6a3b87408604e8b0c20c0c055018178",
          "sha256": "a2b8ed2b8a49875afa45caa73c7848377508143c4549a7be0e22a307254b37db",
          "sha1": "b975524b6a03b6e4db3aac7e35ac19c5a1c221ae",
          "md5": "e9e01fb4a2f2ad95390a36eece41f8d6"
        }
      ]
    }
  ]
}
