{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/f384302/test-utils-annotations-junit5-f384302.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "f384302",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-iossimulatorarm64-f384302.klib",
          "size": 7135,
          "sha512": "11d345fc64f6e9dec68c63102b2576443704c52100e65b33faaf3b8b08337be245f194456ea51e65cfabe34feef1add181af829ce7885a7977d5d41005286531",
          "sha256": "7aad63ef12408ddf057d9a90d3cd85bbde21ba77747fb5fd197ec32db68a5fd7",
          "sha1": "795460f85c22927d3586a3b92de139e140806fa2",
          "md5": "a422756344bc796618ae9c6a89dd1ed7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-iossimulatorarm64-f384302-metadata.jar",
          "url": "test-utils-annotations-junit5-iossimulatorarm64-f384302-metadata.jar",
          "size": 261,
          "sha512": "f0a7dfab0288d976c6ca59fac4d124b38bd75f9b0d47e8b2a0c083babff391824363a5d8e7b8746f0538ef84c77f1d5be02a2337176e8c932f0103ec4792af35",
          "sha256": "5904084f818d1dc2d9c2adbde896d0be2d00728325fb3fc1854cac9349778312",
          "sha1": "6808588584029943b0a73236f59ff006832d0927",
          "md5": "99355add3325b833d41324e04851e6d2"
        }
      ]
    }
  ]
}
