{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "a3cc152",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-a3cc152.jar",
          "url": "kmock-gradle-a3cc152.jar",
          "size": 50491,
          "sha512": "888fe55eb49662a3126d28b3420cdc7a7a69be7304b8eaf02a9e5e12718b5513e24755062d0eaccb49a3ed57c5b65d34d267edf05dad30048b7dd98496125646",
          "sha256": "55696d9786df2c9f774337d09bfaf29b84418acc3bcc231b422f2d4e707f4388",
          "sha1": "8aef65a30ecc12ae214f5324a14f56352630ee10",
          "md5": "3584509590a72b077ab95671443706dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-a3cc152.jar",
          "url": "kmock-gradle-a3cc152.jar",
          "size": 50491,
          "sha512": "888fe55eb49662a3126d28b3420cdc7a7a69be7304b8eaf02a9e5e12718b5513e24755062d0eaccb49a3ed57c5b65d34d267edf05dad30048b7dd98496125646",
          "sha256": "55696d9786df2c9f774337d09bfaf29b84418acc3bcc231b422f2d4e707f4388",
          "sha1": "8aef65a30ecc12ae214f5324a14f56352630ee10",
          "md5": "3584509590a72b077ab95671443706dc"
        }
      ]
    }
  ]
}
