{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/8c5f468/test-utils-8c5f468.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "8c5f468",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iossimulatorarm64-8c5f468.klib",
          "size": 14405,
          "sha512": "a83f77382284dc34042a29118c65e364fda5f87b90e7f94435bec85fb1decc5cbdcf90700fdb923f9eaaf0b78b510c4e2829431f37750f322971fa5016bab1ab",
          "sha256": "df5c1c6e76e8d90512ebb6607b0347d4c076a929b5c9b1ebe1f919c5f52dbf82",
          "sha1": "bc592cbed3c070d337e93db635b8046bad950758",
          "md5": "764862a43813ad1f5f4681b9d1726518"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iossimulatorarm64-8c5f468-metadata.jar",
          "url": "test-utils-iossimulatorarm64-8c5f468-metadata.jar",
          "size": 261,
          "sha512": "0f4d93950a8d1868dd8ed377f4b2c9c4d995848c8122c17334b2b56447e57ba5cbd92330ebd4d7b1a218ff4140c73e0a5a238d834b633933ffc4c4e250d2a2e4",
          "sha256": "5139862bf00864a92a5fe95cd12a1e90b5713165de2421f7f8ec245488d46d98",
          "sha1": "715aceede0c7e32d79a86b7be4e2bc4652faffc4",
          "md5": "f3c081cdaf590898ddae525a5a6065a1"
        }
      ]
    }
  ]
}
