{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "988d949",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-988d949.jar",
          "url": "antibytes-gradle-utils-988d949.jar",
          "size": 11392,
          "sha512": "c210190ea62b2858dc8ca272d2fad7ea86ebe43c9bd5b88811805b085073a600a77e5af46a2e09394f1f21311c99f9f1ccaa5b4e2cb04ce4920b5d0ba349f79a",
          "sha256": "5b119c6007e0430ff2c258c5a6e2edb73ae575117b8f9c0d208b4d7f349337e1",
          "sha1": "9f2189d5bb86a054745ae0324c59c761bc24692f",
          "md5": "b0f87d25e5d6c940d32c8f609e9474a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-988d949.jar",
          "url": "antibytes-gradle-utils-988d949.jar",
          "size": 11392,
          "sha512": "c210190ea62b2858dc8ca272d2fad7ea86ebe43c9bd5b88811805b085073a600a77e5af46a2e09394f1f21311c99f9f1ccaa5b4e2cb04ce4920b5d0ba349f79a",
          "sha256": "5b119c6007e0430ff2c258c5a6e2edb73ae575117b8f9c0d208b4d7f349337e1",
          "sha1": "9f2189d5bb86a054745ae0324c59c761bc24692f",
          "md5": "b0f87d25e5d6c940d32c8f609e9474a6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-988d949-javadoc.jar",
          "url": "antibytes-gradle-utils-988d949-javadoc.jar",
          "size": 261,
          "sha512": "c63999c7235f7516326703cb4ebceac7a48da015147f87e38b85919aa396f51e4f4edd95a113dfaedfe82736b4a764ada665edf760c558b2bded926b32008e31",
          "sha256": "6b3eb615d2ccadb4da08a843f5cf1f02ca44b42d33f8a8844b0330ffb00fdbeb",
          "sha1": "e42e30ec3f7a5208b7d295eaa2cc9441e9ee8ca1",
          "md5": "f02b87f3c54ebefcb5aa91e5e76c4d93"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-988d949-sources.jar",
          "url": "antibytes-gradle-utils-988d949-sources.jar",
          "size": 3524,
          "sha512": "ce1903aad70f23b14088675d51250c68436378b506a821e7daf5a484d21eb0874a0cfba11aca8e1c799e6acd42d023d8f2d2aa161e530d9f87538a16aced8c18",
          "sha256": "a860d4d200eed7a97975480037d83018f95846bac6ae7fafa4b95f237edf48eb",
          "sha1": "f6860f59d4a190cf80a333f56469317e6a59a7d4",
          "md5": "69e56294af04816bfed49084689ba6fd"
        }
      ]
    }
  ]
}
