{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/cf35c27/test-utils-coroutine-cf35c27.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "cf35c27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosx64-cf35c27.klib",
          "size": 10106,
          "sha512": "4a9b0d8c6bbf29ff8559ce506c4140361e592a3810e352628bab3fd6f9c249c12dfcb69848e604020a0e587822b6c5f99ade82bdeaec71415f0726a3e008888a",
          "sha256": "c3bea4f9fd5a4e958a9a1b6d1f53c9d203f36f6249be2a6bcca2b1958635377d",
          "sha1": "ab8b1719020ab655506f34a4b6f2ef27d35a9acf",
          "md5": "c00982d032e9baadf7a58f15156d1104"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosx64-cf35c27-metadata.jar",
          "url": "test-utils-coroutine-iosx64-cf35c27-metadata.jar",
          "size": 261,
          "sha512": "a005cf1f4e9c63d2e4a1fbabdd92c4e40679a0c3189d7d57f4a5fbba15a94169a65540b049ea8c9c9cae2a57780dcc21253c2f2fe90e46dbbfa6341b6e1fd436",
          "sha256": "95cac755680bd716e84352f2f8f6becf233ea7e756c7a6b8870a295b020f8564",
          "sha1": "2f1da2fdc12b772d0bd1f3d7e5af2cde9a5ad755",
          "md5": "bc05dbdc7918e5740b29f077af218fa8"
        }
      ]
    }
  ]
}
