{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/61a6ee5/test-utils-resourceloader-61a6ee5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "61a6ee5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iossimulatorarm64-61a6ee5.klib",
          "size": 12951,
          "sha512": "ef348779e4f1a42ca14d1dd5d6094f4b858a6ef6384c064af86a44b80f149a4a46f326676f3f5393fd964d4ec2669d7f49fdfa989bc2db6cd7a034b165ab10d3",
          "sha256": "31e73ccaffabdf9994f5dc643372a6f48ac9f9a19901d96122bdcf6c17c5f997",
          "sha1": "2999a2a2e1f8572af551acb6600ae6a6aa5eed48",
          "md5": "66321d6a894f9bdf98de4e775614d366"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iossimulatorarm64-61a6ee5-metadata.jar",
          "url": "test-utils-resourceloader-iossimulatorarm64-61a6ee5-metadata.jar",
          "size": 261,
          "sha512": "93524b8485e5309a933a675a3567630eea1948e8aa0c3fff653f955a827c578fe4de48876659a63992f488df7378e709931b378820187a26cb23ff1a11232647",
          "sha256": "6e73b753d7fc091b224350182e9eeb9320c53c373571faec79eaec834825a1e6",
          "sha1": "d131ef424f276ff4cbcfd134b28a67eac667b240",
          "md5": "00daa06c1729235873231bf1791da2a6"
        }
      ]
    }
  ]
}
