{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-catalog",
    "version": "3831237",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-3831237.toml",
          "url": "antibytes-dependency-catalog-3831237.toml",
          "size": 229586,
          "sha512": "a3266070be9752823948f2f556f6c0700af31fc097ddb981148b672524cc36b9ab09e4c942c964759726e39964e3f3e2750cc71f0b9f117422b514007ac5e4e2",
          "sha256": "fd3592c73a6b7b56cea67e9b387740ccbabcc568f7b028e9979f864353064949",
          "sha1": "a95cb87e46cfcbe12090fafdcc70cf15717f658a",
          "md5": "6ae28b0b159f01d90e9f9cc15d38793a"
        }
      ]
    }
  ]
}
