{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc06-SNAPSHOT/kmock-0.3.0-rc06-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc06-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-linuxx64-0.3.0-rc06-SNAPSHOT.klib",
          "size": 202467,
          "sha512": "18c7f1230cdf2200cbe92aa2e847f172e8280336bf66128f2667d1b025eedefebbf0380d6cc70d0a746fdf36c08658a76610e07974b375efdf6f3177cfe3997c",
          "sha256": "37dd55d13642475536432143cb485a8e3431d5adf34e09c569aee565a71a1757",
          "sha1": "8dd797d2906886fc035561966a226922ea42e6ba",
          "md5": "f26428d8d9a217a2d88402316f7f3e30"
        }
      ]
    }
  ]
}
