{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.dokka",
    "module": "antibytes-dokka-configuration",
    "version": "42d3d0a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dokka-configuration-42d3d0a.jar",
          "url": "antibytes-dokka-configuration-42d3d0a.jar",
          "size": 7889,
          "sha512": "9cc20afdc0e477c49570a3bb8a31e339e13bdcfa790895e4bc2230c717b2ebf2bcca98857aafec5f07131d1cbe4ccfbbe162b7762d97533571691c6669108306",
          "sha256": "9ad8d10c1b825ca17967e668474c2bdfdfe29242e3b6d98cc0ab856cb4eb74b3",
          "sha1": "3ae2ba4c1cd0b9ff74fac0df3cf8cbe9e43a8831",
          "md5": "f1e7658efae92312bfab28fcfdc98f78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "42d3d0a"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dokka-configuration-42d3d0a.jar",
          "url": "antibytes-dokka-configuration-42d3d0a.jar",
          "size": 7889,
          "sha512": "9cc20afdc0e477c49570a3bb8a31e339e13bdcfa790895e4bc2230c717b2ebf2bcca98857aafec5f07131d1cbe4ccfbbe162b7762d97533571691c6669108306",
          "sha256": "9ad8d10c1b825ca17967e668474c2bdfdfe29242e3b6d98cc0ab856cb4eb74b3",
          "sha1": "3ae2ba4c1cd0b9ff74fac0df3cf8cbe9e43a8831",
          "md5": "f1e7658efae92312bfab28fcfdc98f78"
        }
      ]
    }
  ]
}
