{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "558fe4c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "558fe4c"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-558fe4c.jar",
          "url": "antibytes-publishing-558fe4c.jar",
          "size": 111246,
          "sha512": "9e496e43b1d2a8cae623e2552ef50ba3cc5fd827a4adaf66ac7e139aeab6ebe6891df6fab52cdf534c0488aec8d709496ec66abc5e17705c06e8166895c884e1",
          "sha256": "1afeac24b25f5ea51a91f6a2beb3cfe762b87a9d86c347d0a66f6ecea6b7da90",
          "sha1": "d2e2af62fed7b9a955aad2694be613a766d4bae1",
          "md5": "7d48d463066eb4ce78a7147e892f2e2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.1.0.202203080745-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "558fe4c"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "558fe4c"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-558fe4c.jar",
          "url": "antibytes-publishing-558fe4c.jar",
          "size": 111246,
          "sha512": "9e496e43b1d2a8cae623e2552ef50ba3cc5fd827a4adaf66ac7e139aeab6ebe6891df6fab52cdf534c0488aec8d709496ec66abc5e17705c06e8166895c884e1",
          "sha256": "1afeac24b25f5ea51a91f6a2beb3cfe762b87a9d86c347d0a66f6ecea6b7da90",
          "sha1": "d2e2af62fed7b9a955aad2694be613a766d4bae1",
          "md5": "7d48d463066eb4ce78a7147e892f2e2f"
        }
      ]
    }
  ]
}
