{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.java",
    "module": "antibytes-java-configuration",
    "version": "f6a864b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-java-configuration-f6a864b.jar",
          "url": "antibytes-java-configuration-f6a864b.jar",
          "size": 5214,
          "sha512": "2d31dceda887fe74732df75b4705e881fe1662f1849f5bc3241984ad7a5f1d2a3927b9527b62db4018fe7ed399e0e8552951e3efb1f727c0c41fc11d1edfb9b6",
          "sha256": "25b6c04d9873118588b699456868238758782cef10749134dc1b71cec1859305",
          "sha1": "ad3446fe352a2cdbca23c9b933553baca41d1906",
          "md5": "c1df85007e3d7148a1d279f0f3081b3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "f6a864b"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-java-configuration-f6a864b.jar",
          "url": "antibytes-java-configuration-f6a864b.jar",
          "size": 5214,
          "sha512": "2d31dceda887fe74732df75b4705e881fe1662f1849f5bc3241984ad7a5f1d2a3927b9527b62db4018fe7ed399e0e8552951e3efb1f727c0c41fc11d1edfb9b6",
          "sha256": "25b6c04d9873118588b699456868238758782cef10749134dc1b71cec1859305",
          "sha1": "ad3446fe352a2cdbca23c9b933553baca41d1906",
          "md5": "c1df85007e3d7148a1d279f0f3081b3b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-java-configuration-f6a864b-javadoc.jar",
          "url": "antibytes-java-configuration-f6a864b-javadoc.jar",
          "size": 261,
          "sha512": "106aa73b6aec9ab049c2cd2917282a9266c727970cf40acb4afc14fb090c22aff9645c72e5851a32a0b3edc4e37364b5ae6c36ea9d86aa6d4d9d485b3e6e3bac",
          "sha256": "4cb5c2cd4d9bfebfc03a2de0972501b8fa99c7ad3dc12fee85d55c425e5c70f4",
          "sha1": "ef5df42768e4cb68e4130297cbf6c880c6c080d8",
          "md5": "5d0df18b924ed3b90224127c4b2e0a69"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-java-configuration-f6a864b-sources.jar",
          "url": "antibytes-java-configuration-f6a864b-sources.jar",
          "size": 2041,
          "sha512": "9119d3ab99201ce5867cb92d7fb9027bad974551b1d92ddaf2353c7d8c3b5f012a5201b07839b7e2d0fd4f062641aba6b58ea738514c8a8ef49f4e72ee6f8125",
          "sha256": "006b0564419747a760fbfa55f642bc6ceb1da531baa9ee41e8f206a342c2de68",
          "sha1": "8522b323feec075400beba92c8017333b8f70611",
          "md5": "c35a503fbd6880814328b83d26b7630b"
        }
      ]
    }
  ]
}
