{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "8068699",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-8068699.jar",
          "url": "antibytes-android-application-configuration-8068699.jar",
          "size": 56574,
          "sha512": "a8f1db7814a62d56a2bccd42da98dc0f818701efacf926fbbc7e5ed8cd8bc3067a53ab1c0c13f231714cf4c4850461d30a714206a6f8e71860f093b422a7d5e8",
          "sha256": "a84973e424bb017081a9870e896aee7a4bcca74fc622ae0200b1de8d8cac53bb",
          "sha1": "97381d7bf4b794d9807b027da3326a7850285f53",
          "md5": "11327757e72ef715b293944c39ce0ef5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "8068699"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-8068699.jar",
          "url": "antibytes-android-application-configuration-8068699.jar",
          "size": 56574,
          "sha512": "a8f1db7814a62d56a2bccd42da98dc0f818701efacf926fbbc7e5ed8cd8bc3067a53ab1c0c13f231714cf4c4850461d30a714206a6f8e71860f093b422a7d5e8",
          "sha256": "a84973e424bb017081a9870e896aee7a4bcca74fc622ae0200b1de8d8cac53bb",
          "sha1": "97381d7bf4b794d9807b027da3326a7850285f53",
          "md5": "11327757e72ef715b293944c39ce0ef5"
        }
      ]
    }
  ]
}
