{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "0638349",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-0638349.jar",
          "url": "antibytes-dependency-node-0638349.jar",
          "size": 20143,
          "sha512": "7940d3fcf3cff71e47fa789d3f580e26a1bcb62ff5cacd6eb4e6025f1cd30d0710f35efd785c91629e343ea232caba887b7a52d9499edd71dd2e8eaa4d443f02",
          "sha256": "89c4a57e38b8f08d635e3da74aca9dfb27dfa144738007c4ed2fe8f6166b002a",
          "sha1": "6ea418c087d784f937f12d1da6e434b817e96bf0",
          "md5": "cdbf15fec77fa1b69d45ceac20fee984"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-0638349.jar",
          "url": "antibytes-dependency-node-0638349.jar",
          "size": 20143,
          "sha512": "7940d3fcf3cff71e47fa789d3f580e26a1bcb62ff5cacd6eb4e6025f1cd30d0710f35efd785c91629e343ea232caba887b7a52d9499edd71dd2e8eaa4d443f02",
          "sha256": "89c4a57e38b8f08d635e3da74aca9dfb27dfa144738007c4ed2fe8f6166b002a",
          "sha1": "6ea418c087d784f937f12d1da6e434b817e96bf0",
          "md5": "cdbf15fec77fa1b69d45ceac20fee984"
        }
      ]
    }
  ]
}
