{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "dfa7e53",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-dfa7e53.jar",
          "url": "antibytes-android-application-configuration-dfa7e53.jar",
          "size": 58039,
          "sha512": "95218e6b7f620e36737ba4b92cffdb3ea58e4093218a4535f8082be4f4dda24e396b80527aa942cbde95b447a40807123092f14417acb169cb7c8871662892d4",
          "sha256": "31cac3dc7c61276ff9c3e0724ba64e2a0bdcb681cd757ca1d5551385028188b7",
          "sha1": "f273d2c88b51cb06d98e780b0b515dc0b98f12d7",
          "md5": "3e40263714b0fff29576a5e48548434a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "dfa7e53"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-dfa7e53.jar",
          "url": "antibytes-android-application-configuration-dfa7e53.jar",
          "size": 58039,
          "sha512": "95218e6b7f620e36737ba4b92cffdb3ea58e4093218a4535f8082be4f4dda24e396b80527aa942cbde95b447a40807123092f14417acb169cb7c8871662892d4",
          "sha256": "31cac3dc7c61276ff9c3e0724ba64e2a0bdcb681cd757ca1d5551385028188b7",
          "sha1": "f273d2c88b51cb06d98e780b0b515dc0b98f12d7",
          "md5": "3e40263714b0fff29576a5e48548434a"
        }
      ]
    }
  ]
}
