{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-helper",
    "version": "31fab8d-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-31fab8d-SNAPSHOT.jar",
          "url": "antibytes-dependency-helper-31fab8d-SNAPSHOT.jar",
          "size": 55371,
          "sha512": "3466e14737562d9c7b20281350f9f8ecf15198657b22921bae1459248fd204a2db451fbc5ad4bc97d6ad146a3e538658bd895c445a2d3cb834f9429031de6d9f",
          "sha256": "8361c66544c5109de3a3570a90590db819f77781963ceba6b1efb5e4b2cded8d",
          "sha1": "4fafa56344672801cac1f0226c755c39e57ab63f",
          "md5": "0c37ae09fd48cd2b037528d1dfc7fa2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "31fab8d-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-31fab8d-SNAPSHOT.jar",
          "url": "antibytes-dependency-helper-31fab8d-SNAPSHOT.jar",
          "size": 55371,
          "sha512": "3466e14737562d9c7b20281350f9f8ecf15198657b22921bae1459248fd204a2db451fbc5ad4bc97d6ad146a3e538658bd895c445a2d3cb834f9429031de6d9f",
          "sha256": "8361c66544c5109de3a3570a90590db819f77781963ceba6b1efb5e4b2cded8d",
          "sha1": "4fafa56344672801cac1f0226c755c39e57ab63f",
          "md5": "0c37ae09fd48cd2b037528d1dfc7fa2d"
        }
      ]
    }
  ]
}
