{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "efb5584",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-efb5584.jar",
          "url": "antibytes-grammar-tools-efb5584.jar",
          "size": 39371,
          "sha512": "8306f2d9d1828bf44319eb6a87078aaffe5a8c04f8cb352d8206c427340891a1d1baac0f9cf357adf5b042f86e8fdd540dac7dc5d8863713ea4a0b683aee4e50",
          "sha256": "9c5538588f4e6b96875832fbf5a570d569c53af3d821dc880741847cf7dfc793",
          "sha1": "f758c0e20905950ea26dea4635eafbeb2d743673",
          "md5": "73d5b93e8b554519e2b904aaa7b69f48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-efb5584.jar",
          "url": "antibytes-grammar-tools-efb5584.jar",
          "size": 39371,
          "sha512": "8306f2d9d1828bf44319eb6a87078aaffe5a8c04f8cb352d8206c427340891a1d1baac0f9cf357adf5b042f86e8fdd540dac7dc5d8863713ea4a0b683aee4e50",
          "sha256": "9c5538588f4e6b96875832fbf5a570d569c53af3d821dc880741847cf7dfc793",
          "sha1": "f758c0e20905950ea26dea4635eafbeb2d743673",
          "md5": "73d5b93e8b554519e2b904aaa7b69f48"
        }
      ]
    }
  ]
}
