{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "432b684",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-metadata-432b684.jar",
          "url": "kmock-432b684.jar",
          "size": 13013,
          "sha512": "a4dffcc03b4132d8b3d4090c338292ba3c9ee32060d8080cf2d101e5e1d3575e91f3941c3732b35bffa349580d0795526f27e4a0fed3d0f9fa664455cc11547c",
          "sha256": "74c7c5ad3d1fa940fab9e9b90aa9ec5133ca62b0014a8f15a3d7f9e097ae1635",
          "sha1": "07ea8e770fb3ae0b230047ee2c6ad62312888837",
          "md5": "33864c3e5354c3838da3e366ac22c620"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/432b684/kmock-android-432b684.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "432b684"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/432b684/kmock-android-432b684.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "432b684"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/432b684/kmock-iosarm64-432b684.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "432b684"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/432b684/kmock-iosx64-432b684.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "432b684"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/432b684/kmock-js-432b684.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "432b684"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/432b684/kmock-js-432b684.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "432b684"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/432b684/kmock-jvm-432b684.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "432b684"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/432b684/kmock-jvm-432b684.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "432b684"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/432b684/kmock-linuxx64-432b684.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "432b684"
      }
    }
  ]
}
