{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/b35e311/core-b35e311.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "b35e311",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-b35e311.klib",
          "size": 50782,
          "sha512": "7ddb4ee98243589851f71d33e084cc52c26d1ae5983f6125a80363e5eef71b9cc4f8329110beb5baf6129d38c4d01fe7e224588703daa3ef943b2240f5f11104",
          "sha256": "c016d48e9d100fadca3d144287a666437f7dc9aa9ef8d09649d59bd5b4d2b79f",
          "sha1": "a5880dca2a70923ee57c0caef5ad65c9ebdfcf34",
          "md5": "99bc61466b7c03ae723cc3aee13b48c8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-b35e311-metadata.jar",
          "url": "core-iossimulatorarm64-b35e311-metadata.jar",
          "size": 261,
          "sha512": "df42a4b8801e617eca24595cf860495a3b47f5a02585e0af881c38e2513c85bd65a5a76ad635e9cb8305956bdeb8d40a453abb5c577145eb4b60580040e0d3c0",
          "sha256": "8327127f4adcbd4c37e7cd3c569af49f9856c10d8b3bb83ec44a9eb1377c8596",
          "sha1": "38a9173bbae1d402bf861b894242aa5c3dc3b59f",
          "md5": "a9412a735b947010ea6218980bf2b9b9"
        }
      ]
    }
  ]
}
