{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-androidnativex86-0.4.0-SNAPSHOT.klib",
          "size": 105853,
          "sha512": "91168d1559f5a15fe41764fbd6bfef2fc258078a1560eb3968f5fa3c74cd2c7344b20b012b6eb8d1f4a6468118ebcc6c31eef9f8b67635b04d6d179cae9f07b5",
          "sha256": "449614cd5035e21ccce9140010d0d41fda9e39a123bbc1868c2009bb8ce02edb",
          "sha1": "dc1a3479e495fd1cbeef3b7cfa3a8819833a92ef",
          "md5": "d29f0491e1eefff07c673b43e92aa252"
        }
      ]
    }
  ]
}
