{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/cf35c27/test-utils-cf35c27.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "cf35c27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm-cf35c27.jar",
          "url": "test-utils-jvm-cf35c27.jar",
          "size": 8848,
          "sha512": "580daa3b1a9ca15e53e62b1f2a4ff798aedd34224979fada5f4f3c03987b471a455c2b7a05856aa3d5bf6b37ac97d458752bde92a630db80d0a46d222c47eafc",
          "sha256": "92d4c4b340a8c28492710daf0a895973935570947ebc284bfe210938ee17d1a6",
          "sha1": "d0c91680b75d5a1e65edd99e6b99eaba99ca9b94",
          "md5": "06b0a70ff81a5a3e1d750eb268f64f79"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-cf35c27.jar",
          "url": "test-utils-jvm-cf35c27.jar",
          "size": 8848,
          "sha512": "580daa3b1a9ca15e53e62b1f2a4ff798aedd34224979fada5f4f3c03987b471a455c2b7a05856aa3d5bf6b37ac97d458752bde92a630db80d0a46d222c47eafc",
          "sha256": "92d4c4b340a8c28492710daf0a895973935570947ebc284bfe210938ee17d1a6",
          "sha1": "d0c91680b75d5a1e65edd99e6b99eaba99ca9b94",
          "md5": "06b0a70ff81a5a3e1d750eb268f64f79"
        }
      ]
    }
  ]
}
