{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "ec7ea01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-ec7ea01.jar",
          "url": "antibytes-coverage-ec7ea01.jar",
          "size": 135215,
          "sha512": "84e2a4a90efbd42e9a0188538bb5643d149b89bf0c99d98b951085f4fa4983b1912c6177b6d8e507904bcfad986f91b9a0d65a127c238809119feef144287359",
          "sha256": "ce319ddc5e42c3dd59247536fe690c73b85892b5bf427eda15bf79ebaabd418f",
          "sha1": "bf3add1e8a453d60364e5b5c74c34b949a35e52c",
          "md5": "cbb7453b895b72ae27c9dc3065b29ba7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "ec7ea01"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-ec7ea01.jar",
          "url": "antibytes-coverage-ec7ea01.jar",
          "size": 135215,
          "sha512": "84e2a4a90efbd42e9a0188538bb5643d149b89bf0c99d98b951085f4fa4983b1912c6177b6d8e507904bcfad986f91b9a0d65a127c238809119feef144287359",
          "sha256": "ce319ddc5e42c3dd59247536fe690c73b85892b5bf427eda15bf79ebaabd418f",
          "sha1": "bf3add1e8a453d60364e5b5c74c34b949a35e52c",
          "md5": "cbb7453b895b72ae27c9dc3065b29ba7"
        }
      ]
    }
  ]
}
