{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/6be4f13/test-utils-ktor-6be4f13.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "6be4f13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iosarm64-6be4f13.klib",
          "size": 14830,
          "sha512": "bd7406a5fca33e6df98a56161cb2582114fa2ced0580821ce46ee5d6a0134cde74ed3a178355b1496937476ebaf2a06a9ceb6b173d76160610e3f64a5c9717b1",
          "sha256": "09acb6a01ff2527865f96fef8a0b70cfe59d6a883497dd9ef0c7e468af63345f",
          "sha1": "15f0ffc3a574aa1fc69d10da1e94b0e60c673b11",
          "md5": "952a7893a3e50a89d44f3dc8de80c713"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iosarm64-6be4f13-metadata.jar",
          "url": "test-utils-ktor-iosarm64-6be4f13-metadata.jar",
          "size": 261,
          "sha512": "0c74203261fd59e0e746d1b713e65dc9412cfc6a06dc789e1ebc73586dc75d293e4a02330c03bc01ff4b0b0f957e2c8df5ebac91f8dd8e789bb7309fdb610970",
          "sha256": "fdeb81009314e1ff92a2e9e2717e7bccf2951feba7e841471895347b7d669b64",
          "sha1": "a03c80eb66967a9ea44f47d1122354e73b7baeee",
          "md5": "4cb23ef72d6762ee7c0256c4c8d999e6"
        }
      ]
    }
  ]
}
