{
  "formatVersion": "1.1",
  "component": {
    "url": "../../clientSDK/8b3897f/clientSDK-8b3897f.module",
    "group": "tech.antibytes.awesomecats",
    "module": "clientSDK",
    "version": "8b3897f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result",
          "version": {
            "requires": "05a4d20-customize-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "clientSDK.klib",
          "url": "clientSDK-linuxx64-8b3897f.klib",
          "size": 45918,
          "sha512": "3084999d4094e7ddb1518d2f769cb22839d26a3cd04a54a184fc1459c8337dc20a7301a89184c1ef5778571b62500a125a9e4ad70d6937c4ed09ca6fd704ed27",
          "sha256": "dba5c97766d2fa4b771ecf5b963fa6a61fb3926a3fab55b9b0ec975c518b8515",
          "sha1": "90ae4c280560ab5470e57759fd874266e45d6f8d",
          "md5": "61f2ad87abf7ebb4a06a3d99bf4f29d4"
        }
      ]
    }
  ]
}
