{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "ae101dc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-ae101dc.jar",
          "url": "antibytes-dependency-node-ae101dc.jar",
          "size": 21473,
          "sha512": "a0f22006429d1729d61ed29f441c87869628a1053f07bc7c2038643ac143194b1159bc4de257087bd82d7d3f81c20c30a2fc41d0269ccc0e31cbd30aee80d60c",
          "sha256": "0f435d0f76cb696384ba0c7f9f54da52fc1c7b1be085ba0f3454fd16c1b90bbd",
          "sha1": "48466597331d2951830de169388240766327f32e",
          "md5": "26956b8d7ec85460b3c1e28cb291871a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-ae101dc.jar",
          "url": "antibytes-dependency-node-ae101dc.jar",
          "size": 21473,
          "sha512": "a0f22006429d1729d61ed29f441c87869628a1053f07bc7c2038643ac143194b1159bc4de257087bd82d7d3f81c20c30a2fc41d0269ccc0e31cbd30aee80d60c",
          "sha256": "0f435d0f76cb696384ba0c7f9f54da52fc1c7b1be085ba0f3454fd16c1b90bbd",
          "sha1": "48466597331d2951830de169388240766327f32e",
          "md5": "26956b8d7ec85460b3c1e28cb291871a"
        }
      ]
    }
  ]
}
