{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1-SNAPSHOT/core-0.3.1-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.3.1-SNAPSHOT.klib",
          "size": 110283,
          "sha512": "9411a613601f9ac64e60f3dbd466acfac1ef839924c52331ca5e0f1aecbde6037b5ee863100a0989a9e62b846dd4a95e90424f5284101a4df42b22ab2e141283",
          "sha256": "2918ba4a0cab440865f706883f7eacaf077212617a7a2027b6ae00641f26e3a7",
          "sha1": "e8f2c0f274116c3a9016ebcb9620e54420beb8ac",
          "md5": "6d288194892654127096b262b8b26b4f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.3.1-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.3.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d0eaf62608c5db4f7e999fc0e1dabe1c6f4a73cbe73f1e22b3b593a2753c9d1ed15f4582dea0219ec421b4122de584f5601ca1d55302a43e651dc047f9a86c72",
          "sha256": "0bf9d1fdae0f9621eb62acc884f311cce5b7683275f38e739d607cdc83f984a6",
          "sha1": "067ea2350b4e3a5667752165dc40c47a34690cca",
          "md5": "7c48953db6eb7ff82dcdc64f8344db8b"
        }
      ]
    }
  ]
}
