{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "776a480",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-776a480.jar",
          "url": "kmock-gradle-776a480.jar",
          "size": 42648,
          "sha512": "4aea22bf1595b448842715e40d5a18fb30dfa8207e7b0463bbf325131f3b2d1dcefb15fe92b08625e60e7e69be50b96fcf305f1b25b13866d015ce46a2364583",
          "sha256": "bdfcd746ddfb72468366a187993cedd9d1411a4f7615dedf424abdc51dc876c3",
          "sha1": "7748f6bec5b304390d936493c3b3c14d84e484e6",
          "md5": "1e3ea1d91ac40967599e01c1596b8578"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "ed855ae"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-776a480.jar",
          "url": "kmock-gradle-776a480.jar",
          "size": 42648,
          "sha512": "4aea22bf1595b448842715e40d5a18fb30dfa8207e7b0463bbf325131f3b2d1dcefb15fe92b08625e60e7e69be50b96fcf305f1b25b13866d015ce46a2364583",
          "sha256": "bdfcd746ddfb72468366a187993cedd9d1411a4f7615dedf424abdc51dc876c3",
          "sha1": "7748f6bec5b304390d936493c3b3c14d84e484e6",
          "md5": "1e3ea1d91ac40967599e01c1596b8578"
        }
      ]
    }
  ]
}
