{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/8a321a1/test-utils-ktor-8a321a1.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "8a321a1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-8a321a1.jar",
          "url": "test-utils-ktor-jvm-8a321a1.jar",
          "size": 26352,
          "sha512": "5fd79e072c72a05b441a4378bf0b23eb4ae870d7334c59334d58f029219cb80219db367e03398ff7d8a1cb74bc4718576622199b8da4a59b66fae306c100a8d4",
          "sha256": "8a3c8db26807cd4774cffaa1292ea7b1a54708fe485e0a7b31f1f4083f4b1a12",
          "sha1": "5c2925da2663404c4c42a0a923eba029351b75e9",
          "md5": "36b7e0d2fd8f52d0f0f991a0913b8e25"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-8a321a1.jar",
          "url": "test-utils-ktor-jvm-8a321a1.jar",
          "size": 26352,
          "sha512": "5fd79e072c72a05b441a4378bf0b23eb4ae870d7334c59334d58f029219cb80219db367e03398ff7d8a1cb74bc4718576622199b8da4a59b66fae306c100a8d4",
          "sha256": "8a3c8db26807cd4774cffaa1292ea7b1a54708fe485e0a7b31f1f4083f4b1a12",
          "sha1": "5c2925da2663404c4c42a0a923eba029351b75e9",
          "md5": "36b7e0d2fd8f52d0f0f991a0913b8e25"
        }
      ]
    }
  ]
}
