{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.kmp",
    "module": "antibytes-kmp-configuration",
    "version": "283c93a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-283c93a.jar",
          "url": "antibytes-kmp-configuration-283c93a.jar",
          "size": 58433,
          "sha512": "0246e3dd3ed4c528fc4a6314e7f07f370cb73a8b62c755d07794fd93e59264e04dc8fb1fdd8fcf7d3799c3fd569413d61505792f866eaf7debecb9e939113c42",
          "sha256": "0178760c7049baf7aba98b9a5b8c1c526ee5c350c101dfc51f798db6b4782af5",
          "sha1": "e3f2f4d3b6a331fb1ac915cb1bf488740984e73d",
          "md5": "032fb4d84654a7391de61e1f0ca82e28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "283c93a"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-kmp-configuration-283c93a.jar",
          "url": "antibytes-kmp-configuration-283c93a.jar",
          "size": 58433,
          "sha512": "0246e3dd3ed4c528fc4a6314e7f07f370cb73a8b62c755d07794fd93e59264e04dc8fb1fdd8fcf7d3799c3fd569413d61505792f866eaf7debecb9e939113c42",
          "sha256": "0178760c7049baf7aba98b9a5b8c1c526ee5c350c101dfc51f798db6b4782af5",
          "sha1": "e3f2f4d3b6a331fb1ac915cb1bf488740984e73d",
          "md5": "032fb4d84654a7391de61e1f0ca82e28"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-283c93a-javadoc.jar",
          "url": "antibytes-kmp-configuration-283c93a-javadoc.jar",
          "size": 261,
          "sha512": "b48d01c676185cd88a7e7d2701edfa65725b15360a971fe9050f2f3e0f71e05e2120797a3f31e9c14a225dc47eb57169f81fb5aca3182a3996b87c85a728c4d0",
          "sha256": "73db4186d289ecf83bf1f8501433adfa1668c55e1c21213b9f5bb0bfc390a33f",
          "sha1": "c5c09321fa66f1bd697c022c1bc843a8b18ca95b",
          "md5": "bd1daa684167c98c7e78aa16524f4ec8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-283c93a-sources.jar",
          "url": "antibytes-kmp-configuration-283c93a-sources.jar",
          "size": 12495,
          "sha512": "cc0aae500624bc6b76b875235c81d886c4705564f5bba2a2b7c06ae9fd34264881ffa1e4746feb91d4d6d7d0dd6d4ea3fcac73b022eec559829f4f15e63d21e6",
          "sha256": "01f6331e4d8b1234fa26e2597468b4894de39a68d7a3a39ebc1aa5e546ef5643",
          "sha1": "82dd92316f37a7787164b98ed3b172b57ee21ed4",
          "md5": "1342f9438c21ec259807f07636906730"
        }
      ]
    }
  ]
}
