{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "db3eb1b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-db3eb1b.jar",
          "url": "antibytes-dependency-node-db3eb1b.jar",
          "size": 21473,
          "sha512": "7f379664fe3bf258ee7334ac604c87d9db5342b94cc57c27eacf6f85ab2b38d61e0f5ceaa5b35b05099b481f57954272bc81c0d686265e49f791d14589316730",
          "sha256": "f936499a9c2119791e33deeaa689c7b09725161c9ab438ef3b543f02db920ba7",
          "sha1": "eb81d310a6caf208d9f32cd847b5f0549eacb9c2",
          "md5": "85a4547cfeb0aa18700d58021b1717d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-db3eb1b.jar",
          "url": "antibytes-dependency-node-db3eb1b.jar",
          "size": 21473,
          "sha512": "7f379664fe3bf258ee7334ac604c87d9db5342b94cc57c27eacf6f85ab2b38d61e0f5ceaa5b35b05099b481f57954272bc81c0d686265e49f791d14589316730",
          "sha256": "f936499a9c2119791e33deeaa689c7b09725161c9ab438ef3b543f02db920ba7",
          "sha1": "eb81d310a6caf208d9f32cd847b5f0549eacb9c2",
          "md5": "85a4547cfeb0aa18700d58021b1717d2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-db3eb1b-javadoc.jar",
          "url": "antibytes-dependency-node-db3eb1b-javadoc.jar",
          "size": 261,
          "sha512": "77aec2a5a6b19ef97a46841af0d54e178969a98ae307ae0a376645263eac9e1e656d6e84311a0d169187cbcc53122f96f6ecd545e3d26cb28ad237f56dc009ff",
          "sha256": "e1b7b1b0c2c65b7fc4348c40c2e95eeaf2331032ba9d27f6988f3ed00608e5fb",
          "sha1": "aaee29f880382e4d8896a6125cc904e74c97effe",
          "md5": "2c595e42526e4d41abf3149ef0ae6112"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-db3eb1b-sources.jar",
          "url": "antibytes-dependency-node-db3eb1b-sources.jar",
          "size": 4172,
          "sha512": "0c4352394f5637ce52bc78bc550ce92157032760875cf51e488fa8dbd3581f89b11e1680591bfd59d6ca10ccf6b624bcb3a2c36be202b10032a283444b837df4",
          "sha256": "7d287ab5940131b0c3242b256b795c2d319e421221e77a5a9637971813f59980",
          "sha1": "972b8da842a16bf618e701cb19ed0adaf2312052",
          "md5": "7470b433896d78d06234f39bd3eed8e2"
        }
      ]
    }
  ]
}
