{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-SNAPSHOT/ktx-datetime-0.3.1-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-js-0.3.1-SNAPSHOT.klib",
          "url": "ktx-datetime-js-0.3.1-SNAPSHOT.klib",
          "size": 13040,
          "sha512": "3bd9382895144280246b9769291ac43538e4176b7cf1d9cb7af874f0e3efccb7aae9d6aba60206c78de04342216bf5c82c185ec05b25e07d35ef46b858a4a5bb",
          "sha256": "f05cf5aa43b6597b06b6181c1e859ea5c30234f9bb892c5f4decb68e5550c09b",
          "sha1": "1237fc022b1eb17ef33507a8513188ba4479f9cd",
          "md5": "e3640aecdbb64bf2a8e28bd2d5177983"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-js-0.3.1-SNAPSHOT.klib",
          "url": "ktx-datetime-js-0.3.1-SNAPSHOT.klib",
          "size": 13040,
          "sha512": "3bd9382895144280246b9769291ac43538e4176b7cf1d9cb7af874f0e3efccb7aae9d6aba60206c78de04342216bf5c82c185ec05b25e07d35ef46b858a4a5bb",
          "sha256": "f05cf5aa43b6597b06b6181c1e859ea5c30234f9bb892c5f4decb68e5550c09b",
          "sha1": "1237fc022b1eb17ef33507a8513188ba4479f9cd",
          "md5": "e3640aecdbb64bf2a8e28bd2d5177983"
        }
      ]
    }
  ]
}
