{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "423842c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-423842c.jar",
          "url": "antibytes-custom-component-423842c.jar",
          "size": 16172,
          "sha512": "613c208e580d419c5713681fc05160fe0ce386897372f4a8e1baef3fc0d0d8eb0c8b09049d98c96f53958f1c64aef0abb5bad57d73ac2da99e64942875d8b882",
          "sha256": "1d9fb1f51f687ae61fc2397dc06bca95124acb667cb78cf46d5b91be42d7e289",
          "sha1": "f3ff7850124af11adb84e1918d5c029f95ae9df1",
          "md5": "70ab67731cc8334c1bcbd57147169bd0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-423842c.jar",
          "url": "antibytes-custom-component-423842c.jar",
          "size": 16172,
          "sha512": "613c208e580d419c5713681fc05160fe0ce386897372f4a8e1baef3fc0d0d8eb0c8b09049d98c96f53958f1c64aef0abb5bad57d73ac2da99e64942875d8b882",
          "sha256": "1d9fb1f51f687ae61fc2397dc06bca95124acb667cb78cf46d5b91be42d7e289",
          "sha1": "f3ff7850124af11adb84e1918d5c029f95ae9df1",
          "md5": "70ab67731cc8334c1bcbd57147169bd0"
        }
      ]
    }
  ]
}
