{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/8066bd0/test-utils-ktor-8066bd0.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "8066bd0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-watchosarm32-8066bd0.klib",
          "size": 15061,
          "sha512": "f42f114a4914b37d5544b7f07a04c4cee20f777f282e15ec3fd99437499ab7b1610722dcd1300df51ef6eaa8b9c392b2dabf2c04752b54ec52384b1634bfdcf4",
          "sha256": "253bc5aaeb7baee4c614705093fc31d95688a1acaa7c5783168837da1ed22827",
          "sha1": "dd8b9fec67d16fe5bf74e63bfd5aaf4f4a90659a",
          "md5": "4a9df491df76e2f0849c508500fa2273"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-watchosarm32-8066bd0-metadata.jar",
          "url": "test-utils-ktor-watchosarm32-8066bd0-metadata.jar",
          "size": 261,
          "sha512": "227c0dbc9e25dd7af6944f225a04930cd6f8de643acff368bae100d9739f584beec960cf0e2be8e1e0112f42702805b550e5c8beb016f6f4c8d80cbcdbb0a749",
          "sha256": "9120f728f26f91f7c56b16ba82558c17378a56aa176132f0bad7646b4b25d821",
          "sha1": "6cf576fbb1d8a72deb6b5871c85439d2d3593f9c",
          "md5": "1b751f3e8225ed1edfceec02d9a5dd0e"
        }
      ]
    }
  ]
}
