{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "cfd6317",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-cfd6317.toml",
          "url": "antibytes-dependency-catalog-cfd6317.toml",
          "size": 250086,
          "sha512": "ab418958201a2b78b6e2de02bad81b6176287c9a1207c711e1716289321c28ed254f4b7c9d0fc575e343ec04e0775395eec588492beee52c3136cd1864cc30c9",
          "sha256": "7a8d50fa5569d2bf417caa162d06ac57a72bcb30881fd5be4102ded553fadf7d",
          "sha1": "c593bef60f81fa77f608dd73035b23ae2a710f90",
          "md5": "3d4251840645acc91e11b19b3106e5c5"
        }
      ]
    }
  ]
}
