{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-versioning",
    "version": "807f122",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-807f122.jar",
          "url": "antibytes-versioning-807f122.jar",
          "size": 16029,
          "sha512": "5a865c42e85cd3b9b961e775d915438cd336ade548679653711b61001091b5d550fd844322934f1c8bc02be1d4c5b3df5e79d00369bcb6d74af9fbcf9ca77348",
          "sha256": "eecf5838e798f1bff3747ce498ff2a24ba0d64c012b710e7f7c2788f2e234c3d",
          "sha1": "847d1e048b3131598d7dec8109892d476a9cfcca",
          "md5": "1ce999134b4c249168e5dfa9bb5845bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-807f122.jar",
          "url": "antibytes-versioning-807f122.jar",
          "size": 16029,
          "sha512": "5a865c42e85cd3b9b961e775d915438cd336ade548679653711b61001091b5d550fd844322934f1c8bc02be1d4c5b3df5e79d00369bcb6d74af9fbcf9ca77348",
          "sha256": "eecf5838e798f1bff3747ce498ff2a24ba0d64c012b710e7f7c2788f2e234c3d",
          "sha1": "847d1e048b3131598d7dec8109892d476a9cfcca",
          "md5": "1ce999134b4c249168e5dfa9bb5845bf"
        }
      ]
    }
  ]
}
