{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "fc88d6a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-metadata-fc88d6a-all.jar",
          "url": "test-utils-ktor-fc88d6a-all.jar",
          "size": 5337,
          "sha512": "55b52ecb7240524f75a92a586a7fa29cfbcd8dbffc0be60693469e63cb52d80e17440bbfd505e33d59f2c2f9f3fdf0cdc91c441689c8420a4f4ab91a99e861a1",
          "sha256": "21eea63b8ca239c7a454f04c45fc2d1da6f2116106db20abd4b6f2a816b8e800",
          "sha1": "c576d4660531f2424b805f9ddd1c21daaae65a4c",
          "md5": "2e50371f1b95bfab8b26146992fac790"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-ktor-fc88d6a.jar",
          "url": "test-utils-ktor-fc88d6a.jar",
          "size": 2502,
          "sha512": "b2c02641f2a243b22cdec7fe27175e6031f5771827993d98a62a109253e32177878e48fbe08b9650cbb86ce673ca7c83a46bb1daaf266b10643dd4292577a12f",
          "sha256": "b18ad90d85f25500e2ea7c39dc682214760a7b3fdc5cd0f6e31859d22ae49a2c",
          "sha1": "760286f992e176534bf7a3e52898a26970f463c2",
          "md5": "b7842b71b6a30cc254806bcdc63e5619"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/fc88d6a/test-utils-ktor-android-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "fc88d6a"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/fc88d6a/test-utils-ktor-android-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "fc88d6a"
      }
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iosarm32/fc88d6a/test-utils-ktor-iosarm32-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iosarm32",
        "version": "fc88d6a"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iosarm32/fc88d6a/test-utils-ktor-iosarm32-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iosarm32",
        "version": "fc88d6a"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iosarm64/fc88d6a/test-utils-ktor-iosarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iosarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iosarm64/fc88d6a/test-utils-ktor-iosarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iosarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iossimulatorarm64/fc88d6a/test-utils-ktor-iossimulatorarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iossimulatorarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iossimulatorarm64/fc88d6a/test-utils-ktor-iossimulatorarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iossimulatorarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iosx64/fc88d6a/test-utils-ktor-iosx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iosx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iosx64/fc88d6a/test-utils-ktor-iosx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iosx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-ktor-js/fc88d6a/test-utils-ktor-js-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-js",
        "version": "fc88d6a"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-ktor-js/fc88d6a/test-utils-ktor-js-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-js",
        "version": "fc88d6a"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/fc88d6a/test-utils-ktor-jvm-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "fc88d6a"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/fc88d6a/test-utils-ktor-jvm-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "fc88d6a"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-linuxx64/fc88d6a/test-utils-ktor-linuxx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-linuxx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-macosarm64/fc88d6a/test-utils-ktor-macosarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-macosarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-macosarm64/fc88d6a/test-utils-ktor-macosarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-macosarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-macosx64/fc88d6a/test-utils-ktor-macosx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-macosx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-macosx64/fc88d6a/test-utils-ktor-macosx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-macosx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-mingwx64/fc88d6a/test-utils-ktor-mingwx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-mingwx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-tvosarm64/fc88d6a/test-utils-ktor-tvosarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-tvosarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-tvosarm64/fc88d6a/test-utils-ktor-tvosarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-tvosarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-tvossimulatorarm64/fc88d6a/test-utils-ktor-tvossimulatorarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-tvossimulatorarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-tvossimulatorarm64/fc88d6a/test-utils-ktor-tvossimulatorarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-tvossimulatorarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-tvosx64/fc88d6a/test-utils-ktor-tvosx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-tvosx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-tvosx64/fc88d6a/test-utils-ktor-tvosx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-tvosx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchosarm32/fc88d6a/test-utils-ktor-watchosarm32-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchosarm32",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchosarm32/fc88d6a/test-utils-ktor-watchosarm32-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchosarm32",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchosarm64/fc88d6a/test-utils-ktor-watchosarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchosarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchosarm64/fc88d6a/test-utils-ktor-watchosarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchosarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchossimulatorarm64/fc88d6a/test-utils-ktor-watchossimulatorarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchossimulatorarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchossimulatorarm64/fc88d6a/test-utils-ktor-watchossimulatorarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchossimulatorarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchosx64/fc88d6a/test-utils-ktor-watchosx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchosx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchosx64/fc88d6a/test-utils-ktor-watchosx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchosx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchosx86/fc88d6a/test-utils-ktor-watchosx86-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchosx86",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchosx86/fc88d6a/test-utils-ktor-watchosx86-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchosx86",
        "version": "fc88d6a"
      }
    }
  ]
}
