{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/1b54cfa/test-utils-fixture-1b54cfa.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "1b54cfa",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm.jar",
          "url": "test-utils-fixture-jvm-1b54cfa.jar",
          "size": 40993,
          "sha512": "0d744ba12744076f23fd2aea9b2b2466874d2ec02777f3d4c84b36d1d9764c663ffd50ce53ef2807be1119117cba46f2a858d8e1538c8d7d28fc17b0164313f3",
          "sha256": "85b4aa44084ec57cf14d8012cac70af71ff3940cfaef2d674f11af41938afcac",
          "sha1": "bbc3ad07fa11d6299908d3db2d35ac63a8a40e39",
          "md5": "c1d9eea3807962c3d4890c48787610fe"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm.jar",
          "url": "test-utils-fixture-jvm-1b54cfa.jar",
          "size": 40993,
          "sha512": "0d744ba12744076f23fd2aea9b2b2466874d2ec02777f3d4c84b36d1d9764c663ffd50ce53ef2807be1119117cba46f2a858d8e1538c8d7d28fc17b0164313f3",
          "sha256": "85b4aa44084ec57cf14d8012cac70af71ff3940cfaef2d674f11af41938afcac",
          "sha1": "bbc3ad07fa11d6299908d3db2d35ac63a8a40e39",
          "md5": "c1d9eea3807962c3d4890c48787610fe"
        }
      ]
    }
  ]
}
