{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/4f11117/test-utils-annotations-junit5-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "linuxMipsel32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-linuxmipsel32-4f11117.klib",
          "size": 7093,
          "sha512": "a4e139c749557af3a9c0318f16d1472c5194b568a4da255428331a97d6edd1a16dbe1483a10aa76925cd67805fc7f8b54124e05bb19ff2d188c36fd07fd02281",
          "sha256": "d58d0ab28c6285240e261bf662435c7489454f7e4abcdb36d210ce169eadaae1",
          "sha1": "dd5e4e7d7636f0a1da69892386f7ffd46c3531e5",
          "md5": "b535b745b57329f17bf62aff37fb94e5"
        }
      ]
    },
    {
      "name": "linuxMipsel32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-linuxmipsel32-4f11117-metadata.jar",
          "url": "test-utils-annotations-junit5-linuxmipsel32-4f11117-metadata.jar",
          "size": 261,
          "sha512": "b72445d0fd26a7cfa5971bad1d4bfd73b178f3b353093138b114dd8741507f287e6418d98bca3a21b921989729218b908dfb414ea59d4cf758d13acffe8b4f5e",
          "sha256": "eda28fefac44d696aff04dd86f93dfa51695e51c324fe920283fd26d2bbee618",
          "sha1": "ec7e7fa054c45e49b278cc23a88b35583d897e14",
          "md5": "edce00e5f31452f83c2b207410ddedc7"
        }
      ]
    }
  ]
}
