{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "fc88d6a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-metadata-fc88d6a-all.jar",
          "url": "test-utils-fc88d6a-all.jar",
          "size": 4862,
          "sha512": "1e0a2a72d88cb6bed6d4864f70b43e68ddec963161c64b3c5946bb3719dc818842ae982138d860099f8ac113a4eed10ff8c9c2fbbcff1942cc68955566780fc0",
          "sha256": "0425e8d9375da8b6103ac4d85033937e4fbff9b8c29f48efc1f8eb2970e19ec2",
          "sha1": "a284b2fbe5d03809bb595fdbd881df9a903062d5",
          "md5": "ee2195713e0d3588cedec2da3d1aed1d"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-fc88d6a.jar",
          "url": "test-utils-fc88d6a.jar",
          "size": 2080,
          "sha512": "ee99ef377272028cb67e13ce6397a2b0fdfa42e5055d04f730770956471005206a291342ac4da513837865a686a203f8eb3fb2c60d59911713c79d077067b0c9",
          "sha256": "c8c470c47c21fea8ddbc952ecafe878f54269f9c969a6a0ae459e388ac3a9146",
          "sha1": "44faaf6d148a97e474e16169fca422681ef12509",
          "md5": "b2ee392198eaae61b7e40ef6f9cafa61"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/fc88d6a/test-utils-android-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "fc88d6a"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/fc88d6a/test-utils-android-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "fc88d6a"
      }
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-androidnativearm32/fc88d6a/test-utils-androidnativearm32-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-androidnativearm32",
        "version": "fc88d6a"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-androidnativearm64/fc88d6a/test-utils-androidnativearm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-androidnativearm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-androidnativex64/fc88d6a/test-utils-androidnativex64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-androidnativex64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-androidnativex86/fc88d6a/test-utils-androidnativex86-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-androidnativex86",
        "version": "fc88d6a"
      }
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosarm32/fc88d6a/test-utils-iosarm32-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosarm32",
        "version": "fc88d6a"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosarm32/fc88d6a/test-utils-iosarm32-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosarm32",
        "version": "fc88d6a"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosarm64/fc88d6a/test-utils-iosarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosarm64/fc88d6a/test-utils-iosarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iossimulatorarm64/fc88d6a/test-utils-iossimulatorarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iossimulatorarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iossimulatorarm64/fc88d6a/test-utils-iossimulatorarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iossimulatorarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosx64/fc88d6a/test-utils-iosx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosx64/fc88d6a/test-utils-iosx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-js/fc88d6a/test-utils-js-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-js",
        "version": "fc88d6a"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-js/fc88d6a/test-utils-js-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-js",
        "version": "fc88d6a"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/fc88d6a/test-utils-jvm-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "fc88d6a"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/fc88d6a/test-utils-jvm-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "fc88d6a"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-linuxarm32hfp/fc88d6a/test-utils-linuxarm32hfp-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-linuxarm32hfp",
        "version": "fc88d6a"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-linuxarm64/fc88d6a/test-utils-linuxarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-linuxarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "linuxMips32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-linuxmips32/fc88d6a/test-utils-linuxmips32-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-linuxmips32",
        "version": "fc88d6a"
      }
    },
    {
      "name": "linuxMips32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-linuxmips32/fc88d6a/test-utils-linuxmips32-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-linuxmips32",
        "version": "fc88d6a"
      }
    },
    {
      "name": "linuxMipsel32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-linuxmipsel32/fc88d6a/test-utils-linuxmipsel32-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-linuxmipsel32",
        "version": "fc88d6a"
      }
    },
    {
      "name": "linuxMipsel32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-linuxmipsel32/fc88d6a/test-utils-linuxmipsel32-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-linuxmipsel32",
        "version": "fc88d6a"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-linuxx64/fc88d6a/test-utils-linuxx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-linuxx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-macosarm64/fc88d6a/test-utils-macosarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-macosarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-macosarm64/fc88d6a/test-utils-macosarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-macosarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-macosx64/fc88d6a/test-utils-macosx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-macosx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-macosx64/fc88d6a/test-utils-macosx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-macosx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-mingwx64/fc88d6a/test-utils-mingwx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-mingwx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "mingwX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-mingwx86/fc88d6a/test-utils-mingwx86-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-mingwx86",
        "version": "fc88d6a"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-tvosarm64/fc88d6a/test-utils-tvosarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-tvosarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-tvosarm64/fc88d6a/test-utils-tvosarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-tvosarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-tvossimulatorarm64/fc88d6a/test-utils-tvossimulatorarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-tvossimulatorarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-tvossimulatorarm64/fc88d6a/test-utils-tvossimulatorarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-tvossimulatorarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-tvosx64/fc88d6a/test-utils-tvosx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-tvosx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-tvosx64/fc88d6a/test-utils-tvosx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-tvosx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "wasm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "wasm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-wasm32/fc88d6a/test-utils-wasm32-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-wasm32",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-watchosarm32/fc88d6a/test-utils-watchosarm32-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-watchosarm32",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-watchosarm32/fc88d6a/test-utils-watchosarm32-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-watchosarm32",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-watchosarm64/fc88d6a/test-utils-watchosarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-watchosarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-watchosarm64/fc88d6a/test-utils-watchosarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-watchosarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-watchossimulatorarm64/fc88d6a/test-utils-watchossimulatorarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-watchossimulatorarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-watchossimulatorarm64/fc88d6a/test-utils-watchossimulatorarm64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-watchossimulatorarm64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-watchosx64/fc88d6a/test-utils-watchosx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-watchosx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-watchosx64/fc88d6a/test-utils-watchosx64-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-watchosx64",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-watchosx86/fc88d6a/test-utils-watchosx86-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-watchosx86",
        "version": "fc88d6a"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-watchosx86/fc88d6a/test-utils-watchosx86-fc88d6a.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-watchosx86",
        "version": "fc88d6a"
      }
    }
  ]
}
