{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "4ad1594",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-4ad1594.toml",
          "url": "antibytes-dependency-catalog-4ad1594.toml",
          "size": 231379,
          "sha512": "c849c43d98c00fc065315608a89fd82c7ec0031aa5ed8d22cf22a02b5ea6f1c3cb5ffe77ce6b3e101e1926412634a354e591a38ba75b8d4d84e3f0edf8a3e54f",
          "sha256": "c3f06d21c0ce03620b1019e500dd67233910247e3dce112acd138a6cf6c10e84",
          "sha1": "6fedcb337016af3af3adae24df917b8fdee027f1",
          "md5": "17fde48e2aeba9aaa1bc7dcd9a418b14"
        }
      ]
    }
  ]
}
