{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "35ae125",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-metadata-35ae125.jar",
          "url": "kmock-35ae125.jar",
          "size": 17475,
          "sha512": "80e789e1fb8138d51707a46783481eaa2778c6b5af9768832f6892d94e2c404506f442f36b93a12f9a8af5ca88d429c89c0fd2570c30628b9584ddb698493f26",
          "sha256": "64ddf3561cb4e169c9a892e7e205354d94e9cb9991870f59c95510097bc481f8",
          "sha1": "0ef94dcdee17ee28b31ca2ec3f17aa7b298aa3bd",
          "md5": "9353c45db1d8ea3fc54d1ea6c81c577d"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/35ae125/kmock-android-35ae125.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "35ae125"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/35ae125/kmock-android-35ae125.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "35ae125"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/35ae125/kmock-iosarm64-35ae125.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "35ae125"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/35ae125/kmock-iosx64-35ae125.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "35ae125"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/35ae125/kmock-js-35ae125.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "35ae125"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/35ae125/kmock-js-35ae125.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "35ae125"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/35ae125/kmock-jvm-35ae125.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "35ae125"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/35ae125/kmock-jvm-35ae125.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "35ae125"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/35ae125/kmock-linuxx64-35ae125.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "35ae125"
      }
    }
  ]
}
