{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-watchosarm64-0.4.0-SNAPSHOT.klib",
          "size": 105870,
          "sha512": "3831b55bd4e198839bf5974c9538f8717086ee971595a3ff3fc4b9e8b12ce3e6fdfc7d26d620e55cef0a5fc3035c23a5d9f445af883cbf773a07d0f7e060e189",
          "sha256": "67bd08a14d36c0fa70e6edbf92c35beee20d9ec0ba9c6ba6ea9538db49b8d522",
          "sha1": "20b75f0e877ce263986352c9fd4600bf98b2a2d5",
          "md5": "0bf37b68051cead45472df08b026bce8"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchosarm64-0.4.0-SNAPSHOT-metadata.jar",
          "url": "core-watchosarm64-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "44f5c060df676a8a250cafcee08ff568d38582dc9b4e658eae035317f091b006ad0a1bc561712f1cc80960b4bd299c8df7a7b2c4f254b1c393220b463fdfdd7e",
          "sha256": "18e7fd9881e71799660e8ea2a396e4ea8ebaa854a4d594925f2f22a1048e3171",
          "sha1": "61ee9a91636de7f22ae0eca92774110c1765eeb6",
          "md5": "2a88b62741df10616e51bf1a9cd7738c"
        }
      ]
    }
  ]
}
