{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/2395d28/test-utils-ktor-2395d28.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "2395d28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-2395d28.jar",
          "size": 22816,
          "sha512": "3935b548e2df7f468144e795be9d851757be48cc29ab42fba9e1968011f040a2bbb9d2830e44c039154d1a0cb82a1105bf74afaf61df1b72a0da67955d0eee05",
          "sha256": "62a64d4f5ffdbe34465eb6d0a7afc4039b79fbb52e5506e4cdce9a5d411c6dad",
          "sha1": "624b178c6b300a2793b1a51fdda788e90bc6313f",
          "md5": "eb65c81080e2b7b44813da1d3b295068"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-2395d28.jar",
          "size": 22816,
          "sha512": "3935b548e2df7f468144e795be9d851757be48cc29ab42fba9e1968011f040a2bbb9d2830e44c039154d1a0cb82a1105bf74afaf61df1b72a0da67955d0eee05",
          "sha256": "62a64d4f5ffdbe34465eb6d0a7afc4039b79fbb52e5506e4cdce9a5d411c6dad",
          "sha1": "624b178c6b300a2793b1a51fdda788e90bc6313f",
          "md5": "eb65c81080e2b7b44813da1d3b295068"
        }
      ]
    }
  ]
}
