{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "508b21d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-508b21d.jar",
          "url": "antibytes-publishing-508b21d.jar",
          "size": 105775,
          "sha512": "ca5cec66b62c8674a553ac39a4c4fe369e11cbd9b647144d2a4f5d552cb4d23c6dbb1700dd37d17a405597d7d8622e1f4cfcf52d7d00e7d0e946bfdf77ba59e0",
          "sha256": "a790c7d8000c515e935c1aa60a459190760f437df33b91f6fa1251c0d235114d",
          "sha1": "2d16b74016879fe6e83569b8b898fcdccf7d397b",
          "md5": "78ae069bcc2358e3d89525fda1e62c95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.13.0.202109080827-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.12.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "508b21d"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-508b21d.jar",
          "url": "antibytes-publishing-508b21d.jar",
          "size": 105775,
          "sha512": "ca5cec66b62c8674a553ac39a4c4fe369e11cbd9b647144d2a4f5d552cb4d23c6dbb1700dd37d17a405597d7d8622e1f4cfcf52d7d00e7d0e946bfdf77ba59e0",
          "sha256": "a790c7d8000c515e935c1aa60a459190760f437df33b91f6fa1251c0d235114d",
          "sha1": "2d16b74016879fe6e83569b8b898fcdccf7d397b",
          "md5": "78ae069bcc2358e3d89525fda1e62c95"
        }
      ]
    }
  ]
}
