{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "f006ae5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-f006ae5.jar",
          "url": "antibytes-dependency-helper-f006ae5.jar",
          "size": 69711,
          "sha512": "227c67c914a40678247469bd7398ec9be0e3cb9813b4c86af0aea56fe175f043d46dae8275a6da5ba57a745e82d610f152c33bef2e783dfa23ae0e8d3e851863",
          "sha256": "c1893808c779e319a80a7cf3703646cc0c70c3405c9feb7bb336935a90ea276f",
          "sha1": "dc01cfac422215eeb9af12293a3483650c0c5f64",
          "md5": "b3a3ec2415c8ee08441fc3c130742720"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.49.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "f006ae5"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-f006ae5.jar",
          "url": "antibytes-dependency-helper-f006ae5.jar",
          "size": 69711,
          "sha512": "227c67c914a40678247469bd7398ec9be0e3cb9813b4c86af0aea56fe175f043d46dae8275a6da5ba57a745e82d610f152c33bef2e783dfa23ae0e8d3e851863",
          "sha256": "c1893808c779e319a80a7cf3703646cc0c70c3405c9feb7bb336935a90ea276f",
          "sha1": "dc01cfac422215eeb9af12293a3483650c0c5f64",
          "md5": "b3a3ec2415c8ee08441fc3c130742720"
        }
      ]
    }
  ]
}
