{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.1.0-SNAPSHOT/core-0.1.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.1.0-SNAPSHOT.klib",
          "url": "core-js-0.1.0-SNAPSHOT.klib",
          "size": 61766,
          "sha512": "962f69251f7c254f2f30f1fbdc0c5ff6a497550993efb95584ca7056c3430061fd83cfb68e3edc878723b9ce013a23c36db24e4fbd5990da02c1badde2238190",
          "sha256": "077591285677c24e9eb789fd72e9eda31818303581795861505bae3a9fd002de",
          "sha1": "e4e7a3b7185cb3d2ab8ee257abe9e6caaae90895",
          "md5": "7f593adfd052e5461eeea6ea047db555"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.1.0-SNAPSHOT.klib",
          "url": "core-js-0.1.0-SNAPSHOT.klib",
          "size": 61766,
          "sha512": "962f69251f7c254f2f30f1fbdc0c5ff6a497550993efb95584ca7056c3430061fd83cfb68e3edc878723b9ce013a23c36db24e4fbd5990da02c1badde2238190",
          "sha256": "077591285677c24e9eb789fd72e9eda31818303581795861505bae3a9fd002de",
          "sha1": "e4e7a3b7185cb3d2ab8ee257abe9e6caaae90895",
          "md5": "7f593adfd052e5461eeea6ea047db555"
        }
      ]
    }
  ]
}
