{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-SNAPSHOT/ktx-datetime-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-js-0.4.0-SNAPSHOT.klib",
          "url": "ktx-datetime-js-0.4.0-SNAPSHOT.klib",
          "size": 40068,
          "sha512": "cb7d5faf25a463bb686fa738ab33d297e00495b1f71261e05ba557bffe5c205c970ef13be5b8adb6d3d5b8b499d039e6cd230a205f790d378a0cd7ca8f116e8b",
          "sha256": "20aa5d9b71556eb8e80127ef96c506adbe621e0ee39ead1151cfc37eecc1d436",
          "sha1": "3f74864ead7bb4b975851b6c00d7d8d28fced847",
          "md5": "eebd64b6829a4a654c719037f7d927c4"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-js-0.4.0-SNAPSHOT.klib",
          "url": "ktx-datetime-js-0.4.0-SNAPSHOT.klib",
          "size": 40068,
          "sha512": "cb7d5faf25a463bb686fa738ab33d297e00495b1f71261e05ba557bffe5c205c970ef13be5b8adb6d3d5b8b499d039e6cd230a205f790d378a0cd7ca8f116e8b",
          "sha256": "20aa5d9b71556eb8e80127ef96c506adbe621e0ee39ead1151cfc37eecc1d436",
          "sha1": "3f74864ead7bb4b975851b6c00d7d8d28fced847",
          "md5": "eebd64b6829a4a654c719037f7d927c4"
        }
      ]
    }
  ]
}
