{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-SNAPSHOT/ktx-datetime-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-js-0.4.0-SNAPSHOT.klib",
          "url": "ktx-datetime-js-0.4.0-SNAPSHOT.klib",
          "size": 42757,
          "sha512": "733d1db76e63ff19ab56d1e24640ef2f50eb0f8e470fd061fad0426f90016dc65e5f885b9a4f29d5d024e8f91685b481d62dcd0cad8eade4b7c99113973909e6",
          "sha256": "eebce45ee056ed2ec7fd061cfbc8437e2b239c08b24c2d84356eed39e50ccd45",
          "sha1": "16c3839fcb52dcb20fd08f7544d6f316d328de87",
          "md5": "5ca0de3e85960a4297462438126476ad"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-js-0.4.0-SNAPSHOT.klib",
          "url": "ktx-datetime-js-0.4.0-SNAPSHOT.klib",
          "size": 42757,
          "sha512": "733d1db76e63ff19ab56d1e24640ef2f50eb0f8e470fd061fad0426f90016dc65e5f885b9a4f29d5d024e8f91685b481d62dcd0cad8eade4b7c99113973909e6",
          "sha256": "eebce45ee056ed2ec7fd061cfbc8437e2b239c08b24c2d84356eed39e50ccd45",
          "sha1": "16c3839fcb52dcb20fd08f7544d6f316d328de87",
          "md5": "5ca0de3e85960a4297462438126476ad"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "ktx-datetime-js-0.4.0-SNAPSHOT-sources.jar",
          "url": "ktx-datetime-js-0.4.0-SNAPSHOT-sources.jar",
          "size": 16088,
          "sha512": "2fd1093b4f66fb86460e0e5fc46d3c82d6d649e51f6fa67d86c49ee2405d528475c31f450f406b1a2be2e691d1f52d71036cf571bf342b1c7bbfdb18aacafc58",
          "sha256": "ddfeada0f92e68af51cd57f3ddcf63f5349e6ad12c9b5c93c0313015c5cc3e8e",
          "sha1": "e3f7b5b02498f31f31ff09a28221f9502399b3a2",
          "md5": "b2ce74b02e7d0b4b4cf6bb0c3c064bd4"
        }
      ]
    }
  ]
}
