{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "2a2dbc6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-2a2dbc6.jar",
          "url": "antibytes-gradle-test-utils-2a2dbc6.jar",
          "size": 17243,
          "sha512": "0c05b1caec1140166195d9a6002c3875aa4cdea7a9989017f3b9477094a3128b04107d3c1a0bc47f28e29a799128e06426ebf931666ab6f1583a4c2d9d33cc5f",
          "sha256": "43f3968a7736df763ac9113a1be9e1ff3417208bb5a481a32fa2950b77c81448",
          "sha1": "6f64adfe9adaaa2d739e7f4eda2038db86b4d77c",
          "md5": "699743aa3850499d86b3a9ab93bebb67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-2a2dbc6.jar",
          "url": "antibytes-gradle-test-utils-2a2dbc6.jar",
          "size": 17243,
          "sha512": "0c05b1caec1140166195d9a6002c3875aa4cdea7a9989017f3b9477094a3128b04107d3c1a0bc47f28e29a799128e06426ebf931666ab6f1583a4c2d9d33cc5f",
          "sha256": "43f3968a7736df763ac9113a1be9e1ff3417208bb5a481a32fa2950b77c81448",
          "sha1": "6f64adfe9adaaa2d739e7f4eda2038db86b4d77c",
          "md5": "699743aa3850499d86b3a9ab93bebb67"
        }
      ]
    }
  ]
}
