{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "b12f9e2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-b12f9e2.jar",
          "url": "antibytes-gradle-utils-b12f9e2.jar",
          "size": 9568,
          "sha512": "38e743862fd326836016383d85386bed1c18e38ef2424675ec7ae49d732cb7c04bc307bb28cd52a6f081f56dd8cecffd80165de1c1d4d089096c38cd1ff48032",
          "sha256": "c51994b63958d7741dae91140d66c7babac845d37f0859785ae131addbfc9001",
          "sha1": "1b5a69a9020c539d591a941ba8ccba4ac05ed8d2",
          "md5": "17ac2eba9bf3d5ba79f68605f33a2863"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-b12f9e2.jar",
          "url": "antibytes-gradle-utils-b12f9e2.jar",
          "size": 9568,
          "sha512": "38e743862fd326836016383d85386bed1c18e38ef2424675ec7ae49d732cb7c04bc307bb28cd52a6f081f56dd8cecffd80165de1c1d4d089096c38cd1ff48032",
          "sha256": "c51994b63958d7741dae91140d66c7babac845d37f0859785ae131addbfc9001",
          "sha1": "1b5a69a9020c539d591a941ba8ccba4ac05ed8d2",
          "md5": "17ac2eba9bf3d5ba79f68605f33a2863"
        }
      ]
    }
  ]
}
