{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "5238ed6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-metadata-5238ed6-all.jar",
          "url": "test-utils-5238ed6-all.jar",
          "size": 9814,
          "sha512": "81a7f9d668287d9ff5153c73a1436376b3a8c550843e1660cf31a8d38c40bf966e03058a3d2ba27154218d1c263727ca2cd568e50da52ed43216bee2c37f1bb1",
          "sha256": "f54e44fbfc0534cfdb3441ac8d8ccec2cb5fbddc414ff7f765740e98c507d539",
          "sha1": "4748e6a2885c02e0b21638a31820b283f0ddf121",
          "md5": "10991b29cb523a45168d90d4ee7fd9ec"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-5238ed6.jar",
          "url": "test-utils-5238ed6.jar",
          "size": 3985,
          "sha512": "e8650b859623e98bdaea654074a5d0968a0047e87b99b023d5a7a33792aded83c452af4b7c2542ac422801f7107c4565e8660293c3effd8638e85c51b16359e3",
          "sha256": "cc4f363ceda2d29ec63fc1f907da090964d207498e0363a25cd3f7169ea31adf",
          "sha1": "6666f783a53b9219e1f9fddbbfac49e2b9db1a75",
          "md5": "808cfeac08570c1672157cd104103cd7"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/5238ed6/test-utils-android-5238ed6.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "5238ed6"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/5238ed6/test-utils-android-5238ed6.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "5238ed6"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosarm64/5238ed6/test-utils-iosarm64-5238ed6.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosarm64",
        "version": "5238ed6"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosarm64/5238ed6/test-utils-iosarm64-5238ed6.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosarm64",
        "version": "5238ed6"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iossimulatorarm64/5238ed6/test-utils-iossimulatorarm64-5238ed6.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iossimulatorarm64",
        "version": "5238ed6"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iossimulatorarm64/5238ed6/test-utils-iossimulatorarm64-5238ed6.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iossimulatorarm64",
        "version": "5238ed6"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosx64/5238ed6/test-utils-iosx64-5238ed6.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosx64",
        "version": "5238ed6"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosx64/5238ed6/test-utils-iosx64-5238ed6.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosx64",
        "version": "5238ed6"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-js/5238ed6/test-utils-js-5238ed6.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-js",
        "version": "5238ed6"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-js/5238ed6/test-utils-js-5238ed6.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-js",
        "version": "5238ed6"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/5238ed6/test-utils-jvm-5238ed6.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "5238ed6"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/5238ed6/test-utils-jvm-5238ed6.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "5238ed6"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-linuxx64/5238ed6/test-utils-linuxx64-5238ed6.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-linuxx64",
        "version": "5238ed6"
      }
    }
  ]
}
