{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "fa2239f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-fa2239f.jar",
          "url": "antibytes-grammar-tools-fa2239f.jar",
          "size": 39894,
          "sha512": "e6e6c9fbd0a24588b1064315c944b2652cb2f0444d706d9966d3b1bb33a5e2add9c60efceadcbbf271dca0eb845c41b56c259c8819f52b90df42b57d21c72233",
          "sha256": "ad55b953d56facdc33343e5e292583c1ffadaa7a914b6fc17250bba0abc048c9",
          "sha1": "5464b8205cee6f74bf2ddfcebdb79a4a2d334230",
          "md5": "4369999f2e89e84e1a18f5e72111ee79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-fa2239f.jar",
          "url": "antibytes-grammar-tools-fa2239f.jar",
          "size": 39894,
          "sha512": "e6e6c9fbd0a24588b1064315c944b2652cb2f0444d706d9966d3b1bb33a5e2add9c60efceadcbbf271dca0eb845c41b56c259c8819f52b90df42b57d21c72233",
          "sha256": "ad55b953d56facdc33343e5e292583c1ffadaa7a914b6fc17250bba0abc048c9",
          "sha1": "5464b8205cee6f74bf2ddfcebdb79a4a2d334230",
          "md5": "4369999f2e89e84e1a18f5e72111ee79"
        }
      ]
    }
  ]
}
