{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "fca89fa",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-fca89fa.jar",
          "url": "antibytes-coverage-fca89fa.jar",
          "size": 133730,
          "sha512": "71c47f4b43400b5004e9a26993b1b2652563610b08dfa5662e5e3e9c6482aa0ce7f4c50b6bf609625cba788399f45c4155b5ca68fd4a1078638e7f7388968d06",
          "sha256": "35ff00726c21bb9872ebb10b5f380dbe7b2066ac3bed2eb31d03729ee1321c09",
          "sha1": "878deae7fbd6805f893ddfdc8c0c7b8656369fc5",
          "md5": "d77472b2a3a05da5d3456bc91e2314b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "fca89fa"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-fca89fa.jar",
          "url": "antibytes-coverage-fca89fa.jar",
          "size": 133730,
          "sha512": "71c47f4b43400b5004e9a26993b1b2652563610b08dfa5662e5e3e9c6482aa0ce7f4c50b6bf609625cba788399f45c4155b5ca68fd4a1078638e7f7388968d06",
          "sha256": "35ff00726c21bb9872ebb10b5f380dbe7b2066ac3bed2eb31d03729ee1321c09",
          "sha1": "878deae7fbd6805f893ddfdc8c0c7b8656369fc5",
          "md5": "d77472b2a3a05da5d3456bc91e2314b9"
        }
      ]
    }
  ]
}
