{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "288f8da",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-288f8da.jar",
          "url": "antibytes-custom-component-288f8da.jar",
          "size": 16534,
          "sha512": "19afe25db2ee5ea3b878a2b98071ebb607374ecc4e884c00cedff49d86a3c59c936a4c59967cc475c4fdb1db810d87170dab77404b3a2f34644443fec5940f23",
          "sha256": "a2e84e2d146ab5d6f7edb35b5602dc7a94f9d378dbb78b5bf6e1e7b300905f3b",
          "sha1": "fc2425454d35938d203e3f49a9d5e302382e0d02",
          "md5": "577cb2f32922567b8d7e98c703698404"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-288f8da.jar",
          "url": "antibytes-custom-component-288f8da.jar",
          "size": 16534,
          "sha512": "19afe25db2ee5ea3b878a2b98071ebb607374ecc4e884c00cedff49d86a3c59c936a4c59967cc475c4fdb1db810d87170dab77404b3a2f34644443fec5940f23",
          "sha256": "a2e84e2d146ab5d6f7edb35b5602dc7a94f9d378dbb78b5bf6e1e7b300905f3b",
          "sha1": "fc2425454d35938d203e3f49a9d5e302382e0d02",
          "md5": "577cb2f32922567b8d7e98c703698404"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-custom-component-288f8da-javadoc.jar",
          "url": "antibytes-custom-component-288f8da-javadoc.jar",
          "size": 261,
          "sha512": "4e08f2d9eaabe2a11a8d0bfac80033eeb4595c3a3e26c4035602b771d6552a5d2b98508a26c3c6faabd8bf27f0a62621b0a7429bb968ac3a208c4f26e17118f9",
          "sha256": "f67e0ddc3d689b5137ff9573d00cd50d6f0dedb0ea0e906ec31e5ead9abb5f3e",
          "sha1": "d173de16dbc8c64b52a399e5b2a2e2a52b1cbf25",
          "md5": "21170ed1f2518a5db561f8ae6ec8a9b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-custom-component-288f8da-sources.jar",
          "url": "antibytes-custom-component-288f8da-sources.jar",
          "size": 3352,
          "sha512": "4711910f890b81a9f6599794710520c0eeda27726dac1e2529f795c0750886e771c3308ba360cc714f5f9963ae122dee8f417a825deabc56db5b842cd2d23e01",
          "sha256": "9eae37c3790b2fb942ba3b2677e2ea7c7333d37153416fab86e1dd85a69c0ab9",
          "sha1": "e02b0997f6b828fb63f21534a024a268e5940558",
          "md5": "1d9ce6406443f23d0ed19523af8401e4"
        }
      ]
    }
  ]
}
