{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/b9030f2/test-utils-coroutine-b9030f2.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "b9030f2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-watchosarm32-b9030f2.klib",
          "size": 11085,
          "sha512": "3f01f23a30dc50164ab7348f46f5a50c5e0279cb444b6df980c6a75eca76b37a0f3cd2802d1e94a5ae093569b5fd1156f30062cba7e277f2004783d1e343e77e",
          "sha256": "95686907262584d70cc79cc5e3f6b6a4165928691956940fb1d6d63dabc6d92a",
          "sha1": "a3754e7a0f92a65338b49de1e82aebac0468ed11",
          "md5": "7bbea017ee2d742a29a7cd64b21657b4"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-coroutine-watchosarm32-b9030f2-sources.jar",
          "url": "test-utils-coroutine-watchosarm32-b9030f2-sources.jar",
          "size": 4432,
          "sha512": "a6473d4ff59cb600f3c0fa9878a35c8f858acacd98510b4befc1e5f35be910c62a88e3b6041f5ba76c050b7c41af13fff93cd8bf60902a249f16b7429faa3ecf",
          "sha256": "cec6c043fde96eb3a674995451dc91cc39b82763e15d04e005be7dc8b426bde6",
          "sha1": "9c071f18ad7900caca2bc6884118c0e6ea620326",
          "md5": "a9e30d3490844e974b0610b29233965f"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-watchosarm32-b9030f2-metadata.jar",
          "url": "test-utils-coroutine-watchosarm32-b9030f2-metadata.jar",
          "size": 261,
          "sha512": "0b4dbf0e3aebb60994db29e0e3a5036a22adec671fd16e22ab0620b1131923d90444abf6738ed99b7c42dda1f705bac3cec7f54b96cfda748e251e4c59b5fc56",
          "sha256": "1cf687bd45990bb9ab50903fc49ea1391afb8c8f26935d121773dcf9a4f880da",
          "sha1": "7ed1f4ac30f3e9a1ba361090eb711ed0968a97b6",
          "md5": "ba805f3f705f6c83f568b50a3a31dbb2"
        }
      ]
    }
  ]
}
