{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-catalog",
    "version": "31fab8d-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-31fab8d-SNAPSHOT.toml",
          "url": "antibytes-dependency-catalog-31fab8d-SNAPSHOT.toml",
          "size": 230399,
          "sha512": "5b4aa86916d21a15d855b570840d180df00f7616c68f53c21a3b9540002f9901dd07ebaa05c2a28bd753ce665048dbc6d6d2f929d5176627792927aafa1f4408",
          "sha256": "8f7ebabb4ab5387b582efb0a701ae39e721eaf1f44eeff826fed7dfcb721e090",
          "sha1": "feab2c09e4c1b49d10ef85bc100d7905660728c9",
          "md5": "dae641bf87344eebddfcdd674f613ed3"
        }
      ]
    }
  ]
}
