{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/907767d/kmock-907767d.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "907767d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "8b81c5a"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-linuxx64-907767d.klib",
          "size": 70670,
          "sha512": "1d057b09b88581c1df7144b81c2fe43861e6833227b8bdc43cc50e64e89e0a9ff4289efbb57aeeaaedf6b724b5f91d89c3ae40875f5935a625b2ff7cd6412193",
          "sha256": "ae0dcf8e4a1b8d10f3bc671754a23387c4b887bae3c488a7160324dd49812530",
          "sha1": "858296d4c8a665b4b5094f0ce4b16e36a7da069b",
          "md5": "4989bc9fd47f7c87a9cc0a182a67c899"
        }
      ]
    }
  ]
}
