{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.quality",
    "module": "antibytes-quality",
    "version": "080e68f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "4.4.1.3373"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-080e68f.jar",
          "url": "antibytes-quality-080e68f.jar",
          "size": 64752,
          "sha512": "036244c6409876de19f71f460c8892cf524da47c5abdd5d651f1e1a919a27d455284cad95a6af340bc3064c0133ba802b0d52aa3f4e7c15d47e4e1b4b2ddec52",
          "sha256": "543341bef90e5fbc869653bd6c2c83a68e648e940bb98f610461524ed6eef65c",
          "sha1": "1f0cc20a4c169deb33c42800d9a4d5bcc7412747",
          "md5": "57a10cfaebd16061d9cd64d039c67093"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.25.0"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "080e68f"
          }
        },
        {
          "group": "tech.antibytes.gradle.dependency.helper",
          "module": "antibytes-dependency-helper",
          "version": {
            "requires": "080e68f"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "4.4.1.3373"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-080e68f.jar",
          "url": "antibytes-quality-080e68f.jar",
          "size": 64752,
          "sha512": "036244c6409876de19f71f460c8892cf524da47c5abdd5d651f1e1a919a27d455284cad95a6af340bc3064c0133ba802b0d52aa3f4e7c15d47e4e1b4b2ddec52",
          "sha256": "543341bef90e5fbc869653bd6c2c83a68e648e940bb98f610461524ed6eef65c",
          "sha1": "1f0cc20a4c169deb33c42800d9a4d5bcc7412747",
          "md5": "57a10cfaebd16061d9cd64d039c67093"
        }
      ]
    }
  ]
}
