{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/5454da8/test-utils-5454da8.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "5454da8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-5454da8.jar",
          "size": 17517,
          "sha512": "f3a5a8ebf91df1ef118e4928dadaf6dd809bf17c4f401f73217be3c33c91dd1e97bb97a7d4eb2684483caaaf2aa4f70744e0c945e5151fffd4b8498728bd9612",
          "sha256": "bb270f9b81a9b4da78f3a62b7ec53e82131588c8781552071de8e11e12306839",
          "sha1": "dfbf7f30be68f318adab7c7ceba0992dc8837260",
          "md5": "9f6e8f15d08bcecb87cd5485ebaca3d1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-5454da8.jar",
          "size": 17517,
          "sha512": "f3a5a8ebf91df1ef118e4928dadaf6dd809bf17c4f401f73217be3c33c91dd1e97bb97a7d4eb2684483caaaf2aa4f70744e0c945e5151fffd4b8498728bd9612",
          "sha256": "bb270f9b81a9b4da78f3a62b7ec53e82131588c8781552071de8e11e12306839",
          "sha1": "dfbf7f30be68f318adab7c7ceba0992dc8837260",
          "md5": "9f6e8f15d08bcecb87cd5485ebaca3d1"
        }
      ]
    }
  ]
}
