{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "5cd8a47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-5cd8a47.jar",
          "url": "antibytes-android-application-configuration-5cd8a47.jar",
          "size": 56574,
          "sha512": "1ddad5e8412a09112a446ec2f282a6493260edc01bcc9f76108143a02c8a78efda4b01270d734eb40ce8cd0d137c1a87b0212429d500a1d4d9bbabff0d3804c2",
          "sha256": "4a33e24664f5fc0dc83e386845351e7729aafc7d234fcea2f781f4afeb355b07",
          "sha1": "9d0ed50433c40c5c55d7429ab63d84c255645637",
          "md5": "3b0a13fec3bd4827522071f121f57913"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "5cd8a47"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-5cd8a47.jar",
          "url": "antibytes-android-application-configuration-5cd8a47.jar",
          "size": 56574,
          "sha512": "1ddad5e8412a09112a446ec2f282a6493260edc01bcc9f76108143a02c8a78efda4b01270d734eb40ce8cd0d137c1a87b0212429d500a1d4d9bbabff0d3804c2",
          "sha256": "4a33e24664f5fc0dc83e386845351e7729aafc7d234fcea2f781f4afeb355b07",
          "sha1": "9d0ed50433c40c5c55d7429ab63d84c255645637",
          "md5": "3b0a13fec3bd4827522071f121f57913"
        }
      ]
    }
  ]
}
