{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "999693f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "999693f"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-999693f.jar",
          "url": "antibytes-mkdocs-999693f.jar",
          "size": 11930,
          "sha512": "0a0e5f0d6d11f41652a4d791770ab676c7525e7fbf81f779a51c5f7df3d2dc21029949c381f48198fc041966ea375b81a5e749b4abaff16967ef911c6b4e4de1",
          "sha256": "b36d25a881a01f75ef025116788fae9d3d008fe3886905e88a3b5cef9f53f93d",
          "sha1": "a329a956579c673ba063a46db0d0bf7e9e2e1509",
          "md5": "b99f597e8588239c07c1c56574c3a2ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "999693f"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "999693f"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-999693f.jar",
          "url": "antibytes-mkdocs-999693f.jar",
          "size": 11930,
          "sha512": "0a0e5f0d6d11f41652a4d791770ab676c7525e7fbf81f779a51c5f7df3d2dc21029949c381f48198fc041966ea375b81a5e749b4abaff16967ef911c6b4e4de1",
          "sha256": "b36d25a881a01f75ef025116788fae9d3d008fe3886905e88a3b5cef9f53f93d",
          "sha1": "a329a956579c673ba063a46db0d0bf7e9e2e1509",
          "md5": "b99f597e8588239c07c1c56574c3a2ba"
        }
      ]
    }
  ]
}
