{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.dokka",
    "module": "antibytes-dokka-configuration",
    "version": "89ba0c4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dokka-configuration-89ba0c4.jar",
          "url": "antibytes-dokka-configuration-89ba0c4.jar",
          "size": 7889,
          "sha512": "87e57f294137c51f1781fbcf23ef547bd6763630de1ff159fcf4866e2bdc9a3c4dfccf5138e45fc34637495439db075b1597ed0a56f2effdc8fd1345bf1bca86",
          "sha256": "d682cec961bacabc98523759ad14b9c4679a1d18f15652b1cd6bd7b27c63a679",
          "sha1": "3761df5ede28559648827dfc55190bf3af38d639",
          "md5": "3c858f76326c1168184a5b7151ce1f94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "89ba0c4"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dokka-configuration-89ba0c4.jar",
          "url": "antibytes-dokka-configuration-89ba0c4.jar",
          "size": 7889,
          "sha512": "87e57f294137c51f1781fbcf23ef547bd6763630de1ff159fcf4866e2bdc9a3c4dfccf5138e45fc34637495439db075b1597ed0a56f2effdc8fd1345bf1bca86",
          "sha256": "d682cec961bacabc98523759ad14b9c4679a1d18f15652b1cd6bd7b27c63a679",
          "sha1": "3761df5ede28559648827dfc55190bf3af38d639",
          "md5": "3c858f76326c1168184a5b7151ce1f94"
        }
      ]
    }
  ]
}
