{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "f6a864b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-f6a864b.jar",
          "url": "antibytes-android-application-configuration-f6a864b.jar",
          "size": 63996,
          "sha512": "b15e09f2c4bb4066e2d789203090c037ac107d3c5ab937418d33ba54694b5a5abee85b3bd7c1d7396fd14b105cc980883d159df5a3d2fcf5fa41f4edd3ca7863",
          "sha256": "8d623d03e623d4d2e6effd853ff327b344344772e3cd1a40d9d6bf5786ea5b90",
          "sha1": "1b9992cc57089fdecb7357bead0896a3e66bb8a4",
          "md5": "e5228cfc7b8407137444819922e2301f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "f6a864b"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-f6a864b.jar",
          "url": "antibytes-android-application-configuration-f6a864b.jar",
          "size": 63996,
          "sha512": "b15e09f2c4bb4066e2d789203090c037ac107d3c5ab937418d33ba54694b5a5abee85b3bd7c1d7396fd14b105cc980883d159df5a3d2fcf5fa41f4edd3ca7863",
          "sha256": "8d623d03e623d4d2e6effd853ff327b344344772e3cd1a40d9d6bf5786ea5b90",
          "sha1": "1b9992cc57089fdecb7357bead0896a3e66bb8a4",
          "md5": "e5228cfc7b8407137444819922e2301f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-f6a864b-javadoc.jar",
          "url": "antibytes-android-application-configuration-f6a864b-javadoc.jar",
          "size": 261,
          "sha512": "310c324bd7eac6e75f5dfde702a3719317066ca5ca9f3430308a09978919b7df0772b46ff85de8109720886c5db9a5d1287bf68140a697f2dd0004977a554505",
          "sha256": "f1755d291141206251e25f0142a3cbd4bc003741cdb38d062f05ac306c904f0b",
          "sha1": "c2a4322b145deff5162fbbd1d0dff8279a88f0d7",
          "md5": "ae285091dcbeabd189e9d5dec490eac6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-f6a864b-sources.jar",
          "url": "antibytes-android-application-configuration-f6a864b-sources.jar",
          "size": 12867,
          "sha512": "536037d93fc476d21a62cf0283d246c7f1c15a581ad0bcf45dea84ec19ad982306f895d801f3e68dfb0e6e27ab3e68362899badc92175934ef45573f4ed36f09",
          "sha256": "7afb150f5a1b7b3204b1a950cfb7ebcf72cb1861b5b90b238f8698f1c595b759",
          "sha1": "52daed5abe823eb000d96d0ac0fc4f375cc83236",
          "md5": "e5dbfcbc79f964fb2a4cd10c98e0f55c"
        }
      ]
    }
  ]
}
