{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.2.0-SNAPSHOT/kmock-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.2.0-SNAPSHOT.klib",
          "url": "kmock-js-0.2.0-SNAPSHOT.klib",
          "size": 216422,
          "sha512": "62e30960c50d1cd302fcfc20ea7200c0cf3fa06a06e7e21073566e2b082fdfd06161e6da34770fcb5256fe18220e8c03d5125ca0298529eae6abd073915dc7e3",
          "sha256": "6f4808805541c4bd6026f1fbf52c8ef879a6b9f4edb88ee8b93fcd663c08637a",
          "sha1": "e24ec604a49b0728de96420977fa6a5827bc46aa",
          "md5": "2170a5c4a7bf214c0b9f9b1bfc23129b"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.2.0-SNAPSHOT.klib",
          "url": "kmock-js-0.2.0-SNAPSHOT.klib",
          "size": 216422,
          "sha512": "62e30960c50d1cd302fcfc20ea7200c0cf3fa06a06e7e21073566e2b082fdfd06161e6da34770fcb5256fe18220e8c03d5125ca0298529eae6abd073915dc7e3",
          "sha256": "6f4808805541c4bd6026f1fbf52c8ef879a6b9f4edb88ee8b93fcd663c08637a",
          "sha1": "e24ec604a49b0728de96420977fa6a5827bc46aa",
          "md5": "2170a5c4a7bf214c0b9f9b1bfc23129b"
        }
      ]
    }
  ]
}
