{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "967d356",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-967d356.jar",
          "url": "antibytes-grammar-tools-967d356.jar",
          "size": 39410,
          "sha512": "033983a5eb5e5f1e1ba9f69712623da94288049d20ddc9febe206991849f42e9a2a67fdc555c6bcdaac07bef2a0a96fc6da4acdf0828c6a1b0d2e57c3be8472d",
          "sha256": "ccbbe7f656be6d07795d8675e96034c8a5e86678f9d72a704ff93ef5b2f19f73",
          "sha1": "c2bfd2ba8f30cd3fc0ff8eb68c414e740e6c1b85",
          "md5": "2ad1ed61468eef5f5500a1cc1b3af7f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-967d356.jar",
          "url": "antibytes-grammar-tools-967d356.jar",
          "size": 39410,
          "sha512": "033983a5eb5e5f1e1ba9f69712623da94288049d20ddc9febe206991849f42e9a2a67fdc555c6bcdaac07bef2a0a96fc6da4acdf0828c6a1b0d2e57c3be8472d",
          "sha256": "ccbbe7f656be6d07795d8675e96034c8a5e86678f9d72a704ff93ef5b2f19f73",
          "sha1": "c2bfd2ba8f30cd3fc0ff8eb68c414e740e6c1b85",
          "md5": "2ad1ed61468eef5f5500a1cc1b3af7f5"
        }
      ]
    }
  ]
}
