{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/5238ed6/test-utils-fixture-5238ed6.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "5238ed6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture.klib",
          "url": "test-utils-fixture-iossimulatorarm64-5238ed6.klib",
          "size": 32918,
          "sha512": "3e557e885027620afce093f076377386c7b8588d38d140318f18f7dba2c90987b2771852138e7cd4568e79bd03a1198a1efc767293fc6143cadee87b6a0790c0",
          "sha256": "5f9c1e22f4a3c9f25c1bd9c49ee2da85877ec0ca67b4452e23f47aef1017f8ea",
          "sha1": "55d973f80887696e2131c619dfb570966d0aefd2",
          "md5": "542f9e009650b31c2b3c264baa8b5246"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-iossimulatorarm64-5238ed6-metadata.jar",
          "url": "test-utils-fixture-iossimulatorarm64-5238ed6-metadata.jar",
          "size": 261,
          "sha512": "dce4caff1f0d79fbaf94ca18159d49a99aec04cf45dbf60985f1a5a9ea46bee169319cbb6e650c15c54a4018b9be5a5c5675c894a9407c0e2b34ce4916adb39f",
          "sha256": "74c63770a93ca03ed353342702710356f9f6ad635cd032c71174b1fb8ceddf29",
          "sha1": "317795525644599dd5024c982e80b8705b078336",
          "md5": "82a2c6556b0dbf2a7914349db197d7c3"
        }
      ]
    }
  ]
}
