{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "de4d813",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-de4d813.jar",
          "url": "antibytes-versioning-de4d813.jar",
          "size": 24286,
          "sha512": "87a92497713934f74b4736834ba2ec101bbc7147471fd55d325bb5d6f64b8d2c9949c3221d9ccbf1d38fc1b8d3e75bd37b512f61d19c1bf35100e5a4df718808",
          "sha256": "e3dd3e36198c9389ddf1db7bf6f9d6a52a2d09a0becf48076eb0bc700c259264",
          "sha1": "2de26722d9729f351787e87926697e1d3b436c81",
          "md5": "c3f3cd0995b7b466cb1b3f5c5a9ca52a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-de4d813.jar",
          "url": "antibytes-versioning-de4d813.jar",
          "size": 24286,
          "sha512": "87a92497713934f74b4736834ba2ec101bbc7147471fd55d325bb5d6f64b8d2c9949c3221d9ccbf1d38fc1b8d3e75bd37b512f61d19c1bf35100e5a4df718808",
          "sha256": "e3dd3e36198c9389ddf1db7bf6f9d6a52a2d09a0becf48076eb0bc700c259264",
          "sha1": "2de26722d9729f351787e87926697e1d3b436c81",
          "md5": "c3f3cd0995b7b466cb1b3f5c5a9ca52a"
        }
      ]
    }
  ]
}
