{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-test-utils",
    "version": "328fc7c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-test-utils-328fc7c.jar",
          "url": "antibytes-test-utils-328fc7c.jar",
          "size": 15046,
          "sha512": "62d27ab17a9604f09f161034bac518a74f28fa0350b1d0850de96cf526a2f523486594f60f1540e5b5d02a5e626ccce3bf6b2682ba87bcb1e9c5438faf03e5c2",
          "sha256": "b3dbb63ee89b997243f92785715e2d7c92b8000e4da8cdf276dfea61ee9062f8",
          "sha1": "f55ae3c3b915eb033be7e3a9f2badac3323ccd12",
          "md5": "14d7ddf2fa12c14419b4135362879c5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-test-utils-328fc7c.jar",
          "url": "antibytes-test-utils-328fc7c.jar",
          "size": 15046,
          "sha512": "62d27ab17a9604f09f161034bac518a74f28fa0350b1d0850de96cf526a2f523486594f60f1540e5b5d02a5e626ccce3bf6b2682ba87bcb1e9c5438faf03e5c2",
          "sha256": "b3dbb63ee89b997243f92785715e2d7c92b8000e4da8cdf276dfea61ee9062f8",
          "sha1": "f55ae3c3b915eb033be7e3a9f2badac3323ccd12",
          "md5": "14d7ddf2fa12c14419b4135362879c5b"
        }
      ]
    }
  ]
}
