{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "a7a030d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-ktor-metadata-all.jar",
          "url": "test-utils-ktor-a7a030d-all.jar",
          "size": 4936,
          "sha512": "ce42a5f424b9c2ff7d3c7c067fb7590d9771003d39678838a5875cea9da1de4bba86b1c658e3e2e43d908059094cc5a4691446cd25d771df8fa2a869a842a687",
          "sha256": "2d424fc81f8cefa42dc21a6069af888a2dd496deaee22b2de97820a294f603cf",
          "sha1": "b8f2a3ab8b5a6ba27097305381597af81492d405",
          "md5": "6004d3abaa7a365f3be2235b24150d37"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-ktor.jar",
          "url": "test-utils-ktor-a7a030d.jar",
          "size": 2460,
          "sha512": "ae96d3dbf70a45e6ccf5c4c00d726aa185b6a5dcb9bb447e1b8c75dd3d0783b699c2616296beaa04e50fb7dc87bb9a47f0ad880862f96d769a2681b0773aef63",
          "sha256": "fa9eaca4825d66a03956a51d6f5cc50918ba271c16a9876360136a36ee858712",
          "sha1": "6321d340fd23574e92be6ec97cd7844f15bff5b2",
          "md5": "3a0ec4e1de11c2b282dac6cb43df97c1"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/a7a030d/test-utils-ktor-android-a7a030d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "a7a030d"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/a7a030d/test-utils-ktor-android-a7a030d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "a7a030d"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-ktor-js/a7a030d/test-utils-ktor-js-a7a030d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-js",
        "version": "a7a030d"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-ktor-js/a7a030d/test-utils-ktor-js-a7a030d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-js",
        "version": "a7a030d"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/a7a030d/test-utils-ktor-jvm-a7a030d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "a7a030d"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/a7a030d/test-utils-ktor-jvm-a7a030d.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "a7a030d"
      }
    }
  ]
}
