{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/56c4547/test-utils-annotations-junit5-56c4547.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "56c4547",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-tvosx64-56c4547.klib",
          "size": 7043,
          "sha512": "1c63edc7beff8c107b430a09674c9a667ba69ace1a9f568f10f985c413cdc33d481632a40ef5d0e38dfcca6d01485d99d2c936d31aa1ea1f34ef178857f415a7",
          "sha256": "05b2fbc3bb6638eaacc1657ae62d6e6f3ae7b4ae7d8f82e43a96a9b063fcaa2d",
          "sha1": "a2987b06ed0706c705f5c9b381c121d7da3a580f",
          "md5": "bba78f4957c769222f4b0f86a51e602d"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-tvosx64-56c4547-metadata.jar",
          "url": "test-utils-annotations-junit5-tvosx64-56c4547-metadata.jar",
          "size": 261,
          "sha512": "ac1a161570abe4527b1e96ab78226e6ea93110b7d165cd3682f4cb8843e0618776da8935b45d9ee9d97503e8ca17a7bcaa7224d8dca304d4c414f7d6a4d4ee12",
          "sha256": "86a4dfe3e0cb7440826927eede540c43ed6998f82d8c684932f6d4c1b1613899",
          "sha1": "2c6a2e5830ed9fdf2ba047fba39cb67461ded601",
          "md5": "7926c90ddaa655ac28714311f04a0858"
        }
      ]
    }
  ]
}
