{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "cfd6317",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "cfd6317"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-cfd6317.jar",
          "url": "antibytes-mkdocs-cfd6317.jar",
          "size": 12153,
          "sha512": "9a8ea0516752927a10fccfe3d6700fd9d7d8876f3f6bde58d17c3f7451e2548d7eb4e114056c455115f0a6e22e7076a0721316d112277fb2f01a6715cfa4c205",
          "sha256": "d9dd374710e06f08c99a653a1cf73abdd19a3c7be4015b6881488db429efc698",
          "sha1": "46cc8673da01d6e5884f9e16e7c9edf186082ea8",
          "md5": "568966b8cc1a389b69748db1381a0c01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "cfd6317"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "cfd6317"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-cfd6317.jar",
          "url": "antibytes-mkdocs-cfd6317.jar",
          "size": 12153,
          "sha512": "9a8ea0516752927a10fccfe3d6700fd9d7d8876f3f6bde58d17c3f7451e2548d7eb4e114056c455115f0a6e22e7076a0721316d112277fb2f01a6715cfa4c205",
          "sha256": "d9dd374710e06f08c99a653a1cf73abdd19a3c7be4015b6881488db429efc698",
          "sha1": "46cc8673da01d6e5884f9e16e7c9edf186082ea8",
          "md5": "568966b8cc1a389b69748db1381a0c01"
        }
      ]
    }
  ]
}
