{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "2a98d8e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-metadata-2a98d8e.jar",
          "url": "kmock-2a98d8e.jar",
          "size": 18077,
          "sha512": "cceca7e847f9a4da2ff643f661137aaac087435662482cffcc8e682f5905420032abdc132e2d5e756ace924965ac8537d3eca5e7ea83852624a226550afc6994",
          "sha256": "326b4577ad3ccddb5afdab74e06b8b5f5880743d80c50ad68000f378a05d192f",
          "sha1": "a818682abe497d145df6670b9f3fa767ef7d9a40",
          "md5": "9eccb07fb7acc88539f38ec37a24e082"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/2a98d8e/kmock-android-2a98d8e.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "2a98d8e"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/2a98d8e/kmock-android-2a98d8e.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "2a98d8e"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/2a98d8e/kmock-iosarm64-2a98d8e.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "2a98d8e"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/2a98d8e/kmock-iosx64-2a98d8e.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "2a98d8e"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/2a98d8e/kmock-js-2a98d8e.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "2a98d8e"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/2a98d8e/kmock-js-2a98d8e.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "2a98d8e"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/2a98d8e/kmock-jvm-2a98d8e.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "2a98d8e"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/2a98d8e/kmock-jvm-2a98d8e.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "2a98d8e"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/2a98d8e/kmock-linuxx64-2a98d8e.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "2a98d8e"
      }
    }
  ]
}
