{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "0193e7c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-0193e7c.jar",
          "url": "antibytes-dependency-0193e7c.jar",
          "size": 71463,
          "sha512": "1e7adb4011bc93a55e1c9029bf08da0a2ce2d8416ffae68fa07fd6272460e3853482efd300a4a4c64a4b548e99f24c4b018524e6df714fa0bd9579a4324c7ca4",
          "sha256": "1a24cc604f005478042e59cc4030e6be73762f2c166c9b2fba5eb05f04d80b31",
          "sha1": "75150a88960d0bb0d8d22caf70f8e2f2be037bf3",
          "md5": "cdafe6549dc3564fa573673147c2b9b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-gradle-plugin",
          "version": {
            "requires": "0.17.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.0.4.1"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.44.0"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "0193e7c"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-0193e7c.jar",
          "url": "antibytes-dependency-0193e7c.jar",
          "size": 71463,
          "sha512": "1e7adb4011bc93a55e1c9029bf08da0a2ce2d8416ffae68fa07fd6272460e3853482efd300a4a4c64a4b548e99f24c4b018524e6df714fa0bd9579a4324c7ca4",
          "sha256": "1a24cc604f005478042e59cc4030e6be73762f2c166c9b2fba5eb05f04d80b31",
          "sha1": "75150a88960d0bb0d8d22caf70f8e2f2be037bf3",
          "md5": "cdafe6549dc3564fa573673147c2b9b6"
        }
      ]
    }
  ]
}
