{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "bde325d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-bde325d.jar",
          "url": "antibytes-gradle-test-utils-bde325d.jar",
          "size": 17243,
          "sha512": "63683a1ed31f409cf61ddb29ce76a676d9657cee553ddddcf0cf9957871204b9ad8d5e67ee7bf89e16f47b29246241d81c35d9f1437eac62db3b3888283f5cfa",
          "sha256": "e1b86bfae73b88473b1062a8b6954b06711d11a03e1ffad7a4831f25dfd8fcdc",
          "sha1": "cfd6f482be8239b5d53825b8380b18126b689c34",
          "md5": "41c6c9d5f78afd55946cd0ea1c0fc6fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-bde325d.jar",
          "url": "antibytes-gradle-test-utils-bde325d.jar",
          "size": 17243,
          "sha512": "63683a1ed31f409cf61ddb29ce76a676d9657cee553ddddcf0cf9957871204b9ad8d5e67ee7bf89e16f47b29246241d81c35d9f1437eac62db3b3888283f5cfa",
          "sha256": "e1b86bfae73b88473b1062a8b6954b06711d11a03e1ffad7a4831f25dfd8fcdc",
          "sha1": "cfd6f482be8239b5d53825b8380b18126b689c34",
          "md5": "41c6c9d5f78afd55946cd0ea1c0fc6fb"
        }
      ]
    }
  ]
}
