{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.2.0-SNAPSHOT.klib",
          "url": "core-js-0.2.0-SNAPSHOT.klib",
          "size": 123790,
          "sha512": "ec9d57a48afe684a870d192866ca97bc54f27eadb0db51ab43f95162e1fd6dc445d28e7be3cec1ac261324d879b0b6dcc6dc1ce1c554f723cca43c4572922c98",
          "sha256": "743f907ad318f7e7233f2aa42a06837d54150f4a4b6b18c3e0b32c0984fee8b8",
          "sha1": "7b7c0c9467e94ba75ab3b1f0b2f89464660e4099",
          "md5": "9ef9a557eebc813eff818f87d809a2af"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.2.0-SNAPSHOT.klib",
          "url": "core-js-0.2.0-SNAPSHOT.klib",
          "size": 123790,
          "sha512": "ec9d57a48afe684a870d192866ca97bc54f27eadb0db51ab43f95162e1fd6dc445d28e7be3cec1ac261324d879b0b6dcc6dc1ce1c554f723cca43c4572922c98",
          "sha256": "743f907ad318f7e7233f2aa42a06837d54150f4a4b6b18c3e0b32c0984fee8b8",
          "sha1": "7b7c0c9467e94ba75ab3b1f0b2f89464660e4099",
          "md5": "9ef9a557eebc813eff818f87d809a2af"
        }
      ]
    }
  ]
}
