{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.2.0-SNAPSHOT.klib",
          "url": "core-js-0.2.0-SNAPSHOT.klib",
          "size": 77468,
          "sha512": "de903be4f5170c84a35ce01806f9bc64e6c9531b756df892aaebc7fb5e5932594c99f659d1c3ecedcb34e12ca1bb98b0676777f22e4fc20a68f29dc01f3ebd4f",
          "sha256": "6ab1bbd28181e6988d17933de7e9f7fc8ba207f26fdc6ef858db20eb0c68ca08",
          "sha1": "05268f715729fda3762a3f43b90e6da1e9153a2a",
          "md5": "3792a8774df2d9bac85fb107f0a2f1fb"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.2.0-SNAPSHOT.klib",
          "url": "core-js-0.2.0-SNAPSHOT.klib",
          "size": 77468,
          "sha512": "de903be4f5170c84a35ce01806f9bc64e6c9531b756df892aaebc7fb5e5932594c99f659d1c3ecedcb34e12ca1bb98b0676777f22e4fc20a68f29dc01f3ebd4f",
          "sha256": "6ab1bbd28181e6988d17933de7e9f7fc8ba207f26fdc6ef858db20eb0c68ca08",
          "sha1": "05268f715729fda3762a3f43b90e6da1e9153a2a",
          "md5": "3792a8774df2d9bac85fb107f0a2f1fb"
        }
      ]
    }
  ]
}
