{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-SNAPSHOT.jar",
          "size": 263931,
          "sha512": "5e75b700322b1bac734d938eeb462750fa506f35eb9b32f9481e5b04cc98d5712c34c2e9d15037e86268f4f7032d2542f9ce4f67f1d7183e966c173afbd18673",
          "sha256": "02600f39265a4ba3e20eece7be85f00fd3b09dbf1f2024748d69898d3a0bb91b",
          "sha1": "168d96d64d4abe80b56a12b6ad484705f26eb5a3",
          "md5": "101d66c32a424ad8fdecc4940470dd97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.1.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-SNAPSHOT.jar",
          "size": 263931,
          "sha512": "5e75b700322b1bac734d938eeb462750fa506f35eb9b32f9481e5b04cc98d5712c34c2e9d15037e86268f4f7032d2542f9ce4f67f1d7183e966c173afbd18673",
          "sha256": "02600f39265a4ba3e20eece7be85f00fd3b09dbf1f2024748d69898d3a0bb91b",
          "sha1": "168d96d64d4abe80b56a12b6ad484705f26eb5a3",
          "md5": "101d66c32a424ad8fdecc4940470dd97"
        }
      ]
    }
  ]
}
