{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-SNAPSHOT.jar",
          "size": 177934,
          "sha512": "d7959128a220e5c81a1612f305f2893987a510d5e53d99510bd096016f20de25e57a49584e4dd018dad72346a437b0373fba93acaa63f96c67abef6942fbc57d",
          "sha256": "88146bfd58ed6dd7a38fec85e38cae02f0e67b122d2003a6fc21b8c003d3c923",
          "sha1": "07bc1755be612c0066f8ffd029c61e00298e596b",
          "md5": "1ed1cbb0bb609a5f33c83aba1aed44e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.1.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-SNAPSHOT.jar",
          "size": 177934,
          "sha512": "d7959128a220e5c81a1612f305f2893987a510d5e53d99510bd096016f20de25e57a49584e4dd018dad72346a437b0373fba93acaa63f96c67abef6942fbc57d",
          "sha256": "88146bfd58ed6dd7a38fec85e38cae02f0e67b122d2003a6fc21b8c003d3c923",
          "sha1": "07bc1755be612c0066f8ffd029c61e00298e596b",
          "md5": "1ed1cbb0bb609a5f33c83aba1aed44e4"
        }
      ]
    }
  ]
}
