{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-SNAPSHOT.jar",
          "size": 239161,
          "sha512": "cae47509e954845c75e0c7dd4b660c8e5b33cf80d04bccb1e30b5c78551a5327abdeb566af8757ce54d988bd50676d41adbadd407d22a64683a988562de3cee6",
          "sha256": "3ad82124af6b1ad8a19037abe15577f74e7dcff1fb435a763de6ecf77cc6b1c3",
          "sha1": "603dc46457118ad7c2a86c1ba331929437e5bca3",
          "md5": "774c79dc20608c8683b777b4ed665594"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.1.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-SNAPSHOT.jar",
          "size": 239161,
          "sha512": "cae47509e954845c75e0c7dd4b660c8e5b33cf80d04bccb1e30b5c78551a5327abdeb566af8757ce54d988bd50676d41adbadd407d22a64683a988562de3cee6",
          "sha256": "3ad82124af6b1ad8a19037abe15577f74e7dcff1fb435a763de6ecf77cc6b1c3",
          "sha1": "603dc46457118ad7c2a86c1ba331929437e5bca3",
          "md5": "774c79dc20608c8683b777b4ed665594"
        }
      ]
    }
  ]
}
