{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-SNAPSHOT.jar",
          "size": 115155,
          "sha512": "1aea265c84161cec06bfb270ca132700e3d95475d29b7f01bebea6f26dd7ecf507e68bc2acf7c5663803b46f3b87b6fec44bf1514af36f904348de7187da9ec4",
          "sha256": "747dab9617d7738dc17f61b3870d65a2729cb2f325fc5812b127a077377aa3d3",
          "sha1": "e45126a93eb914184791e25be9b78d89e1f07ece",
          "md5": "57b926cf8ccd2e5813e7667af2adfb48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.1.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-SNAPSHOT.jar",
          "size": 115155,
          "sha512": "1aea265c84161cec06bfb270ca132700e3d95475d29b7f01bebea6f26dd7ecf507e68bc2acf7c5663803b46f3b87b6fec44bf1514af36f904348de7187da9ec4",
          "sha256": "747dab9617d7738dc17f61b3870d65a2729cb2f325fc5812b127a077377aa3d3",
          "sha1": "e45126a93eb914184791e25be9b78d89e1f07ece",
          "md5": "57b926cf8ccd2e5813e7667af2adfb48"
        }
      ]
    }
  ]
}
