{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/7008207/test-utils-annotations-7008207.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "7008207",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-iosx64-7008207.klib",
          "size": 11190,
          "sha512": "7636affaa2508e0641fd82b7b5312f754be431877d8ba8ccf48ce3e3cbb7c69b2877a3d5968896c05cb85068366fbd8be3d98d4b5d76b24f24e0667ecb15a954",
          "sha256": "600ab0112815257158cd95518792fa5f376bb19b4912b0d02f5d8eb95c43cb00",
          "sha1": "f299b0776b29df3292eefb2000e37152e09dd6f6",
          "md5": "b593084051b99e0e2280d02971e86651"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-iosx64-7008207-metadata.jar",
          "url": "test-utils-annotations-iosx64-7008207-metadata.jar",
          "size": 261,
          "sha512": "a7fb61429721276f5380d717e5378c9bbd123282137a435fec81722ddd78b5ff562625bbddac5c05d5229399e7a8cf557cca1f240c886123e0275a2fa375a3b6",
          "sha256": "d2e4de164935a781abeecffd9b6f60945a9a7393751ef2df21f786676abb5d4c",
          "sha1": "cd91ec03798d7dc8559746f65cd799bc67bcf600",
          "md5": "8d14b36b6e380d2ef6e4247f8ab1cd77"
        }
      ]
    }
  ]
}
