{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/61a6ee5/test-utils-coroutine-61a6ee5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "61a6ee5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iossimulatorarm64-61a6ee5.klib",
          "size": 10210,
          "sha512": "4e6c8650d52b4ac184d14f704e3a2a119b82315ba8665094297dde817c1c6577a274a1a2e6359a9d6462dfe15d26359db6fd028bf3cc6e44b27ffe56eb1be57b",
          "sha256": "73ed4ced9dd0d433a6e8a1e48b1406ae0a38155c2f9061ee8cf21f5e9dc30343",
          "sha1": "1f2884ffc19bcb91d904ed12d8b018dd5e120388",
          "md5": "fa44c515a7a2019b52cf5c51c692b7f2"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iossimulatorarm64-61a6ee5-metadata.jar",
          "url": "test-utils-coroutine-iossimulatorarm64-61a6ee5-metadata.jar",
          "size": 261,
          "sha512": "99fc32bf4f9eb36d4ac1ad86e0e2e8a266721b5d828d05ae1615923bf34509f3a27fe7fe018029173c1fdfdfd5171ad453720b9b870aef82c115165d71c64ef7",
          "sha256": "6f4175265c4b8afa79c44c63298861a11d77c82efaddf711105216756ad77a44",
          "sha1": "5ea414bd2e36f4e2a63e7bc586c70c9b56cf2619",
          "md5": "8d88b35edaddcca447533a6d0b28144d"
        }
      ]
    }
  ]
}
