{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/8066bd0/test-utils-ktor-8066bd0.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "8066bd0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-watchosx64-8066bd0.klib",
          "size": 15044,
          "sha512": "f40c8d0937811e2ace0589d2b2cf8aa6846f0f547827a2ff30b82eccea6d5b5381de71ed11e18a13258d4b7756c256a49614b3bcdd15070d25a5e9341a312fcb",
          "sha256": "92aad9ab31b909dad934e1fc085949ac651cdec0cdc40b98bbe134e1e2aa11fa",
          "sha1": "fd6bd39a296f9cfc19c1b1ea5ba165d8bd94d605",
          "md5": "69851541c7a0c862f6218c4a900cc513"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-watchosx64-8066bd0-metadata.jar",
          "url": "test-utils-ktor-watchosx64-8066bd0-metadata.jar",
          "size": 261,
          "sha512": "a1c941db45a4e4756719698b9a6db1c13435338922d8efdc26117026daf3e69d15bf7ac40e869ef6b940e1c910abf115eefa84f51c455dd957af9685e9cff74f",
          "sha256": "d675b9edbd209d4d1e58c106397a3919a6d5c06c4640e311e36db8837ac42fb9",
          "sha1": "e92004bccb375355d587bfc25e061861ed2448d2",
          "md5": "d6d3786931bde8d906c30d244568f289"
        }
      ]
    }
  ]
}
