{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "a2a10c6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-a2a10c6.jar",
          "url": "antibytes-custom-component-a2a10c6.jar",
          "size": 16172,
          "sha512": "b05a1c4ed48743ecec6c612fd9feb3eb59a4c12aef2c114563f2d8a2944af24307b0778a0861b0a9ab98368da05eb4f0f0b48d4368eba5ae015bb9a76414f203",
          "sha256": "797547b7d4f93c94bb063390fbd28964e8fe5b99e2eb40c3dc59b5d1a9fdbc80",
          "sha1": "ac901df1ed33a1d045e78f2327b5072e7d7845d4",
          "md5": "0436ed58b6b0c509cac464eed030494b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-a2a10c6.jar",
          "url": "antibytes-custom-component-a2a10c6.jar",
          "size": 16172,
          "sha512": "b05a1c4ed48743ecec6c612fd9feb3eb59a4c12aef2c114563f2d8a2944af24307b0778a0861b0a9ab98368da05eb4f0f0b48d4368eba5ae015bb9a76414f203",
          "sha256": "797547b7d4f93c94bb063390fbd28964e8fe5b99e2eb40c3dc59b5d1a9fdbc80",
          "sha1": "ac901df1ed33a1d045e78f2327b5072e7d7845d4",
          "md5": "0436ed58b6b0c509cac464eed030494b"
        }
      ]
    }
  ]
}
