{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "c6456b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-c6456b0.jar",
          "url": "antibytes-dependency-c6456b0.jar",
          "size": 71525,
          "sha512": "598904890bff3819a03ab3e0d847d77ca7fd4a2d23595bda771816fd7b30da2176f11f36371d6c204f338e337c032dee1d22cac84c519640ffe7cb7174a33740",
          "sha256": "0ef9382496bf227189a0f2c0447392c4492689ec49557e2137c74f0b16d3bebe",
          "sha1": "af5fe834c71c76d070600ef9f045e08c9faa694a",
          "md5": "b969c577c7143c0ed0afc2996f170946"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-gradle-plugin",
          "version": {
            "requires": "0.17.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.0.4.1"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.44.0"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "c6456b0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-c6456b0.jar",
          "url": "antibytes-dependency-c6456b0.jar",
          "size": 71525,
          "sha512": "598904890bff3819a03ab3e0d847d77ca7fd4a2d23595bda771816fd7b30da2176f11f36371d6c204f338e337c032dee1d22cac84c519640ffe7cb7174a33740",
          "sha256": "0ef9382496bf227189a0f2c0447392c4492689ec49557e2137c74f0b16d3bebe",
          "sha1": "af5fe834c71c76d070600ef9f045e08c9faa694a",
          "md5": "b969c577c7143c0ed0afc2996f170946"
        }
      ]
    }
  ]
}
