{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/eaacea3/test-utils-annotations-eaacea3.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "eaacea3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm-eaacea3.jar",
          "url": "test-utils-annotations-jvm-eaacea3.jar",
          "size": 10872,
          "sha512": "dc9a4d1d2c8893fc55fcc7bde2c71c41b41188b035f82d062417685d72e11a824ca566015842c543aed00e64d5214543c994c2b1542958bf49a25be4f725e8f5",
          "sha256": "883fbe8566ac289b0db7a0d10d17fb8bfbcfb2659bb02a407e11744d97e1c89a",
          "sha1": "6319d309dd6b597d648fc916fea5d779a6f27ea4",
          "md5": "830fb771dc621cd4451209df5d72eb26"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm-eaacea3.jar",
          "url": "test-utils-annotations-jvm-eaacea3.jar",
          "size": 10872,
          "sha512": "dc9a4d1d2c8893fc55fcc7bde2c71c41b41188b035f82d062417685d72e11a824ca566015842c543aed00e64d5214543c994c2b1542958bf49a25be4f725e8f5",
          "sha256": "883fbe8566ac289b0db7a0d10d17fb8bfbcfb2659bb02a407e11744d97e1c89a",
          "sha1": "6319d309dd6b597d648fc916fea5d779a6f27ea4",
          "md5": "830fb771dc621cd4451209df5d72eb26"
        }
      ]
    }
  ]
}
