{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "7bd994e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-metadata-7bd994e-all.jar",
          "url": "test-utils-7bd994e-all.jar",
          "size": 9830,
          "sha512": "2c8c0198f42176d73d66b7c8ec703b491202c7c5dd7d660f7af5509e6760e000c6ae13c3b814d903eea038d54fffb3fec3f7099f78258d32b01f8f9f32ea9355",
          "sha256": "713e584e2dd7a02af89aae084f12dd54b734fce85653378a3525a766cea53679",
          "sha1": "e60477c31737f54c2bd7aa30838cc533f1c28682",
          "md5": "35ed6510950d5f9e0f2e524969759237"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-7bd994e.jar",
          "url": "test-utils-7bd994e.jar",
          "size": 3985,
          "sha512": "265ea03df943b83d501e3b95682f232754ef7a4ed1ca1c61c831232c854e0559c640af3f6188e5c32930c025ec33d8df9c8e34765153278ffba0b08a3db144c3",
          "sha256": "aec89bde5e1f7cfa6477b04cec2c831e07bc82318b54fb29f64af03ccf07c9ae",
          "sha1": "0362347ce9c74637432f646bbd7bfed9c4522a36",
          "md5": "bd229ebff48f7d0a9d0b52880c032f73"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/7bd994e/test-utils-android-7bd994e.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "7bd994e"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/7bd994e/test-utils-android-7bd994e.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "7bd994e"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosarm64/7bd994e/test-utils-iosarm64-7bd994e.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosarm64",
        "version": "7bd994e"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosarm64/7bd994e/test-utils-iosarm64-7bd994e.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosarm64",
        "version": "7bd994e"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iossimulatorarm64/7bd994e/test-utils-iossimulatorarm64-7bd994e.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iossimulatorarm64",
        "version": "7bd994e"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iossimulatorarm64/7bd994e/test-utils-iossimulatorarm64-7bd994e.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iossimulatorarm64",
        "version": "7bd994e"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosx64/7bd994e/test-utils-iosx64-7bd994e.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosx64",
        "version": "7bd994e"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosx64/7bd994e/test-utils-iosx64-7bd994e.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosx64",
        "version": "7bd994e"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-js/7bd994e/test-utils-js-7bd994e.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-js",
        "version": "7bd994e"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-js/7bd994e/test-utils-js-7bd994e.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-js",
        "version": "7bd994e"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/7bd994e/test-utils-jvm-7bd994e.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "7bd994e"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/7bd994e/test-utils-jvm-7bd994e.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "7bd994e"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-linuxx64/7bd994e/test-utils-linuxx64-7bd994e.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-linuxx64",
        "version": "7bd994e"
      }
    }
  ]
}
