{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "71dd209",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-71dd209.jar",
          "url": "antibytes-configuration-71dd209.jar",
          "size": 59287,
          "sha512": "4da172c122f7eda2e629843592ad42788c99c28da31b342880252ead3a29c8beb225d6ac70731ff63a4e6530fdea134a243daa4c07711f91b9e1cefeedef597b",
          "sha256": "04bb27e1726dadca74d70c537dfcd6825e227854ab4871f9e1868f3bdf70af79",
          "sha1": "62ce721636fbcb70e6b64d175b543fda071fd124",
          "md5": "76fbefbb68993451a5eceb409782f462"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "71dd209"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-71dd209.jar",
          "url": "antibytes-configuration-71dd209.jar",
          "size": 59287,
          "sha512": "4da172c122f7eda2e629843592ad42788c99c28da31b342880252ead3a29c8beb225d6ac70731ff63a4e6530fdea134a243daa4c07711f91b9e1cefeedef597b",
          "sha256": "04bb27e1726dadca74d70c537dfcd6825e227854ab4871f9e1868f3bdf70af79",
          "sha1": "62ce721636fbcb70e6b64d175b543fda071fd124",
          "md5": "76fbefbb68993451a5eceb409782f462"
        }
      ]
    }
  ]
}
