{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "6b92a3b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-6b92a3b.jar",
          "url": "antibytes-android-application-configuration-6b92a3b.jar",
          "size": 56574,
          "sha512": "1f89a6e974aa6a18487965d6afffdebefd06936f67b7d7c46a143b56a665a9af8c36c2285996e72141a87fd9864387c102b04773daa6cd576dff1b8ff53915d5",
          "sha256": "0064858f29942bd83dd9c64d77cfccfe50f9fa86a681f04ed60c0e163b2c385d",
          "sha1": "ac40fd5efecc0cd30b91fc4ba18830695e6a8a99",
          "md5": "3eeae0187d1fd2014230a347051d6f7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "6b92a3b"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-6b92a3b.jar",
          "url": "antibytes-android-application-configuration-6b92a3b.jar",
          "size": 56574,
          "sha512": "1f89a6e974aa6a18487965d6afffdebefd06936f67b7d7c46a143b56a665a9af8c36c2285996e72141a87fd9864387c102b04773daa6cd576dff1b8ff53915d5",
          "sha256": "0064858f29942bd83dd9c64d77cfccfe50f9fa86a681f04ed60c0e163b2c385d",
          "sha1": "ac40fd5efecc0cd30b91fc4ba18830695e6a8a99",
          "md5": "3eeae0187d1fd2014230a347051d6f7d"
        }
      ]
    }
  ]
}
