{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-SNAPSHOT/ktx-datetime-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-tvosx64-0.4.0-SNAPSHOT.klib",
          "size": 36944,
          "sha512": "8081e8d15812d480a5febdaa6d90c3500cf0c89745d16a0a90680c897e053319b1eaff32a5b85a0d99ca88e5a8c0d0966678353bdd6122129ed6b7db3d609876",
          "sha256": "c8ed71ca5b1c0adc005594f0b1b65df0e036043ce4a9f450179971249f3ef602",
          "sha1": "650bd0cb716ad0c3b87ed756cdacc8b767f55f48",
          "md5": "d1691dbb9cb7e20760552d51c163e2ca"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktx-datetime-tvosx64-0.4.0-SNAPSHOT-sources.jar",
          "url": "ktx-datetime-tvosx64-0.4.0-SNAPSHOT-sources.jar",
          "size": 16088,
          "sha512": "2fd1093b4f66fb86460e0e5fc46d3c82d6d649e51f6fa67d86c49ee2405d528475c31f450f406b1a2be2e691d1f52d71036cf571bf342b1c7bbfdb18aacafc58",
          "sha256": "ddfeada0f92e68af51cd57f3ddcf63f5349e6ad12c9b5c93c0313015c5cc3e8e",
          "sha1": "e3f7b5b02498f31f31ff09a28221f9502399b3a2",
          "md5": "b2ce74b02e7d0b4b4cf6bb0c3c064bd4"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-tvosx64-0.4.0-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-tvosx64-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b512fbd4e3ef4e61d867e913586fb918e60bcfa0e159ae15e8d8167572983ca76c6a758255bb7819d1607066613140ac276ea26fbb6f0a7d82803ce5f062e83e",
          "sha256": "1421c06035f5e64fa194405166bde4a17ae78c2817d1c3b7977ac2124c34413b",
          "sha1": "fdb6cd5326a575f8833038f15f01c2541d531a0c",
          "md5": "62b5c9b275b3dfdb7584e997b86a372d"
        }
      ]
    }
  ]
}
