{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/573821d/kmock-573821d.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "573821d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-573821d.jar",
          "url": "kmock-jvm-573821d.jar",
          "size": 269592,
          "sha512": "450fc816e35a51587df9276df1af04628b264556b0ea8863f5f31d0e0a192359c816807e0f3ec2897fcf7dec72eecf5a399f4dcf5bd1816c33c23a2bed31b542",
          "sha256": "18ddc6eb05a514179e8b922cd49aa759e112b96f782fd2497dbdf95c1f197055",
          "sha1": "e2ef41acd456f697cfd65bc8bfafbc68bc93006a",
          "md5": "001bff87ed7038de4cd253edafcbc0c1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-573821d.jar",
          "url": "kmock-jvm-573821d.jar",
          "size": 269592,
          "sha512": "450fc816e35a51587df9276df1af04628b264556b0ea8863f5f31d0e0a192359c816807e0f3ec2897fcf7dec72eecf5a399f4dcf5bd1816c33c23a2bed31b542",
          "sha256": "18ddc6eb05a514179e8b922cd49aa759e112b96f782fd2497dbdf95c1f197055",
          "sha1": "e2ef41acd456f697cfd65bc8bfafbc68bc93006a",
          "md5": "001bff87ed7038de4cd253edafcbc0c1"
        }
      ]
    }
  ]
}
