{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "d81ce55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-d81ce55.jar",
          "url": "antibytes-configuration-d81ce55.jar",
          "size": 49663,
          "sha512": "fec0a8f6d9f9835860a0b26bf521046ae4b0a8a1e9abbf0ab247a6455fabeb81542803d5b3c57688010d1f4455c8736e8521fe397217b50fb41227a4655e12fe",
          "sha256": "330dbec32820bb0d5f626eee32299b7f3f2b3b44311e05732a9795c0a118838e",
          "sha1": "1bf240a8bf597e2ac240de9b2200ec4fb2e93d7c",
          "md5": "e5c538aec11910acfd79d5b702c1beda"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "d81ce55"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-d81ce55.jar",
          "url": "antibytes-configuration-d81ce55.jar",
          "size": 49663,
          "sha512": "fec0a8f6d9f9835860a0b26bf521046ae4b0a8a1e9abbf0ab247a6455fabeb81542803d5b3c57688010d1f4455c8736e8521fe397217b50fb41227a4655e12fe",
          "sha256": "330dbec32820bb0d5f626eee32299b7f3f2b3b44311e05732a9795c0a118838e",
          "sha1": "1bf240a8bf597e2ac240de9b2200ec4fb2e93d7c",
          "md5": "e5c538aec11910acfd79d5b702c1beda"
        }
      ]
    }
  ]
}
