{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "9318316",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-9318316.toml",
          "url": "antibytes-dependency-catalog-9318316.toml",
          "size": 231595,
          "sha512": "1cf920b45a9b089665a5f3ff55b49c3aaefa0c4953cd023ae0fab8a02a847d8fae447a8b2833de76b42b89d6ce8e018204dcb5513d64f45376b13bd9f77134c9",
          "sha256": "70c0103495b6c57c2cc64307edc394a7bd17c58b9c187ddc6546b86f3038ee5c",
          "sha1": "8f613d2f771337a797b95a8c0c0dbcd7db63e241",
          "md5": "5a6c3c05d75cadd7d2f31d812677bbab"
        }
      ]
    }
  ]
}
