{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "32b33c8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-32b33c8.jar",
          "url": "antibytes-coverage-32b33c8.jar",
          "size": 128528,
          "sha512": "2d3a40cbb2e131b8359e449ed1c38f2eaa3135fef7257436eb042386f27ba05d90b04b3c4146d28b8c5a04754a1fdaa4e9b14701c6ca9134133dc5392d3c7ae6",
          "sha256": "2b83863954f9affb21f48552b7cb4faa0afac44ea38fbe4a63f2bb46f582e437",
          "sha1": "77b0a5b670ca4773010b335c4aa3df531f18dd68",
          "md5": "d0eb8ce0240d03b2c438241b8caaf452"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "32b33c8"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-32b33c8.jar",
          "url": "antibytes-coverage-32b33c8.jar",
          "size": 128528,
          "sha512": "2d3a40cbb2e131b8359e449ed1c38f2eaa3135fef7257436eb042386f27ba05d90b04b3c4146d28b8c5a04754a1fdaa4e9b14701c6ca9134133dc5392d3c7ae6",
          "sha256": "2b83863954f9affb21f48552b7cb4faa0afac44ea38fbe4a63f2bb46f582e437",
          "sha1": "77b0a5b670ca4773010b335c4aa3df531f18dd68",
          "md5": "d0eb8ce0240d03b2c438241b8caaf452"
        }
      ]
    }
  ]
}
