{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "51860c6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-51860c6.jar",
          "url": "antibytes-dependency-helper-51860c6.jar",
          "size": 69703,
          "sha512": "65ac66b3e016b2ad59befc3162aa2631484bc26c7565d7c43e558fe39835cfa2860e029fdc513a28245b47bc4d42b1de15b60f608510c230034ff101a6a99663",
          "sha256": "ce2593afdf6fb638f8a64b208f7d63494b9e9481a8d37e7c5e44277f7067a98c",
          "sha1": "004747daa51d76ba90cd3a9e81332e6f72a4bead",
          "md5": "d8e40852485ae6c7e24e87ba41af64a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.51.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "9.0.9"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "51860c6"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-51860c6.jar",
          "url": "antibytes-dependency-helper-51860c6.jar",
          "size": 69703,
          "sha512": "65ac66b3e016b2ad59befc3162aa2631484bc26c7565d7c43e558fe39835cfa2860e029fdc513a28245b47bc4d42b1de15b60f608510c230034ff101a6a99663",
          "sha256": "ce2593afdf6fb638f8a64b208f7d63494b9e9481a8d37e7c5e44277f7067a98c",
          "sha1": "004747daa51d76ba90cd3a9e81332e6f72a4bead",
          "md5": "d8e40852485ae6c7e24e87ba41af64a9"
        }
      ]
    }
  ]
}
