{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "4827895",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-4827895.jar",
          "url": "antibytes-versioning-4827895.jar",
          "size": 21893,
          "sha512": "973cfc8ecafdadc7898ae8c649fb18565af9d3c016ca80d9b4db3371676a7738343952619a8819e9cb6680b366d28031e907cf2bfebe8cada76eb767a0bee199",
          "sha256": "052a562dba620dcec19c516555d962be2dbb45aadbdf03256d78780afa238df1",
          "sha1": "924fccf1082a2fc03d0057f71d65ec1f6f7ccbad",
          "md5": "21174f9e616219ac434be2933c604dc9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-4827895.jar",
          "url": "antibytes-versioning-4827895.jar",
          "size": 21893,
          "sha512": "973cfc8ecafdadc7898ae8c649fb18565af9d3c016ca80d9b4db3371676a7738343952619a8819e9cb6680b366d28031e907cf2bfebe8cada76eb767a0bee199",
          "sha256": "052a562dba620dcec19c516555d962be2dbb45aadbdf03256d78780afa238df1",
          "sha1": "924fccf1082a2fc03d0057f71d65ec1f6f7ccbad",
          "md5": "21174f9e616219ac434be2933c604dc9"
        }
      ]
    }
  ]
}
