{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/fc88d6a/test-utils-annotations-junit4-fc88d6a.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "fc88d6a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-tvossimulatorarm64-fc88d6a.klib",
          "size": 11449,
          "sha512": "30fe12f3fcb58af061a1a7c12052c83b3d482b516a724b30e968bde89483cd992ebec186c9de347012c4a17244d4a107a57c7d5b5d1ab2f75dfe63eda253f531",
          "sha256": "6f47b288262026fd1e541035f53831fde90cd0b1f33f9807576bae4ad4e8e733",
          "sha1": "8465619d9b978d601c52a26c003ca17bbbefea5f",
          "md5": "8661f556610006ea77f189ca46dbd25e"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-tvossimulatorarm64-fc88d6a-metadata.jar",
          "url": "test-utils-annotations-junit4-tvossimulatorarm64-fc88d6a-metadata.jar",
          "size": 261,
          "sha512": "bc50b4456c2d4a8d271f26d5ddedd03acd460da32f3fc51b8a870cda8cacede88e8502098f8b779fc41f0324ff90c3c2e6e1611a898d57ec4537b0a4ffd17eb7",
          "sha256": "2b5ef93f77d91bd8e9e74d82b80d1c31ce06e24d5e69289fa2ff0f16bef41768",
          "sha1": "7ac275f1825fec0d516689dfa52c4d81d6bc0f01",
          "md5": "f947863aa524e8237bada7ff3e0114a1"
        }
      ]
    }
  ]
}
