{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/4f11117/test-utils-coroutine-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-4f11117.klib",
          "url": "test-utils-coroutine-js-4f11117.klib",
          "size": 10189,
          "sha512": "f6da82b97f7956bb3b4c1f7c73a6c59fe9545a977de2114371d881a69f17aa2d90f91bc574b7cbb15269d87664b0e3679094d4b3878174c2e3916691abb10e1c",
          "sha256": "e3acbecb2c1a11aed25993b321f793b624993220964478e4d6601cd09829c46c",
          "sha1": "3af5a4b5f2f500959742d500cda237b9fb861147",
          "md5": "903101886f8ae50dbfb22150df7c9ea3"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-4f11117.klib",
          "url": "test-utils-coroutine-js-4f11117.klib",
          "size": 10189,
          "sha512": "f6da82b97f7956bb3b4c1f7c73a6c59fe9545a977de2114371d881a69f17aa2d90f91bc574b7cbb15269d87664b0e3679094d4b3878174c2e3916691abb10e1c",
          "sha256": "e3acbecb2c1a11aed25993b321f793b624993220964478e4d6601cd09829c46c",
          "sha1": "3af5a4b5f2f500959742d500cda237b9fb861147",
          "md5": "903101886f8ae50dbfb22150df7c9ea3"
        }
      ]
    }
  ]
}
