{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/231a33c/test-utils-annotations-junit5-231a33c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "231a33c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-jvm-231a33c.jar",
          "url": "test-utils-annotations-junit5-jvm-231a33c.jar",
          "size": 4271,
          "sha512": "626e522701ed3a8e0cbafc33b72b7538c401860aa8257b538de0e65ceaddc025aaec1e5b8f9e9d03038c1c984bad35222eee26ccc8df7d1435b13a35181874c0",
          "sha256": "e03af9b8e9f5ead1bd72f9f2d2d79d1c41b26af4f7a873fddde6991eeebc7d3a",
          "sha1": "197877bfd83ec92bd0f732a0137847a57bf5825a",
          "md5": "9db0611e9e490daf963692e0120b92c1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit5",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-jvm-231a33c.jar",
          "url": "test-utils-annotations-junit5-jvm-231a33c.jar",
          "size": 4271,
          "sha512": "626e522701ed3a8e0cbafc33b72b7538c401860aa8257b538de0e65ceaddc025aaec1e5b8f9e9d03038c1c984bad35222eee26ccc8df7d1435b13a35181874c0",
          "sha256": "e03af9b8e9f5ead1bd72f9f2d2d79d1c41b26af4f7a873fddde6991eeebc7d3a",
          "sha1": "197877bfd83ec92bd0f732a0137847a57bf5825a",
          "md5": "9db0611e9e490daf963692e0120b92c1"
        }
      ]
    }
  ]
}
