{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "51860c6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-51860c6.jar",
          "url": "antibytes-custom-component-51860c6.jar",
          "size": 16534,
          "sha512": "8761abb501ff694dfd74d1d412b05d0f4b9190b2659316356565cf26688921b634836260f84b7e84fdc85b2929ac7b347fb130b8f70cb46bf58d74673f7ac8ed",
          "sha256": "6a5da2b9f21bacb34c07386789b616d632c2035f15b51a538961801a57212fb6",
          "sha1": "275c97367bfab39608493865a6d0177fb7f89224",
          "md5": "69251f42364ba20c243e389b2650d113"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-51860c6.jar",
          "url": "antibytes-custom-component-51860c6.jar",
          "size": 16534,
          "sha512": "8761abb501ff694dfd74d1d412b05d0f4b9190b2659316356565cf26688921b634836260f84b7e84fdc85b2929ac7b347fb130b8f70cb46bf58d74673f7ac8ed",
          "sha256": "6a5da2b9f21bacb34c07386789b616d632c2035f15b51a538961801a57212fb6",
          "sha1": "275c97367bfab39608493865a6d0177fb7f89224",
          "md5": "69251f42364ba20c243e389b2650d113"
        }
      ]
    }
  ]
}
