{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.2.2-SNAPSHOT.jar",
          "url": "kmock-processor-0.2.2-SNAPSHOT.jar",
          "size": 382796,
          "sha512": "eda7e36bc2fefd53809fdd8a9da17fcdb1229c6c2565afe5d6bec95a7a0c50c032315f4102df37182fec89e1f350e2d6d4ba09788d731a4232439895eed628f2",
          "sha256": "c889d6c4cfde44256de31f32068dad3377d176253f4ed00de83763347fd82fa7",
          "sha1": "fcca77a54e6753c946f37bef5646f4d896c3fc1c",
          "md5": "11bfe76cc0684124427a557e3e0dcfc3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.21-1.0.6"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.2.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.2.2-SNAPSHOT.jar",
          "url": "kmock-processor-0.2.2-SNAPSHOT.jar",
          "size": 382796,
          "sha512": "eda7e36bc2fefd53809fdd8a9da17fcdb1229c6c2565afe5d6bec95a7a0c50c032315f4102df37182fec89e1f350e2d6d4ba09788d731a4232439895eed628f2",
          "sha256": "c889d6c4cfde44256de31f32068dad3377d176253f4ed00de83763347fd82fa7",
          "sha1": "fcca77a54e6753c946f37bef5646f4d896c3fc1c",
          "md5": "11bfe76cc0684124427a557e3e0dcfc3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-processor-0.2.2-SNAPSHOT-javadoc.jar",
          "url": "kmock-processor-0.2.2-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "ca816e8b23d13223d3a38edffc69582ab042eea33ef8b1828d88f8708493414fe4ca5fff60111ccc1c8624cc0fbbefad7d575e32dc129398afa90d99fb76427a",
          "sha256": "33fd593aab08271f805236307baebffe4984b953342b67073b0c4c4e06000a4b",
          "sha1": "131d912c18a153d06aaf2269ec90ecd202104635",
          "md5": "ef4023ec9d368660c1ab0c113b14c3b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-processor-0.2.2-SNAPSHOT-sources.jar",
          "url": "kmock-processor-0.2.2-SNAPSHOT-sources.jar",
          "size": 80113,
          "sha512": "8aa26755a914b7c00beb8c0b884dd4cf2d9cfc1e25a8c95350e6a1fd4ebb4428c5a5b789f1accf900a0051012d2b9622e6c074b8e85eafd36bdb86d52d9ad04c",
          "sha256": "9a95c773431d53debb486bd64a11f9c9a1d71a6f10bef3ed469c32f4dc55a5bc",
          "sha1": "2d503edd576d6530a50fdb7442674c3571b4bd4b",
          "md5": "3bbf9face555ec4f93e0a41158bcc4d1"
        }
      ]
    }
  ]
}
