{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "f2c3d06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-f2c3d06.jar",
          "url": "antibytes-versioning-f2c3d06.jar",
          "size": 21893,
          "sha512": "2df6f40ed5b8f445c9c5df2b268f3072867c99f8be99e2962b8dcff699107b4427e1c716d37a6e778a6d02a668e55530097d95181ec18997d175c1edfa704a1d",
          "sha256": "bca52686bce144dc525b8f77678a70bcfe9e43ff5c69161c3dd6cc2e077ccd17",
          "sha1": "8cebf2c0e32238f67406749416b4dc23e88bd330",
          "md5": "6e151b6cae31c6532d2f666ecd663456"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-f2c3d06.jar",
          "url": "antibytes-versioning-f2c3d06.jar",
          "size": 21893,
          "sha512": "2df6f40ed5b8f445c9c5df2b268f3072867c99f8be99e2962b8dcff699107b4427e1c716d37a6e778a6d02a668e55530097d95181ec18997d175c1edfa704a1d",
          "sha256": "bca52686bce144dc525b8f77678a70bcfe9e43ff5c69161c3dd6cc2e077ccd17",
          "sha1": "8cebf2c0e32238f67406749416b4dc23e88bd330",
          "md5": "6e151b6cae31c6532d2f666ecd663456"
        }
      ]
    }
  ]
}
