{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "967d356",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-967d356.jar",
          "url": "antibytes-gradle-utils-967d356.jar",
          "size": 9580,
          "sha512": "a3ab2660986bc9a307948fc058ba7b8bc1d4e49cfde109285645792ddabed8d188dd462c3945642d5475b265f318ba02a0a023ff6541d46da289ca223a943c3d",
          "sha256": "f6e768e3e1e8e7d2c52b3bdac857d6c9653d6140c143501bca9650c23140c725",
          "sha1": "900f674f1d87e19beb3a675d0d5dea24c2f15c4c",
          "md5": "039e6cbf3695636d2c215e5ef0729289"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-967d356.jar",
          "url": "antibytes-gradle-utils-967d356.jar",
          "size": 9580,
          "sha512": "a3ab2660986bc9a307948fc058ba7b8bc1d4e49cfde109285645792ddabed8d188dd462c3945642d5475b265f318ba02a0a023ff6541d46da289ca223a943c3d",
          "sha256": "f6e768e3e1e8e7d2c52b3bdac857d6c9653d6140c143501bca9650c23140c725",
          "sha1": "900f674f1d87e19beb3a675d0d5dea24c2f15c4c",
          "md5": "039e6cbf3695636d2c215e5ef0729289"
        }
      ]
    }
  ]
}
