{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/86ec4d6/test-utils-resourceloader-86ec4d6.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "86ec4d6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-watchossimulatorarm64-86ec4d6.klib",
          "size": 14333,
          "sha512": "5d1ce790cdde49a196617e5fe7974fbee0c981758d8cf26341d66bd738e4047649138bf4e7b94c90aec40747a058b83bf296a898c3bb104e4249ba6e2461f166",
          "sha256": "cc5189d571afc1447eb7190eb28761b5d4defcd6a4658bf4b79c32a652a172bf",
          "sha1": "fb4644370e71036318d39a8b1d264c11147e167c",
          "md5": "1c9e787cf0c30835ca9f285727adf0e2"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-watchossimulatorarm64-86ec4d6-sources.jar",
          "url": "test-utils-resourceloader-watchossimulatorarm64-86ec4d6-sources.jar",
          "size": 4241,
          "sha512": "284172150658cfb9dae6c2bb10bbd5de382a8193d892540a4de60322cb16b05740a160fc4f827c092194ab0e3983419cb75c9d52eee7cf9cf1ac22b32a8f7d7b",
          "sha256": "28c33fb0c5429879a7515dfb1ee5400a354f30a17cda3a32c13cec2fd413b7da",
          "sha1": "e6bc305f912fc8fc1e733215728491f83d594bd4",
          "md5": "935272aedc89d60202c3ad87a167495a"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-watchossimulatorarm64-86ec4d6-metadata.jar",
          "url": "test-utils-resourceloader-watchossimulatorarm64-86ec4d6-metadata.jar",
          "size": 261,
          "sha512": "dad3f0a91bb8e0fbfdd99b19c0a11f4267ea0e3a3e89fd22817a5577d0f1000c81a8a8d0b25a3f56c20637ec3f9658de94df0cf23a0c16fe8a39bb3afaf14667",
          "sha256": "8a0f3858f490db8193272f75d01acabfc81e7ea03a4f4524f6e9d02b0a24ef25",
          "sha1": "1657821ef4cdf75f6c6315fae55f3d0d1e96f131",
          "md5": "c96e9d04909e6a445978ccb4d5b16224"
        }
      ]
    }
  ]
}
