{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "b1373c3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-b1373c3.jar",
          "url": "antibytes-versioning-b1373c3.jar",
          "size": 21893,
          "sha512": "f199c2f9addfbd981b4736b5b921fe1d07d70769724a55e806a83c7660ef55d5855d7cdf84a1307e47016d0f942eaa945512f80b7a2e60b64fdf02c27af0cec4",
          "sha256": "88d92954c48dff3f2b600ea3f6170fc8ad8d5eef8a1d734ec0e8df8ae0e1cea4",
          "sha1": "366a7849e16d3e3cfbc697440a6d0a846e2ba3dc",
          "md5": "e6a397895c8607d5cfc31f166ffb4238"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-b1373c3.jar",
          "url": "antibytes-versioning-b1373c3.jar",
          "size": 21893,
          "sha512": "f199c2f9addfbd981b4736b5b921fe1d07d70769724a55e806a83c7660ef55d5855d7cdf84a1307e47016d0f942eaa945512f80b7a2e60b64fdf02c27af0cec4",
          "sha256": "88d92954c48dff3f2b600ea3f6170fc8ad8d5eef8a1d734ec0e8df8ae0e1cea4",
          "sha1": "366a7849e16d3e3cfbc697440a6d0a846e2ba3dc",
          "md5": "e6a397895c8607d5cfc31f166ffb4238"
        }
      ]
    }
  ]
}
