{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-SNAPSHOT/ktx-datetime-0.3.1-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktx-datetime-jvm-0.3.1-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.3.1-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "604627d50ca2050c0c6ea337760f5023b8b7f5bd27264592c43b05a041eb64e3ade5e72be5b9f2d368b195eef1930495485ba5aabf7af3e44ee156943b72a434",
          "sha256": "12ad2906c77d0b3a3961157fef440c49e7f8c9de5ab58b11e1b07aecd63c6731",
          "sha1": "22867202127728fd5caacb8107936fedbfae2e82",
          "md5": "6cf667bf22b86320a59be1aaa1c4ce2b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.3.1-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.3.1-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "604627d50ca2050c0c6ea337760f5023b8b7f5bd27264592c43b05a041eb64e3ade5e72be5b9f2d368b195eef1930495485ba5aabf7af3e44ee156943b72a434",
          "sha256": "12ad2906c77d0b3a3961157fef440c49e7f8c9de5ab58b11e1b07aecd63c6731",
          "sha1": "22867202127728fd5caacb8107936fedbfae2e82",
          "md5": "6cf667bf22b86320a59be1aaa1c4ce2b"
        }
      ]
    }
  ]
}
