{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "ae101dc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-ae101dc.jar",
          "url": "antibytes-gradle-test-utils-ae101dc.jar",
          "size": 17888,
          "sha512": "2840955cc7a11f8659d58c0b638f0ceed1a4f496330357aa08b95a88b1cb79fdd694a71ee47670f022944e4ae49881ebf29b779c3c23726f3c6402f06a80da64",
          "sha256": "ddeaf1b73e414ad9ac2539d3655fb46efd48c2018f76f50c3cb44e7dd9377919",
          "sha1": "589cb48329915c68434f38ea610260ef05f5871f",
          "md5": "a9bc4d6ba908f2757ec2f42d1ad1fafb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-ae101dc.jar",
          "url": "antibytes-gradle-test-utils-ae101dc.jar",
          "size": 17888,
          "sha512": "2840955cc7a11f8659d58c0b638f0ceed1a4f496330357aa08b95a88b1cb79fdd694a71ee47670f022944e4ae49881ebf29b779c3c23726f3c6402f06a80da64",
          "sha256": "ddeaf1b73e414ad9ac2539d3655fb46efd48c2018f76f50c3cb44e7dd9377919",
          "sha1": "589cb48329915c68434f38ea610260ef05f5871f",
          "md5": "a9bc4d6ba908f2757ec2f42d1ad1fafb"
        }
      ]
    }
  ]
}
