{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/f163e11/test-utils-f163e11.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "f163e11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-f163e11.klib",
          "url": "test-utils-js-f163e11.klib",
          "size": 12083,
          "sha512": "d64ff935e47330f584799958acc5683f58fa7271cbd82f98711482fa249cbf017a1aeb9f7bdde1100a1fec224818b57221981f17ccd37eb61b97262e09589083",
          "sha256": "687b300c32555e74c1bf8532ea241fabb5f2ce35ce6140352dcc874e9d9b7ef9",
          "sha1": "86fa776576c2250e0b3834256c4133760f673514",
          "md5": "9ac0a98a3fd9e38b99c1665b5eb53a00"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-f163e11.klib",
          "url": "test-utils-js-f163e11.klib",
          "size": 12083,
          "sha512": "d64ff935e47330f584799958acc5683f58fa7271cbd82f98711482fa249cbf017a1aeb9f7bdde1100a1fec224818b57221981f17ccd37eb61b97262e09589083",
          "sha256": "687b300c32555e74c1bf8532ea241fabb5f2ce35ce6140352dcc874e9d9b7ef9",
          "sha1": "86fa776576c2250e0b3834256c4133760f673514",
          "md5": "9ac0a98a3fd9e38b99c1665b5eb53a00"
        }
      ]
    }
  ]
}
