{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/dbba7bb/test-utils-coroutine-dbba7bb.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "dbba7bb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-dbba7bb.jar",
          "url": "test-utils-coroutine-jvm-dbba7bb.jar",
          "size": 11975,
          "sha512": "b11377297cbf121443e27b373ef400e6d3c3679211423a4ebf90836613f7fbbe963c33bdb68e3c59bd7b0490204014f33667336643eb8040d21205178343519d",
          "sha256": "28141e1ad6f2fab15abc8f83ba293aadcf9c24dc5dc03d7c3e6b0d988f008de5",
          "sha1": "2e188d53fbbc18732fae0a912146b42abc4dbcbe",
          "md5": "e38c712cad1b9ccb261c733b05469a83"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-dbba7bb.jar",
          "url": "test-utils-coroutine-jvm-dbba7bb.jar",
          "size": 11975,
          "sha512": "b11377297cbf121443e27b373ef400e6d3c3679211423a4ebf90836613f7fbbe963c33bdb68e3c59bd7b0490204014f33667336643eb8040d21205178343519d",
          "sha256": "28141e1ad6f2fab15abc8f83ba293aadcf9c24dc5dc03d7c3e6b0d988f008de5",
          "sha1": "2e188d53fbbc18732fae0a912146b42abc4dbcbe",
          "md5": "e38c712cad1b9ccb261c733b05469a83"
        }
      ]
    }
  ]
}
