{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-c9500aecac-SNAPSHOT/kmock-0.1.1-c9500aecac-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-c9500aecac-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-c9500aecac-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-c9500aecac-SNAPSHOT.klib",
          "size": 209372,
          "sha512": "59f53a8326db4ed9447a7e84f30d4ca6966babc726309a4f55995f4d97ed980625ac116ac9396c41f380f5b4014e0949f6af881fbeebc4249ed96327753ded1f",
          "sha256": "f78662d1b1761d71fdc0c2a5396f428964248c0aa793d8bf385993a32da8f1e6",
          "sha1": "0a5844d6dd67d0cbb06b7a30b8f32b320cf10beb",
          "md5": "efe5d7dc6c7adb3046cc23c0fac5c4a0"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-c9500aecac-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-c9500aecac-SNAPSHOT.klib",
          "size": 209372,
          "sha512": "59f53a8326db4ed9447a7e84f30d4ca6966babc726309a4f55995f4d97ed980625ac116ac9396c41f380f5b4014e0949f6af881fbeebc4249ed96327753ded1f",
          "sha256": "f78662d1b1761d71fdc0c2a5396f428964248c0aa793d8bf385993a32da8f1e6",
          "sha1": "0a5844d6dd67d0cbb06b7a30b8f32b320cf10beb",
          "md5": "efe5d7dc6c7adb3046cc23c0fac5c4a0"
        }
      ]
    }
  ]
}
