{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "c6456b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-c6456b0.jar",
          "url": "antibytes-gradle-test-utils-c6456b0.jar",
          "size": 15106,
          "sha512": "bf7d1d2d465de0f215dcb9cf0eb014f076a863026ffc067f2ccf157d2f91834a92a7312cf9bf169042c1bfe912dfffe21b557f4bf0f0b5eb81accf80f43ef5bd",
          "sha256": "5f62e3f4c27c8586772146c9c0dd878c75b435140147333109305107e26ea686",
          "sha1": "f7e26ef253e985c548c98f5267f15c4df12a0592",
          "md5": "0bfe3fffd1308233816f056c535aab00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.3"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-c6456b0.jar",
          "url": "antibytes-gradle-test-utils-c6456b0.jar",
          "size": 15106,
          "sha512": "bf7d1d2d465de0f215dcb9cf0eb014f076a863026ffc067f2ccf157d2f91834a92a7312cf9bf169042c1bfe912dfffe21b557f4bf0f0b5eb81accf80f43ef5bd",
          "sha256": "5f62e3f4c27c8586772146c9c0dd878c75b435140147333109305107e26ea686",
          "sha1": "f7e26ef253e985c548c98f5267f15c4df12a0592",
          "md5": "0bfe3fffd1308233816f056c535aab00"
        }
      ]
    }
  ]
}
