{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-runtime-configuration",
    "version": "314bef8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-314bef8.jar",
          "url": "antibytes-runtime-configuration-314bef8.jar",
          "size": 20356,
          "sha512": "2b65e25809939ff89fd2bf0ce384f68dc2da980d441fc8ab6c645e61c0715bbf851e971e2911ab51b0d584f6aa8444c444ae144b605372a0bda2eb74a2306dbd",
          "sha256": "e9cb46bc4ffbd0b739c5ab4670b45ea292e606ef78357e12616184e843f4070c",
          "sha1": "4ba58cd767a7b1f107b265fb4f376e7e8faba192",
          "md5": "bb7e398d1aed950e6c323ec08a4e41de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "314bef8"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-314bef8.jar",
          "url": "antibytes-runtime-configuration-314bef8.jar",
          "size": 20356,
          "sha512": "2b65e25809939ff89fd2bf0ce384f68dc2da980d441fc8ab6c645e61c0715bbf851e971e2911ab51b0d584f6aa8444c444ae144b605372a0bda2eb74a2306dbd",
          "sha256": "e9cb46bc4ffbd0b739c5ab4670b45ea292e606ef78357e12616184e843f4070c",
          "sha1": "4ba58cd767a7b1f107b265fb4f376e7e8faba192",
          "md5": "bb7e398d1aed950e6c323ec08a4e41de"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-314bef8-javadoc.jar",
          "url": "antibytes-runtime-configuration-314bef8-javadoc.jar",
          "size": 261,
          "sha512": "f3ea410c0ef1eb68222d281586cd2087e608a493cbf3a897103bc3b76c3aef6786ef5c39d939d9d48813809f6d33612c400e7114b62348abdeaf1745416dab67",
          "sha256": "8e285d3efe35256fc1508e63448add0f60f58a1de5f330e2405294c36f7b6a77",
          "sha1": "667a06ca6834108a484895577bc61044af9057a8",
          "md5": "58f228ffa26f54c5b0dffba6fca096de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-314bef8-sources.jar",
          "url": "antibytes-runtime-configuration-314bef8-sources.jar",
          "size": 6059,
          "sha512": "cfeaaa1faec1472c9ed4137227b356ccfb716090aaecd44193b02636acedf6eae755211b5001e6fa13e23c1aec1b750a2276a7db768e8b6ed914f0ccdaa9552d",
          "sha256": "c72ab87fba17d12bd85b899b21fae10b77b2c55e6eb11237686cf27479c2c683",
          "sha1": "a07981139a84caad010872ee35db5518df8e2d86",
          "md5": "e945c2d15b8073a046d91b409d761763"
        }
      ]
    }
  ]
}
