{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "558ae36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-558ae36.jar",
          "url": "antibytes-coverage-558ae36.jar",
          "size": 128596,
          "sha512": "b5a8c7b3463d4c6fb247f6a768fe5e20011ebcde67bcb05b59fadfdc5d1e9c16cdf5c2ffa4498bb25c637d90659373e2c54a430f8f5eddc717ed1883835a7f55",
          "sha256": "ccb99ddacaa211ee0b3a4f75d1105b59369f6e905e7c690840663bcf2288d321",
          "sha1": "3e3ab9d8c8b010d961c0c9f689333d363fa770bb",
          "md5": "9b4c3e68e69c98c9627090194382f25b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "558ae36"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-558ae36.jar",
          "url": "antibytes-coverage-558ae36.jar",
          "size": 128596,
          "sha512": "b5a8c7b3463d4c6fb247f6a768fe5e20011ebcde67bcb05b59fadfdc5d1e9c16cdf5c2ffa4498bb25c637d90659373e2c54a430f8f5eddc717ed1883835a7f55",
          "sha256": "ccb99ddacaa211ee0b3a4f75d1105b59369f6e905e7c690840663bcf2288d321",
          "sha1": "3e3ab9d8c8b010d961c0c9f689333d363fa770bb",
          "md5": "9b4c3e68e69c98c9627090194382f25b"
        }
      ]
    }
  ]
}
