{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/56c4547/test-utils-resourceloader-56c4547.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "56c4547",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-js-56c4547.klib",
          "url": "test-utils-resourceloader-js-56c4547.klib",
          "size": 9574,
          "sha512": "08896006b1f6ca857b335c256bfcab488f7ef760a8ceb08316985d68d52dd62c6c7a3c4905cab022e7b035004552eab8ff9d4413745718e6f74f8aca5439d635",
          "sha256": "611aa2a3767971e6b1f4337691604ad35b95133bf745ac4773746f71744936fa",
          "sha1": "03ef7bce8bf063a1f676d427a5f3af7c47422b2a",
          "md5": "34edf2c146f0144259c1b969f14f7717"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-js-56c4547.klib",
          "url": "test-utils-resourceloader-js-56c4547.klib",
          "size": 9574,
          "sha512": "08896006b1f6ca857b335c256bfcab488f7ef760a8ceb08316985d68d52dd62c6c7a3c4905cab022e7b035004552eab8ff9d4413745718e6f74f8aca5439d635",
          "sha256": "611aa2a3767971e6b1f4337691604ad35b95133bf745ac4773746f71744936fa",
          "sha1": "03ef7bce8bf063a1f676d427a5f3af7c47422b2a",
          "md5": "34edf2c146f0144259c1b969f14f7717"
        }
      ]
    }
  ]
}
