{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "c352c02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-c352c02.jar",
          "url": "antibytes-custom-component-c352c02.jar",
          "size": 16190,
          "sha512": "f5328db73c3ae330d81bfb4ab951db4e1a200464d80d90610f73eeb9c82a4ba581af1a832edb0566cc23eb5cb76d1d37cd92bc2601bae1569576582ec96d2113",
          "sha256": "48fc9b966e74f761f8dc5954a907a1d098f7a3f095b99331be1f8d64e685042c",
          "sha1": "3282dc4390504516a599dd1c8682611968f61650",
          "md5": "d5f4ae589ca1ac8dffbb87c99d179c5f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-c352c02.jar",
          "url": "antibytes-custom-component-c352c02.jar",
          "size": 16190,
          "sha512": "f5328db73c3ae330d81bfb4ab951db4e1a200464d80d90610f73eeb9c82a4ba581af1a832edb0566cc23eb5cb76d1d37cd92bc2601bae1569576582ec96d2113",
          "sha256": "48fc9b966e74f761f8dc5954a907a1d098f7a3f095b99331be1f8d64e685042c",
          "sha1": "3282dc4390504516a599dd1c8682611968f61650",
          "md5": "d5f4ae589ca1ac8dffbb87c99d179c5f"
        }
      ]
    }
  ]
}
