{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/4731843/fixture-4731843.module",
    "group": "tech.antibytes.kotlin-fixtures-kmp",
    "module": "fixture",
    "version": "4731843",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fixture-release.aar",
          "url": "fixture-android-4731843.aar",
          "size": 58748,
          "sha512": "52b6b6bb5fb3f66a091b98fab119c91127293443a537cf244bc1c95243a44eeda896c758384cf2d863c69b2782c27379c1fea362452c04a7cdcbd82f115e6f28",
          "sha256": "8969a9dde65d5e5ad8447ab65080894a6742f23acb7c3f09314ab3ba35e25407",
          "sha1": "da31158671f5ddb828bbdb0a9ce5eecb553ff5ae",
          "md5": "c4e4f9a1c2799fb1e61f42ef78876ab8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fixture-release.aar",
          "url": "fixture-android-4731843.aar",
          "size": 58748,
          "sha512": "52b6b6bb5fb3f66a091b98fab119c91127293443a537cf244bc1c95243a44eeda896c758384cf2d863c69b2782c27379c1fea362452c04a7cdcbd82f115e6f28",
          "sha256": "8969a9dde65d5e5ad8447ab65080894a6742f23acb7c3f09314ab3ba35e25407",
          "sha1": "da31158671f5ddb828bbdb0a9ce5eecb553ff5ae",
          "md5": "c4e4f9a1c2799fb1e61f42ef78876ab8"
        }
      ]
    }
  ]
}
