{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.4.0-SNAPSHOT.jar",
          "url": "core-jvm-0.4.0-SNAPSHOT.jar",
          "size": 273618,
          "sha512": "503546fb1ba21e55387921ffbf2ca87b9d014b168c852bd405a0b1121477088f57e9f7c8396ebbf332d0b617307828bf1e6654ef1b9871e2862dda0ae331a912",
          "sha256": "a8605790a99a8a0d4a555714e9ff341d1404b0e395b9a551e6396c6ee3fde60f",
          "sha1": "a74c0f0d60d1c0f57eb23f6ddf340349595d1bb6",
          "md5": "6c4a081cb0ac4ca1ac740a99c7a2abfb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.4.0-SNAPSHOT.jar",
          "url": "core-jvm-0.4.0-SNAPSHOT.jar",
          "size": 273618,
          "sha512": "503546fb1ba21e55387921ffbf2ca87b9d014b168c852bd405a0b1121477088f57e9f7c8396ebbf332d0b617307828bf1e6654ef1b9871e2862dda0ae331a912",
          "sha256": "a8605790a99a8a0d4a555714e9ff341d1404b0e395b9a551e6396c6ee3fde60f",
          "sha1": "a74c0f0d60d1c0f57eb23f6ddf340349595d1bb6",
          "md5": "6c4a081cb0ac4ca1ac740a99c7a2abfb"
        }
      ]
    }
  ]
}
