{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-SNAPSHOT/ktx-datetime-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "6689380ebc1605aaa87c61ed9265bc52a8e39d956779baf304630125120900de2440a5658129ea266b5a54db0e0a2a297019db9691c3d84b4ecfd0c5284791b3",
          "sha256": "e64ab82f6581ad4bc5893e7d097d1f2053540ed2333c83b661ecd3d14e87e6fa",
          "sha1": "50b5bac439df7daf8942e503b9ac621f66ff66f4",
          "md5": "ca8c6dcf236f7f57bc1ee689c3cbaf59"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "6689380ebc1605aaa87c61ed9265bc52a8e39d956779baf304630125120900de2440a5658129ea266b5a54db0e0a2a297019db9691c3d84b4ecfd0c5284791b3",
          "sha256": "e64ab82f6581ad4bc5893e7d097d1f2053540ed2333c83b661ecd3d14e87e6fa",
          "sha1": "50b5bac439df7daf8942e503b9ac621f66ff66f4",
          "md5": "ca8c6dcf236f7f57bc1ee689c3cbaf59"
        }
      ]
    }
  ]
}
