{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-SNAPSHOT/ktx-datetime-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "4858e90f54a48c765c7d39a607972346df539a5c36c394f5ec700b1fc6646839d92856433d6c7c46a5b102c3bf735861264af951f1d634173198036e2ffafbe8",
          "sha256": "bd01f8ae75a3a7074f244ec332cc5eee09ce950156ac2e98fb9e4987badd2e5b",
          "sha1": "6bdad659723211b8e46a67dc74c642bb28966890",
          "md5": "f42363b4ba7ae5fb39d907e20da12e6e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "4858e90f54a48c765c7d39a607972346df539a5c36c394f5ec700b1fc6646839d92856433d6c7c46a5b102c3bf735861264af951f1d634173198036e2ffafbe8",
          "sha256": "bd01f8ae75a3a7074f244ec332cc5eee09ce950156ac2e98fb9e4987badd2e5b",
          "sha1": "6bdad659723211b8e46a67dc74c642bb28966890",
          "md5": "f42363b4ba7ae5fb39d907e20da12e6e"
        }
      ]
    }
  ]
}
