{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-SNAPSHOT/ktx-datetime-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "cc31c772cdd53e13938ae838e3f17a6af37ffecde9ad5a1cb04dcce3a43c547e2535200ca2aa2e474c12e47a0450bfdcce744382863d8bceadb4bed75b4acde1",
          "sha256": "09c7d89109d8dc3fe3875db3b0fbcaaba1b05fa483d5baa4389485afd89566fe",
          "sha1": "f0f4439bcf2dcabcc6e3370302a707c367470bd4",
          "md5": "0de9ff84ea4c53efa6b2e2208c19adc7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "cc31c772cdd53e13938ae838e3f17a6af37ffecde9ad5a1cb04dcce3a43c547e2535200ca2aa2e474c12e47a0450bfdcce744382863d8bceadb4bed75b4acde1",
          "sha256": "09c7d89109d8dc3fe3875db3b0fbcaaba1b05fa483d5baa4389485afd89566fe",
          "sha1": "f0f4439bcf2dcabcc6e3370302a707c367470bd4",
          "md5": "0de9ff84ea4c53efa6b2e2208c19adc7"
        }
      ]
    }
  ]
}
