{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34698,
          "sha512": "f90fdabded399abff959bc56fe18734435fab071dd8e17302418652612dab8b77de61e9044ec9c9aaa6d8133b4a83c0a784042981ae92eb8137e61438efeb998",
          "sha256": "f3ce8617f1210f14326ffa5970eec5934af868de3eb3ced6dfc2102ee9f6e715",
          "sha1": "e626f1ed875ddb3e1765bf5224e8e9f859a4b5c2",
          "md5": "37f20f44bf68e3477cfe17c046e3305a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34698,
          "sha512": "f90fdabded399abff959bc56fe18734435fab071dd8e17302418652612dab8b77de61e9044ec9c9aaa6d8133b4a83c0a784042981ae92eb8137e61438efeb998",
          "sha256": "f3ce8617f1210f14326ffa5970eec5934af868de3eb3ced6dfc2102ee9f6e715",
          "sha1": "e626f1ed875ddb3e1765bf5224e8e9f859a4b5c2",
          "md5": "37f20f44bf68e3477cfe17c046e3305a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "b0d0b8d8e1798d819f41565d1c4c81f156ac955f60c49502f66f0daf91beba183f667d223a9af0a90eed6443a045b89b2d75869fb0971381fa3d6c40d9a7a9d2",
          "sha256": "eb4f9078d9087d054f3b883e7c23a1f1fef3609be829191a5b29dd6f3c975c92",
          "sha1": "79e08ff07a54465e429d2728229688f1d25e1a33",
          "md5": "7e804cde4b91567ebf62d307c81a1a02"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "size": 9389,
          "sha512": "40330e9cd45b4a80b3ecd7e745a370b1013d89b4ac7b23edd2ee6d9485dc33695a2d65808cb64f7c8ec8525dd2701ca5b86231501746f7a28786f1abbcb9a207",
          "sha256": "35c2ce152cb630e36f8b8a740248ae2b4281ddb9adcf56e4c82571a9b95c9c35",
          "sha1": "70d0ed9ef55bc1c2f594865f63d26d4ba642e146",
          "md5": "64994935efab57907bb584dbc9b0d8eb"
        }
      ]
    }
  ]
}
