{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 47527,
          "sha512": "41d68502f1ab1c82771141149446af60f05680398b3a0811a96ad91d0f1059fb9c783ccaa644e4f2c98f384c03e7533ee996a0e1b52dd889f5ca317c2ade1a32",
          "sha256": "aa23e84f2fb5be8fe84bc026022ac285c77193f6c78d37e91b53e97ba6a9239f",
          "sha1": "66d005077180d401eb7e37c8f51f1a4b0c1b08b0",
          "md5": "0c12d5c4b8ee9517158154107810053a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 47527,
          "sha512": "41d68502f1ab1c82771141149446af60f05680398b3a0811a96ad91d0f1059fb9c783ccaa644e4f2c98f384c03e7533ee996a0e1b52dd889f5ca317c2ade1a32",
          "sha256": "aa23e84f2fb5be8fe84bc026022ac285c77193f6c78d37e91b53e97ba6a9239f",
          "sha1": "66d005077180d401eb7e37c8f51f1a4b0c1b08b0",
          "md5": "0c12d5c4b8ee9517158154107810053a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "de89aae352c6f152fd1148f22c67075dc39657fb4e6852f9e8c71ef365d2444e6ecfe4aca2ba48ca42d64072f6c516fe3f44a5ea46777b3b0e3f4bf24867fac7",
          "sha256": "46320d7500a8d67a5c9b54fee483a2fd5ac11fbfbe634b4a52a5d46450b8bb91",
          "sha1": "d89d7c91ed72868c5e49dd033e8090019a5ab8b0",
          "md5": "036cd2a2ce20d6c4ec57e87b58542d4c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "size": 10917,
          "sha512": "ba32e3ea2f19b3a933cf40e916ef6725b96902dff8b1570ae211e84748a0ed7ee233b42704f75dc2eb10717292f1004f4b9d228895f59c5ce3ebfb0b2b808183",
          "sha256": "1f7a8f52c0e0e604de1daee3c5b12e7b77a4c171ef9d66fb7aca757ca66921d2",
          "sha1": "772beb0b0045e5f297df45341c04a5c047adeee7",
          "md5": "82b4314a76aa6c509b517cfcb318272e"
        }
      ]
    }
  ]
}
