{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34265,
          "sha512": "6ae04d9957685520a736cbe9b75861bae2c955cd9e435ab7fb8ac209bb01324284dd9805312da4d6487f34763cc95c9283b5718120ae1a8bccca61745617753c",
          "sha256": "fac0fc06a3086a4ff9bb9396aef1810da208501fa9e056736fc3d299e1be0cf0",
          "sha1": "c01e3f60d291755e6135b4512e8234128557a203",
          "md5": "35a3efc7f32e7ccf23355b457de411f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34265,
          "sha512": "6ae04d9957685520a736cbe9b75861bae2c955cd9e435ab7fb8ac209bb01324284dd9805312da4d6487f34763cc95c9283b5718120ae1a8bccca61745617753c",
          "sha256": "fac0fc06a3086a4ff9bb9396aef1810da208501fa9e056736fc3d299e1be0cf0",
          "sha1": "c01e3f60d291755e6135b4512e8234128557a203",
          "md5": "35a3efc7f32e7ccf23355b457de411f5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "c57dcf6cf000399770a71781c03cf84b4864c38a8cad482d4d503f1215173906136fbf0617e34e57e1704162c52f1ad8d12283f02c2a8f139cb4bb205eda2825",
          "sha256": "ab8317dc33b4665452074121366679d1957d125c09409d165c8ee1cb4b506db5",
          "sha1": "73ff4f2001f62c899dd4ba2734a08d8042f61163",
          "md5": "d47d4a78d9f5e9e0f4f7a0e3a3a28d1a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "size": 9205,
          "sha512": "5158b27254edb738557b4f7290405b9e42e0aa6943ad394c55a80a69b1bb052ac6acca4ff33a4dea3492080fefaa7e03ed76c80d1ef5bb0989582f9ab49a231f",
          "sha256": "9c2f6f51b395365ba87816a1ae4961a525d97afde699d3a70275a3f66704bd34",
          "sha1": "86c2c5fe86c7bb44bb11666ce71d14604f13eec1",
          "md5": "57ffe9c4bfba6f6ab68da7e4de4b3338"
        }
      ]
    }
  ]
}
