{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34265,
          "sha512": "8671c42d85d6e2305bc7b1cd841e136f2068c8bc5a139724490b5bd2ec14853e4150d73ac28653cd9eef6f786bdf55d16ee98bdf87d5f84d73446b800390fe1d",
          "sha256": "e98c92d07190a69de84025cf692c056fb3dc83f2913fe39fee44356ed09e13ff",
          "sha1": "669aaf2916ac90bb1f08adea7612abb84614875d",
          "md5": "ff578f1c7f95d031b0383aa3114f77ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34265,
          "sha512": "8671c42d85d6e2305bc7b1cd841e136f2068c8bc5a139724490b5bd2ec14853e4150d73ac28653cd9eef6f786bdf55d16ee98bdf87d5f84d73446b800390fe1d",
          "sha256": "e98c92d07190a69de84025cf692c056fb3dc83f2913fe39fee44356ed09e13ff",
          "sha1": "669aaf2916ac90bb1f08adea7612abb84614875d",
          "md5": "ff578f1c7f95d031b0383aa3114f77ae"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "3da9928255cf6c51eb3b563147d54406c290c3ea804097de6c3363d28f3c1bb2b25216396e0e5b6153420be8913e55779a6333659dffa99b94fa51488e5910c9",
          "sha256": "636b0bfedabed04c538b64d448104e4f3d8214d95ee21ca53818692d9af8049f",
          "sha1": "34629747af08df78dd11b3218aa210633109a20f",
          "md5": "5a493d585d780c8f8ad958792dce1d59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "size": 9205,
          "sha512": "6bcb9c428e97b4ab431dd30cf908c33f76c9dbcd0862000c2a3e7d935b29478caf1a9ab0c2b443d8ae4a991a76e8d1e01be462aad4970d5097c03337dc28cfaf",
          "sha256": "3b3dde71ed67fc17030742522c7111ad66ce94555b44cd6ccca7204afe404f22",
          "sha1": "1ea09c56646ec2cd32e4e5bd6e3fd864909e2c39",
          "md5": "f3f4dd38e4faa64f09440c7855645c34"
        }
      ]
    }
  ]
}
