{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34698,
          "sha512": "6c14401b0614b02ca9702ee2c09646c48340f6a549c597f5c7fdd82aec9bca9c62c68382fcc71b7c59bd3819e55109c709a8a43e37296f898853eb263a7ab1cd",
          "sha256": "009534b398f1cb1ec600360319a17dd550a9766b12d402a51641d6fc2488172a",
          "sha1": "ebbfad4dd9cdb9ece4ff67f41a31aa21cb7bb5f2",
          "md5": "f9f6dcf0887187d927bb8ada02bc36aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34698,
          "sha512": "6c14401b0614b02ca9702ee2c09646c48340f6a549c597f5c7fdd82aec9bca9c62c68382fcc71b7c59bd3819e55109c709a8a43e37296f898853eb263a7ab1cd",
          "sha256": "009534b398f1cb1ec600360319a17dd550a9766b12d402a51641d6fc2488172a",
          "sha1": "ebbfad4dd9cdb9ece4ff67f41a31aa21cb7bb5f2",
          "md5": "f9f6dcf0887187d927bb8ada02bc36aa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "513aa23d9d791ec82a645d843dfeaca29e905555fababf645118936051029929d92e3beb2f7de1bd4e950fc26a1ebd4a9783f934e6469c137c15b7d997dc0eb3",
          "sha256": "b9cbeefe98a1796fa899a7801a4f387c84262d298fdebc89a23b2f15e1f2ed1c",
          "sha1": "2facf34bc292d0f5f1052b090cad301dcb6ebbf3",
          "md5": "3ae1ec158c7582da526a5b10eb6aaf15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "size": 9389,
          "sha512": "31215a8a92ec612a3dbba902ed103b952fd75e5549900e57cacef3e2654d0d5ce4006c1c72b65699d6b8e164b10429a855f9d71e94b8e9dee2e540728fa97988",
          "sha256": "866f7c38c96056d47cd0ded6a82fa4ab2df4ed421dbacdc806b121aa34d35883",
          "sha1": "7475604c03dcceee315b36315e88895daed184fd",
          "md5": "31b28f56f4f2e1806c58564321e6e5d7"
        }
      ]
    }
  ]
}
