{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34861,
          "sha512": "7cea48a3a76cbb8910a78b1ecece4553d737e9de3cbfe18e38fe283d06e221d5dd0714e05535f5fab8bba02bcc3d2d244807e16fbc8e54765c29fc1238c7599c",
          "sha256": "274d23d3d20435d52d3ed268e48552b842cce8a7ecd2700bb15eddc639aa32d1",
          "sha1": "e23fab3a7c87be1c639bd7a6863e18f6b10e5368",
          "md5": "a45389cecac308b99e911a00d5104878"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34861,
          "sha512": "7cea48a3a76cbb8910a78b1ecece4553d737e9de3cbfe18e38fe283d06e221d5dd0714e05535f5fab8bba02bcc3d2d244807e16fbc8e54765c29fc1238c7599c",
          "sha256": "274d23d3d20435d52d3ed268e48552b842cce8a7ecd2700bb15eddc639aa32d1",
          "sha1": "e23fab3a7c87be1c639bd7a6863e18f6b10e5368",
          "md5": "a45389cecac308b99e911a00d5104878"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "26f9bc3c413b1fa328297b3c3722e4edcf0ea4a170da2903c30096fa65efe6b33425d6722673c41372791502c9f852aab1dbe6c41beb77cc5072402165854e99",
          "sha256": "15413ac740e8cfc34f071cebfaa5bfa98e3361bb8629543ab974ed4dcbb3f271",
          "sha1": "72f880867dd90bcc2223232f3ec19e1b21532861",
          "md5": "e5a77b6f62876e406f991a5593e94d23"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "size": 9465,
          "sha512": "07bfbe8aa5b000b996b1b2cbbd1016a27346e50e844aad1022f3f2ebe440b920cc70c2cb60d29033ca2a38e9165a6847f8e2ea36173403a803ee66adb64f5c38",
          "sha256": "ebeb98623f8e77403ad48172ace51c7e1ecb9f68c8e3c5ef1dc926c416afd6e4",
          "sha1": "768403c392f16758635ef5ddb9b028b57254b298",
          "md5": "538171f2a4de6f3642e0ba5365eb8ce6"
        }
      ]
    }
  ]
}
