{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34698,
          "sha512": "c5d1593b7ce8da28645fbf14cd79f75a9c88415bc755e68f715ff0272228493434556771c4281109d0886b54cb84ca56d35c5fe9f93997ed0435b80a1e5c3d59",
          "sha256": "48b77f8efc455a4b6fc92f3167aece89e5d434f925a5d5281af14f4ae3abba94",
          "sha1": "4afef0d474e7c30136b4dc535d472ce2a38a70e4",
          "md5": "602a84e9a901cc117462e8b6d64b683e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34698,
          "sha512": "c5d1593b7ce8da28645fbf14cd79f75a9c88415bc755e68f715ff0272228493434556771c4281109d0886b54cb84ca56d35c5fe9f93997ed0435b80a1e5c3d59",
          "sha256": "48b77f8efc455a4b6fc92f3167aece89e5d434f925a5d5281af14f4ae3abba94",
          "sha1": "4afef0d474e7c30136b4dc535d472ce2a38a70e4",
          "md5": "602a84e9a901cc117462e8b6d64b683e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "8ea344478ad19c10e1a300273b3157e6a65c0a06bf659285bd8f9e9fa793205697d2a7d1b73f5710a3bcaa24b43f34bf425c66a721ef344176f8354a98e3f039",
          "sha256": "20cfbdee2e3fa4f76e8a4974c8c7c36248751e906279715a455f75099737053a",
          "sha1": "981034ffd195f4110f6276cc022ea78965dd2204",
          "md5": "0b677e0dad974b7afa0e778d2066d481"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "size": 9389,
          "sha512": "571c35c15f072b70063cbe8f6194407220d92e4adff8fcee2c54b018043364979173ee2c3d819844c3cfebbe5f815b2e4eb8670c65f29e5881fda1dd72175be0",
          "sha256": "2ec30c5f48153264f531500e3b3f9168d07deb4d369393ed0e9110659a40070c",
          "sha1": "c6270afc9c1fb2282440a17c757a8ac3aa88de8e",
          "md5": "f865c7ecf7784f52060ae180bc829736"
        }
      ]
    }
  ]
}
