{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34861,
          "sha512": "21cab704e4e94ecadc4e416c7bcbdbefc14098e31a13adf4e6c95e5361e8bbaa560e109b85eec34b310fc1202ec6bd9c3d1dcc2c146ff094d36286b41ee34945",
          "sha256": "8c611d839c2561a389d3fb9951aca3ec7263e9bbbf8ca652fc817bc055320edf",
          "sha1": "a5de3bbfdb43c59e8d5270ec141736d963b614c3",
          "md5": "bd416348697962b030b65c5ffd46e226"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34861,
          "sha512": "21cab704e4e94ecadc4e416c7bcbdbefc14098e31a13adf4e6c95e5361e8bbaa560e109b85eec34b310fc1202ec6bd9c3d1dcc2c146ff094d36286b41ee34945",
          "sha256": "8c611d839c2561a389d3fb9951aca3ec7263e9bbbf8ca652fc817bc055320edf",
          "sha1": "a5de3bbfdb43c59e8d5270ec141736d963b614c3",
          "md5": "bd416348697962b030b65c5ffd46e226"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "4eb4f889e4b316c4190f801b759d89e8c616ee6dd14a31b19834dd76471df0e6e726e321abd8a77da3bd242bc3b90c873d507eda2625ae0d8430d8415946c0c1",
          "sha256": "9ebfcd8ad11f007d5650b88c440b788fbd177ce97e3dc5168b686a0348e7d25d",
          "sha1": "336b896094e875df069edf99a1c5f9a8c62db19f",
          "md5": "a49e8b724219f212745eec1c6bec3e4e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "size": 9454,
          "sha512": "fa0e2ac150dcd49d4d26e16fbf3fe8fe99c831d3eadd08b7d637dea44e247bc234ca6277ae68f9613164d79f8c574e296de0fab076bc939417048c6eac283a66",
          "sha256": "cb18d1839fc79d8e2aae5da6d505cf0fc37449641ea71a1595bda18763d59aad",
          "sha1": "5a2b0e17b8e344288ca10cb7190c3ead052b877f",
          "md5": "25680d4b195f6dc5698ef4cca2bb8158"
        }
      ]
    }
  ]
}
