{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 40978,
          "sha512": "054a897f057dddaa0bd49f35c8a5f0f29d3c23c44f8502fd61df32e9604afe3033859bcd7ed7040b9213f0f809578a5486030f906a2d89d7321a3fa2e9030213",
          "sha256": "7e8aff042de17400362e42d070f4c98fa02ad06f98d081eac74c7a073ef854af",
          "sha1": "1dac40ddce8f07fc4f94e0c52af753b56b85ff47",
          "md5": "1e0c6fae0a5b1b3a3123659f53e03a6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 40978,
          "sha512": "054a897f057dddaa0bd49f35c8a5f0f29d3c23c44f8502fd61df32e9604afe3033859bcd7ed7040b9213f0f809578a5486030f906a2d89d7321a3fa2e9030213",
          "sha256": "7e8aff042de17400362e42d070f4c98fa02ad06f98d081eac74c7a073ef854af",
          "sha1": "1dac40ddce8f07fc4f94e0c52af753b56b85ff47",
          "md5": "1e0c6fae0a5b1b3a3123659f53e03a6b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "97d93bef31562ba1404765006f1004c2c93917a2d78259a82ca20bb7be08501e928d8532ae89c8a3ebfc7e33027a2b5641f2487eafa1b8520b9ee4d83e3b30ef",
          "sha256": "d5032b6d0cdb19bf0ca9b77d14669990a1de8881751dbc205d6bf00e7b521e1c",
          "sha1": "e6502caa8902315815bda3b18f93848f2a57d6ec",
          "md5": "0290598fdb8bb18593c64e0ceaa1998e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "size": 10357,
          "sha512": "96ba6558a53b974316200067e643d85f02c8aabdd8c646600d32f7d31006e1bae575d700b2362357ddbe84445e8240e4c126f5dbd99544c07bcca1ed7465e60d",
          "sha256": "4e1bce5485f25521ad3e62368ff0fb9226d4071d0c903876a7691a98d79498ef",
          "sha1": "734a9911426302f2a8e62fb76fb6774e239fcc0c",
          "md5": "e067c979ec1b9120b2231440bfe42894"
        }
      ]
    }
  ]
}
