{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34698,
          "sha512": "8f3375a0894ada99378e9112ef367e0c5eadbef3e98b1f7bf56047c172736a497b937ed2b50c26e07c732a8dd863cac5f650eb1da1d441d77d9f0e4f1c2f4f23",
          "sha256": "2ae4f63101359a5f9eb758991775697156d6ea88145259353535d41008230ff5",
          "sha1": "218a6836a3625717de6227cc77ded400f32271f9",
          "md5": "b15324874ab2c092a3785a9899af2787"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34698,
          "sha512": "8f3375a0894ada99378e9112ef367e0c5eadbef3e98b1f7bf56047c172736a497b937ed2b50c26e07c732a8dd863cac5f650eb1da1d441d77d9f0e4f1c2f4f23",
          "sha256": "2ae4f63101359a5f9eb758991775697156d6ea88145259353535d41008230ff5",
          "sha1": "218a6836a3625717de6227cc77ded400f32271f9",
          "md5": "b15324874ab2c092a3785a9899af2787"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "a937c7549453516b3cb41a2fbd38dfd344352074e05b6edc7c1ecefae5ba72a062b7c52466a00b8af17a484c235a50d454c356375d55217fafed91f416fb3fa0",
          "sha256": "24c1ec4b822d0ab12094dd748162ea1ef711368c04e5deb8f3c51a2062e18ca7",
          "sha1": "7505e957863e5a5e8f1df32d584dcfc1de4991bd",
          "md5": "ec130da62cf35d2f8f004ae81cb1ff14"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "size": 9389,
          "sha512": "9ab0b3cd41749e4b6bf3afbe42ac67d5a7cfac3f727bef8c6b964d6d1c64039e883fd7350bd2ffb08f11ba5ba25778b1583d1c414184b1ff7ec8a3b671351149",
          "sha256": "e45fb4e4c0e89c9cb677da09e6439eba5023253eba075904e6cbe1e3c78af2c5",
          "sha1": "62e0a651912716010efb6140d444a1b2c8b906db",
          "md5": "dee8259f0a986d53a866b8e7c834d64b"
        }
      ]
    }
  ]
}
