{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34265,
          "sha512": "dffd6e1fc608ad38741fe4b1a33b459f25cdced2ddd81eb5ede7004426e97438618116ee003def35a51b9957d61fab29945f40178e640fecf32028859362c2e7",
          "sha256": "97736e6f0c0c0bcefde4d8da9bee8fe11d36140d5479e496c4df689d6799e9ed",
          "sha1": "b03f3525bcde2fd7b5b99b875de36c9fd499cf64",
          "md5": "b8074130c4392e6a21598f42f44c4291"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT.jar",
          "size": 34265,
          "sha512": "dffd6e1fc608ad38741fe4b1a33b459f25cdced2ddd81eb5ede7004426e97438618116ee003def35a51b9957d61fab29945f40178e640fecf32028859362c2e7",
          "sha256": "97736e6f0c0c0bcefde4d8da9bee8fe11d36140d5479e496c4df689d6799e9ed",
          "sha1": "b03f3525bcde2fd7b5b99b875de36c9fd499cf64",
          "md5": "b8074130c4392e6a21598f42f44c4291"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "c395b71bfc79c0387167921a87ac9b62284ab26959a4968dd612540adfa7d2e38a9bb46183e71c854f787a3f396202effee63cfa8e9c33ca3772db9b67c56038",
          "sha256": "0bd98a0bc36934bf537133cf21cfadfb7766ae2c9e4dcee576239b5b68a3c120",
          "sha1": "eafec7d5feee7901f14a48acff9929350c38f572",
          "md5": "d14d6687d8e8606b589f487d6498e066"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-SNAPSHOT-sources.jar",
          "size": 9205,
          "sha512": "565c8cbe4f587b8a8ead22a562dec5585d7ba59e1f4eed71b0081a05974a7e621ab5c6ec14d0292469bc32365165a5743c7154fddeda1c7a82c4b7fc0e008b2d",
          "sha256": "c3d11bf138419b32f1649d3b9489681b545941d063599cbbcd5de64a71776ff9",
          "sha1": "7a7421d7308a6a909cd633666db56534946ea337",
          "md5": "4c945783242a5a518f88824efe830b61"
        }
      ]
    }
  ]
}
