{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "b0f1bff",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-metadata-b0f1bff-all.jar",
          "url": "test-utils-fixture-b0f1bff-all.jar",
          "size": 15401,
          "sha512": "4817a800921d0bd906b6a3f64425f60bb6a0d40a9b33aff916ad5af204bbdcaf9b33434143155162a5517a7be8cf68b5a5482e2484ace735e6af64f4d472c5f3",
          "sha256": "6db40ab8b6f66464e8654daa9b76831e37076fb5698846cd28d16bde72ef8097",
          "sha1": "24dc6b4931de5991b6b605dcfad10e9c194757d2",
          "md5": "c5a3c40a80b053e6ac46839861c4544e"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-fixture-b0f1bff.jar",
          "url": "test-utils-fixture-b0f1bff.jar",
          "size": 15466,
          "sha512": "aadc3b34b9801aa944c03e04110a7f5997ce12065c9cb579ee283b8efe98bf14569156fb3da36bcfb7c2b1d5e93a1097aa6074ba7e211ece5a876a8a252cac70",
          "sha256": "fd14c5b069d6b98a18591ce1ef43b92552354eb3d3a4665c419c9de46ebd1091",
          "sha1": "1f437c318619c490ea29613d5b4fc1791e45f890",
          "md5": "e83d63f4e53e483528d78666c2f32016"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-android/b0f1bff/test-utils-fixture-android-b0f1bff.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-android",
        "version": "b0f1bff"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-android/b0f1bff/test-utils-fixture-android-b0f1bff.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-android",
        "version": "b0f1bff"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iosarm64/b0f1bff/test-utils-fixture-iosarm64-b0f1bff.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iosarm64",
        "version": "b0f1bff"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iosarm64/b0f1bff/test-utils-fixture-iosarm64-b0f1bff.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iosarm64",
        "version": "b0f1bff"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iosx64/b0f1bff/test-utils-fixture-iosx64-b0f1bff.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iosx64",
        "version": "b0f1bff"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iosx64/b0f1bff/test-utils-fixture-iosx64-b0f1bff.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iosx64",
        "version": "b0f1bff"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-fixture-js/b0f1bff/test-utils-fixture-js-b0f1bff.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-js",
        "version": "b0f1bff"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-fixture-js/b0f1bff/test-utils-fixture-js-b0f1bff.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-js",
        "version": "b0f1bff"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-jvm/b0f1bff/test-utils-fixture-jvm-b0f1bff.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-jvm",
        "version": "b0f1bff"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-jvm/b0f1bff/test-utils-fixture-jvm-b0f1bff.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-jvm",
        "version": "b0f1bff"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-linuxx64/b0f1bff/test-utils-fixture-linuxx64-b0f1bff.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-linuxx64",
        "version": "b0f1bff"
      }
    }
  ]
}
