{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "add2d99",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-add2d99.jar",
          "url": "antibytes-coverage-add2d99.jar",
          "size": 128039,
          "sha512": "f9562e8cbaead2433d6f17f1c7e8e8989311d96bb34eb8663810862f6c894bf78beff85c1a5279cc4bafa64d787630c8763bd57db3c4266a2a0b92eeb46e5be4",
          "sha256": "851aea7d6c276704fc380c7d7899fa37e6fb1abe3cadd28f5a126afdb355c609",
          "sha1": "aa95a2e5bf79970e16214111682a3fb589da30cb",
          "md5": "e14228989b251a64174d59b274c8a0d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-add2d99.jar",
          "url": "antibytes-coverage-add2d99.jar",
          "size": 128039,
          "sha512": "f9562e8cbaead2433d6f17f1c7e8e8989311d96bb34eb8663810862f6c894bf78beff85c1a5279cc4bafa64d787630c8763bd57db3c4266a2a0b92eeb46e5be4",
          "sha256": "851aea7d6c276704fc380c7d7899fa37e6fb1abe3cadd28f5a126afdb355c609",
          "sha1": "aa95a2e5bf79970e16214111682a3fb589da30cb",
          "md5": "e14228989b251a64174d59b274c8a0d3"
        }
      ]
    }
  ]
}
