{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "11324f8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-11324f8.jar",
          "url": "antibytes-custom-component-11324f8.jar",
          "size": 16534,
          "sha512": "123b3d8b9b9189068631063c28e370aa7a78095a831e959a98dbe772d27d3d5615b543699205e11d1e78be44cfe7960b71fd00c98262c7364b1c876d98d49342",
          "sha256": "4e5a79fe2f28ce778f55956d8bfa291c9380ef0fcce9fb081e82224e16373475",
          "sha1": "e9f3eaa2dc764217a4632b02bb1102926cfb35f8",
          "md5": "068c7ad3b6af67e793d56a22906204b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-11324f8.jar",
          "url": "antibytes-custom-component-11324f8.jar",
          "size": 16534,
          "sha512": "123b3d8b9b9189068631063c28e370aa7a78095a831e959a98dbe772d27d3d5615b543699205e11d1e78be44cfe7960b71fd00c98262c7364b1c876d98d49342",
          "sha256": "4e5a79fe2f28ce778f55956d8bfa291c9380ef0fcce9fb081e82224e16373475",
          "sha1": "e9f3eaa2dc764217a4632b02bb1102926cfb35f8",
          "md5": "068c7ad3b6af67e793d56a22906204b4"
        }
      ]
    }
  ]
}
