{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "8c67525",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-8c67525.jar",
          "url": "antibytes-grammar-tools-8c67525.jar",
          "size": 39371,
          "sha512": "0cbdcd1aa6d240f3989d2433363335722329bf2401823046ed1b60ae357bb603d5fd7a1c18b52166e84e9fec576a274f721e381b4e4ed10428614b3dcbb7d759",
          "sha256": "1f943c362d27966d4a51b1504e781554a3d8d183395ffa09d0878bb08e261ef2",
          "sha1": "f87cb9f1ef10eff3c8d7b556e1277413bf810401",
          "md5": "e85d9994bc3222f61c0afea6337a21f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-8c67525.jar",
          "url": "antibytes-grammar-tools-8c67525.jar",
          "size": 39371,
          "sha512": "0cbdcd1aa6d240f3989d2433363335722329bf2401823046ed1b60ae357bb603d5fd7a1c18b52166e84e9fec576a274f721e381b4e4ed10428614b3dcbb7d759",
          "sha256": "1f943c362d27966d4a51b1504e781554a3d8d183395ffa09d0878bb08e261ef2",
          "sha1": "f87cb9f1ef10eff3c8d7b556e1277413bf810401",
          "md5": "e85d9994bc3222f61c0afea6337a21f6"
        }
      ]
    }
  ]
}
