{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "15fbbaa",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-15fbbaa.jar",
          "url": "antibytes-grammar-tools-15fbbaa.jar",
          "size": 39371,
          "sha512": "c0e1e4dd854a4b4fa0c48091d82e83275009a89cf1d5697acccb35746d8618404b08392a43361afeed26ba4602d70abf83c2cc9f2bef3d128b31f3b0716392f4",
          "sha256": "074381fd8c8be781180fba11efa27409e8ac213c42948f84b3a81a74541f3d35",
          "sha1": "6969e48851c01cc690c1202518f4881d513805fe",
          "md5": "def2a46c7b3eeda10b62cb472d53b2c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-15fbbaa.jar",
          "url": "antibytes-grammar-tools-15fbbaa.jar",
          "size": 39371,
          "sha512": "c0e1e4dd854a4b4fa0c48091d82e83275009a89cf1d5697acccb35746d8618404b08392a43361afeed26ba4602d70abf83c2cc9f2bef3d128b31f3b0716392f4",
          "sha256": "074381fd8c8be781180fba11efa27409e8ac213c42948f84b3a81a74541f3d35",
          "sha1": "6969e48851c01cc690c1202518f4881d513805fe",
          "md5": "def2a46c7b3eeda10b62cb472d53b2c4"
        }
      ]
    }
  ]
}
