{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.settings",
    "module": "antibytes-dependency-settings",
    "version": "5bbfded",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-settings-5bbfded.jar",
          "url": "antibytes-dependency-settings-5bbfded.jar",
          "size": 11230,
          "sha512": "5f929fdceeef1d716131495bd9c0dae250b3259adef26cc66d32b836f944ad45f0fe04d7e76bbf7269187a5af633b356bc734159460f96cf6ddd6bfc12e333e7",
          "sha256": "be4826367742b33122f5ace5f099fa85ca1c2990b1ae8d5049f48004e9f37699",
          "sha1": "06cb6140fba6758a88e4097f2399fc10a23e0bdb",
          "md5": "7996e095dec62a6c88b07f86bdb2ee8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-settings-5bbfded.jar",
          "url": "antibytes-dependency-settings-5bbfded.jar",
          "size": 11230,
          "sha512": "5f929fdceeef1d716131495bd9c0dae250b3259adef26cc66d32b836f944ad45f0fe04d7e76bbf7269187a5af633b356bc734159460f96cf6ddd6bfc12e333e7",
          "sha256": "be4826367742b33122f5ace5f099fa85ca1c2990b1ae8d5049f48004e9f37699",
          "sha1": "06cb6140fba6758a88e4097f2399fc10a23e0bdb",
          "md5": "7996e095dec62a6c88b07f86bdb2ee8c"
        }
      ]
    }
  ]
}
