{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "875fe2a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-875fe2a.jar",
          "url": "antibytes-gradle-utils-875fe2a.jar",
          "size": 9421,
          "sha512": "de050778eb8b5c4498d62436c840e4e8ce43fdce6e1e913963a73999b0443ab5148d7872586f611ce6a4a627d4431df81669759c778eb9fb96c3fe6dadd07795",
          "sha256": "f12d069fc4ff3633e1f2dba4e794c3ce855e2569d3bd7be331b942ac1df61967",
          "sha1": "69f355971f13a6fe54fdb6da3af45eba8635d636",
          "md5": "a5d273e1ce0c7ee59f512710ebe0a779"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-875fe2a.jar",
          "url": "antibytes-gradle-utils-875fe2a.jar",
          "size": 9421,
          "sha512": "de050778eb8b5c4498d62436c840e4e8ce43fdce6e1e913963a73999b0443ab5148d7872586f611ce6a4a627d4431df81669759c778eb9fb96c3fe6dadd07795",
          "sha256": "f12d069fc4ff3633e1f2dba4e794c3ce855e2569d3bd7be331b942ac1df61967",
          "sha1": "69f355971f13a6fe54fdb6da3af45eba8635d636",
          "md5": "a5d273e1ce0c7ee59f512710ebe0a779"
        }
      ]
    }
  ]
}
