{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/35ae125/kmock-35ae125.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "35ae125",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "c3e5acf"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-linuxx64-35ae125.klib",
          "size": 98294,
          "sha512": "519a847f0f4065953e677d08313ce3e68a25a787a8bcca504460b8c45b78a273f091ca2286d958445a94ceb00fad704b47951de0e53e80b58c7509fff7b0880e",
          "sha256": "fcffc02ec20b314e3f711380ada7fb1b3fd9ff343f98ffbac6a2be4a1dc628cf",
          "sha1": "7d319e459fe04599a1b185867969bd1c1718c7b0",
          "md5": "87dafec931be15908181435f9d194a84"
        }
      ]
    }
  ]
}
