{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/26d38d1/fixture-26d38d1.module",
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "26d38d1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture.klib",
          "url": "fixture-iosarm64-26d38d1.klib",
          "size": 49906,
          "sha512": "2ccd97904457e2cd7c819d15214d0d346fae17abfbf9ca5a4cfaf99b8832e4099d88196b7729c7c8238bd117ac7e411791113207b12b5411c51c5f56b37f5f42",
          "sha256": "d8afab15c46293614c0eeecde25982a1406f997404022d05381bd1b973875de6",
          "sha1": "74723ae6e3d8cb6127e888822736329bf8593a1a",
          "md5": "2d87bd54ab65678c44f29ac556056008"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-iosarm64-26d38d1-metadata.jar",
          "url": "fixture-iosarm64-26d38d1-metadata.jar",
          "size": 261,
          "sha512": "44e4702a1284a0e6e99721592d51a55b9e21ca0856043a4e9ef6a9113f2aefa17f15831a4f6d9aa573920d9020c3ca8613f1a8e4e4d067696e189de30a7b3c97",
          "sha256": "895d1c9e23652c154beb02e85c0ee443b829e5d8e5124e62ee2c5ec88d30dc4f",
          "sha1": "e56a8612d3e354fbd95f1fe0c0e7c4c9eb77624e",
          "md5": "b535e4b896cae186065b2b38b19ef7d8"
        }
      ]
    }
  ]
}
