{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-runtime-configuration",
    "version": "ec7ea01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-ec7ea01.jar",
          "url": "antibytes-runtime-configuration-ec7ea01.jar",
          "size": 9073,
          "sha512": "f7dc5cd83f2acf4fc846093539546b82ed1a16b204ef5c73562e174a121036fb49c2fc3bc69fc5517230dd6b0ee962037209710cc824a79264b562a90567f983",
          "sha256": "1601350d15572c8bc2358ee447e7417845a5ccb5b399cf89b0c49351d5a161d6",
          "sha1": "3f64bad71c76c3f8d9fe3949b15f86a8ac673c7e",
          "md5": "59ccc14e7738be0300a9fdec07e81b03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "ec7ea01"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-ec7ea01.jar",
          "url": "antibytes-runtime-configuration-ec7ea01.jar",
          "size": 9073,
          "sha512": "f7dc5cd83f2acf4fc846093539546b82ed1a16b204ef5c73562e174a121036fb49c2fc3bc69fc5517230dd6b0ee962037209710cc824a79264b562a90567f983",
          "sha256": "1601350d15572c8bc2358ee447e7417845a5ccb5b399cf89b0c49351d5a161d6",
          "sha1": "3f64bad71c76c3f8d9fe3949b15f86a8ac673c7e",
          "md5": "59ccc14e7738be0300a9fdec07e81b03"
        }
      ]
    }
  ]
}
