{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosx64-0.2.0-SNAPSHOT.klib",
          "size": 73798,
          "sha512": "1ffdce8ad398945fdbde404a385ece5dd4c3d7a6ec11995c44e58ae61c12cd1cf265586294968ea34a2350909483976f0223d095beb2e188688c6a4973118939",
          "sha256": "092408fdcd3323c031782f003a3e082de0d66a311ea92d6b5465550f7bfc0e2a",
          "sha1": "16424e0794313325f873124a0ffa38e683bb4dd6",
          "md5": "667a5815bb870f76342ea5d5ca1236ca"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.2.0-SNAPSHOT-metadata.jar",
          "url": "core-iosx64-0.2.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "f471e463fd766d791c6a170229c346cdce89ce812d54b3fc074b57bc27ac9181561bcb9afaf2ec310cd485f34c4a19b89e9a0a0ba5b5da35d7f557b40fea9812",
          "sha256": "3c4410d76e96289e261d1f4e327446ddc2c065e3b4f342fc2fd0b3eef770c5f5",
          "sha1": "fcd5aba94af00b950661cf19c6e46c76bf0d7e67",
          "md5": "2baf3a9e98b5f1d5286c3f8fba211297"
        }
      ]
    }
  ]
}
