{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-SNAPSHOT/ktx-datetime-0.3.1-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iossimulatorarm64-0.3.1-SNAPSHOT.klib",
          "size": 34785,
          "sha512": "8f0b1a31f3112809e249c830ea7dc505cd979b549c66f799f854a8c005e456b87cb265a5642b64c9090441f96a1dc355070b088c49f54bb31ee8fe6de75689a6",
          "sha256": "f1a3d0355c51be80e881bd041a1cbb722f80aabcf457e03d3d141b141ce99a23",
          "sha1": "98d8873bffae3b4f6f3e1f2920f94408a0d4de20",
          "md5": "e73173220ddfd62b626eeec87f235a82"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iossimulatorarm64-0.3.1-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iossimulatorarm64-0.3.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "df83287d9cd769282cd85e5f75ee7a63d5009a48fd91fec164e71b65cb187e689f8a2d8ef050afe4c1bc5bd7fd53295302c8a50cd3185d523e351373d4801e0b",
          "sha256": "6359c91f60e460114f491167391612e33293fd0ba0f4987603bddacc1658125e",
          "sha1": "254454f5c80e904c70ea53935e9a1675bc922a3b",
          "md5": "d6b8b5bbc2904ffb2f1244fb3b9ae238"
        }
      ]
    }
  ]
}
