{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-SNAPSHOT/ktx-datetime-0.3.1-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iossimulatorarm64-0.3.1-SNAPSHOT.klib",
          "size": 24722,
          "sha512": "27223820637802d3e15a5077e945cbe45f75eb419981f8a657d1daeb26a7368aadd520dd5258296b39d578f9cc7492f0c6a9e1d87d7690e6a244913265a1e379",
          "sha256": "4edee04f2a54b015108b9f1a84a067d1f4dca296e1de4636d50216da769811de",
          "sha1": "0ffe176971065eb15976a3366fc2411a174cfa8e",
          "md5": "c8b1b7db866a064e4fe72dedfa5db40b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iossimulatorarm64-0.3.1-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iossimulatorarm64-0.3.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7441e58d70ca2530f7dee0778b82ee0b8b001bd556888e4c9fff923ce1fe89a7e8ab405d814e2fe77fe0a49254ad3825467304255382878a27b2e7ec584e5d33",
          "sha256": "1b2cbdeefe6958aa6c286bc864d3ab7e479a1b84933fd6739a5d78d6b9cf7b4a",
          "sha1": "92defa96a113cc9e59072c159a683d1d9022e83c",
          "md5": "cf81a85a04d474a535d3400677368abd"
        }
      ]
    }
  ]
}
