{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "4137039",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-4137039.jar",
          "url": "antibytes-gradle-test-utils-4137039.jar",
          "size": 15105,
          "sha512": "76dcf6483cf60352b47528ffb11fd9361a4e14397dd0a8887d50ffab0e780a6c62259e646a6052f29bc61a5e35cfb0c0f1da95ce37525e95bc8efe69bace84bf",
          "sha256": "c7f4bac8bbbd5584894be5021780eadc73ff9ac54417d44657bb67bdc7c9b534",
          "sha1": "8ab87fc54addeed664d5622202adb5ee7c2048b3",
          "md5": "a4f938979f18bdce5a0ff63defdf63a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-4137039.jar",
          "url": "antibytes-gradle-test-utils-4137039.jar",
          "size": 15105,
          "sha512": "76dcf6483cf60352b47528ffb11fd9361a4e14397dd0a8887d50ffab0e780a6c62259e646a6052f29bc61a5e35cfb0c0f1da95ce37525e95bc8efe69bace84bf",
          "sha256": "c7f4bac8bbbd5584894be5021780eadc73ff9ac54417d44657bb67bdc7c9b534",
          "sha1": "8ab87fc54addeed664d5622202adb5ee7c2048b3",
          "md5": "a4f938979f18bdce5a0ff63defdf63a0"
        }
      ]
    }
  ]
}
