{
  "formatVersion": "1.1",
  "component": {
    "url": "../../banana-i18n/e4c2701/banana-i18n-e4c2701.module",
    "group": "tech.antibytes",
    "module": "banana-i18n",
    "version": "e4c2701",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-e4c2701.jar",
          "size": 1394,
          "sha512": "e83b97e5ff7403548b1c2f97b1461e0281988457134bc7d360d7663a8ef70ecd29436af2ff7b392da41648c90ecebbeb351c2768ddc71f0ce54049438c186a29",
          "sha256": "7e1f4b4497cc1811bf019ba2e28920cbc4dd09cf79e7f5d2a52efbab8c668f9b",
          "sha1": "4bfeb198d9e3b643f1bf129649e9b3a5e30290f2",
          "md5": "b24e15e46e63f85cc7d7a3d9489119d5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-e4c2701.jar",
          "size": 1394,
          "sha512": "e83b97e5ff7403548b1c2f97b1461e0281988457134bc7d360d7663a8ef70ecd29436af2ff7b392da41648c90ecebbeb351c2768ddc71f0ce54049438c186a29",
          "sha256": "7e1f4b4497cc1811bf019ba2e28920cbc4dd09cf79e7f5d2a52efbab8c668f9b",
          "sha1": "4bfeb198d9e3b643f1bf129649e9b3a5e30290f2",
          "md5": "b24e15e46e63f85cc7d7a3d9489119d5"
        }
      ]
    }
  ]
}
