{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/fc88d6a/test-utils-annotations-junit5-fc88d6a.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "fc88d6a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-mingwx64-fc88d6a.klib",
          "size": 7050,
          "sha512": "f22d54fe1a1ed8bad90c19c1823929b298d6ac161289f09a2c5fd51e1ddf8430ead89d9702f10ee77a03acefeb0bdfcd91c4a480be6c494e2cdea620b77e3d42",
          "sha256": "18555dfd3ab06ea2b312c504a65395bbc06916b71ace9669de78a979b148b33a",
          "sha1": "10a1a18a690d8f6f9fc9abe7dac63f2315f50dfc",
          "md5": "0dfc535ef2704ddab9d7087974052727"
        }
      ]
    }
  ]
}
