{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/1b54cfa/test-utils-1b54cfa.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "1b54cfa",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-1b54cfa.jar",
          "size": 17517,
          "sha512": "fa2b654fdc634576a778f00afe74693eb3af06d1cd733c1e84f3e395386fbd15f2c87772d85789e8c152e182734ca1dfbf1af7aac808d7f36be153368131577d",
          "sha256": "1022121adc1b9addbfed77d731041a9736d4fe7438c3fd10665c472031a740b0",
          "sha1": "ad0539b47c9f2d8ab119842c03521ef9e64e5eb8",
          "md5": "24f454e17a6a0cbe680dccbc5e289d4d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-1b54cfa.jar",
          "size": 17517,
          "sha512": "fa2b654fdc634576a778f00afe74693eb3af06d1cd733c1e84f3e395386fbd15f2c87772d85789e8c152e182734ca1dfbf1af7aac808d7f36be153368131577d",
          "sha256": "1022121adc1b9addbfed77d731041a9736d4fe7438c3fd10665c472031a740b0",
          "sha1": "ad0539b47c9f2d8ab119842c03521ef9e64e5eb8",
          "md5": "24f454e17a6a0cbe680dccbc5e289d4d"
        }
      ]
    }
  ]
}
