{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "e45307c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-e45307c.jar",
          "url": "antibytes-gradle-utils-e45307c.jar",
          "size": 9568,
          "sha512": "5fb7b2b3bd886f9309ebd28f7613f5c5033bb0ab9452a6ff8ac83ef3ee6d9bb842780ba2c05abb2689de69e864933f120625c25ac97222930566c45d56dde8c3",
          "sha256": "8daf41e839754399e6c9ab6bd0f12adf712c9cd305214b4a5d436ff3c2f8889c",
          "sha1": "9bbf4aba1b44da664bb5869b167af267d864f7e6",
          "md5": "de01f08c1c1d5c9e7c33c21c8e821b22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-e45307c.jar",
          "url": "antibytes-gradle-utils-e45307c.jar",
          "size": 9568,
          "sha512": "5fb7b2b3bd886f9309ebd28f7613f5c5033bb0ab9452a6ff8ac83ef3ee6d9bb842780ba2c05abb2689de69e864933f120625c25ac97222930566c45d56dde8c3",
          "sha256": "8daf41e839754399e6c9ab6bd0f12adf712c9cd305214b4a5d436ff3c2f8889c",
          "sha1": "9bbf4aba1b44da664bb5869b167af267d864f7e6",
          "md5": "de01f08c1c1d5c9e7c33c21c8e821b22"
        }
      ]
    }
  ]
}
