{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/56c4547/test-utils-56c4547.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "56c4547",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-watchossimulatorarm64-56c4547.klib",
          "size": 8083,
          "sha512": "1a5e29cb7fcf97a56aef35ede031943fac3221134669174f129621ebe394d37305b582150e88a476fbb20e59440b0667a203484d904fe4e66b3da4cfee501817",
          "sha256": "2219122e15879d93043ea2b83dcd4ccd9c17cc17db74b2e6739a8127b893d242",
          "sha1": "07dfb622f7f0cd389f91cf49b856ddc171d8845d",
          "md5": "7be4beab6795b01d68ddaa9de9a945b5"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-watchossimulatorarm64-56c4547-metadata.jar",
          "url": "test-utils-watchossimulatorarm64-56c4547-metadata.jar",
          "size": 261,
          "sha512": "eca9aa0a5ed02188843db70da1710d6eadad18a87e0388486a004b524717a61fa7c6e46ed429dbbfd29968945d0fbcda9c9deb43101dba5c655564220faccafa",
          "sha256": "fea059866d13f6307a9b4aa85fe68ded7698c72923e4429f1249902e68e0987d",
          "sha1": "974fe98e181286754e54b09396e75e3a97a749dc",
          "md5": "14b89abd533269eaeb26e3f27917370a"
        }
      ]
    }
  ]
}
