{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "afcad58",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-afcad58.jar",
          "url": "antibytes-android-application-configuration-afcad58.jar",
          "size": 58039,
          "sha512": "e7bbb5038accd46c40c4a774d5d2f13ed3c47a70aeba813ffdc9094bbed9cf3a93b1ddab3ff62d39d5c77186f44843ec39867d23bd81b759ca3367194a415d29",
          "sha256": "56241d793517e9b60aa158af6209393094d08d98104fb8876ec07a1297800f58",
          "sha1": "637662c94ffaed1ac71457b973e6c27b4a39910d",
          "md5": "a3e22af634ce2371c9f9aa9d3240ceed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "afcad58"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-afcad58.jar",
          "url": "antibytes-android-application-configuration-afcad58.jar",
          "size": 58039,
          "sha512": "e7bbb5038accd46c40c4a774d5d2f13ed3c47a70aeba813ffdc9094bbed9cf3a93b1ddab3ff62d39d5c77186f44843ec39867d23bd81b759ca3367194a415d29",
          "sha256": "56241d793517e9b60aa158af6209393094d08d98104fb8876ec07a1297800f58",
          "sha1": "637662c94ffaed1ac71457b973e6c27b4a39910d",
          "md5": "a3e22af634ce2371c9f9aa9d3240ceed"
        }
      ]
    }
  ]
}
