{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "a1b98b8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-a1b98b8.jar",
          "url": "antibytes-dependency-node-a1b98b8.jar",
          "size": 21473,
          "sha512": "5792ad702a0136253dd56e6da545a2b9f1b77264d3cf03945c1464998b56f3e555b4015203d528bf31a588ae06a22d20ae623b3fa47179483d94ea0f877d9256",
          "sha256": "571dbee4bccd18ce8f12f8735570313d392c28bbd9c6417a37101f76f58503c9",
          "sha1": "7c6bf5cf5e3906adf65d5953582ab5417e361106",
          "md5": "ec2cc14a4f56ee813599ec93382d562a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-a1b98b8.jar",
          "url": "antibytes-dependency-node-a1b98b8.jar",
          "size": 21473,
          "sha512": "5792ad702a0136253dd56e6da545a2b9f1b77264d3cf03945c1464998b56f3e555b4015203d528bf31a588ae06a22d20ae623b3fa47179483d94ea0f877d9256",
          "sha256": "571dbee4bccd18ce8f12f8735570313d392c28bbd9c6417a37101f76f58503c9",
          "sha1": "7c6bf5cf5e3906adf65d5953582ab5417e361106",
          "md5": "ec2cc14a4f56ee813599ec93382d562a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-a1b98b8-javadoc.jar",
          "url": "antibytes-dependency-node-a1b98b8-javadoc.jar",
          "size": 261,
          "sha512": "77f769df5dc8227e2ce7291c3f5d2d1e8e9553694fea0d2bb37beb2a29b9de875c8c0bd6a0c808e07575acc4290805c6f146a16ce7154487ae63877cad4f8794",
          "sha256": "f54bf6059155f299b663e4a20ea72b233cfa9b865ff2f54ce97fd48128ae5da6",
          "sha1": "e55d8278d8222f63c97a48ca68c6b2aba908bf2c",
          "md5": "8105aec096a27b6417db88cef4df88e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-a1b98b8-sources.jar",
          "url": "antibytes-dependency-node-a1b98b8-sources.jar",
          "size": 4172,
          "sha512": "a6db6d26500f71faed90771b731c6c68f72cc7e52b69e56ebd7bfcf90d724de97997c84c77a0ecefb4951086ad8b2da45412c7e249b48ebeb75d1bd4563637a0",
          "sha256": "f6976cc6a8969e57593ad2a836032d60f2f3b6d13c0bd20f431306334ec69a58",
          "sha1": "8fca775bc2abe0ef8542069dc9c8edc43f4a3ad6",
          "md5": "0d21f6fe74830a06647d04497703a2cd"
        }
      ]
    }
  ]
}
