{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "558ae36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-558ae36.jar",
          "url": "antibytes-gradle-test-utils-558ae36.jar",
          "size": 15069,
          "sha512": "605dd0f0aa0df91f7e9b1bf196a525d4911180209ffc25ae6802757bd4e4968c8af5d45f2277aa85607aaebe3981834a67cc3cabd74f1d119713fa552942bf85",
          "sha256": "7f47dbc3a4c17d9f7c62e583ff88ace53710878548ad650dfc823b291131befe",
          "sha1": "755537efbdb20b378cc2fdaaa42283f74f970873",
          "md5": "bee2af6b931dc83b9ee7e89adf5c2a81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-558ae36.jar",
          "url": "antibytes-gradle-test-utils-558ae36.jar",
          "size": 15069,
          "sha512": "605dd0f0aa0df91f7e9b1bf196a525d4911180209ffc25ae6802757bd4e4968c8af5d45f2277aa85607aaebe3981834a67cc3cabd74f1d119713fa552942bf85",
          "sha256": "7f47dbc3a4c17d9f7c62e583ff88ace53710878548ad650dfc823b291131befe",
          "sha1": "755537efbdb20b378cc2fdaaa42283f74f970873",
          "md5": "bee2af6b931dc83b9ee7e89adf5c2a81"
        }
      ]
    }
  ]
}
