{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "db3eb1b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-db3eb1b.toml",
          "url": "antibytes-dependency-catalog-db3eb1b.toml",
          "size": 248356,
          "sha512": "8af25924ddedf277174aeb18470c57611be8f209eb3ad1e2c3ccbc67039897ef9a4bde8a28c69e84222154d9f60be6ad5c51f75a4f15495519994db4ce52176c",
          "sha256": "eda2290f57a6c1f237d0d0e3d3e2019d17b0c2783d7c20e3c76b12aa533247ff",
          "sha1": "51fb2fcc8e3c24f977a536d3cfbdc6bbc15a3621",
          "md5": "313d9aa88cf65f0355cfd7fbeeed6d80"
        }
      ]
    }
  ]
}
