{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "afcad58",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-afcad58.jar",
          "url": "antibytes-dependency-node-afcad58.jar",
          "size": 21501,
          "sha512": "f58e38ca0ff713b2085e42b06ac069def9f5cd7d81b6d9562ff70dc2ac1795d8acdb7f7875fa3e624664a66a536504dbe2682b3a6b7a6958cc384ac81a390be4",
          "sha256": "779d48246c248aa87d7c69e44331c8f2dad258b24fd924ce3d1bc6676e0b87ce",
          "sha1": "0acfab06549b319c72faef1505ecfbd997ff18d2",
          "md5": "109bfb281a545a769615201ddb5efb73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-afcad58.jar",
          "url": "antibytes-dependency-node-afcad58.jar",
          "size": 21501,
          "sha512": "f58e38ca0ff713b2085e42b06ac069def9f5cd7d81b6d9562ff70dc2ac1795d8acdb7f7875fa3e624664a66a536504dbe2682b3a6b7a6958cc384ac81a390be4",
          "sha256": "779d48246c248aa87d7c69e44331c8f2dad258b24fd924ce3d1bc6676e0b87ce",
          "sha1": "0acfab06549b319c72faef1505ecfbd997ff18d2",
          "md5": "109bfb281a545a769615201ddb5efb73"
        }
      ]
    }
  ]
}
