{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "283c93a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-283c93a.jar",
          "url": "antibytes-versioning-283c93a.jar",
          "size": 24286,
          "sha512": "d0e5a699f0895304b822657e1f3a5a3772514780faac58ffad399199725259df603254a171ff53ec0ac785aa0aafc26f953cdb456fe863569580f6adce52d791",
          "sha256": "75eb7275e027491a482c8a55db9d7178fc108be911c26aa96002f1bbab4a87e7",
          "sha1": "bcf7359e934bcf9c324f35364e4bb4e2a9c70cc3",
          "md5": "ed1bd1ad425195a850d390a78972ab22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-283c93a.jar",
          "url": "antibytes-versioning-283c93a.jar",
          "size": 24286,
          "sha512": "d0e5a699f0895304b822657e1f3a5a3772514780faac58ffad399199725259df603254a171ff53ec0ac785aa0aafc26f953cdb456fe863569580f6adce52d791",
          "sha256": "75eb7275e027491a482c8a55db9d7178fc108be911c26aa96002f1bbab4a87e7",
          "sha1": "bcf7359e934bcf9c324f35364e4bb4e2a9c70cc3",
          "md5": "ed1bd1ad425195a850d390a78972ab22"
        }
      ]
    }
  ]
}
