{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/766ba9c/test-utils-annotations-junit5-766ba9c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "766ba9c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-jvm-766ba9c.jar",
          "url": "test-utils-annotations-junit5-jvm-766ba9c.jar",
          "size": 4271,
          "sha512": "d942a6079a667442ae0d4a64f011d622d342f0986008eaa3381256b80f1adb29b134173da73f78160f09686ff790bd97dc62fee824939e13981d87c871aa886b",
          "sha256": "2a80a8ff0c898d2160d81417c455ea5fca8feff211d5bd6e9678353d833f7a74",
          "sha1": "45e398214dd65647ad7a3fa17003845a4a0a82a8",
          "md5": "df6c34c29d369c54c3bffa1a292d32ff"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit5",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-jvm-766ba9c.jar",
          "url": "test-utils-annotations-junit5-jvm-766ba9c.jar",
          "size": 4271,
          "sha512": "d942a6079a667442ae0d4a64f011d622d342f0986008eaa3381256b80f1adb29b134173da73f78160f09686ff790bd97dc62fee824939e13981d87c871aa886b",
          "sha256": "2a80a8ff0c898d2160d81417c455ea5fca8feff211d5bd6e9678353d833f7a74",
          "sha1": "45e398214dd65647ad7a3fa17003845a4a0a82a8",
          "md5": "df6c34c29d369c54c3bffa1a292d32ff"
        }
      ]
    }
  ]
}
