{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "0730670",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-0730670.jar",
          "url": "antibytes-dependency-0730670.jar",
          "size": 32294,
          "sha512": "58c08f9690c607e7e98f6c09df33fbffd454b273688966427d5b9748ad79db13e8e1eb4f5cc80509fece80ce0f4970388fd6ccbe434266d6de413d07948661a0",
          "sha256": "0386826c5d365cccb83a281ca685fdcad7e8dea870c92ec94a867ef17efe6568",
          "sha1": "7e1126780249c718b2fc6e89c7abe875bd5d9639",
          "md5": "5045dc51aac5ebffcd1856eb4c8aed93"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.39.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "6.5.0.1"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.43.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "0730670"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-0730670.jar",
          "url": "antibytes-dependency-0730670.jar",
          "size": 32294,
          "sha512": "58c08f9690c607e7e98f6c09df33fbffd454b273688966427d5b9748ad79db13e8e1eb4f5cc80509fece80ce0f4970388fd6ccbe434266d6de413d07948661a0",
          "sha256": "0386826c5d365cccb83a281ca685fdcad7e8dea870c92ec94a867ef17efe6568",
          "sha1": "7e1126780249c718b2fc6e89c7abe875bd5d9639",
          "md5": "5045dc51aac5ebffcd1856eb4c8aed93"
        }
      ]
    }
  ]
}
