{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/fc88d6a/test-utils-annotations-junit4-fc88d6a.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "fc88d6a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-watchosarm32-fc88d6a.klib",
          "size": 11389,
          "sha512": "0613662ba8e9f1633b65cc77d7b76c8bef2aa1df04891c942527da1614bad3db46a70364ee707420dba4578f00cd622e175275a89829ce13877c0190c9568c7c",
          "sha256": "6184ba45842781044ac2e0bc0022731463faeda5776b4093c8890e7d88ae2052",
          "sha1": "b7009d0c94f6487ad45f99f5563e81f4344539e6",
          "md5": "d19f4b971631544df9d0dcc08262b510"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-watchosarm32-fc88d6a-metadata.jar",
          "url": "test-utils-annotations-junit4-watchosarm32-fc88d6a-metadata.jar",
          "size": 261,
          "sha512": "d55d31049bb29ff8dd44de465ef0b7a4884dca073c3eecb9b86e4f93dd6c278bd2ca4d62f36ef2cd17dc327bccb087e94f346beab653d22f5c06fcac2383712a",
          "sha256": "9064ede95c2cc80a7f3b5cdb78767a67078b5711d13b260c7e49dc40f4df2697",
          "sha1": "be7a2481d91be8d79ac78614ef9929b5a8ae94b1",
          "md5": "3a672ff0956069eb3cb311f5627143fe"
        }
      ]
    }
  ]
}
