{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "d555f79",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-d555f79.jar",
          "url": "antibytes-gradle-utils-d555f79.jar",
          "size": 9421,
          "sha512": "b93da9c83c0eb3ff1043d64149002aff9290a738f3342a0e77e5197b84f0e6b6f52f4ce587fca08a4312c6f893e137b15ce65dffa4d38a6e5bcac94f0286934c",
          "sha256": "ccd89eaf0361dec4cdd8efa630f6c2f9a2bca6b8f889e2d108d599acb0346e24",
          "sha1": "19bddf96e4ed3934052030c52c95f0c8326c9173",
          "md5": "8a0e03a93766b6ed8743a9cae2ddceb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-d555f79.jar",
          "url": "antibytes-gradle-utils-d555f79.jar",
          "size": 9421,
          "sha512": "b93da9c83c0eb3ff1043d64149002aff9290a738f3342a0e77e5197b84f0e6b6f52f4ce587fca08a4312c6f893e137b15ce65dffa4d38a6e5bcac94f0286934c",
          "sha256": "ccd89eaf0361dec4cdd8efa630f6c2f9a2bca6b8f889e2d108d599acb0346e24",
          "sha1": "19bddf96e4ed3934052030c52c95f0c8326c9173",
          "md5": "8a0e03a93766b6ed8743a9cae2ddceb6"
        }
      ]
    }
  ]
}
