{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/4f11117/test-utils-annotations-junit5-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-linuxarm32hfp-4f11117.klib",
          "size": 7104,
          "sha512": "47010dc2dc42c7a383caed706be1bb22369e068ce7e6fa2b2105d85845c31cb1838b0dae333e29c47cf6082daf43796cebd86bad50671909bf380241ce79d480",
          "sha256": "b50a8d590941589217f5ea9bab5dfe446ebeed01a9a28b4f78bcb4798d745256",
          "sha1": "343ebd0546c9bfec0e9287ebd8b12c3d5845277f",
          "md5": "734ed4ff1dabaea684695c7de0c4e9dc"
        }
      ]
    }
  ]
}
