{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/7ef26b1/test-utils-ktor-7ef26b1.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "7ef26b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-7ef26b1.jar",
          "size": 22735,
          "sha512": "de0cfb74cca59f827010a9671a6e0a8020a2842677ece65431c7c384a9848cdd81b5022c01249f738a56a8eee8a08bd3e8f854d1c30c565ea9be4b95af8c61de",
          "sha256": "e1f2c744fe851339469d4df3ad59beba55e1ff0d298cea7a7b17628f26c6ae03",
          "sha1": "4313b4ffcfc096b1da73f815b0a8b4bfffa46b0b",
          "md5": "4674fd477a8bd19d08fff1d66ed2d87a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-7ef26b1.jar",
          "size": 22735,
          "sha512": "de0cfb74cca59f827010a9671a6e0a8020a2842677ece65431c7c384a9848cdd81b5022c01249f738a56a8eee8a08bd3e8f854d1c30c565ea9be4b95af8c61de",
          "sha256": "e1f2c744fe851339469d4df3ad59beba55e1ff0d298cea7a7b17628f26c6ae03",
          "sha1": "4313b4ffcfc096b1da73f815b0a8b4bfffa46b0b",
          "md5": "4674fd477a8bd19d08fff1d66ed2d87a"
        }
      ]
    }
  ]
}
