{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "776a480",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-776a480.jar",
          "url": "kmock-processor-776a480.jar",
          "size": 40060,
          "sha512": "0f388b13cf4c42c1c9348a926ef48e4eb163ce84439032c66bba214b7f07b34a9c1bf26f77671ad0ecf88e312273e30790c8baed648cc9d55eef073b986cf54f",
          "sha256": "ec8bb0e4220d84d790444dab20f5f13a57d8e89bdc8091ad4e8bbcc7910e1305",
          "sha1": "f4a12276dda55a2ce5f4de6b7a2998cf0b265f78",
          "md5": "0cf3a5e445205a0b645677da2be35c15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "776a480"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-776a480.jar",
          "url": "kmock-processor-776a480.jar",
          "size": 40060,
          "sha512": "0f388b13cf4c42c1c9348a926ef48e4eb163ce84439032c66bba214b7f07b34a9c1bf26f77671ad0ecf88e312273e30790c8baed648cc9d55eef073b986cf54f",
          "sha256": "ec8bb0e4220d84d790444dab20f5f13a57d8e89bdc8091ad4e8bbcc7910e1305",
          "sha1": "f4a12276dda55a2ce5f4de6b7a2998cf0b265f78",
          "md5": "0cf3a5e445205a0b645677da2be35c15"
        }
      ]
    }
  ]
}
