{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "f6a864b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-f6a864b.toml",
          "url": "antibytes-dependency-catalog-f6a864b.toml",
          "size": 248153,
          "sha512": "c188f948d3375264e833248d0c40898394a2d106830c55fe563a9e93bcbe44dabbd131a965b1ae0043239b51e40385560319fc42f7e00f577a630f67253fb968",
          "sha256": "a86b22c57c4ea270738c81ed6b9e31a8d7e34b482945b229c7c86679636c9e2a",
          "sha1": "a32f297ccf3eff250d91cc2f9af4d4eebdaeb8f8",
          "md5": "3f0eed0245462cae5e1bf63cf4a16ea4"
        }
      ]
    }
  ]
}
