{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/cd6e425/kmock-cd6e425.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "cd6e425",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosx64-cd6e425.klib",
          "size": 127671,
          "sha512": "0d445d6ee78bc6e22b649e12bd852d0c1d08caa2801b295b0cf3611e6b66ea760828b56e0b3da6a0e0f654b92f007d7ad55cf6a53f88ad4fa3ab901eea55d337",
          "sha256": "a4932c1526e2d375fb3421e4d0a2037c3b3f8023933db2694f322bbca30ceeff",
          "sha1": "066011f5e4e99f5b13a4a69c4fc58398d45c5863",
          "md5": "29f240dc124033650133a920087306b9"
        }
      ]
    }
  ]
}
