{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "07928c3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-07928c3.jar",
          "url": "antibytes-coverage-07928c3.jar",
          "size": 135215,
          "sha512": "c20e1606611f415b44f7e5aba9ce752aceef5e6e3a95e729bd6f8a06ca2fd00233cb613fa10132ef38425c27d15611a4f78dcee54d0c854ffe785b448da4fe29",
          "sha256": "38fa7f0388056d485f6fbaab8c13653195dc0dfd2ad07ad9984c49ec8a8d0346",
          "sha1": "80d920f09f3847deb1d6d8e8d036acb4b74c2ad2",
          "md5": "56f1c1d5150c8a672ba3511c998437eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "07928c3"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-07928c3.jar",
          "url": "antibytes-coverage-07928c3.jar",
          "size": 135215,
          "sha512": "c20e1606611f415b44f7e5aba9ce752aceef5e6e3a95e729bd6f8a06ca2fd00233cb613fa10132ef38425c27d15611a4f78dcee54d0c854ffe785b448da4fe29",
          "sha256": "38fa7f0388056d485f6fbaab8c13653195dc0dfd2ad07ad9984c49ec8a8d0346",
          "sha1": "80d920f09f3847deb1d6d8e8d036acb4b74c2ad2",
          "md5": "56f1c1d5150c8a672ba3511c998437eb"
        }
      ]
    }
  ]
}
