{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/dbba7bb/test-utils-ktor-dbba7bb.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "dbba7bb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-watchosarm32-dbba7bb.klib",
          "size": 15061,
          "sha512": "f42f114a4914b37d5544b7f07a04c4cee20f777f282e15ec3fd99437499ab7b1610722dcd1300df51ef6eaa8b9c392b2dabf2c04752b54ec52384b1634bfdcf4",
          "sha256": "253bc5aaeb7baee4c614705093fc31d95688a1acaa7c5783168837da1ed22827",
          "sha1": "dd8b9fec67d16fe5bf74e63bfd5aaf4f4a90659a",
          "md5": "4a9df491df76e2f0849c508500fa2273"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-watchosarm32-dbba7bb-metadata.jar",
          "url": "test-utils-ktor-watchosarm32-dbba7bb-metadata.jar",
          "size": 261,
          "sha512": "faea3569e42d2d1e332cbc0e93b926b51882fbab86ac64b0c294ab9ac4d48584fe82697f26788a9c506a7af77e244ef57585b39f6c57b0a47ea1424db8785d51",
          "sha256": "b6c5f7af5a8474b38b46cdbe8976fedca51fd440290bfd9ff357bf203200cc06",
          "sha1": "742f79b5eb7455d3d0477995cabe8b139f4aa6f7",
          "md5": "d37f0aec0d5a0b10711a044decf9b74f"
        }
      ]
    }
  ]
}
