{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "1f0d712",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-1f0d712.jar",
          "url": "antibytes-gradle-utils-1f0d712.jar",
          "size": 9568,
          "sha512": "5fa1118ee91d1c4101e9371f8a08b18c8746e6d0f2901279fed1490c870b32c8e5bd368246025b692d9c7641cc28a26d366440a6ed21dfb988a30c8d9c31d8bb",
          "sha256": "f278a6fc1660f3240ed68ff575f2213cf1a2f66be39fd74eb4bc03c347687581",
          "sha1": "0313e361169be8f30eb31d9bf0a34170400c2986",
          "md5": "80e1488c6b562bf9e1232ec7d0f48606"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-1f0d712.jar",
          "url": "antibytes-gradle-utils-1f0d712.jar",
          "size": 9568,
          "sha512": "5fa1118ee91d1c4101e9371f8a08b18c8746e6d0f2901279fed1490c870b32c8e5bd368246025b692d9c7641cc28a26d366440a6ed21dfb988a30c8d9c31d8bb",
          "sha256": "f278a6fc1660f3240ed68ff575f2213cf1a2f66be39fd74eb4bc03c347687581",
          "sha1": "0313e361169be8f30eb31d9bf0a34170400c2986",
          "md5": "80e1488c6b562bf9e1232ec7d0f48606"
        }
      ]
    }
  ]
}
