{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.settings",
    "module": "antibytes-dependency-settings",
    "version": "5b4a923",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "5b4a923"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-5b4a923.jar",
          "url": "antibytes-dependency-settings-5b4a923.jar",
          "size": 17996,
          "sha512": "436b0d5301c08dce77f49b61da3c40060a29891268da7f7294ea480bfaceb0171dc98b8c6537b2ea21787bd30613a75e8224e6cc093284ebf6761c0f804b3b7e",
          "sha256": "35bafe9f1a3a219ea519c72cdac250d61d66e57f6c47f8d63e61282109eb157a",
          "sha1": "984d1e09262c4f61842a2f41105aae6e0b5d8313",
          "md5": "0b4f0ad0d6fa8a714b122966bfa7f5d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains",
          "module": "foojay-resolver",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "5b4a923"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-5b4a923.jar",
          "url": "antibytes-dependency-settings-5b4a923.jar",
          "size": 17996,
          "sha512": "436b0d5301c08dce77f49b61da3c40060a29891268da7f7294ea480bfaceb0171dc98b8c6537b2ea21787bd30613a75e8224e6cc093284ebf6761c0f804b3b7e",
          "sha256": "35bafe9f1a3a219ea519c72cdac250d61d66e57f6c47f8d63e61282109eb157a",
          "sha1": "984d1e09262c4f61842a2f41105aae6e0b5d8313",
          "md5": "0b4f0ad0d6fa8a714b122966bfa7f5d4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-settings-5b4a923-javadoc.jar",
          "url": "antibytes-dependency-settings-5b4a923-javadoc.jar",
          "size": 261,
          "sha512": "6b0844b5936ce3d35856ec056b5ea8ef53bf37d3f14f2ecbc014c63ae03c90993f21f7a8b3172d46a8ebd859cdef1c5b845cf4fbbdb11fb79a65a1ccbcee5bbf",
          "sha256": "d7da5f1635b624fa894f2f746066cd6ab71eda4c8f95954e12082544854d4fc4",
          "sha1": "61a6ae3008fca2f842e9e5d5375653415f6f7c09",
          "md5": "c0b21cf68ccf32712c4298e58c0547cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-settings-5b4a923-sources.jar",
          "url": "antibytes-dependency-settings-5b4a923-sources.jar",
          "size": 3876,
          "sha512": "785371c69470c3ab146aaa3d74ccae11586659ce14c355a12293e9f2f365e105d8925a0ba7b3c1e7ad1d8ea246c915fc533fbcf799015a20e36faa7782941dfa",
          "sha256": "b28e656b0a4938a77881b2db76acc77fefb5af33f2590a06d54fa1a406ddeac7",
          "sha1": "c8d16ee7399bac7ba3d1de509723d61b1761691d",
          "md5": "e3245c5943931f1c5c4544683206ca2d"
        }
      ]
    }
  ]
}
