{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/a7a030d/test-utils-annotations-a7a030d.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "a7a030d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-release.aar",
          "url": "test-utils-annotations-android-a7a030d.aar",
          "size": 4057,
          "sha512": "88db17c9ab499edfaed85b4cf9461ba152c06b8b06c70d351b8b1639716432d01494d1d24315f7567b357075315dc18dd34080853f88f14e8b83beaaa91c6ed0",
          "sha256": "466279876421fbb1843bb3160fb0e573c2fa3c21c13c7aa97ac1c04ef067f5e7",
          "sha1": "6d239d1cf36b85f76f668f04693ce9f85a1c47ae",
          "md5": "0abfcc0d83524b61184b3a4be49c8273"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-release.aar",
          "url": "test-utils-annotations-android-a7a030d.aar",
          "size": 4057,
          "sha512": "88db17c9ab499edfaed85b4cf9461ba152c06b8b06c70d351b8b1639716432d01494d1d24315f7567b357075315dc18dd34080853f88f14e8b83beaaa91c6ed0",
          "sha256": "466279876421fbb1843bb3160fb0e573c2fa3c21c13c7aa97ac1c04ef067f5e7",
          "sha1": "6d239d1cf36b85f76f668f04693ce9f85a1c47ae",
          "md5": "0abfcc0d83524b61184b3a4be49c8273"
        }
      ]
    }
  ]
}
