{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "65d8995",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-65d8995.jar",
          "url": "antibytes-gradle-test-utils-65d8995.jar",
          "size": 17226,
          "sha512": "10a07579fbd57f59fb9f2681d6051f7a16d32411fce49b9445dfca30f72113b5377d0b3306e65ce72df604845cefc48b1cbda82113c0eefe9677d38568eb8f18",
          "sha256": "615fb21923b7b04e0e9557adb5552b8d6f8887addbb259047f15392a698197e1",
          "sha1": "ae44d6deeeb94807a07e5fa5e25ba9e416adb64f",
          "md5": "ce8f1911bb8eb69b2aa47120690ed25f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-65d8995.jar",
          "url": "antibytes-gradle-test-utils-65d8995.jar",
          "size": 17226,
          "sha512": "10a07579fbd57f59fb9f2681d6051f7a16d32411fce49b9445dfca30f72113b5377d0b3306e65ce72df604845cefc48b1cbda82113c0eefe9677d38568eb8f18",
          "sha256": "615fb21923b7b04e0e9557adb5552b8d6f8887addbb259047f15392a698197e1",
          "sha1": "ae44d6deeeb94807a07e5fa5e25ba9e416adb64f",
          "md5": "ce8f1911bb8eb69b2aa47120690ed25f"
        }
      ]
    }
  ]
}
