{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/8066bd0/test-utils-resourceloader-8066bd0.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "8066bd0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iosx64-8066bd0.klib",
          "size": 12849,
          "sha512": "b05d419daa737638e1a68389db45e60bea41be3040a340ff709c504009a3e5ec8c8be71a2b276b3138d910f6f6f7f282daed519f0d7ccd55e01886495d2eb310",
          "sha256": "3c611a4912536b6a5fd7316d6a18b4fd7713a78c6c2c4cebe3d2a73d8d0d005f",
          "sha1": "fc5acdc5e365bcf321e84682b21068d4a0b8cd53",
          "md5": "c294d934ca5be70f140b4cd78fcc592f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iosx64-8066bd0-metadata.jar",
          "url": "test-utils-resourceloader-iosx64-8066bd0-metadata.jar",
          "size": 261,
          "sha512": "e7b7370085b4fbe00a7b47362876be8ad6b31e4aeb42776e7bb777db2672bd4a2a651d8a05058cbc0a57b10bbb2087fcbb5c6f4282348ef41d6aded6dca56351",
          "sha256": "36525493bc7b2baf8291c01be0148a09277cc1f94254e414169d2444715e4a2f",
          "sha1": "0c48cff9a2ee8e085e003ab824ddd12bb0945f85",
          "md5": "12ad01c1c7bad39e7a2dd1c98d37b9a0"
        }
      ]
    }
  ]
}
