{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.dokka",
    "module": "antibytes-dokka-configuration",
    "version": "fcf90ae",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dokka-configuration-fcf90ae.jar",
          "url": "antibytes-dokka-configuration-fcf90ae.jar",
          "size": 8108,
          "sha512": "7e35fbdb5bed357fc4a013a03ce783b274965fde84b3e644c2eb06fb79ca6161ec2f87af42d27a32d16e4c761c2834957408ab1c16e262ae0871d7cd7b4cc338",
          "sha256": "7721424cafb135f1f123effb131402075e4b4081e4395c0c7225167ad2cc3c85",
          "sha1": "42662e2e88d44c7edd1254b1205710570fc6e27b",
          "md5": "cf895cc1099c2158e418f943062171f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "fcf90ae"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dokka-configuration-fcf90ae.jar",
          "url": "antibytes-dokka-configuration-fcf90ae.jar",
          "size": 8108,
          "sha512": "7e35fbdb5bed357fc4a013a03ce783b274965fde84b3e644c2eb06fb79ca6161ec2f87af42d27a32d16e4c761c2834957408ab1c16e262ae0871d7cd7b4cc338",
          "sha256": "7721424cafb135f1f123effb131402075e4b4081e4395c0c7225167ad2cc3c85",
          "sha1": "42662e2e88d44c7edd1254b1205710570fc6e27b",
          "md5": "cf895cc1099c2158e418f943062171f1"
        }
      ]
    }
  ]
}
