{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/2395d28/test-utils-fixture-2395d28.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "2395d28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm.jar",
          "url": "test-utils-fixture-jvm-2395d28.jar",
          "size": 41804,
          "sha512": "27899bb3bd542139dc57a530c4a2bafe776a91c79042ed9ec96953ddbee3ba60e8261cb582cb8b1d28dbaa7f5095f4bca9611766442cc463f77ba91230195a02",
          "sha256": "8ccb244277ddb7c7acda5e403934c533e159e9bb06aa6540f9ec9d732290f9af",
          "sha1": "e5f37e319dca4f46f70bc972f24f790743ae77ce",
          "md5": "d5908cb709c90ebccfb00a136a572a9d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm.jar",
          "url": "test-utils-fixture-jvm-2395d28.jar",
          "size": 41804,
          "sha512": "27899bb3bd542139dc57a530c4a2bafe776a91c79042ed9ec96953ddbee3ba60e8261cb582cb8b1d28dbaa7f5095f4bca9611766442cc463f77ba91230195a02",
          "sha256": "8ccb244277ddb7c7acda5e403934c533e159e9bb06aa6540f9ec9d732290f9af",
          "sha1": "e5f37e319dca4f46f70bc972f24f790743ae77ce",
          "md5": "d5908cb709c90ebccfb00a136a572a9d"
        }
      ]
    }
  ]
}
