{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.coverage",
    "module": "antibytes-coverage",
    "version": "bf5cf3e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-bf5cf3e.jar",
          "url": "antibytes-coverage-bf5cf3e.jar",
          "size": 146046,
          "sha512": "6d21097b078504503870536ef2363c69cb5a279c5a035a397467654c8c3310d42f0c04e91122e36fe8509280daff510ae45ba8fc5ef6261601fd9b431e7ce1da",
          "sha256": "4203352521aac6a8363f99034801d81f240e4176796e4a5fa5521fa36d51d2c9",
          "sha1": "c24521e9d1008e52e4ff9e44fe06f626a339c53f",
          "md5": "2226f99cd19e08540770188a0fe7f02d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "bf5cf3e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-bf5cf3e.jar",
          "url": "antibytes-coverage-bf5cf3e.jar",
          "size": 146046,
          "sha512": "6d21097b078504503870536ef2363c69cb5a279c5a035a397467654c8c3310d42f0c04e91122e36fe8509280daff510ae45ba8fc5ef6261601fd9b431e7ce1da",
          "sha256": "4203352521aac6a8363f99034801d81f240e4176796e4a5fa5521fa36d51d2c9",
          "sha1": "c24521e9d1008e52e4ff9e44fe06f626a339c53f",
          "md5": "2226f99cd19e08540770188a0fe7f02d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-coverage-bf5cf3e-javadoc.jar",
          "url": "antibytes-coverage-bf5cf3e-javadoc.jar",
          "size": 261,
          "sha512": "c0544e5ec9a7ea9844ae0d7b6d15313c07707155ffdd426bf8ac0de8f019ba10d8e427ba0bac4b61b22d2884058f3776efbe4a7a85219ab6d5e9f8a4b08c0707",
          "sha256": "5ec3f1e2409f14cb7e017e34c6647876b9e42951313be9b330a75bf8838e4eb1",
          "sha1": "59d9c3ab8c1606a689320b627c9298361b90c6f6",
          "md5": "b351f6f5ef167b08e7305250e24700b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-coverage-bf5cf3e-sources.jar",
          "url": "antibytes-coverage-bf5cf3e-sources.jar",
          "size": 27853,
          "sha512": "a2a2d4fd4677930213566fa8cc2d3fabcc34582283c838efe24122a9f7aa738e12085b0b244232d4b36e1e06b992ceccea3aeb78b512bfcfbf385caa0197b351",
          "sha256": "abf28ff58f8bd30ba98ff119e17fcf75da5452a6a07a60d9cc0ae4ae14630137",
          "sha1": "c4080115f426491d2e458f163ab82cf5e0a93aa4",
          "md5": "8d32550991747947c01136e599a9d0fe"
        }
      ]
    }
  ]
}
