{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-0.1.1-SNAPSHOT.aar",
          "size": 294755,
          "sha512": "47c7d10ebdc312a149eccbe545fb631c7cd3806954143e80f3dd1d21709d17db75fd54f88d72057e0ec6547e792b8f9e08105c0e43f633a581e0e5f22e012e5e",
          "sha256": "d64be92bd85c959077d6e6a08a4bd3da8937157e2b8c31806305d38d31d679f0",
          "sha1": "2573b1347472f8a00de97418c89c672c5c3b2fa4",
          "md5": "a6f49d3914fff6ba161a3d9785298a00"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-0.1.1-SNAPSHOT.aar",
          "size": 294755,
          "sha512": "47c7d10ebdc312a149eccbe545fb631c7cd3806954143e80f3dd1d21709d17db75fd54f88d72057e0ec6547e792b8f9e08105c0e43f633a581e0e5f22e012e5e",
          "sha256": "d64be92bd85c959077d6e6a08a4bd3da8937157e2b8c31806305d38d31d679f0",
          "sha1": "2573b1347472f8a00de97418c89c672c5c3b2fa4",
          "md5": "a6f49d3914fff6ba161a3d9785298a00"
        }
      ]
    }
  ]
}
