{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-0.1.1-SNAPSHOT.aar",
          "size": 342254,
          "sha512": "f0b7694c5a04d5bd8721d94779a0bdff3b17740c37982277edc63deacf451bd85aef873d5559489fbb1a73e67071457f6a8a007535f727b83112751d0e4fa164",
          "sha256": "9fecf226613876339c573d2a24b23ffc845916df80c6ad2213e78b9c77682bd8",
          "sha1": "124beffa84adb494fab22161906aa487e2c60c5f",
          "md5": "7c2fe345ead835145caa65984ad01691"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-0.1.1-SNAPSHOT.aar",
          "size": 342254,
          "sha512": "f0b7694c5a04d5bd8721d94779a0bdff3b17740c37982277edc63deacf451bd85aef873d5559489fbb1a73e67071457f6a8a007535f727b83112751d0e4fa164",
          "sha256": "9fecf226613876339c573d2a24b23ffc845916df80c6ad2213e78b9c77682bd8",
          "sha1": "124beffa84adb494fab22161906aa487e2c60c5f",
          "md5": "7c2fe345ead835145caa65984ad01691"
        }
      ]
    }
  ]
}
