{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-0.1.1-SNAPSHOT.aar",
          "size": 342343,
          "sha512": "d3bcd86e7ddfd0a98f270a4c54222b8a48024060027a378734ddb691029f0e9ae20bd64ef9504ee781b9004cd8b4021a94710bf672b81c1ee75574cc0aacc71d",
          "sha256": "af075272d4d772733976fa7795a9ff3c483077eda9580ab19aa196d71eb913e7",
          "sha1": "f39445bae208d659b954a93e73dfdc4ce699e6eb",
          "md5": "5a86645a58d15fffe40e3664adfd900d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-0.1.1-SNAPSHOT.aar",
          "size": 342343,
          "sha512": "d3bcd86e7ddfd0a98f270a4c54222b8a48024060027a378734ddb691029f0e9ae20bd64ef9504ee781b9004cd8b4021a94710bf672b81c1ee75574cc0aacc71d",
          "sha256": "af075272d4d772733976fa7795a9ff3c483077eda9580ab19aa196d71eb913e7",
          "sha1": "f39445bae208d659b954a93e73dfdc4ce699e6eb",
          "md5": "5a86645a58d15fffe40e3664adfd900d"
        }
      ]
    }
  ]
}
