{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-0.1.1-SNAPSHOT.aar",
          "size": 295478,
          "sha512": "9135eb2162a4f710ddeac1ef8397ed4fb07ff9015b38da8a8ec579daf51c4981e2af15f4ce3c4646c6e11639c9237e9b00a1b7a67cfc9a9d87f7ab5f669d2fbd",
          "sha256": "28fc18126007cdcda3166d7d3aa5faa93dfe388831fa4526a7bc0cc7acc08434",
          "sha1": "4d465263317c67df74cea6f8091d851222576f6a",
          "md5": "168bd06b6775c3f43fd0b3294370baf1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-0.1.1-SNAPSHOT.aar",
          "size": 295478,
          "sha512": "9135eb2162a4f710ddeac1ef8397ed4fb07ff9015b38da8a8ec579daf51c4981e2af15f4ce3c4646c6e11639c9237e9b00a1b7a67cfc9a9d87f7ab5f669d2fbd",
          "sha256": "28fc18126007cdcda3166d7d3aa5faa93dfe388831fa4526a7bc0cc7acc08434",
          "sha1": "4d465263317c67df74cea6f8091d851222576f6a",
          "md5": "168bd06b6775c3f43fd0b3294370baf1"
        }
      ]
    }
  ]
}
