{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/8066bd0/test-utils-annotations-junit5-8066bd0.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "8066bd0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-watchosx64-8066bd0.klib",
          "size": 7069,
          "sha512": "d1d1117c451c6786d37528b8a21cefd98abee62c2eb31e1fe4a60270713fceb50ff4f5815f30d42a3d9becbc956dc683bca142214c5755e3bdc4d738d05b443f",
          "sha256": "672d9b11beb19e1233df5088963e759ab93d97ab004a4e1dd483961f5feba247",
          "sha1": "05f3b5b614824e3a2eb67a5f7d7b89662d267b63",
          "md5": "a45c9569803132ede8e6cc99b8f05a39"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-watchosx64-8066bd0-metadata.jar",
          "url": "test-utils-annotations-junit5-watchosx64-8066bd0-metadata.jar",
          "size": 261,
          "sha512": "7d37082d3aa4f61d260ca9907806820dbb86b378834face3cdc00cec11e6edd64717592453a66feb70262e6819c65c968d2ab69c646f2638751a099bb842e025",
          "sha256": "834320eebad91429a62ca8e82437ca90b30cf56ecf193f69fbde2923cabce6d3",
          "sha1": "a179c173c972cc15a682ea4deda79a07c531941a",
          "md5": "b1874a99cf6f73330f5cd0f3ea3201ef"
        }
      ]
    }
  ]
}
