{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/b6c6e6c/test-utils-b6c6e6c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "b6c6e6c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm64-b6c6e6c.klib",
          "size": 8343,
          "sha512": "21a8a1d3ee0e741477e780379cc0538cf7e470bf4df289c99a3f3726e7251cdd1006e0ba9ce029c74a6cf401824b415e2a0b46bbb23db1a80e06376917bf7dfd",
          "sha256": "f02d65a57988f71be514d33f36e5e5b511c1eebfe025ea3035f0c5f6336f11fd",
          "sha1": "260e02db29e37b9ed8984cb4dec7b41043c56e30",
          "md5": "6d4db9e3f4a58fb4f7916b5189f02be8"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-iosarm64-b6c6e6c-sources.jar",
          "url": "test-utils-iosarm64-b6c6e6c-sources.jar",
          "size": 2202,
          "sha512": "200f256b59ba175210138bed146ee54ab58c9bb91f071774698eb6b3f4920f792214d2d44a1cc764422cb2c09da1a0773d4d288080e067e60263b96f2ed68050",
          "sha256": "9e0bd104bc203c511c12aaf2143514ee32a59c775ece92a04e7ee764ee60affa",
          "sha1": "773bcb344a1f6fd820f6ee6e62aea2b59ecfa180",
          "md5": "8b3c7f259a640a3d1e2ffd34b7f29645"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm64-b6c6e6c-metadata.jar",
          "url": "test-utils-iosarm64-b6c6e6c-metadata.jar",
          "size": 261,
          "sha512": "9f565189cbc24ca62b268d9212dc787ff610c3b828a0896adbd5cf3dbdebbd2c946fdc91a9e1495b990114d091638d360649dd0c6824d26fbfdecc6f75497f33",
          "sha256": "9e80cf2b1e535bc393e6cab7e5517f61c2db438b864383d0dd8adbc3b569bfc9",
          "sha1": "47357ed033fdb5347c1a4eb845de7af9dd10d326",
          "md5": "58d88a5a0688bd09e2b7d56d045284f9"
        }
      ]
    }
  ]
}
