{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/f384302/test-utils-ktor-f384302.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "f384302",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iossimulatorarm64-f384302.klib",
          "size": 15112,
          "sha512": "f6806f23abd2aa4b59e085a314019581c11a0261c20c1c72efcc189d6e717907ba9b0a368f76813b329bba41404de8f1297be6f879ff788754a6811b99cb181e",
          "sha256": "7864dbddda6682a12e2792d772d1dfc7fe0c401877f4be31cd7772779b5a7e88",
          "sha1": "d91df1894222c777a76efd4e94a09639bd32f957",
          "md5": "a66e376179d5e04d270847e48eba3bcb"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iossimulatorarm64-f384302-metadata.jar",
          "url": "test-utils-ktor-iossimulatorarm64-f384302-metadata.jar",
          "size": 261,
          "sha512": "4ae0e6f81b2e2b75dd1fcdd3d8c35c47b13cc0118504b532a9e13a0461b47884e61b3b1c1fb143989917813efc21423c7b80ee0645ec92f82be04fcf725818a5",
          "sha256": "d1b6dc3112ec7a64e715662f9f9c36d4f03b7ed46117f125ef99c79698d8647e",
          "sha1": "d32f4e45db606e5e11377063a1764da06c7e6a7c",
          "md5": "63fad3194d9e130c9bfb32b7ed5e5866"
        }
      ]
    }
  ]
}
