{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "a9d047f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-a9d047f.jar",
          "url": "antibytes-dependency-node-a9d047f.jar",
          "size": 21473,
          "sha512": "ff45932d6a3b0dff41b42d3621d0ab66f2bec1d519035b978b2b1c2f95adc033fddf088bfcd1692c535e5a090aebaf6f75001a8841620e9fb641404810c907c9",
          "sha256": "854c15763621cb5582a04e139f37911f01db3ca0c9988ba42a52d9e29f33bc10",
          "sha1": "76ccf1357dab2ad502c644c88cec95c8f73c7b56",
          "md5": "c4b19709c3528f1f034bf325fbec4945"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-a9d047f.jar",
          "url": "antibytes-dependency-node-a9d047f.jar",
          "size": 21473,
          "sha512": "ff45932d6a3b0dff41b42d3621d0ab66f2bec1d519035b978b2b1c2f95adc033fddf088bfcd1692c535e5a090aebaf6f75001a8841620e9fb641404810c907c9",
          "sha256": "854c15763621cb5582a04e139f37911f01db3ca0c9988ba42a52d9e29f33bc10",
          "sha1": "76ccf1357dab2ad502c644c88cec95c8f73c7b56",
          "md5": "c4b19709c3528f1f034bf325fbec4945"
        }
      ]
    }
  ]
}
