{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.3.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc01-SNAPSHOT.jar",
          "url": "kmock-processor-0.3.0-rc01-SNAPSHOT.jar",
          "size": 384124,
          "sha512": "55d51b0ef3fb99d4f2fc26d94cc77b0f496ec25798a7db9359e29aad0863871ba3848826aa76967f6339da682bd334ace042a78396053611eaed10c4841956be",
          "sha256": "6a93592805382bf09246b9550285b2532e265ff844ce2e3c88eb33ec3e3bd5cf",
          "sha1": "86734803ed24cbae8e382409ee5c92f91db510ae",
          "md5": "85177be5280f2afe4a0b12338e4ad6e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.21-1.0.6"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.3.0-rc01-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc01-SNAPSHOT.jar",
          "url": "kmock-processor-0.3.0-rc01-SNAPSHOT.jar",
          "size": 384124,
          "sha512": "55d51b0ef3fb99d4f2fc26d94cc77b0f496ec25798a7db9359e29aad0863871ba3848826aa76967f6339da682bd334ace042a78396053611eaed10c4841956be",
          "sha256": "6a93592805382bf09246b9550285b2532e265ff844ce2e3c88eb33ec3e3bd5cf",
          "sha1": "86734803ed24cbae8e382409ee5c92f91db510ae",
          "md5": "85177be5280f2afe4a0b12338e4ad6e2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc01-SNAPSHOT-javadoc.jar",
          "url": "kmock-processor-0.3.0-rc01-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "276dae50f031e974b5f1a637a269a2ed1eb673aa658f1cdb41bb30f7584907733b21581508214184db6f89bb678f5942d729abca7803f68b63341b54f623951a",
          "sha256": "e41b0b1bb12e5306f571259a5720d7aa3db81286976ab0c5b21c4792d48185a8",
          "sha1": "26b927f6e38e3110b1f81264ab2754e32beafad8",
          "md5": "00912e2a4948ed778d7c5ac4448ead34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc01-SNAPSHOT-sources.jar",
          "url": "kmock-processor-0.3.0-rc01-SNAPSHOT-sources.jar",
          "size": 80445,
          "sha512": "4855c29eee174fae9ba9b8f9f6c554cc7a79745f1a3724bff7c590ae72ab66c38cb86d819eee367555624323a4af20e411e41771d03c3ee47b2db17e88816b5d",
          "sha256": "d6322b8a7484699981b9162ffcb5ca52d4fb2a4dc3f8cc896ca13b316f970276",
          "sha1": "7e74822d8b4f975dc675d5ea0c33ce26075b87a3",
          "md5": "199d2564d4bd2249b68c58d8c16b6af0"
        }
      ]
    }
  ]
}
