{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.3.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc01-SNAPSHOT.jar",
          "url": "kmock-processor-0.3.0-rc01-SNAPSHOT.jar",
          "size": 384124,
          "sha512": "84c00c38137bfa124f66358a670fb2746a2238ff666a1f0ef3e31e3004435424e6044edc1a858b989c2e81dbda9312987b7ba83646a80c0d2fa3c49709afd9b9",
          "sha256": "170a7065aba2191ee034afdc94e9315c1055b095f31df13e9414379277da2509",
          "sha1": "3b3f9a9c1beeaa04506ffd4bd53bc71b53b880c4",
          "md5": "87e4eca6547b9ca4a8bab29517eac75c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.21-1.0.6"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.3.0-rc01-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc01-SNAPSHOT.jar",
          "url": "kmock-processor-0.3.0-rc01-SNAPSHOT.jar",
          "size": 384124,
          "sha512": "84c00c38137bfa124f66358a670fb2746a2238ff666a1f0ef3e31e3004435424e6044edc1a858b989c2e81dbda9312987b7ba83646a80c0d2fa3c49709afd9b9",
          "sha256": "170a7065aba2191ee034afdc94e9315c1055b095f31df13e9414379277da2509",
          "sha1": "3b3f9a9c1beeaa04506ffd4bd53bc71b53b880c4",
          "md5": "87e4eca6547b9ca4a8bab29517eac75c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc01-SNAPSHOT-javadoc.jar",
          "url": "kmock-processor-0.3.0-rc01-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "32c0f4bc407d1be624fa2ea63bd095134f59c485f65dcf153d5c486669a8db8b68a5c2ce55422ed39cd67c9045a0fb1fde51da178045b6d13f3af908ec238377",
          "sha256": "fb0bc30920daf39e128d88d617287c11dd7160695c4181404ce897a18e71cf26",
          "sha1": "249eb41f27596ddb33f3b9aaac9a9001af6a4f42",
          "md5": "d08cadb6ef3717544e3567ceecbd38f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc01-SNAPSHOT-sources.jar",
          "url": "kmock-processor-0.3.0-rc01-SNAPSHOT-sources.jar",
          "size": 80445,
          "sha512": "a9fef9d1363ccad53d9de5db9813255b706828ac7e06e2fc33cf3c3380a660e799976c224a6e7ba5118236c199665989953e68ff205f19becccf91f3cb8f4761",
          "sha256": "d89110ee067fb81a43ac87c62b2980137de654685985ac1731081cdcafbc2f36",
          "sha1": "38f7d48bf10be6a1646c0c8ecb5b9a0f97aad642",
          "md5": "e037af05d106784f4913c3f25014c11b"
        }
      ]
    }
  ]
}
