{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/d135d93/kmock-d135d93.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "d135d93",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-d135d93.jar",
          "url": "kmock-jvm-d135d93.jar",
          "size": 255257,
          "sha512": "69b1118ab4f698ea135b4acd6f0a036bb0d09291f4c3bae204929ccc8a3bfbe7791e4f3ab72d61600ef6456d14e1547c9591886b59c041690125e28e0d1f6341",
          "sha256": "83c7bffe06648886b34cdc4df0d7081d54546fe0af3a61b0d0a05f20b01d15d9",
          "sha1": "a68d1357fa49fed0ecffa7be47fcd97b1cf3fc44",
          "md5": "9d1f300d550d844d5b04ae6763a430e3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-d135d93.jar",
          "url": "kmock-jvm-d135d93.jar",
          "size": 255257,
          "sha512": "69b1118ab4f698ea135b4acd6f0a036bb0d09291f4c3bae204929ccc8a3bfbe7791e4f3ab72d61600ef6456d14e1547c9591886b59c041690125e28e0d1f6341",
          "sha256": "83c7bffe06648886b34cdc4df0d7081d54546fe0af3a61b0d0a05f20b01d15d9",
          "sha1": "a68d1357fa49fed0ecffa7be47fcd97b1cf3fc44",
          "md5": "9d1f300d550d844d5b04ae6763a430e3"
        }
      ]
    }
  ]
}
