{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/0a42b71/test-utils-0a42b71.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "0a42b71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-0a42b71.klib",
          "url": "test-utils-js-0a42b71.klib",
          "size": 11900,
          "sha512": "f85c5107fff9c02db7e7566ea28f13eabbf77de2d0e96deeada49fc70b79170c6961c55d0fc4c08001b82c29269f6110f30f171eb77d65915fa37c98d41a9d6c",
          "sha256": "653287df738b40af85a2df17c42f8357394558e9132092e7b4863cd261c80c28",
          "sha1": "09aefd4f8b0861e739465e7a1a736a37e6a32f06",
          "md5": "251ebc8f03a0e20fb186366aab94968a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-0a42b71.klib",
          "url": "test-utils-js-0a42b71.klib",
          "size": 11900,
          "sha512": "f85c5107fff9c02db7e7566ea28f13eabbf77de2d0e96deeada49fc70b79170c6961c55d0fc4c08001b82c29269f6110f30f171eb77d65915fa37c98d41a9d6c",
          "sha256": "653287df738b40af85a2df17c42f8357394558e9132092e7b4863cd261c80c28",
          "sha1": "09aefd4f8b0861e739465e7a1a736a37e6a32f06",
          "md5": "251ebc8f03a0e20fb186366aab94968a"
        }
      ]
    }
  ]
}
