{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "42d3d0a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-42d3d0a.jar",
          "url": "antibytes-grammar-tools-42d3d0a.jar",
          "size": 39371,
          "sha512": "f5dd0ab725a4f16811e41eae02bfa6b2b11d1e2e730d3c0083afc63138a62134fa4b3cb905cb695ef1c99a98bf8d29e68c17f4800b8f6cefd0a854c5b865fa28",
          "sha256": "6234d7335fc487e8808490bad3f40570a8a2bed4074960615fad491f0d928216",
          "sha1": "4fc07b02ba58f745972f686fed27bee9ebb7d91c",
          "md5": "354da81b999525c2350b57ae7a61ed17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-42d3d0a.jar",
          "url": "antibytes-grammar-tools-42d3d0a.jar",
          "size": 39371,
          "sha512": "f5dd0ab725a4f16811e41eae02bfa6b2b11d1e2e730d3c0083afc63138a62134fa4b3cb905cb695ef1c99a98bf8d29e68c17f4800b8f6cefd0a854c5b865fa28",
          "sha256": "6234d7335fc487e8808490bad3f40570a8a2bed4074960615fad491f0d928216",
          "sha1": "4fc07b02ba58f745972f686fed27bee9ebb7d91c",
          "md5": "354da81b999525c2350b57ae7a61ed17"
        }
      ]
    }
  ]
}
