{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/4f11117/test-utils-annotations-junit5-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-js-4f11117.klib",
          "url": "test-utils-annotations-junit5-js-4f11117.klib",
          "size": 4798,
          "sha512": "385d1033753a2e3014fc9cece3aa3f030855d9fde38b8cb2af9161b67dbe00d89df61c232c3427e60ed860693346583d572b926a1b434726813fc74165bd3cc4",
          "sha256": "ee62bab5bcdd6d103d261ce998e2132efdc501da72a812cda58399cb09bd1c2d",
          "sha1": "9691eb24e7c74673a596daf73f3a4fd8008554bd",
          "md5": "15fdc88dcbc62004715647ac269facf1"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-js-4f11117.klib",
          "url": "test-utils-annotations-junit5-js-4f11117.klib",
          "size": 4798,
          "sha512": "385d1033753a2e3014fc9cece3aa3f030855d9fde38b8cb2af9161b67dbe00d89df61c232c3427e60ed860693346583d572b926a1b434726813fc74165bd3cc4",
          "sha256": "ee62bab5bcdd6d103d261ce998e2132efdc501da72a812cda58399cb09bd1c2d",
          "sha1": "9691eb24e7c74673a596daf73f3a4fd8008554bd",
          "md5": "15fdc88dcbc62004715647ac269facf1"
        }
      ]
    }
  ]
}
