{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.dokka",
    "module": "antibytes-dokka-configuration",
    "version": "314bef8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dokka-configuration-314bef8.jar",
          "url": "antibytes-dokka-configuration-314bef8.jar",
          "size": 8108,
          "sha512": "113ca273905fb7a0888fb813538763fb84d7cbbb7030a12eb04836d303c9d91c20a537368fe0b07bf338f02d6e71c4f9cd439fd28904558841894d1f1d8cbad4",
          "sha256": "089a4ddbb2c7a9714fa7a73a9828a5019cf2b85d17c675d887346cf5120354ee",
          "sha1": "84c42ebe0857718d939d0f6cf3e50c512cb01fd6",
          "md5": "35a5d8ba1f701238700e7d7c08933a89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "314bef8"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dokka-configuration-314bef8.jar",
          "url": "antibytes-dokka-configuration-314bef8.jar",
          "size": 8108,
          "sha512": "113ca273905fb7a0888fb813538763fb84d7cbbb7030a12eb04836d303c9d91c20a537368fe0b07bf338f02d6e71c4f9cd439fd28904558841894d1f1d8cbad4",
          "sha256": "089a4ddbb2c7a9714fa7a73a9828a5019cf2b85d17c675d887346cf5120354ee",
          "sha1": "84c42ebe0857718d939d0f6cf3e50c512cb01fd6",
          "md5": "35a5d8ba1f701238700e7d7c08933a89"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dokka-configuration-314bef8-javadoc.jar",
          "url": "antibytes-dokka-configuration-314bef8-javadoc.jar",
          "size": 261,
          "sha512": "1ab50bade51df238a16675d876e47e34921261ae9efb1471ebbac562eed3b534a5d473915f7574294421ca328b9a64120a014e055d526ae7c6348fde4808f5a3",
          "sha256": "8c17f1670ad83b9b7d8f0b00030a7641ac7e1819e8da5133843494049b6e2cea",
          "sha1": "cf959cc1e35e29decca1b84d84b30d3d384d2062",
          "md5": "ff4fc0b9013c8f9a73da4cc2f6cbab01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dokka-configuration-314bef8-sources.jar",
          "url": "antibytes-dokka-configuration-314bef8-sources.jar",
          "size": 2499,
          "sha512": "922467d8d294612e162c0ee4cb9a38c16082e69c521257f60a492a6a7ab95a358a609504d93354d36ae824075e6111d677c53ffac7272aa207b465f5f537888a",
          "sha256": "beb4e5f93ae9453c27ac64d1eba91d7847d9fd4c511ac8a012475854b7fb573f",
          "sha1": "92b8193d2e1a346fd22c82046969009d2e7e54e9",
          "md5": "cbbb4589512cde9d595428a12e622a6d"
        }
      ]
    }
  ]
}
