{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "789d509",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-metadata.jar",
          "url": "test-utils-789d509.jar",
          "size": 9083,
          "sha512": "b09e9863483a48390d2704d4a7103a5420b3fff675976e85a21d436fc3faaf2042344015d6f8d3e4012d305c6f79c25afe42623a937e1120598eeee1cbf3f982",
          "sha256": "56d9b97923a6410dedf55cf14b9a783f7ad82f92f06c9a75aabb8e7db6c1dd19",
          "sha1": "b195e91b72087aad50a6a2d32a330faff5421b9c",
          "md5": "283a0a5e06db5fff47ace3dd79745032"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/789d509/test-utils-android-789d509.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "789d509"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/789d509/test-utils-android-789d509.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "789d509"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/789d509/test-utils-jvm-789d509.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "789d509"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/789d509/test-utils-jvm-789d509.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "789d509"
      }
    }
  ]
}
