{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/a3cc152/kmock-a3cc152.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "a3cc152",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-a3cc152.klib",
          "url": "kmock-js-a3cc152.klib",
          "size": 119089,
          "sha512": "fbae6e3b1e5149db5f70955cf066f1d7404b91bcab7c26050657da5b8295190fea58ab077394cd840c41cf85102438c7901d08f1fcd2c56050ab0dfc06788bbd",
          "sha256": "f86fbdea9e852e864f749fe0d7216c599fca78cd0ffefd723f6126de59025e7f",
          "sha1": "8ef5bb1cc1c8f565da6a80fd449e9231796f62b1",
          "md5": "27e31895e7dcf16c8292017317b906d5"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-a3cc152.klib",
          "url": "kmock-js-a3cc152.klib",
          "size": 119089,
          "sha512": "fbae6e3b1e5149db5f70955cf066f1d7404b91bcab7c26050657da5b8295190fea58ab077394cd840c41cf85102438c7901d08f1fcd2c56050ab0dfc06788bbd",
          "sha256": "f86fbdea9e852e864f749fe0d7216c599fca78cd0ffefd723f6126de59025e7f",
          "sha1": "8ef5bb1cc1c8f565da6a80fd449e9231796f62b1",
          "md5": "27e31895e7dcf16c8292017317b906d5"
        }
      ]
    }
  ]
}
