{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-catalog",
    "version": "807f122",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-807f122.toml",
          "url": "antibytes-dependency-catalog-807f122.toml",
          "size": 225397,
          "sha512": "9aafb5469ece75f1661a27dc1f17060e430c10272d12ea97b1896a2b39303d514316e96548a44100bf76648d021a03b61a79ca3aae04c2a87cae9716e225873a",
          "sha256": "d649a26e578bf131ef3a67b7eceee7fc3bf5c64e0cc8862e491c64f679b28afe",
          "sha1": "90b3d04412420b20be1dcfee89f91f71abfb0d50",
          "md5": "dbfbf8a9411e63b3929518b040cd779c"
        }
      ]
    }
  ]
}
