{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency",
    "module": "antibytes-dependency",
    "version": "fa9f81c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-fa9f81c.jar",
          "url": "antibytes-dependency-fa9f81c.jar",
          "size": 88198,
          "sha512": "59d8afce38572bcad9aaaf5840eab7d09baae6a352f75115968c8556d13fca352aedbadfb47302e515be10316aba13eac9b4e048ed47ff7523e8d1e3f1d475f0",
          "sha256": "4ffc04c3c8f1434da12327bb457f47f32b2754b09d84a457f6a5bf55190a8563",
          "sha1": "cf40895c707e4f3ee3349aa757976bbc557e0a6a",
          "md5": "a0d0a0c2901172a30615a18ba277dee2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          },
          "excludes": [
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-xml"
            }
          ]
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "fa9f81c"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-fa9f81c.jar",
          "url": "antibytes-dependency-fa9f81c.jar",
          "size": 88198,
          "sha512": "59d8afce38572bcad9aaaf5840eab7d09baae6a352f75115968c8556d13fca352aedbadfb47302e515be10316aba13eac9b4e048ed47ff7523e8d1e3f1d475f0",
          "sha256": "4ffc04c3c8f1434da12327bb457f47f32b2754b09d84a457f6a5bf55190a8563",
          "sha1": "cf40895c707e4f3ee3349aa757976bbc557e0a6a",
          "md5": "a0d0a0c2901172a30615a18ba277dee2"
        }
      ]
    }
  ]
}
