{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/4f11117/test-utils-resourceloader-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-jvm-4f11117.jar",
          "url": "test-utils-resourceloader-jvm-4f11117.jar",
          "size": 5533,
          "sha512": "9850f82436521fa23cebbda16c41d317edf2c3d3ce19b2d9d47da51430fd8c89ccea388bbc90768aade63a16645bc1ae37d7a57d0828c8c63ce404ea1ba7a0e9",
          "sha256": "c7019ff2b2c0c1ec120cd437ff831791ec05aaf562b7fb4628b7894c557f9583",
          "sha1": "c73fb1c136385eb4629b3d521177376e9d977a31",
          "md5": "8b2ea0a5e2de73f779e63cb934d6984d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-jvm-4f11117.jar",
          "url": "test-utils-resourceloader-jvm-4f11117.jar",
          "size": 5533,
          "sha512": "9850f82436521fa23cebbda16c41d317edf2c3d3ce19b2d9d47da51430fd8c89ccea388bbc90768aade63a16645bc1ae37d7a57d0828c8c63ce404ea1ba7a0e9",
          "sha256": "c7019ff2b2c0c1ec120cd437ff831791ec05aaf562b7fb4628b7894c557f9583",
          "sha1": "c73fb1c136385eb4629b3d521177376e9d977a31",
          "md5": "8b2ea0a5e2de73f779e63cb934d6984d"
        }
      ]
    }
  ]
}
