{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/b9030f2/test-utils-resourceloader-b9030f2.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "b9030f2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-jvm-b9030f2.jar",
          "url": "test-utils-resourceloader-jvm-b9030f2.jar",
          "size": 6043,
          "sha512": "47df623d64e96df955cb9bbd856adc8cb7fd4172197d6ffd994af0308583977e5da542191f039111b8daf75b6699fab0433591c754c2bd1158eb3aab367f50e0",
          "sha256": "61dd032fb4ce86ffa510794d61982fe2f6c9aee4dbb40e17b273ca35a9e5d062",
          "sha1": "ef5b0751ec82dc9023fbae9f4fc5b1bc3ae7348e",
          "md5": "1d4d7b756b9c99928fda406cb99aef95"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-jvm-b9030f2.jar",
          "url": "test-utils-resourceloader-jvm-b9030f2.jar",
          "size": 6043,
          "sha512": "47df623d64e96df955cb9bbd856adc8cb7fd4172197d6ffd994af0308583977e5da542191f039111b8daf75b6699fab0433591c754c2bd1158eb3aab367f50e0",
          "sha256": "61dd032fb4ce86ffa510794d61982fe2f6c9aee4dbb40e17b273ca35a9e5d062",
          "sha1": "ef5b0751ec82dc9023fbae9f4fc5b1bc3ae7348e",
          "md5": "1d4d7b756b9c99928fda406cb99aef95"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-jvm-b9030f2-sources.jar",
          "url": "test-utils-resourceloader-jvm-b9030f2-sources.jar",
          "size": 3939,
          "sha512": "7d85cbd7e09301341ebc4a452974ea831daa47ecc20692cbd431c2b68ca72a05384a8a719e8d57c6ad9a08c604267f3bc585ad536112d38e67bf9fddeee875e1",
          "sha256": "464bb24a6fd8bcd03e6967c1fc82984afe22729853ac96f54e657f5efa51b5b8",
          "sha1": "071d7b720a3754f9a1ef1abe564f81b0f66ec341",
          "md5": "6ed222871ad195ee381ae6e47bfa73bd"
        }
      ]
    }
  ]
}
