{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.dokka",
    "module": "antibytes-dokka-configuration",
    "version": "9318316",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dokka-configuration-9318316.jar",
          "url": "antibytes-dokka-configuration-9318316.jar",
          "size": 7889,
          "sha512": "d74553017ab0f09152233af60e01660e54622e70da7e34bc323b9933e7e8cce0a42e4d9f0dc64017f276c9ae3f5d7e13d88241670c59427f7c7b248e9eb718ce",
          "sha256": "ebe6f5f97a5c885d6fc973fa2399824acdf964fb5678e17bb1c1f9c400da2d1e",
          "sha1": "b5f707e43738170f0300f1757bfb51893137f854",
          "md5": "d1441dbb36194f87efcdc2cad7de5f6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "9318316"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dokka-configuration-9318316.jar",
          "url": "antibytes-dokka-configuration-9318316.jar",
          "size": 7889,
          "sha512": "d74553017ab0f09152233af60e01660e54622e70da7e34bc323b9933e7e8cce0a42e4d9f0dc64017f276c9ae3f5d7e13d88241670c59427f7c7b248e9eb718ce",
          "sha256": "ebe6f5f97a5c885d6fc973fa2399824acdf964fb5678e17bb1c1f9c400da2d1e",
          "sha1": "b5f707e43738170f0300f1757bfb51893137f854",
          "md5": "d1441dbb36194f87efcdc2cad7de5f6c"
        }
      ]
    }
  ]
}
