{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/7bd994e/test-utils-7bd994e.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "7bd994e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-7bd994e.klib",
          "url": "test-utils-js-7bd994e.klib",
          "size": 12070,
          "sha512": "2adce76263df2e727a45df3bde133283b3fac67f70cfabec737f9f70bed7840f67031aa18486058cdc391df5941bf88671d43e56cb73e9b3d84494e698bcdc01",
          "sha256": "b86a62312695a5757ef73339683941aa59f1b423bb1911d5f35fb289886b5706",
          "sha1": "a205390e9f04c10a752bf5f9aeafb0f4e2b8b5d8",
          "md5": "bc7f85c4ec9ece47e1e18569fd553fe0"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-7bd994e.klib",
          "url": "test-utils-js-7bd994e.klib",
          "size": 12070,
          "sha512": "2adce76263df2e727a45df3bde133283b3fac67f70cfabec737f9f70bed7840f67031aa18486058cdc391df5941bf88671d43e56cb73e9b3d84494e698bcdc01",
          "sha256": "b86a62312695a5757ef73339683941aa59f1b423bb1911d5f35fb289886b5706",
          "sha1": "a205390e9f04c10a752bf5f9aeafb0f4e2b8b5d8",
          "md5": "bc7f85c4ec9ece47e1e18569fd553fe0"
        }
      ]
    }
  ]
}
