{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "165ee05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-165ee05.jar",
          "url": "antibytes-grammar-tools-165ee05.jar",
          "size": 39410,
          "sha512": "9e029c5c3b7bd470a16e7a86c8ab5011a996116b2c871b92b7d1c8e96a4e9227a7ae4d4f626b6039f00dc7a58928f177061b98f2fddfca706c2fe79c1d36b833",
          "sha256": "f37f37ce68ea1f2179f88db519ddf48c2a2e87acc0f873c9a51e9fef73f3e4e2",
          "sha1": "96778429d14ccbb50251e7118b043221d35df3a3",
          "md5": "11573dc26027ad1a37eea3569d44c98b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-165ee05.jar",
          "url": "antibytes-grammar-tools-165ee05.jar",
          "size": 39410,
          "sha512": "9e029c5c3b7bd470a16e7a86c8ab5011a996116b2c871b92b7d1c8e96a4e9227a7ae4d4f626b6039f00dc7a58928f177061b98f2fddfca706c2fe79c1d36b833",
          "sha256": "f37f37ce68ea1f2179f88db519ddf48c2a2e87acc0f873c9a51e9fef73f3e4e2",
          "sha1": "96778429d14ccbb50251e7118b043221d35df3a3",
          "md5": "11573dc26027ad1a37eea3569d44c98b"
        }
      ]
    }
  ]
}
