{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "56c4547",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-metadata-56c4547-all.jar",
          "url": "test-utils-resourceloader-56c4547-all.jar",
          "size": 10683,
          "sha512": "52b0cdb0463efe3791f19fc5366c7566e61db6924676ae9012efff8728d818718f3720e142cac0a7ab795b6a2b305fff1f0a3f7e9fef0a029531c8b932444d2f",
          "sha256": "543036c76693838b380da1e268c668e12fa6b54791b209ada963bfb17fa303ed",
          "sha1": "0782632643f5831deda807cd0a9406fd9eb136a0",
          "md5": "92bc87bc0b46746360f0e160c9fb260e"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-56c4547.jar",
          "url": "test-utils-resourceloader-56c4547.jar",
          "size": 3188,
          "sha512": "46150ff69020de9b2fa050c4e1d0795fb6803c39bd0092fb7c21ff0c7b9b1f3c6641d334a714f60648635204a09190563dfaf8c62e5f81243f3e428674b5aea7",
          "sha256": "6e9c4486b290f245f35d2982aa6be3bc63dbb3e994899f7c52be0eec1d2832ed",
          "sha1": "4157190da5735518a7c8139c8303a95947fb88ff",
          "md5": "09fc62b7e5021e81e4ea50a73be16c9e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-android/56c4547/test-utils-resourceloader-android-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-android",
        "version": "56c4547"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-android/56c4547/test-utils-resourceloader-android-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-android",
        "version": "56c4547"
      }
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosarm32/56c4547/test-utils-resourceloader-iosarm32-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosarm32",
        "version": "56c4547"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosarm32/56c4547/test-utils-resourceloader-iosarm32-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosarm32",
        "version": "56c4547"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosarm64/56c4547/test-utils-resourceloader-iosarm64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosarm64",
        "version": "56c4547"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosarm64/56c4547/test-utils-resourceloader-iosarm64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosarm64",
        "version": "56c4547"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iossimulatorarm64/56c4547/test-utils-resourceloader-iossimulatorarm64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iossimulatorarm64",
        "version": "56c4547"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iossimulatorarm64/56c4547/test-utils-resourceloader-iossimulatorarm64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iossimulatorarm64",
        "version": "56c4547"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosx64/56c4547/test-utils-resourceloader-iosx64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosx64",
        "version": "56c4547"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosx64/56c4547/test-utils-resourceloader-iosx64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosx64",
        "version": "56c4547"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-js/56c4547/test-utils-resourceloader-js-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-js",
        "version": "56c4547"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-js/56c4547/test-utils-resourceloader-js-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-js",
        "version": "56c4547"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-jvm/56c4547/test-utils-resourceloader-jvm-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-jvm",
        "version": "56c4547"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-jvm/56c4547/test-utils-resourceloader-jvm-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-jvm",
        "version": "56c4547"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-linuxarm32hfp/56c4547/test-utils-resourceloader-linuxarm32hfp-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-linuxarm32hfp",
        "version": "56c4547"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-linuxarm64/56c4547/test-utils-resourceloader-linuxarm64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-linuxarm64",
        "version": "56c4547"
      }
    },
    {
      "name": "linuxMips32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-linuxmips32/56c4547/test-utils-resourceloader-linuxmips32-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-linuxmips32",
        "version": "56c4547"
      }
    },
    {
      "name": "linuxMips32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-linuxmips32/56c4547/test-utils-resourceloader-linuxmips32-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-linuxmips32",
        "version": "56c4547"
      }
    },
    {
      "name": "linuxMipsel32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-linuxmipsel32/56c4547/test-utils-resourceloader-linuxmipsel32-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-linuxmipsel32",
        "version": "56c4547"
      }
    },
    {
      "name": "linuxMipsel32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-linuxmipsel32/56c4547/test-utils-resourceloader-linuxmipsel32-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-linuxmipsel32",
        "version": "56c4547"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-linuxx64/56c4547/test-utils-resourceloader-linuxx64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-linuxx64",
        "version": "56c4547"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-macosarm64/56c4547/test-utils-resourceloader-macosarm64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-macosarm64",
        "version": "56c4547"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-macosarm64/56c4547/test-utils-resourceloader-macosarm64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-macosarm64",
        "version": "56c4547"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-macosx64/56c4547/test-utils-resourceloader-macosx64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-macosx64",
        "version": "56c4547"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-macosx64/56c4547/test-utils-resourceloader-macosx64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-macosx64",
        "version": "56c4547"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-mingwx64/56c4547/test-utils-resourceloader-mingwx64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-mingwx64",
        "version": "56c4547"
      }
    },
    {
      "name": "mingwX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-mingwx86/56c4547/test-utils-resourceloader-mingwx86-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-mingwx86",
        "version": "56c4547"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-tvosarm64/56c4547/test-utils-resourceloader-tvosarm64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-tvosarm64",
        "version": "56c4547"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-tvosarm64/56c4547/test-utils-resourceloader-tvosarm64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-tvosarm64",
        "version": "56c4547"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-tvossimulatorarm64/56c4547/test-utils-resourceloader-tvossimulatorarm64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-tvossimulatorarm64",
        "version": "56c4547"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-tvossimulatorarm64/56c4547/test-utils-resourceloader-tvossimulatorarm64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-tvossimulatorarm64",
        "version": "56c4547"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-tvosx64/56c4547/test-utils-resourceloader-tvosx64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-tvosx64",
        "version": "56c4547"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-tvosx64/56c4547/test-utils-resourceloader-tvosx64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-tvosx64",
        "version": "56c4547"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-watchosarm32/56c4547/test-utils-resourceloader-watchosarm32-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-watchosarm32",
        "version": "56c4547"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-watchosarm32/56c4547/test-utils-resourceloader-watchosarm32-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-watchosarm32",
        "version": "56c4547"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-watchosarm64/56c4547/test-utils-resourceloader-watchosarm64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-watchosarm64",
        "version": "56c4547"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-watchosarm64/56c4547/test-utils-resourceloader-watchosarm64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-watchosarm64",
        "version": "56c4547"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-watchossimulatorarm64/56c4547/test-utils-resourceloader-watchossimulatorarm64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-watchossimulatorarm64",
        "version": "56c4547"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-watchossimulatorarm64/56c4547/test-utils-resourceloader-watchossimulatorarm64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-watchossimulatorarm64",
        "version": "56c4547"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-watchosx64/56c4547/test-utils-resourceloader-watchosx64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-watchosx64",
        "version": "56c4547"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-watchosx64/56c4547/test-utils-resourceloader-watchosx64-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-watchosx64",
        "version": "56c4547"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-watchosx86/56c4547/test-utils-resourceloader-watchosx86-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-watchosx86",
        "version": "56c4547"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-watchosx86/56c4547/test-utils-resourceloader-watchosx86-56c4547.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-watchosx86",
        "version": "56c4547"
      }
    }
  ]
}
