{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "39e413c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-39e413c.jar",
          "url": "antibytes-grammar-tools-39e413c.jar",
          "size": 39422,
          "sha512": "d7e7bd5bd9cc822fed8dd3147eefd52cb12aed7072569fc2eb840e597bba0bdbe18648e69b08821ee48892e6db0a412874a8ee56993301f4fd52eb0627cf14e2",
          "sha256": "cf72db1124d3a3b1cf0e64adcb5ee3dc7ba1bed417e8fbb96c38346d397d0100",
          "sha1": "48fab9fd90fa8eb5c5d5d9279f90b053da460529",
          "md5": "1c6b266e7632f4dc74dc38b56c36b39e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-39e413c.jar",
          "url": "antibytes-grammar-tools-39e413c.jar",
          "size": 39422,
          "sha512": "d7e7bd5bd9cc822fed8dd3147eefd52cb12aed7072569fc2eb840e597bba0bdbe18648e69b08821ee48892e6db0a412874a8ee56993301f4fd52eb0627cf14e2",
          "sha256": "cf72db1124d3a3b1cf0e64adcb5ee3dc7ba1bed417e8fbb96c38346d397d0100",
          "sha1": "48fab9fd90fa8eb5c5d5d9279f90b053da460529",
          "md5": "1c6b266e7632f4dc74dc38b56c36b39e"
        }
      ]
    }
  ]
}
