{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/b6c6e6c/test-utils-coroutine-b6c6e6c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "b6c6e6c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-watchosarm64-b6c6e6c.klib",
          "size": 11085,
          "sha512": "b6c3af3bb9b00e284ba930b642354642015e5e1d8ac0a881cd89498959fb9f392d5c5c02fb86dc76f6bfd135073ddd756a5a7b2c3fdf00191b07f337cbe1d8ee",
          "sha256": "965d9f0dbed3b4ff19c5e49513e990e8edb79df6bd82d4d1ebb0b1e674afe1a5",
          "sha1": "afb4330fb5ef195febc2715d5512995fceef13b6",
          "md5": "293aa27df096b0aae4d7d1856656d810"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-coroutine-watchosarm64-b6c6e6c-sources.jar",
          "url": "test-utils-coroutine-watchosarm64-b6c6e6c-sources.jar",
          "size": 4432,
          "sha512": "a6473d4ff59cb600f3c0fa9878a35c8f858acacd98510b4befc1e5f35be910c62a88e3b6041f5ba76c050b7c41af13fff93cd8bf60902a249f16b7429faa3ecf",
          "sha256": "cec6c043fde96eb3a674995451dc91cc39b82763e15d04e005be7dc8b426bde6",
          "sha1": "9c071f18ad7900caca2bc6884118c0e6ea620326",
          "md5": "a9e30d3490844e974b0610b29233965f"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-watchosarm64-b6c6e6c-metadata.jar",
          "url": "test-utils-coroutine-watchosarm64-b6c6e6c-metadata.jar",
          "size": 261,
          "sha512": "218c814cb4616c0773e29c666ffd053e674daea018fd197eff7b550bc861a6d9d5ccd69726b034ee74e9b4e2cffe80a0d1ab06d7490ac0a145dce31a05fb3c70",
          "sha256": "a79d2e5d3abfbb59cac69d340dfa15cd95a94e4c3f1b24a0d9eac7c96f707ad6",
          "sha1": "9518d940a40b48e2f3d8da6a665c00ae3f1b01ed",
          "md5": "ff82775dcee5e1541ec832efa904b0e1"
        }
      ]
    }
  ]
}
