{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/735eeec/test-utils-annotations-735eeec.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "735eeec",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-iosarm64-735eeec.klib",
          "size": 11328,
          "sha512": "139a1df39a4e87c57b226458c3f51eaa692324fa78134a1bb48ab51abd2c7914c027c864aa5a49d1f5f93566d868cabea5b0e4f543a1d8768ac47fae6bc65bbc",
          "sha256": "167078fceafef4d7b12aa1246194b22e2f64c21b6857db5ecdb79fe34a416ff5",
          "sha1": "840af79c504cffa448a9a408ad2cc5136c0fa2bc",
          "md5": "7682e0404c38c1fab5c4d35970f7ad44"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-iosarm64-735eeec-metadata.jar",
          "url": "test-utils-annotations-iosarm64-735eeec-metadata.jar",
          "size": 261,
          "sha512": "553ccb62a2f093f3bfb8b8d743022c682864b026b07460ad2ea5614b8ee1cf15c8b26ab4aebd67424201db2dfe001fa49cabbe7c1948fc00ef7bce36538bf8e3",
          "sha256": "6eabcee491109f2d222380037d0e6d81c35fd8a4e1a055b462a868f092e9fd92",
          "sha1": "1580e8578d4b9ac06973a09980aabca41c9e3b3f",
          "md5": "c3fb778b143f75d9767c23181a8a690c"
        }
      ]
    }
  ]
}
