{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "c189d8a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-c189d8a.jar",
          "url": "antibytes-versioning-c189d8a.jar",
          "size": 21893,
          "sha512": "392d091ea258019e99ce10a4bef8539c2a547fcc68f162ae5f0b4308843d081e5ce3c43c55debbf348415a847f77d1f70aa7e18bab0da7f8b4c9e6bd8066f30c",
          "sha256": "2c7c62c8edcb94420c0450c569df6d019ad80a2a712f403f0ed08adea54b318a",
          "sha1": "c045e8bea2dae56edb3d38c28ba44fd3ab81dda2",
          "md5": "0990647e5bc8674b46c5a9406364a447"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-c189d8a.jar",
          "url": "antibytes-versioning-c189d8a.jar",
          "size": 21893,
          "sha512": "392d091ea258019e99ce10a4bef8539c2a547fcc68f162ae5f0b4308843d081e5ce3c43c55debbf348415a847f77d1f70aa7e18bab0da7f8b4c9e6bd8066f30c",
          "sha256": "2c7c62c8edcb94420c0450c569df6d019ad80a2a712f403f0ed08adea54b318a",
          "sha1": "c045e8bea2dae56edb3d38c28ba44fd3ab81dda2",
          "md5": "0990647e5bc8674b46c5a9406364a447"
        }
      ]
    }
  ]
}
