{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "313c993",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-313c993.jar",
          "url": "antibytes-dependency-node-313c993.jar",
          "size": 21473,
          "sha512": "c97ef9536ffd90a14ceddbabd595252e91e8485bba2f7ab72a3b457c6841bda10ab527486b89d4508b9c22835241673823679dd89e4eb3009663fb99f9d4bff8",
          "sha256": "972018a38b6a52f3d8fc2c9c26de6f20435a25bcea4e6d68484c57215afbfa82",
          "sha1": "0a71f193d8d250bac4f9ffcc6f5a94c9c6a13796",
          "md5": "31cc248a240617b6ccec686e5db85bce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-313c993.jar",
          "url": "antibytes-dependency-node-313c993.jar",
          "size": 21473,
          "sha512": "c97ef9536ffd90a14ceddbabd595252e91e8485bba2f7ab72a3b457c6841bda10ab527486b89d4508b9c22835241673823679dd89e4eb3009663fb99f9d4bff8",
          "sha256": "972018a38b6a52f3d8fc2c9c26de6f20435a25bcea4e6d68484c57215afbfa82",
          "sha1": "0a71f193d8d250bac4f9ffcc6f5a94c9c6a13796",
          "md5": "31cc248a240617b6ccec686e5db85bce"
        }
      ]
    }
  ]
}
