{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-bridge",
    "version": "f006ae5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-bridge-f006ae5.jar",
          "url": "antibytes-dependency-bridge-f006ae5.jar",
          "size": 39844,
          "sha512": "fd3f9c95185f2ee157d73436edc5dfbdeb8d288f0ab4a1142969fc76e5d4884b1c43c65ae9b4f94935bec9f32b4377396a2a266469e6dabee4c325e017df4549",
          "sha256": "06de16708586381eeba17ccb7aba0a633f4e531c44b1e30e578ebb0a31683263",
          "sha1": "b5b5f196ea6cfbd712062f94ce83c6c28a7c2692",
          "md5": "197b5178782bf83357ddf799234baf41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "f006ae5"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-bridge-f006ae5.jar",
          "url": "antibytes-dependency-bridge-f006ae5.jar",
          "size": 39844,
          "sha512": "fd3f9c95185f2ee157d73436edc5dfbdeb8d288f0ab4a1142969fc76e5d4884b1c43c65ae9b4f94935bec9f32b4377396a2a266469e6dabee4c325e017df4549",
          "sha256": "06de16708586381eeba17ccb7aba0a633f4e531c44b1e30e578ebb0a31683263",
          "sha1": "b5b5f196ea6cfbd712062f94ce83c6c28a7c2692",
          "md5": "197b5178782bf83357ddf799234baf41"
        }
      ]
    }
  ]
}
