{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.coverage",
    "module": "antibytes-coverage",
    "version": "a821fe5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-a821fe5.jar",
          "url": "antibytes-coverage-a821fe5.jar",
          "size": 135187,
          "sha512": "6166fe68459e7646c2330ee131c2cbc105295d7a2f06c38b2550d39c56a99fd8ead8f6106050ae21055dc21b217aa07c0b0720b76a40c944e437b9971409d547",
          "sha256": "9f4d36d8d0f1a8694513ba7828ed1a84f5c2710cb0486feddd4101a280565b89",
          "sha1": "bafe205787c905638efa7ce4e3d74397cfd7826e",
          "md5": "b31341e944349ae0843d426b039ff67f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "a821fe5"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-a821fe5.jar",
          "url": "antibytes-coverage-a821fe5.jar",
          "size": 135187,
          "sha512": "6166fe68459e7646c2330ee131c2cbc105295d7a2f06c38b2550d39c56a99fd8ead8f6106050ae21055dc21b217aa07c0b0720b76a40c944e437b9971409d547",
          "sha256": "9f4d36d8d0f1a8694513ba7828ed1a84f5c2710cb0486feddd4101a280565b89",
          "sha1": "bafe205787c905638efa7ce4e3d74397cfd7826e",
          "md5": "b31341e944349ae0843d426b039ff67f"
        }
      ]
    }
  ]
}
