{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/fc88d6a/test-utils-annotations-junit4-fc88d6a.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "fc88d6a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-iosx64-fc88d6a.klib",
          "size": 11335,
          "sha512": "a2b53caf68a6238f48cb4582555a79eb50d91dc842aa7c144782c1901b31ce7f9bf0d6b81e791a8ff23dd068e3bf2897198e58f008a6bb58779d8995c89dc042",
          "sha256": "0c0bd6ef30e191d9933583a320776bb991623922170cba30ae14477f3e3c90d7",
          "sha1": "c9d01ac9add1320a06ea845bb74746a10fbf870b",
          "md5": "123085bdd3e3489ec2d5e3886fd3710f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-iosx64-fc88d6a-metadata.jar",
          "url": "test-utils-annotations-junit4-iosx64-fc88d6a-metadata.jar",
          "size": 261,
          "sha512": "c4a93ea32fdf16148d61a2bf3006a28c204337c6a40f405d76a0c95d0436747ef4738fc148248dab9af2361657109cad28b2856affeba031a78580ac39c76157",
          "sha256": "0b90deb8bd8823481fb394fa400a53cfb9d297f26db34384f79214cf83bba2b2",
          "sha1": "c6a4cd65105e4e9845f8bcdea3d03a9fec5b46b4",
          "md5": "724d18288db03b92a5e9730484ffb8ad"
        }
      ]
    }
  ]
}
