{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "a68f09c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-a68f09c.jar",
          "url": "antibytes-android-application-configuration-a68f09c.jar",
          "size": 56572,
          "sha512": "a3cc27214f3575b363a64410c2cd4a08a5eb4d744b327568962352452590bbbef81e34b42600db92e473431a70aa1b0e9ac2037678b30a376bc9c28d42e9ce31",
          "sha256": "2aa18b537e53187f55888762fa076b3fcf8d16c16601b22a53eef4cd25593527",
          "sha1": "b161ad6600a20863ac6f37a029ae1f2856934020",
          "md5": "9820c1ae93b351f0d8d73d1971233aca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "a68f09c"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-a68f09c.jar",
          "url": "antibytes-android-application-configuration-a68f09c.jar",
          "size": 56572,
          "sha512": "a3cc27214f3575b363a64410c2cd4a08a5eb4d744b327568962352452590bbbef81e34b42600db92e473431a70aa1b0e9ac2037678b30a376bc9c28d42e9ce31",
          "sha256": "2aa18b537e53187f55888762fa076b3fcf8d16c16601b22a53eef4cd25593527",
          "sha1": "b161ad6600a20863ac6f37a029ae1f2856934020",
          "md5": "9820c1ae93b351f0d8d73d1971233aca"
        }
      ]
    }
  ]
}
