{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.publishing",
    "module": "antibytes-publishing",
    "version": "4d535a7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-4d535a7.jar",
          "url": "antibytes-publishing-4d535a7.jar",
          "size": 141166,
          "sha512": "b1bfd6abb8a3de1993c2c342354634016f04e01c340827220ca372ad9891ca16ae29673914def867a0ee884216e5980c60a127b8141820c4323a8dcb9030d5da",
          "sha256": "95bb9ec04316e3691d02c3027caa8e949e5830be3e982ac66dceb89565a1dfea",
          "sha1": "ed38ced26303600147333d1a0c8673b75d4ec783",
          "md5": "c7e2e1c0fe65297f256e497a4f7be117"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.7.0.202309050840-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "4d535a7"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-4d535a7.jar",
          "url": "antibytes-publishing-4d535a7.jar",
          "size": 141166,
          "sha512": "b1bfd6abb8a3de1993c2c342354634016f04e01c340827220ca372ad9891ca16ae29673914def867a0ee884216e5980c60a127b8141820c4323a8dcb9030d5da",
          "sha256": "95bb9ec04316e3691d02c3027caa8e949e5830be3e982ac66dceb89565a1dfea",
          "sha1": "ed38ced26303600147333d1a0c8673b75d4ec783",
          "md5": "c7e2e1c0fe65297f256e497a4f7be117"
        }
      ]
    }
  ]
}
