{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "b1a580e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-b1a580e.jar",
          "url": "antibytes-coverage-b1a580e.jar",
          "size": 133730,
          "sha512": "58bb48103bf640d96e621b91b65e4a2b1e3d02b4d1f124f195a294cd1721d8871466535e68b31dbe8da58cf89401d2275fc611d8b9993f711c82571c00695217",
          "sha256": "7c860f6065880949170ec99be4b35ee367ff6d01d2a86829bf48c2409ad8d5df",
          "sha1": "f86855977fa974f42e159e8774bd900fdd498f3f",
          "md5": "a331fcd69100e5acb74a5aca51fe2879"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "b1a580e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-b1a580e.jar",
          "url": "antibytes-coverage-b1a580e.jar",
          "size": 133730,
          "sha512": "58bb48103bf640d96e621b91b65e4a2b1e3d02b4d1f124f195a294cd1721d8871466535e68b31dbe8da58cf89401d2275fc611d8b9993f711c82571c00695217",
          "sha256": "7c860f6065880949170ec99be4b35ee367ff6d01d2a86829bf48c2409ad8d5df",
          "sha1": "f86855977fa974f42e159e8774bd900fdd498f3f",
          "md5": "a331fcd69100e5acb74a5aca51fe2879"
        }
      ]
    }
  ]
}
