{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/8c5f468/test-utils-8c5f468.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "8c5f468",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm64-8c5f468.klib",
          "size": 14316,
          "sha512": "c77850254b2f5394110262f86f71576eaf68e40b44bcd198a3f6c39249036c07a608297345781f2efe32f702335a2bfc440ad4976f0ef653acbcb8e1f52a2c20",
          "sha256": "c4cab3c108c8626ad2e7cf6d1ade158666a8db0735f78f7920f6312e9ff9da6d",
          "sha1": "4d1bd781f2f280911e1f1f302bf2e9cfceddf52d",
          "md5": "3500ffd51405ad1cd1cd2de0d9c2eec7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm64-8c5f468-metadata.jar",
          "url": "test-utils-iosarm64-8c5f468-metadata.jar",
          "size": 261,
          "sha512": "0f4d93950a8d1868dd8ed377f4b2c9c4d995848c8122c17334b2b56447e57ba5cbd92330ebd4d7b1a218ff4140c73e0a5a238d834b633933ffc4c4e250d2a2e4",
          "sha256": "5139862bf00864a92a5fe95cd12a1e90b5713165de2421f7f8ec245488d46d98",
          "sha1": "715aceede0c7e32d79a86b7be4e2bc4652faffc4",
          "md5": "f3c081cdaf590898ddae525a5a6065a1"
        }
      ]
    }
  ]
}
