{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "4e1c621",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-4e1c621.jar",
          "url": "antibytes-custom-component-4e1c621.jar",
          "size": 16172,
          "sha512": "f9148b44bebf15b956691fb4fb0f6017c1dc85dfb9dd45c16469feb709e7c5c1293c644ac81fe98de2677fdf74cd8b7b18193508360589a92ddf1e051dfb968d",
          "sha256": "98734fca19c25d406d303149f4b96c20f7311ca9002dcd4edda66816b83cc9dd",
          "sha1": "637bcc3d7c9dee26a752827ca9f98ef8f2c1100a",
          "md5": "2c4c04e018d70310f291ce7571333abb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-4e1c621.jar",
          "url": "antibytes-custom-component-4e1c621.jar",
          "size": 16172,
          "sha512": "f9148b44bebf15b956691fb4fb0f6017c1dc85dfb9dd45c16469feb709e7c5c1293c644ac81fe98de2677fdf74cd8b7b18193508360589a92ddf1e051dfb968d",
          "sha256": "98734fca19c25d406d303149f4b96c20f7311ca9002dcd4edda66816b83cc9dd",
          "sha1": "637bcc3d7c9dee26a752827ca9f98ef8f2c1100a",
          "md5": "2c4c04e018d70310f291ce7571333abb"
        }
      ]
    }
  ]
}
