{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/dd59a45/test-utils-dd59a45.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "dd59a45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iossimulatorarm64-dd59a45.klib",
          "size": 14402,
          "sha512": "6ccf77678659d6aa7a19d5804f04f15e1ffbb19da6f07aa411fc20dc8fb1d25a8ae544f9b5c38b895f230349b93bab81bfaa1679d7e96de9aea56cbb9c293f6f",
          "sha256": "2842406ee09b5960ca932349a9dd9f950c7a6972f99b0664f413038235605023",
          "sha1": "f2bdb6636ad7f58af21706f085e0000c009b3b7a",
          "md5": "2653a2e2afd8371c43126d57e0d0ac8a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iossimulatorarm64-dd59a45-metadata.jar",
          "url": "test-utils-iossimulatorarm64-dd59a45-metadata.jar",
          "size": 261,
          "sha512": "e1b9313ac9c4fc2db0d141963c0d2f2aa5353b59900ca4e8e99e041e1a4bd9e72e681f916a0df7fa83382b8f628efedeb51e77bc7b720880946b5a21ae0466e3",
          "sha256": "f5260e888403bebe054063431aa1a20293673d5aee871949befb674fe47a0726",
          "sha1": "d90c0a0e6845e2a4682c7d43aa8575f620d217d4",
          "md5": "475a9bf7af75c61bad4a6ab4bebcf172"
        }
      ]
    }
  ]
}
