{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/ad2b9d7/kmock-ad2b9d7.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "ad2b9d7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-ad2b9d7.aar",
          "size": 118805,
          "sha512": "081b81c53c09dc768a17a4ecfb98c626c292aeffbea051d430117a0cd7640c0e60ec8d38f501245428698a524921c4eb0c1d973f6d7acf50900e1ea6b44a12d5",
          "sha256": "dce9df7e3a298e44df15a1f6e13d70c8200f64b6542ef636e37fb1bd14552447",
          "sha1": "370381839486c7bb1b5b9260626e7a03bde7dc80",
          "md5": "f32f464d58e4da98cd79bd25dd2834fe"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "7b11c9d-add-ios-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-ad2b9d7.aar",
          "size": 118805,
          "sha512": "081b81c53c09dc768a17a4ecfb98c626c292aeffbea051d430117a0cd7640c0e60ec8d38f501245428698a524921c4eb0c1d973f6d7acf50900e1ea6b44a12d5",
          "sha256": "dce9df7e3a298e44df15a1f6e13d70c8200f64b6542ef636e37fb1bd14552447",
          "sha1": "370381839486c7bb1b5b9260626e7a03bde7dc80",
          "md5": "f32f464d58e4da98cd79bd25dd2834fe"
        }
      ]
    }
  ]
}
