{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "42d3d0a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-42d3d0a.toml",
          "url": "antibytes-dependency-catalog-42d3d0a.toml",
          "size": 232720,
          "sha512": "b3aff4b27ea1f5e723659bc70246831c15d1b33dd27f11b36ae3a45c83b464de8ca143a24d1bd36560f4020e2aef251f931869bc64c5e8660b4524e42311b5a1",
          "sha256": "301ecd7ba6ed3de3b085d6aee083572f46dabe45fe9718a37a82b3ebd163d47a",
          "sha1": "c6862fa61648bc1170eaac3e52305f5554374883",
          "md5": "228ae858cfa6a080bcf1bce0465a2d4c"
        }
      ]
    }
  ]
}
