{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.publishing",
    "module": "antibytes-publishing",
    "version": "283c93a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "283c93a"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-283c93a.jar",
          "url": "antibytes-publishing-283c93a.jar",
          "size": 141292,
          "sha512": "6caa1db9ed544116669c2d328521baa9019ce9b57fd42846d871f1ae799629babee729cec3e9deec1f312d4bb5ff529f381d0eab437ba0677d108485586fc8ce",
          "sha256": "6811cf11377e0ec2210f6d53ed0ddf3e84905778bf8ffab62adbcbd15c17acf3",
          "sha1": "b31dffc77c81bf5d262845a1af7ff13d1d937bc7",
          "md5": "e318079c31884152e47499ae0dfe5cdd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.8.0.202311291450-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "283c93a"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "283c93a"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-283c93a.jar",
          "url": "antibytes-publishing-283c93a.jar",
          "size": 141292,
          "sha512": "6caa1db9ed544116669c2d328521baa9019ce9b57fd42846d871f1ae799629babee729cec3e9deec1f312d4bb5ff529f381d0eab437ba0677d108485586fc8ce",
          "sha256": "6811cf11377e0ec2210f6d53ed0ddf3e84905778bf8ffab62adbcbd15c17acf3",
          "sha1": "b31dffc77c81bf5d262845a1af7ff13d1d937bc7",
          "md5": "e318079c31884152e47499ae0dfe5cdd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-publishing-283c93a-javadoc.jar",
          "url": "antibytes-publishing-283c93a-javadoc.jar",
          "size": 261,
          "sha512": "2cfda3df007d777eb23dd4dfcaf33ed278fa02eb1e7f2fc91e298660a7f26205d09e9ab197b8e41e4ab1debb4c9dc1a71038fd939393d4cf6788491a96974b64",
          "sha256": "86e3ca4f6c17e6fbac9fc2ab71b8191726582bbf00fbe2ddd0b4935814e8d014",
          "sha1": "6e8240573f7c1138a4fd9577d1d0defb026ff1f1",
          "md5": "5f6118139fc75a2f098cfc8b147dbb77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-publishing-283c93a-sources.jar",
          "url": "antibytes-publishing-283c93a-sources.jar",
          "size": 25566,
          "sha512": "b8c11035a3e67d4eb6c12450d3041d375d8e440f2cfdd60257b09b875a14b902c104e2528ac9b45b5675a26a8a9851a90c6bb4520474b8d4c52b02cbf429ecd7",
          "sha256": "d8bd2e35f2c277b3cdf42b7ed1db196f3afa34dea986e743d54963d1196f03c7",
          "sha1": "2c69100285bbe792ffa5fb1f0191e2d78818db2d",
          "md5": "baa402f252dc7f219e07c01b583ba5e7"
        }
      ]
    }
  ]
}
