{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "625aee1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-625aee1-SNAPSHOT.jar",
          "url": "antibytes-grammar-tools-625aee1-SNAPSHOT.jar",
          "size": 39371,
          "sha512": "78ed173280f9a3ec7a2f8fead95206a207063bbcc70cc4ab8206824ae531a1d4cc264462d397d5d3a731692a980cc728692b0e2b133e09ea0ad97de70c081fb4",
          "sha256": "f4974054264d9b23b878323beb24ffb8ab3426d824bcc94797f6f45cb115a954",
          "sha1": "e3e4373c5d8052b24e2aebff0dd4cd2302ce8675",
          "md5": "d3d066202c8bb3db289c1a4e6958742c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-625aee1-SNAPSHOT.jar",
          "url": "antibytes-grammar-tools-625aee1-SNAPSHOT.jar",
          "size": 39371,
          "sha512": "78ed173280f9a3ec7a2f8fead95206a207063bbcc70cc4ab8206824ae531a1d4cc264462d397d5d3a731692a980cc728692b0e2b133e09ea0ad97de70c081fb4",
          "sha256": "f4974054264d9b23b878323beb24ffb8ab3426d824bcc94797f6f45cb115a954",
          "sha1": "e3e4373c5d8052b24e2aebff0dd4cd2302ce8675",
          "md5": "d3d066202c8bb3db289c1a4e6958742c"
        }
      ]
    }
  ]
}
