{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "fca89fa",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-fca89fa.jar",
          "url": "antibytes-grammar-tools-fca89fa.jar",
          "size": 39410,
          "sha512": "57a28ac4c08c87855a3110d28b90d033fdc7c470332ba8e4a322483454e70b7795202c4ee46a883767d5de8953b31490bcad1530d109a4eec381632d171fb1ec",
          "sha256": "0c3dfffaf604c1a9ddd7377ecc4c230aa3784d4746762afdf6ce3a351752ab0b",
          "sha1": "93dc3ca3f44610629a0f2a66804f451bcf9b865b",
          "md5": "01c97b64b4ceb0d24aceaf831ff5852e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-fca89fa.jar",
          "url": "antibytes-grammar-tools-fca89fa.jar",
          "size": 39410,
          "sha512": "57a28ac4c08c87855a3110d28b90d033fdc7c470332ba8e4a322483454e70b7795202c4ee46a883767d5de8953b31490bcad1530d109a4eec381632d171fb1ec",
          "sha256": "0c3dfffaf604c1a9ddd7377ecc4c230aa3784d4746762afdf6ce3a351752ab0b",
          "sha1": "93dc3ca3f44610629a0f2a66804f451bcf9b865b",
          "md5": "01c97b64b4ceb0d24aceaf831ff5852e"
        }
      ]
    }
  ]
}
