{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/56c4547/test-utils-annotations-junit5-56c4547.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "56c4547",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-watchosx86-56c4547.klib",
          "size": 7069,
          "sha512": "896997b4acc03353a0176793866c3472f78c7054a301205f3f292df890c5183ccb652d42bdf35e29a676697cac509a42053cbd33ac3bf0d15298f814b2139476",
          "sha256": "dcc2b327d4cff00184a44722299ccc5ca43ef0eb0ada231d611420a2cdc6f1c9",
          "sha1": "002d589bb44d1402c66ee469d7ac487436596cfd",
          "md5": "885a5be95c2a0ed7bd6bf6bae8801838"
        }
      ]
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-watchosx86-56c4547-metadata.jar",
          "url": "test-utils-annotations-junit5-watchosx86-56c4547-metadata.jar",
          "size": 261,
          "sha512": "ffa7768c143dbd767f27fc233381fbdbb2b329c203c403bb0965fb9d27ee16dea068fd074a1f2533a59707db092645e1b77781ade12149424d20ef4928250e18",
          "sha256": "496b9d8f4c52f86019cfab14072d26443c6b505a43bee8ee2146e732a4e1d7d8",
          "sha1": "535e6f9707a324c41ce869e41d0d7b31d94ba52d",
          "md5": "12e425a5617f2968bab684a5b6bf535e"
        }
      ]
    }
  ]
}
