{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "8609980",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-8609980.toml",
          "url": "antibytes-dependency-catalog-8609980.toml",
          "size": 232700,
          "sha512": "072f0b4f73094ee0381efed8b06b59ad29bd6887a2a87c7c512a70acefdaddc7f530fbaa15f2eb2a980f635e60fd96fb84589a4cabf9c992814a62ff912fc51d",
          "sha256": "33f690e9c6d5218eee2525de19d3d5c7c3921f668734f9b64c7652fcbb08bf6e",
          "sha1": "2226d4e5a437f1494e27b7564999f48522259f6d",
          "md5": "1fa7a91a37e29f0f0cff5f099b52dcf0"
        }
      ]
    }
  ]
}
