{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "f384302",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-metadata-f384302-all.jar",
          "url": "test-utils-annotations-junit5-f384302-all.jar",
          "size": 9656,
          "sha512": "7bd71650dfd53c2e6f1a9023dd6b121a2844b19a79788a4444aa36a4cedd5b952359e2f453036d1bed7092475b6fafcf67c3462d93df41cdd8471bc7a42e7a5b",
          "sha256": "4add985f04cc93aea37c78331eed301dcd5d6065ebbaf3b539b632c167a98e57",
          "sha1": "cda6eb4059149d6017ad94b0a3aec70d44ae1e43",
          "md5": "0554737457287e1cf64208c60bfda2ff"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-f384302.jar",
          "url": "test-utils-annotations-junit5-f384302.jar",
          "size": 3784,
          "sha512": "d26b6e23da82b19d43369ae359e8f9bb19c24add9c32ecc15f547a44ce882bce30e9e41faa87b6f928f55857b57a9682ee29cbed208be7960f17a1633af0decd",
          "sha256": "bcafc04d0c186bf46f3ebbe3f79a975a0315b8623d18764e3df6582fe986565c",
          "sha1": "b992f4f3a28a33e25e4821b7eb802e28af004093",
          "md5": "8998e183b596a7737ab342f516609655"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-android/f384302/test-utils-annotations-junit5-android-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-android",
        "version": "f384302"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-android/f384302/test-utils-annotations-junit5-android-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-android",
        "version": "f384302"
      }
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-androidnativearm32/f384302/test-utils-annotations-junit5-androidnativearm32-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-androidnativearm32",
        "version": "f384302"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-androidnativearm64/f384302/test-utils-annotations-junit5-androidnativearm64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-androidnativearm64",
        "version": "f384302"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-androidnativex64/f384302/test-utils-annotations-junit5-androidnativex64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-androidnativex64",
        "version": "f384302"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-androidnativex86/f384302/test-utils-annotations-junit5-androidnativex86-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-androidnativex86",
        "version": "f384302"
      }
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-iosarm32/f384302/test-utils-annotations-junit5-iosarm32-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-iosarm32",
        "version": "f384302"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-iosarm32/f384302/test-utils-annotations-junit5-iosarm32-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-iosarm32",
        "version": "f384302"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-iosarm64/f384302/test-utils-annotations-junit5-iosarm64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-iosarm64",
        "version": "f384302"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-iosarm64/f384302/test-utils-annotations-junit5-iosarm64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-iosarm64",
        "version": "f384302"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-iossimulatorarm64/f384302/test-utils-annotations-junit5-iossimulatorarm64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-iossimulatorarm64",
        "version": "f384302"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-iossimulatorarm64/f384302/test-utils-annotations-junit5-iossimulatorarm64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-iossimulatorarm64",
        "version": "f384302"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-iosx64/f384302/test-utils-annotations-junit5-iosx64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-iosx64",
        "version": "f384302"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-iosx64/f384302/test-utils-annotations-junit5-iosx64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-iosx64",
        "version": "f384302"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-js/f384302/test-utils-annotations-junit5-js-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-js",
        "version": "f384302"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-js/f384302/test-utils-annotations-junit5-js-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-js",
        "version": "f384302"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-jvm/f384302/test-utils-annotations-junit5-jvm-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-jvm",
        "version": "f384302"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-jvm/f384302/test-utils-annotations-junit5-jvm-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-jvm",
        "version": "f384302"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-linuxarm32hfp/f384302/test-utils-annotations-junit5-linuxarm32hfp-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-linuxarm32hfp",
        "version": "f384302"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-linuxarm64/f384302/test-utils-annotations-junit5-linuxarm64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-linuxarm64",
        "version": "f384302"
      }
    },
    {
      "name": "linuxMips32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-linuxmips32/f384302/test-utils-annotations-junit5-linuxmips32-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-linuxmips32",
        "version": "f384302"
      }
    },
    {
      "name": "linuxMips32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-linuxmips32/f384302/test-utils-annotations-junit5-linuxmips32-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-linuxmips32",
        "version": "f384302"
      }
    },
    {
      "name": "linuxMipsel32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-linuxmipsel32/f384302/test-utils-annotations-junit5-linuxmipsel32-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-linuxmipsel32",
        "version": "f384302"
      }
    },
    {
      "name": "linuxMipsel32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-linuxmipsel32/f384302/test-utils-annotations-junit5-linuxmipsel32-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-linuxmipsel32",
        "version": "f384302"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-linuxx64/f384302/test-utils-annotations-junit5-linuxx64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-linuxx64",
        "version": "f384302"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-macosarm64/f384302/test-utils-annotations-junit5-macosarm64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-macosarm64",
        "version": "f384302"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-macosarm64/f384302/test-utils-annotations-junit5-macosarm64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-macosarm64",
        "version": "f384302"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-macosx64/f384302/test-utils-annotations-junit5-macosx64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-macosx64",
        "version": "f384302"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-macosx64/f384302/test-utils-annotations-junit5-macosx64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-macosx64",
        "version": "f384302"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-mingwx64/f384302/test-utils-annotations-junit5-mingwx64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-mingwx64",
        "version": "f384302"
      }
    },
    {
      "name": "mingwX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-mingwx86/f384302/test-utils-annotations-junit5-mingwx86-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-mingwx86",
        "version": "f384302"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-tvosarm64/f384302/test-utils-annotations-junit5-tvosarm64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-tvosarm64",
        "version": "f384302"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-tvosarm64/f384302/test-utils-annotations-junit5-tvosarm64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-tvosarm64",
        "version": "f384302"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-tvossimulatorarm64/f384302/test-utils-annotations-junit5-tvossimulatorarm64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-tvossimulatorarm64",
        "version": "f384302"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-tvossimulatorarm64/f384302/test-utils-annotations-junit5-tvossimulatorarm64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-tvossimulatorarm64",
        "version": "f384302"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-tvosx64/f384302/test-utils-annotations-junit5-tvosx64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-tvosx64",
        "version": "f384302"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-tvosx64/f384302/test-utils-annotations-junit5-tvosx64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-tvosx64",
        "version": "f384302"
      }
    },
    {
      "name": "wasm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "wasm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-wasm32/f384302/test-utils-annotations-junit5-wasm32-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-wasm32",
        "version": "f384302"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchosarm32/f384302/test-utils-annotations-junit5-watchosarm32-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchosarm32",
        "version": "f384302"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchosarm32/f384302/test-utils-annotations-junit5-watchosarm32-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchosarm32",
        "version": "f384302"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchosarm64/f384302/test-utils-annotations-junit5-watchosarm64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchosarm64",
        "version": "f384302"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchosarm64/f384302/test-utils-annotations-junit5-watchosarm64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchosarm64",
        "version": "f384302"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchossimulatorarm64/f384302/test-utils-annotations-junit5-watchossimulatorarm64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchossimulatorarm64",
        "version": "f384302"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchossimulatorarm64/f384302/test-utils-annotations-junit5-watchossimulatorarm64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchossimulatorarm64",
        "version": "f384302"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchosx64/f384302/test-utils-annotations-junit5-watchosx64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchosx64",
        "version": "f384302"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchosx64/f384302/test-utils-annotations-junit5-watchosx64-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchosx64",
        "version": "f384302"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchosx86/f384302/test-utils-annotations-junit5-watchosx86-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchosx86",
        "version": "f384302"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchosx86/f384302/test-utils-annotations-junit5-watchosx86-f384302.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchosx86",
        "version": "f384302"
      }
    }
  ]
}
