{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/4f11117/test-utils-resourceloader-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iossimulatorarm64-4f11117.klib",
          "size": 12951,
          "sha512": "ef348779e4f1a42ca14d1dd5d6094f4b858a6ef6384c064af86a44b80f149a4a46f326676f3f5393fd964d4ec2669d7f49fdfa989bc2db6cd7a034b165ab10d3",
          "sha256": "31e73ccaffabdf9994f5dc643372a6f48ac9f9a19901d96122bdcf6c17c5f997",
          "sha1": "2999a2a2e1f8572af551acb6600ae6a6aa5eed48",
          "md5": "66321d6a894f9bdf98de4e775614d366"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iossimulatorarm64-4f11117-metadata.jar",
          "url": "test-utils-resourceloader-iossimulatorarm64-4f11117-metadata.jar",
          "size": 261,
          "sha512": "21f50903185ce3b5ef2ae72da947b965940e154a99dbd73daa11121e2303e49fc98f2cf1475169c877de35d31418496426c73990b37f3ee9f1f615e4b41dd9db",
          "sha256": "7ad44bc924aade152ea71a8895e5d693d0cfb89dfe0a5a4f15647cacdfc4fd93",
          "sha1": "e1b0004f5b880872624d03cbedfa93ac91b137ca",
          "md5": "7949b7f301cb2d6df263570013784b55"
        }
      ]
    }
  ]
}
