{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/b9030f2/test-utils-annotations-junit4-b9030f2.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "b9030f2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-tvosarm64-b9030f2.klib",
          "size": 11712,
          "sha512": "6a973e0de5a7214604df083a9dfe13113788a3520b47c918424f84bd9641aedbe06230331221b985aaf0902b0e1557bbd9648212b367057e44262e03b1d65458",
          "sha256": "3ca1c74db83ad469e4c32651bf053c35fa3871cd4d9ce23dfa914642a950ffff",
          "sha1": "4d433fb0dd0000e785940da9796c6c57b3fe1786",
          "md5": "59fef8f2b93f9889f2a414de021ff6de"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-annotations-junit4-tvosarm64-b9030f2-sources.jar",
          "url": "test-utils-annotations-junit4-tvosarm64-b9030f2-sources.jar",
          "size": 4896,
          "sha512": "2fe566b164f18a378d2c2daef090e149e0410a28bce2fd8eb67e9c81f2f2829b88cd4d3144e475fd0e8bd4d1e875624f6a42181ca5c272ee8cb3c5120df576b8",
          "sha256": "ce6588d8cdfe151428ad5243f3789335be34b41a39afba73df51f6509fb505d9",
          "sha1": "b969be4de0cad713d3e23159129ccc7f8256d550",
          "md5": "7378c76f616bc582b49cf2cf7b9d2f0a"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-tvosarm64-b9030f2-metadata.jar",
          "url": "test-utils-annotations-junit4-tvosarm64-b9030f2-metadata.jar",
          "size": 261,
          "sha512": "9e0c27316e255e8fac5369f0f51e1c9c363f6e2d3c045ecc85eadbbe4eef200fd8c5d448e19ee5e38a2486e65cfaa6b7774182033b91ac4a892a25085e8d0355",
          "sha256": "753ab0d9dae93ec7423ca96379cdda1e643159d9c02665bf3e2a8133d2b81311",
          "sha1": "4ac744fceb6404b1b503d21303e1e0f8b4895464",
          "md5": "b670c23e5ee9adc7c2ff99fe4618d01a"
        }
      ]
    }
  ]
}
