{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "e45307c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-e45307c.jar",
          "url": "antibytes-dependency-helper-e45307c.jar",
          "size": 68558,
          "sha512": "27879d9bf67e53ef11c82a2156090639413e4547d28f263f6848bac9e9d8b19d7539e7f4a7068fab7c7cc2505c0683ebbfed13c4d12db7ab340e5138e934e6c3",
          "sha256": "b8520ed8f808623bc6851b5cb7791fa84d63da8a52a6bff81d62a9469614debf",
          "sha1": "d4f5f1fddd639eeb922f7573c10c93beecbf432a",
          "md5": "05d90cee12671516bf0e25d86edbf43f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "e45307c"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-e45307c.jar",
          "url": "antibytes-dependency-helper-e45307c.jar",
          "size": 68558,
          "sha512": "27879d9bf67e53ef11c82a2156090639413e4547d28f263f6848bac9e9d8b19d7539e7f4a7068fab7c7cc2505c0683ebbfed13c4d12db7ab340e5138e934e6c3",
          "sha256": "b8520ed8f808623bc6851b5cb7791fa84d63da8a52a6bff81d62a9469614debf",
          "sha1": "d4f5f1fddd639eeb922f7573c10c93beecbf432a",
          "md5": "05d90cee12671516bf0e25d86edbf43f"
        }
      ]
    }
  ]
}
