{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "bf5cf3e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "bf5cf3e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-bf5cf3e.jar",
          "url": "antibytes-mkdocs-bf5cf3e.jar",
          "size": 12151,
          "sha512": "dbc8ea5a608e4df3a73ef88f2519c581b4f7f570371b65b3ca67e276c679ec27359bf9eda4fee8fc2e3e7d302e90c93ab7c7eeee9da7d562251c113af852f9f3",
          "sha256": "b64499ce2e1bf9c361b6aa2d4eac08019126ef584c6d657762454abb93e688c0",
          "sha1": "93511294c00a46cacc40dc5546299b9fb8267068",
          "md5": "f855b3fcff73c067ddbb0e8920e9f0d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "bf5cf3e"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "bf5cf3e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-bf5cf3e.jar",
          "url": "antibytes-mkdocs-bf5cf3e.jar",
          "size": 12151,
          "sha512": "dbc8ea5a608e4df3a73ef88f2519c581b4f7f570371b65b3ca67e276c679ec27359bf9eda4fee8fc2e3e7d302e90c93ab7c7eeee9da7d562251c113af852f9f3",
          "sha256": "b64499ce2e1bf9c361b6aa2d4eac08019126ef584c6d657762454abb93e688c0",
          "sha1": "93511294c00a46cacc40dc5546299b9fb8267068",
          "md5": "f855b3fcff73c067ddbb0e8920e9f0d7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-mkdocs-bf5cf3e-javadoc.jar",
          "url": "antibytes-mkdocs-bf5cf3e-javadoc.jar",
          "size": 261,
          "sha512": "e59a84294187e38ce58f80e88673fc24a38d8b0c4a908a5bc45a6cf5288da9d7b83cae1981a817eb0b58a063ec12dc72368dcc4c09ceb1cdfc65fad7eed544bc",
          "sha256": "73e7caa6df1c696545ca09bfb8e0edfe015f8e31e21220f195ffc15ff222c7a9",
          "sha1": "48e6622e0f138a69e71112a5f50505225cd94a60",
          "md5": "93c43a3b4d02e0f6a1051672046c84b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-mkdocs-bf5cf3e-sources.jar",
          "url": "antibytes-mkdocs-bf5cf3e-sources.jar",
          "size": 3210,
          "sha512": "4d9dfe8e1cb631e0e7b2d7ee58036ab8041180fd35949653533ab07eaacf9510823538172e8f2366ad4ecca3843e8c74b84bb8e42f7daa6a70f9181077d574f0",
          "sha256": "cc0b6b4b62b0b12703a641f181ff8068b8000569d8d81ce746802aa717beb02a",
          "sha1": "eeb28b091d67e3bdb76022634a3b4f0dbd2e0938",
          "md5": "a2bae684f50f482a404146adb591f667"
        }
      ]
    }
  ]
}
