{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "601dc8e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-601dc8e.toml",
          "url": "antibytes-dependency-catalog-601dc8e.toml",
          "size": 250839,
          "sha512": "d87ff84f766d9fe2a559cee7470745ec2a84812f409c3d1240dbbd1728bfc3f40fe9b10f570eb4672fa05e9110f0f797af0d2e647bd8f994afc048bc0c3387cf",
          "sha256": "a5e47621d6ecb160845572d9461024d52a4a34b7f80b7efbac472e6274108a89",
          "sha1": "78b05e51585bb2541ee321e2a6714f9efa09cbd6",
          "md5": "3192b2b878c5c1b9bd4c2c98fa33b1d0"
        }
      ]
    }
  ]
}
