{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "690bc5a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-690bc5a.jar",
          "url": "antibytes-custom-component-690bc5a.jar",
          "size": 16177,
          "sha512": "98cc495a5c4f5eb71898ab577519b4211a782c4484cf0a20858a488cdfc0b5f93428b8637fe70831cf49cd6a544b2c74e517f3e7c70eef34ccb69172ccdd3f40",
          "sha256": "f44872b5fe71fd0db90d0bad5300da597bb97c9bd4b98db7ebd33f9bd1d94040",
          "sha1": "57a6ba0d6a37e011a50bc9beb2210b1782c1a5eb",
          "md5": "5f7598a59dfed3f3664568a084617a43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-690bc5a.jar",
          "url": "antibytes-custom-component-690bc5a.jar",
          "size": 16177,
          "sha512": "98cc495a5c4f5eb71898ab577519b4211a782c4484cf0a20858a488cdfc0b5f93428b8637fe70831cf49cd6a544b2c74e517f3e7c70eef34ccb69172ccdd3f40",
          "sha256": "f44872b5fe71fd0db90d0bad5300da597bb97c9bd4b98db7ebd33f9bd1d94040",
          "sha1": "57a6ba0d6a37e011a50bc9beb2210b1782c1a5eb",
          "md5": "5f7598a59dfed3f3664568a084617a43"
        }
      ]
    }
  ]
}
