{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "b821e91",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-b821e91.toml",
          "url": "antibytes-dependency-catalog-b821e91.toml",
          "size": 241184,
          "sha512": "9c4eca58898bb4bcf65e34cfb8e4fe8d51066a396fcf4d5b9821e520f1347c449d22c2ed69eccd6b449b5b8d1127393e361cd8d43d9b4fbb640694f8816b1fa4",
          "sha256": "f74e14357439e411195367d3e950d45fb0bd59e733e72f3e5396cf5430ea3d9f",
          "sha1": "df2d31e1d02db3173837a5d7b8f5a785d1d23974",
          "md5": "54f2ab4bb43b277818e7d3b20bdc9636"
        }
      ]
    }
  ]
}
