{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/24bf67b/test-utils-fixture-24bf67b.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "24bf67b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js.klib",
          "url": "test-utils-fixture-js-24bf67b.klib",
          "size": 36097,
          "sha512": "82f5b5ae096448c323cfe3ec445485abfa4cce7bf9320fc684f49ed951fd92a8623bb07812ad63f8fa55f1efe335abece1cdcb4ef635aeee44202b8cf5db5571",
          "sha256": "0833aee019b5cb1248c3b1c64d4e9854db514ae82c5c33ebe41988b4ac6ccd1e",
          "sha1": "f559991204611dd2af7f873277cbea081ad3d93d",
          "md5": "06a25f4dd9c09f1524fd580059cec58c"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js.klib",
          "url": "test-utils-fixture-js-24bf67b.klib",
          "size": 36097,
          "sha512": "82f5b5ae096448c323cfe3ec445485abfa4cce7bf9320fc684f49ed951fd92a8623bb07812ad63f8fa55f1efe335abece1cdcb4ef635aeee44202b8cf5db5571",
          "sha256": "0833aee019b5cb1248c3b1c64d4e9854db514ae82c5c33ebe41988b4ac6ccd1e",
          "sha1": "f559991204611dd2af7f873277cbea081ad3d93d",
          "md5": "06a25f4dd9c09f1524fd580059cec58c"
        }
      ]
    }
  ]
}
