{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/fc88d6a/test-utils-resourceloader-fc88d6a.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "fc88d6a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-watchossimulatorarm64-fc88d6a.klib",
          "size": 12987,
          "sha512": "03f6ac1e3f8fa2103a667566aa55c217d37941df7843fa0161353db92cd593b9b51ff855b9ae4f0e8db5268e3f05d086dd6cad1dcad75359147f013781127086",
          "sha256": "822a62aa274eccaceb720db3a905492c267594ea28f947dd090ef5f49e72195a",
          "sha1": "4acb42eff9af631f38eef0dc10ad9cf0553a3a46",
          "md5": "13eab5c1282aa261e6ce17e79baf66f0"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-watchossimulatorarm64-fc88d6a-metadata.jar",
          "url": "test-utils-resourceloader-watchossimulatorarm64-fc88d6a-metadata.jar",
          "size": 261,
          "sha512": "8f168369b59a6e81cfda561465c6740c6b6ffd55f577a0a6b4a190865c7a8615ab2324511d4a7a443cc091269133f52da54731bee1181c329917f0e03dcb4c7a",
          "sha256": "4233a9f0c8aa7c16018764ef72bf723e3b535544ff0f4159c73ba99c215e659e",
          "sha1": "73aeb16e3849a55f9739c0ad634a6b31c93b58ec",
          "md5": "9dc570efcdcec735aa758ef062cb1842"
        }
      ]
    }
  ]
}
