{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/4f11117/test-utils-resourceloader-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "linuxMips32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-linuxmips32-4f11117.klib",
          "size": 12889,
          "sha512": "97f41ee1337ddb9ef1cecd97eecc90a9e590c40185af23d52e1f2d7ce48069ef79724c9865d9886c311e22eb18716fc1741694c07ff5487c26fc7c64d6af968c",
          "sha256": "badef04266f2b04120f5a4ea6c75899d24b9b0710aeb4808e22ede457046a8d9",
          "sha1": "991ff6ce8f13dbd0f42e9b9fd8d6cc6aec91477b",
          "md5": "ad92efedc1caab0577f9d2069a7d3f97"
        }
      ]
    },
    {
      "name": "linuxMips32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-linuxmips32-4f11117-metadata.jar",
          "url": "test-utils-resourceloader-linuxmips32-4f11117-metadata.jar",
          "size": 261,
          "sha512": "b72445d0fd26a7cfa5971bad1d4bfd73b178f3b353093138b114dd8741507f287e6418d98bca3a21b921989729218b908dfb414ea59d4cf758d13acffe8b4f5e",
          "sha256": "eda28fefac44d696aff04dd86f93dfa51695e51c324fe920283fd26d2bbee618",
          "sha1": "ec7e7fa054c45e49b278cc23a88b35583d897e14",
          "md5": "edce00e5f31452f83c2b207410ddedc7"
        }
      ]
    }
  ]
}
