{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/7bd994e/test-utils-coroutine-7bd994e.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "7bd994e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosx64-7bd994e.klib",
          "size": 10107,
          "sha512": "106e50c2ef08425a51366534db2fb184b8ac4ef80f087fff01f6c2bb9cd2d020f7cc88df0359720da4f6d13259325286574fe557c0285f1eacd22df07164453e",
          "sha256": "fa5c2d721e6cd6f1c9611f16760b87b2629af2a04419266852a2b68a97db350a",
          "sha1": "13e7453d88d68c5b8f25d07228ba0e1f8c6864cd",
          "md5": "c147117cb33e9beb33ed14f8ef84ead8"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosx64-7bd994e-metadata.jar",
          "url": "test-utils-coroutine-iosx64-7bd994e-metadata.jar",
          "size": 261,
          "sha512": "3d9891e82aedfdad6a365f17eb763840ee767448938bdf918b0e36ced01c20e9f49fccf4c63556dcca94b741e941ab3bacdf90bbcf9ee5bb0cf44a798002aa23",
          "sha256": "1e1c8e568dc0b12307b42b1b2b0a38323ba1ba1d7743d80f844fa3da66f8f3ac",
          "sha1": "a5dbb055d3d152804fb94d302f94c4188a675b89",
          "md5": "0f97c5fcb00df5e7a5c41271a784b611"
        }
      ]
    }
  ]
}
