{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/766ba9c/test-utils-annotations-junit4-766ba9c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "766ba9c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-iosarm64-766ba9c.klib",
          "size": 11351,
          "sha512": "eab01ccdc633125109f8844313c375f7821d74fd72713a110dcd21edadaadb67d0f9a4f42aea27872ff5873c6eca1367eabd6516f3e6f718c879785be3d3b229",
          "sha256": "ac318de8cc81066e0b59e7ee3b0d09e9f2fe1fa5288b0f460273a0d91e085660",
          "sha1": "8461e6ece21752696e7b9b24da62772ef6133a3b",
          "md5": "eb05bdc9218caeac1aafb0b1c4779775"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-iosarm64-766ba9c-metadata.jar",
          "url": "test-utils-annotations-junit4-iosarm64-766ba9c-metadata.jar",
          "size": 261,
          "sha512": "f93985032fa84dd584911d8e0875b423aca75fb734227b83f78d1b9d226e8d34ef5c8ae3d6be09fb7e099b10fcec1097704a3688583fd6ab6968967b173ee700",
          "sha256": "5a29e622851e41992dc5d5c2bd163fa281bb2714cc7f10bb2fa9852148f69477",
          "sha1": "5834898d1320bec862e86f812ea047593242178b",
          "md5": "bf1c0e76e2ce8832af03ca28904423e5"
        }
      ]
    }
  ]
}
