{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/231a33c/test-utils-annotations-junit4-231a33c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "231a33c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-js-231a33c.klib",
          "url": "test-utils-annotations-junit4-js-231a33c.klib",
          "size": 9754,
          "sha512": "ffcab69e3b56e6a0ff1d0ad1915c26452093f9c4342a3a0c04741eb4e8e6e547cbabaf6b9323dfacb53e37fce310011563c694c4dc9ffa93104538293c1c59b2",
          "sha256": "c121611465e682c072548f57f041afaf1f8afc79454066f33db732b5ce43f539",
          "sha1": "64e4c3af52768fbf8abaae9b0239119b8b4880ca",
          "md5": "e914bb6595c8f7fe5e46e1b2a373e6e0"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-js-231a33c.klib",
          "url": "test-utils-annotations-junit4-js-231a33c.klib",
          "size": 9754,
          "sha512": "ffcab69e3b56e6a0ff1d0ad1915c26452093f9c4342a3a0c04741eb4e8e6e547cbabaf6b9323dfacb53e37fce310011563c694c4dc9ffa93104538293c1c59b2",
          "sha256": "c121611465e682c072548f57f041afaf1f8afc79454066f33db732b5ce43f539",
          "sha1": "64e4c3af52768fbf8abaae9b0239119b8b4880ca",
          "md5": "e914bb6595c8f7fe5e46e1b2a373e6e0"
        }
      ]
    }
  ]
}
