{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "862b3a7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-862b3a7.toml",
          "url": "antibytes-dependency-catalog-862b3a7.toml",
          "size": 250086,
          "sha512": "634d86249aa3d67b859966f556076cd07dc95c291051e0a77cad0ba77d5b55443104f16daa95c4a737a57d94766515f1589c277a62d32b8f5ae993a45745c1d9",
          "sha256": "03c95e8bcacf30d3aefe64a1ee0c48ee599b72aee69aff44f1cab3251663d886",
          "sha1": "29f277307c57b1fce36a167c689a1bbec5e3ac8b",
          "md5": "576019cd5ec4fd7d9bb295f7e69e4257"
        }
      ]
    }
  ]
}
