{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "c560d77",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-metadata-c560d77.jar",
          "url": "kmock-c560d77.jar",
          "size": 17475,
          "sha512": "6ba077d481005f4ca5564898bcf03f127fa41269b37ec4fa68bdca6ed4b8fd2e6815438469fec752c9dbfb3b2de55f8baa3843e55c3644b7b6f9ca255a88a7e8",
          "sha256": "d9f797289bec127750525c89b59e3c3ebed4b4d97132379792b2c43d02e45cd2",
          "sha1": "80dbd4e6a3057449f374b7a4d44d16cdf046e1e3",
          "md5": "bf544229765925b7b0a6543eece76310"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/c560d77/kmock-android-c560d77.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "c560d77"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/c560d77/kmock-android-c560d77.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "c560d77"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/c560d77/kmock-iosarm64-c560d77.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "c560d77"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/c560d77/kmock-iosx64-c560d77.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "c560d77"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/c560d77/kmock-js-c560d77.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "c560d77"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/c560d77/kmock-js-c560d77.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "c560d77"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/c560d77/kmock-jvm-c560d77.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "c560d77"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/c560d77/kmock-jvm-c560d77.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "c560d77"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/c560d77/kmock-linuxx64-c560d77.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "c560d77"
      }
    }
  ]
}
