{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "2d16671",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-2d16671.jar",
          "url": "antibytes-gradle-test-utils-2d16671.jar",
          "size": 17888,
          "sha512": "f358c909fed455c5827f35816ba6dbf108f2d065458a48bab9d859a9d5b2b494102a98d404874f39faba350b6a5b20e2e7c293caf4975596717f02816ff122c3",
          "sha256": "7c89a03b8acb27bb5dc63cf41497e492d5ef65695778f3eee67acb83ea003ec9",
          "sha1": "4409e4c4a485a511ee95c0d3658c71cb286bc9d3",
          "md5": "02d741a1fd6efe9c3d83a0a58f3f2779"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-2d16671.jar",
          "url": "antibytes-gradle-test-utils-2d16671.jar",
          "size": 17888,
          "sha512": "f358c909fed455c5827f35816ba6dbf108f2d065458a48bab9d859a9d5b2b494102a98d404874f39faba350b6a5b20e2e7c293caf4975596717f02816ff122c3",
          "sha256": "7c89a03b8acb27bb5dc63cf41497e492d5ef65695778f3eee67acb83ea003ec9",
          "sha1": "4409e4c4a485a511ee95c0d3658c71cb286bc9d3",
          "md5": "02d741a1fd6efe9c3d83a0a58f3f2779"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-2d16671-javadoc.jar",
          "url": "antibytes-gradle-test-utils-2d16671-javadoc.jar",
          "size": 261,
          "sha512": "a703faf1dbd5de694229fa1ce6bdb33889d62623e00370d05f0cabb78577d8684e8b72f390bce09143f1014d65cbb9a464d6be6958e74ae896818f31e84d18ed",
          "sha256": "43b93f3cfefe5c482bf0c09fdcc0dfb54a38a9f63473c872a7d063953ed2cbda",
          "sha1": "27fa6f04114e1448929da594b99d59f43358afab",
          "md5": "12dd10c4484d82603164072a22819e2b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-2d16671-sources.jar",
          "url": "antibytes-gradle-test-utils-2d16671-sources.jar",
          "size": 3097,
          "sha512": "fab849422ca6e5a2885c19615428a7fe9f5c120695274798189e9e723cd25821ac71450842f1ad17f5209dd4eb6aa91619580ca1ec37eeea6674be1344be438b",
          "sha256": "104c5b649ce561a621c56af0d4936ec347e62165e27f9167bd0aa3d5d30d84e6",
          "sha1": "9df19fa454918bf536479966ab94cfb9ff4dca72",
          "md5": "9d1190b9d172288b571c484f29ec09c6"
        }
      ]
    }
  ]
}
