{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "96b20e0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-96b20e0.toml",
          "url": "antibytes-dependency-catalog-96b20e0.toml",
          "size": 232720,
          "sha512": "824b02fbd83bc564beede094095f06e619a7694e903da25b331b68fd2939cce5e0f9d5cf4a95d566b0104c743f7ee3594d7aee74ad3256691c391f14222a92b8",
          "sha256": "1fb97ec6efb8607ed2d21dca1ba60ace89c452126ba1ce640e36ebe91571991e",
          "sha1": "780db55f8af064055b0b80a5fc0e406a6bff7e22",
          "md5": "0993a72d25af2e35024b416c7db2c0ab"
        }
      ]
    }
  ]
}
