{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "bbae234",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-bbae234.jar",
          "url": "antibytes-gradle-utils-bbae234.jar",
          "size": 9471,
          "sha512": "8f7cfff74e3d1c14802c8b68b81b1c1950acd706dad59891eb8cd4978823d8a3924630d236c0702be070e08b1b97b8b207e8b13694130a18d2ed3fae941a0ad3",
          "sha256": "b2ccc905c6be9de02cb8ae54892827f3a40b13aa703fec2d79ff9d1e018532a0",
          "sha1": "cbb5224411cd5c87fc4a164874d6351fca044849",
          "md5": "ccded76fb77b56936a192739532c8ad5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-bbae234.jar",
          "url": "antibytes-gradle-utils-bbae234.jar",
          "size": 9471,
          "sha512": "8f7cfff74e3d1c14802c8b68b81b1c1950acd706dad59891eb8cd4978823d8a3924630d236c0702be070e08b1b97b8b207e8b13694130a18d2ed3fae941a0ad3",
          "sha256": "b2ccc905c6be9de02cb8ae54892827f3a40b13aa703fec2d79ff9d1e018532a0",
          "sha1": "cbb5224411cd5c87fc4a164874d6351fca044849",
          "md5": "ccded76fb77b56936a192739532c8ad5"
        }
      ]
    }
  ]
}
