{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/57db3a3/test-utils-coroutine-57db3a3.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "57db3a3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosarm64-57db3a3.klib",
          "size": 10124,
          "sha512": "6f1b87cc5fead1460cc7c8a6943d873389d65bf60ef4c8fa203ed21810a5dad4038da0eebe6bb9b90ef0b1f587e16e99f48370c593e54e6a788334303d03c885",
          "sha256": "aab199985bd5e67a4df1739aecc094ef2931f7bb304357fe28ff517f02a30c30",
          "sha1": "722a138aa6c815113b927e29b57762d968b2c11b",
          "md5": "b69ac5267b7d7b40a61ccdd92a821810"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosarm64-57db3a3-metadata.jar",
          "url": "test-utils-coroutine-iosarm64-57db3a3-metadata.jar",
          "size": 261,
          "sha512": "f40fbb1e9ceda23b45ba7e2563edbffeb21a15b3f2e5ff43baca8da0629f75be80a0adce01b3847d81c9297e15e02cd18aa2c9f8d8e673a51002e72196f508c8",
          "sha256": "235486ea8ff1aa19ea49158df6f12857da65376f63a45fc5bb4ee38777619d90",
          "sha1": "691103450d210a2f1887e18e3f46f3c6c6b9f281",
          "md5": "315cb699113cbfac3cc18c2f2b47c05a"
        }
      ]
    }
  ]
}
