{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "2bd65c1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-metadata-2bd65c1.jar",
          "url": "kmock-2bd65c1.jar",
          "size": 21090,
          "sha512": "932cd399af41344d5178ad6468cec98bad3e56552f04d9379404c7e34d8d9553eda7c78e61fb009d16c59a66df782215f54083466b881ee58824e16143a10cd2",
          "sha256": "75a2faabc9fb58e1bd52c7d5d9482ab2760e62911351f6f00733bf9b985358f6",
          "sha1": "939fdfef878d8d311de42893cf419f4dcc34bab0",
          "md5": "903303ac45a60aea975460947a2e6e6c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/2bd65c1/kmock-android-2bd65c1.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "2bd65c1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/2bd65c1/kmock-android-2bd65c1.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "2bd65c1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/2bd65c1/kmock-iosarm64-2bd65c1.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "2bd65c1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/2bd65c1/kmock-iosx64-2bd65c1.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "2bd65c1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/2bd65c1/kmock-js-2bd65c1.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "2bd65c1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/2bd65c1/kmock-js-2bd65c1.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "2bd65c1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/2bd65c1/kmock-jvm-2bd65c1.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "2bd65c1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/2bd65c1/kmock-jvm-2bd65c1.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "2bd65c1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/2bd65c1/kmock-linuxx64-2bd65c1.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "2bd65c1"
      }
    }
  ]
}
