{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/4f11117/test-utils-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm32-4f11117.klib",
          "size": 7962,
          "sha512": "2fc4ccee1addc3cb32356a025da5297edaed25947e4bfac9c334afc2882db9ce82c47607bbe56845bb5c6b570243e373989f2ed0c003c4b3cf346d44548536b4",
          "sha256": "c2b570c058f2f6a9f061c1802776841938a08d50f0d1f7815552290c4290088a",
          "sha1": "3d5c5b4cf5e2b9e21abe9bef700f8d4f3fa0169d",
          "md5": "103fede5a6124eb790461fde2db1573c"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm32-4f11117-metadata.jar",
          "url": "test-utils-iosarm32-4f11117-metadata.jar",
          "size": 261,
          "sha512": "3ebe7e63b770add05b8201dd57fc39562d47ee839c39963d26f75b0d9b78b6d25716d76c2cdc892c2e51ebdd76bd047d96f8967dd66752f1de6f2b1b8a81a9c5",
          "sha256": "75c8dc353a36e6c47f6134990de9a3589682b56e128ae2dedd5d459a11959508",
          "sha1": "5b6e786d6b2985dcd61569ad58c9ddf494ac96dc",
          "md5": "47585853f5ac04c5a5c4af58d5c6dabd"
        }
      ]
    }
  ]
}
