{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "690bc5a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-690bc5a.jar",
          "url": "antibytes-android-application-configuration-690bc5a.jar",
          "size": 56572,
          "sha512": "44238f707bc2e0371b310b342adf1c313b5cfe281755c127d2b3882d3d0e253c2b3a2d6e6de234413792b5404f1f9d54518eb70fb23d3855590865e4585c94b2",
          "sha256": "bb729b63c344a9ffa6cf218aeda543c81f3c5200a92a8191058596bc6a6fd6b9",
          "sha1": "88a6fa56477e628b10ea384c82674bba4274f221",
          "md5": "0a8c55d193983ae654bce945fd24e774"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "690bc5a"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-690bc5a.jar",
          "url": "antibytes-android-application-configuration-690bc5a.jar",
          "size": 56572,
          "sha512": "44238f707bc2e0371b310b342adf1c313b5cfe281755c127d2b3882d3d0e253c2b3a2d6e6de234413792b5404f1f9d54518eb70fb23d3855590865e4585c94b2",
          "sha256": "bb729b63c344a9ffa6cf218aeda543c81f3c5200a92a8191058596bc6a6fd6b9",
          "sha1": "88a6fa56477e628b10ea384c82674bba4274f221",
          "md5": "0a8c55d193983ae654bce945fd24e774"
        }
      ]
    }
  ]
}
