{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.settings",
    "module": "antibytes-dependency-settings",
    "version": "6b92a3b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "6b92a3b"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-6b92a3b.jar",
          "url": "antibytes-dependency-settings-6b92a3b.jar",
          "size": 15260,
          "sha512": "fb28e8a0d9a6fda4140acd470a27125d5b172b5c194246e6bf48a9757ef7b8d63b6081986033b41d107b194087936ed5fdd89f05ad57870747fe50e26dbe2886",
          "sha256": "cc8b59d973ff530bda3acc61b2634ab434258f001a06e9f09bb4b10a3ec896af",
          "sha1": "65e91345902ce5b1a75153338a3180e1940bfdad",
          "md5": "d1f772b63934aad6dbf0f63146550c8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "6b92a3b"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-6b92a3b.jar",
          "url": "antibytes-dependency-settings-6b92a3b.jar",
          "size": 15260,
          "sha512": "fb28e8a0d9a6fda4140acd470a27125d5b172b5c194246e6bf48a9757ef7b8d63b6081986033b41d107b194087936ed5fdd89f05ad57870747fe50e26dbe2886",
          "sha256": "cc8b59d973ff530bda3acc61b2634ab434258f001a06e9f09bb4b10a3ec896af",
          "sha1": "65e91345902ce5b1a75153338a3180e1940bfdad",
          "md5": "d1f772b63934aad6dbf0f63146550c8e"
        }
      ]
    }
  ]
}
