{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/b1ee631/kmock-b1ee631.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "b1ee631",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "047a358-add-ios-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-b1ee631.klib",
          "url": "kmock-js-b1ee631.klib",
          "size": 74742,
          "sha512": "608838146166fb9a282f4d9c379c815e3197d4a5a555ce3c0cbed7ea97340cea15ded4eef470cd7442ceb8a001a9ceb08172d5299c57d81a2c9b0bba9106b374",
          "sha256": "601985362951d814294ec3c79ab1688572b470985d02e285c385a1ec602342f4",
          "sha1": "e13678e9761b1e4b66fe305ef3644d8fd8122d69",
          "md5": "0078a38eac0f5ca3c2b4ffd4cce2a803"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "047a358-add-ios-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-b1ee631.klib",
          "url": "kmock-js-b1ee631.klib",
          "size": 74742,
          "sha512": "608838146166fb9a282f4d9c379c815e3197d4a5a555ce3c0cbed7ea97340cea15ded4eef470cd7442ceb8a001a9ceb08172d5299c57d81a2c9b0bba9106b374",
          "sha256": "601985362951d814294ec3c79ab1688572b470985d02e285c385a1ec602342f4",
          "sha1": "e13678e9761b1e4b66fe305ef3644d8fd8122d69",
          "md5": "0078a38eac0f5ca3c2b4ffd4cce2a803"
        }
      ]
    }
  ]
}
