{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-quality",
    "version": "01e59f4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-quality-01e59f4.jar",
          "url": "antibytes-quality-01e59f4.jar",
          "size": 62593,
          "sha512": "956642846aa15b059997ea76b939569097805beef339bb128b195780792a62e430d1253ffa6e69c51f1be690b0957ccc7d10c81503ad09f574b44903fe86a3c2",
          "sha256": "50e30558037cbca6874793b7362d0d7c5711a874d24945ee9e78b26c3fa6978f",
          "sha1": "72eb57f32b38006c7b50d6dee65d2eb31fdd46b1",
          "md5": "f681423b5bd389867948453600793b90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.21.0"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "01e59f4"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-dependency-helper",
          "version": {
            "requires": "01e59f4"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-01e59f4.jar",
          "url": "antibytes-quality-01e59f4.jar",
          "size": 62593,
          "sha512": "956642846aa15b059997ea76b939569097805beef339bb128b195780792a62e430d1253ffa6e69c51f1be690b0957ccc7d10c81503ad09f574b44903fe86a3c2",
          "sha256": "50e30558037cbca6874793b7362d0d7c5711a874d24945ee9e78b26c3fa6978f",
          "sha1": "72eb57f32b38006c7b50d6dee65d2eb31fdd46b1",
          "md5": "f681423b5bd389867948453600793b90"
        }
      ]
    }
  ]
}
