{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/56c4547/test-utils-annotations-junit5-56c4547.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "56c4547",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-watchosarm64-56c4547.klib",
          "size": 7086,
          "sha512": "5375c934c293382a66ed350449d350206980273045a93130135db1067ee4d254812b2b34ea02d72617f5ff8f82f597b7eab8b7b3f8c4c822bdd3607c34c249a6",
          "sha256": "1432ca394b02f768ce4d7c31117de8116da79ade416cc2a79c33875f09ce239a",
          "sha1": "dccf6ffa23d7083d2b04feaba2746674f7b48b99",
          "md5": "30a4505ceaa9c4c1e2810c9254ef6461"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-watchosarm64-56c4547-metadata.jar",
          "url": "test-utils-annotations-junit5-watchosarm64-56c4547-metadata.jar",
          "size": 261,
          "sha512": "24462a44dc71db0c7d41e071d872a5627fef33f1241ea6d4655b5811d737b8ded815f1cba0343423e9388a7f748e2e4b6365299dc0f336b09fabcc5b23b2af65",
          "sha256": "1d471a511ed3c820d2e788fe2d512f3e92f59ac6ac3e6adcdb364d09716488e0",
          "sha1": "17d5897c6eeed3994a12204b87dc2a08efea1d68",
          "md5": "8c3eb4686f57bc347e1e728e91f6f960"
        }
      ]
    }
  ]
}
