{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.kmp",
    "module": "antibytes-kmp-configuration",
    "version": "6ff4993",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-6ff4993.jar",
          "url": "antibytes-kmp-configuration-6ff4993.jar",
          "size": 58433,
          "sha512": "609a57f1e6916646067dce3ad746e2720fc1828fd21830cfa060b33506ae5ee663346bfa1c0109e94cee57d628f51882318b425a4db7d42cec41a5acb6b7da16",
          "sha256": "b658ced4782eb041c754ca117667063c62f6334046975045dcad51746638dbcd",
          "sha1": "4e46117521c35143d8f5615f12267c3a467b63fe",
          "md5": "05904bb18e699686d3a82903d49287c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "6ff4993"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-kmp-configuration-6ff4993.jar",
          "url": "antibytes-kmp-configuration-6ff4993.jar",
          "size": 58433,
          "sha512": "609a57f1e6916646067dce3ad746e2720fc1828fd21830cfa060b33506ae5ee663346bfa1c0109e94cee57d628f51882318b425a4db7d42cec41a5acb6b7da16",
          "sha256": "b658ced4782eb041c754ca117667063c62f6334046975045dcad51746638dbcd",
          "sha1": "4e46117521c35143d8f5615f12267c3a467b63fe",
          "md5": "05904bb18e699686d3a82903d49287c1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-6ff4993-javadoc.jar",
          "url": "antibytes-kmp-configuration-6ff4993-javadoc.jar",
          "size": 261,
          "sha512": "3250bba64cab8037c9d044d10b5488cbabb12dec3de77abdb6e7485c3f5bdb98b5a0c38bcebbaf081c938607b61e86626739363ddc9c57f7cbab5d1789261a53",
          "sha256": "0df42f1ff45f76e03a72eeac3652be37d7fa467e96396eb066b394808bc88264",
          "sha1": "e1b28882eba7a0e889c55a61a3bffb33ff994e55",
          "md5": "e54e937072b74153b188daa2446988c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-6ff4993-sources.jar",
          "url": "antibytes-kmp-configuration-6ff4993-sources.jar",
          "size": 12495,
          "sha512": "d50bc0a8ae06516d17e12565c793e7cb696ba3644b8b6f0d72858da8196ec6af39b1b6fdf5087ec9820b22e540b5437e212c9dd0e7d4ac33decd9b48bfe7acda",
          "sha256": "6c1242480caed6ee2dc880dda19a2e2ecdd8b884381104c9e755a041b989377f",
          "sha1": "7722932950e0a04be212348fcba327189c10d6dc",
          "md5": "73fd0d282ddbc620e685b8cf3b491b76"
        }
      ]
    }
  ]
}
