{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/231a33c/test-utils-resourceloader-231a33c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "231a33c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iosx64-231a33c.klib",
          "size": 12849,
          "sha512": "b05d419daa737638e1a68389db45e60bea41be3040a340ff709c504009a3e5ec8c8be71a2b276b3138d910f6f6f7f282daed519f0d7ccd55e01886495d2eb310",
          "sha256": "3c611a4912536b6a5fd7316d6a18b4fd7713a78c6c2c4cebe3d2a73d8d0d005f",
          "sha1": "fc5acdc5e365bcf321e84682b21068d4a0b8cd53",
          "md5": "c294d934ca5be70f140b4cd78fcc592f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iosx64-231a33c-metadata.jar",
          "url": "test-utils-resourceloader-iosx64-231a33c-metadata.jar",
          "size": 261,
          "sha512": "6e15413401abba09416fa4150aa42cf703de9c21672d440c7a37f4b7727c76d6c6830263d669803d7209a0acba5e39c0118dfe201914b1649c47894e34e8e76a",
          "sha256": "7ac1ef88483b146b5e49cd8a6bfd14e755dbd1f3512d37e8e0bf0448328094cc",
          "sha1": "def05e503442c64c0415213594847eedcbbe66f5",
          "md5": "74de5250ecd18ca3f07db72f1be6ad01"
        }
      ]
    }
  ]
}
