{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "d067446",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-d067446.jar",
          "url": "antibytes-dependency-node-d067446.jar",
          "size": 21473,
          "sha512": "0036693082ce4d9ff235073507dc00d9839e8344e722485b68a4495231e5490ef17869040aea34e0168b3773e5b8f24d0141b0cc71f100e5911fb819059dc084",
          "sha256": "abc8e3843f8f9145f19197e16562a009365843d4e15c9ae849724e96edfebcb4",
          "sha1": "d069ed5f8ee4f1006572a5486505f7c703b6f8ca",
          "md5": "63762b2c2fb407623b019d22b22e6ef8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-d067446.jar",
          "url": "antibytes-dependency-node-d067446.jar",
          "size": 21473,
          "sha512": "0036693082ce4d9ff235073507dc00d9839e8344e722485b68a4495231e5490ef17869040aea34e0168b3773e5b8f24d0141b0cc71f100e5911fb819059dc084",
          "sha256": "abc8e3843f8f9145f19197e16562a009365843d4e15c9ae849724e96edfebcb4",
          "sha1": "d069ed5f8ee4f1006572a5486505f7c703b6f8ca",
          "md5": "63762b2c2fb407623b019d22b22e6ef8"
        }
      ]
    }
  ]
}
