{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.0-SNAPSHOT/kmock-0.1.0-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.1.0-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.0-SNAPSHOT.jar",
          "size": 269592,
          "sha512": "5e436d3678d7238f9a1cb827184b76c4142d4aa2e1193e38f819b3679304f62326ee541c5788f81054963c176f7bb4499da6fb62e7fde401a92b57fb3356e1e2",
          "sha256": "fd092f296f84d66368aceb767a14296e997b538c46086d268f4dd32b3350a79f",
          "sha1": "4f55148ec411ccbd79aee7e64239ca2920d358de",
          "md5": "e72a04c6708e39aa69da5deed524dd13"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.1.0-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.0-SNAPSHOT.jar",
          "size": 269592,
          "sha512": "5e436d3678d7238f9a1cb827184b76c4142d4aa2e1193e38f819b3679304f62326ee541c5788f81054963c176f7bb4499da6fb62e7fde401a92b57fb3356e1e2",
          "sha256": "fd092f296f84d66368aceb767a14296e997b538c46086d268f4dd32b3350a79f",
          "sha1": "4f55148ec411ccbd79aee7e64239ca2920d358de",
          "md5": "e72a04c6708e39aa69da5deed524dd13"
        }
      ]
    }
  ]
}
