{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/7008207/test-utils-7008207.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "7008207",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm64-7008207.klib",
          "size": 14314,
          "sha512": "48c79b07b706c3ce272a91d2762b9fe7ed355bc45dda37abe73a4a31bee1ebe97326b64b5997014690657d46916593f9dfe0c9f05d0058918016317c289d17eb",
          "sha256": "f6ea5d2df079ee008a8ea65daaad0454e4f375fb57130b017d9164d956c2fafc",
          "sha1": "d326ecf1061a7fa161daa977ae965db9aebde3cd",
          "md5": "ef736f215e450e3f115ecad17d8d4e6b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm64-7008207-metadata.jar",
          "url": "test-utils-iosarm64-7008207-metadata.jar",
          "size": 261,
          "sha512": "641f3a51fa5439ad0371d499f8a989adeacd2afaab6303a301612bf57ba05e6a305a5317805d5a9823f517489157ac2f0a9831fff9b44b3f71b529faaccc8310",
          "sha256": "ae9e249c421117b6a5e899844b34ee892723c9d1e21df8e3d78bfa1909ea85df",
          "sha1": "c28d20d0f70ba70ae00645f76c1e92f7b09dc7ff",
          "md5": "806292bd6ed9d509c008dc026481acf8"
        }
      ]
    }
  ]
}
