{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.3.0-rc02-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc02-SNAPSHOT.jar",
          "url": "kmock-processor-0.3.0-rc02-SNAPSHOT.jar",
          "size": 384040,
          "sha512": "4e72e00d32a5161520479a20841b943516a721df2f9e8b027f739e303466f3df9ac8179aa4881d1d450eaf355e538bdfb9c17868111dea7120880820c86ab07a",
          "sha256": "190091b1b946e086cdabc1501deee5638cd57bb8700e7f148b03beb1a768c56a",
          "sha1": "07670d787798c9751c7d1140fda16110b0459a92",
          "md5": "4daf60609ef50af33a60d52fba2dabdf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.21-1.0.6"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.3.0-rc02-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc02-SNAPSHOT.jar",
          "url": "kmock-processor-0.3.0-rc02-SNAPSHOT.jar",
          "size": 384040,
          "sha512": "4e72e00d32a5161520479a20841b943516a721df2f9e8b027f739e303466f3df9ac8179aa4881d1d450eaf355e538bdfb9c17868111dea7120880820c86ab07a",
          "sha256": "190091b1b946e086cdabc1501deee5638cd57bb8700e7f148b03beb1a768c56a",
          "sha1": "07670d787798c9751c7d1140fda16110b0459a92",
          "md5": "4daf60609ef50af33a60d52fba2dabdf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc02-SNAPSHOT-javadoc.jar",
          "url": "kmock-processor-0.3.0-rc02-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "290a28e35476df2b5a7da09ceed893ec7b1f6ee1dc32d01ec81da0948e92a456632dacd025b711df7a7025edd36681932a8b75b1125734d6cdef87131ec4f999",
          "sha256": "535a88e11d51a16219809ca58e3f4ea8ac8482f84122ea0e8252ecbc73f29c68",
          "sha1": "3c658e9928a2d02e45e35cb5d1b6400d45fdf413",
          "md5": "69ae22c559e800fc96d60dd75d5e9c69"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc02-SNAPSHOT-sources.jar",
          "url": "kmock-processor-0.3.0-rc02-SNAPSHOT-sources.jar",
          "size": 80429,
          "sha512": "189509c5cb9cb3aa4646ae703fa0542b8ce419d5d0e3ff0614fe238466a6bedbccee557a6b31bbda4ed10836139443931d897da5020322d7cf413bc6859b361c",
          "sha256": "b7e76c5fe613f5e2947ffd27fbecc199d1feaaa25fba2e1072059cac741e3a9f",
          "sha1": "780b732d25f130c48ac03c2df9cfa3a165fe6d94",
          "md5": "81304aad429b684ae8b571298606b29a"
        }
      ]
    }
  ]
}
