{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.3.0-rc02-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc02-SNAPSHOT.jar",
          "url": "kmock-processor-0.3.0-rc02-SNAPSHOT.jar",
          "size": 384634,
          "sha512": "633a0c358c43f7abeb9fe4a7d2925a9d717d0a23d900324b54e6c6d4022533375c33655cbbf9da9cdc981c96842dbaa27b82dc8ab130ec3ae532e60745accd4d",
          "sha256": "7bab56e5839621e1c480a29987195a5f51f64c375f7609892b70ef7a042a1f96",
          "sha1": "29aeec5502fc6f17b23d18c9f84adae7a59be7e1",
          "md5": "3104b4a82c3ece57a2952d310f9e7a31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.21-1.0.6"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.3.0-rc02-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc02-SNAPSHOT.jar",
          "url": "kmock-processor-0.3.0-rc02-SNAPSHOT.jar",
          "size": 384634,
          "sha512": "633a0c358c43f7abeb9fe4a7d2925a9d717d0a23d900324b54e6c6d4022533375c33655cbbf9da9cdc981c96842dbaa27b82dc8ab130ec3ae532e60745accd4d",
          "sha256": "7bab56e5839621e1c480a29987195a5f51f64c375f7609892b70ef7a042a1f96",
          "sha1": "29aeec5502fc6f17b23d18c9f84adae7a59be7e1",
          "md5": "3104b4a82c3ece57a2952d310f9e7a31"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc02-SNAPSHOT-javadoc.jar",
          "url": "kmock-processor-0.3.0-rc02-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "bee35c5e72b16077a23d400fa3b5a1a6b98b58a85637b03406c8a5392355b4f7e2f04992f6b67fe4e40f07cc006916bcf291bb177348661f5cb756867cb951d5",
          "sha256": "c017fc21e662c89168f77a37afbf7197494bd252d316001a3561b43b77d766a3",
          "sha1": "fd5068716a39263a5de8ed635a006df78c8d3a17",
          "md5": "a9bf81607437ed6144ea866f05421071"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc02-SNAPSHOT-sources.jar",
          "url": "kmock-processor-0.3.0-rc02-SNAPSHOT-sources.jar",
          "size": 80549,
          "sha512": "3a4e2a01cbdcd5dbbbb83f2915eb55765fbf47d00d09e301f05bb968c6945eb45214c405b12433c8e7e067d01575e7bd512502f72a9ce82d1835de918cecbe52",
          "sha256": "79c14df1dd1509b9086fc7e2248eed7f484ae538fb3b49ec4cffb8f55c2193ab",
          "sha1": "b138312f8a0e877d9456040e31c7b9eb7d953c15",
          "md5": "09e5182944ef96daf80ac8f8dfd63d32"
        }
      ]
    }
  ]
}
