{
  "formatVersion": "1.1",
  "component": {
    "url": "../../banana-i18n/63396e3/banana-i18n-63396e3.module",
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "63396e3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-63396e3.jar",
          "size": 58530,
          "sha512": "391c84a6b4095c9ece1218f9f24bc22991ff667d67972eb008e150eb0750bbb095c77dff1a1156b931a17f3111e4df23efbc148e2874f409d5611b6c4b7534c1",
          "sha256": "aea4228c4146dd1550d3a55e72306265f7109d5cfe3e541d18dfec04c16374ee",
          "sha1": "91163639d4a87791c2cfe3e0fafa24bd8d2b4e6e",
          "md5": "6c69e48ae700ab0810d6fe0d35e962b9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-63396e3.jar",
          "size": 58530,
          "sha512": "391c84a6b4095c9ece1218f9f24bc22991ff667d67972eb008e150eb0750bbb095c77dff1a1156b931a17f3111e4df23efbc148e2874f409d5611b6c4b7534c1",
          "sha256": "aea4228c4146dd1550d3a55e72306265f7109d5cfe3e541d18dfec04c16374ee",
          "sha1": "91163639d4a87791c2cfe3e0fafa24bd8d2b4e6e",
          "md5": "6c69e48ae700ab0810d6fe0d35e962b9"
        }
      ]
    }
  ]
}
