{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "b7a1e13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-b7a1e13.jar",
          "url": "kmock-processor-b7a1e13.jar",
          "size": 76785,
          "sha512": "4c875059084f2edf9ae7616a76f9fd7a7ef9323d0974c4e43d1fae7f30d7a152cc912df125adcd26633b4ca0c00eccd9d3a9f956619cb80c60ca64e864f46953",
          "sha256": "bae6cb656d3a11285895b17dc8611ff3e984ee95ccb34d8a00f0e32d9d74fcad",
          "sha1": "c6d393ce33c6fe5f8a583f03641b5529387aa90b",
          "md5": "522c356ed18cbf6f2ac5af2359d046ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "b7a1e13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-b7a1e13.jar",
          "url": "kmock-processor-b7a1e13.jar",
          "size": 76785,
          "sha512": "4c875059084f2edf9ae7616a76f9fd7a7ef9323d0974c4e43d1fae7f30d7a152cc912df125adcd26633b4ca0c00eccd9d3a9f956619cb80c60ca64e864f46953",
          "sha256": "bae6cb656d3a11285895b17dc8611ff3e984ee95ccb34d8a00f0e32d9d74fcad",
          "sha1": "c6d393ce33c6fe5f8a583f03641b5529387aa90b",
          "md5": "522c356ed18cbf6f2ac5af2359d046ff"
        }
      ]
    }
  ]
}
