{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "c78d849",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-ktor-metadata-c78d849-all.jar",
          "url": "test-utils-ktor-c78d849-all.jar",
          "size": 5006,
          "sha512": "c93292ce50dff5753f336a9c81d68df8f3e5243bdd11240c45495495e95bc97e62ffe692ebecea98baa71931f4cd6c82b95abc1e0cd9729c21ff5f4645544435",
          "sha256": "719ac3b6fa13d4bb0bbbed83b6f3766aa6cda1f176fb3cec9ca1b78f421170c1",
          "sha1": "7a001c8771c8a6e6ee74291aacb35bae130aa17b",
          "md5": "adeb59ac55b524d4024dba64dffe0b25"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-ktor-c78d849.jar",
          "url": "test-utils-ktor-c78d849.jar",
          "size": 2512,
          "sha512": "b19b4ff1889541e5673d4befe0b949c078b7383dd5d7377bee0577ebb994a994282520c0cb564849e69a01e2bfa0ca3a1471e1d9dc398a29b44de7cf31292285",
          "sha256": "7536976e20e7c5a77bc78efed5c67389d831910df7d0b626e588641087b2d6d0",
          "sha1": "1e3b6b7f5d061e5c1f67171efbf01dbc3128c64a",
          "md5": "0f3f37c98096e9b113544c4399345528"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/c78d849/test-utils-ktor-android-c78d849.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "c78d849"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/c78d849/test-utils-ktor-android-c78d849.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "c78d849"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-ktor-js/c78d849/test-utils-ktor-js-c78d849.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-js",
        "version": "c78d849"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-ktor-js/c78d849/test-utils-ktor-js-c78d849.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-js",
        "version": "c78d849"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/c78d849/test-utils-ktor-jvm-c78d849.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "c78d849"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/c78d849/test-utils-ktor-jvm-c78d849.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "c78d849"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-linuxx64/c78d849/test-utils-ktor-linuxx64-c78d849.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-linuxx64",
        "version": "c78d849"
      }
    }
  ]
}
