{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.publishing",
    "module": "antibytes-publishing",
    "version": "afcad58",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "afcad58"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-afcad58.jar",
          "url": "antibytes-publishing-afcad58.jar",
          "size": 141166,
          "sha512": "011b38e629dfa1f48199128203fb4adb4ba2d6fbe21f15fd40daf9f88e03539831648d82a0ddae7094daaab537d6d08d055d30144163f4675a53329155b22922",
          "sha256": "b6cc0300fa7e9d322c6c9ef508ebc59a10b04207ae0ad820f9a7f1c3f7892a32",
          "sha1": "cd02ec3f9b3d42df271cbbc8f448d93a6e7adbac",
          "md5": "d053004c8ee4d78d13f3eb5d32a12323"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.7.0.202309050840-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "afcad58"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "afcad58"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-afcad58.jar",
          "url": "antibytes-publishing-afcad58.jar",
          "size": 141166,
          "sha512": "011b38e629dfa1f48199128203fb4adb4ba2d6fbe21f15fd40daf9f88e03539831648d82a0ddae7094daaab537d6d08d055d30144163f4675a53329155b22922",
          "sha256": "b6cc0300fa7e9d322c6c9ef508ebc59a10b04207ae0ad820f9a7f1c3f7892a32",
          "sha1": "cd02ec3f9b3d42df271cbbc8f448d93a6e7adbac",
          "md5": "d053004c8ee4d78d13f3eb5d32a12323"
        }
      ]
    }
  ]
}
