{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "d50fcae",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-d50fcae.jar",
          "url": "antibytes-custom-component-d50fcae.jar",
          "size": 16172,
          "sha512": "8d3ac91ee4c408730af892c8b265d0b99319d80a53664e7afba025c5af9bad130cad195d93cbb3da244ef1b6d01c955dea3aa378ee045a4f75b515de7eebdd3b",
          "sha256": "c810426015a00370f4e3a6c12c07bf74068b11b82faf2a326bc8ebe9efcffba8",
          "sha1": "3ac9c8b22892ba63d6a0b06b7d186347d27f5435",
          "md5": "bcc471d47abe43100656f15e194fdda8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-d50fcae.jar",
          "url": "antibytes-custom-component-d50fcae.jar",
          "size": 16172,
          "sha512": "8d3ac91ee4c408730af892c8b265d0b99319d80a53664e7afba025c5af9bad130cad195d93cbb3da244ef1b6d01c955dea3aa378ee045a4f75b515de7eebdd3b",
          "sha256": "c810426015a00370f4e3a6c12c07bf74068b11b82faf2a326bc8ebe9efcffba8",
          "sha1": "3ac9c8b22892ba63d6a0b06b7d186347d27f5435",
          "md5": "bcc471d47abe43100656f15e194fdda8"
        }
      ]
    }
  ]
}
