{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/8066bd0/test-utils-annotations-junit5-8066bd0.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "8066bd0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-iosarm32-8066bd0.klib",
          "size": 7049,
          "sha512": "a6dd9a3a567969fd9905cf0dc9f50114fc03c7a85b8f938d941aa9665506cfc3db3835ae1a64349083578a4cb8e1de347ad7a490a65b3894a93dcf9bd2e8083e",
          "sha256": "ca0e705b9ff325a7b3e27229d3ab104d7c6721214f280317d76ed3103f0dc2e1",
          "sha1": "367df46f17bb68f601df4927fd31b10bc95274b8",
          "md5": "5ed3b3657b59e066ccc9e2a8a6934bed"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-iosarm32-8066bd0-metadata.jar",
          "url": "test-utils-annotations-junit5-iosarm32-8066bd0-metadata.jar",
          "size": 261,
          "sha512": "dd640544be91a7c29c77b07cde2f085660728381970b9fbe108564a63e0302ed481940dd8a3a37e73979d5bc5c06e94b27bb8357ec7d7a4ecd180b3164c73c91",
          "sha256": "b94773d82627a959f84b8af4e619f63cfd708190ac3ec7afe03cd1f63c8c1161",
          "sha1": "153acf8c96458480e011e98d7d748b255b4d8f11",
          "md5": "f08381cbdd1721bad9fdb49a8946e527"
        }
      ]
    }
  ]
}
