{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/64c6243/test-utils-coroutine-64c6243.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "64c6243",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-64c6243.klib",
          "url": "test-utils-coroutine-js-64c6243.klib",
          "size": 10133,
          "sha512": "825f3bab1ba88bf2b4fbb726e80ead96231411b809340ab6d846ddf5791eac1773ffda061fd2cd2feee48c8c67d04ddff162336ae10db175e0151f2affc5cfeb",
          "sha256": "5c7908c35f11bc0ee3d95104ec2947870da2e1d5b758467f815631e19fb60133",
          "sha1": "96b9a10595558465cf4103e57f35c11ca99dc90b",
          "md5": "a3fc8047e562ab873f4a915027eddfa0"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-64c6243.klib",
          "url": "test-utils-coroutine-js-64c6243.klib",
          "size": 10133,
          "sha512": "825f3bab1ba88bf2b4fbb726e80ead96231411b809340ab6d846ddf5791eac1773ffda061fd2cd2feee48c8c67d04ddff162336ae10db175e0151f2affc5cfeb",
          "sha256": "5c7908c35f11bc0ee3d95104ec2947870da2e1d5b758467f815631e19fb60133",
          "sha1": "96b9a10595558465cf4103e57f35c11ca99dc90b",
          "md5": "a3fc8047e562ab873f4a915027eddfa0"
        }
      ]
    }
  ]
}
