{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "5538abc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-5538abc.jar",
          "url": "antibytes-publishing-5538abc.jar",
          "size": 105775,
          "sha512": "39e8ecf213abdfb85d3a479ba6fe8823f58cbbdc4fe3c600307a4bb18260d25bcc56806baf3c97b3b38848106e12a3fa6d486491b363713953715f5a96654230",
          "sha256": "7ac5dbd75d3a2a1dc27070f22dfc91ad5853903fae235a437ed9188d1d88d34e",
          "sha1": "aef7aefa1299aef402d11906d0c6a07d857122cc",
          "md5": "ae7bba1ca93c54fb70136f6f1a44aefb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.13.0.202109080827-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.12.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "5538abc"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-5538abc.jar",
          "url": "antibytes-publishing-5538abc.jar",
          "size": 105775,
          "sha512": "39e8ecf213abdfb85d3a479ba6fe8823f58cbbdc4fe3c600307a4bb18260d25bcc56806baf3c97b3b38848106e12a3fa6d486491b363713953715f5a96654230",
          "sha256": "7ac5dbd75d3a2a1dc27070f22dfc91ad5853903fae235a437ed9188d1d88d34e",
          "sha1": "aef7aefa1299aef402d11906d0c6a07d857122cc",
          "md5": "ae7bba1ca93c54fb70136f6f1a44aefb"
        }
      ]
    }
  ]
}
