{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "b5d11da",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-b5d11da.jar",
          "url": "antibytes-custom-component-b5d11da.jar",
          "size": 16534,
          "sha512": "ed5eaac39ee4631650f4e5d7c1e269b0e6b4a6d7e1e55a9868cd2177d33b932870907939a7883c70e40ee4185a8bf3184fb3fa27a0c7dc1de7130591e9dc00bd",
          "sha256": "8e3c12e92707bf28446f7931bfa8189abfd5caee3543466748cad152c27fe1b3",
          "sha1": "4e5afac33e53cc6d8a3e8e0287010c32014a2f38",
          "md5": "2956c4ce7ab31c7fb14aabf3800d0d36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-b5d11da.jar",
          "url": "antibytes-custom-component-b5d11da.jar",
          "size": 16534,
          "sha512": "ed5eaac39ee4631650f4e5d7c1e269b0e6b4a6d7e1e55a9868cd2177d33b932870907939a7883c70e40ee4185a8bf3184fb3fa27a0c7dc1de7130591e9dc00bd",
          "sha256": "8e3c12e92707bf28446f7931bfa8189abfd5caee3543466748cad152c27fe1b3",
          "sha1": "4e5afac33e53cc6d8a3e8e0287010c32014a2f38",
          "md5": "2956c4ce7ab31c7fb14aabf3800d0d36"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-custom-component-b5d11da-javadoc.jar",
          "url": "antibytes-custom-component-b5d11da-javadoc.jar",
          "size": 261,
          "sha512": "5fb018925204ebddf7baf1e2aad24ae878e12834ca31a0cc9339a5dd46b1b332aa7735831f475583c525224dc83e38ac92933a1c4328016d952bdae79ced60ab",
          "sha256": "66b21f365b772a8b52e4330e24df691bf81f6361b7ab9c6d630c70220464aa4a",
          "sha1": "f76e5f2d100639751d1a3a54fd9ac55af6ac19b3",
          "md5": "601128750a7dc37997e71e7e1a36cfa3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-custom-component-b5d11da-sources.jar",
          "url": "antibytes-custom-component-b5d11da-sources.jar",
          "size": 3352,
          "sha512": "b18096d782e69f35e9431806bff4b9e2d158b95fc7cd5e114ffdb0614ec988828769a485a20bd56c00aba966f75712b859b75d0e66d91a3d624547e6e591341e",
          "sha256": "3033fa56bf3fe65c047ec48dd72954ccb9e1dc0eb073e754965cea2f9e37f97a",
          "sha1": "463c4e1665c72d7c298943758744e9b19833a2cf",
          "md5": "e6b1706728cb57c13178a839212650e1"
        }
      ]
    }
  ]
}
