{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/b6c6e6c/test-utils-b6c6e6c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "b6c6e6c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-tvossimulatorarm64-b6c6e6c.klib",
          "size": 8438,
          "sha512": "3a3ecc5118412c91c4903abc0b9f13d1bc39ac7b7c5e977be4099dda604935338d978ee06698f5a358ce5345fc98260ce020be1df67e268e307362f44a750c97",
          "sha256": "e57c9014ed9e45c65519a184c41609ba7c1ff329cb19144e4774291dbb2c1761",
          "sha1": "c71f5ceef4eff058c215a5c7139f09d989546546",
          "md5": "196896799376c036bd5e80dde611d98a"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-tvossimulatorarm64-b6c6e6c-sources.jar",
          "url": "test-utils-tvossimulatorarm64-b6c6e6c-sources.jar",
          "size": 2202,
          "sha512": "200f256b59ba175210138bed146ee54ab58c9bb91f071774698eb6b3f4920f792214d2d44a1cc764422cb2c09da1a0773d4d288080e067e60263b96f2ed68050",
          "sha256": "9e0bd104bc203c511c12aaf2143514ee32a59c775ece92a04e7ee764ee60affa",
          "sha1": "773bcb344a1f6fd820f6ee6e62aea2b59ecfa180",
          "md5": "8b3c7f259a640a3d1e2ffd34b7f29645"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-tvossimulatorarm64-b6c6e6c-metadata.jar",
          "url": "test-utils-tvossimulatorarm64-b6c6e6c-metadata.jar",
          "size": 261,
          "sha512": "cb751b7b5cf0ee95c90f634d9f2f29a3a54d91d87d8cd56b8e4788881e0f71eea1ee6d6c85341d9b6f1878debc23c03fcb2131e6209a0deab9dc4c8908a0f019",
          "sha256": "c9647eb1e84b0d9d97761b2d0a228c6844f541f42adad29a8706e491078a62fd",
          "sha1": "acc78af09009ae70b73948d2db3feefd871fd81d",
          "md5": "e4543914f3815f6f32ad7f2dcf9dd788"
        }
      ]
    }
  ]
}
