{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "c1aadb7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-c1aadb7.jar",
          "url": "kmock-gradle-c1aadb7.jar",
          "size": 49785,
          "sha512": "7014c630cf6409ace3f053ceab81ebc99558901905d6d3745d3e402542766f7909f1dcc2085ba878205e3cc2e3f49ccab8ceeb66b0f43c1ecd012cb623dfc690",
          "sha256": "fd9ae655ff33610eb7c1e9a5a593850cfd3c5407a13760b0ff1245a9810cba92",
          "sha1": "20a6bba4c8c0de4ac47abbe987c80e901b6b6637",
          "md5": "6a0cefb26b488253dbbd9506e80ab720"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-c1aadb7.jar",
          "url": "kmock-gradle-c1aadb7.jar",
          "size": 49785,
          "sha512": "7014c630cf6409ace3f053ceab81ebc99558901905d6d3745d3e402542766f7909f1dcc2085ba878205e3cc2e3f49ccab8ceeb66b0f43c1ecd012cb623dfc690",
          "sha256": "fd9ae655ff33610eb7c1e9a5a593850cfd3c5407a13760b0ff1245a9810cba92",
          "sha1": "20a6bba4c8c0de4ac47abbe987c80e901b6b6637",
          "md5": "6a0cefb26b488253dbbd9506e80ab720"
        }
      ]
    }
  ]
}
