{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/fc88d6a/test-utils-annotations-junit4-fc88d6a.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "fc88d6a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-watchossimulatorarm64-fc88d6a.klib",
          "size": 11474,
          "sha512": "3b4b536cdad4219d7b95390a21d49502b432ae1861bf807a154ada16c16c4557cab3ff29354af0f55faa4ae3eba89c359e521c0d29c5ab75aa6b01f4742a00ab",
          "sha256": "0d1644cd3220707f02b9838ee2bc02ecf0e929ef8952b4c1ea419c1a54c6a309",
          "sha1": "5f31a3a8565676168d35d02994ca4751e1294abe",
          "md5": "7f42d9a50c67ea6d3f69543f4298f6d0"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-watchossimulatorarm64-fc88d6a-metadata.jar",
          "url": "test-utils-annotations-junit4-watchossimulatorarm64-fc88d6a-metadata.jar",
          "size": 261,
          "sha512": "b1d1e53624a4dcf459f2aaefd48171d5596217f68d3783919513c027294a89e063d47aaf9b05a7d5a84f4cb2f12d05773591a66d31a7967ee8fe8a4061290cc5",
          "sha256": "c43bc612d3975242d39d8afd461a38f5b28a7e947838f26c94ea2b81a79e667a",
          "sha1": "96adcead2886a8da9f743ffc6a590df615ed5a80",
          "md5": "30c510bdd7e028c643b92362018c1de2"
        }
      ]
    }
  ]
}
