{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.settings",
    "module": "antibytes-dependency-settings",
    "version": "0e82305",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "0e82305"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-0e82305.jar",
          "url": "antibytes-dependency-settings-0e82305.jar",
          "size": 15130,
          "sha512": "e647dc18f5d5654d6c7fced5f9f09371198df42a8f58d19721e6915c51aa1030576e92965291f6f12001e3df8d081630aeed8767c82a3062f3ac5265563c2321",
          "sha256": "35933c4858e84ef2b3cef3abea45bda86e12350ab3d63c4f693e4c5309a03216",
          "sha1": "d0342dbe42bdb864eeeb563b78e4681c03f6f79d",
          "md5": "f4d3854582daf339b1d32257f40176df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "0e82305"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-0e82305.jar",
          "url": "antibytes-dependency-settings-0e82305.jar",
          "size": 15130,
          "sha512": "e647dc18f5d5654d6c7fced5f9f09371198df42a8f58d19721e6915c51aa1030576e92965291f6f12001e3df8d081630aeed8767c82a3062f3ac5265563c2321",
          "sha256": "35933c4858e84ef2b3cef3abea45bda86e12350ab3d63c4f693e4c5309a03216",
          "sha1": "d0342dbe42bdb864eeeb563b78e4681c03f6f79d",
          "md5": "f4d3854582daf339b1d32257f40176df"
        }
      ]
    }
  ]
}
