{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "7dc619f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-7dc619f.jar",
          "url": "antibytes-versioning-7dc619f.jar",
          "size": 24286,
          "sha512": "1aa04e5756fa5ab939d97b31efa8b16185bf214b038f98ce5b6381bed4254bce0909c7c0a4a39622a0cc9dbff0db3c3c4bdb404b47d855033f3faa8b85629ee8",
          "sha256": "7d59a4d27cafb5de0b820a1bf4bf3e053582c456be9e86eb05a7cb047b171acd",
          "sha1": "2f1bfc4118bbf9d20f5a6bdb953c01bd1943955a",
          "md5": "71a46f89b58040d59f900cf6c17551a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-7dc619f.jar",
          "url": "antibytes-versioning-7dc619f.jar",
          "size": 24286,
          "sha512": "1aa04e5756fa5ab939d97b31efa8b16185bf214b038f98ce5b6381bed4254bce0909c7c0a4a39622a0cc9dbff0db3c3c4bdb404b47d855033f3faa8b85629ee8",
          "sha256": "7d59a4d27cafb5de0b820a1bf4bf3e053582c456be9e86eb05a7cb047b171acd",
          "sha1": "2f1bfc4118bbf9d20f5a6bdb953c01bd1943955a",
          "md5": "71a46f89b58040d59f900cf6c17551a0"
        }
      ]
    }
  ]
}
