{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "de4d813",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-de4d813.jar",
          "url": "antibytes-grammar-tools-de4d813.jar",
          "size": 59182,
          "sha512": "44068de64813b7653a93dfaa99be8b8b6de38037a9dddac9970534fbc05c43648c3d025371159d378d545a1aa4ca6a66a74f9f069993db12748d44a3bc8e1b38",
          "sha256": "1f7a5880e0d0ff95ea3ed488b1d99a68ad291f27e24eab22fd7d8ba151d436a9",
          "sha1": "9c23e478ed0c850f15d2f1d2784cbde23b1a4697",
          "md5": "6c49a427ec52726eaa380436e3c801a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-de4d813.jar",
          "url": "antibytes-grammar-tools-de4d813.jar",
          "size": 59182,
          "sha512": "44068de64813b7653a93dfaa99be8b8b6de38037a9dddac9970534fbc05c43648c3d025371159d378d545a1aa4ca6a66a74f9f069993db12748d44a3bc8e1b38",
          "sha256": "1f7a5880e0d0ff95ea3ed488b1d99a68ad291f27e24eab22fd7d8ba151d436a9",
          "sha1": "9c23e478ed0c850f15d2f1d2784cbde23b1a4697",
          "md5": "6c49a427ec52726eaa380436e3c801a7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-de4d813-javadoc.jar",
          "url": "antibytes-grammar-tools-de4d813-javadoc.jar",
          "size": 261,
          "sha512": "9eaca56e1f2bcb2f7395e839cd50bf67aca01d2da35f148efbc9dc7825b59a86f215dbc2cece99167a25dcff4b9d54f7fd90caea3975c5901a2de51d76f974ce",
          "sha256": "d461a4f2876c34552128bbd1f483b701290b6b8068f3edf1dd6c74d153e9a5c2",
          "sha1": "258ab8ffe6edd0916ed2d13fdb7392eb437689ad",
          "md5": "81beeb733d4c5d986a96e23d9a798444"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-de4d813-sources.jar",
          "url": "antibytes-grammar-tools-de4d813-sources.jar",
          "size": 12245,
          "sha512": "1c4161da39f8b11e1799b8f06b03c1bc88d590169feb2e72b5de5f9b4d5ce41bbb89c8196dcbbb7e26b1299e615d448d1d12b367f64e143f4b5df4e501b52221",
          "sha256": "6ffb0b0c4c976082c9ce911989206169884e229855c9bf1ca120335d177b6546",
          "sha1": "61100e1f884a0e0b637f24df288c5bbbd115c75e",
          "md5": "f2ae5f010f5c01873d302435d1dff455"
        }
      ]
    }
  ]
}
