{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1-SNAPSHOT/core-0.3.1-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosx64-0.3.1-SNAPSHOT.klib",
          "size": 110162,
          "sha512": "ffe86ef047f66734997f444d7be2e8c1d1a5aef87a6f2380669557204b8d8e2162c476ea3917d2761f504d47bc2aebfd96272b92df7a3ce9763c3bb9699aa7ef",
          "sha256": "f478fbfd1de275ab1629e0395fcfdf5d5c9503e89c75d242767597ed6d77e5b3",
          "sha1": "1692bea11ddfd2439ad3f9c27c2b2cbc6f8d491c",
          "md5": "5530ca0c9522f92c97fd60154673f3e9"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.3.1-SNAPSHOT-metadata.jar",
          "url": "core-iosx64-0.3.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "0d1cfdc3595546df7eebe2a11d84d402b1b5d3410b401014045ab995bfb81561034866a4ded32f4f9931bec42218edaddcdebe295cef4dfd438523d09682276e",
          "sha256": "58ac252ea5e0fce5a0df7cce8503dd2f45bf566504ee77d91eac729633a530d8",
          "sha1": "d77da2c3db67a3736f2cde0fb7d61988bd6cfc11",
          "md5": "f126444c5f857b397f2254260cb57579"
        }
      ]
    }
  ]
}
