{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1-SNAPSHOT/core-0.3.1-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosx64-0.3.1-SNAPSHOT.klib",
          "size": 110182,
          "sha512": "143bc4c59d99954e326df52f1b0e6cd88f35265a19b3d7d4f4082a5c9c8df795879e73421e99b698da4ee140bbfa9947bffd9596e283a35e56b323f86197920f",
          "sha256": "1547469ed1c53e9d41b87c611814fff814aa3d7f443af0cd2007e95915c24036",
          "sha1": "732daadfb85a3a2b372119f6bfb07e5f0e22328d",
          "md5": "f5605e937d2c079f02c51a0895485ff6"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.3.1-SNAPSHOT-metadata.jar",
          "url": "core-iosx64-0.3.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "9eadef890f59ab292a8f235a3711739bce470bcca3ec561485ec13d7069a6b0bc1c3bcdcda069c06bbb8f9e53151c7c82b5b586916fd4d92bcba11fa454c2310",
          "sha256": "178ddf72f161e42d3985495a98be2ff8e09ab8b48d1968eac3728176c1798dda",
          "sha1": "4334fefc27990802a4cca94f198078ac362b9624",
          "md5": "0ddb0374c64f7bc63bc691e605c3c7dd"
        }
      ]
    }
  ]
}
