{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/27ceceb/test-utils-ktor-27ceceb.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "27ceceb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-27ceceb.klib",
          "url": "test-utils-ktor-js-27ceceb.klib",
          "size": 11802,
          "sha512": "af722a6d353ae68291fde77069d46eb85be328bfa7dc950ef5be80ed3cd1c635ac7367c2fc4555f701b15a70f72c86f2c48230672b8c9344b163c3216e8b2624",
          "sha256": "b71547ccc4a673c3a3481d84c9fed2e96172270c80a25929a5d375f8d6322057",
          "sha1": "cc71fee034f688e4ab586074f90d91358dd4d1ba",
          "md5": "38cf9ce44c8b772794f88704fcf5cdc9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-27ceceb.klib",
          "url": "test-utils-ktor-js-27ceceb.klib",
          "size": 11802,
          "sha512": "af722a6d353ae68291fde77069d46eb85be328bfa7dc950ef5be80ed3cd1c635ac7367c2fc4555f701b15a70f72c86f2c48230672b8c9344b163c3216e8b2624",
          "sha256": "b71547ccc4a673c3a3481d84c9fed2e96172270c80a25929a5d375f8d6322057",
          "sha1": "cc71fee034f688e4ab586074f90d91358dd4d1ba",
          "md5": "38cf9ce44c8b772794f88704fcf5cdc9"
        }
      ]
    }
  ]
}
