{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.publishing",
    "module": "antibytes-publishing-configuration",
    "version": "601dc8e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-configuration-601dc8e.jar",
          "url": "antibytes-publishing-configuration-601dc8e.jar",
          "size": 4888,
          "sha512": "9aefedcbc265996d37eeaefd0becfdc0a74a2a79a897dc17f4aa1428dae9dfb0da027b3b6d27404105261478cd89b8e7518f73af84bd4b9ca94f2f819c02da4a",
          "sha256": "c29e7b85916e1a467bceafd45545b4d501744dcbb8b6e19154ea65f3b5533138",
          "sha1": "f1c4e1e0c795d93b0f3b4743fe1483f782d9f5a2",
          "md5": "f7721e3d3cd2571e7a9db80a72249d53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.publishing",
          "module": "antibytes-publishing",
          "version": {
            "requires": "601dc8e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-configuration-601dc8e.jar",
          "url": "antibytes-publishing-configuration-601dc8e.jar",
          "size": 4888,
          "sha512": "9aefedcbc265996d37eeaefd0becfdc0a74a2a79a897dc17f4aa1428dae9dfb0da027b3b6d27404105261478cd89b8e7518f73af84bd4b9ca94f2f819c02da4a",
          "sha256": "c29e7b85916e1a467bceafd45545b4d501744dcbb8b6e19154ea65f3b5533138",
          "sha1": "f1c4e1e0c795d93b0f3b4743fe1483f782d9f5a2",
          "md5": "f7721e3d3cd2571e7a9db80a72249d53"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-publishing-configuration-601dc8e-javadoc.jar",
          "url": "antibytes-publishing-configuration-601dc8e-javadoc.jar",
          "size": 261,
          "sha512": "3e765059eeee7b5d22557372acc147576b30ddc79bdad94245ea2c86d9087f339ec0fd521f342108f3451244b5badb152ee09adcbbe5e0c7f7711d6cbc29babd",
          "sha256": "feccacacd72e0978ee4f72605df980b5eae7efa0de437ec7c37c032f39093272",
          "sha1": "327d4c357ee6272ab6237f14e11da47a5008fd61",
          "md5": "fcea5a4a72e6e7ca02915fd285169c55"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-publishing-configuration-601dc8e-sources.jar",
          "url": "antibytes-publishing-configuration-601dc8e-sources.jar",
          "size": 2031,
          "sha512": "949936ee8e7841e68a996aff0edc1418cd3d1946b8ed65eed9b3408b0395776fbb94094bfd6343ac4a5251ee80a82b33e2faab5712ea326dc22651492a2086e8",
          "sha256": "75bf8fb3cd3044ebe8481f9c5e57b7575469974aa516b9168318b5e0ceb1e378",
          "sha1": "48c77b849a9fd04d71207a17148723b498ba025e",
          "md5": "655bc2dfcf8349efa04b5c4fcc11421e"
        }
      ]
    }
  ]
}
