{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/1540b3c/kmock-1540b3c.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "1540b3c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosx64-1540b3c.klib",
          "size": 120057,
          "sha512": "325f1c58695a9367f0e9bfa694983f168409030ad8f626203ade5e27c1856c29427a822e111cfc91c6fd891082076eecf9aee87cddbff89e89b2aa44a6b7dfa7",
          "sha256": "dd6b7d03bde15c58e78f588b6f516f94e1185384e8c1399f8fdfce6cdc3354da",
          "sha1": "24839dc04fbe216aefdd0471d496aab8f4e4f6e7",
          "md5": "80467bb0d03309e711e46c2be625bd08"
        }
      ]
    }
  ]
}
