{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/8066bd0/test-utils-annotations-junit5-8066bd0.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "8066bd0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-watchosarm64-8066bd0.klib",
          "size": 7086,
          "sha512": "5375c934c293382a66ed350449d350206980273045a93130135db1067ee4d254812b2b34ea02d72617f5ff8f82f597b7eab8b7b3f8c4c822bdd3607c34c249a6",
          "sha256": "1432ca394b02f768ce4d7c31117de8116da79ade416cc2a79c33875f09ce239a",
          "sha1": "dccf6ffa23d7083d2b04feaba2746674f7b48b99",
          "md5": "30a4505ceaa9c4c1e2810c9254ef6461"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-watchosarm64-8066bd0-metadata.jar",
          "url": "test-utils-annotations-junit5-watchosarm64-8066bd0-metadata.jar",
          "size": 261,
          "sha512": "983cc76b4937f219408adcea50da0120067a21d0dab720fb65703eee17f3fd906016d2a5c45f9598365a1f7a90d978fdace6811251b2baa229508ca499b8a5a0",
          "sha256": "5db01143686513eec7d516577e21b383f26e7aeb571913a46e12fe761882f5a9",
          "sha1": "ff0c2deabdddc7fb44a5f0177069cc933b734085",
          "md5": "94d2bec666fd8720a1ac6623627f91e5"
        }
      ]
    }
  ]
}
