{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "3d1fb1f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-3d1fb1f.jar",
          "url": "antibytes-android-application-configuration-3d1fb1f.jar",
          "size": 58039,
          "sha512": "a3c2aeb854659663711ebf0484f62d5a5562d1f0d8cffd4be049bc3b542c628a0dc5d01ef8ac86d7a7136e69c21b66fb14341538b643db1efe1f18d291010423",
          "sha256": "ecde8845b1b7e393f72fd9bc45a591fb21148b0d531fd89d617cabc09511777b",
          "sha1": "7a71e4d8814b728e04acf0bc7ca43a8275ff80e1",
          "md5": "2343780e64ee6698b4ad6fde5a6cc42a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "3d1fb1f"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-3d1fb1f.jar",
          "url": "antibytes-android-application-configuration-3d1fb1f.jar",
          "size": 58039,
          "sha512": "a3c2aeb854659663711ebf0484f62d5a5562d1f0d8cffd4be049bc3b542c628a0dc5d01ef8ac86d7a7136e69c21b66fb14341538b643db1efe1f18d291010423",
          "sha256": "ecde8845b1b7e393f72fd9bc45a591fb21148b0d531fd89d617cabc09511777b",
          "sha1": "7a71e4d8814b728e04acf0bc7ca43a8275ff80e1",
          "md5": "2343780e64ee6698b4ad6fde5a6cc42a"
        }
      ]
    }
  ]
}
