{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.4.0-SNAPSHOT.klib",
          "size": 105923,
          "sha512": "f201b335872042436de1ab78e34e9d457a26deb6796f4830318a8f88e93825876284e4e9c59ee2e6672026494e4fc1c15a6d4af9ceae9a27aea40ba32bd2875c",
          "sha256": "9c7a60ba522a6fc2c7595c62f18e9bc937ae555afef5219a86ece7c357a96c43",
          "sha1": "7a04126c30738c5072e1940d17c2192c810366a2",
          "md5": "097fd14063df40d2c8b4e1e3edd9f883"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.4.0-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4921119dd464c7b610a27b464af24931e361133f18736adb2f909cfbceec557be003d32d7df75154140fb1d811169ef3fd29966aa4a6bfb9d22e4bfe00f3baf7",
          "sha256": "128856fd6834417a9ff9d6af8cc413f12b77fb8d7f3f8b7c0261bfbb4c07e742",
          "sha1": "fd59b65819024605e48312bf2c52de115490ec19",
          "md5": "90b96ef27ae22a2908124dfd13d0f6eb"
        }
      ]
    }
  ]
}
