{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.2.1-SNAPSHOT/kmock-0.2.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.2.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.2.1-SNAPSHOT.jar",
          "size": 395086,
          "sha512": "e0ae1ba89cc4fb3b7771bc174ae2c7ce050e9983096d05a730f45f5a823e0150a016a9e6cb1ef6e0aed0934bc4fb2e99032d39a239d39e333f0c097397d752e8",
          "sha256": "ae1e157e79d36d9cdc89ad0f2a92cbdd104c445d1079b71cb70102c564bda060",
          "sha1": "df2c785966033c46b210a8c892646aa2321fda12",
          "md5": "2f039e349941f3d30ffbc1ba8fdd2ebf"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.2.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.2.1-SNAPSHOT.jar",
          "size": 395086,
          "sha512": "e0ae1ba89cc4fb3b7771bc174ae2c7ce050e9983096d05a730f45f5a823e0150a016a9e6cb1ef6e0aed0934bc4fb2e99032d39a239d39e333f0c097397d752e8",
          "sha256": "ae1e157e79d36d9cdc89ad0f2a92cbdd104c445d1079b71cb70102c564bda060",
          "sha1": "df2c785966033c46b210a8c892646aa2321fda12",
          "md5": "2f039e349941f3d30ffbc1ba8fdd2ebf"
        }
      ]
    }
  ]
}
