{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "a5c6f90",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-a5c6f90.jar",
          "url": "antibytes-dependency-a5c6f90.jar",
          "size": 71469,
          "sha512": "63ae705008d1093c2b3c9d8e7425458d6514caf3fdf14f3604d83b4aa37e8dbb7da5e5d05a418ed5ee360c86b53c8b70c7507e540ca5ecf2ff91c2a782875f2c",
          "sha256": "47c69f57bbed25a901f9084131ba8ac1a114ea9f82d650ce722dd6aaea041c62",
          "sha1": "e6d4f75f1a1cd56d4b44fa46bfd19c7bcd027313",
          "md5": "913d9a4ef991eb1e9268ed2888402933"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-gradle-plugin",
          "version": {
            "requires": "0.17.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.44.0"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "a5c6f90"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-a5c6f90.jar",
          "url": "antibytes-dependency-a5c6f90.jar",
          "size": 71469,
          "sha512": "63ae705008d1093c2b3c9d8e7425458d6514caf3fdf14f3604d83b4aa37e8dbb7da5e5d05a418ed5ee360c86b53c8b70c7507e540ca5ecf2ff91c2a782875f2c",
          "sha256": "47c69f57bbed25a901f9084131ba8ac1a114ea9f82d650ce722dd6aaea041c62",
          "sha1": "e6d4f75f1a1cd56d4b44fa46bfd19c7bcd027313",
          "md5": "913d9a4ef991eb1e9268ed2888402933"
        }
      ]
    }
  ]
}
