{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/dd59a45/test-utils-coroutine-dd59a45.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "dd59a45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosarm64-dd59a45.klib",
          "size": 10123,
          "sha512": "10c9db4f0c9b4635abbaaff580006a3f64bf8194ac79491fc55f3b844fca94679282b33c38e59715b35dd2b35cb9a3af3f1ebda5a4980f0bd78ec2cfc5fca7dd",
          "sha256": "72564496fea31c8d738cff0910d76580b18684e25e71aa3277d7e20ad4334d2b",
          "sha1": "e1f1ffd87962052fd9a1f50fee397285144fcaeb",
          "md5": "dc1e56df809dc42d2927a364000c8274"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosarm64-dd59a45-metadata.jar",
          "url": "test-utils-coroutine-iosarm64-dd59a45-metadata.jar",
          "size": 261,
          "sha512": "eb3c0c97fda1bc2f582b4d9b6b55ec7f308ab4f14009c3f3ff5855bf500e0ef5628e2fbdb6743112ae30936262adb238bea5e3a0673a8794bec4f992cec534ac",
          "sha256": "138a3d25cbc62e3f4211497a77cc484bf7a4e032f45f3c24930116c02be90049",
          "sha1": "5026f3c532c4515425befff3f3e78830d78464b7",
          "md5": "7988d63338a1ed678d4d870a63280923"
        }
      ]
    }
  ]
}
