{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/3948768/test-utils-annotations-3948768.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "3948768",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm-3948768.jar",
          "url": "test-utils-annotations-jvm-3948768.jar",
          "size": 10872,
          "sha512": "af2e3d93af3dc827835663aca106c2d05bdb984a396c7ca59cc29ebc204b78453b2b1d4f9c999fe409c00ae1ebb202925de0d521f833cdc533ca9bfca34f8b90",
          "sha256": "288799cafbeff6f02a0beb6e24f74205ef67ebdafad4c7ccf9dcb7e2f551e3f0",
          "sha1": "38a1ef288c1dba049afe173ad3b90ebebccea850",
          "md5": "fca279cbb20c74e44f20028b7d871fd9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm-3948768.jar",
          "url": "test-utils-annotations-jvm-3948768.jar",
          "size": 10872,
          "sha512": "af2e3d93af3dc827835663aca106c2d05bdb984a396c7ca59cc29ebc204b78453b2b1d4f9c999fe409c00ae1ebb202925de0d521f833cdc533ca9bfca34f8b90",
          "sha256": "288799cafbeff6f02a0beb6e24f74205ef67ebdafad4c7ccf9dcb7e2f551e3f0",
          "sha1": "38a1ef288c1dba049afe173ad3b90ebebccea850",
          "md5": "fca279cbb20c74e44f20028b7d871fd9"
        }
      ]
    }
  ]
}
