{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "67e17ce",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-67e17ce.jar",
          "url": "antibytes-gradle-test-utils-67e17ce.jar",
          "size": 15099,
          "sha512": "4259b879dc386ad75f6c990a46a17b7e7279d97589606445d07e361ce3de857a67bfacad4a9b5603763d713b7837f48a3d3e1a8798d144735ac5735ac0ad9a7e",
          "sha256": "0a55f87be0faee8145d1bc5b5df698a856e2acd0f9dcc759a6e269cdf3700233",
          "sha1": "8c6f5cc99564e89c3bade58a554c5628c5bac14f",
          "md5": "060500c17c923055164190cc3a391b74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-67e17ce.jar",
          "url": "antibytes-gradle-test-utils-67e17ce.jar",
          "size": 15099,
          "sha512": "4259b879dc386ad75f6c990a46a17b7e7279d97589606445d07e361ce3de857a67bfacad4a9b5603763d713b7837f48a3d3e1a8798d144735ac5735ac0ad9a7e",
          "sha256": "0a55f87be0faee8145d1bc5b5df698a856e2acd0f9dcc759a6e269cdf3700233",
          "sha1": "8c6f5cc99564e89c3bade58a554c5628c5bac14f",
          "md5": "060500c17c923055164190cc3a391b74"
        }
      ]
    }
  ]
}
