{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "4e0b439",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-4e0b439.jar",
          "url": "antibytes-dependency-node-4e0b439.jar",
          "size": 21501,
          "sha512": "d5a9bad3c886d203a9da72d228d0d39cea943985a90ddd21c013253cc08a1aeb73aaf1ae129ed87cbf1e48fbf02f16f303c9b8dbfe3b8b40b8326680ecbd9e47",
          "sha256": "81f93f6cc939a80b1e08fd3b5c919ef7d85e4e5661d7da48b6a3039052c6e4f9",
          "sha1": "2836f7bd4cfa0afb92cf90fb515ebaeda54f6c83",
          "md5": "0303573751462a4961e58636b6f821fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-4e0b439.jar",
          "url": "antibytes-dependency-node-4e0b439.jar",
          "size": 21501,
          "sha512": "d5a9bad3c886d203a9da72d228d0d39cea943985a90ddd21c013253cc08a1aeb73aaf1ae129ed87cbf1e48fbf02f16f303c9b8dbfe3b8b40b8326680ecbd9e47",
          "sha256": "81f93f6cc939a80b1e08fd3b5c919ef7d85e4e5661d7da48b6a3039052c6e4f9",
          "sha1": "2836f7bd4cfa0afb92cf90fb515ebaeda54f6c83",
          "md5": "0303573751462a4961e58636b6f821fe"
        }
      ]
    }
  ]
}
