{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "1c6105d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-1c6105d.toml",
          "url": "antibytes-dependency-catalog-1c6105d.toml",
          "size": 249686,
          "sha512": "7fa293d6122cdc0f4d1dfcf36a2bb48db64e6f72d9989f9274577d54a3873e3a9ae706ba15f69e8457a8a18441bc2c6c67b6848cdaf366e33654f02a9857d757",
          "sha256": "5db589061650eb09498d5a597d0efca2dace708ac3548f6b7d80b8b077cc2add",
          "sha1": "9177ea10756e5dd8af9527aff9b5fda410be74af",
          "md5": "f9b1673bee13f84dfa3fee8b2ac8b7a7"
        }
      ]
    }
  ]
}
