{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "a775936",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-a775936.jar",
          "url": "antibytes-configuration-a775936.jar",
          "size": 49663,
          "sha512": "e3ea11268ba9f748ea47cfabe65b395a518ce24341657d3dac609a342f60dc3abf343ea83cca2bf3da7bd6792c5f8284d3d0cf8f54379be86623bc356d6863db",
          "sha256": "3c7d76873128416bed6b8bc3529bad8c2b5d9ed33e3a96ad79f2578d2799b69d",
          "sha1": "7b9074f75d00ac456501b983f1351dcda3192bc8",
          "md5": "d0af12f19c711f66e590405f3b179fbb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "a775936"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-a775936.jar",
          "url": "antibytes-configuration-a775936.jar",
          "size": 49663,
          "sha512": "e3ea11268ba9f748ea47cfabe65b395a518ce24341657d3dac609a342f60dc3abf343ea83cca2bf3da7bd6792c5f8284d3d0cf8f54379be86623bc356d6863db",
          "sha256": "3c7d76873128416bed6b8bc3529bad8c2b5d9ed33e3a96ad79f2578d2799b69d",
          "sha1": "7b9074f75d00ac456501b983f1351dcda3192bc8",
          "md5": "d0af12f19c711f66e590405f3b179fbb"
        }
      ]
    }
  ]
}
