{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/dbba7bb/test-utils-annotations-junit4-dbba7bb.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "dbba7bb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-watchossimulatorarm64-dbba7bb.klib",
          "size": 11474,
          "sha512": "3b4b536cdad4219d7b95390a21d49502b432ae1861bf807a154ada16c16c4557cab3ff29354af0f55faa4ae3eba89c359e521c0d29c5ab75aa6b01f4742a00ab",
          "sha256": "0d1644cd3220707f02b9838ee2bc02ecf0e929ef8952b4c1ea419c1a54c6a309",
          "sha1": "5f31a3a8565676168d35d02994ca4751e1294abe",
          "md5": "7f42d9a50c67ea6d3f69543f4298f6d0"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-watchossimulatorarm64-dbba7bb-metadata.jar",
          "url": "test-utils-annotations-junit4-watchossimulatorarm64-dbba7bb-metadata.jar",
          "size": 261,
          "sha512": "5e27d2118c1cbdc4e5063e514ad494da0dad0abf057063f4bbd3ad8f3aebbe79f204797747f602d9be0c1b59a03b04a4b9aab0810e6e3a833431c464f0694693",
          "sha256": "a526c4eae05043aec4948b5caef7dc5cbefa99496414642c4a1188ab23d9b33f",
          "sha1": "c17ba44eebb78a8df8d873659a39c6f7fa5dcc92",
          "md5": "06a236c57db2ce73716688fdc27ffce9"
        }
      ]
    }
  ]
}
