{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "999693f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-999693f.jar",
          "url": "antibytes-dependency-helper-999693f.jar",
          "size": 68558,
          "sha512": "01dd6dede470227fe5fb45c804fb3a6ebffbfb54cafb4c7dc332781f823e0033e31faa27b160fcb5b126a6b1fae709642e5646415a5c87ab6e6b9746c4b85424",
          "sha256": "3277e038ce94f264382b051c960ac34967a87072610a6863d43785b370982886",
          "sha1": "aa8f762d236c13af7d31739295fa10b44d3349e6",
          "md5": "272934c326b817cd3f65efb93bbfb904"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "999693f"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-999693f.jar",
          "url": "antibytes-dependency-helper-999693f.jar",
          "size": 68558,
          "sha512": "01dd6dede470227fe5fb45c804fb3a6ebffbfb54cafb4c7dc332781f823e0033e31faa27b160fcb5b126a6b1fae709642e5646415a5c87ab6e6b9746c4b85424",
          "sha256": "3277e038ce94f264382b051c960ac34967a87072610a6863d43785b370982886",
          "sha1": "aa8f762d236c13af7d31739295fa10b44d3349e6",
          "md5": "272934c326b817cd3f65efb93bbfb904"
        }
      ]
    }
  ]
}
