{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/b67f120/test-utils-coroutine-b67f120.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "b67f120",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iossimulatorarm64-b67f120.klib",
          "size": 10215,
          "sha512": "20f8faf97ffe763f21a5727be08c7cc050477ad101cf5fcf7173e9ddbe61e09ad64024ed4ac84f526406d32dada6786171cb15ed0140b91d8c0099e9b3e42c52",
          "sha256": "b5ee960a0de26f99ed0dae68d0108fc1f8a3ffb5ce966589d0682b49fd80510d",
          "sha1": "b306a632a58df0d61fcd0d72b06743ddc98ed3f8",
          "md5": "d0c2d9c2207c602d76d9a6491b30bff1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iossimulatorarm64-b67f120-metadata.jar",
          "url": "test-utils-coroutine-iossimulatorarm64-b67f120-metadata.jar",
          "size": 261,
          "sha512": "98002bc589a5f63b074839d60f323d6ea39902f226eccf8f76503400ff1d1553bb25e2b0dbbd8fda0af3139dd003ad9bdaf416b4eb71242dc54398cd98786418",
          "sha256": "0bd4d1b16ae9e9aa348581886b657907a72233c8ce8afd48105cbab7b06fe941",
          "sha1": "50f6374d0f50a0783b5cffa1bdd916dbee1395f2",
          "md5": "5029d1708529e8e033c1ac51401691c4"
        }
      ]
    }
  ]
}
