{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/ece8407/core-ece8407.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "ece8407",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-ece8407.jar",
          "url": "core-jvm-ece8407.jar",
          "size": 101337,
          "sha512": "de4a9d7bfd883be9dc41c15d0593f7fab48f1c92a26be466e057ca95532f66952dc210d141305729be06afc51dfb5e80856b535fbec88cd4eb36797070bd2a06",
          "sha256": "1454e58b277a2d2bb1cae3ea0b7fad09b9fba1ac9e738759e1da154c85a0b300",
          "sha1": "98c1fae85c8783088c5393ae3397b6fcfd34e385",
          "md5": "ceb312a88a004d05146460ae8ca2e4ac"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-ece8407.jar",
          "url": "core-jvm-ece8407.jar",
          "size": 101337,
          "sha512": "de4a9d7bfd883be9dc41c15d0593f7fab48f1c92a26be466e057ca95532f66952dc210d141305729be06afc51dfb5e80856b535fbec88cd4eb36797070bd2a06",
          "sha256": "1454e58b277a2d2bb1cae3ea0b7fad09b9fba1ac9e738759e1da154c85a0b300",
          "sha1": "98c1fae85c8783088c5393ae3397b6fcfd34e385",
          "md5": "ceb312a88a004d05146460ae8ca2e4ac"
        }
      ]
    }
  ]
}
