{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/7bd994e/test-utils-7bd994e.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "7bd994e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iossimulatorarm64-7bd994e.klib",
          "size": 14405,
          "sha512": "a83f77382284dc34042a29118c65e364fda5f87b90e7f94435bec85fb1decc5cbdcf90700fdb923f9eaaf0b78b510c4e2829431f37750f322971fa5016bab1ab",
          "sha256": "df5c1c6e76e8d90512ebb6607b0347d4c076a929b5c9b1ebe1f919c5f52dbf82",
          "sha1": "bc592cbed3c070d337e93db635b8046bad950758",
          "md5": "764862a43813ad1f5f4681b9d1726518"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iossimulatorarm64-7bd994e-metadata.jar",
          "url": "test-utils-iossimulatorarm64-7bd994e-metadata.jar",
          "size": 261,
          "sha512": "819f0c810c8e2e93e4d0d82fea144861cbf5da596252c5540cbde666f71ef10740e99378b4183af17975c81a6e45f2757518042d2775a4d1e6f5625d273103c1",
          "sha256": "9caae3a2d6a50f9f12f91285de11060fff72cbe580e70f8545e4e0ef3ceb0576",
          "sha1": "aa30e6cf95eb422daab83f1ecec1cd3c9ab6bb0a",
          "md5": "618a3c55a85a9552d4309ca81467f04b"
        }
      ]
    }
  ]
}
