{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/7281fe2/test-utils-coroutine-7281fe2.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "7281fe2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosarm64-7281fe2.klib",
          "size": 10123,
          "sha512": "10c9db4f0c9b4635abbaaff580006a3f64bf8194ac79491fc55f3b844fca94679282b33c38e59715b35dd2b35cb9a3af3f1ebda5a4980f0bd78ec2cfc5fca7dd",
          "sha256": "72564496fea31c8d738cff0910d76580b18684e25e71aa3277d7e20ad4334d2b",
          "sha1": "e1f1ffd87962052fd9a1f50fee397285144fcaeb",
          "md5": "dc1e56df809dc42d2927a364000c8274"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosarm64-7281fe2-metadata.jar",
          "url": "test-utils-coroutine-iosarm64-7281fe2-metadata.jar",
          "size": 261,
          "sha512": "ef5f6c997c98dea33e513d979f3a3bbe8742927869f38c381a5e9a877736e6bad69884d7311d53422b717ad7124ad96c6c405a7772e1fab1c59ec67bf7a4bb70",
          "sha256": "c093bfd4318569ba887aefe6edb664889388a134ee48936feac118c92682a743",
          "sha1": "52aac9d4415cef1700c3a98838640be87f526727",
          "md5": "12c630f7134ef638b397d0b60408f886"
        }
      ]
    }
  ]
}
