{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.2.0-rc01-SNAPSHOT/kmock-0.2.0-rc01-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.2.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.2.0-rc01-SNAPSHOT.jar",
          "url": "kmock-jvm-0.2.0-rc01-SNAPSHOT.jar",
          "size": 383636,
          "sha512": "154cdcf5efbb63566de667f61dd8b97fd9f37ab138f66f725378c675cb4bfe01f5db010da1787882745f2d0f50c513212477e4ccbad940bceec0e3e12919d669",
          "sha256": "ad0df6b0da38e3c4effcca30710bdc71fd5d31777c677d3c567d24ce0da6bca3",
          "sha1": "b49094cbc57a29df6f23706f9763f2f5ffd927d2",
          "md5": "481e8ceff848ba03f46b5ba813c22bee"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.2.0-rc01-SNAPSHOT.jar",
          "url": "kmock-jvm-0.2.0-rc01-SNAPSHOT.jar",
          "size": 383636,
          "sha512": "154cdcf5efbb63566de667f61dd8b97fd9f37ab138f66f725378c675cb4bfe01f5db010da1787882745f2d0f50c513212477e4ccbad940bceec0e3e12919d669",
          "sha256": "ad0df6b0da38e3c4effcca30710bdc71fd5d31777c677d3c567d24ce0da6bca3",
          "sha1": "b49094cbc57a29df6f23706f9763f2f5ffd927d2",
          "md5": "481e8ceff848ba03f46b5ba813c22bee"
        }
      ]
    }
  ]
}
