{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.0-SNAPSHOT/core-0.3.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosx64-0.3.0-SNAPSHOT.klib",
          "size": 99958,
          "sha512": "cf01e577e57aaabe6b5b26992ebcbe05b10f371e27f32e1cc5d34bd0ae2baf952e060e329953bc512c22b5026041fce2e83affc8cddc587e401d56eb8ff33686",
          "sha256": "159a94b8066fa03e93d3868bad280cfd44221f3a2052fa664044f3d723221b4a",
          "sha1": "53cb4654a9782a752016466302d4e04f9d895e5e",
          "md5": "1a56a0bad06fc5acc66e60366c16c24a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.3.0-SNAPSHOT-metadata.jar",
          "url": "core-iosx64-0.3.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4257aa38a59518b889f97f434b85533850f087ab62b79bc6448b8fe9773d6d37859d2036b58f4f2f2568090ad4077a96c4110d7852789c219ef1c97e4fc09d0a",
          "sha256": "b54ed4870d3815d18c24342ef0b00aa83436f8d7cc00ddaf8b734c9272cb2ccf",
          "sha1": "f1dd398c501d9cf4ff9fbde0c22340ade99ea645",
          "md5": "88e73ed7f48c704857c2d80f258ec7af"
        }
      ]
    }
  ]
}
