{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "508b21d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-508b21d.jar",
          "url": "antibytes-gradle-utils-508b21d.jar",
          "size": 9421,
          "sha512": "f5bcaa4b20e640b0ba712d4249c523e48003cdf00fdc5f30eeca980c57f60c0b2fdaa9092e73ad6f24912f4efca8e70f0dff903a05dee0a89704e31c4ada99e6",
          "sha256": "c5c44a3546cb04190ad0e83061939cf609f7b1c06cd40cfeddd03c9f26fe983f",
          "sha1": "62c1ba73bf5383fb09d3b212109ccd5322d666fe",
          "md5": "eebb2a454bcf847813a681f2ef896e41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-508b21d.jar",
          "url": "antibytes-gradle-utils-508b21d.jar",
          "size": 9421,
          "sha512": "f5bcaa4b20e640b0ba712d4249c523e48003cdf00fdc5f30eeca980c57f60c0b2fdaa9092e73ad6f24912f4efca8e70f0dff903a05dee0a89704e31c4ada99e6",
          "sha256": "c5c44a3546cb04190ad0e83061939cf609f7b1c06cd40cfeddd03c9f26fe983f",
          "sha1": "62c1ba73bf5383fb09d3b212109ccd5322d666fe",
          "md5": "eebb2a454bcf847813a681f2ef896e41"
        }
      ]
    }
  ]
}
