{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/b67f120/test-utils-coroutine-b67f120.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "b67f120",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosarm64-b67f120.klib",
          "size": 10129,
          "sha512": "35b514c90d7924051f386b713af1db6f3498cce6fff1721b399759427ff4357415a9d0aa60451287fb65cf5eb6a3fa83a443cb12cbc58aa29d29e96b3d703fe6",
          "sha256": "79c8f739a5068e87f92be4c36c30dfda44bd350019e68a21fe54d318bd820c17",
          "sha1": "a93040db971a59d83fe98682380c7998fecec18f",
          "md5": "fef28cc9f42b966eeda32da41ee99aac"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosarm64-b67f120-metadata.jar",
          "url": "test-utils-coroutine-iosarm64-b67f120-metadata.jar",
          "size": 261,
          "sha512": "98002bc589a5f63b074839d60f323d6ea39902f226eccf8f76503400ff1d1553bb25e2b0dbbd8fda0af3139dd003ad9bdaf416b4eb71242dc54398cd98786418",
          "sha256": "0bd4d1b16ae9e9aa348581886b657907a72233c8ce8afd48105cbab7b06fe941",
          "sha1": "50f6374d0f50a0783b5cffa1bdd916dbee1395f2",
          "md5": "5029d1708529e8e033c1ac51401691c4"
        }
      ]
    }
  ]
}
