{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "4f29d93",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-4f29d93.jar",
          "url": "antibytes-publishing-4f29d93.jar",
          "size": 101115,
          "sha512": "cecc91e7f9e5c91a0b161bd30788cfa087a4486164ad5c1ea1c5e73110b45b6132678f007e52b7fe1ecb95b63525859b7c24bc0e2cd419b2a36ce36497be75c1",
          "sha256": "2b430b67b47498cec10820c7a2544271a3a568c1cd4699870eecdc5104edfd7a",
          "sha1": "e5bc7b0a3bf7cba9afb397a1bd8992ae2422ed64",
          "md5": "8bcdae371e4454a31bb132a7b83aa192"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.13.0.202109080827-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-4f29d93.jar",
          "url": "antibytes-publishing-4f29d93.jar",
          "size": 101115,
          "sha512": "cecc91e7f9e5c91a0b161bd30788cfa087a4486164ad5c1ea1c5e73110b45b6132678f007e52b7fe1ecb95b63525859b7c24bc0e2cd419b2a36ce36497be75c1",
          "sha256": "2b430b67b47498cec10820c7a2544271a3a568c1cd4699870eecdc5104edfd7a",
          "sha1": "e5bc7b0a3bf7cba9afb397a1bd8992ae2422ed64",
          "md5": "8bcdae371e4454a31bb132a7b83aa192"
        }
      ]
    }
  ]
}
