{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "a415edd",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-a415edd.jar",
          "url": "antibytes-dependency-node-a415edd.jar",
          "size": 20149,
          "sha512": "8f2017b204ede12e20e6982eb25c27e177afbe0dc74b644c212adfa545196f28a88fb7c15f00dd509260af3f1056ae1bf837145eb92a52b845103c99b741e1a9",
          "sha256": "529bb6a0042b0e5a08a92d230149a04a1cffce0b1baf0c6b4de9c53b1e5e7837",
          "sha1": "443a0feabf14e3185a1cfafc2f0bd899a9919486",
          "md5": "97a92c02d5599b6942371c0658874913"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-a415edd.jar",
          "url": "antibytes-dependency-node-a415edd.jar",
          "size": 20149,
          "sha512": "8f2017b204ede12e20e6982eb25c27e177afbe0dc74b644c212adfa545196f28a88fb7c15f00dd509260af3f1056ae1bf837145eb92a52b845103c99b741e1a9",
          "sha256": "529bb6a0042b0e5a08a92d230149a04a1cffce0b1baf0c6b4de9c53b1e5e7837",
          "sha1": "443a0feabf14e3185a1cfafc2f0bd899a9919486",
          "md5": "97a92c02d5599b6942371c0658874913"
        }
      ]
    }
  ]
}
