{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc02-SNAPSHOT/kmock-0.3.0-rc02-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc02-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc02-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc02-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "34d856722ed6aa034c60c63f284be493700f5f09ce073336a4323b3ca59d9b4211c909a395cf9c861b1fe69514db06ddf21cc866f435e7d8c5f9a7cd1a625781",
          "sha256": "1ed66000b18c2a1fb9d85cadb3b2e94638ceb896dd46487a408591c0c61520b2",
          "sha1": "f3e34bac75ed618d51440b173d4859f4fef4fa64",
          "md5": "4ffa47aa2623e95b0417285260c2ca67"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc02-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc02-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "34d856722ed6aa034c60c63f284be493700f5f09ce073336a4323b3ca59d9b4211c909a395cf9c861b1fe69514db06ddf21cc866f435e7d8c5f9a7cd1a625781",
          "sha256": "1ed66000b18c2a1fb9d85cadb3b2e94638ceb896dd46487a408591c0c61520b2",
          "sha1": "f3e34bac75ed618d51440b173d4859f4fef4fa64",
          "md5": "4ffa47aa2623e95b0417285260c2ca67"
        }
      ]
    }
  ]
}
