{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc02-SNAPSHOT/kmock-0.3.0-rc02-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc02-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc02-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc02-SNAPSHOT.jar",
          "size": 401239,
          "sha512": "2eae226ae64576e93008e98e2ccf4635a6f98c8dff794436c824b424f191e5dc2f249b9781eb8bc9e5047fd257173f323968d395ae507c6f4a4461a36625e7c8",
          "sha256": "6a2a2348c943bd4c46bb2588a35cf1f37e8f42773cc5dcb92990884456becf7e",
          "sha1": "41a2aca05cb2c6fa147b8e1a752b4661f6fe4890",
          "md5": "838f0ac462cb834c7e757031f13e93a8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc02-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc02-SNAPSHOT.jar",
          "size": 401239,
          "sha512": "2eae226ae64576e93008e98e2ccf4635a6f98c8dff794436c824b424f191e5dc2f249b9781eb8bc9e5047fd257173f323968d395ae507c6f4a4461a36625e7c8",
          "sha256": "6a2a2348c943bd4c46bb2588a35cf1f37e8f42773cc5dcb92990884456becf7e",
          "sha1": "41a2aca05cb2c6fa147b8e1a752b4661f6fe4890",
          "md5": "838f0ac462cb834c7e757031f13e93a8"
        }
      ]
    }
  ]
}
