{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "4fb6791",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-4fb6791.jar",
          "url": "antibytes-versioning-4fb6791.jar",
          "size": 24286,
          "sha512": "e0c7e2240ac9a63c02d590797281187f05cf1e454c81f631b9201794cc99566e9af2af79e2dab9e0b60694f77bf58976ceac717ae5c13ab6cab161c00968f3b3",
          "sha256": "53125c4fb5ff67c036c4a8a76091d7328b31cfa4b836a1ed5f47f329e2b39d7d",
          "sha1": "8563d56cea2cfb1a5922c06c1238dc0cfd463044",
          "md5": "5dc5974711a8540addd317ae69cbae0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-4fb6791.jar",
          "url": "antibytes-versioning-4fb6791.jar",
          "size": 24286,
          "sha512": "e0c7e2240ac9a63c02d590797281187f05cf1e454c81f631b9201794cc99566e9af2af79e2dab9e0b60694f77bf58976ceac717ae5c13ab6cab161c00968f3b3",
          "sha256": "53125c4fb5ff67c036c4a8a76091d7328b31cfa4b836a1ed5f47f329e2b39d7d",
          "sha1": "8563d56cea2cfb1a5922c06c1238dc0cfd463044",
          "md5": "5dc5974711a8540addd317ae69cbae0a"
        }
      ]
    }
  ]
}
