{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-78602a6661-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-78602a6661-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-78602a6661-SNAPSHOT.jar",
          "size": 47560,
          "sha512": "e382557aa6b90a1659d8ffc12538805e86704b848ecd48580c6b92f298524ac2ce7bb055e0243d9587540b5277db6f8270732fa4a1231ed02468de1b95bc9c25",
          "sha256": "0e3f3ef292a867063bf42521fc80725b26e865372a0a36cd88b955df76334c84",
          "sha1": "1be17689fb4d046716fed906b4e46e03100b2ea3",
          "md5": "430677deca1f2bb722c932471f04cfc8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-78602a6661-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-78602a6661-SNAPSHOT.jar",
          "size": 47560,
          "sha512": "e382557aa6b90a1659d8ffc12538805e86704b848ecd48580c6b92f298524ac2ce7bb055e0243d9587540b5277db6f8270732fa4a1231ed02468de1b95bc9c25",
          "sha256": "0e3f3ef292a867063bf42521fc80725b26e865372a0a36cd88b955df76334c84",
          "sha1": "1be17689fb4d046716fed906b4e46e03100b2ea3",
          "md5": "430677deca1f2bb722c932471f04cfc8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-78602a6661-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-78602a6661-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "2936b059fff0c0bae49fd5d2847ed8086288329158ba573a8aa0884cc93405fb93f10beee8d5bc6169c37a29d7a16e26cd357698af160e805f3f1de9ea7f4554",
          "sha256": "1d7de84a7a9a516c73c3ced51a66e01233efa385a862ade76120aa4e4148c24f",
          "sha1": "453c7989e24b6e7f7412c1fa5cd401cefe35225b",
          "md5": "9717e39492d84741ae6fe78677717557"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-78602a6661-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-78602a6661-SNAPSHOT-sources.jar",
          "size": 10928,
          "sha512": "8eaa7e9db17bfa71f7e389bed1e9a7d00b8d152c5f94f3c327544befe2947dbc31f26b4f55ec649227b03d39679ee26cd3f9d3218bdb2285b4b9e6dfacd687d3",
          "sha256": "7037b9c5edc73c416512a15cd6b4dfc3782bdee7a5254bd99efb1f5d60f3254a",
          "sha1": "f0ed5b54eae2e04bb6959c388a548b90f7dd56f7",
          "md5": "87db9428c4ffefdc544eb50f1836d64f"
        }
      ]
    }
  ]
}
