{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes",
    "module": "banana-i18n",
    "version": "99da957",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n-metadata-all.jar",
          "url": "banana-i18n-99da957-all.jar",
          "size": 670,
          "sha512": "3f5ab1037b30ceb3b2e50d4f65c91942f191417851c258aec313bbe6e85d4dcff5650262d54edd8bb29f1b012e895f8b31b298560f3496170cbf7dbd2963fc3c",
          "sha256": "2545fe290fc87b098f2b010058f94b5a45cc08c55d92374ff78700ba101d7ea6",
          "sha1": "c6fb49d23a95abc75325135dbad8d3fa216d8be6",
          "md5": "c69148840a47db5480275943d7dabb6b"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n.jar",
          "url": "banana-i18n-99da957.jar",
          "size": 8908,
          "sha512": "ddcd8af29af1dc39320b45b76499fe5b261b3e57a257ea88d5fe472530a501f27b60c931e63fbfc6712ff4b5ce5cda508b48a72944323a83b7db40df443b3559",
          "sha256": "cd68e28870384a67f431fbf845586ad90691bbfbc9b8e7fd26eb3b8e7b937b4f",
          "sha1": "bd281412bf1d5ea01f489509465a27c62a43bf1a",
          "md5": "1f70faf610404150136ee7df802d55d7"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/99da957/banana-i18n-android-99da957.module",
        "group": "tech.antibytes",
        "module": "banana-i18n-android",
        "version": "99da957"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/99da957/banana-i18n-android-99da957.module",
        "group": "tech.antibytes",
        "module": "banana-i18n-android",
        "version": "99da957"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/99da957/banana-i18n-jvm-99da957.module",
        "group": "tech.antibytes",
        "module": "banana-i18n-jvm",
        "version": "99da957"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/99da957/banana-i18n-jvm-99da957.module",
        "group": "tech.antibytes",
        "module": "banana-i18n-jvm",
        "version": "99da957"
      }
    }
  ]
}
