{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.settings",
    "module": "antibytes-dependency-settings",
    "version": "52dc3b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "52dc3b1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-52dc3b1.jar",
          "url": "antibytes-dependency-settings-52dc3b1.jar",
          "size": 15128,
          "sha512": "c2933031fea7060b3b3ce6f2a2131e96d0a83d5a5063d4dae3f25be69356caf94e778b27bbbe3567a26ba3421c82267d9259a8b4fc68c0b1a9127e154446570a",
          "sha256": "f3b946b925efa2f168be80cc69f3b72b3c3263620db0914d63ff1ba5a00077a5",
          "sha1": "71bdebb93476d243c81b7a587d79c0bfbc7f30d0",
          "md5": "bcaeae7e5d3366704cbf6b5979fcc9c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "52dc3b1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-52dc3b1.jar",
          "url": "antibytes-dependency-settings-52dc3b1.jar",
          "size": 15128,
          "sha512": "c2933031fea7060b3b3ce6f2a2131e96d0a83d5a5063d4dae3f25be69356caf94e778b27bbbe3567a26ba3421c82267d9259a8b4fc68c0b1a9127e154446570a",
          "sha256": "f3b946b925efa2f168be80cc69f3b72b3c3263620db0914d63ff1ba5a00077a5",
          "sha1": "71bdebb93476d243c81b7a587d79c0bfbc7f30d0",
          "md5": "bcaeae7e5d3366704cbf6b5979fcc9c0"
        }
      ]
    }
  ]
}
