{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "ca7bdaf",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-ca7bdaf.toml",
          "url": "antibytes-dependency-catalog-ca7bdaf.toml",
          "size": 231809,
          "sha512": "16d0fc5955a5f87772e5a79d65c8f2a425a73e1cabdeda104529387d4b1485390b8a8aeccb60e6acacb655d773f5cbe6f24f372e35755a6df81a91984d56ff26",
          "sha256": "2579d1e5f21fe3c30adaf5ef256d27a41c0eff13c102f9e041b4c323ce5fde9c",
          "sha1": "9bac0ebbbfb1558d8009a78043884b746dfb67eb",
          "md5": "163dec7b913772f91c5135bf56784f20"
        }
      ]
    }
  ]
}
