{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/b6c6e6c/test-utils-annotations-junit4-b6c6e6c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "b6c6e6c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-iosarm64-b6c6e6c.klib",
          "size": 11704,
          "sha512": "2bdadb4b8b97bcc660924559d8de8139085294b342d744bf106b78284e0718739b6c6b1e80fded81090b70f90ea87e840fbbe97c3eab3184d928780a86181ff9",
          "sha256": "0181346d028707fefa7119f64664042f1e6c77639d1455ea4e8f95d0403de694",
          "sha1": "21b566cbaa62b7e8b2c1dce0bc29fa800c03dda3",
          "md5": "2eaa8ebd282eb3a6be16972f283a4184"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-annotations-junit4-iosarm64-b6c6e6c-sources.jar",
          "url": "test-utils-annotations-junit4-iosarm64-b6c6e6c-sources.jar",
          "size": 4896,
          "sha512": "2fe566b164f18a378d2c2daef090e149e0410a28bce2fd8eb67e9c81f2f2829b88cd4d3144e475fd0e8bd4d1e875624f6a42181ca5c272ee8cb3c5120df576b8",
          "sha256": "ce6588d8cdfe151428ad5243f3789335be34b41a39afba73df51f6509fb505d9",
          "sha1": "b969be4de0cad713d3e23159129ccc7f8256d550",
          "md5": "7378c76f616bc582b49cf2cf7b9d2f0a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-iosarm64-b6c6e6c-metadata.jar",
          "url": "test-utils-annotations-junit4-iosarm64-b6c6e6c-metadata.jar",
          "size": 261,
          "sha512": "1d358f78cba440e99518b381afdb433cc5485e0e654949328294bcc650eb2dd9cbe43bf38fd6f6159744e6bf2b572e07bd0ee972c2a7cb5b8ad27b2f61bd8928",
          "sha256": "582152ce6d40ce1daeda5c800165246ed93832d2e04117f93e038481566571c1",
          "sha1": "d80498a27c38a6981d0f63373481804eae832eff",
          "md5": "8c61bebba837466882d72381a5ebd41f"
        }
      ]
    }
  ]
}
