{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-linuxx64-0.2.0-SNAPSHOT.klib",
          "size": 62154,
          "sha512": "b6d2e7c227a5de6e89b28c7754f74a032e47cc9a6b49185f1fdabba424f8165c4e7af8183a9ada701323db91f196c93994c29801bbc246b8721f8ef65639a7ba",
          "sha256": "59c949e9d18f838778b5b7c5ac06f7002bb4d60e637d7f4249a2239b89272812",
          "sha1": "6881346126ec66cea4ef0364324f0e78e104274a",
          "md5": "e9fab61f620f504b13594d605668544e"
        }
      ]
    }
  ]
}
