{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-linuxx64-0.2.0-SNAPSHOT.klib",
          "size": 86576,
          "sha512": "8457f873c3f88c10a1ce415a06e0143ac242c3b7293bcc5ec36d24e99b5af21a20b9404033cba95b0f8ee11ca582d436ebb69c5fd0f678abe1532394abf205c6",
          "sha256": "83520cb4e3d6653b6a3e5631e23cecd2830f156e1306e66b890fd28e98147461",
          "sha1": "614e89a227a620d86e320d7f9a5e9042defc4782",
          "md5": "62327cb2cd32414d845174375d06bcc3"
        }
      ]
    }
  ]
}
