{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-linuxx64-0.2.0-SNAPSHOT.klib",
          "size": 61616,
          "sha512": "8ea676cd266ad4d4f14573331da84435ec9860d9a5e77f918b353fe9d08653ac07c8289af44691aef6c677dc5aa431ecdf0c08a8ce3dbdaf3653fc2e1679c65c",
          "sha256": "bc4dc4b866d4fbc5cf5aa2a223f4a0d399a4e09df2fb6a45d90904b9cb93fed5",
          "sha1": "3769e2d700ac644a9584fe66ae5beea826506642",
          "md5": "44a749afb63b622d5cd7c3554ea958cd"
        }
      ]
    }
  ]
}
