{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-linuxx64-0.2.0-SNAPSHOT.klib",
          "size": 100141,
          "sha512": "c278d630658e3a8765fa176c2abb03fbfcc2255e2f52c47a82de979f39934e9842b39cbdc4d6180c85676451185e1261e1b72c58bbf2e040e9ba68301ea6dce2",
          "sha256": "b7352914cc41fc978ebf2a6a11f4818a25e8ec8b61e51b53f492dd195dd24b27",
          "sha1": "ebad14c64a116627c8ad149b6d56ea47b6225af9",
          "md5": "f052001cfaf7e796f177e8945c2c0df4"
        }
      ]
    }
  ]
}
