{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-linuxx64-0.2.0-SNAPSHOT.klib",
          "size": 81760,
          "sha512": "3c061a058eef181a00ecc77503d9a835535b919eab7a8e3c47c5c6328cad3c6aaf807b048cb0219725aa9bb0b1168bc9d49d1bdca60ff84479422e78d137eccf",
          "sha256": "854d22b8487e92b6f1aba043207435662c29c1c65aaa2501eacec6954ab9524b",
          "sha1": "58ed6d2cc0644f11a1017e1001714ed73a26a445",
          "md5": "1c01826396a5fafe5204150ee532e579"
        }
      ]
    }
  ]
}
