{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-helper",
    "version": "4204626",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-4204626.jar",
          "url": "antibytes-dependency-helper-4204626.jar",
          "size": 44923,
          "sha512": "4fba70e21f36c90add1884995fef49e5cc375baedeb11b5f076efba5212fd1fc62e5fb4053c5784a8206bfd9c72d42ade63e3c16093f0f502181551ccef70031",
          "sha256": "ba8a15ffc63cfdfe2d1ea7ed15f189016030a66df0c088574e75a14b7641a0f8",
          "sha1": "13e99904fc7d536581c3f353511933c4eb0003f8",
          "md5": "68c411f7e5663f5053cb335bd86033d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "4204626"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-4204626.jar",
          "url": "antibytes-dependency-helper-4204626.jar",
          "size": 44923,
          "sha512": "4fba70e21f36c90add1884995fef49e5cc375baedeb11b5f076efba5212fd1fc62e5fb4053c5784a8206bfd9c72d42ade63e3c16093f0f502181551ccef70031",
          "sha256": "ba8a15ffc63cfdfe2d1ea7ed15f189016030a66df0c088574e75a14b7641a0f8",
          "sha1": "13e99904fc7d536581c3f353511933c4eb0003f8",
          "md5": "68c411f7e5663f5053cb335bd86033d5"
        }
      ]
    }
  ]
}
