{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.publishing",
    "module": "antibytes-publishing-configuration",
    "version": "5b4a923",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-configuration-5b4a923.jar",
          "url": "antibytes-publishing-configuration-5b4a923.jar",
          "size": 4888,
          "sha512": "c2997a740406947cc79fcf7603c097613d95cad1784dce2c5b29dcaac5969939414a4ed706fc30d11f69a320339cd38e92a93d3d7a4a53884795a4f2dbf5ce28",
          "sha256": "cded328c44c223d8b9e27a12ff1320a886c8fb804cc5fc32b758cb040dd06d32",
          "sha1": "62bdfe5a5e0e2596eed6726a7817d086e9911379",
          "md5": "250dc28448fb3b49bd1cb705690547ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.publishing",
          "module": "antibytes-publishing",
          "version": {
            "requires": "5b4a923"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-configuration-5b4a923.jar",
          "url": "antibytes-publishing-configuration-5b4a923.jar",
          "size": 4888,
          "sha512": "c2997a740406947cc79fcf7603c097613d95cad1784dce2c5b29dcaac5969939414a4ed706fc30d11f69a320339cd38e92a93d3d7a4a53884795a4f2dbf5ce28",
          "sha256": "cded328c44c223d8b9e27a12ff1320a886c8fb804cc5fc32b758cb040dd06d32",
          "sha1": "62bdfe5a5e0e2596eed6726a7817d086e9911379",
          "md5": "250dc28448fb3b49bd1cb705690547ab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-publishing-configuration-5b4a923-javadoc.jar",
          "url": "antibytes-publishing-configuration-5b4a923-javadoc.jar",
          "size": 261,
          "sha512": "78efc86027f5ba6739de2d220797f6847aecb8565edcee86bafa522f6985ef236d69cff807bd819d3fc87f516116cd9d97de972511a44aaaecf30fa712a01724",
          "sha256": "b62f82071b9fe5822836948dcd1ffde4dfd7bd085df241773eefc4807ba7952a",
          "sha1": "d40052798598cf9e8aac85bbf872f1158824be5a",
          "md5": "1fc4a7bca0e1b73b936473c3fd4131e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-publishing-configuration-5b4a923-sources.jar",
          "url": "antibytes-publishing-configuration-5b4a923-sources.jar",
          "size": 2031,
          "sha512": "5d1341c5675c0bf5abb668d7b662a0aa574822d7ca1ea11c56c3d429f3199a6eaeed666105bf8cbbcadff70803d32ccb2623395f69502c863b8e69c5ef267021",
          "sha256": "2473368ce3d0fe3b3448ba8a4d6e8471192f11bc5fe2e42cd78535963fe104be",
          "sha1": "cf55d38f21e73a18148e643602dcc438c26c250e",
          "md5": "fa61ebbb541403edd29d373ee90c9306"
        }
      ]
    }
  ]
}
