{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "7d5f4dd",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-7d5f4dd.jar",
          "url": "antibytes-dependency-node-7d5f4dd.jar",
          "size": 21473,
          "sha512": "9a954e1cf521fa33579d76118fc6de5136f4a9ee7f0dcaa288a713e3b687c27ae6d317921730c92e3a7a3fe9dabdf337bfef22db262c7c05e34ddb0df595b910",
          "sha256": "6f790aa870e2abea94774ffacecb66f02f7c13d459765161c3a29471a4081410",
          "sha1": "50fca83ab7056d9a7d4e5be165f3ffa028d15b5c",
          "md5": "acae8cd43609b2a356732bf64ef00d6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-7d5f4dd.jar",
          "url": "antibytes-dependency-node-7d5f4dd.jar",
          "size": 21473,
          "sha512": "9a954e1cf521fa33579d76118fc6de5136f4a9ee7f0dcaa288a713e3b687c27ae6d317921730c92e3a7a3fe9dabdf337bfef22db262c7c05e34ddb0df595b910",
          "sha256": "6f790aa870e2abea94774ffacecb66f02f7c13d459765161c3a29471a4081410",
          "sha1": "50fca83ab7056d9a7d4e5be165f3ffa028d15b5c",
          "md5": "acae8cd43609b2a356732bf64ef00d6b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-7d5f4dd-javadoc.jar",
          "url": "antibytes-dependency-node-7d5f4dd-javadoc.jar",
          "size": 261,
          "sha512": "684e93b17c215121d8f96f4f606dd2f6f2ede9a6bcd2c9c70cc9c11d78d0137ac5c54d0a4ba71f63ac72167271b55b8500f5b4eed031306f1d3e40efc4dcc526",
          "sha256": "8c8408e1aa6a719593b7e3e27010b3730b0959b21319780239fc0fb584106e89",
          "sha1": "4360f22706470871d51e8e6dcd8f31b4f65a1b3b",
          "md5": "033ca39f6f5474acfc67406dca9b87ec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-7d5f4dd-sources.jar",
          "url": "antibytes-dependency-node-7d5f4dd-sources.jar",
          "size": 4172,
          "sha512": "158fa49f3b02109a1d0474104960cb80429a99a0702e56612c7c95e3314792254e8445fa3b83ad0ebd1946321f18f47c505fa23d4280feff767f62531385b6c1",
          "sha256": "288555b4dd75ca8d164f317faa96dc80b5552eb9e6dd6a42cace3956f35db7da",
          "sha1": "51597809e8459a82adfa954384e2c32c4b6522ae",
          "md5": "05fb9faa785230e077beaabd103c4a3d"
        }
      ]
    }
  ]
}
