{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/1887fc4/core-1887fc4.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "1887fc4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-1887fc4.klib",
          "url": "core-js-1887fc4.klib",
          "size": 61528,
          "sha512": "54b3639cbbaa3db336bbdcea8f8536864c90881ee2ee7cdd008aaeed20443c9d4a02e2156c9875bcc1fffb7d80c36d5301218db94c6dd259fd7b1c993566cf28",
          "sha256": "4b805ea0d4426f64eb02a15be73371bc69b59bb90a1059a315567a25fa945d6a",
          "sha1": "4bbd13aae30566aeb2eb3f49cd8d196f9aa6ae7f",
          "md5": "243041c43af5d12309d200f4a2cf17b9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-1887fc4.klib",
          "url": "core-js-1887fc4.klib",
          "size": 61528,
          "sha512": "54b3639cbbaa3db336bbdcea8f8536864c90881ee2ee7cdd008aaeed20443c9d4a02e2156c9875bcc1fffb7d80c36d5301218db94c6dd259fd7b1c993566cf28",
          "sha256": "4b805ea0d4426f64eb02a15be73371bc69b59bb90a1059a315567a25fa945d6a",
          "sha1": "4bbd13aae30566aeb2eb3f49cd8d196f9aa6ae7f",
          "md5": "243041c43af5d12309d200f4a2cf17b9"
        }
      ]
    }
  ]
}
