{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-runtime-configuration",
    "version": "3e2b68f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-3e2b68f.jar",
          "url": "antibytes-runtime-configuration-3e2b68f.jar",
          "size": 20356,
          "sha512": "f683837835d844e673283ef3f1fe720c9c1ff0df2d0c60a53aeb480f15a0ee0847a3c1e39c7032f8f492162d7b0315178d12dfcbc9524a9d7e835cf2f35e7b0a",
          "sha256": "b2cdcfcb85b9805b337f552ff41483ef8f2dc5d1d3e6880002ce6d7dee4d3a84",
          "sha1": "81fed55770cb3d70c09f5e076c19369a2d5c5a00",
          "md5": "06b4dbca9bf46842bd85b30957c48b33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "3e2b68f"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-3e2b68f.jar",
          "url": "antibytes-runtime-configuration-3e2b68f.jar",
          "size": 20356,
          "sha512": "f683837835d844e673283ef3f1fe720c9c1ff0df2d0c60a53aeb480f15a0ee0847a3c1e39c7032f8f492162d7b0315178d12dfcbc9524a9d7e835cf2f35e7b0a",
          "sha256": "b2cdcfcb85b9805b337f552ff41483ef8f2dc5d1d3e6880002ce6d7dee4d3a84",
          "sha1": "81fed55770cb3d70c09f5e076c19369a2d5c5a00",
          "md5": "06b4dbca9bf46842bd85b30957c48b33"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-3e2b68f-javadoc.jar",
          "url": "antibytes-runtime-configuration-3e2b68f-javadoc.jar",
          "size": 261,
          "sha512": "e853a51175a44961cb2b1002e809f835391b79a43eb0cc2049d4780b44e1b5f7777f5968397002d81f7364d860fa51256910efc9d2c2eacab6ab78873261bbab",
          "sha256": "156daf84ab923875e75a5e8ab12244ce4607f26a95d31cc09664805a074da324",
          "sha1": "d70ab6955bdc85078c0f9f2d1acae474bffcd4bc",
          "md5": "ad93031e8cfc54530b117b71abddbd90"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-3e2b68f-sources.jar",
          "url": "antibytes-runtime-configuration-3e2b68f-sources.jar",
          "size": 6059,
          "sha512": "bd091946c172c042560219d267f41ebe1e5d50938ce69304151881d2e45ee4e4e242a83a5372c1a1de7a7ebe2922918a7c2a8c2e864f971aa96ba2712afa0eaf",
          "sha256": "b00e15be8f6f4b896f44e1daf2afa7734ca11f21e74c8ab86587664b74113d68",
          "sha1": "2a39aa8621d47cc8d1ef13bd17c16dca171453cb",
          "md5": "2c9c1ba706b3abb126544ee7ae30d930"
        }
      ]
    }
  ]
}
