{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/980554b/kmock-980554b.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "980554b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-980554b.jar",
          "url": "kmock-jvm-980554b.jar",
          "size": 255257,
          "sha512": "f6e7bae9e1ac0f4ce5a40a6aab72c72180d3d69f5da20e67d862c82e3b02b1800201f49c97091501a344c51962ad7d573d8d475c43556cf18d2a31ca582d2e62",
          "sha256": "26649672f77638a71906610c8ad3b4368c433e670ff24de330652d24c6e5e28d",
          "sha1": "12c70123f3f2a00a44f68c487ed58810bab36f3c",
          "md5": "fe6633ce42556f46eda82878ae1521a1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-980554b.jar",
          "url": "kmock-jvm-980554b.jar",
          "size": 255257,
          "sha512": "f6e7bae9e1ac0f4ce5a40a6aab72c72180d3d69f5da20e67d862c82e3b02b1800201f49c97091501a344c51962ad7d573d8d475c43556cf18d2a31ca582d2e62",
          "sha256": "26649672f77638a71906610c8ad3b4368c433e670ff24de330652d24c6e5e28d",
          "sha1": "12c70123f3f2a00a44f68c487ed58810bab36f3c",
          "md5": "fe6633ce42556f46eda82878ae1521a1"
        }
      ]
    }
  ]
}
