{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/f384302/test-utils-annotations-junit4-f384302.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "f384302",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-macosx64-f384302.klib",
          "size": 11352,
          "sha512": "473985b88e223580dfd4d75f0a264b6789032c26f30dda6d14e9b3b6709dc204720668995aaf6a6755c8fa5bd858ba927ac0b50d5fca9eb29b9ac103dbbbbe18",
          "sha256": "79174ef68b01947b495b75bdcc7fc3e580baf006490e8bbbc9ccd76b6c1d337c",
          "sha1": "91997f33ecd8091baa23d5d394c7d1700f644cf4",
          "md5": "3e4b64a7b2fc8b134111b71f9ee61520"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-macosx64-f384302-metadata.jar",
          "url": "test-utils-annotations-junit4-macosx64-f384302-metadata.jar",
          "size": 261,
          "sha512": "bf488df5955a2a152fe4c1c3e5e90820e7cabe3cc084762c3e889057dc22dfc4c5c7f2b826e252c103073afdb939bd7d8852987f95be372fc9aae43598498be8",
          "sha256": "b485a34cd65ba8ef15eb5e704ab4cf47582b73ebf940722c3593e43721ebeb5c",
          "sha1": "14549ae568e03f1c0b51a10a2c25a5edcffc262f",
          "md5": "3646f99622e5606d883a5942622515b2"
        }
      ]
    }
  ]
}
