{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.publishing",
    "module": "antibytes-publishing",
    "version": "fa2239f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "fa2239f"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-fa2239f.jar",
          "url": "antibytes-publishing-fa2239f.jar",
          "size": 141166,
          "sha512": "35935c6be0e2094d6b6eb5ca6891d4b4219b5c90302822684ad571e70ed2c59989efca8e365d52c33a26dd221e9dfe417d0f994505e804a60b346fc6765ae90d",
          "sha256": "a057f109ef39fcb1848b65d0fec1e5c651f86f97d197e54013fe237be38bd8d5",
          "sha1": "06f91548aad09ae307079e8bddf43ef24eeee575",
          "md5": "4e108144201b8cbb808c66c9621b93bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.7.0.202309050840-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "fa2239f"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "fa2239f"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-fa2239f.jar",
          "url": "antibytes-publishing-fa2239f.jar",
          "size": 141166,
          "sha512": "35935c6be0e2094d6b6eb5ca6891d4b4219b5c90302822684ad571e70ed2c59989efca8e365d52c33a26dd221e9dfe417d0f994505e804a60b346fc6765ae90d",
          "sha256": "a057f109ef39fcb1848b65d0fec1e5c651f86f97d197e54013fe237be38bd8d5",
          "sha1": "06f91548aad09ae307079e8bddf43ef24eeee575",
          "md5": "4e108144201b8cbb808c66c9621b93bd"
        }
      ]
    }
  ]
}
