{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/ad2b9d7/kmock-ad2b9d7.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "ad2b9d7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm.jar",
          "url": "kmock-jvm-ad2b9d7.jar",
          "size": 130756,
          "sha512": "7db6f81447ad5f025607c3b82a41aafa4d9a70b9c33c37c7b151adae4a69eec3ffb6947ebe650f6227e97ded4f4641a724090372583fc457da700a39b2051ecb",
          "sha256": "f0c97ae3afaa8933739906206a8519e05de2cb42c817ee56958950840a0f4b5b",
          "sha1": "5f5612bfc757abed30a4cf5d30f5a094ebfeb25f",
          "md5": "0a03530d101c94866638dc24d6b24d1b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "7b11c9d-add-ios-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm.jar",
          "url": "kmock-jvm-ad2b9d7.jar",
          "size": 130756,
          "sha512": "7db6f81447ad5f025607c3b82a41aafa4d9a70b9c33c37c7b151adae4a69eec3ffb6947ebe650f6227e97ded4f4641a724090372583fc457da700a39b2051ecb",
          "sha256": "f0c97ae3afaa8933739906206a8519e05de2cb42c817ee56958950840a0f4b5b",
          "sha1": "5f5612bfc757abed30a4cf5d30f5a094ebfeb25f",
          "md5": "0a03530d101c94866638dc24d6b24d1b"
        }
      ]
    }
  ]
}
