{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "4d9e549",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "4d9e549"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-4d9e549.jar",
          "url": "antibytes-publishing-4d9e549.jar",
          "size": 117663,
          "sha512": "ae7175955f45aea9be37513467c84f742fb11724230d489b67a087b801b26a05b2a886690a3a8fcc09f84c3b52831ff4e58c89ab26264e6a3e7bd5718295772b",
          "sha256": "b19a3c7a55751535f5ae2c78e86abe4619c15d4779ba4750cc9f6edd8083d67e",
          "sha1": "993a60099ef2261340d1bab5215608a7f78c0b91",
          "md5": "8f7b01207a95817a0adeadaf27f8d548"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.3.0.202209071007-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "4d9e549"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "4d9e549"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-4d9e549.jar",
          "url": "antibytes-publishing-4d9e549.jar",
          "size": 117663,
          "sha512": "ae7175955f45aea9be37513467c84f742fb11724230d489b67a087b801b26a05b2a886690a3a8fcc09f84c3b52831ff4e58c89ab26264e6a3e7bd5718295772b",
          "sha256": "b19a3c7a55751535f5ae2c78e86abe4619c15d4779ba4750cc9f6edd8083d67e",
          "sha1": "993a60099ef2261340d1bab5215608a7f78c0b91",
          "md5": "8f7b01207a95817a0adeadaf27f8d548"
        }
      ]
    }
  ]
}
