{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/c3e5acf/test-utils-c3e5acf.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "c3e5acf",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-c3e5acf.klib",
          "url": "test-utils-js-c3e5acf.klib",
          "size": 11902,
          "sha512": "f7bd73918e58bcb1362235a3eb2bcf5a92f3f56153570c2c3cd9c33d7691ba2e4f330e9863cf93025a002b4e9ea254415b889186757149829f8fc53cce348c88",
          "sha256": "6abbaeb390d6aebf5dd5cd3ab2822bbd7583b3133b805053749aa4848466d4c9",
          "sha1": "18e606f59a5fbdfe980e46b5e187e09ed2c1b375",
          "md5": "0f840e4bec0944ff9ac31d214901c895"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-c3e5acf.klib",
          "url": "test-utils-js-c3e5acf.klib",
          "size": 11902,
          "sha512": "f7bd73918e58bcb1362235a3eb2bcf5a92f3f56153570c2c3cd9c33d7691ba2e4f330e9863cf93025a002b4e9ea254415b889186757149829f8fc53cce348c88",
          "sha256": "6abbaeb390d6aebf5dd5cd3ab2822bbd7583b3133b805053749aa4848466d4c9",
          "sha1": "18e606f59a5fbdfe980e46b5e187e09ed2c1b375",
          "md5": "0f840e4bec0944ff9ac31d214901c895"
        }
      ]
    }
  ]
}
