{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "bf45661",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-metadata-bf45661.jar",
          "url": "kmock-bf45661.jar",
          "size": 21090,
          "sha512": "d86e19c19301aa8ef996647fdd22c95a08b533cc2eb3f88c7c6f95b1775170f4cb69cd0943e9d16b7e16c32e476dbac793be7f7ca0e79e7eb8c490a33954e909",
          "sha256": "d84f21f530a0cef5d214f3d58f0f19277fa74eac89cd8a412ba775f6c787a636",
          "sha1": "e1fa30081066f2dee9ff598b60c31f68b00f8086",
          "md5": "e89e6e02ef79b63bdc6240e741f516d5"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/bf45661/kmock-android-bf45661.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "bf45661"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/bf45661/kmock-android-bf45661.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "bf45661"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/bf45661/kmock-iosarm64-bf45661.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "bf45661"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/bf45661/kmock-iosx64-bf45661.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "bf45661"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/bf45661/kmock-js-bf45661.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "bf45661"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/bf45661/kmock-js-bf45661.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "bf45661"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/bf45661/kmock-jvm-bf45661.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "bf45661"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/bf45661/kmock-jvm-bf45661.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "bf45661"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/bf45661/kmock-linuxx64-bf45661.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "bf45661"
      }
    }
  ]
}
