{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "2c9ef96",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-metadata-2c9ef96.jar",
          "url": "kmock-2c9ef96.jar",
          "size": 13812,
          "sha512": "61c300aeaca519fca917f7f314450e67cf36b00e2fb1e01870cb943d7253eabf2b9f3a75d96dfcc9473d64f3e14dca620d68dd519626d11a7796601be295031c",
          "sha256": "cffad4f551e2bc8945bf92f320291b7642c0acc6974f7e873863a29e81aee385",
          "sha1": "40fedc53efd4f23d8cce78f3197acb2a9f952602",
          "md5": "70f757e52353349a7d6c57887a24c008"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/2c9ef96/kmock-android-2c9ef96.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "2c9ef96"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/2c9ef96/kmock-android-2c9ef96.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "2c9ef96"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/2c9ef96/kmock-iosarm64-2c9ef96.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "2c9ef96"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/2c9ef96/kmock-iosx64-2c9ef96.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "2c9ef96"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/2c9ef96/kmock-js-2c9ef96.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "2c9ef96"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/2c9ef96/kmock-js-2c9ef96.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "2c9ef96"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/2c9ef96/kmock-jvm-2c9ef96.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "2c9ef96"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/2c9ef96/kmock-jvm-2c9ef96.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "2c9ef96"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/2c9ef96/kmock-linuxx64-2c9ef96.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "2c9ef96"
      }
    }
  ]
}
