{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/dbba7bb/test-utils-resourceloader-dbba7bb.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "dbba7bb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "linuxMipsel32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-linuxmipsel32-dbba7bb.klib",
          "size": 12906,
          "sha512": "710cd04f59fbda72b8830e39b43dc6773e8f93fbae24460531199ae026da213702904eeca0c7489a20e3c669934690510401fcad3881ce934d1b8d30cf3327d8",
          "sha256": "f3a9d19ceae9e9b93b63a9a02a1dcee8fbaaa3ba2e9063f5adc12597e31c9b05",
          "sha1": "90b49e4d0f36d30501b0e79092e011c2945420fb",
          "md5": "3059fe0a013e9ee5f9fbf8108ae0c517"
        }
      ]
    },
    {
      "name": "linuxMipsel32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-linuxmipsel32-dbba7bb-metadata.jar",
          "url": "test-utils-resourceloader-linuxmipsel32-dbba7bb-metadata.jar",
          "size": 261,
          "sha512": "c75202649344c0e625c71760790a5e52f848f70041a086d46268532cc68f9493c47babe7a5d4c803d45563d8a010485776bd5c909b306c4b2c067e20481a10b1",
          "sha256": "8c96c040b1a1a115d8451d7b8cccbc25451d14b6b66aa603327e9036828f9089",
          "sha1": "f9775f7f50eb1fbcbb2f38bdce78e0b12996b8e2",
          "md5": "ede364f935b4158be9ec5903c92f017d"
        }
      ]
    }
  ]
}
