{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.0-SNAPSHOT/core-0.3.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-0.3.0-SNAPSHOT.klib",
          "size": 99975,
          "sha512": "9e2c89f3208b252a4734d13e3fade4b4fbad79998867964b3b9b36a71046d1d333ac2ddc90f6185f488cff79901a9eecad04a6e5362c66df8ee6a6a091c7bce2",
          "sha256": "bc938b9875dc6f8581e56dfbe6808ed983d38006f4faf2d59f73a333682da366",
          "sha1": "789691f6ce6cacd2965c20d19c1cef8cf6aa6b2b",
          "md5": "fdc32d98fea5761322a50c8e3f3a0c41"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.3.0-SNAPSHOT-metadata.jar",
          "url": "core-iosarm64-0.3.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4257aa38a59518b889f97f434b85533850f087ab62b79bc6448b8fe9773d6d37859d2036b58f4f2f2568090ad4077a96c4110d7852789c219ef1c97e4fc09d0a",
          "sha256": "b54ed4870d3815d18c24342ef0b00aa83436f8d7cc00ddaf8b734c9272cb2ccf",
          "sha1": "f1dd398c501d9cf4ff9fbde0c22340ade99ea645",
          "md5": "88e73ed7f48c704857c2d80f258ec7af"
        }
      ]
    }
  ]
}
