{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/6be4f13/test-utils-fixture-6be4f13.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "6be4f13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-6be4f13.klib",
          "url": "test-utils-fixture-js-6be4f13.klib",
          "size": 38261,
          "sha512": "3fb1ed0cdccfd8b595ae5aac0c019148cc187acfe5120f9085b44d51ed39878cfdbd55849f7b82e3bdd02f12a4e424622ec46f37b0417bd8879382b1a1bc7185",
          "sha256": "a74cd98ed1424ce60e07eebc3cd0f7ae94d4a10da903e8939b0655fea3c75b0e",
          "sha1": "70183d6da742f0b49876fed18316c374b1b1d28f",
          "md5": "ce771e27181dd537dcc5142c116fecca"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-6be4f13.klib",
          "url": "test-utils-fixture-js-6be4f13.klib",
          "size": 38261,
          "sha512": "3fb1ed0cdccfd8b595ae5aac0c019148cc187acfe5120f9085b44d51ed39878cfdbd55849f7b82e3bdd02f12a4e424622ec46f37b0417bd8879382b1a1bc7185",
          "sha256": "a74cd98ed1424ce60e07eebc3cd0f7ae94d4a10da903e8939b0655fea3c75b0e",
          "sha1": "70183d6da742f0b49876fed18316c374b1b1d28f",
          "md5": "ce771e27181dd537dcc5142c116fecca"
        }
      ]
    }
  ]
}
