{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-bridge",
    "version": "8c67525",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-bridge-8c67525.jar",
          "url": "antibytes-dependency-bridge-8c67525.jar",
          "size": 38501,
          "sha512": "fc2bc3e215920f2630029b5364537239bee1e964f996f073c2b9d85d7536070fc24d237b7065b70d87f67d5a13342fcbd6091346b5b79f35b931a46e115b1ced",
          "sha256": "68bcdc3876977294dd5868c4d14ecc6e8ed379eb9d3cea547800e4f427e391d4",
          "sha1": "f31d72dbd7a66c1ec95679c452c72871b14d544f",
          "md5": "65a83c3ceda93d121d17940e0603e8c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-bridge-8c67525.jar",
          "url": "antibytes-dependency-bridge-8c67525.jar",
          "size": 38501,
          "sha512": "fc2bc3e215920f2630029b5364537239bee1e964f996f073c2b9d85d7536070fc24d237b7065b70d87f67d5a13342fcbd6091346b5b79f35b931a46e115b1ced",
          "sha256": "68bcdc3876977294dd5868c4d14ecc6e8ed379eb9d3cea547800e4f427e391d4",
          "sha1": "f31d72dbd7a66c1ec95679c452c72871b14d544f",
          "md5": "65a83c3ceda93d121d17940e0603e8c5"
        }
      ]
    }
  ]
}
