{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "6eac159",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-6eac159.jar",
          "url": "antibytes-grammar-tools-6eac159.jar",
          "size": 39373,
          "sha512": "999cf4fa8cbb2376433c7e3902371d0d4617b38197f83fb11a60279065624e0a9a2452b99de013e5c563435d72f60de5a87d768f2acd7e9460740925decce309",
          "sha256": "8963b207a1a7aab81f8af9990fa10aded0f7d0cb04bd8a4cfcb3b838acaafc95",
          "sha1": "66d8f168887bbb3a817dd5b9fc16e54d1a87d131",
          "md5": "47701d55a1ecc35d9fdb5ed4c94bfe0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-6eac159.jar",
          "url": "antibytes-grammar-tools-6eac159.jar",
          "size": 39373,
          "sha512": "999cf4fa8cbb2376433c7e3902371d0d4617b38197f83fb11a60279065624e0a9a2452b99de013e5c563435d72f60de5a87d768f2acd7e9460740925decce309",
          "sha256": "8963b207a1a7aab81f8af9990fa10aded0f7d0cb04bd8a4cfcb3b838acaafc95",
          "sha1": "66d8f168887bbb3a817dd5b9fc16e54d1a87d131",
          "md5": "47701d55a1ecc35d9fdb5ed4c94bfe0c"
        }
      ]
    }
  ]
}
