{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "ed86011",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-ed86011.toml",
          "url": "antibytes-dependency-catalog-ed86011.toml",
          "size": 249537,
          "sha512": "b65621b9625cc6709e9657802700a85f59c4fd92e74de1684aa9a040db518794c4455cda36931040f08b639ad9865fa37fa41cf5bcb6e0bf4b07de59c97fe46c",
          "sha256": "1eafd420c2a5345e46bd3264362ffb0a0e71e0e8d4a116fcda363cf547d39134",
          "sha1": "8e3a21622117a9c7e4e30cec9e62e9fc27ddcfc6",
          "md5": "39e3640c663cca6139db70d888550aba"
        }
      ]
    }
  ]
}
