{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/1d9e81e/kmock-1d9e81e.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "1d9e81e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-1d9e81e.jar",
          "url": "kmock-jvm-1d9e81e.jar",
          "size": 195134,
          "sha512": "a7400eb7d914ec728b879fcbb18f4425805eeeaf128b5ca61ebb3db82de0bc772948209cb1bc7204942b20c6e877eb76c9be0b182989ded73365d658b4917e5a",
          "sha256": "2395bee0d469d140a805cfca6543227889e7167a3135872d763cb30f0495e7c8",
          "sha1": "f3c2b2fa39a229e5ebf1cc9c2eeeb6680fe6bd03",
          "md5": "ef3a480f9e2f9483530cef36f98020d5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "c3e5acf"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-1d9e81e.jar",
          "url": "kmock-jvm-1d9e81e.jar",
          "size": 195134,
          "sha512": "a7400eb7d914ec728b879fcbb18f4425805eeeaf128b5ca61ebb3db82de0bc772948209cb1bc7204942b20c6e877eb76c9be0b182989ded73365d658b4917e5a",
          "sha256": "2395bee0d469d140a805cfca6543227889e7167a3135872d763cb30f0495e7c8",
          "sha1": "f3c2b2fa39a229e5ebf1cc9c2eeeb6680fe6bd03",
          "md5": "ef3a480f9e2f9483530cef36f98020d5"
        }
      ]
    }
  ]
}
