{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-metadata-0.3.1-SNAPSHOT-all.jar",
          "url": "ktx-datetime-0.3.1-SNAPSHOT-all.jar",
          "size": 5881,
          "sha512": "edac84ae71b04cb1d939d9a12b690a0c9482b667e543995a1b41e9ead8f8b56e6b08bcafdd93d91f77ce12d32a738f8bc3c662fdcaf50d6f1882a89a8e5fe40a",
          "sha256": "1b2b6dfde8cc79bca7d314bc26eb7f9eba21ac357334797c7ccfcb231bcb1a8d",
          "sha1": "d5c254c1ca730047b50dc578dd6ad4f0b298a46f",
          "md5": "3c54d67b01442f6186155d43f067ac7c"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktx-datetime-0.3.1-SNAPSHOT.jar",
          "url": "ktx-datetime-0.3.1-SNAPSHOT.jar",
          "size": 3872,
          "sha512": "1446b3264980cb663c2f195b218eeb4aa7267b58ed76799d783e3efbb2784e7c29d319a06631446ac9dc93f90aaf87e0619306b462d58c3857888e8bd35feb4a",
          "sha256": "253f5bc0aacf0a17fef6e191e3d9e84d2201492ebc1bb7db49314f591e27acbb",
          "sha1": "c101b128d83a48b8ca1ba485da289b0498b3147f",
          "md5": "868460777a4c73ece8fdcce5cfd117ce"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-android/0.3.1-SNAPSHOT/ktx-datetime-android-0.3.1-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-android",
        "version": "0.3.1-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-android/0.3.1-SNAPSHOT/ktx-datetime-android-0.3.1-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-android",
        "version": "0.3.1-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosarm64/0.3.1-SNAPSHOT/ktx-datetime-iosarm64-0.3.1-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosarm64",
        "version": "0.3.1-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosarm64/0.3.1-SNAPSHOT/ktx-datetime-iosarm64-0.3.1-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosarm64",
        "version": "0.3.1-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iossimulatorarm64/0.3.1-SNAPSHOT/ktx-datetime-iossimulatorarm64-0.3.1-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iossimulatorarm64",
        "version": "0.3.1-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iossimulatorarm64/0.3.1-SNAPSHOT/ktx-datetime-iossimulatorarm64-0.3.1-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iossimulatorarm64",
        "version": "0.3.1-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosx64/0.3.1-SNAPSHOT/ktx-datetime-iosx64-0.3.1-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosx64",
        "version": "0.3.1-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosx64/0.3.1-SNAPSHOT/ktx-datetime-iosx64-0.3.1-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosx64",
        "version": "0.3.1-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktx-datetime-js/0.3.1-SNAPSHOT/ktx-datetime-js-0.3.1-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-js",
        "version": "0.3.1-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktx-datetime-js/0.3.1-SNAPSHOT/ktx-datetime-js-0.3.1-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-js",
        "version": "0.3.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-jvm/0.3.1-SNAPSHOT/ktx-datetime-jvm-0.3.1-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-jvm",
        "version": "0.3.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-jvm/0.3.1-SNAPSHOT/ktx-datetime-jvm-0.3.1-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-jvm",
        "version": "0.3.1-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-linuxx64/0.3.1-SNAPSHOT/ktx-datetime-linuxx64-0.3.1-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-linuxx64",
        "version": "0.3.1-SNAPSHOT"
      }
    }
  ]
}
