{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.coverage",
    "module": "antibytes-coverage",
    "version": "f6a864b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-f6a864b.jar",
          "url": "antibytes-coverage-f6a864b.jar",
          "size": 146046,
          "sha512": "e125c7cd671e3c4b713565a678782a1dea03fe574999104c19a43426f275ab6c994b63cf853e41c718e62d7ceb632257d6313ad413d384fb1d7fa5ee795d8598",
          "sha256": "095eb178df7526d9f291bdb11ba574de77c25a677a2aca60c9322fc0cf1cef36",
          "sha1": "40a655360fdb5118e91cef19e12bc4b65398d00b",
          "md5": "bc9121fe49a47e61807a0937336fb19d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "f6a864b"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-f6a864b.jar",
          "url": "antibytes-coverage-f6a864b.jar",
          "size": 146046,
          "sha512": "e125c7cd671e3c4b713565a678782a1dea03fe574999104c19a43426f275ab6c994b63cf853e41c718e62d7ceb632257d6313ad413d384fb1d7fa5ee795d8598",
          "sha256": "095eb178df7526d9f291bdb11ba574de77c25a677a2aca60c9322fc0cf1cef36",
          "sha1": "40a655360fdb5118e91cef19e12bc4b65398d00b",
          "md5": "bc9121fe49a47e61807a0937336fb19d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-coverage-f6a864b-javadoc.jar",
          "url": "antibytes-coverage-f6a864b-javadoc.jar",
          "size": 261,
          "sha512": "2fa68d19a5791168de061d6892fa9a6e0b555d379388e329fb591d66bb0e65c741bf038274429535ab3398f0c515f1d05b10845e6fa1f4c39335aac9cb0ec9d3",
          "sha256": "d5fd87bb3902a2f78934d7e51f4feb7256b61db26c5a6aa71e40f08de8b87f96",
          "sha1": "21db0a2a2de975a6d9d468510a8931f49195c527",
          "md5": "e6578cde71807b6d27eda151c0dc8a78"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-coverage-f6a864b-sources.jar",
          "url": "antibytes-coverage-f6a864b-sources.jar",
          "size": 27853,
          "sha512": "714c82c91d77e44d2e819243a0e3b2e724de87b6d1ea6775119658e84d873c73a99c0eb533e7dbfed1174de248409bf9fee586d66bcf0807543e4e912af06e61",
          "sha256": "96b19a9cbb232a2b2c94b9e7feadae5c3a11e123785f0455dcf1215ebd58f708",
          "sha1": "11d75b8c04d1f0a0721a8d7089f1ffb106da26c1",
          "md5": "f0e1fd2d1f84466fe5bffc6db8591f5e"
        }
      ]
    }
  ]
}
