{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-linuxx64-0.1.1-SNAPSHOT.klib",
          "size": 150895,
          "sha512": "7089c07e1fd01f00ec8e18764bf8cfcb4c4b8d1ba9fea07fa683f684102d4d15dbc33fb3555b9770b98c26e0d581de2570a2d26ff0e6b7b1629c3dfbb9518ae6",
          "sha256": "5c054dbbefe96f7511717851594f9e1495d7c897d914299434c8d46bb53e87ff",
          "sha1": "651146effb485bbcdaab9469eb80f17a3d11e591",
          "md5": "88387995a78ae762f424842d11a11f44"
        }
      ]
    }
  ]
}
