{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-linuxx64-0.1.1-SNAPSHOT.klib",
          "size": 156025,
          "sha512": "2e68e9a880e5d65e3fbb405be5927a9ed8c0199e4b8f7b43de4579c80c503300cfa318639156ea6936621423afd90cf45bf831ba0d9b9472afc467d44886e239",
          "sha256": "5b7436dfdfd227bf357dba808097726c3a954c2b4e86e586961c6f3c52287987",
          "sha1": "43f4b3275fa56c9f4a12d0e381398e1f6abacd4b",
          "md5": "511800e566a409848e0c39d91507f4f0"
        }
      ]
    }
  ]
}
