{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/dbba7bb/test-utils-annotations-junit5-dbba7bb.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "dbba7bb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-watchosx64-dbba7bb.klib",
          "size": 7069,
          "sha512": "d1d1117c451c6786d37528b8a21cefd98abee62c2eb31e1fe4a60270713fceb50ff4f5815f30d42a3d9becbc956dc683bca142214c5755e3bdc4d738d05b443f",
          "sha256": "672d9b11beb19e1233df5088963e759ab93d97ab004a4e1dd483961f5feba247",
          "sha1": "05f3b5b614824e3a2eb67a5f7d7b89662d267b63",
          "md5": "a45c9569803132ede8e6cc99b8f05a39"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-watchosx64-dbba7bb-metadata.jar",
          "url": "test-utils-annotations-junit5-watchosx64-dbba7bb-metadata.jar",
          "size": 261,
          "sha512": "7c1163a327cd5fcb093d0218fe6317e68a5d7c0e3ff4c26b49e856a45932c84c19bbb3870a54984d1aa04927ad5adc586aa278e333d92ce8728de506ed3c4ec1",
          "sha256": "462bb646f066cb831a71f3c76612b8132faeb2300d06a3860f3a787b64365b97",
          "sha1": "b96de0402db523779e7b27e8e1f1773a0e3497b3",
          "md5": "e280f74a60750e051366c47a8dd85cc0"
        }
      ]
    }
  ]
}
