{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/0c09612/test-utils-coroutine-0c09612.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "0c09612",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-coroutine-jvm.jar",
          "url": "test-utils-coroutine-jvm-0c09612.jar",
          "size": 5897,
          "sha512": "5399b20d053d162fc0dbcfe59b2af66b2e3bedac0988207c9cc507e399f88716f7cbc5d717dfb54bec59dab853b4b04475292317cfac05ef92b0197b6d708e94",
          "sha256": "40a262e979007e77061ae1283b7ae5991f6ae729fb2e35d9b630086e1a54029e",
          "sha1": "3ea4e720c0cce9f14078e2ab73c20a274ffce1bd",
          "md5": "636ce90d1da9714a1de90c30c4a486d5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm.jar",
          "url": "test-utils-coroutine-jvm-0c09612.jar",
          "size": 5897,
          "sha512": "5399b20d053d162fc0dbcfe59b2af66b2e3bedac0988207c9cc507e399f88716f7cbc5d717dfb54bec59dab853b4b04475292317cfac05ef92b0197b6d708e94",
          "sha256": "40a262e979007e77061ae1283b7ae5991f6ae729fb2e35d9b630086e1a54029e",
          "sha1": "3ea4e720c0cce9f14078e2ab73c20a274ffce1bd",
          "md5": "636ce90d1da9714a1de90c30c4a486d5"
        }
      ]
    }
  ]
}
