{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-watchosx64-0.4.0-SNAPSHOT.klib",
          "size": 105854,
          "sha512": "eb5c018c302040c497855b09ddc9992dbee6beb776786101ac6acf31ca9d359729648ca33093d00a2baa48d263df5f3e5c2510ee58b93cd3d741208d67e79941",
          "sha256": "5720c1db3183b053a34b3d78a9c3a2b35c0d4ee26458eb7e93c225175a726308",
          "sha1": "97acd61ec85443383a460fa1155dfb56bf586487",
          "md5": "841d3784ef0a64c328270fd0ecb6e8ad"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchosx64-0.4.0-SNAPSHOT-metadata.jar",
          "url": "core-watchosx64-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "c3d3aa0a06936506014a431437e7d01a4a32eae0b161087ce241679983529f51df0c742beefffe6e510d7bf01ecad4257bb985936145ec76e242fc598e19008b",
          "sha256": "68a3712cfa6b38e787104fa0b5c69e2749d016360a5a895464accc63932a8043",
          "sha1": "8eeb5ca164832d7c01ad57385644bc6099a8f1e1",
          "md5": "3638e00a6e5a7ae7b4678fb8be835fc7"
        }
      ]
    }
  ]
}
