{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-watchosx64-0.4.0-SNAPSHOT.klib",
          "size": 105854,
          "sha512": "eb5c018c302040c497855b09ddc9992dbee6beb776786101ac6acf31ca9d359729648ca33093d00a2baa48d263df5f3e5c2510ee58b93cd3d741208d67e79941",
          "sha256": "5720c1db3183b053a34b3d78a9c3a2b35c0d4ee26458eb7e93c225175a726308",
          "sha1": "97acd61ec85443383a460fa1155dfb56bf586487",
          "md5": "841d3784ef0a64c328270fd0ecb6e8ad"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchosx64-0.4.0-SNAPSHOT-metadata.jar",
          "url": "core-watchosx64-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d7badbc9e08de54ddd26a4cbce1d68dfc773afef1f691cea087479c0df71ee07998cf85556454b0886fce1fe0dce15870447f0534009647b274ffb6c35e5fd8d",
          "sha256": "b982b910b405a2e4a67a4f1089969108c2d6e5e1abebc2c4e8deee8743b3742e",
          "sha1": "a4756bacc775924b6868b1b9acc0b4bbc1e221c9",
          "md5": "d881ee70c0bf4ff584874cbf9d8543d7"
        }
      ]
    }
  ]
}
