{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "807f122",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-807f122.jar",
          "url": "antibytes-coverage-807f122.jar",
          "size": 133706,
          "sha512": "e22880aef26f8ba4937a9871585526ad316c93bff0ee883c738b988a73a3677f3565592a45a0c86e79517c7ac9f072303cd1d271ad0d3e979d79eaa3cd27278d",
          "sha256": "4c3ebea06d647cfa33b039fa61d367601790fdfdb64242610db463927f640e13",
          "sha1": "299a46334f4b614135b702db01724f05c6515ddb",
          "md5": "e0716b8ba7ff8993373d17d1cfa75df5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "807f122"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-807f122.jar",
          "url": "antibytes-coverage-807f122.jar",
          "size": 133706,
          "sha512": "e22880aef26f8ba4937a9871585526ad316c93bff0ee883c738b988a73a3677f3565592a45a0c86e79517c7ac9f072303cd1d271ad0d3e979d79eaa3cd27278d",
          "sha256": "4c3ebea06d647cfa33b039fa61d367601790fdfdb64242610db463927f640e13",
          "sha1": "299a46334f4b614135b702db01724f05c6515ddb",
          "md5": "e0716b8ba7ff8993373d17d1cfa75df5"
        }
      ]
    }
  ]
}
