{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/4f11117/test-utils-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "linuxMipsel32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-linuxmipsel32-4f11117.klib",
          "size": 8005,
          "sha512": "96c4190f9c3b1d5952aa551d4b133e9af89247e00c0ad100d68ad1d07677927554fed190e8b0fb93998006daf5d04aed2804389cd43983dc0f2bc4b4f9d64663",
          "sha256": "b7edf2edf7bb9832535218280779afb26a62cea497c686e8b189d0a638027e36",
          "sha1": "463ef4b78beeee9fe74014a2fe5b822c0b591249",
          "md5": "eda012ee644f64e6ad108f2b1f100f24"
        }
      ]
    },
    {
      "name": "linuxMipsel32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-linuxmipsel32-4f11117-metadata.jar",
          "url": "test-utils-linuxmipsel32-4f11117-metadata.jar",
          "size": 261,
          "sha512": "b72445d0fd26a7cfa5971bad1d4bfd73b178f3b353093138b114dd8741507f287e6418d98bca3a21b921989729218b908dfb414ea59d4cf758d13acffe8b4f5e",
          "sha256": "eda28fefac44d696aff04dd86f93dfa51695e51c324fe920283fd26d2bbee618",
          "sha1": "ec7e7fa054c45e49b278cc23a88b35583d897e14",
          "md5": "edce00e5f31452f83c2b207410ddedc7"
        }
      ]
    }
  ]
}
