{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "3fa260b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-3fa260b.jar",
          "url": "antibytes-grammar-tools-3fa260b.jar",
          "size": 39371,
          "sha512": "f0e4f9b851c48bdcc0ec669cff07e9a1425d78eacdf6ca04a1bb1ffb5efa10c026d5e0e41f1db3aad6e42303c4c5fbbf7e1671a1cfe190e2d77bf6d40ed8f2bf",
          "sha256": "554180cbe2e46844af7fae2b52d1b3adb0a55f472913f9720e092d566e09fbfe",
          "sha1": "9e9724aaa0c060c5cd0d7f2d0753ef7f50bdaec0",
          "md5": "35dc5871038dc3e8347a2541c9f03a09"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-3fa260b.jar",
          "url": "antibytes-grammar-tools-3fa260b.jar",
          "size": 39371,
          "sha512": "f0e4f9b851c48bdcc0ec669cff07e9a1425d78eacdf6ca04a1bb1ffb5efa10c026d5e0e41f1db3aad6e42303c4c5fbbf7e1671a1cfe190e2d77bf6d40ed8f2bf",
          "sha256": "554180cbe2e46844af7fae2b52d1b3adb0a55f472913f9720e092d566e09fbfe",
          "sha1": "9e9724aaa0c060c5cd0d7f2d0753ef7f50bdaec0",
          "md5": "35dc5871038dc3e8347a2541c9f03a09"
        }
      ]
    }
  ]
}
