{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-watchosx86-0.4.0-SNAPSHOT.klib",
          "size": 105854,
          "sha512": "e329f0c06611b415fbb9c916977e31b532c8f5c4f57beede067057b181d825beca6b22d347cca42785a3333b842b7ca40a24206b07de24b86cadb4c443c3a267",
          "sha256": "a8f3516fa309affa18f82228abdd015927f6f3cde92eccb4a1f2624fdcc1dfcf",
          "sha1": "c63d8d0b797ce07f3d4b0c4c2c0c9769537db28a",
          "md5": "fe87cbe3887090c412b4e53c685a5873"
        }
      ]
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchosx86-0.4.0-SNAPSHOT-metadata.jar",
          "url": "core-watchosx86-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "59beb96c0a478edd9357bbad7d87c372a499d72f9acbb0bd560cd17a58bd4e0af83c2d52ff8d3ef1fb5562d49931570559e7d694fa54c34ffe21f8bdf28fe976",
          "sha256": "a81c9518d609b6f19f1069d9cd6cfe66ebfe78139a63630f7442d85c0ca23753",
          "sha1": "0764eb16c996b99bfc258496a266e7685790de4b",
          "md5": "8c1e065986c97d744937ce29c6e583fe"
        }
      ]
    }
  ]
}
