{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-0.4.0-SNAPSHOT.klib",
          "size": 105834,
          "sha512": "265550cc4abccf8514cc2010212104828d280c101704ad4790ca486b6f2ed8b91cff578772f80469d92ef5198cd9c80b8d12bb7bbc424a19a29d69f63b189d78",
          "sha256": "332bd314c3afeca78f9427a2573aee921f7272cb0e9b3cbad1f13989f188254d",
          "sha1": "ea23320eaa0eaeab840c0a1d999ededa5612aa8a",
          "md5": "2029b6318fa9a8c26ff80c64a21efbc5"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.4.0-SNAPSHOT-metadata.jar",
          "url": "core-iosarm64-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d69db4fd9edf65023f4e4f63834b5904d77129f6e70e5a4b133b2f1a2d17321350c7ef24fa735a7ec32b0a8d201f5098510e084b5dc550af68c0a5bf9f32368c",
          "sha256": "5adddd1a9a55f59ab6504cce091bb9f17a303f67c5ec57c33e50db433133f8df",
          "sha1": "02c884e09feefe7b0f370832920ae438321dcc66",
          "md5": "b587a13024b9b966858ae2401ac76458"
        }
      ]
    }
  ]
}
