{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-0.4.0-SNAPSHOT.klib",
          "size": 105834,
          "sha512": "265550cc4abccf8514cc2010212104828d280c101704ad4790ca486b6f2ed8b91cff578772f80469d92ef5198cd9c80b8d12bb7bbc424a19a29d69f63b189d78",
          "sha256": "332bd314c3afeca78f9427a2573aee921f7272cb0e9b3cbad1f13989f188254d",
          "sha1": "ea23320eaa0eaeab840c0a1d999ededa5612aa8a",
          "md5": "2029b6318fa9a8c26ff80c64a21efbc5"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.4.0-SNAPSHOT-metadata.jar",
          "url": "core-iosarm64-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "191b2ca831da30805ae92ccfddec174fcd9d10366729ada5bc8decbde4ba110d61d8bf3613ac8f2b887846f235dca62af754944463efd5382f5b95180021ac35",
          "sha256": "0d9e9e9b7b4a8d9c5383380898a9c75c3fd18f16a16c6b43c20aa0e92da10bda",
          "sha1": "5d9b3ba0b024a3082b5c3fd12d787b1f9dc1ca4a",
          "md5": "f6218714a633b10cb13794202bdf6b82"
        }
      ]
    }
  ]
}
