{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "fca89fa",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-fca89fa.jar",
          "url": "antibytes-gradle-test-utils-fca89fa.jar",
          "size": 15099,
          "sha512": "62cdba864b6a53e4132ad1d6b1858748aaf6de68dd092b5f75c1760476a8d4dcbcb9c68ae0f46ca520ea7baa1ac0d1f6fabb24c48cce5a788f21f14d34f39008",
          "sha256": "39127b528343779bd7da5c36602865246711ce40af5acfff48162d3d1b7de9b0",
          "sha1": "7c382e13f500b0ac504e5eab84a53d3a29c65ad5",
          "md5": "c86355f52803fe28ec8b62e89a79a47d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-fca89fa.jar",
          "url": "antibytes-gradle-test-utils-fca89fa.jar",
          "size": 15099,
          "sha512": "62cdba864b6a53e4132ad1d6b1858748aaf6de68dd092b5f75c1760476a8d4dcbcb9c68ae0f46ca520ea7baa1ac0d1f6fabb24c48cce5a788f21f14d34f39008",
          "sha256": "39127b528343779bd7da5c36602865246711ce40af5acfff48162d3d1b7de9b0",
          "sha1": "7c382e13f500b0ac504e5eab84a53d3a29c65ad5",
          "md5": "c86355f52803fe28ec8b62e89a79a47d"
        }
      ]
    }
  ]
}
