{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc02-SNAPSHOT/kmock-0.3.0-rc02-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc02-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iossimulatorarm64-0.3.0-rc02-SNAPSHOT.klib",
          "size": 202580,
          "sha512": "45997cf8fc1c9c07753c2ed18e90621c27a7f585b538da1d34aaaba0ac0d770772b135a59fe6b337daf8afd3dd4bec0849718a4a6dae9ef137035edae788e28a",
          "sha256": "361d5eee4b94d0d1032791e890dcdf49b6feae166ebc24fe191e5f2de3211fef",
          "sha1": "9bb1279019b5ecc0acc9744430889ee4924394de",
          "md5": "e22b9ae6b7eb656f2d8b9a3139310b8d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iossimulatorarm64-0.3.0-rc02-SNAPSHOT-metadata.jar",
          "url": "kmock-iossimulatorarm64-0.3.0-rc02-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "fa2a67a39d935e0d18489df44bb6ee385dd2b175b821f3e6e467679d5ddcb1096ec468409f2cfbaaf2d3ef976e2874a32c24abd0a4f19b9c0738fe44161171dd",
          "sha256": "3621cc583533ea61e1c8fc0472d86ad1bae48a648c524820f2a6d0f896504181",
          "sha1": "ab079002af21c41ca536afc2498e7534aa18b664",
          "md5": "588d2511938cd346ce30ccb740cc17f1"
        }
      ]
    }
  ]
}
