{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "7456350",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-7456350.jar",
          "url": "antibytes-coverage-7456350.jar",
          "size": 133706,
          "sha512": "73410538292e3bb5d0e3b5c2f315882dc534767e1892067ba230e58f6873d5614ed106e87be6a9e41f02c291baebf1cde826990e0179cd515226cd26b33d3300",
          "sha256": "75d1a3b4b87da95c46f1ba7305393ad159eac965e8a91a2b6f9670279dcb2d5c",
          "sha1": "5ea327348ebdba83c5b5ecbcea9ca3a508e02dd3",
          "md5": "531ebded4fcb205c5174df757dcbf0ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "7456350"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-7456350.jar",
          "url": "antibytes-coverage-7456350.jar",
          "size": 133706,
          "sha512": "73410538292e3bb5d0e3b5c2f315882dc534767e1892067ba230e58f6873d5614ed106e87be6a9e41f02c291baebf1cde826990e0179cd515226cd26b33d3300",
          "sha256": "75d1a3b4b87da95c46f1ba7305393ad159eac965e8a91a2b6f9670279dcb2d5c",
          "sha1": "5ea327348ebdba83c5b5ecbcea9ca3a508e02dd3",
          "md5": "531ebded4fcb205c5174df757dcbf0ed"
        }
      ]
    }
  ]
}
