{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-quality",
    "version": "f536734",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-quality-f536734.jar",
          "url": "antibytes-quality-f536734.jar",
          "size": 62595,
          "sha512": "74c4fc766dde967d3ea383b0b19b9e33eace5ffd9fd6ac21e4b1a819790f0c0f40479020a6d2e19b8682277998f2c9e3b1a17f1865bd7dff886d310dfef2d1d6",
          "sha256": "6e8bd72e530a02e2af44a9517c5c7ffb5a7c778a5a254d3e100d7b0bf47d55ce",
          "sha1": "9a4737462fcf78f4be3cc292cbb8d8cbd9d263bb",
          "md5": "22d4777309d7c2cc963e3b275cf22c12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.21.0"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "f536734"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-dependency-helper",
          "version": {
            "requires": "f536734"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-f536734.jar",
          "url": "antibytes-quality-f536734.jar",
          "size": 62595,
          "sha512": "74c4fc766dde967d3ea383b0b19b9e33eace5ffd9fd6ac21e4b1a819790f0c0f40479020a6d2e19b8682277998f2c9e3b1a17f1865bd7dff886d310dfef2d1d6",
          "sha256": "6e8bd72e530a02e2af44a9517c5c7ffb5a7c778a5a254d3e100d7b0bf47d55ce",
          "sha1": "9a4737462fcf78f4be3cc292cbb8d8cbd9d263bb",
          "md5": "22d4777309d7c2cc963e3b275cf22c12"
        }
      ]
    }
  ]
}
