{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/86ec4d6/test-utils-resourceloader-86ec4d6.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "86ec4d6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iosarm64-86ec4d6.klib",
          "size": 14212,
          "sha512": "dd5a05b51343c6379c980325a0052766cb6c45318c298fb7850ca56d12d96d0eed04839b1a237a9d60fcef00b8a9043e3f9672c75713c17b5b1a0a5e0c2ad71e",
          "sha256": "b4388923455a298e74b237e19a183fb0914c02620082f4e40985fc34f1b510d2",
          "sha1": "d659b21d4516e70df228140e85286c4a79a4a6cc",
          "md5": "31ed27cd81032b82e76c05cf87d997e3"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-iosarm64-86ec4d6-sources.jar",
          "url": "test-utils-resourceloader-iosarm64-86ec4d6-sources.jar",
          "size": 4241,
          "sha512": "284172150658cfb9dae6c2bb10bbd5de382a8193d892540a4de60322cb16b05740a160fc4f827c092194ab0e3983419cb75c9d52eee7cf9cf1ac22b32a8f7d7b",
          "sha256": "28c33fb0c5429879a7515dfb1ee5400a354f30a17cda3a32c13cec2fd413b7da",
          "sha1": "e6bc305f912fc8fc1e733215728491f83d594bd4",
          "md5": "935272aedc89d60202c3ad87a167495a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iosarm64-86ec4d6-metadata.jar",
          "url": "test-utils-resourceloader-iosarm64-86ec4d6-metadata.jar",
          "size": 261,
          "sha512": "13708f542c5b79a148a40fca18f289996a427c61648335d51bd51bd1deef421f0732c39477918e0b0f9f1f1999340d73deda0d191f6ac5c57f0072edee280a1b",
          "sha256": "21d91f8bbb638b5b4278d223f77fef126d280aa3ed5bd2411ee9488feb4a9cb1",
          "sha1": "1a0054cb7f61424885277a6a2465cf536d797292",
          "md5": "6821bf94ed2b49cb8a519b9e587a52fe"
        }
      ]
    }
  ]
}
