{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/dbba7bb/test-utils-resourceloader-dbba7bb.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "dbba7bb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iosarm64-dbba7bb.klib",
          "size": 12865,
          "sha512": "d4354a16ff4e7f671a885afb5bd50aa493618e58eb624522b6443a3e88c75c55809c4c7926e37e528f7ee3db77798347c8dfa0f0dfe19972f3324d577ca388db",
          "sha256": "34d19a0a80dbb12e2b11109e11dc0627ee8514043a2e6e69b536b6dfd94e211a",
          "sha1": "52b6a8fdf6b799f09150e4e5169200bdd7f836c4",
          "md5": "bf93c70f016dce7067f84b5922b6e864"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iosarm64-dbba7bb-metadata.jar",
          "url": "test-utils-resourceloader-iosarm64-dbba7bb-metadata.jar",
          "size": 261,
          "sha512": "07a0605ca2d5fdd3ecaf9f394fbfedbdd0860c927feb7db140753db3a1310cabfe4d3a41933f19a562adfb39a00d9ff2193c1278a8c20616ab9d3ae35b3ed8c5",
          "sha256": "126ccf4faedd7e12a0caa6c75fe262e53d217549897a23f418a91faea2e9d0e0",
          "sha1": "a3ad2f0548d35002e0a4d9a207b64b2bec6401c9",
          "md5": "da1a909dbfcb2d8346ba82d30b28fa0f"
        }
      ]
    }
  ]
}
