{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "cfd6317",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-cfd6317.jar",
          "url": "antibytes-dependency-node-cfd6317.jar",
          "size": 21501,
          "sha512": "e4b745075994eaf00f76e7f9b50f5614bfd911da5630ab9fac2e6f07109164a04b130cf542f8d764dbc2280f2a29331713316579b7829aad93915c4444a94c0b",
          "sha256": "b9ea4ef758c9cf2e82587e06c7e50586aaff0b674e86dad784fecc5b864b456e",
          "sha1": "694b1ded24893be4919bd8972cb0f669a8519fd1",
          "md5": "7447504ca6163277bbad9e69bd0943d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-cfd6317.jar",
          "url": "antibytes-dependency-node-cfd6317.jar",
          "size": 21501,
          "sha512": "e4b745075994eaf00f76e7f9b50f5614bfd911da5630ab9fac2e6f07109164a04b130cf542f8d764dbc2280f2a29331713316579b7829aad93915c4444a94c0b",
          "sha256": "b9ea4ef758c9cf2e82587e06c7e50586aaff0b674e86dad784fecc5b864b456e",
          "sha1": "694b1ded24893be4919bd8972cb0f669a8519fd1",
          "md5": "7447504ca6163277bbad9e69bd0943d8"
        }
      ]
    }
  ]
}
