{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/c926cf7/fixture-c926cf7.module",
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "c926cf7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture.klib",
          "url": "fixture-iossimulatorarm64-c926cf7.klib",
          "size": 43661,
          "sha512": "f3e8e316d2d9cb49cc6214c60796bff9e8452c6cdebb85fc331d3f9ad3199adcec7c69cc015a5d6242e9b1d28226cf2723230319d66cb0b039ef967fce4715f7",
          "sha256": "ecfd2c3bfab5fa1dfc93db34c938da419d9a045c20b2f9a53088892ed25d5cd8",
          "sha1": "26d612949eb0ecb5e05bec083dbcacbd5ca6c608",
          "md5": "6868b648457e76e26c7d15e134068103"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-iossimulatorarm64-c926cf7-metadata.jar",
          "url": "fixture-iossimulatorarm64-c926cf7-metadata.jar",
          "size": 261,
          "sha512": "121cd8f97f59c58104d241b61e34f14b36cd3cc7160b9d37686244f4a78db8e0c23c05ee4dfa9eec3657133b225866e597e38b3e644d9899e73364418c8769af",
          "sha256": "c577e14323b37e35de92c9413a30381aea78e0f590731f6edce953a9110b9e45",
          "sha1": "a128c2068524fb4ad8e86e71099becbf4b931c82",
          "md5": "000cd539b9e8b148f826ec5da2a5993d"
        }
      ]
    }
  ]
}
