{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/4f11117/test-utils-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-watchosx86-4f11117.klib",
          "size": 7980,
          "sha512": "847daee23a58191c4d0ff4649b94a3f5776957ce4bd94f79f3c291ea31a35d251e232cebcde85353f0ef68c6317184052a4a13b968b8872d61090cfe710bbcf4",
          "sha256": "262fc6678350a1ea467af4bb8aafbee996a74d9541c711ca05bd4319ede5192a",
          "sha1": "187c10b9dbb8237efff9ae01fe0b2f6e15f3ce4f",
          "md5": "29762f0e7b4d22a07c365bdff84f0900"
        }
      ]
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-watchosx86-4f11117-metadata.jar",
          "url": "test-utils-watchosx86-4f11117-metadata.jar",
          "size": 261,
          "sha512": "2ba01c0fbde084c43e9e9d5d1231d4300003746c2be6c918e64338056c95c4e1c6020d78bbbd696c77f67062e60f49b805e31eb96e04f863f674cda17a5683e3",
          "sha256": "1d16898f9c3356b3103d18a6468a00770b7b7398cbe5083580c9c950cffc763b",
          "sha1": "a35f08acef7d8af8fcc23b5448b923ff58799ea7",
          "md5": "a580813560953c74065344356b38283c"
        }
      ]
    }
  ]
}
