{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/18a85ea/test-utils-fixture-18a85ea.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "18a85ea",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm.jar",
          "url": "test-utils-fixture-jvm-18a85ea.jar",
          "size": 41804,
          "sha512": "9c807d847d0b5381a69780699839e7575a807af7ed21a8eeb4ad3cdb24306d23ebb352304ee312b6c30207476c066f9a9ab5ae4670be8d279408237093aec3f4",
          "sha256": "a5b3013320119295af07b8fb7600d86caaff5f0b410bb9b4780cde8dd387a75e",
          "sha1": "3c7672711b8d38446e6b90884d8b47415eefe5c4",
          "md5": "851549ee69eeb64927485104aa4341de"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm.jar",
          "url": "test-utils-fixture-jvm-18a85ea.jar",
          "size": 41804,
          "sha512": "9c807d847d0b5381a69780699839e7575a807af7ed21a8eeb4ad3cdb24306d23ebb352304ee312b6c30207476c066f9a9ab5ae4670be8d279408237093aec3f4",
          "sha256": "a5b3013320119295af07b8fb7600d86caaff5f0b410bb9b4780cde8dd387a75e",
          "sha1": "3c7672711b8d38446e6b90884d8b47415eefe5c4",
          "md5": "851549ee69eeb64927485104aa4341de"
        }
      ]
    }
  ]
}
