{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.kmp",
    "module": "antibytes-kmp-configuration",
    "version": "b1373c3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-b1373c3.jar",
          "url": "antibytes-kmp-configuration-b1373c3.jar",
          "size": 66404,
          "sha512": "168bde6bdfe43da677cbc02a3f3046fe0ff49447f0b56c10b4ee8575e10db6a86571fe850a66f2951c4c2a92004ba161472dcef1c6951f9a83a430ac444b6591",
          "sha256": "9d79b1457f8eb9a3dd3c46947992261b4e4cb9d167e01127871a3aa3f4e770c1",
          "sha1": "a2de7cce36729c412e35afa1a55f7b67e7d43fb2",
          "md5": "ecb318230239d7cf2ef5a65d7c1cc67e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "b1373c3"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-kmp-configuration-b1373c3.jar",
          "url": "antibytes-kmp-configuration-b1373c3.jar",
          "size": 66404,
          "sha512": "168bde6bdfe43da677cbc02a3f3046fe0ff49447f0b56c10b4ee8575e10db6a86571fe850a66f2951c4c2a92004ba161472dcef1c6951f9a83a430ac444b6591",
          "sha256": "9d79b1457f8eb9a3dd3c46947992261b4e4cb9d167e01127871a3aa3f4e770c1",
          "sha1": "a2de7cce36729c412e35afa1a55f7b67e7d43fb2",
          "md5": "ecb318230239d7cf2ef5a65d7c1cc67e"
        }
      ]
    }
  ]
}
