{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "e2ca35b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-e2ca35b.jar",
          "url": "antibytes-gradle-test-utils-e2ca35b.jar",
          "size": 15106,
          "sha512": "6bc7c8e2b36e0d1f97b54b1db1f067b96867edda02184c1f0e5da958ab3051ddb622969785cae932cd755631806f54192ab8c881c886db005528e40f5962909a",
          "sha256": "50f4538f31bfc4027390db75bd5617ee5d65e888f61bd9f0482cb5e3453fc81f",
          "sha1": "ab6901daae4b6a94efbf6c25cd984c3eaf2d2374",
          "md5": "a3bf204fa7a6ffda26f35f999c759cda"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.3"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-e2ca35b.jar",
          "url": "antibytes-gradle-test-utils-e2ca35b.jar",
          "size": 15106,
          "sha512": "6bc7c8e2b36e0d1f97b54b1db1f067b96867edda02184c1f0e5da958ab3051ddb622969785cae932cd755631806f54192ab8c881c886db005528e40f5962909a",
          "sha256": "50f4538f31bfc4027390db75bd5617ee5d65e888f61bd9f0482cb5e3453fc81f",
          "sha1": "ab6901daae4b6a94efbf6c25cd984c3eaf2d2374",
          "md5": "a3bf204fa7a6ffda26f35f999c759cda"
        }
      ]
    }
  ]
}
