{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.4.0-SNAPSHOT.klib",
          "url": "core-js-0.4.0-SNAPSHOT.klib",
          "size": 129883,
          "sha512": "136ecab26653a31f7f0bf5bbaee397e6982cde67094f58b44550c418c53476ed032690ac217ecb3e89d46f667bf3e2ee35041b51c712162a4367039c1851b6e3",
          "sha256": "7d4820a91bdbb26cea8af03a42c4e13a8959e9542ee6618eaf22fde9dfe6e876",
          "sha1": "7e5e5b37c4c6aaf084db60e34d44666b412211c9",
          "md5": "1b34b3f4d425bf2f4124d9deff3f1195"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.4.0-SNAPSHOT.klib",
          "url": "core-js-0.4.0-SNAPSHOT.klib",
          "size": 129883,
          "sha512": "136ecab26653a31f7f0bf5bbaee397e6982cde67094f58b44550c418c53476ed032690ac217ecb3e89d46f667bf3e2ee35041b51c712162a4367039c1851b6e3",
          "sha256": "7d4820a91bdbb26cea8af03a42c4e13a8959e9542ee6618eaf22fde9dfe6e876",
          "sha1": "7e5e5b37c4c6aaf084db60e34d44666b412211c9",
          "md5": "1b34b3f4d425bf2f4124d9deff3f1195"
        }
      ]
    }
  ]
}
