{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.4.0-SNAPSHOT.klib",
          "url": "core-js-0.4.0-SNAPSHOT.klib",
          "size": 129883,
          "sha512": "62bac4e334107e0dc9adec8447ae4d7c9a0711843e9231564bbc73a7955ac1d868f367d7a4f97e35aa7af53f0234b75bd4383b502708299c78012efe563e8a8d",
          "sha256": "134e206d4eae98595404053055dfcbacc8cbb3d634025c1dda4a75c3e3519d37",
          "sha1": "c815be69ffc0fef81512f6fbd6c96293dbe2489c",
          "md5": "b80bda20e96fd65386916a5b695d26b5"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.4.0-SNAPSHOT.klib",
          "url": "core-js-0.4.0-SNAPSHOT.klib",
          "size": 129883,
          "sha512": "62bac4e334107e0dc9adec8447ae4d7c9a0711843e9231564bbc73a7955ac1d868f367d7a4f97e35aa7af53f0234b75bd4383b502708299c78012efe563e8a8d",
          "sha256": "134e206d4eae98595404053055dfcbacc8cbb3d634025c1dda4a75c3e3519d37",
          "sha1": "c815be69ffc0fef81512f6fbd6c96293dbe2489c",
          "md5": "b80bda20e96fd65386916a5b695d26b5"
        }
      ]
    }
  ]
}
