{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/fc88d6a/test-utils-annotations-junit5-fc88d6a.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "fc88d6a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "linuxMips32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-linuxmips32-fc88d6a.klib",
          "size": 7076,
          "sha512": "a7e8b745ac70e8bf05d119b14973dee049d7e05878a9186e5765aa734eefec8210a3a2a6d3b121abf41e54c524c60d2d2911c8f0316f3e94c9755798cec18f16",
          "sha256": "5f6932b1ba8433edc0ee22f6a2707c0b56780e5ef3a05684cd7c5ad78ec0df1f",
          "sha1": "398a96af67888fa6cdb58656b1c278968490b8f2",
          "md5": "d703f89cb76410173ceb6b14c48dd103"
        }
      ]
    },
    {
      "name": "linuxMips32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-linuxmips32-fc88d6a-metadata.jar",
          "url": "test-utils-annotations-junit5-linuxmips32-fc88d6a-metadata.jar",
          "size": 261,
          "sha512": "80c09a620f42de989339343b5160ba46cdb4a0c47333adcf22bb5223a40a172988913ec5d54935d2327527d2c99f292c0df6c2bb33404f67ceae35aa4d2766ca",
          "sha256": "d4474eee3ffefda5a51a4d621259ebf21e9d8b55473e0d9a66cbbd81455b9a81",
          "sha1": "5fa3a8e1f9228a1af423b1cdeaf01f508b5acada",
          "md5": "355f6aa5f421a48a64e7a95d379e3d60"
        }
      ]
    }
  ]
}
