{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/56c4547/test-utils-coroutine-56c4547.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "56c4547",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-56c4547.jar",
          "url": "test-utils-coroutine-jvm-56c4547.jar",
          "size": 11975,
          "sha512": "d40f4cc17e7e36ac5ad9311b9398616e1831a47699ba74a4853695e532da9124f915da4669b03f97ab15c42add9276269dcf3ee514791cc2ffca5f2b8476be43",
          "sha256": "8e12a60a4caebae6da045296e98ada0a8c85036d64e6cbf21565f1e6bd81c402",
          "sha1": "c683bac92437faf07f87a29efa373f87263909d9",
          "md5": "d406ec0e77fbab5df8b3e8ad0a243b7e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-56c4547.jar",
          "url": "test-utils-coroutine-jvm-56c4547.jar",
          "size": 11975,
          "sha512": "d40f4cc17e7e36ac5ad9311b9398616e1831a47699ba74a4853695e532da9124f915da4669b03f97ab15c42add9276269dcf3ee514791cc2ffca5f2b8476be43",
          "sha256": "8e12a60a4caebae6da045296e98ada0a8c85036d64e6cbf21565f1e6bd81c402",
          "sha1": "c683bac92437faf07f87a29efa373f87263909d9",
          "md5": "d406ec0e77fbab5df8b3e8ad0a243b7e"
        }
      ]
    }
  ]
}
