{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/2078ec8/fixture-2078ec8.module",
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "2078ec8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-js-2078ec8.klib",
          "url": "fixture-js-2078ec8.klib",
          "size": 61087,
          "sha512": "34d0c17644cafaa4bd301a8e21ec429d44601ad9860af95c80ca58a2b5f1a387fc697737fd1cceccb5f8a12d99cb5cd529ab0d34025e8a2d7714c97a9082b0ff",
          "sha256": "d1259ce7dce2dfa8baf0b678b293284a18b4f4b280bec7929e25d14165356c0e",
          "sha1": "cce97921c9c8fdb040782d9b48112fe54b159efe",
          "md5": "a1860f864de78c7454dfedd3bb9a0dab"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-js-2078ec8.klib",
          "url": "fixture-js-2078ec8.klib",
          "size": 61087,
          "sha512": "34d0c17644cafaa4bd301a8e21ec429d44601ad9860af95c80ca58a2b5f1a387fc697737fd1cceccb5f8a12d99cb5cd529ab0d34025e8a2d7714c97a9082b0ff",
          "sha256": "d1259ce7dce2dfa8baf0b678b293284a18b4f4b280bec7929e25d14165356c0e",
          "sha1": "cce97921c9c8fdb040782d9b48112fe54b159efe",
          "md5": "a1860f864de78c7454dfedd3bb9a0dab"
        }
      ]
    }
  ]
}
