{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/dbba7bb/test-utils-resourceloader-dbba7bb.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "dbba7bb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-macosx64-dbba7bb.klib",
          "size": 12866,
          "sha512": "8ad3f1e2876ecb5e87f59a958685c0821682dfed598d87593055fb8bf5f1991b708b5c7af0373b105897d48aeb159c008407cd389ea27020c403aafaa64fa8a1",
          "sha256": "d3526b0860ca683adc91be933bd209cea744cb85720b32decad40ed2297b9afe",
          "sha1": "be622699d30496853132a29aaee77b823fcb6d0a",
          "md5": "9e74148237e38fbf7dc68f1aaf6e2768"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-macosx64-dbba7bb-metadata.jar",
          "url": "test-utils-resourceloader-macosx64-dbba7bb-metadata.jar",
          "size": 261,
          "sha512": "d051cfa7f2ef904ebd4069c7420af7b4073d82bec5d486cbc33fe75b1acc4df9e7e838bcab7f862bc64c1f1067f56dafe9fe4ced84611033af90f99fefc96eba",
          "sha256": "ade22881644f03e7a82e4dd465d3ae54d3dd293f0c43ef690a1cfe892ad3be34",
          "sha1": "6e72c119179a7f4e33504b2a16815a70d64708fb",
          "md5": "9576e07d3e809e0ee32d9f2d4f78d9d1"
        }
      ]
    }
  ]
}
