{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosx64-0.1.1-SNAPSHOT.klib",
          "size": 142411,
          "sha512": "7eb9f171233a99f4875cac52496a7cf11ea0e032efc6aa1ce67ede69ac04ba70f5ec2e91bd59a0cdac0f86ff2bede5d76edd4dcf3b126c3eac62b32c2aa3df6b",
          "sha256": "43bb914a2a2f62a567a272915e1248525e673c112f20c5e5562b5d5082de47c8",
          "sha1": "3aba966eaccb4d86b91c1f3f32f4bc6a3c465eec",
          "md5": "c6a6804f6753a5b2011ac24c8da7dd45"
        }
      ]
    }
  ]
}
