{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosx64-0.1.1-SNAPSHOT.klib",
          "size": 129766,
          "sha512": "f45c95d67fd8baf2a83aedae663bb8966369e4a8db51b2c2df2434422a59173c025a99982a51b1197bab9e2d2632e2193700c1bced1d2db7fa505bf7c02ea4b7",
          "sha256": "acde527d2d5c2b4c54697db48c43cf42cd70e65d2b91d5d93b299ac400a748e6",
          "sha1": "6e515436521f5eebaf7ec3b652c465e817b4367b",
          "md5": "7a18fe75c217b90fb238635eabc8c7a2"
        }
      ]
    }
  ]
}
