{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosx64-0.1.1-SNAPSHOT.klib",
          "size": 157942,
          "sha512": "5172416bcde4cd499d5d43376e8234c73dbede6019f333e83521418a5fe9b1b09672d1f727c073d20e7755d69c7f037321ba8d5f02551003337fc98b2abd2c5e",
          "sha256": "2fd66888c6dd6be12feef1840402a1cdbb85ce4bc6cc4b3cfa3d5c3fbc7f296d",
          "sha1": "e5208400d12b034a9b2ee199331db9217d5831cf",
          "md5": "5288b2c58395f0148fcc9d3f5436f8d5"
        }
      ]
    }
  ]
}
