{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/4f11117/test-utils-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosx64-4f11117.klib",
          "size": 7944,
          "sha512": "25f3a71877f32cf043dac487ebbb53d8da138e0ff58242b257dacc6cf1bffda14f850caf2c5713010be077c95100cdb40bb5033d18e37f52a1886c97a016e47d",
          "sha256": "619be0373b05e0e14ec541377c98618efb15f0cd650e2d89149c0d6ec2a582a7",
          "sha1": "55dd25723d1e0c3bf49f99524aff65c338fdf96a",
          "md5": "8e559a5c6968296c38bd2f011da07083"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosx64-4f11117-metadata.jar",
          "url": "test-utils-iosx64-4f11117-metadata.jar",
          "size": 261,
          "sha512": "3e9d7cd564b621646ea7c584283b4eeb981cc4387b9b57aa8caca79922fb0c387d6680b94ed59b66435b53606c39a0b73d7445ca4f38c0f0da9463e050d8de70",
          "sha256": "ba09cad9068b6142c9477aa4b784d61c3b71f85bf8a8bc65d1544b36d1d14f57",
          "sha1": "6ab124c04cc25ff45efa2868a601903c435ee1a5",
          "md5": "27cd1faf3437effe04c7c755e3a168ad"
        }
      ]
    }
  ]
}
