{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/fc88d6a/test-utils-annotations-junit5-fc88d6a.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "fc88d6a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-watchosarm64-fc88d6a.klib",
          "size": 7086,
          "sha512": "5375c934c293382a66ed350449d350206980273045a93130135db1067ee4d254812b2b34ea02d72617f5ff8f82f597b7eab8b7b3f8c4c822bdd3607c34c249a6",
          "sha256": "1432ca394b02f768ce4d7c31117de8116da79ade416cc2a79c33875f09ce239a",
          "sha1": "dccf6ffa23d7083d2b04feaba2746674f7b48b99",
          "md5": "30a4505ceaa9c4c1e2810c9254ef6461"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-watchosarm64-fc88d6a-metadata.jar",
          "url": "test-utils-annotations-junit5-watchosarm64-fc88d6a-metadata.jar",
          "size": 261,
          "sha512": "a0216045bc53c4ac5217d1f1d7b2a60756bfb0bc70e1bbde8a85b9063eb052aefdc5c35dcefffd24359947186c0713115c410c06562906a2f62a2407a7e85669",
          "sha256": "bb9165cd151d422bed4ebe9bb940ca0ca5920e8e339e6e06f28545555d732779",
          "sha1": "6e2fd26598c842f4bd94b61fb38f396b439e46a2",
          "md5": "56573b69983dd639f0f6ab0a2eab4923"
        }
      ]
    }
  ]
}
