{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "32b33c8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-32b33c8.jar",
          "url": "antibytes-publishing-32b33c8.jar",
          "size": 106088,
          "sha512": "6e8cd33377d11878a9a2427111dd1abd81cffd8a5f00856fdfc5f37d66dfe3caf1d98218d66a62123118e24e907de7149defe8b396a7be641484361b0248ef38",
          "sha256": "bb60729630fd22996564b0130ad50a245b818fe0d4f83376d83f3a2d23050bbc",
          "sha1": "0f9da4d63cbbf8a2f82985a6edabc59049d4cc61",
          "md5": "77c501a471d11b2c25f6c837040d4461"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.0.0.202111291000-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.12.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "32b33c8"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-32b33c8.jar",
          "url": "antibytes-publishing-32b33c8.jar",
          "size": 106088,
          "sha512": "6e8cd33377d11878a9a2427111dd1abd81cffd8a5f00856fdfc5f37d66dfe3caf1d98218d66a62123118e24e907de7149defe8b396a7be641484361b0248ef38",
          "sha256": "bb60729630fd22996564b0130ad50a245b818fe0d4f83376d83f3a2d23050bbc",
          "sha1": "0f9da4d63cbbf8a2f82985a6edabc59049d4cc61",
          "md5": "77c501a471d11b2c25f6c837040d4461"
        }
      ]
    }
  ]
}
