{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.dokka",
    "module": "antibytes-dokka-configuration",
    "version": "db3eb1b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dokka-configuration-db3eb1b.jar",
          "url": "antibytes-dokka-configuration-db3eb1b.jar",
          "size": 8108,
          "sha512": "11b4fbe34aa2a5f14d27d792a763d877b634293bf9eb2da8703254b2834e2932f74596c424404f5fa38faad746ec3dd731d20731b89bfc936a8f0c3e2eb7d922",
          "sha256": "4c672827bfbb96973334abd9eac4116ba3c1cb5b70f3876e1ac6507f91b35373",
          "sha1": "a4df02747538ffc93c906d286aa08cb965e95b1b",
          "md5": "cd8c306bb7938b88809e3583243bef4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "db3eb1b"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dokka-configuration-db3eb1b.jar",
          "url": "antibytes-dokka-configuration-db3eb1b.jar",
          "size": 8108,
          "sha512": "11b4fbe34aa2a5f14d27d792a763d877b634293bf9eb2da8703254b2834e2932f74596c424404f5fa38faad746ec3dd731d20731b89bfc936a8f0c3e2eb7d922",
          "sha256": "4c672827bfbb96973334abd9eac4116ba3c1cb5b70f3876e1ac6507f91b35373",
          "sha1": "a4df02747538ffc93c906d286aa08cb965e95b1b",
          "md5": "cd8c306bb7938b88809e3583243bef4f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dokka-configuration-db3eb1b-javadoc.jar",
          "url": "antibytes-dokka-configuration-db3eb1b-javadoc.jar",
          "size": 261,
          "sha512": "ecdc8c7d5e752e74b267c408224812f2bb98822871496d78be1e3d69c38af523d7c6d1c351e7834fa134104005f1fb5731615d6ec713353204ab027eabf9c4f4",
          "sha256": "ba6000d3814621bede9065ae377077bc56304872f34ae2e39a9f127ac204b10f",
          "sha1": "be90a299096885362463c6648fb52a159cd22b83",
          "md5": "82c7fdb21381e65cc0c6d02bdfd59757"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dokka-configuration-db3eb1b-sources.jar",
          "url": "antibytes-dokka-configuration-db3eb1b-sources.jar",
          "size": 2499,
          "sha512": "de15ee98a0b05de7dbe1ecb7f5b0998f054cd88bf1e3e381ae9e6afde09e24e699541c7cf96c27e8a22df265de945855c5677a8ac59ca484b4c7482a190153e1",
          "sha256": "4a8ba90787bdfc27b7275ac5852d958a6f90662e055f409405a49370ad40e348",
          "sha1": "91e8c6ef11a336e07ac2e49fb995601003893458",
          "md5": "b2209a128e1ccf0e1177899655df4da5"
        }
      ]
    }
  ]
}
