{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "cba59bc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-metadata-cba59bc.jar",
          "url": "kmock-cba59bc.jar",
          "size": 21090,
          "sha512": "6483bc305b16984f7cb6b6a2c7db65ffe6bb2e2c62601584e3112e0cbc24cb8d69dd965ffd48aa0d70a3657aaa732ea233cf4f549a9268a616cbbe5a7a4a8e8b",
          "sha256": "9213a9069c24965251bc65e1553c7489ec9b9d1e571a39a6e93a40d796907014",
          "sha1": "da7d73236eb06a987c3fe16c3fc87fa4a27d12ea",
          "md5": "38ed9cfb457f2314b987dd7cbd3ddf2a"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/cba59bc/kmock-android-cba59bc.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "cba59bc"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/cba59bc/kmock-android-cba59bc.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "cba59bc"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/cba59bc/kmock-iosarm64-cba59bc.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "cba59bc"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/cba59bc/kmock-iosx64-cba59bc.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "cba59bc"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/cba59bc/kmock-js-cba59bc.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "cba59bc"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/cba59bc/kmock-js-cba59bc.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "cba59bc"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/cba59bc/kmock-jvm-cba59bc.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "cba59bc"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/cba59bc/kmock-jvm-cba59bc.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "cba59bc"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/cba59bc/kmock-linuxx64-cba59bc.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "cba59bc"
      }
    }
  ]
}
