{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/f163e11/test-utils-ktor-f163e11.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "f163e11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-release.aar",
          "url": "test-utils-ktor-android-f163e11.aar",
          "size": 23764,
          "sha512": "0d352e1d4cc3bc35e081a7f2fe62bfdb8b92e484651d3d9c7034bd9b98d488df4eed36f8b5cdc99d453507bd054a00ebe3efc2732f3a40f18d6a054f64c5b2ac",
          "sha256": "462be426035e4a368630628041e022ea2624210905a408a629b3827a4cefc549",
          "sha1": "23521f97f708a1ae9c7176c5e4670215246f0c54",
          "md5": "9bdf8af4c6e66703104f087be836147d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-release.aar",
          "url": "test-utils-ktor-android-f163e11.aar",
          "size": 23764,
          "sha512": "0d352e1d4cc3bc35e081a7f2fe62bfdb8b92e484651d3d9c7034bd9b98d488df4eed36f8b5cdc99d453507bd054a00ebe3efc2732f3a40f18d6a054f64c5b2ac",
          "sha256": "462be426035e4a368630628041e022ea2624210905a408a629b3827a4cefc549",
          "sha1": "23521f97f708a1ae9c7176c5e4670215246f0c54",
          "md5": "9bdf8af4c6e66703104f087be836147d"
        }
      ]
    }
  ]
}
