{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-runtime-configuration",
    "version": "41c21f2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-41c21f2.jar",
          "url": "antibytes-runtime-configuration-41c21f2.jar",
          "size": 9073,
          "sha512": "05b1e053cd438af1cf3565ddf4992d196cbbd96fe9ef319be0cc1c5e38982aab422086361f7acb1f1b4ce73b57fbff561d6d6683306f0c94fdaeb89c811307fe",
          "sha256": "4904989075e5aa83c267def14e304a8b31a98db0ab1a9a9beac5681608329b9e",
          "sha1": "42ebeffb1859aa7398b04c1e6c342123af8cf725",
          "md5": "58e450476e4860cc48a009a37d51f667"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "41c21f2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-41c21f2.jar",
          "url": "antibytes-runtime-configuration-41c21f2.jar",
          "size": 9073,
          "sha512": "05b1e053cd438af1cf3565ddf4992d196cbbd96fe9ef319be0cc1c5e38982aab422086361f7acb1f1b4ce73b57fbff561d6d6683306f0c94fdaeb89c811307fe",
          "sha256": "4904989075e5aa83c267def14e304a8b31a98db0ab1a9a9beac5681608329b9e",
          "sha1": "42ebeffb1859aa7398b04c1e6c342123af8cf725",
          "md5": "58e450476e4860cc48a009a37d51f667"
        }
      ]
    }
  ]
}
