{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-SNAPSHOT/ktx-datetime-0.3.1-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ktx-datetime-release.aar",
          "url": "ktx-datetime-android-0.3.1-SNAPSHOT.aar",
          "size": 13175,
          "sha512": "7a51b52a4f67bfc5242c06006b1e1ae37e7a45c214a68fdcb29f3e2d39bdbb55bc004dd96892e3c4833a8d866771cecf99fd91090bf624bb99250e45e546f37a",
          "sha256": "7194bd62976dba9cf7e001aba373a508de663bd72045010f5e590df6ebf7b7c2",
          "sha1": "d791ad7a84c4fb55affa9802afd6d3c9eaeee186",
          "md5": "28bc70046d7b71218d9b322b49d5827e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-release.aar",
          "url": "ktx-datetime-android-0.3.1-SNAPSHOT.aar",
          "size": 13175,
          "sha512": "7a51b52a4f67bfc5242c06006b1e1ae37e7a45c214a68fdcb29f3e2d39bdbb55bc004dd96892e3c4833a8d866771cecf99fd91090bf624bb99250e45e546f37a",
          "sha256": "7194bd62976dba9cf7e001aba373a508de663bd72045010f5e590df6ebf7b7c2",
          "sha1": "d791ad7a84c4fb55affa9802afd6d3c9eaeee186",
          "md5": "28bc70046d7b71218d9b322b49d5827e"
        }
      ]
    }
  ]
}
