{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/a7a030d/test-utils-a7a030d.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "a7a030d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-a7a030d.jar",
          "size": 8776,
          "sha512": "a9dbdbe7e22e25c2bd98501df48b0043dea3b2b5eb836be7750e54520e5543cc4a2e702b5ba2c43910984b8368ed00cca286e4171ad5b61472d0b7278281f5a7",
          "sha256": "cec40f2a94e900d1b1fd4553028043ea01947e6edc8e9b6750a9a8a8925f79eb",
          "sha1": "a8dccc927e1cfbce1b881a536f101bc55925f19f",
          "md5": "a0666f1b55e55f1c1e13bf8443c0bc98"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-a7a030d.jar",
          "size": 8776,
          "sha512": "a9dbdbe7e22e25c2bd98501df48b0043dea3b2b5eb836be7750e54520e5543cc4a2e702b5ba2c43910984b8368ed00cca286e4171ad5b61472d0b7278281f5a7",
          "sha256": "cec40f2a94e900d1b1fd4553028043ea01947e6edc8e9b6750a9a8a8925f79eb",
          "sha1": "a8dccc927e1cfbce1b881a536f101bc55925f19f",
          "md5": "a0666f1b55e55f1c1e13bf8443c0bc98"
        }
      ]
    }
  ]
}
