{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/fb654eb/kmock-fb654eb.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "fb654eb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-fb654eb.jar",
          "url": "kmock-jvm-fb654eb.jar",
          "size": 252026,
          "sha512": "eb93fcfff8fcdba10d4e65fc106ee3ae80774f54fc5e349c5c6d7b51388292318e2c2f4a2d2b3bcacd41e6b56e3f23cd44831301ae0516331432874b39cc5543",
          "sha256": "9c7868d5cb8afc2f7d8fc2dcf83397630ba227a826af8f8aef9a3983bbd80929",
          "sha1": "817223e8526d7318f6dbe03533921bbd23c6e31a",
          "md5": "19dbbc9605a44f21748f31557b8801a7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-fb654eb.jar",
          "url": "kmock-jvm-fb654eb.jar",
          "size": 252026,
          "sha512": "eb93fcfff8fcdba10d4e65fc106ee3ae80774f54fc5e349c5c6d7b51388292318e2c2f4a2d2b3bcacd41e6b56e3f23cd44831301ae0516331432874b39cc5543",
          "sha256": "9c7868d5cb8afc2f7d8fc2dcf83397630ba227a826af8f8aef9a3983bbd80929",
          "sha1": "817223e8526d7318f6dbe03533921bbd23c6e31a",
          "md5": "19dbbc9605a44f21748f31557b8801a7"
        }
      ]
    }
  ]
}
