{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "d555f79",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-d555f79.jar",
          "url": "antibytes-publishing-d555f79.jar",
          "size": 105775,
          "sha512": "57a47e7bdd1c5b3c321df37eb7a445844612dcdd62e41ad2151039e1c0b0393990d525e9df380f30f91b87012292c51f570f52430a238837270e8794477195a6",
          "sha256": "01fb96db6ace6ad229cb468fff6bf073c26ac15816c241e6d0bf18cba99f21a4",
          "sha1": "8f5575f849fc4f75bc2d82d08975d002356d6bc8",
          "md5": "099743fa430f1cbfbbfb56b113893742"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.0.0.202111291000-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.12.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "d555f79"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-d555f79.jar",
          "url": "antibytes-publishing-d555f79.jar",
          "size": 105775,
          "sha512": "57a47e7bdd1c5b3c321df37eb7a445844612dcdd62e41ad2151039e1c0b0393990d525e9df380f30f91b87012292c51f570f52430a238837270e8794477195a6",
          "sha256": "01fb96db6ace6ad229cb468fff6bf073c26ac15816c241e6d0bf18cba99f21a4",
          "sha1": "8f5575f849fc4f75bc2d82d08975d002356d6bc8",
          "md5": "099743fa430f1cbfbbfb56b113893742"
        }
      ]
    }
  ]
}
