{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/6be4f13/test-utils-coroutine-6be4f13.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "6be4f13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-coroutine-jvm-6be4f13.jar",
          "url": "test-utils-coroutine-jvm-6be4f13.jar",
          "size": 12013,
          "sha512": "fc896631b57447c190701a56670b0bba7a772593f564cfb409d471eb9467f2471949a26ed062bf9c22200a50085c63a45cb85635ecba77fe325b91d828b64821",
          "sha256": "36ba61f3fce421f0fda50663baddabf57b6914274fb9602ee40d73e81080945a",
          "sha1": "fe17eeb9364c0edfe823dad412f6334e8b4186b3",
          "md5": "e12946ec34608322a68fbb47f3b5165f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-6be4f13.jar",
          "url": "test-utils-coroutine-jvm-6be4f13.jar",
          "size": 12013,
          "sha512": "fc896631b57447c190701a56670b0bba7a772593f564cfb409d471eb9467f2471949a26ed062bf9c22200a50085c63a45cb85635ecba77fe325b91d828b64821",
          "sha256": "36ba61f3fce421f0fda50663baddabf57b6914274fb9602ee40d73e81080945a",
          "sha1": "fe17eeb9364c0edfe823dad412f6334e8b4186b3",
          "md5": "e12946ec34608322a68fbb47f3b5165f"
        }
      ]
    }
  ]
}
