{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/86ec4d6/test-utils-resourceloader-86ec4d6.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "86ec4d6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iossimulatorarm64-86ec4d6.klib",
          "size": 14297,
          "sha512": "59eb510b9d0e4e656e328e083ab683ee6442cefe0410da01c234d3ed00c87d92bcace589bee158f3c36250d5073633a5be4f9dc34643a31d94328e0e6106477b",
          "sha256": "c9f1bc20e9f98190d00c5664035c3e05ef2f0ff6992e61c41ac79ec80c4d8491",
          "sha1": "7495203e757829ba22e174505dec5fa1e6e2cda8",
          "md5": "750b1167d1698ffe2ec04bba2759fcf1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-iossimulatorarm64-86ec4d6-sources.jar",
          "url": "test-utils-resourceloader-iossimulatorarm64-86ec4d6-sources.jar",
          "size": 4241,
          "sha512": "284172150658cfb9dae6c2bb10bbd5de382a8193d892540a4de60322cb16b05740a160fc4f827c092194ab0e3983419cb75c9d52eee7cf9cf1ac22b32a8f7d7b",
          "sha256": "28c33fb0c5429879a7515dfb1ee5400a354f30a17cda3a32c13cec2fd413b7da",
          "sha1": "e6bc305f912fc8fc1e733215728491f83d594bd4",
          "md5": "935272aedc89d60202c3ad87a167495a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iossimulatorarm64-86ec4d6-metadata.jar",
          "url": "test-utils-resourceloader-iossimulatorarm64-86ec4d6-metadata.jar",
          "size": 261,
          "sha512": "13708f542c5b79a148a40fca18f289996a427c61648335d51bd51bd1deef421f0732c39477918e0b0f9f1f1999340d73deda0d191f6ac5c57f0072edee280a1b",
          "sha256": "21d91f8bbb638b5b4278d223f77fef126d280aa3ed5bd2411ee9488feb4a9cb1",
          "sha1": "1a0054cb7f61424885277a6a2465cf536d797292",
          "md5": "6821bf94ed2b49cb8a519b9e587a52fe"
        }
      ]
    }
  ]
}
