{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-androidnativearm64-0.4.0-SNAPSHOT.klib",
          "size": 113583,
          "sha512": "a4ab5677ad5075ea1836b97da10a64c8edb1db741dfb14732551e1e049903e24f874f3d226cb3450831ba77985139045915cfa742323dcb5900359e7a7f39996",
          "sha256": "4b31e9b55ec95e2b8d5a9f7f6e0a46b220bd407551bb529d92ef2c9216c6163d",
          "sha1": "ccc645ee5e5459b7bd08605090f81a481850901e",
          "md5": "80fcb7d66f110e58a842f64cfbc8f7aa"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-androidnativearm64-0.4.0-SNAPSHOT-sources.jar",
          "url": "core-androidnativearm64-0.4.0-SNAPSHOT-sources.jar",
          "size": 48843,
          "sha512": "02b779d206e7862a26b0330fcb090100c9d196fbc28bceaff452c2dded1de091c242d638767a6b5970fce31db3f59942f32ea8632beee3df70a6e4e5e463cc42",
          "sha256": "e839d09e900a7efe6e276e9b64eccc1d8325fbf7fd254ff72deeb2935868c75d",
          "sha1": "95cb16d25a14e253822596920de6c0903afb2ff3",
          "md5": "462cfdf835b3bc65281d914ae146d5d4"
        }
      ]
    }
  ]
}
