{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/64c6243/test-utils-fixture-64c6243.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "64c6243",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm-64c6243.jar",
          "url": "test-utils-fixture-jvm-64c6243.jar",
          "size": 43614,
          "sha512": "1661827b3f6841f9854b688f6799fe9cab3679b9d657860877ebafc945c4027822f1a69db6aa9b512c717798ce74194152cfac3211b132b870dc761f400b5d5a",
          "sha256": "355c2ff2aee391831adb573d45ce993bfb0a497380c978ad6643b150f77f4cae",
          "sha1": "a010feeb800ed971f88c149d9c4dc16d39c587d1",
          "md5": "a7010ff1c2552e23a24233a473d50e0c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm-64c6243.jar",
          "url": "test-utils-fixture-jvm-64c6243.jar",
          "size": 43614,
          "sha512": "1661827b3f6841f9854b688f6799fe9cab3679b9d657860877ebafc945c4027822f1a69db6aa9b512c717798ce74194152cfac3211b132b870dc761f400b5d5a",
          "sha256": "355c2ff2aee391831adb573d45ce993bfb0a497380c978ad6643b150f77f4cae",
          "sha1": "a010feeb800ed971f88c149d9c4dc16d39c587d1",
          "md5": "a7010ff1c2552e23a24233a473d50e0c"
        }
      ]
    }
  ]
}
