{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "fa9f81c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-fa9f81c.jar",
          "url": "antibytes-versioning-fa9f81c.jar",
          "size": 21893,
          "sha512": "ddd93e132856fa9d989250a0b92f936af5fa1b1bf9c0f3bcd9eaaaeeda21d77d1bcdc7e20ec7f3d64a3848a184c5713140be8c91654ce40037c58b973d05f79a",
          "sha256": "f2fd14276465f4dd80c9e977be89f81acfee258cd47accbc9491f066e5011e4a",
          "sha1": "f02bb0746fa0b96790c09f3d0dd37fe1511661db",
          "md5": "093f90c9e45a875dbfb8deb2725a12f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-fa9f81c.jar",
          "url": "antibytes-versioning-fa9f81c.jar",
          "size": 21893,
          "sha512": "ddd93e132856fa9d989250a0b92f936af5fa1b1bf9c0f3bcd9eaaaeeda21d77d1bcdc7e20ec7f3d64a3848a184c5713140be8c91654ce40037c58b973d05f79a",
          "sha256": "f2fd14276465f4dd80c9e977be89f81acfee258cd47accbc9491f066e5011e4a",
          "sha1": "f02bb0746fa0b96790c09f3d0dd37fe1511661db",
          "md5": "093f90c9e45a875dbfb8deb2725a12f4"
        }
      ]
    }
  ]
}
