{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/24bf67b/test-utils-annotations-24bf67b.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "24bf67b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js.klib",
          "url": "test-utils-annotations-js-24bf67b.klib",
          "size": 9629,
          "sha512": "22de7a4a15da989691f55213fb84d6963ea4f59474884360490792e590b34e11e8e851053e498b4dd2fa8c409d99dc25b10fe7c7d02a08eb2e184d2f8103b431",
          "sha256": "899d05b2a034afa43f8eeb494815b38059c10c14b22d0cd4a5570a1b6ac366fe",
          "sha1": "74557f9818890e35f5a3233b2a472a027dfbdaef",
          "md5": "c8ca6890beb85536ccc195ce72b787b6"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js.klib",
          "url": "test-utils-annotations-js-24bf67b.klib",
          "size": 9629,
          "sha512": "22de7a4a15da989691f55213fb84d6963ea4f59474884360490792e590b34e11e8e851053e498b4dd2fa8c409d99dc25b10fe7c7d02a08eb2e184d2f8103b431",
          "sha256": "899d05b2a034afa43f8eeb494815b38059c10c14b22d0cd4a5570a1b6ac366fe",
          "sha1": "74557f9818890e35f5a3233b2a472a027dfbdaef",
          "md5": "c8ca6890beb85536ccc195ce72b787b6"
        }
      ]
    }
  ]
}
