{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/b5aaed7/test-utils-coroutine-b5aaed7.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "b5aaed7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosx64-b5aaed7.klib",
          "size": 10112,
          "sha512": "0c9109497ef5116df57d780fb9927fa9a211b8c342a4a7fbb3461b555cfc0a69658dd4d762d29aeb47083f1264b99df98abe9ca148acfe1f7227ae8e67041ad7",
          "sha256": "2da8c8de1522ad369562f0bd2b838eba30fdb3b2eefa319776aab12fff1d9c69",
          "sha1": "3d1c065ed2929a8a21b7209b42256a163e080647",
          "md5": "6e8825ff0ee058c6b2a9aeeefd714a50"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosx64-b5aaed7-metadata.jar",
          "url": "test-utils-coroutine-iosx64-b5aaed7-metadata.jar",
          "size": 261,
          "sha512": "cad270b73dd2b10eec023ebbba30b9c83ac8d139c3f178fd027391b0e6489f46d3a3f73076a552ed389520a4ca8778ba3852e014449556268d0a754d7dc511e3",
          "sha256": "d1d2912de73ca92755a1c52d98c9723867f6e2d5d75a75f7bbf4dc42e4fdbce7",
          "sha1": "0453aa18cfb338db6355bbc160940a4e440f71d4",
          "md5": "fbcb636d796dfb0f946dc320303cd0f3"
        }
      ]
    }
  ]
}
