{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "d50bc26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-d50bc26.jar",
          "url": "antibytes-dependency-node-d50bc26.jar",
          "size": 20149,
          "sha512": "30489a6c99656590df5e793ff90b4f616c2f6db7708237805bf7ae26e7b136a5d6330631d21c194134982b8e90d7a6cef073b4e7f6afb7ae4169db53dff23d7b",
          "sha256": "e077da376b23794363681326cdec37f7ca47d12e670df78c67310fb5cb1b0a03",
          "sha1": "0027cbb51e8472f8c4b90633cdd48c1abab6a115",
          "md5": "b47983e39115b1ea8f891f25d4e59392"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-d50bc26.jar",
          "url": "antibytes-dependency-node-d50bc26.jar",
          "size": 20149,
          "sha512": "30489a6c99656590df5e793ff90b4f616c2f6db7708237805bf7ae26e7b136a5d6330631d21c194134982b8e90d7a6cef073b4e7f6afb7ae4169db53dff23d7b",
          "sha256": "e077da376b23794363681326cdec37f7ca47d12e670df78c67310fb5cb1b0a03",
          "sha1": "0027cbb51e8472f8c4b90633cdd48c1abab6a115",
          "md5": "b47983e39115b1ea8f891f25d4e59392"
        }
      ]
    }
  ]
}
