{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "74f873c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-74f873c.jar",
          "url": "antibytes-gradle-utils-74f873c.jar",
          "size": 9471,
          "sha512": "e092755f2a62cac4893a8bf98a33003bc1d8994c8818fbe40bb5f2b94b7bd5978debf1a69305a8e544cc72df0633b88ed84d019012856a361f48ff53beb1791f",
          "sha256": "2da36803b7d6ac79c73ba605ce688d0218458f3eb4f77620760b73c053585815",
          "sha1": "a9ebae117b884d457f4867655e7d7b42aadc4291",
          "md5": "3e066133490b1b54e09e74ca9c7bd849"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-74f873c.jar",
          "url": "antibytes-gradle-utils-74f873c.jar",
          "size": 9471,
          "sha512": "e092755f2a62cac4893a8bf98a33003bc1d8994c8818fbe40bb5f2b94b7bd5978debf1a69305a8e544cc72df0633b88ed84d019012856a361f48ff53beb1791f",
          "sha256": "2da36803b7d6ac79c73ba605ce688d0218458f3eb4f77620760b73c053585815",
          "sha1": "a9ebae117b884d457f4867655e7d7b42aadc4291",
          "md5": "3e066133490b1b54e09e74ca9c7bd849"
        }
      ]
    }
  ]
}
