{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "9b8f33c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n-metadata-9b8f33c-all.jar",
          "url": "banana-i18n-9b8f33c-all.jar",
          "size": 670,
          "sha512": "5c692631ab9ea27ffeda812a976742da4bb21c5d35ad2adf06a33d9502de8ff1207b28a70b18b3dcd769eef4b51025f1b2c2938b2f778c0256b176796f894fbb",
          "sha256": "a9ea042c0363b2274eb178aca4e36a29b727319dec8a4b1c55936946ef96a66d",
          "sha1": "f793a966927e436a9310990e3496a71c5fedc884",
          "md5": "6a355334ebd3037f4ad95c1629d64ea4"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n-9b8f33c.jar",
          "url": "banana-i18n-9b8f33c.jar",
          "size": 26844,
          "sha512": "5f9e7e92cea14aea18b6e07688160feadf121fb250792bebd40d060402a6b314a7314c69065e602c32ac9a2c2a184c73addeb6a0aa8b51ad1a8d2ca1eec7eadf",
          "sha256": "6349ddcb9a730987215e358debb6d58ddd1a31efbc41ed8a5f422e307c27f460",
          "sha1": "0fd07e665faa2e309d59749e8fb8565bf9027faf",
          "md5": "3edb7647847c1a7a5b5ef4c42d78131d"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/9b8f33c/banana-i18n-android-9b8f33c.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "9b8f33c"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/9b8f33c/banana-i18n-android-9b8f33c.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "9b8f33c"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/9b8f33c/banana-i18n-jvm-9b8f33c.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "9b8f33c"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/9b8f33c/banana-i18n-jvm-9b8f33c.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "9b8f33c"
      }
    }
  ]
}
