{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "8686647",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-8686647.jar",
          "url": "antibytes-versioning-8686647.jar",
          "size": 21893,
          "sha512": "bceca6d65f44b5029a21c4aa08d9d6bdc2dcff62069ac1f9642018cd3b6fbb66623938c3011c21d21e2ac98edba029aa0f33409a89aee638421f98c18284a372",
          "sha256": "47e792742c54686f63427a7a5400d519a1377630dc463a36d3596f659c290685",
          "sha1": "ec9bca32bab079d24cce46296d599de942e34b1c",
          "md5": "d426a677875347137f9e1d618553b649"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-8686647.jar",
          "url": "antibytes-versioning-8686647.jar",
          "size": 21893,
          "sha512": "bceca6d65f44b5029a21c4aa08d9d6bdc2dcff62069ac1f9642018cd3b6fbb66623938c3011c21d21e2ac98edba029aa0f33409a89aee638421f98c18284a372",
          "sha256": "47e792742c54686f63427a7a5400d519a1377630dc463a36d3596f659c290685",
          "sha1": "ec9bca32bab079d24cce46296d599de942e34b1c",
          "md5": "d426a677875347137f9e1d618553b649"
        }
      ]
    }
  ]
}
