{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "7687817",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-7687817.jar",
          "url": "antibytes-dependency-helper-7687817.jar",
          "size": 69711,
          "sha512": "3fe6857d72926c7ad4ace67029ef00bb140ad03076f413f01771962d3ebcc22fce282236e84e0929f51b464c6159239f2f6ea9de961b577c86b3e89a2c00282a",
          "sha256": "01f79ade43979ad763c01d21b69a618bdb8af7ff1c9f4655ca202e0dbda8571d",
          "sha1": "02f1271db79c64e0f4b9cdfcffa252971265153d",
          "md5": "d6a8c45f49661d24d7e3b0440a60fee5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.49.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "7687817"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-7687817.jar",
          "url": "antibytes-dependency-helper-7687817.jar",
          "size": 69711,
          "sha512": "3fe6857d72926c7ad4ace67029ef00bb140ad03076f413f01771962d3ebcc22fce282236e84e0929f51b464c6159239f2f6ea9de961b577c86b3e89a2c00282a",
          "sha256": "01f79ade43979ad763c01d21b69a618bdb8af7ff1c9f4655ca202e0dbda8571d",
          "sha1": "02f1271db79c64e0f4b9cdfcffa252971265153d",
          "md5": "d6a8c45f49661d24d7e3b0440a60fee5"
        }
      ]
    }
  ]
}
