{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "b6f4fbe",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "b6f4fbe"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-b6f4fbe.jar",
          "url": "antibytes-publishing-b6f4fbe.jar",
          "size": 117676,
          "sha512": "7592d1e3900e840b0c9b13560227b8942cd0d46c3dd5e6f85f73bc463cf16cd1e4d7f0195174a0c15717440123192e48eaeb8a510e0675804d3c72dd5805e2e8",
          "sha256": "7c5df1576e50b7f23bb2e569b77cdf8b2520763f1e576b9cfe0d9e14ca3925b6",
          "sha1": "a12319ffb84cf9ced80263db53776078f0730d17",
          "md5": "09b30e4e19df2e627d80ad77b82b4b06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.2.0.202206071550-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "b6f4fbe"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "b6f4fbe"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-b6f4fbe.jar",
          "url": "antibytes-publishing-b6f4fbe.jar",
          "size": 117676,
          "sha512": "7592d1e3900e840b0c9b13560227b8942cd0d46c3dd5e6f85f73bc463cf16cd1e4d7f0195174a0c15717440123192e48eaeb8a510e0675804d3c72dd5805e2e8",
          "sha256": "7c5df1576e50b7f23bb2e569b77cdf8b2520763f1e576b9cfe0d9e14ca3925b6",
          "sha1": "a12319ffb84cf9ced80263db53776078f0730d17",
          "md5": "09b30e4e19df2e627d80ad77b82b4b06"
        }
      ]
    }
  ]
}
