{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/7281fe2/test-utils-fixture-7281fe2.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "7281fe2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm-7281fe2.jar",
          "url": "test-utils-fixture-jvm-7281fe2.jar",
          "size": 68983,
          "sha512": "7146d936deaa88cadd37a31cff6e97836338d56d04d31bf481dfd8f5cf125ebc578370b311c540ff1d563d3cd34376b321ab901f8a1fcb98756c1f5bce84337f",
          "sha256": "e7b7d4a329bfda6ba9c882b0f63ff2b1ec04eca3627de5a0cc9c7cc446fcb541",
          "sha1": "22a99ab0d4b0480e4936d0c4d463d57667ebd30a",
          "md5": "78d13ba3378c524563cd77ca82c05e59"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm-7281fe2.jar",
          "url": "test-utils-fixture-jvm-7281fe2.jar",
          "size": 68983,
          "sha512": "7146d936deaa88cadd37a31cff6e97836338d56d04d31bf481dfd8f5cf125ebc578370b311c540ff1d563d3cd34376b321ab901f8a1fcb98756c1f5bce84337f",
          "sha256": "e7b7d4a329bfda6ba9c882b0f63ff2b1ec04eca3627de5a0cc9c7cc446fcb541",
          "sha1": "22a99ab0d4b0480e4936d0c4d463d57667ebd30a",
          "md5": "78d13ba3378c524563cd77ca82c05e59"
        }
      ]
    }
  ]
}
