{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.quality",
    "module": "antibytes-quality",
    "version": "313c993",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "4.4.1.3373"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-313c993.jar",
          "url": "antibytes-quality-313c993.jar",
          "size": 64846,
          "sha512": "9175f6cbbe92744df850e9c6b9bb8b5497f24bbc5de1a15a8a1fe82e4b90f271ea2171b153884c41ea57711a84639476d6f7b0f756d5c388c64452463fa95ef5",
          "sha256": "fb0848436e1aed29a5e0bbb7b14193e0e0c1cfad8ba30132b34670cdfaeac880",
          "sha1": "410ef017ad707b31bab7070abc0cd8219873ffa7",
          "md5": "b6681fda72aeb045f939bcfbd0d7965a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.25.0"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "313c993"
          }
        },
        {
          "group": "tech.antibytes.gradle.dependency.helper",
          "module": "antibytes-dependency-helper",
          "version": {
            "requires": "313c993"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "4.4.1.3373"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-313c993.jar",
          "url": "antibytes-quality-313c993.jar",
          "size": 64846,
          "sha512": "9175f6cbbe92744df850e9c6b9bb8b5497f24bbc5de1a15a8a1fe82e4b90f271ea2171b153884c41ea57711a84639476d6f7b0f756d5c388c64452463fa95ef5",
          "sha256": "fb0848436e1aed29a5e0bbb7b14193e0e0c1cfad8ba30132b34670cdfaeac880",
          "sha1": "410ef017ad707b31bab7070abc0cd8219873ffa7",
          "md5": "b6681fda72aeb045f939bcfbd0d7965a"
        }
      ]
    }
  ]
}
