{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-mkdocs",
    "version": "01e59f4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "01e59f4"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-01e59f4.jar",
          "url": "antibytes-mkdocs-01e59f4.jar",
          "size": 11951,
          "sha512": "3c1e4135c3a353e89a71cb6eaf81ea2859325642b1ebddb56839cdffe0f3750bed8668dce1947900d1207bccc79fd93f7c29a43a4c4f8521f703121bea0bf87f",
          "sha256": "9050ebeae3866b77f50056249dcd17b2b38f09ca022473ec956650485cf52660",
          "sha1": "cec43f738fb4cb2f502ed59858099ed67e491b3b",
          "md5": "0243a7baf40dd8c1bab97a4a6cb97051"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "01e59f4"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "01e59f4"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-01e59f4.jar",
          "url": "antibytes-mkdocs-01e59f4.jar",
          "size": 11951,
          "sha512": "3c1e4135c3a353e89a71cb6eaf81ea2859325642b1ebddb56839cdffe0f3750bed8668dce1947900d1207bccc79fd93f7c29a43a4c4f8521f703121bea0bf87f",
          "sha256": "9050ebeae3866b77f50056249dcd17b2b38f09ca022473ec956650485cf52660",
          "sha1": "cec43f738fb4cb2f502ed59858099ed67e491b3b",
          "md5": "0243a7baf40dd8c1bab97a4a6cb97051"
        }
      ]
    }
  ]
}
