{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "967d356",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-967d356.jar",
          "url": "antibytes-dependency-967d356.jar",
          "size": 71463,
          "sha512": "c83ba51ad2c1c6f6f8369bb4a6004e0804cde735b4c9464741a7e4b31fbb2039e138f689041ce0c5099a46d3431f745f3b7eb7e9f2a3b0b05d2f017773ae1c23",
          "sha256": "a53cdda2dd94b9bb36b96ed754922e0114878d1ce7c45ec01238b03218b783a2",
          "sha1": "b1a5f8d40750100b8c5a352a28378726ff5c04f5",
          "md5": "4a598ab6a5dd94d3a1faae6f8c449853"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-gradle-plugin",
          "version": {
            "requires": "0.17.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.0.4.1"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.44.0"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "967d356"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-967d356.jar",
          "url": "antibytes-dependency-967d356.jar",
          "size": 71463,
          "sha512": "c83ba51ad2c1c6f6f8369bb4a6004e0804cde735b4c9464741a7e4b31fbb2039e138f689041ce0c5099a46d3431f745f3b7eb7e9f2a3b0b05d2f017773ae1c23",
          "sha256": "a53cdda2dd94b9bb36b96ed754922e0114878d1ce7c45ec01238b03218b783a2",
          "sha1": "b1a5f8d40750100b8c5a352a28378726ff5c04f5",
          "md5": "4a598ab6a5dd94d3a1faae6f8c449853"
        }
      ]
    }
  ]
}
