{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/0a42b71/test-utils-fixture-0a42b71.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "0a42b71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm-0a42b71.jar",
          "url": "test-utils-fixture-jvm-0a42b71.jar",
          "size": 43668,
          "sha512": "ee9a743f4a456a25049efd6e15a53505e792d7fe73228293ec3cf98fa04148b2fa351323ebb2044e630d365324c39c445fa0ae544b4f54a8e359ce4053e0566c",
          "sha256": "3042fba6314430f3a53c5621ff7cb52cb3f60eef4117dd74475e310b7cc041a7",
          "sha1": "164dbb8934aeaff3be13baa63c75549a79752994",
          "md5": "1d8410e49a28624e63d66a1efe6e49a6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm-0a42b71.jar",
          "url": "test-utils-fixture-jvm-0a42b71.jar",
          "size": 43668,
          "sha512": "ee9a743f4a456a25049efd6e15a53505e792d7fe73228293ec3cf98fa04148b2fa351323ebb2044e630d365324c39c445fa0ae544b4f54a8e359ce4053e0566c",
          "sha256": "3042fba6314430f3a53c5621ff7cb52cb3f60eef4117dd74475e310b7cc041a7",
          "sha1": "164dbb8934aeaff3be13baa63c75549a79752994",
          "md5": "1d8410e49a28624e63d66a1efe6e49a6"
        }
      ]
    }
  ]
}
