{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-macosarm64-0.4.0-SNAPSHOT.klib",
          "size": 105853,
          "sha512": "59682954cdcce8ae8bf903c168f3616bfe022737c386899ff953dae5e3ef58c2ae5a0a1688cbf4007905c87ebd3ca6fb1e2f040e55eeef419aa99ece3c4240f7",
          "sha256": "9b86b4b1dc9e1f76700139dd56fcceb647ca299785f2504c72bb5102e63213c5",
          "sha1": "bd98e1bfb5e34d7ce4a6bb54797e4b0b3201bb3a",
          "md5": "c6d497be75c9e8e11a1e3e13f90f9456"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-macosarm64-0.4.0-SNAPSHOT-metadata.jar",
          "url": "core-macosarm64-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d435b269c31f3508f9611d50f552e10e9b65a0808a26c0e0b19d8873e9a8856882ddc1ee2a6d9c09ce7219beca46366576fc577b7a752c1bbfa5ef20947693a8",
          "sha256": "dcf8fd06d0dae71da9159ea44a88e3a158161556be4f8beb085b34fe1335ab25",
          "sha1": "069145b919ba617b7c94b44b45166e83c0f4b550",
          "md5": "34545ba7a1519c3c57c117c8d61b4dcd"
        }
      ]
    }
  ]
}
