{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.quality",
    "module": "antibytes-quality",
    "version": "96b20e0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-quality-96b20e0.jar",
          "url": "antibytes-quality-96b20e0.jar",
          "size": 62564,
          "sha512": "05b870fa98d26dbb1a6df1374bc7803e85c3260378d257d56142e9c2466cb48d7a8410ed954b132499e262acda58d578e633e47f66094c78b0e759686113841a",
          "sha256": "f8169adae271ea754e0ed5f199fdb9569f404225019c0ad534d2149ec723895e",
          "sha1": "7b66eec13dcb0be1966449090cfa230be5fd3197",
          "md5": "8106da2e856c32c80da1b3f66b83446e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.21.0"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "96b20e0"
          }
        },
        {
          "group": "tech.antibytes.gradle.dependency.helper",
          "module": "antibytes-dependency-helper",
          "version": {
            "requires": "96b20e0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-96b20e0.jar",
          "url": "antibytes-quality-96b20e0.jar",
          "size": 62564,
          "sha512": "05b870fa98d26dbb1a6df1374bc7803e85c3260378d257d56142e9c2466cb48d7a8410ed954b132499e262acda58d578e633e47f66094c78b0e759686113841a",
          "sha256": "f8169adae271ea754e0ed5f199fdb9569f404225019c0ad534d2149ec723895e",
          "sha1": "7b66eec13dcb0be1966449090cfa230be5fd3197",
          "md5": "8106da2e856c32c80da1b3f66b83446e"
        }
      ]
    }
  ]
}
