{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/b6c6e6c/test-utils-coroutine-b6c6e6c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "b6c6e6c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-watchosarm32-b6c6e6c.klib",
          "size": 11085,
          "sha512": "3f01f23a30dc50164ab7348f46f5a50c5e0279cb444b6df980c6a75eca76b37a0f3cd2802d1e94a5ae093569b5fd1156f30062cba7e277f2004783d1e343e77e",
          "sha256": "95686907262584d70cc79cc5e3f6b6a4165928691956940fb1d6d63dabc6d92a",
          "sha1": "a3754e7a0f92a65338b49de1e82aebac0468ed11",
          "md5": "7bbea017ee2d742a29a7cd64b21657b4"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-coroutine-watchosarm32-b6c6e6c-sources.jar",
          "url": "test-utils-coroutine-watchosarm32-b6c6e6c-sources.jar",
          "size": 4432,
          "sha512": "a6473d4ff59cb600f3c0fa9878a35c8f858acacd98510b4befc1e5f35be910c62a88e3b6041f5ba76c050b7c41af13fff93cd8bf60902a249f16b7429faa3ecf",
          "sha256": "cec6c043fde96eb3a674995451dc91cc39b82763e15d04e005be7dc8b426bde6",
          "sha1": "9c071f18ad7900caca2bc6884118c0e6ea620326",
          "md5": "a9e30d3490844e974b0610b29233965f"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-watchosarm32-b6c6e6c-metadata.jar",
          "url": "test-utils-coroutine-watchosarm32-b6c6e6c-metadata.jar",
          "size": 261,
          "sha512": "a1620f92785803755ce33f4d9fbfec6b1baaf274962b43c05cf5cdec9a82b50c3acb7b47172fd7162c9c2507e9228bc5d76afb5286d26bdbb3e456465cd90f9b",
          "sha256": "33c1a486b9d14963c3406351b10640d3fb26bfde3acc739b84c1d26236ed0f51",
          "sha1": "36e79190cf59e32564d573d47613e45bdbaa1fdd",
          "md5": "67560577b905dd33638666811c596ef2"
        }
      ]
    }
  ]
}
