{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/3e118d0/test-utils-3e118d0.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "3e118d0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm-3e118d0.jar",
          "url": "test-utils-jvm-3e118d0.jar",
          "size": 8814,
          "sha512": "01ee8ec44c3306477e24f3090d29c2498b8ca14576c91004a4186fa78feb8aac58ab7fe1b4f5feaa544246c493026008e07e4a0f1e9a686eaf253336425042cd",
          "sha256": "bf53109c1a6f60716982cafdf81edac660b73918442b828a80d15345d07f22ea",
          "sha1": "9145423541f740a5b25b642f4bcf82ca3b2746b9",
          "md5": "6a125d69985a161877a74f4cc91c7145"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-3e118d0.jar",
          "url": "test-utils-jvm-3e118d0.jar",
          "size": 8814,
          "sha512": "01ee8ec44c3306477e24f3090d29c2498b8ca14576c91004a4186fa78feb8aac58ab7fe1b4f5feaa544246c493026008e07e4a0f1e9a686eaf253336425042cd",
          "sha256": "bf53109c1a6f60716982cafdf81edac660b73918442b828a80d15345d07f22ea",
          "sha1": "9145423541f740a5b25b642f4bcf82ca3b2746b9",
          "md5": "6a125d69985a161877a74f4cc91c7145"
        }
      ]
    }
  ]
}
