{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/10714ef/kmock-10714ef.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "10714ef",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosx64-10714ef.klib",
          "size": 115142,
          "sha512": "04c6dab21ffc3290c246a9994c9b271390e3f09b460e7524f62a9232426a642190bb1d73dbf45e3c2e2449ba04e15f0507bca8debd138d54dd83eeff81b9f584",
          "sha256": "a185e8727f8b30d95c1a9c287f55fde75967de7ef0acd2b50458f64fc477a948",
          "sha1": "93a47299edddb42eecddb6cc2eb628263fc65d90",
          "md5": "665ccfa1d3dd4c85ae432c21509a95ef"
        }
      ]
    }
  ]
}
