{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/3e118d0/test-utils-ktor-3e118d0.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "3e118d0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-3e118d0.klib",
          "url": "test-utils-ktor-js-3e118d0.klib",
          "size": 12119,
          "sha512": "fff014fbed7519d302209d7850c3b3028c73aa2fc952008027c5175b4fc873aed0ce8d69017a913a6e64dbf0b51df1ce75c3d485f308a533a8b3eee7c8509d46",
          "sha256": "32a815fce4ac236d4f2eadca5bd6b2b70913c14fb9284f2e7d0e1a3e390457e0",
          "sha1": "6b764a5a2fa02e5391bf37107006547e8c9cdab9",
          "md5": "68589a39819a77d4029105e31f1dc4d6"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-3e118d0.klib",
          "url": "test-utils-ktor-js-3e118d0.klib",
          "size": 12119,
          "sha512": "fff014fbed7519d302209d7850c3b3028c73aa2fc952008027c5175b4fc873aed0ce8d69017a913a6e64dbf0b51df1ce75c3d485f308a533a8b3eee7c8509d46",
          "sha256": "32a815fce4ac236d4f2eadca5bd6b2b70913c14fb9284f2e7d0e1a3e390457e0",
          "sha1": "6b764a5a2fa02e5391bf37107006547e8c9cdab9",
          "md5": "68589a39819a77d4029105e31f1dc4d6"
        }
      ]
    }
  ]
}
