{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-quality",
    "version": "03118a6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-quality-03118a6.jar",
          "url": "antibytes-quality-03118a6.jar",
          "size": 62318,
          "sha512": "60bc978809972b8a565e3c1936e296e326c90d4e9cd682820009abe87b0431643e4415ff7ff96743c7d9684e9180b493f1b4b7f9b39b69df90fc0243d4fd49a3",
          "sha256": "77f2eb020ea8f0f02e50a4a2c463636725078a71a9cb9540b073a270f038c4ee",
          "sha1": "c40ffdb32514caad972b396cc8e702269de6f95f",
          "md5": "7200443147d1553e45f5a6d6596c438c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.21.0"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-03118a6.jar",
          "url": "antibytes-quality-03118a6.jar",
          "size": 62318,
          "sha512": "60bc978809972b8a565e3c1936e296e326c90d4e9cd682820009abe87b0431643e4415ff7ff96743c7d9684e9180b493f1b4b7f9b39b69df90fc0243d4fd49a3",
          "sha256": "77f2eb020ea8f0f02e50a4a2c463636725078a71a9cb9540b073a270f038c4ee",
          "sha1": "c40ffdb32514caad972b396cc8e702269de6f95f",
          "md5": "7200443147d1553e45f5a6d6596c438c"
        }
      ]
    }
  ]
}
