{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/b7a1e13/kmock-b7a1e13.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "b7a1e13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-b7a1e13.jar",
          "url": "kmock-jvm-b7a1e13.jar",
          "size": 252905,
          "sha512": "439536ded2f1e7929d8194b5e407890331b465f14661974c7767d5159104c035e8315a90d3823fae9a0c3b2227f66370549409d9ad93071e426b0727e9227134",
          "sha256": "2fcd715fb41f2e072f7779864d875ce200dc381d64e337a99efc5c6c2159f18e",
          "sha1": "b30880dfa4831e2fe3120c2b03413a48a53626d3",
          "md5": "64fcb909e9dcc128e13d32f7fb06d541"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-b7a1e13.jar",
          "url": "kmock-jvm-b7a1e13.jar",
          "size": 252905,
          "sha512": "439536ded2f1e7929d8194b5e407890331b465f14661974c7767d5159104c035e8315a90d3823fae9a0c3b2227f66370549409d9ad93071e426b0727e9227134",
          "sha256": "2fcd715fb41f2e072f7779864d875ce200dc381d64e337a99efc5c6c2159f18e",
          "sha1": "b30880dfa4831e2fe3120c2b03413a48a53626d3",
          "md5": "64fcb909e9dcc128e13d32f7fb06d541"
        }
      ]
    }
  ]
}
