{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "de4d813",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-de4d813.jar",
          "url": "antibytes-gradle-test-utils-de4d813.jar",
          "size": 17888,
          "sha512": "2a32a0c14874caf612a654aff103812436013897ae8e435e36372fec1fb1cd1d8ffd1131a7d89c1162e8c67e2dac12ed7300943977816d4a82137da414b7d9b8",
          "sha256": "4698f5ae8c7c3ded96bf16fe27c7fbec07505c3d5c010ca21f03c48af4f509b9",
          "sha1": "310b00790feb2377f3a8ea85caf3465925f46e18",
          "md5": "1957b5ec9125eac41c870849e1ff6b26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-de4d813.jar",
          "url": "antibytes-gradle-test-utils-de4d813.jar",
          "size": 17888,
          "sha512": "2a32a0c14874caf612a654aff103812436013897ae8e435e36372fec1fb1cd1d8ffd1131a7d89c1162e8c67e2dac12ed7300943977816d4a82137da414b7d9b8",
          "sha256": "4698f5ae8c7c3ded96bf16fe27c7fbec07505c3d5c010ca21f03c48af4f509b9",
          "sha1": "310b00790feb2377f3a8ea85caf3465925f46e18",
          "md5": "1957b5ec9125eac41c870849e1ff6b26"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-de4d813-javadoc.jar",
          "url": "antibytes-gradle-test-utils-de4d813-javadoc.jar",
          "size": 261,
          "sha512": "124df6511919d33d993378749b9ae71012074a4dfc6802ea7f8d55e996a24f0363785e66806348fde31b102ed9e2287fb614b3a0db680e0499a5c0e180a9c258",
          "sha256": "ddebca844fd23b5f6f8e4b16b85f73e78c081ef8b0eb020e666858edb71d7464",
          "sha1": "ed4fb14766a6ff62f7c2cff02a470544a8af7c7a",
          "md5": "972b7a102b5b7a8e95486e905907868d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-de4d813-sources.jar",
          "url": "antibytes-gradle-test-utils-de4d813-sources.jar",
          "size": 3097,
          "sha512": "04852d54af49fc6305e31028273787e5b7d6c368d72ba0e1b62e7fae79b84ab292ff9502d0cc2f4e8bbd4ea5ee5238a0e729da2170f4e96ca80467482269374a",
          "sha256": "bf603c22f5801e72f2bf21d4c936687a3ff76c18bc1cf2c84094eb496efa3997",
          "sha1": "cb0753096ebc95913bea08b1a3aa82f927a39bd9",
          "md5": "d5d8594e90fa95b2c9ec5e8099b9d084"
        }
      ]
    }
  ]
}
