{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "5318a03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-annotations-metadata-all.jar",
          "url": "test-utils-annotations-5318a03-all.jar",
          "size": 4917,
          "sha512": "a6b67b5567870072929303bfafc5a58c0f61109f9fe0f866d5445fb0ae7c3a1fea5c775240fe5187bb2ba25e59fccc9ed1a9f73d60b4d2cc71fc1e8696b43146",
          "sha256": "1b80b0df614af32f28501cef41e48c1b226c26808702c5150aeff2dfacbe3ba4",
          "sha1": "4e10e728689ddcb6efa12c69545226d1708cb747",
          "md5": "125977b3d1d6058087ed160d0f35fbcd"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-annotations.jar",
          "url": "test-utils-annotations-5318a03.jar",
          "size": 7367,
          "sha512": "99709e567b0fed92d56dcd4065def2d0b5a6da4be5f3411588e982ab1ea5c6e4cd23b9937cbed1c130f63d9b3a10443262fe582c45a0bbf5e481877e3b472100",
          "sha256": "972e6ee2a2908e8d7eb7d67987426eda851362d23421090aa2d00b9439dd32ee",
          "sha1": "325adbe60f504c0d0146482c5e9293b552c3b8d8",
          "md5": "6b25ffde8946022539ed01957ca4ccda"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-android/5318a03/test-utils-annotations-android-5318a03.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-android",
        "version": "5318a03"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-android/5318a03/test-utils-annotations-android-5318a03.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-android",
        "version": "5318a03"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-js/5318a03/test-utils-annotations-js-5318a03.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-js",
        "version": "5318a03"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-js/5318a03/test-utils-annotations-js-5318a03.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-js",
        "version": "5318a03"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-jvm/5318a03/test-utils-annotations-jvm-5318a03.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-jvm",
        "version": "5318a03"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-jvm/5318a03/test-utils-annotations-jvm-5318a03.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-jvm",
        "version": "5318a03"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-linuxx64/5318a03/test-utils-annotations-linuxx64-5318a03.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-linuxx64",
        "version": "5318a03"
      }
    }
  ]
}
