{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/4f11117/test-utils-annotations-junit4-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-iossimulatorarm64-4f11117.klib",
          "size": 11438,
          "sha512": "5700ba1a32678fc80c38f747337de30ce4835055c7169a46ec00940499756eae4190bdb9378de5deb02e77521a13a55900c2cdc615d1a53e28932fd92b9ffc70",
          "sha256": "c839fe2faf3ddf73845d5dcdff0c9c283a6e2bfc9cf05544ff8e35cbc1107a5f",
          "sha1": "1cecf9b278f26825878551578a6ce863a1497ab4",
          "md5": "5a4768817d18ac1138b6e5e9f61ba9cb"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-iossimulatorarm64-4f11117-metadata.jar",
          "url": "test-utils-annotations-junit4-iossimulatorarm64-4f11117-metadata.jar",
          "size": 261,
          "sha512": "a641dbae397ddaa2fba07a4a092efe34a026908194a82f2280f336adf3530a0f25483c18b054dc6d4e17896aa4d97d37e192c47f8784fac6b41bbcf8ccd25c54",
          "sha256": "35b84b3f3c3db01f2e104d6e46e4cf06a32a7d7aa68b3893e0493d2b0c703e0f",
          "sha1": "c252b73f66547b5456aae252d097a84733ec79db",
          "md5": "d6d3fcbe20cf4df33e61136e9fd9c634"
        }
      ]
    }
  ]
}
