{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/cf35c27/test-utils-ktor-cf35c27.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "cf35c27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-cf35c27.klib",
          "url": "test-utils-ktor-js-cf35c27.klib",
          "size": 11895,
          "sha512": "b2d509f02483caa209ccb5a52a3855f4b266b9052f22884108f28e78e980adb7ad2daccf2293fda60fbf701c7140b66fddbb9740fd450485a54b5bdacade327a",
          "sha256": "fd0b28b76a7c978230caa37ce162e88d4401405da9f46a4ae10f25d1c24f8e58",
          "sha1": "445598ff3b52df165fcdb5e4b04a82403f91125c",
          "md5": "654fe416ee7543ba5d970d5cc65d6221"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-cf35c27.klib",
          "url": "test-utils-ktor-js-cf35c27.klib",
          "size": 11895,
          "sha512": "b2d509f02483caa209ccb5a52a3855f4b266b9052f22884108f28e78e980adb7ad2daccf2293fda60fbf701c7140b66fddbb9740fd450485a54b5bdacade327a",
          "sha256": "fd0b28b76a7c978230caa37ce162e88d4401405da9f46a4ae10f25d1c24f8e58",
          "sha1": "445598ff3b52df165fcdb5e4b04a82403f91125c",
          "md5": "654fe416ee7543ba5d970d5cc65d6221"
        }
      ]
    }
  ]
}
