{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "165ee05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-165ee05.jar",
          "url": "antibytes-gradle-test-utils-165ee05.jar",
          "size": 15105,
          "sha512": "8e9a14dc0cda45505877f856cc157b4ec55284869539651617ac552f6bb47ec870fe763790791ff227ad22fd1056a7dd66108063c3c8c0d9a504aa5e43cf9260",
          "sha256": "025281971fa1765ce47e194fb0548e29c2a96e322afc63a04a73cb5463c531de",
          "sha1": "c48cb14c8e260116da4efde39171261a27c8316d",
          "md5": "633db5b3a9fce9a88b9065cbbee2f13d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-165ee05.jar",
          "url": "antibytes-gradle-test-utils-165ee05.jar",
          "size": 15105,
          "sha512": "8e9a14dc0cda45505877f856cc157b4ec55284869539651617ac552f6bb47ec870fe763790791ff227ad22fd1056a7dd66108063c3c8c0d9a504aa5e43cf9260",
          "sha256": "025281971fa1765ce47e194fb0548e29c2a96e322afc63a04a73cb5463c531de",
          "sha1": "c48cb14c8e260116da4efde39171261a27c8316d",
          "md5": "633db5b3a9fce9a88b9065cbbee2f13d"
        }
      ]
    }
  ]
}
