{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/8a321a1/test-utils-annotations-junit5-8a321a1.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "8a321a1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-js-8a321a1.klib",
          "url": "test-utils-annotations-junit5-js-8a321a1.klib",
          "size": 4798,
          "sha512": "fae853fe4dab02e4684d8bdaa1624ae7fdf9703f9d64ee3688549784feae4bb9606a364e7b28c8caad1d071668fa16881de1091fa49b5a8957fb0f54f8dd240a",
          "sha256": "7791b2ed9e91225a9a680ba7db0b8bfde8972eeaf1d1800bf49b3ffa4506733c",
          "sha1": "d80633e3608fa824ccee799d2749233432427285",
          "md5": "f98d7fe231357543b08d4b5b12f99b47"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-js-8a321a1.klib",
          "url": "test-utils-annotations-junit5-js-8a321a1.klib",
          "size": 4798,
          "sha512": "fae853fe4dab02e4684d8bdaa1624ae7fdf9703f9d64ee3688549784feae4bb9606a364e7b28c8caad1d071668fa16881de1091fa49b5a8957fb0f54f8dd240a",
          "sha256": "7791b2ed9e91225a9a680ba7db0b8bfde8972eeaf1d1800bf49b3ffa4506733c",
          "sha1": "d80633e3608fa824ccee799d2749233432427285",
          "md5": "f98d7fe231357543b08d4b5b12f99b47"
        }
      ]
    }
  ]
}
