{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.coverage",
    "module": "antibytes-coverage",
    "version": "5b4a923",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-5b4a923.jar",
          "url": "antibytes-coverage-5b4a923.jar",
          "size": 146046,
          "sha512": "4d1c2dccde727ff127de4ad88f59cb50001d9719cfe698297982715a090916797f0ff355a12b374eef385524071f3732bb3468af2963ad6370cb1700db4a826d",
          "sha256": "f70ee9dd0e17464e516dbe90d7d0da2495e1b9274f411df590744ed93a958591",
          "sha1": "17d881ba2a5e86f2370e7c611d98381db7811c26",
          "md5": "54099d89598072b1f5ace117721fcba8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "5b4a923"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-5b4a923.jar",
          "url": "antibytes-coverage-5b4a923.jar",
          "size": 146046,
          "sha512": "4d1c2dccde727ff127de4ad88f59cb50001d9719cfe698297982715a090916797f0ff355a12b374eef385524071f3732bb3468af2963ad6370cb1700db4a826d",
          "sha256": "f70ee9dd0e17464e516dbe90d7d0da2495e1b9274f411df590744ed93a958591",
          "sha1": "17d881ba2a5e86f2370e7c611d98381db7811c26",
          "md5": "54099d89598072b1f5ace117721fcba8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-coverage-5b4a923-javadoc.jar",
          "url": "antibytes-coverage-5b4a923-javadoc.jar",
          "size": 261,
          "sha512": "9f459a9239a21c7fa7e5ca92dfa5f50d53a660e97f80936f0fa0cc2486b7c7c5be4a40da7eb7a08c1ede921aee7c8ca7815c2076547e1c32ebf8f6c49a1d8827",
          "sha256": "17d1f30e844efec18b8b7f8ab3e2e21f1d5e6e8c85efe195a1c0e467ba30cd5b",
          "sha1": "99fbd7aee35170ba2f4d098ce5da0d0755ecde64",
          "md5": "be26cd8c0b229d5c58ea7f776c502721"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-coverage-5b4a923-sources.jar",
          "url": "antibytes-coverage-5b4a923-sources.jar",
          "size": 27853,
          "sha512": "a9e6194014a3745a9e7f06aecea06807daefec9a58b6729689c0c2b7431bfc6f2699b8f9d531cd8a66d7d345e9e27455deac89380b5c68422302beeeaa934618",
          "sha256": "a7a1a74d6396ec8d342aa8f100a2d4a1434f28de745a3bda2b1a3457bf736cce",
          "sha1": "a3ed03a5405c36d9741c9992182a776633b8d550",
          "md5": "cfb1591385eaa29ff583291623ba066f"
        }
      ]
    }
  ]
}
