{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.kmp.scss",
    "module": "antibytes-scss-configuration",
    "version": "314bef8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-scss-configuration-314bef8.jar",
          "url": "antibytes-scss-configuration-314bef8.jar",
          "size": 3926,
          "sha512": "48bfd33df68598678683faeb19b2dcf9b3c3dd2282e1ed760366c151a33ca2a43f1dd5ae6f122b8bece1a99e055a8f6dbb7ae4747ed8b158b39aff657793ab27",
          "sha256": "516fd14fc8de0fd491519974ee44787dd0be9ca299b9847bb706608976f2f951",
          "sha1": "6bae9f53a216f336340b48ae4599bbcb25e5b4e0",
          "md5": "4f15a878c9e72eb9493e35881ef883ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "314bef8"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-scss-configuration-314bef8.jar",
          "url": "antibytes-scss-configuration-314bef8.jar",
          "size": 3926,
          "sha512": "48bfd33df68598678683faeb19b2dcf9b3c3dd2282e1ed760366c151a33ca2a43f1dd5ae6f122b8bece1a99e055a8f6dbb7ae4747ed8b158b39aff657793ab27",
          "sha256": "516fd14fc8de0fd491519974ee44787dd0be9ca299b9847bb706608976f2f951",
          "sha1": "6bae9f53a216f336340b48ae4599bbcb25e5b4e0",
          "md5": "4f15a878c9e72eb9493e35881ef883ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-scss-configuration-314bef8-javadoc.jar",
          "url": "antibytes-scss-configuration-314bef8-javadoc.jar",
          "size": 261,
          "sha512": "c96d6a02ffd5fff14549e3eb3b648195cb4e4daffcbdba98b01215c94effa8652545c2a8d805468f420718c2d4329ac7c6584b744bf4ca59551b1bbb738fd707",
          "sha256": "cd634ad1e6e607d200a72c0c7c61619cc75b79208cb93c3b7fd662ff42481a95",
          "sha1": "471e095c9c52ee80afc2ec5c2e266ab112d7ca64",
          "md5": "80237730115eb13f549de997e3c75029"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-scss-configuration-314bef8-sources.jar",
          "url": "antibytes-scss-configuration-314bef8-sources.jar",
          "size": 1400,
          "sha512": "95255b17a741fc944fea0380e90501db458f9d5ee8b0d8c3e421c9f551da99f1a1be8af2e4558530d500647fe76313078ed572059036acbaf81fd7b64de33bac",
          "sha256": "1a1f3f89656e550f455264ead207bf3946ce06bb6f2e7624df23e7fd811b3773",
          "sha1": "69bfc38c7dc0d29ed5547d642779d5d396e42583",
          "md5": "c561ae23d52a09a439284122853fe212"
        }
      ]
    }
  ]
}
