{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/8b81c5a/test-utils-fixture-8b81c5a.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "8b81c5a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture.klib",
          "url": "test-utils-fixture-iosx64-8b81c5a.klib",
          "size": 32815,
          "sha512": "4fe06d3c62af18070a7cfa5a583d433e3139001bdfee0634759f2173eef59dbdcfeb92cf73874b43fddc05fe0aba5afdd460e8264c26cc9e6345b80bbb02bb16",
          "sha256": "eb9ece9e15ceac3a88e4f105c9b1fe90c496ca0ccc30b7dbc1c80b9768f44505",
          "sha1": "75389e64bb69be17aca362cd9ffd023a84b76238",
          "md5": "fb8e6af45c8838c679174c6b903aa42f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-iosx64-8b81c5a-metadata.jar",
          "url": "test-utils-fixture-iosx64-8b81c5a-metadata.jar",
          "size": 261,
          "sha512": "78546d344a2fee0cb4e8936cd60191735c8b95c47059b73039ad950801b527a24c85a9e7666f7b3f9d6907abef2825aca9009ade39f8cedf23921ebdfc8d20cd",
          "sha256": "7785ab41dd8353021def501c0b5090ea9deb0060ff0136ec4392f296f6e44917",
          "sha1": "c05bec6be19a6cddb6978267c987bed1e1f6da54",
          "md5": "071e4e171e51a15805f50040399805c7"
        }
      ]
    }
  ]
}
