{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/61a30a2/kmock-61a30a2.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "61a30a2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosx64-61a30a2.klib",
          "size": 113396,
          "sha512": "3d9a932dbe2abee3de89b4010ecc52eb19fdf7b430dfbd7520caa995ca50f059e8a56661c5cb5ec7dd5261556d9ecc61e7bdbe6896b02f6609e1e831f1a3df3a",
          "sha256": "ca57293f2d5bf0c5a67179e43cf9d5ea31d96005bc5a62b34bd3610bba425e6c",
          "sha1": "5f6033285903f9f44f34e32cf767d48ccbac9634",
          "md5": "2e34caed96673f322ae62e6d7f4f0b3a"
        }
      ]
    }
  ]
}
