{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/c560d77/kmock-c560d77.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "c560d77",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "c3e5acf"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosx64-c560d77.klib",
          "size": 99707,
          "sha512": "fe4498a7676c0081df474deb9aec8c79ff05c914c7b0d4ed079373379acb2b722d56f6f3d8f705dc52bced775aa632ca53d4ddfc96af58441b84a7a708b014dd",
          "sha256": "4fecc2433b5480e4d00ce9a77f87cf0b1dbf380a265dd4d3a6cb5e1d3f8eb054",
          "sha1": "260503fc2271ab0b38da6f22cb68495342bece39",
          "md5": "30e5e41a92ef92afc9897eef73f7b6b8"
        }
      ]
    }
  ]
}
