{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/20cf1ce/kmock-20cf1ce.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "20cf1ce",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosx64-20cf1ce.klib",
          "size": 104577,
          "sha512": "2276fa8f1511829b56ffde15b0a73f68228f4ea19f51a1c459a452a2bb7c2e1dea8642e89d7193db2b0947e24a38714c9473476ba50d6e4d67e15c51d042a947",
          "sha256": "a7c04e7668cf73fe78bc612483b94ab460c480f108f5e0ea73739670a8423508",
          "sha1": "96735e5091beec3756cd6ec2f08d581315ecc6e2",
          "md5": "802cdbe9258f0a125e6254323ada869e"
        }
      ]
    }
  ]
}
