{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-78602a6661-SNAPSHOT/kmock-0.1.1-78602a6661-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-78602a6661-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-linuxx64-0.1.1-78602a6661-SNAPSHOT.klib",
          "size": 196497,
          "sha512": "e09cb402a5783e86f0f703ebc835508d1ff969a4ae7f2957efc31671082d2448421849b91eec38fbc8eeee900220dc0c49ce00afd9f2b751d3af35ae1b6b3473",
          "sha256": "dcadbad4bac00da7826066c7775144dd6c00c57d1ef950c8d853917c92d5d685",
          "sha1": "67f44d7534b02d783b40234cbb653081f942a7cf",
          "md5": "00046a20979978ea07210ee13f3133fd"
        }
      ]
    }
  ]
}
