{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/efff651/test-utils-coroutine-efff651.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "efff651",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosx64-efff651.klib",
          "size": 10107,
          "sha512": "106e50c2ef08425a51366534db2fb184b8ac4ef80f087fff01f6c2bb9cd2d020f7cc88df0359720da4f6d13259325286574fe557c0285f1eacd22df07164453e",
          "sha256": "fa5c2d721e6cd6f1c9611f16760b87b2629af2a04419266852a2b68a97db350a",
          "sha1": "13e7453d88d68c5b8f25d07228ba0e1f8c6864cd",
          "md5": "c147117cb33e9beb33ed14f8ef84ead8"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosx64-efff651-metadata.jar",
          "url": "test-utils-coroutine-iosx64-efff651-metadata.jar",
          "size": 261,
          "sha512": "18d5057e70098538e6350154b1140e7bc9679aa37eeac1dde9fb18615636296eb77cf9a79e90e5f70b846366bb018e887afe97567d043d967d0709899977385d",
          "sha256": "db01e04085f433cd482dc81a4939c97caa87df841e88d5c5e56637dc3515866d",
          "sha1": "31c43e1c6495e3f8031d910652c930b228e830fe",
          "md5": "570b8b7281a87aebbacebcccbfbdc025"
        }
      ]
    }
  ]
}
