{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "8686647",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-8686647.jar",
          "url": "antibytes-grammar-tools-8686647.jar",
          "size": 39371,
          "sha512": "7885e9a44e2efa9472f024d8d9b9309cd1be05d74953d2ddf1c4620271217f570be89165c28e2e349eb0c5901045fbfbc9c00b4fabdfe98f8fd0793185ecffea",
          "sha256": "08308191a8d440e0309604b78707f69440f5d0cc4a89091204d9623b5280caf7",
          "sha1": "9097841595e163af2e8595b757bc53a670ffc851",
          "md5": "c6472414272a8769b56786840fe69311"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-8686647.jar",
          "url": "antibytes-grammar-tools-8686647.jar",
          "size": 39371,
          "sha512": "7885e9a44e2efa9472f024d8d9b9309cd1be05d74953d2ddf1c4620271217f570be89165c28e2e349eb0c5901045fbfbc9c00b4fabdfe98f8fd0793185ecffea",
          "sha256": "08308191a8d440e0309604b78707f69440f5d0cc4a89091204d9623b5280caf7",
          "sha1": "9097841595e163af2e8595b757bc53a670ffc851",
          "md5": "c6472414272a8769b56786840fe69311"
        }
      ]
    }
  ]
}
