{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc05-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-metadata-0.3.0-rc05-SNAPSHOT-all.jar",
          "url": "kmock-0.3.0-rc05-SNAPSHOT-all.jar",
          "size": 28226,
          "sha512": "72dd009f92da7783fb9e7029c5d98ef565e5b1003c1e18d97f67ac50f753db3961eca3d1aafcdb101d6ef771e811c995c3ecc7fd60734ae9ef286b355f67212a",
          "sha256": "6cc15409da7c3c2e2cad61ddbc40e3212827e53d6bd1c9ea155e4579cdac062a",
          "sha1": "b810756717b333f44019bb50e68a258d0a677415",
          "md5": "05e400f4564b59b77a939e9c229a699a"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-0.3.0-rc05-SNAPSHOT.jar",
          "url": "kmock-0.3.0-rc05-SNAPSHOT.jar",
          "size": 47917,
          "sha512": "9b826c89531ee02d4055270eea97abc54f22bb4e0f7484114b6f4c5a0ac0fec621359560ea74aa8a3fe006ee517384560c9a676f19e8f982daf3447d22978eca",
          "sha256": "c9b3404e064f86fd94809af8397b811b6a606095c42f5ebb2771444beb1de96d",
          "sha1": "446c7b1b59da50bfcd4fde6772a793905b8368fe",
          "md5": "22777f044d4c6ef86d6b3e760cdc5744"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.3.0-rc05-SNAPSHOT/kmock-android-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.3.0-rc05-SNAPSHOT/kmock-android-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm32/0.3.0-rc05-SNAPSHOT/kmock-iosarm32-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm32",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm32/0.3.0-rc05-SNAPSHOT/kmock-iosarm32-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm32",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/0.3.0-rc05-SNAPSHOT/kmock-iosarm64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/0.3.0-rc05-SNAPSHOT/kmock-iosarm64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iossimulatorarm64/0.3.0-rc05-SNAPSHOT/kmock-iossimulatorarm64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iossimulatorarm64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iossimulatorarm64/0.3.0-rc05-SNAPSHOT/kmock-iossimulatorarm64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iossimulatorarm64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/0.3.0-rc05-SNAPSHOT/kmock-iosx64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/0.3.0-rc05-SNAPSHOT/kmock-iosx64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.3.0-rc05-SNAPSHOT/kmock-js-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.3.0-rc05-SNAPSHOT/kmock-js-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.3.0-rc05-SNAPSHOT/kmock-jvm-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.3.0-rc05-SNAPSHOT/kmock-jvm-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/0.3.0-rc05-SNAPSHOT/kmock-linuxx64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-macosarm64/0.3.0-rc05-SNAPSHOT/kmock-macosarm64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-macosarm64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-macosarm64/0.3.0-rc05-SNAPSHOT/kmock-macosarm64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-macosarm64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-macosx64/0.3.0-rc05-SNAPSHOT/kmock-macosx64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-macosx64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-macosx64/0.3.0-rc05-SNAPSHOT/kmock-macosx64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-macosx64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-mingwx64/0.3.0-rc05-SNAPSHOT/kmock-mingwx64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-mingwx64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvosarm64/0.3.0-rc05-SNAPSHOT/kmock-tvosarm64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvosarm64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvosarm64/0.3.0-rc05-SNAPSHOT/kmock-tvosarm64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvosarm64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvossimulatorarm64/0.3.0-rc05-SNAPSHOT/kmock-tvossimulatorarm64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvossimulatorarm64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvossimulatorarm64/0.3.0-rc05-SNAPSHOT/kmock-tvossimulatorarm64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvossimulatorarm64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvosx64/0.3.0-rc05-SNAPSHOT/kmock-tvosx64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvosx64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvosx64/0.3.0-rc05-SNAPSHOT/kmock-tvosx64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvosx64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosarm32/0.3.0-rc05-SNAPSHOT/kmock-watchosarm32-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosarm32",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosarm32/0.3.0-rc05-SNAPSHOT/kmock-watchosarm32-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosarm32",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosarm64/0.3.0-rc05-SNAPSHOT/kmock-watchosarm64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosarm64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosarm64/0.3.0-rc05-SNAPSHOT/kmock-watchosarm64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosarm64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchossimulatorarm64/0.3.0-rc05-SNAPSHOT/kmock-watchossimulatorarm64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchossimulatorarm64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchossimulatorarm64/0.3.0-rc05-SNAPSHOT/kmock-watchossimulatorarm64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchossimulatorarm64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosx64/0.3.0-rc05-SNAPSHOT/kmock-watchosx64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosx64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosx64/0.3.0-rc05-SNAPSHOT/kmock-watchosx64-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosx64",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosx86/0.3.0-rc05-SNAPSHOT/kmock-watchosx86-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosx86",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosx86/0.3.0-rc05-SNAPSHOT/kmock-watchosx86-0.3.0-rc05-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosx86",
        "version": "0.3.0-rc05-SNAPSHOT"
      }
    }
  ]
}
