{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/e99bb93/test-utils-fixture-e99bb93.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "e99bb93",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture.klib",
          "url": "test-utils-fixture-iossimulatorarm64-e99bb93.klib",
          "size": 32918,
          "sha512": "3e557e885027620afce093f076377386c7b8588d38d140318f18f7dba2c90987b2771852138e7cd4568e79bd03a1198a1efc767293fc6143cadee87b6a0790c0",
          "sha256": "5f9c1e22f4a3c9f25c1bd9c49ee2da85877ec0ca67b4452e23f47aef1017f8ea",
          "sha1": "55d973f80887696e2131c619dfb570966d0aefd2",
          "md5": "542f9e009650b31c2b3c264baa8b5246"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-iossimulatorarm64-e99bb93-metadata.jar",
          "url": "test-utils-fixture-iossimulatorarm64-e99bb93-metadata.jar",
          "size": 261,
          "sha512": "3f5545195cb40b6d419fa34334ee3d22a25b09c40d7086f05fdfa6c0b74d2b2bf44d3a3e308d35cdb7769bc4c1f7acf0dda2da015a65b8f6662a02023a581b09",
          "sha256": "bce846ea39e24f2bbf5a67c469e735baacaba8a70c875c711773958ae83d1ab0",
          "sha1": "d9275e43b93b7d7bbc9bf1bf02bb73c93a6925f5",
          "md5": "05db540907a258e98c4edbc454e14c21"
        }
      ]
    }
  ]
}
