{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "9e2ffe9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "9e2ffe9"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-9e2ffe9.jar",
          "url": "antibytes-publishing-9e2ffe9.jar",
          "size": 117663,
          "sha512": "2d842f81c6ff2cee5d9af0f42a70b2d35d87a8996eae24e1a5ed0b27931e1260585743aa51c261205b6bd8bfc1111f1cba7c86cad4f1ab3c098733275c9e662d",
          "sha256": "1ddf13699892b6fd6971ce36c380570a754f744378f6965b5e73a086758d5311",
          "sha1": "480c5130cccd32506ab32f5654ae4607934a67b3",
          "md5": "c819912ad964298cf46416b20bf45974"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.3.0.202209071007-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "9e2ffe9"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "9e2ffe9"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-9e2ffe9.jar",
          "url": "antibytes-publishing-9e2ffe9.jar",
          "size": 117663,
          "sha512": "2d842f81c6ff2cee5d9af0f42a70b2d35d87a8996eae24e1a5ed0b27931e1260585743aa51c261205b6bd8bfc1111f1cba7c86cad4f1ab3c098733275c9e662d",
          "sha256": "1ddf13699892b6fd6971ce36c380570a754f744378f6965b5e73a086758d5311",
          "sha1": "480c5130cccd32506ab32f5654ae4607934a67b3",
          "md5": "c819912ad964298cf46416b20bf45974"
        }
      ]
    }
  ]
}
