{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-versioning",
    "version": "fca89fa",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-fca89fa.jar",
          "url": "antibytes-versioning-fca89fa.jar",
          "size": 16027,
          "sha512": "21838f7f6659920c8ced3f82dd220a0aa1d340b7830fa2be298cf0a4bbe1fed8d93c1391a66ca9fdd91a061e100d54aa1457e90f1d2b14658d146e357e29cd7f",
          "sha256": "7bb78b86d688564b6967f65ea07f57d50694bd578c43bd7b9b55e31713bdcdbd",
          "sha1": "41d2e88bc4dc0e19fbfd140fc181583664deb785",
          "md5": "646214e30177661aa56189b26f8521df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-fca89fa.jar",
          "url": "antibytes-versioning-fca89fa.jar",
          "size": 16027,
          "sha512": "21838f7f6659920c8ced3f82dd220a0aa1d340b7830fa2be298cf0a4bbe1fed8d93c1391a66ca9fdd91a061e100d54aa1457e90f1d2b14658d146e357e29cd7f",
          "sha256": "7bb78b86d688564b6967f65ea07f57d50694bd578c43bd7b9b55e31713bdcdbd",
          "sha1": "41d2e88bc4dc0e19fbfd140fc181583664deb785",
          "md5": "646214e30177661aa56189b26f8521df"
        }
      ]
    }
  ]
}
