{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/f7c1da7/test-utils-annotations-f7c1da7.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "f7c1da7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-iosarm64-f7c1da7.klib",
          "size": 11334,
          "sha512": "6af6cbd9eff8184c553b5cec5f703b6616fb50a5a30ed48fe004e17491b3fd6de014821615af26a44897bfcca46085629a3e4d65b3e3d57f62f2041aa6803830",
          "sha256": "2fe3461e8b110c9fbc4f0af49ff00046b9e2b94b085f8d68461a2cdf5c53cb49",
          "sha1": "7fb6dc5db6305619a7fe527055e8cbab8b5103b2",
          "md5": "4e432e4026f3051b27c0faa0f057466c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-iosarm64-f7c1da7-metadata.jar",
          "url": "test-utils-annotations-iosarm64-f7c1da7-metadata.jar",
          "size": 261,
          "sha512": "b2e7bee7c66fe205e192d93ec09d87e7156da0fe729401f47b0216e75a2374d0e7b789ad003c12dc45e9c0f9215e8874c460801d4e5938be08c67aca3d689de9",
          "sha256": "73fbbbe797278127b503532e557d8ce02cfd2f2fdda275d5a56be03f12963263",
          "sha1": "9acc2e52314c2957f0d591eca86f66eb50c36fd4",
          "md5": "6577ff29bc568d7b4db0a10e7fe05fd0"
        }
      ]
    }
  ]
}
