{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "3a72bda",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-3a72bda.jar",
          "url": "antibytes-gradle-utils-3a72bda.jar",
          "size": 9568,
          "sha512": "d18e7ab74ab0a7be3504c9d65994a6728f01d0be91c883e701abc835afad3c649d213789adb047efcd6d4c7ec017c444d605cf32bcefa0873fe08966e1ea4672",
          "sha256": "c85a151e65d3e45425dd26479526b63464abc2ffa16eb0a9c854061e0030e579",
          "sha1": "7f5c2aef364f84306c5b9574fa77ecfd35683d16",
          "md5": "a1ee446ea56b9fd340b6b6a23688ec8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-3a72bda.jar",
          "url": "antibytes-gradle-utils-3a72bda.jar",
          "size": 9568,
          "sha512": "d18e7ab74ab0a7be3504c9d65994a6728f01d0be91c883e701abc835afad3c649d213789adb047efcd6d4c7ec017c444d605cf32bcefa0873fe08966e1ea4672",
          "sha256": "c85a151e65d3e45425dd26479526b63464abc2ffa16eb0a9c854061e0030e579",
          "sha1": "7f5c2aef364f84306c5b9574fa77ecfd35683d16",
          "md5": "a1ee446ea56b9fd340b6b6a23688ec8b"
        }
      ]
    }
  ]
}
