{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc05-SNAPSHOT/kmock-0.3.0-rc05-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc05-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iossimulatorarm64-0.3.0-rc05-SNAPSHOT.klib",
          "size": 202582,
          "sha512": "5a29bb4688f1136d451406b2eefd19dd88123a737d4b27c4b9dbc3fbc4d09d9eefe0ce490a7e34af9b7109055d56a2fdc6b0c8e969b3733e2d8454aa2a52ba91",
          "sha256": "78d3245c443c5470f125a9a92363f50bdb45a1e28eafbde12141b30d49c8cc27",
          "sha1": "b39735cd4c103ca6e73b0f70f494f56b518983ff",
          "md5": "6ff1309eaa9ad9f7e525950fc0334b4d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iossimulatorarm64-0.3.0-rc05-SNAPSHOT-metadata.jar",
          "url": "kmock-iossimulatorarm64-0.3.0-rc05-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "28d5a077213844543555dd892fbb3f995eb758b33eba93f15a4aaf71a58e24663cbddef91d80019c1d85bd92b34e856f67944956cea9f84ca248170b213deb01",
          "sha256": "9bb7553445b5e44eb4249ed9824196db5f3b286ce518bd86ec4d4efaa47fa4ca",
          "sha1": "3ae3edec1facbe1932ed01199e8628b942e9f9f0",
          "md5": "1d473c2409aafee1d014a3e2eb0329ea"
        }
      ]
    }
  ]
}
