{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/4f11117/test-utils-resourceloader-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iosarm64-4f11117.klib",
          "size": 12865,
          "sha512": "d4354a16ff4e7f671a885afb5bd50aa493618e58eb624522b6443a3e88c75c55809c4c7926e37e528f7ee3db77798347c8dfa0f0dfe19972f3324d577ca388db",
          "sha256": "34d19a0a80dbb12e2b11109e11dc0627ee8514043a2e6e69b536b6dfd94e211a",
          "sha1": "52b6a8fdf6b799f09150e4e5169200bdd7f836c4",
          "md5": "bf93c70f016dce7067f84b5922b6e864"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iosarm64-4f11117-metadata.jar",
          "url": "test-utils-resourceloader-iosarm64-4f11117-metadata.jar",
          "size": 261,
          "sha512": "f3924f8cd67d9bffc1450e277f2858d7e394bb1d8bf7c7dbae6d9a9781dbecfd6c6a5d04f3fc57b04131be31556e401e3623109097cdd862dda598f0d54fafb3",
          "sha256": "8996606064c10a47be27442460a1492f172cd5327d5e3d7642c017a08837ed88",
          "sha1": "17f9fe6bc2a1a72b22da15ef815b5def881d9368",
          "md5": "121a23bc92450b391ae72831f86cb3d3"
        }
      ]
    }
  ]
}
