{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/b6c6e6c/test-utils-b6c6e6c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "b6c6e6c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-watchosarm64-b6c6e6c.klib",
          "size": 8378,
          "sha512": "068b9292ca77daf68e4bd6a86d4a89204c29bdc6291dc7b5d0f6a433a6214ffb31c56de98b53ed503a82adae926a4d57a724e43d835d417106dc808fe2c190b6",
          "sha256": "0e73eaac45ff3d94961d38c974b6b686ea6e1a70118e30d0317d66655cec1cc0",
          "sha1": "bbe469d0cbd0c97c341c932b4609a6fdccd3963c",
          "md5": "464d5a038a504ffbd83b878deadbc1ea"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-watchosarm64-b6c6e6c-sources.jar",
          "url": "test-utils-watchosarm64-b6c6e6c-sources.jar",
          "size": 2202,
          "sha512": "200f256b59ba175210138bed146ee54ab58c9bb91f071774698eb6b3f4920f792214d2d44a1cc764422cb2c09da1a0773d4d288080e067e60263b96f2ed68050",
          "sha256": "9e0bd104bc203c511c12aaf2143514ee32a59c775ece92a04e7ee764ee60affa",
          "sha1": "773bcb344a1f6fd820f6ee6e62aea2b59ecfa180",
          "md5": "8b3c7f259a640a3d1e2ffd34b7f29645"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-watchosarm64-b6c6e6c-metadata.jar",
          "url": "test-utils-watchosarm64-b6c6e6c-metadata.jar",
          "size": 261,
          "sha512": "054336d9c9321ec0c6531af9b58651baa3624d38e112471c36731f8a44e54e75fdebb0ae013c16d43118cad20be731e1f4ef12de1097012b409666e2d82e6c26",
          "sha256": "adf995298a2610438227ec3029196b0fdf37ca8a19e8b13f1d2dacab12428eb9",
          "sha1": "e1f6415989aa2eae5fe19d639aa9d597d8243217",
          "md5": "86fae3971724738b799d8db9c28e9608"
        }
      ]
    }
  ]
}
