{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-runtime-configuration",
    "version": "7253e2e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-7253e2e.jar",
          "url": "antibytes-runtime-configuration-7253e2e.jar",
          "size": 10349,
          "sha512": "1585501bab933397cff23fceb76347468a16316a2f74931dc9ac5060f97062e6012b0cde9a679a19ea5cd952fa246b39d9030d62dcebe52bc8aaa82053a9c9b3",
          "sha256": "587aaf792c64bf5900f455048fa0ee5f74c679625309fef9f4767c11dd0fd3a0",
          "sha1": "d1094ed05ee3ae428aead644159f0f05638512ab",
          "md5": "8438feb21b02af885a3d00d0dc65b228"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "7253e2e"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-7253e2e.jar",
          "url": "antibytes-runtime-configuration-7253e2e.jar",
          "size": 10349,
          "sha512": "1585501bab933397cff23fceb76347468a16316a2f74931dc9ac5060f97062e6012b0cde9a679a19ea5cd952fa246b39d9030d62dcebe52bc8aaa82053a9c9b3",
          "sha256": "587aaf792c64bf5900f455048fa0ee5f74c679625309fef9f4767c11dd0fd3a0",
          "sha1": "d1094ed05ee3ae428aead644159f0f05638512ab",
          "md5": "8438feb21b02af885a3d00d0dc65b228"
        }
      ]
    }
  ]
}
