{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/86ec4d6/test-utils-annotations-junit5-86ec4d6.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "86ec4d6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-androidnativex64-86ec4d6.klib",
          "size": 7094,
          "sha512": "951686ae2a51092d82d6736381d20bc8c4699a3312a2eba5ed0dd925ac861d6af4ccb4cf9be698589a962563d05668eeb10a387c8357e2b485ef2be153613650",
          "sha256": "7cba48790287457e05625bd8f7927366d4027ee4ea1241e6b8709a462b9f32ba",
          "sha1": "17ab18d1bffbe93b8d363a238b7357d35c7a6a82",
          "md5": "550670dad779e5b29ad9f25d0491d23b"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-annotations-junit5-androidnativex64-86ec4d6-sources.jar",
          "url": "test-utils-annotations-junit5-androidnativex64-86ec4d6-sources.jar",
          "size": 3477,
          "sha512": "8910488f2acc4f4c669bf3e6a74835e60ede75d2286f44304a32d7435e9374f50e400ec91ccdc9fcab868fe57ac79f9cc99c5183a87396417d48b059ee008e7f",
          "sha256": "9f2d1a8fe1210ea25bd9b54214171ccdd8f68d07f8c4c7bf4fdaa277b2d059e9",
          "sha1": "c0915589af235519923fb41575cb1d6e37f9dedf",
          "md5": "b993ac9b3bda4583966bb9266ec6da60"
        }
      ]
    }
  ]
}
