{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01-SNAPSHOT/kmock-0.3.0-rc01-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc01-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc01-SNAPSHOT.klib",
          "size": 216790,
          "sha512": "d0dc39abad534973a5340989a3d5ef24202be941f8024f1aacfef4a5583dc8a8d70f1a1d19aea8501d3faec3dfcc75611eacea2351acdd9281324c71a7127e27",
          "sha256": "6ea43367909d2579279e15035235e6021d2407c12ec54140cbf2647101eb01b3",
          "sha1": "68ffcb90410122b473c0b055ae96bd05755e5ee1",
          "md5": "95751c0050d72f822b956a7b615757dc"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc01-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc01-SNAPSHOT.klib",
          "size": 216790,
          "sha512": "d0dc39abad534973a5340989a3d5ef24202be941f8024f1aacfef4a5583dc8a8d70f1a1d19aea8501d3faec3dfcc75611eacea2351acdd9281324c71a7127e27",
          "sha256": "6ea43367909d2579279e15035235e6021d2407c12ec54140cbf2647101eb01b3",
          "sha1": "68ffcb90410122b473c0b055ae96bd05755e5ee1",
          "md5": "95751c0050d72f822b956a7b615757dc"
        }
      ]
    }
  ]
}
