{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "54a39ff",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-54a39ff.jar",
          "url": "kmock-processor-54a39ff.jar",
          "size": 96199,
          "sha512": "67e7b3244eeda897f52e6ac3ba5ddd897f03a8a3adc3b20f631c0658d8f65b9e4599232ef12f4df5daf38b3da59e660b5af465ea5edab2984d57870bb7eb977c",
          "sha256": "702ef448e1fde79cf0b93a09cbf6fd34b1aaade6ee37a75e3f8fdfe5aedd572a",
          "sha1": "f8be03423965d11bd42ff9dff99e15983e3dcc77",
          "md5": "0754ad765984c85a36cd6a90b060bdeb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "54a39ff"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-54a39ff.jar",
          "url": "kmock-processor-54a39ff.jar",
          "size": 96199,
          "sha512": "67e7b3244eeda897f52e6ac3ba5ddd897f03a8a3adc3b20f631c0658d8f65b9e4599232ef12f4df5daf38b3da59e660b5af465ea5edab2984d57870bb7eb977c",
          "sha256": "702ef448e1fde79cf0b93a09cbf6fd34b1aaade6ee37a75e3f8fdfe5aedd572a",
          "sha1": "f8be03423965d11bd42ff9dff99e15983e3dcc77",
          "md5": "0754ad765984c85a36cd6a90b060bdeb"
        }
      ]
    }
  ]
}
