{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/6c316c5/test-utils-annotations-6c316c5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "6c316c5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-6c316c5.klib",
          "url": "test-utils-annotations-js-6c316c5.klib",
          "size": 9731,
          "sha512": "04e2af7e53794d4f73c7825260a05bb5f5af6669edd6d9b4105a753bdec69ef0724ee2b2b3dc82ae312ad54194ace89e99efb8247f826f6dd12a7aaf96158c85",
          "sha256": "64024315ae607e6d0ba13fc90af82dd2b38915052738314e2e6b651af8489d77",
          "sha1": "a3ecfe6cce6d00bf3831b187c854b068ed8be20d",
          "md5": "3b76488ed0e9317aba7de4a484c42d20"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-6c316c5.klib",
          "url": "test-utils-annotations-js-6c316c5.klib",
          "size": 9731,
          "sha512": "04e2af7e53794d4f73c7825260a05bb5f5af6669edd6d9b4105a753bdec69ef0724ee2b2b3dc82ae312ad54194ace89e99efb8247f826f6dd12a7aaf96158c85",
          "sha256": "64024315ae607e6d0ba13fc90af82dd2b38915052738314e2e6b651af8489d77",
          "sha1": "a3ecfe6cce6d00bf3831b187c854b068ed8be20d",
          "md5": "3b76488ed0e9317aba7de4a484c42d20"
        }
      ]
    }
  ]
}
