{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/c3e5acf/test-utils-coroutine-c3e5acf.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "c3e5acf",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-c3e5acf.klib",
          "url": "test-utils-coroutine-js-c3e5acf.klib",
          "size": 10133,
          "sha512": "6c149f0380c5eeacd2cc6e8d1b0aac8f43bd141acd885ac86b7d714281aa45ac0a54386f5d760c2657fe71a2a1da75919f789a698926e164a6d3a66f01546df6",
          "sha256": "63405c813fbbc9959e71fa23df670e9d6c6dcc5b3021b84b230a4c493c45a682",
          "sha1": "605a575eba2665084124e24ca68326be6cd19f3d",
          "md5": "cb58e13dfe3296dc963c6acc1636e9fb"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-c3e5acf.klib",
          "url": "test-utils-coroutine-js-c3e5acf.klib",
          "size": 10133,
          "sha512": "6c149f0380c5eeacd2cc6e8d1b0aac8f43bd141acd885ac86b7d714281aa45ac0a54386f5d760c2657fe71a2a1da75919f789a698926e164a6d3a66f01546df6",
          "sha256": "63405c813fbbc9959e71fa23df670e9d6c6dcc5b3021b84b230a4c493c45a682",
          "sha1": "605a575eba2665084124e24ca68326be6cd19f3d",
          "md5": "cb58e13dfe3296dc963c6acc1636e9fb"
        }
      ]
    }
  ]
}
