{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/6aed143/kmock-6aed143.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "6aed143",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-6aed143.klib",
          "url": "kmock-js-6aed143.klib",
          "size": 126181,
          "sha512": "09c5e5f640838a8570d59519c2fde21a7f8539f838a2b02efa52ea97cd3d9ba25a6f6f4bcc215f5fb86e3c6296458a662dca86f02660c8315c0c8873eeedd507",
          "sha256": "14932e320b114cb517d5f73d0094149cb80c26d90996f6748ad6ae2d26864ced",
          "sha1": "8970f3624d7c94995ba8e037d9ab8c8e9f7a5de8",
          "md5": "6aa42305833ea43c76263e286586f964"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-6aed143.klib",
          "url": "kmock-js-6aed143.klib",
          "size": 126181,
          "sha512": "09c5e5f640838a8570d59519c2fde21a7f8539f838a2b02efa52ea97cd3d9ba25a6f6f4bcc215f5fb86e3c6296458a662dca86f02660c8315c0c8873eeedd507",
          "sha256": "14932e320b114cb517d5f73d0094149cb80c26d90996f6748ad6ae2d26864ced",
          "sha1": "8970f3624d7c94995ba8e037d9ab8c8e9f7a5de8",
          "md5": "6aa42305833ea43c76263e286586f964"
        }
      ]
    }
  ]
}
