{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "89ba0c4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "89ba0c4"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-89ba0c4.jar",
          "url": "antibytes-mkdocs-89ba0c4.jar",
          "size": 11936,
          "sha512": "1823c0c2ddffeac4b95ec45d4ec739f0426d5ef927a77fc1ddca606bd7b3db210a6b8344f50418611ee22f70c208235fb99555f6f098cc69985aa72ced4fe23f",
          "sha256": "862a6ad8efb6a90b3c5f591efaf2dd918404d1782fcaa8bf5224b22faa187dac",
          "sha1": "577930d11ec8344dfb242047f2b1f29cb956c596",
          "md5": "04dff38c7b9d9955f818fbefe8ee95de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "89ba0c4"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "89ba0c4"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-89ba0c4.jar",
          "url": "antibytes-mkdocs-89ba0c4.jar",
          "size": 11936,
          "sha512": "1823c0c2ddffeac4b95ec45d4ec739f0426d5ef927a77fc1ddca606bd7b3db210a6b8344f50418611ee22f70c208235fb99555f6f098cc69985aa72ced4fe23f",
          "sha256": "862a6ad8efb6a90b3c5f591efaf2dd918404d1782fcaa8bf5224b22faa187dac",
          "sha1": "577930d11ec8344dfb242047f2b1f29cb956c596",
          "md5": "04dff38c7b9d9955f818fbefe8ee95de"
        }
      ]
    }
  ]
}
