{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "d273191",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "d273191"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-d273191.jar",
          "url": "antibytes-publishing-d273191.jar",
          "size": 117663,
          "sha512": "28e551256248964261a16b1ea6412e2412717cdcc0479b9ea8c0a0bdbddf321a7769dd7eda0e2c0808c20ef84d7af7d95c6f45f4045b455826b55ff4c74656dd",
          "sha256": "4a5bd59cf73a5e023e3b5ce6bc29af5ac1b5910da0357af654dbd01f0fdb744e",
          "sha1": "069a10469b3792bcd20ab700d45ab90e81b22093",
          "md5": "24dda5cffa373f063e2fd411da56f340"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.2.0.202206071550-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "d273191"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "d273191"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-d273191.jar",
          "url": "antibytes-publishing-d273191.jar",
          "size": 117663,
          "sha512": "28e551256248964261a16b1ea6412e2412717cdcc0479b9ea8c0a0bdbddf321a7769dd7eda0e2c0808c20ef84d7af7d95c6f45f4045b455826b55ff4c74656dd",
          "sha256": "4a5bd59cf73a5e023e3b5ce6bc29af5ac1b5910da0357af654dbd01f0fdb744e",
          "sha1": "069a10469b3792bcd20ab700d45ab90e81b22093",
          "md5": "24dda5cffa373f063e2fd411da56f340"
        }
      ]
    }
  ]
}
