{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "384f364",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-384f364.toml",
          "url": "antibytes-dependency-catalog-384f364.toml",
          "size": 250839,
          "sha512": "484ab8a095c420952ab4dcefd68320e3fed684fe8b9c62a31209e1d7da9f32bf066bf1a5b8bd3e5794320b5c2acb592f1f4f71db0b138eba4c11378d05dd58a1",
          "sha256": "15dc8d6639ed6364ab47f7f906c290589c5167cdce1dec82858d1e67cd02b616",
          "sha1": "ce1ba787d8689d6335080066b38d47412bb06ed3",
          "md5": "8d2269af656b2fc3fed6bc9a019e3df6"
        }
      ]
    }
  ]
}
