{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/dd59a45/test-utils-annotations-dd59a45.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "dd59a45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-iosarm64-dd59a45.klib",
          "size": 11206,
          "sha512": "e9562f03031aa7abee62526f5e739b1858744318b7efbf5e7291e9ae6fa548f953dc83631f1e7dbb0a8bc51fc6252f005a9113601c9698bf609c353c22bce330",
          "sha256": "a5fe8090f5933950ba1733d903ced5a0e277e0cb636ddc304a31159801997823",
          "sha1": "686b666520a4650ae31c0da052e2521774140e78",
          "md5": "a2a22e79f2cafc4d4cbfbde1687a94dc"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-iosarm64-dd59a45-metadata.jar",
          "url": "test-utils-annotations-iosarm64-dd59a45-metadata.jar",
          "size": 261,
          "sha512": "c6a6d906102da15805ae2b543768a1093c79d7905a8b4a7ff7bebf6ab944c43b183f536945b45c94b5816745a5cf4bfc4fd646ad16e675f20cac0a08340eac5f",
          "sha256": "da9c2dbb5270f8993ec03e4c89f1861dbf18c31c5e44f944c91ce42a4f65b08b",
          "sha1": "49360c1b15b06cc597d5322f12a860a91da7ba90",
          "md5": "1fd4fa4a8f1467d65f27d94bc311b77c"
        }
      ]
    }
  ]
}
