{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "11324f8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-11324f8.toml",
          "url": "antibytes-dependency-catalog-11324f8.toml",
          "size": 249942,
          "sha512": "72f958a993068dba14655f73e1e3ce06cd591ceb83ce8f0490db6aef9180ec912f32b84a63d20486a85302041443475fdb3ed08e5313578eb61881113b0ef059",
          "sha256": "bfc4c59a3947df366d9a8763bb9860541aca643a7057ea67525b1220ad50054e",
          "sha1": "e73e2b5062e452c535c052d47736d9eb51c13db0",
          "md5": "6bb09a88aefd639b4fc86f57bd7b6361"
        }
      ]
    }
  ]
}
