{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01-SNAPSHOT/kmock-0.3.0-rc01-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "76ddd8f8a809180362dd02224ad5c3a1a821feafd758363ae576ba35a0037e184c97fe41c408abd8cc096f92a394fc37fc00b298c8ce3c541f88df23f2b83795",
          "sha256": "bf9daa89e8ef9cd1694d7ccfc761db0b2e072d637d66f0d2addf110d181bde9e",
          "sha1": "69107d6ef3ee9eea7771646f303b979a39f5b2e8",
          "md5": "b0226cd515de0459c9563a54f0e6264b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "76ddd8f8a809180362dd02224ad5c3a1a821feafd758363ae576ba35a0037e184c97fe41c408abd8cc096f92a394fc37fc00b298c8ce3c541f88df23f2b83795",
          "sha256": "bf9daa89e8ef9cd1694d7ccfc761db0b2e072d637d66f0d2addf110d181bde9e",
          "sha1": "69107d6ef3ee9eea7771646f303b979a39f5b2e8",
          "md5": "b0226cd515de0459c9563a54f0e6264b"
        }
      ]
    }
  ]
}
