{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/ef4b232/kmock-ef4b232.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "ef4b232",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-ef4b232.jar",
          "url": "kmock-jvm-ef4b232.jar",
          "size": 264329,
          "sha512": "5b168d0318a51d62fe768d3f59273ea5e5e5d361da77507edcee3ef4e495301ffe5f2e59f1cee62d2c8e612c6c97ec74ef4116661bbf736d96fe3711f0919bdc",
          "sha256": "7ffb4abce2d7f93be758bb209fb82725fee1b01f9fbb8978305c3276c1b59b51",
          "sha1": "9286ecb7462da573f7fbdee97cde8ee4a585a46a",
          "md5": "60ac04953fba3bb6eab272228b4da639"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-ef4b232.jar",
          "url": "kmock-jvm-ef4b232.jar",
          "size": 264329,
          "sha512": "5b168d0318a51d62fe768d3f59273ea5e5e5d361da77507edcee3ef4e495301ffe5f2e59f1cee62d2c8e612c6c97ec74ef4116661bbf736d96fe3711f0919bdc",
          "sha256": "7ffb4abce2d7f93be758bb209fb82725fee1b01f9fbb8978305c3276c1b59b51",
          "sha1": "9286ecb7462da573f7fbdee97cde8ee4a585a46a",
          "md5": "60ac04953fba3bb6eab272228b4da639"
        }
      ]
    }
  ]
}
