{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.3.0-rc05-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc05-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc05-SNAPSHOT.jar",
          "size": 75427,
          "sha512": "30092198959c38caa0d5cf0e84e29f2dc4b1e89ccfb7386ef4bac14e0d05aa2cb73ec930d8c14f49ef4b902bed4c299c98e143478b4b24110335651fbf0eec88",
          "sha256": "c7e3d71d866dd59a67537837feeba3e402b39c4eac2e83f77c481a477a6ac4e0",
          "sha1": "b71b97215b740512cd4aef443f40d4c398b79c9b",
          "md5": "70ab2747825f410711121072e71445fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.7.21-1.0.8"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc05-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc05-SNAPSHOT.jar",
          "size": 75427,
          "sha512": "30092198959c38caa0d5cf0e84e29f2dc4b1e89ccfb7386ef4bac14e0d05aa2cb73ec930d8c14f49ef4b902bed4c299c98e143478b4b24110335651fbf0eec88",
          "sha256": "c7e3d71d866dd59a67537837feeba3e402b39c4eac2e83f77c481a477a6ac4e0",
          "sha1": "b71b97215b740512cd4aef443f40d4c398b79c9b",
          "md5": "70ab2747825f410711121072e71445fb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc05-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.3.0-rc05-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "866862b367d35a9a62e0e4055168a5c5a23249e090336e17cdce0952f742a7e216dcaeef40e184ce9bc206e83ba544d36f68bbdfe3d4acb5d12110aad61e4c3a",
          "sha256": "8edeb2a69d5644f805a8cf58a2549c2a404bdb5d06542aa945791630a8ea7ed8",
          "sha1": "6ab180bd8e9ef57eeda33a16fc0de63a386171df",
          "md5": "df6ea1ddbb062facede5f4e7b9962673"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc05-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.3.0-rc05-SNAPSHOT-sources.jar",
          "size": 14711,
          "sha512": "bb9075eda3ba304a4452e1a39ca0b0d1ea8d2319f65f4784cbd05c4120decfcd73defa6e1835d75502a21c4271e834ea8920d990cb74dd8fa22fadcd04ce3eef",
          "sha256": "41c935e67d42cbebefed48d32c42bcde53eb68f4f16ba514436ec8ec0dbba6ce",
          "sha1": "0dd281919e240ccd071c4fbe0d94d94a109d3f98",
          "md5": "080bdff23cb544b01b51988da29df693"
        }
      ]
    }
  ]
}
