{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc02-SNAPSHOT/kmock-0.3.0-rc02-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc02-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc02-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc02-SNAPSHOT.klib",
          "size": 216312,
          "sha512": "7041fabd45f50be7e8cf58f7a9818acafac0d0a675690430bdf53f6e58a427d07748edb1eb8e4d708a9b3db5cc1d3fc63e06b07b6fbc83c9d788b3ba944af810",
          "sha256": "a6fb841ef10f62202bc2274b848ff0b3d1834363d612d7ba506efee017c511ee",
          "sha1": "054538a1eb0c6c320b15cd81964e9336a11b7914",
          "md5": "a0dd1745a5274e311b52fe8b7d24d593"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc02-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc02-SNAPSHOT.klib",
          "size": 216312,
          "sha512": "7041fabd45f50be7e8cf58f7a9818acafac0d0a675690430bdf53f6e58a427d07748edb1eb8e4d708a9b3db5cc1d3fc63e06b07b6fbc83c9d788b3ba944af810",
          "sha256": "a6fb841ef10f62202bc2274b848ff0b3d1834363d612d7ba506efee017c511ee",
          "sha1": "054538a1eb0c6c320b15cd81964e9336a11b7914",
          "md5": "a0dd1745a5274e311b52fe8b7d24d593"
        }
      ]
    }
  ]
}
