{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "11324f8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-11324f8.jar",
          "url": "antibytes-versioning-11324f8.jar",
          "size": 24262,
          "sha512": "9d3599b3faaf0be48a455a2607a029c5df363f9953532baf04b65b2aa6b609a6575c4044213c6bb2937d541ad4031f4418f986b84e5a618fb1adb6c2c0f8bac1",
          "sha256": "73eef3702ffe80ef51b5b8853edff1081c1e57a0faf77f592b4869a7631000e3",
          "sha1": "ad0edb2dde5110181da55ba10596c807393e6821",
          "md5": "f2958f4b87fa11febfab915c122a8337"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-11324f8.jar",
          "url": "antibytes-versioning-11324f8.jar",
          "size": 24262,
          "sha512": "9d3599b3faaf0be48a455a2607a029c5df363f9953532baf04b65b2aa6b609a6575c4044213c6bb2937d541ad4031f4418f986b84e5a618fb1adb6c2c0f8bac1",
          "sha256": "73eef3702ffe80ef51b5b8853edff1081c1e57a0faf77f592b4869a7631000e3",
          "sha1": "ad0edb2dde5110181da55ba10596c807393e6821",
          "md5": "f2958f4b87fa11febfab915c122a8337"
        }
      ]
    }
  ]
}
