{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.quality",
    "module": "antibytes-quality",
    "version": "9d80d4b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "4.4.1.3373"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-9d80d4b.jar",
          "url": "antibytes-quality-9d80d4b.jar",
          "size": 64846,
          "sha512": "bb9f69f057ddc44d8fae025e2faa09d9b374ce2abbaf057d8a285ec39f54971959eb123550f32590e51956168bdddb51d8320a99a33b8bd22ae43e7966e3ad60",
          "sha256": "e33774129288caa57a96c3fb65d6507c6f8f6957211f39e2f0ed6afbaa791dfc",
          "sha1": "d8598f2b96b4725792f2773f2ff489d79891f93c",
          "md5": "661791e05155097069d5cbc994cf520e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.25.0"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-cli",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "9d80d4b"
          }
        },
        {
          "group": "tech.antibytes.gradle.dependency.helper",
          "module": "antibytes-dependency-helper",
          "version": {
            "requires": "9d80d4b"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "4.4.1.3373"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-9d80d4b.jar",
          "url": "antibytes-quality-9d80d4b.jar",
          "size": 64846,
          "sha512": "bb9f69f057ddc44d8fae025e2faa09d9b374ce2abbaf057d8a285ec39f54971959eb123550f32590e51956168bdddb51d8320a99a33b8bd22ae43e7966e3ad60",
          "sha256": "e33774129288caa57a96c3fb65d6507c6f8f6957211f39e2f0ed6afbaa791dfc",
          "sha1": "d8598f2b96b4725792f2773f2ff489d79891f93c",
          "md5": "661791e05155097069d5cbc994cf520e"
        }
      ]
    }
  ]
}
