{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/019d2ce/kmock-019d2ce.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "019d2ce",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosarm64-019d2ce.klib",
          "size": 113414,
          "sha512": "e5c8037854f094894d9f06b514508db033175cfd95005b201c117850557bf6a86cc9acba9ba87a9a48c1d6b6c9c5a5de8b4adb8f5a52271d3c268ef2dee0f796",
          "sha256": "6a65873e16cfdec181aa0a4bf9a29630286f01b45beb67b4786484370b6e3894",
          "sha1": "64b094105235a388cba5a865cfc4cda4140454e2",
          "md5": "db32ecbdbc7030c917835e74b9d0c9ff"
        }
      ]
    }
  ]
}
