{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kotlin-fixtures-kmp",
    "module": "fixture",
    "version": "87f11d9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-metadata-87f11d9-all.jar",
          "url": "fixture-87f11d9-all.jar",
          "size": 15384,
          "sha512": "8480d6ded5680c03af3fef03bc07d91a07fb801910553b09acec8d8ff05674668dbcba8982d659e511af0a4fe6edc147b078e8b8673e87bb6254c8e902b747de",
          "sha256": "40d851cc3c9b5da104b9b529f0a8fef10e02f5d0fbdf80eb4508a79014c2daa9",
          "sha1": "c10255fc99f3026240805f87c7dcf2a0493835ed",
          "md5": "dd6971a9ad6869af06492a968853b3a6"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fixture-87f11d9.jar",
          "url": "fixture-87f11d9.jar",
          "size": 15444,
          "sha512": "b09b45a19635a9abd14889ccd822706253f6c9f0eec2431573a224186236e967fea4a38a4cb4ed796c012b0e4b709f0151a34a39c28a237898b7186b5c8a500b",
          "sha256": "4c029642cc889ad76563d8378b1099ad267c574b8ee2278df6a1ab1d4a8d9917",
          "sha1": "8f34963bc93002788cb0708b00a4a7491d86b798",
          "md5": "a2318abfb8e24409b8fece75fdfef65e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fixture-android/87f11d9/fixture-android-87f11d9.module",
        "group": "tech.antibytes.kotlin-fixtures-kmp",
        "module": "fixture-android",
        "version": "87f11d9"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fixture-android/87f11d9/fixture-android-87f11d9.module",
        "group": "tech.antibytes.kotlin-fixtures-kmp",
        "module": "fixture-android",
        "version": "87f11d9"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-iosarm64/87f11d9/fixture-iosarm64-87f11d9.module",
        "group": "tech.antibytes.kotlin-fixtures-kmp",
        "module": "fixture-iosarm64",
        "version": "87f11d9"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-iosarm64/87f11d9/fixture-iosarm64-87f11d9.module",
        "group": "tech.antibytes.kotlin-fixtures-kmp",
        "module": "fixture-iosarm64",
        "version": "87f11d9"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-iosx64/87f11d9/fixture-iosx64-87f11d9.module",
        "group": "tech.antibytes.kotlin-fixtures-kmp",
        "module": "fixture-iosx64",
        "version": "87f11d9"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-iosx64/87f11d9/fixture-iosx64-87f11d9.module",
        "group": "tech.antibytes.kotlin-fixtures-kmp",
        "module": "fixture-iosx64",
        "version": "87f11d9"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../fixture-js/87f11d9/fixture-js-87f11d9.module",
        "group": "tech.antibytes.kotlin-fixtures-kmp",
        "module": "fixture-js",
        "version": "87f11d9"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../fixture-js/87f11d9/fixture-js-87f11d9.module",
        "group": "tech.antibytes.kotlin-fixtures-kmp",
        "module": "fixture-js",
        "version": "87f11d9"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fixture-jvm/87f11d9/fixture-jvm-87f11d9.module",
        "group": "tech.antibytes.kotlin-fixtures-kmp",
        "module": "fixture-jvm",
        "version": "87f11d9"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fixture-jvm/87f11d9/fixture-jvm-87f11d9.module",
        "group": "tech.antibytes.kotlin-fixtures-kmp",
        "module": "fixture-jvm",
        "version": "87f11d9"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-linuxx64/87f11d9/fixture-linuxx64-87f11d9.module",
        "group": "tech.antibytes.kotlin-fixtures-kmp",
        "module": "fixture-linuxx64",
        "version": "87f11d9"
      }
    }
  ]
}
