{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-runtime-configuration",
    "version": "d1d6651",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-d1d6651.jar",
          "url": "antibytes-runtime-configuration-d1d6651.jar",
          "size": 10350,
          "sha512": "0e91dabcf3e48a17837bf6f48c398d8e403fd1ea2cf79160a6af0fe1aa6725c34160aef7e07ef821f8bf8a7c509ffc544e68161ca0175b98b3e8e42bab22d7da",
          "sha256": "b42c5581cfffd8d8016311da66252b7df775550f23239dd6dd17730f25a64d3c",
          "sha1": "7185f7953ff171fe6546d8893f5828c13b9227e7",
          "md5": "97898d7a18e274b813d685ea22c8f472"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "d1d6651"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-d1d6651.jar",
          "url": "antibytes-runtime-configuration-d1d6651.jar",
          "size": 10350,
          "sha512": "0e91dabcf3e48a17837bf6f48c398d8e403fd1ea2cf79160a6af0fe1aa6725c34160aef7e07ef821f8bf8a7c509ffc544e68161ca0175b98b3e8e42bab22d7da",
          "sha256": "b42c5581cfffd8d8016311da66252b7df775550f23239dd6dd17730f25a64d3c",
          "sha1": "7185f7953ff171fe6546d8893f5828c13b9227e7",
          "md5": "97898d7a18e274b813d685ea22c8f472"
        }
      ]
    }
  ]
}
