{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/eaacea3/test-utils-eaacea3.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "eaacea3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm-eaacea3.jar",
          "url": "test-utils-jvm-eaacea3.jar",
          "size": 8848,
          "sha512": "43b95d42dcf7c409f38bbf2617b7c49973cb2198f6d0c3b3e5cf89dd38baac7960a230be3e8f421f373d598a76b9562702f47b743c809259f339ee540b72a460",
          "sha256": "e010e9373c1271cbb91b4936cfa82da305b0b2dd2e3e3aa9cfab7a76d815c55a",
          "sha1": "78c7c263526cde83c4976988b47c8f882bb8c374",
          "md5": "4919f9a291d47061629d7fa62705e37d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-eaacea3.jar",
          "url": "test-utils-jvm-eaacea3.jar",
          "size": 8848,
          "sha512": "43b95d42dcf7c409f38bbf2617b7c49973cb2198f6d0c3b3e5cf89dd38baac7960a230be3e8f421f373d598a76b9562702f47b743c809259f339ee540b72a460",
          "sha256": "e010e9373c1271cbb91b4936cfa82da305b0b2dd2e3e3aa9cfab7a76d815c55a",
          "sha1": "78c7c263526cde83c4976988b47c8f882bb8c374",
          "md5": "4919f9a291d47061629d7fa62705e37d"
        }
      ]
    }
  ]
}
