{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/4f11117/test-utils-coroutine-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-watchossimulatorarm64-4f11117.klib",
          "size": 10251,
          "sha512": "2677ddc6bf842f9e9a0e6730316aaefeb3b29b615e177fca6f9ae76409226749de4da390e0a869bb6527438e09868552e2a1efee35ff6f97586309ec9ae2a360",
          "sha256": "b0b6961753bd92f9eb1b6d6dc9d8ee017f11bf9f49ab2c6df541de4acc5586ed",
          "sha1": "3459a407654355b2fe5ec7bba6916b60ddeb30d6",
          "md5": "e56ef68d99d3d9c8272d8e2dcba8d6b6"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-watchossimulatorarm64-4f11117-metadata.jar",
          "url": "test-utils-coroutine-watchossimulatorarm64-4f11117-metadata.jar",
          "size": 261,
          "sha512": "593da9a17adbdd725dd8d5a550129386000320f2e7c3139434c3a1d811eb6c467204bf353d8ea96238dfe95e62a65cbd07ce83467276542dace11d2e54f14c83",
          "sha256": "54d3eb3f1e8223560b661f6b16a945e9f598c59b009b69f62877833d362c7e88",
          "sha1": "41c8a274017902c0d1a18063cc0d63411ccf43be",
          "md5": "2a39dd65a25d827b4e84b0557e15e6de"
        }
      ]
    }
  ]
}
