{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-helper",
    "version": "8c83b4c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-8c83b4c.jar",
          "url": "antibytes-dependency-helper-8c83b4c.jar",
          "size": 44923,
          "sha512": "ee9c7d525428f902da010865dcfab1c2b009a27c31c59165ab874a010c85e683dc452d359613dd09a330dd9980aa2abe29bb011f1a06e357385d23803beb2b4c",
          "sha256": "55a14ce813b236b77b2712ba97f098da554566679ac65c405665f185ac3adad4",
          "sha1": "c013db10e401fd86d7172f39c6c9ff8ae4913d05",
          "md5": "944e0601de45255361988e32aa3cceb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "8c83b4c"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-8c83b4c.jar",
          "url": "antibytes-dependency-helper-8c83b4c.jar",
          "size": 44923,
          "sha512": "ee9c7d525428f902da010865dcfab1c2b009a27c31c59165ab874a010c85e683dc452d359613dd09a330dd9980aa2abe29bb011f1a06e357385d23803beb2b4c",
          "sha256": "55a14ce813b236b77b2712ba97f098da554566679ac65c405665f185ac3adad4",
          "sha1": "c013db10e401fd86d7172f39c6c9ff8ae4913d05",
          "md5": "944e0601de45255361988e32aa3cceb7"
        }
      ]
    }
  ]
}
