{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "79a4505",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-79a4505.jar",
          "url": "antibytes-dependency-79a4505.jar",
          "size": 51855,
          "sha512": "dc2d5ec7a9ab79483116f5e9f9bcddf67f3f111d5a12ff8c3a8e8a6a9d607f827d72ff0dfb5fb3cb36034a8427bc902460886929772df922c1c88333aade6bcc",
          "sha256": "e7629d6eb0ae20e595ad9f40645e7ca5d998ef8228891c7e0d88da5ea56774ea",
          "sha1": "97def0ea64c01fed6b959bbdb8f61c2b2ec621b1",
          "md5": "f6b3ecf73b73eda07b5bfa03d847b24b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.41.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "6.5.3"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.43.2"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "79a4505"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-79a4505.jar",
          "url": "antibytes-dependency-79a4505.jar",
          "size": 51855,
          "sha512": "dc2d5ec7a9ab79483116f5e9f9bcddf67f3f111d5a12ff8c3a8e8a6a9d607f827d72ff0dfb5fb3cb36034a8427bc902460886929772df922c1c88333aade6bcc",
          "sha256": "e7629d6eb0ae20e595ad9f40645e7ca5d998ef8228891c7e0d88da5ea56774ea",
          "sha1": "97def0ea64c01fed6b959bbdb8f61c2b2ec621b1",
          "md5": "f6b3ecf73b73eda07b5bfa03d847b24b"
        }
      ]
    }
  ]
}
