{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "b1a580e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-b1a580e.jar",
          "url": "antibytes-dependency-b1a580e.jar",
          "size": 71463,
          "sha512": "68dfe1a5c9b2b68f5a47aaad1e16f2cb3604a266f6d760b550e14064e64df59e7bbbbb3166a60aadc7f1c0daa78e29b8462d519e20d9b62fc1ec7e5484a542cc",
          "sha256": "39148e78e2a9fe6223dd392f1c5e6b1d7754d87c5e2c95ff37020b18d2a9b4bc",
          "sha1": "6ae903309a44be0b9b360bd71117d83c219df3e6",
          "md5": "f092631e26cce3866be0a2dc8f78933d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-gradle-plugin",
          "version": {
            "requires": "0.17.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.0.4.1"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.44.0"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "b1a580e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-b1a580e.jar",
          "url": "antibytes-dependency-b1a580e.jar",
          "size": 71463,
          "sha512": "68dfe1a5c9b2b68f5a47aaad1e16f2cb3604a266f6d760b550e14064e64df59e7bbbbb3166a60aadc7f1c0daa78e29b8462d519e20d9b62fc1ec7e5484a542cc",
          "sha256": "39148e78e2a9fe6223dd392f1c5e6b1d7754d87c5e2c95ff37020b18d2a9b4bc",
          "sha1": "6ae903309a44be0b9b360bd71117d83c219df3e6",
          "md5": "f092631e26cce3866be0a2dc8f78933d"
        }
      ]
    }
  ]
}
