{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "4b4554a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-4b4554a.jar",
          "url": "antibytes-configuration-4b4554a.jar",
          "size": 49663,
          "sha512": "66b0a8ffaafbc78c378b448945e8dd548f1df2168814fa2e66cf50b566ec5bef20ae7f998bc073b7cf2487cf16de789910a593487e3c54cfb5e0931371c4f6b7",
          "sha256": "6920c7996a0ca6e0860f01f42112cded216c150caa904db74fd4556b0f4ec4c0",
          "sha1": "39035f2535f29f6dc7a92a3cdc0cdd8754618782",
          "md5": "097e1a878a608dabab71114891374d65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.0-rc01"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "4b4554a"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-4b4554a.jar",
          "url": "antibytes-configuration-4b4554a.jar",
          "size": 49663,
          "sha512": "66b0a8ffaafbc78c378b448945e8dd548f1df2168814fa2e66cf50b566ec5bef20ae7f998bc073b7cf2487cf16de789910a593487e3c54cfb5e0931371c4f6b7",
          "sha256": "6920c7996a0ca6e0860f01f42112cded216c150caa904db74fd4556b0f4ec4c0",
          "sha1": "39035f2535f29f6dc7a92a3cdc0cdd8754618782",
          "md5": "097e1a878a608dabab71114891374d65"
        }
      ]
    }
  ]
}
