{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "de4d813",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-de4d813.jar",
          "url": "antibytes-custom-component-de4d813.jar",
          "size": 16534,
          "sha512": "7374688d6edb956d3da4c9c04687375d702ea096817df394d122be516343555752d0c07966fe02c8735c71062fe9dbb56682ecd307e33fd578b2423c5918606e",
          "sha256": "59b4247364527c918fdf2f8d2febedbe3a4600f08bcea0300a4d3328b7669676",
          "sha1": "d6a125f09585e076de9debe275bcb2194d7d3364",
          "md5": "c4a5efa8b4c65d9d835ef584eef7c723"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-de4d813.jar",
          "url": "antibytes-custom-component-de4d813.jar",
          "size": 16534,
          "sha512": "7374688d6edb956d3da4c9c04687375d702ea096817df394d122be516343555752d0c07966fe02c8735c71062fe9dbb56682ecd307e33fd578b2423c5918606e",
          "sha256": "59b4247364527c918fdf2f8d2febedbe3a4600f08bcea0300a4d3328b7669676",
          "sha1": "d6a125f09585e076de9debe275bcb2194d7d3364",
          "md5": "c4a5efa8b4c65d9d835ef584eef7c723"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-custom-component-de4d813-javadoc.jar",
          "url": "antibytes-custom-component-de4d813-javadoc.jar",
          "size": 261,
          "sha512": "fa6bb4f13a86e51bb7a1dd972373ec4133c44f38c8f452cc50e80903b717aeef5ff688c7807d48cc31c8a134732bf9bd3f4f2943b4a3bdf2394b54e9baf1569f",
          "sha256": "13aec6db218e32d9bd1c8a118adbe459bb683658e218a6c095b94e2decc55fb0",
          "sha1": "73ba8362353d8057a40a0cc380235be24ac37eec",
          "md5": "c76b65eeec60ab8338dad186a8f9d383"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-custom-component-de4d813-sources.jar",
          "url": "antibytes-custom-component-de4d813-sources.jar",
          "size": 3352,
          "sha512": "968ddf809446a3fe63267edca986ef57f6ac7a303ef52d65f0737bf5ce963f1bb2c946fce1dc013bf4c8e06779c481478ed22a302186a0e476d23c5811dcd888",
          "sha256": "e4c89bed73d3a0004194d90559959d2e804ea79a89ea69bceb53f89dfc7556fd",
          "sha1": "1ae8e2c3733ece1511c1473d378c9cf7c821ca45",
          "md5": "229ef21274036e5c64401a7d1005fde9"
        }
      ]
    }
  ]
}
