{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "fa31c9e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-fa31c9e.jar",
          "url": "antibytes-coverage-fa31c9e.jar",
          "size": 128528,
          "sha512": "d1052c668a2ab1c6a50551318c0007ea139911ca19e6708068990bec1e983f27e3dc2401ce64427643214b24d59330469117ffaebcade3a9a218776f0e481148",
          "sha256": "65f776c3abd14d86988c72d49f8505ddf3dc97329acd30234e2ece144a1ff127",
          "sha1": "332027a362f63f729f727c12a15b3f88199a4617",
          "md5": "f8cba66a2a30f736e1582ffab8dcb9b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "fa31c9e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-fa31c9e.jar",
          "url": "antibytes-coverage-fa31c9e.jar",
          "size": 128528,
          "sha512": "d1052c668a2ab1c6a50551318c0007ea139911ca19e6708068990bec1e983f27e3dc2401ce64427643214b24d59330469117ffaebcade3a9a218776f0e481148",
          "sha256": "65f776c3abd14d86988c72d49f8505ddf3dc97329acd30234e2ece144a1ff127",
          "sha1": "332027a362f63f729f727c12a15b3f88199a4617",
          "md5": "f8cba66a2a30f736e1582ffab8dcb9b6"
        }
      ]
    }
  ]
}
