{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "dda2add",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-dda2add.jar",
          "url": "antibytes-gradle-utils-dda2add.jar",
          "size": 11392,
          "sha512": "77e354145f2650e5e9ae9cfd0be5b5f49d5fb27592a1a1a001208bbc6189a083bbafa6b123a91ad355f86cc3c6a7b4b4288ff8b4070f70d90d6c5184e4b149d6",
          "sha256": "00380c72c128b9ffa7ef724fa03957496152c40209fc643a23d955e65e285f8e",
          "sha1": "36858030ba13478f0edbf9e1231275d692573e23",
          "md5": "2de3853a540ee0b20b9ab99ff79e3087"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-dda2add.jar",
          "url": "antibytes-gradle-utils-dda2add.jar",
          "size": 11392,
          "sha512": "77e354145f2650e5e9ae9cfd0be5b5f49d5fb27592a1a1a001208bbc6189a083bbafa6b123a91ad355f86cc3c6a7b4b4288ff8b4070f70d90d6c5184e4b149d6",
          "sha256": "00380c72c128b9ffa7ef724fa03957496152c40209fc643a23d955e65e285f8e",
          "sha1": "36858030ba13478f0edbf9e1231275d692573e23",
          "md5": "2de3853a540ee0b20b9ab99ff79e3087"
        }
      ]
    }
  ]
}
