{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/b71b46b/kmock-b71b46b.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "b71b46b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-b71b46b.jar",
          "url": "kmock-jvm-b71b46b.jar",
          "size": 269592,
          "sha512": "a9c40baa0f3f33c0d14f20f796bb4881656572a681b9077a0f0f0a42cd4435e3a28a7d816f0f28ec60bf1d6d74075d38f9a3dd3a070bb80a3894deffa8c30c77",
          "sha256": "4f609fdbbc04621443f6ad70254cfafebca5688c7fe8cc34fcb2c9ea3af48345",
          "sha1": "5405e7607e9a675a91bc33cd3ae0fe9d2b19ed24",
          "md5": "cd1e5aaea3ddf3d3bdb263caa35d41e4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-b71b46b.jar",
          "url": "kmock-jvm-b71b46b.jar",
          "size": 269592,
          "sha512": "a9c40baa0f3f33c0d14f20f796bb4881656572a681b9077a0f0f0a42cd4435e3a28a7d816f0f28ec60bf1d6d74075d38f9a3dd3a070bb80a3894deffa8c30c77",
          "sha256": "4f609fdbbc04621443f6ad70254cfafebca5688c7fe8cc34fcb2c9ea3af48345",
          "sha1": "5405e7607e9a675a91bc33cd3ae0fe9d2b19ed24",
          "md5": "cd1e5aaea3ddf3d3bdb263caa35d41e4"
        }
      ]
    }
  ]
}
