{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/86ec4d6/test-utils-annotations-junit4-86ec4d6.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "86ec4d6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-release.aar",
          "url": "test-utils-annotations-junit4-android-86ec4d6.aar",
          "size": 4252,
          "sha512": "9130343ab4cc5a7146ea66319853a4d2496974e964574aa4b3704e9099f5548aa87779f510dd4e367a5e4df8feb3e0cab9154eab2c34214110362d7f992b172f",
          "sha256": "daedf8bef8e0b301d0f2720884b0aca1db1c4981ba1d9f837b95e16b1b541c4e",
          "sha1": "51e933380addb8025822624f37de04aae3625807",
          "md5": "bbec6876a10916e4f5e0f27b5758ceda"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.9.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.9.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.8.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-release.aar",
          "url": "test-utils-annotations-junit4-android-86ec4d6.aar",
          "size": 4252,
          "sha512": "9130343ab4cc5a7146ea66319853a4d2496974e964574aa4b3704e9099f5548aa87779f510dd4e367a5e4df8feb3e0cab9154eab2c34214110362d7f992b172f",
          "sha256": "daedf8bef8e0b301d0f2720884b0aca1db1c4981ba1d9f837b95e16b1b541c4e",
          "sha1": "51e933380addb8025822624f37de04aae3625807",
          "md5": "bbec6876a10916e4f5e0f27b5758ceda"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-junit4-android-86ec4d6-sources.jar",
          "url": "test-utils-annotations-junit4-android-86ec4d6-sources.jar",
          "size": 6113,
          "sha512": "506a643fe7f48d00f739ad90f6d24d05b2a75f94eb6e6ee54a2b54f14a8d31f4de3f97127a5e2040f301a4f53a07b52cf46baf5e0f5ffc8eb22dad5a11086d96",
          "sha256": "589270281efe4db3942e159be5307d02b6b27ce89878df0413d1905e8ac158cc",
          "sha1": "2635a004d2a21b90afffe60d8caf1428039c871e",
          "md5": "01a38fa1e92636580c96a8af746ef81d"
        }
      ]
    }
  ]
}
