{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/6c316c5/test-utils-6c316c5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "6c316c5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iossimulatorarm64-6c316c5.klib",
          "size": 14403,
          "sha512": "b3b3c96d0c53100cd1fe6698cbda3dc77f1b2ce750f1192db68c79082660f41189166767ca53b66b5aac63d8e2619b37cd289c24853fe3d9d2a1834ad0178d84",
          "sha256": "79c069d69cc26ff7b3778cb7c2ff1551b0423fc1b7a51264b516b948ee91fbfa",
          "sha1": "1cb65592a19f507e61a6739b0fc6affd7851f925",
          "md5": "a6d1813b58d436a4142dc25f104cb82a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iossimulatorarm64-6c316c5-metadata.jar",
          "url": "test-utils-iossimulatorarm64-6c316c5-metadata.jar",
          "size": 261,
          "sha512": "43b19a05297ea3f801ba1c5c05a5d1129449a9399ab769696d3c173969a961c4d65c22a1126623edd9fb745cabf553a2aa609524d485d6735983fed13cb16091",
          "sha256": "deb5c749147171f6c6b8a1d101c687e67d0d294fc8afedab2c97daf5afc12900",
          "sha1": "37a7ca72865d6b0bbf21d0a423ee614829607010",
          "md5": "f9eb1241aede62bdcaa98a5a953e88c2"
        }
      ]
    }
  ]
}
