{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.settings",
    "module": "antibytes-dependency-settings",
    "version": "283c93a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "283c93a"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-283c93a.jar",
          "url": "antibytes-dependency-settings-283c93a.jar",
          "size": 17996,
          "sha512": "8c35d89a095a689edbd7bf3ecd74dc13dae3801810ab5f8fa3ced1a473587853f5d3e33d73a9ef8538172dc5c27f2c52f2a747e6e97df3c93f0f3dd494c2b281",
          "sha256": "dda0e695d766253a9efac8b8253e8811dba2690f411aae60a5afcb0852e16851",
          "sha1": "6f07349b9d2e8da6e54a952d3a6517700323c7ce",
          "md5": "f52cec04fdf8b05181017f9e58367927"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains",
          "module": "foojay-resolver",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "283c93a"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-283c93a.jar",
          "url": "antibytes-dependency-settings-283c93a.jar",
          "size": 17996,
          "sha512": "8c35d89a095a689edbd7bf3ecd74dc13dae3801810ab5f8fa3ced1a473587853f5d3e33d73a9ef8538172dc5c27f2c52f2a747e6e97df3c93f0f3dd494c2b281",
          "sha256": "dda0e695d766253a9efac8b8253e8811dba2690f411aae60a5afcb0852e16851",
          "sha1": "6f07349b9d2e8da6e54a952d3a6517700323c7ce",
          "md5": "f52cec04fdf8b05181017f9e58367927"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-settings-283c93a-javadoc.jar",
          "url": "antibytes-dependency-settings-283c93a-javadoc.jar",
          "size": 261,
          "sha512": "38be3af37fb09731d19128274ff54d57d830c02ddcd08bb7e10ba658e5d8718864d6c05ef1c3603946f818727c7d306e99b5c4c0c9530c732cf6842e162da1a5",
          "sha256": "f0eeac954c9fa91f3a059e86ccb05b7951db277e7d5b44eddc38121e7eab7fa3",
          "sha1": "b42d2bf508dfcb9c4ac9b13b5c5235d64faf86e2",
          "md5": "50aba9555f59de49e4de42f632ea3e84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-settings-283c93a-sources.jar",
          "url": "antibytes-dependency-settings-283c93a-sources.jar",
          "size": 3875,
          "sha512": "892e5c4b2847f3cc80aafbd22d61c5222a09fdf0f4987af3d9cd4b7907e47c0547143bfea4b28119e18cc332005880cbda20891fa1f8056590d4c2f528680cb4",
          "sha256": "45e9508c93088fa521e13c8652311ecade57df4d5fd55a27c0a9eceeef5c5d83",
          "sha1": "76748b1b9d38525c037b1949adc24bceb7d02189",
          "md5": "7c9d5f1c225c9a42e759bc4ff20a4687"
        }
      ]
    }
  ]
}
