{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/d2965a7/core-d2965a7.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "d2965a7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-d2965a7.klib",
          "url": "core-js-d2965a7.klib",
          "size": 61533,
          "sha512": "e266d8599d8836d12582fff5b29ea622f5d8a18407fc8868ca10c4af456a7eeaaa60f05148946c059671c840524ed0c586e12327e1ef5a7db2da5c93a9ae21fa",
          "sha256": "940953d22dcb83b0017fa114002d195dfa4050da27fd8d472a3fcc46af3da1ba",
          "sha1": "7cc5cb997d323c7aeba38fe71785b159701b9193",
          "md5": "5b4b14794afc54d7084ae4a87d600fa6"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-d2965a7.klib",
          "url": "core-js-d2965a7.klib",
          "size": 61533,
          "sha512": "e266d8599d8836d12582fff5b29ea622f5d8a18407fc8868ca10c4af456a7eeaaa60f05148946c059671c840524ed0c586e12327e1ef5a7db2da5c93a9ae21fa",
          "sha256": "940953d22dcb83b0017fa114002d195dfa4050da27fd8d472a3fcc46af3da1ba",
          "sha1": "7cc5cb997d323c7aeba38fe71785b159701b9193",
          "md5": "5b4b14794afc54d7084ae4a87d600fa6"
        }
      ]
    }
  ]
}
