{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "933c5f7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-933c5f7.jar",
          "url": "antibytes-custom-component-933c5f7.jar",
          "size": 16177,
          "sha512": "31560ea6f0d9e5e19bb6e203ee64beea5331c923730bdb65cd094b0d8ef1bdb1a958e9046d09aa80068c91d367efa658bc043385ed2a7c6e2f4706123993263f",
          "sha256": "8b4f0b76aa9f3b08017208c1472510c2ebf42d84b1ff9a1974a3518555199619",
          "sha1": "5a69c0fd233536eaf8c650927b5afb0c017cced4",
          "md5": "1a87f919bba2695cd4458e7e99e4f89d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-933c5f7.jar",
          "url": "antibytes-custom-component-933c5f7.jar",
          "size": 16177,
          "sha512": "31560ea6f0d9e5e19bb6e203ee64beea5331c923730bdb65cd094b0d8ef1bdb1a958e9046d09aa80068c91d367efa658bc043385ed2a7c6e2f4706123993263f",
          "sha256": "8b4f0b76aa9f3b08017208c1472510c2ebf42d84b1ff9a1974a3518555199619",
          "sha1": "5a69c0fd233536eaf8c650927b5afb0c017cced4",
          "md5": "1a87f919bba2695cd4458e7e99e4f89d"
        }
      ]
    }
  ]
}
