{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.coverage",
    "module": "antibytes-coverage",
    "version": "65d8995",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-65d8995.jar",
          "url": "antibytes-coverage-65d8995.jar",
          "size": 135215,
          "sha512": "7630632141cd9259f84b711854f7737f111fd88f64f8cdef65360a49786c92f3b3a19a03a95e0d55a7956115669aa4e13fb39a4fdfecc26f0027079cfd69c6fc",
          "sha256": "cf1644de659ad17cbd06c4c6a7680360cd4ec34766ef905b52f5afe30876b0bd",
          "sha1": "93777f9adcbf06f31ad637a85171a54671913b0f",
          "md5": "708f71e7a466e9cbfa7dd5bfb4155e1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "65d8995"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-65d8995.jar",
          "url": "antibytes-coverage-65d8995.jar",
          "size": 135215,
          "sha512": "7630632141cd9259f84b711854f7737f111fd88f64f8cdef65360a49786c92f3b3a19a03a95e0d55a7956115669aa4e13fb39a4fdfecc26f0027079cfd69c6fc",
          "sha256": "cf1644de659ad17cbd06c4c6a7680360cd4ec34766ef905b52f5afe30876b0bd",
          "sha1": "93777f9adcbf06f31ad637a85171a54671913b0f",
          "md5": "708f71e7a466e9cbfa7dd5bfb4155e1b"
        }
      ]
    }
  ]
}
