{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-0.2.0-SNAPSHOT.jar",
          "url": "core-jvm-0.2.0-SNAPSHOT.jar",
          "size": 251480,
          "sha512": "fc098702974853536b1bf5e11711bfa52abf024d81badb5e2d374d886c27bb47167c30be13a4853d20569719a5d6cafeb5718a878e4f933dc041ca8af58e3086",
          "sha256": "afd0ffae0fa8679895e12076e8a57ffe4adca550fa288f2735656f3b2ad7f9c7",
          "sha1": "dbad2cd2c6afa55890309a7414608eecd2627775",
          "md5": "4e1c36897db3c3d746f1210042b9a03b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.2.0-SNAPSHOT.jar",
          "url": "core-jvm-0.2.0-SNAPSHOT.jar",
          "size": 251480,
          "sha512": "fc098702974853536b1bf5e11711bfa52abf024d81badb5e2d374d886c27bb47167c30be13a4853d20569719a5d6cafeb5718a878e4f933dc041ca8af58e3086",
          "sha256": "afd0ffae0fa8679895e12076e8a57ffe4adca550fa288f2735656f3b2ad7f9c7",
          "sha1": "dbad2cd2c6afa55890309a7414608eecd2627775",
          "md5": "4e1c36897db3c3d746f1210042b9a03b"
        }
      ]
    }
  ]
}
