{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-0.2.0-SNAPSHOT.jar",
          "url": "core-jvm-0.2.0-SNAPSHOT.jar",
          "size": 145325,
          "sha512": "bac9c2315b6164db5906c6a1da8694774c64eec91e213c97e5d9bb514a5e150a5fa5da5508a957a440aee4988a2bcc69cf1a348f32a651c09f4b9c13199a1df2",
          "sha256": "e8427a5dc566666b7db3ec11eb19f15255fd4a09613f8590677bc70f8d312466",
          "sha1": "38acb22116ef948d99fc87e644def1d6ba138319",
          "md5": "d324905756e3d54c0ea89cec0255b820"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.2.0-SNAPSHOT.jar",
          "url": "core-jvm-0.2.0-SNAPSHOT.jar",
          "size": 145325,
          "sha512": "bac9c2315b6164db5906c6a1da8694774c64eec91e213c97e5d9bb514a5e150a5fa5da5508a957a440aee4988a2bcc69cf1a348f32a651c09f4b9c13199a1df2",
          "sha256": "e8427a5dc566666b7db3ec11eb19f15255fd4a09613f8590677bc70f8d312466",
          "sha1": "38acb22116ef948d99fc87e644def1d6ba138319",
          "md5": "d324905756e3d54c0ea89cec0255b820"
        }
      ]
    }
  ]
}
