{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/c37cc63/test-utils-fixture-c37cc63.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "c37cc63",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-c37cc63.klib",
          "url": "test-utils-fixture-js-c37cc63.klib",
          "size": 36097,
          "sha512": "212d6642977d5ef9ddf606ed71f364a905636dde9751a4f2e88a427d047d49b3e12a52957b27aac373e0e1863d86af626c6f6388b1ab695c49fcbfe8d7c77491",
          "sha256": "7a6193b251c4c57bac7570e006eea76a0448cde7f49e962aab5857c3a4c9bb16",
          "sha1": "38d07f69bdecb0af3b6ef1efe0bece4b571bbe7b",
          "md5": "cff5a2a9c6e5f5ac57e7773857493c5c"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-c37cc63.klib",
          "url": "test-utils-fixture-js-c37cc63.klib",
          "size": 36097,
          "sha512": "212d6642977d5ef9ddf606ed71f364a905636dde9751a4f2e88a427d047d49b3e12a52957b27aac373e0e1863d86af626c6f6388b1ab695c49fcbfe8d7c77491",
          "sha256": "7a6193b251c4c57bac7570e006eea76a0448cde7f49e962aab5857c3a4c9bb16",
          "sha1": "38d07f69bdecb0af3b6ef1efe0bece4b571bbe7b",
          "md5": "cff5a2a9c6e5f5ac57e7773857493c5c"
        }
      ]
    }
  ]
}
