{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/eaacea3/test-utils-annotations-eaacea3.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "eaacea3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-iosarm64-eaacea3.klib",
          "size": 11206,
          "sha512": "e9562f03031aa7abee62526f5e739b1858744318b7efbf5e7291e9ae6fa548f953dc83631f1e7dbb0a8bc51fc6252f005a9113601c9698bf609c353c22bce330",
          "sha256": "a5fe8090f5933950ba1733d903ced5a0e277e0cb636ddc304a31159801997823",
          "sha1": "686b666520a4650ae31c0da052e2521774140e78",
          "md5": "a2a22e79f2cafc4d4cbfbde1687a94dc"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-iosarm64-eaacea3-metadata.jar",
          "url": "test-utils-annotations-iosarm64-eaacea3-metadata.jar",
          "size": 261,
          "sha512": "b5ad5cb50921835cf37361b06e20785e8eb63ad28ee053e6b24b0265e042d2a0f69372c17c9c3cd2566c0aca13320def58a031cf061d3de74198792e9bd8420c",
          "sha256": "72bc21f65b7ea27499eef4d7a81b22deefa58e12f46d411186ea9b5ff977dfdd",
          "sha1": "23a33052dc81c61b0abd93b53ec86aad46c42b95",
          "md5": "895235aa193d568746f66f53142a2ea7"
        }
      ]
    }
  ]
}
