{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/5318a03/test-utils-coroutine-5318a03.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "5318a03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js.klib",
          "url": "test-utils-coroutine-js-5318a03.klib",
          "size": 8860,
          "sha512": "d731ae79bba01866e218847e589f60f672d7b4f1d3934459e29adbe916dfa91f888af7193b8fa3e50b552c7f358eb9edfdaf935397e8bbdd437ff70d679f34d8",
          "sha256": "586025baa42c6d291be48d937e19510ed5fe5fd9bfba6e320de933dc0535f24b",
          "sha1": "32ed76be593f4ec44874593ea28f8e462afe1c05",
          "md5": "72865a0be0eeab323dd38ecdd8d6a680"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js.klib",
          "url": "test-utils-coroutine-js-5318a03.klib",
          "size": 8860,
          "sha512": "d731ae79bba01866e218847e589f60f672d7b4f1d3934459e29adbe916dfa91f888af7193b8fa3e50b552c7f358eb9edfdaf935397e8bbdd437ff70d679f34d8",
          "sha256": "586025baa42c6d291be48d937e19510ed5fe5fd9bfba6e320de933dc0535f24b",
          "sha1": "32ed76be593f4ec44874593ea28f8e462afe1c05",
          "md5": "72865a0be0eeab323dd38ecdd8d6a680"
        }
      ]
    }
  ]
}
