{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "a415edd",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "a415edd"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-a415edd.jar",
          "url": "antibytes-mkdocs-a415edd.jar",
          "size": 11930,
          "sha512": "5368e0a22a4b7151901111f22db1c06342f3eae0839565ce5e53b5dac535a8cecc10a0105b925ce9b7db801a5744f495fd53bac5d9b3d6ca9f03bc07e6567878",
          "sha256": "aa0a3955f0f16a8d9c7694a15f98aeedefecf0b0fcf815bfa0ad78d88d81da60",
          "sha1": "6326f40a5b44042a2695ad1f03c640d90a057e01",
          "md5": "5314870d2a130803878d0e7505bc4a5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "a415edd"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "a415edd"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-a415edd.jar",
          "url": "antibytes-mkdocs-a415edd.jar",
          "size": 11930,
          "sha512": "5368e0a22a4b7151901111f22db1c06342f3eae0839565ce5e53b5dac535a8cecc10a0105b925ce9b7db801a5744f495fd53bac5d9b3d6ca9f03bc07e6567878",
          "sha256": "aa0a3955f0f16a8d9c7694a15f98aeedefecf0b0fcf815bfa0ad78d88d81da60",
          "sha1": "6326f40a5b44042a2695ad1f03c640d90a057e01",
          "md5": "5314870d2a130803878d0e7505bc4a5c"
        }
      ]
    }
  ]
}
