{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "87d6f96",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-87d6f96.jar",
          "url": "antibytes-gradle-test-utils-87d6f96.jar",
          "size": 15069,
          "sha512": "8439d1f9d4584593ad9f9e601818cebce66b05b113b7eb5f2c7ed08c7d596633e2f9cf23c030a11c0ef1cd71b5da3b582b4cf9c120fc5caa9ed07524ce76bca6",
          "sha256": "33d0802e91b05a2568a70fc049fe4c2a6c6f5023bf150d756b1a2dc2fe8cd66f",
          "sha1": "99ff4af1f2638954e6d042808b43e2da4e4744d5",
          "md5": "c5d7181e9c668c641813662785e3abbd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-87d6f96.jar",
          "url": "antibytes-gradle-test-utils-87d6f96.jar",
          "size": 15069,
          "sha512": "8439d1f9d4584593ad9f9e601818cebce66b05b113b7eb5f2c7ed08c7d596633e2f9cf23c030a11c0ef1cd71b5da3b582b4cf9c120fc5caa9ed07524ce76bca6",
          "sha256": "33d0802e91b05a2568a70fc049fe4c2a6c6f5023bf150d756b1a2dc2fe8cd66f",
          "sha1": "99ff4af1f2638954e6d042808b43e2da4e4744d5",
          "md5": "c5d7181e9c668c641813662785e3abbd"
        }
      ]
    }
  ]
}
