{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/7008207/test-utils-annotations-7008207.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "7008207",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-iosarm64-7008207.klib",
          "size": 11206,
          "sha512": "e9562f03031aa7abee62526f5e739b1858744318b7efbf5e7291e9ae6fa548f953dc83631f1e7dbb0a8bc51fc6252f005a9113601c9698bf609c353c22bce330",
          "sha256": "a5fe8090f5933950ba1733d903ced5a0e277e0cb636ddc304a31159801997823",
          "sha1": "686b666520a4650ae31c0da052e2521774140e78",
          "md5": "a2a22e79f2cafc4d4cbfbde1687a94dc"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-iosarm64-7008207-metadata.jar",
          "url": "test-utils-annotations-iosarm64-7008207-metadata.jar",
          "size": 261,
          "sha512": "a7fb61429721276f5380d717e5378c9bbd123282137a435fec81722ddd78b5ff562625bbddac5c05d5229399e7a8cf557cca1f240c886123e0275a2fa375a3b6",
          "sha256": "d2e4de164935a781abeecffd9b6f60945a9a7393751ef2df21f786676abb5d4c",
          "sha1": "cd91ec03798d7dc8559746f65cd799bc67bcf600",
          "md5": "8d14b36b6e380d2ef6e4247f8ab1cd77"
        }
      ]
    }
  ]
}
