{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-runtime-configuration",
    "version": "601dc8e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-601dc8e.jar",
          "url": "antibytes-runtime-configuration-601dc8e.jar",
          "size": 20356,
          "sha512": "160a30ed30ad235c60b8bbd6dd3746a2646bf145361dc3ea770cc4ac479440976ee78d12a32d6ec3f5d5439b624e60e2f45e5d64e4d5bc31c617fe89cf1de0e7",
          "sha256": "501da78e0f1715d687e6d1f78f5b9583b926c067e3caaeeb5e4cd5107988f466",
          "sha1": "ce79bcc22641011b7fc74a26a0f50dfb7c162c18",
          "md5": "e90bfcb89694cda741cbec0f139db183"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "601dc8e"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-601dc8e.jar",
          "url": "antibytes-runtime-configuration-601dc8e.jar",
          "size": 20356,
          "sha512": "160a30ed30ad235c60b8bbd6dd3746a2646bf145361dc3ea770cc4ac479440976ee78d12a32d6ec3f5d5439b624e60e2f45e5d64e4d5bc31c617fe89cf1de0e7",
          "sha256": "501da78e0f1715d687e6d1f78f5b9583b926c067e3caaeeb5e4cd5107988f466",
          "sha1": "ce79bcc22641011b7fc74a26a0f50dfb7c162c18",
          "md5": "e90bfcb89694cda741cbec0f139db183"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-601dc8e-javadoc.jar",
          "url": "antibytes-runtime-configuration-601dc8e-javadoc.jar",
          "size": 261,
          "sha512": "b8b71dd20d6fade8a3fde5add5e215cb7c05704aadbb96a89f977ffcc928f6794bf03bd4da4d069f55e5eaf850556805d29d9adac2c3f2e13bb328c33a2c262e",
          "sha256": "cd7c5cbce095374f317f9bc08c86b6de265bd18e9a9379c5d40c8d48fb1aa9b9",
          "sha1": "33ae4e78844a0678d7a9d202e8e0a2179d680b87",
          "md5": "26c069e235ef4b047c4f9fa96186e2c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-601dc8e-sources.jar",
          "url": "antibytes-runtime-configuration-601dc8e-sources.jar",
          "size": 6059,
          "sha512": "fe6a6ff4c4a4ff04ee517b1cbcbc5252c34701a8afa3f22c38d76a487497c7584a66cdb14fd2a9c9aa4a3255a45425fac810a6b9d6ddebb083655168d8f7b301",
          "sha256": "e8cac435250fc69d61bf68217caed543cf6ec14e095ce7916b0b99c3be0dfc6d",
          "sha1": "43117b53ecda9d7b4cb6563c9149efb3802fcd13",
          "md5": "8a3c3356fd77f51e142e2f0bc540d9ba"
        }
      ]
    }
  ]
}
