{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "9e55f01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-9e55f01.jar",
          "url": "antibytes-gradle-test-utils-9e55f01.jar",
          "size": 15105,
          "sha512": "1a207f9b569d51277dbbb6eabe37a816bb8e2c039f966d69039607fed9bf14e3ca960b06fe267bf99dccb7f0e7496b52b81045af4f24679c7c5d3291fd08ae0e",
          "sha256": "1a47818a21bbf5c1a014a32433a915c087a1aff2f01ca7312eea1f1910a9bd82",
          "sha1": "de572c6a76155c3308c44e8bb21cd226d43deb61",
          "md5": "83f2235493182ad118c1a95170a643b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-9e55f01.jar",
          "url": "antibytes-gradle-test-utils-9e55f01.jar",
          "size": 15105,
          "sha512": "1a207f9b569d51277dbbb6eabe37a816bb8e2c039f966d69039607fed9bf14e3ca960b06fe267bf99dccb7f0e7496b52b81045af4f24679c7c5d3291fd08ae0e",
          "sha256": "1a47818a21bbf5c1a014a32433a915c087a1aff2f01ca7312eea1f1910a9bd82",
          "sha1": "de572c6a76155c3308c44e8bb21cd226d43deb61",
          "md5": "83f2235493182ad118c1a95170a643b0"
        }
      ]
    }
  ]
}
