{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "080e68f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "080e68f"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-080e68f.jar",
          "url": "antibytes-mkdocs-080e68f.jar",
          "size": 12083,
          "sha512": "85b1a46dc3ddd289312916e00c5634c53aab61a21a04d05389ba2f1aeec7a16d65c00f87b4a3b80e0c62304c20461e16797b030b476cd07b00da617cd403fdca",
          "sha256": "6fb209dd9ef42d956fd6e6a9c91abd9376bbeb5c107606a8265038ff57b9c4cd",
          "sha1": "9b0322b0d618e451411308e3167bb838ef1fee75",
          "md5": "b90c7c8066850cb0eda94b6b4ecc97a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "080e68f"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "080e68f"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-080e68f.jar",
          "url": "antibytes-mkdocs-080e68f.jar",
          "size": 12083,
          "sha512": "85b1a46dc3ddd289312916e00c5634c53aab61a21a04d05389ba2f1aeec7a16d65c00f87b4a3b80e0c62304c20461e16797b030b476cd07b00da617cd403fdca",
          "sha256": "6fb209dd9ef42d956fd6e6a9c91abd9376bbeb5c107606a8265038ff57b9c4cd",
          "sha1": "9b0322b0d618e451411308e3167bb838ef1fee75",
          "md5": "b90c7c8066850cb0eda94b6b4ecc97a8"
        }
      ]
    }
  ]
}
