{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "789d509",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-coroutine-metadata.jar",
          "url": "test-utils-coroutine-789d509.jar",
          "size": 1609,
          "sha512": "e24c13896813072d078b3097f7a515b6ae97b59cb90875e08d6eb832292b035d3feea363a6b4d0b3df2be70c27e81c7a408289b5db7f9aaf325fb39d86b16e4c",
          "sha256": "6053deea8ceeb5cd274e45eb72d62c58917cfe27fc84e7beef963fa95e7c8ee3",
          "sha1": "4716cbd32de3a69001649aeec927765ad926a5b2",
          "md5": "3421c84544bd82116470f181409598ee"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/789d509/test-utils-coroutine-android-789d509.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "789d509"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/789d509/test-utils-coroutine-android-789d509.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "789d509"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/789d509/test-utils-coroutine-jvm-789d509.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "789d509"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/789d509/test-utils-coroutine-jvm-789d509.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "789d509"
      }
    }
  ]
}
