{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-runtime-configuration",
    "version": "423842c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-423842c.jar",
          "url": "antibytes-runtime-configuration-423842c.jar",
          "size": 9073,
          "sha512": "bcf737867a45b046ea327762f2ad045fdcf4de338bf5b26be8cfca3ba706a7a113de8215a633be2232f78f502f3b5a5f448efe6e0c04c533fb021fc415cea2ea",
          "sha256": "337a32f6ce420cd3ee6f7129f872798fc80a9b18ef30a87dc8309e1b089995ad",
          "sha1": "7c39157af35baea98afc6b6af9167dfc2ae01366",
          "md5": "63bab01e6d7d51fd9f4d05fdf8e1778a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "423842c"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-423842c.jar",
          "url": "antibytes-runtime-configuration-423842c.jar",
          "size": 9073,
          "sha512": "bcf737867a45b046ea327762f2ad045fdcf4de338bf5b26be8cfca3ba706a7a113de8215a633be2232f78f502f3b5a5f448efe6e0c04c533fb021fc415cea2ea",
          "sha256": "337a32f6ce420cd3ee6f7129f872798fc80a9b18ef30a87dc8309e1b089995ad",
          "sha1": "7c39157af35baea98afc6b6af9167dfc2ae01366",
          "md5": "63bab01e6d7d51fd9f4d05fdf8e1778a"
        }
      ]
    }
  ]
}
