{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "c6456b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-c6456b0.jar",
          "url": "antibytes-coverage-c6456b0.jar",
          "size": 128528,
          "sha512": "1fd20c5b74ff8234c7471925b6eec1d0e847e7a0b6ccbd9bf925922f91f8b051056bdfc423afb3b0a54129bb08872d49b6aaaf318bfff779aad70f92dcba2fa9",
          "sha256": "0a70838efaefa361a7258b62e135ec1ce7c4d35354e0bcbf457ff6888c956f24",
          "sha1": "ae15cd825240e9400fe80febe2be872d8c7f4c55",
          "md5": "3088bf20b3e73d284ef9ff352262b986"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "c6456b0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-c6456b0.jar",
          "url": "antibytes-coverage-c6456b0.jar",
          "size": 128528,
          "sha512": "1fd20c5b74ff8234c7471925b6eec1d0e847e7a0b6ccbd9bf925922f91f8b051056bdfc423afb3b0a54129bb08872d49b6aaaf318bfff779aad70f92dcba2fa9",
          "sha256": "0a70838efaefa361a7258b62e135ec1ce7c4d35354e0bcbf457ff6888c956f24",
          "sha1": "ae15cd825240e9400fe80febe2be872d8c7f4c55",
          "md5": "3088bf20b3e73d284ef9ff352262b986"
        }
      ]
    }
  ]
}
