{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/f384302/test-utils-coroutine-f384302.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "f384302",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosx64-f384302.klib",
          "size": 10112,
          "sha512": "0c9109497ef5116df57d780fb9927fa9a211b8c342a4a7fbb3461b555cfc0a69658dd4d762d29aeb47083f1264b99df98abe9ca148acfe1f7227ae8e67041ad7",
          "sha256": "2da8c8de1522ad369562f0bd2b838eba30fdb3b2eefa319776aab12fff1d9c69",
          "sha1": "3d1c065ed2929a8a21b7209b42256a163e080647",
          "md5": "6e8825ff0ee058c6b2a9aeeefd714a50"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosx64-f384302-metadata.jar",
          "url": "test-utils-coroutine-iosx64-f384302-metadata.jar",
          "size": 261,
          "sha512": "0648c85edf50add0e1aea2ba0b105792a048ba1c1f3574cb9129beeb54375205b97693b7db3a074f635d5e18e22906c9a1eb382bb68dd6bc36f3bcf7ebd74eed",
          "sha256": "7059af44f1171ed47c7ba709c053bb4a3a246d2290ec4cf34771459841f8d7f4",
          "sha1": "829074b8ff96a65d15b6513a870be83a527c51ba",
          "md5": "a110448ff2b5480c491ad792f3739656"
        }
      ]
    }
  ]
}
