{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.0-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.0-SNAPSHOT.jar",
          "size": 114685,
          "sha512": "447496cab3fbb4d46ce92c526725208f46adb692ac554b6c890a6674dbe54bb6a519bca1170b269469eeb3ea17422354d3457f5d309e035f0635d97e247bef97",
          "sha256": "3273976ca5af3f140d68c34a094f1972ae4ca66f682f6f00efea3dff66a138a3",
          "sha1": "399735ec945966f83bbec041ccb14c7b773e6eab",
          "md5": "6b47642f8986a836d48bcc3ad9e1830f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.0-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.0-SNAPSHOT.jar",
          "size": 114685,
          "sha512": "447496cab3fbb4d46ce92c526725208f46adb692ac554b6c890a6674dbe54bb6a519bca1170b269469eeb3ea17422354d3457f5d309e035f0635d97e247bef97",
          "sha256": "3273976ca5af3f140d68c34a094f1972ae4ca66f682f6f00efea3dff66a138a3",
          "sha1": "399735ec945966f83bbec041ccb14c7b773e6eab",
          "md5": "6b47642f8986a836d48bcc3ad9e1830f"
        }
      ]
    }
  ]
}
