{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.0-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.0-SNAPSHOT.jar",
          "size": 114685,
          "sha512": "46eb3f7c5b995ad4c91f64ea195e3051b9400bf8c7616e0c4d63c5252195f046a791beed92f4affea39f53c03aa2f3baa65fad548ba3ea01dedce938bd95cf31",
          "sha256": "6101e9294984f9e88b932fbbb7844173dc333848ca65d78be343afdd1e66b7b5",
          "sha1": "856ad67ad285efac49d49a98e6a347bac056e150",
          "md5": "a572a08c8af8cb949559283b90f3b5ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.0-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.0-SNAPSHOT.jar",
          "size": 114685,
          "sha512": "46eb3f7c5b995ad4c91f64ea195e3051b9400bf8c7616e0c4d63c5252195f046a791beed92f4affea39f53c03aa2f3baa65fad548ba3ea01dedce938bd95cf31",
          "sha256": "6101e9294984f9e88b932fbbb7844173dc333848ca65d78be343afdd1e66b7b5",
          "sha1": "856ad67ad285efac49d49a98e6a347bac056e150",
          "md5": "a572a08c8af8cb949559283b90f3b5ea"
        }
      ]
    }
  ]
}
