{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/56c4547/test-utils-ktor-56c4547.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "56c4547",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-56c4547.jar",
          "url": "test-utils-ktor-jvm-56c4547.jar",
          "size": 26352,
          "sha512": "39be40fcdaa7372c83d5374c9bc12cc77ee8c253802a1bd51efb166a5b16bb4974f1d492e6f01163a8d4dac93774632778cb98debd4caf522247d08c3bc66a02",
          "sha256": "8a657e2a5d0bffc8b7a4b7f3eb75c381ab625d8ed24f422252dd6b827ee1fbbf",
          "sha1": "930638eaa8fb2e1c80b57ec4e045243deb67b5c1",
          "md5": "331de7abaf2e3a198610c57798ba762b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-56c4547.jar",
          "url": "test-utils-ktor-jvm-56c4547.jar",
          "size": 26352,
          "sha512": "39be40fcdaa7372c83d5374c9bc12cc77ee8c253802a1bd51efb166a5b16bb4974f1d492e6f01163a8d4dac93774632778cb98debd4caf522247d08c3bc66a02",
          "sha256": "8a657e2a5d0bffc8b7a4b7f3eb75c381ab625d8ed24f422252dd6b827ee1fbbf",
          "sha1": "930638eaa8fb2e1c80b57ec4e045243deb67b5c1",
          "md5": "331de7abaf2e3a198610c57798ba762b"
        }
      ]
    }
  ]
}
