{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "009e2b6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-009e2b6.jar",
          "url": "antibytes-grammar-tools-009e2b6.jar",
          "size": 39373,
          "sha512": "464c062bdf2f71e9d811ab317301bdfac4f806c2faa2f7781f67a0e5cf57050868b4e016096a5cff2042c6af31fe65e1d98833f01fc45d71398ba84d908dc122",
          "sha256": "b36f59521aa16f741f18b027cfae62c9073ce3c2233296e7474697296d1b511e",
          "sha1": "825ab6b1f0be09b6dc1e48a35febc18c9e01fde1",
          "md5": "384ad5c8c8223d6822f6806dee65d30e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-009e2b6.jar",
          "url": "antibytes-grammar-tools-009e2b6.jar",
          "size": 39373,
          "sha512": "464c062bdf2f71e9d811ab317301bdfac4f806c2faa2f7781f67a0e5cf57050868b4e016096a5cff2042c6af31fe65e1d98833f01fc45d71398ba84d908dc122",
          "sha256": "b36f59521aa16f741f18b027cfae62c9073ce3c2233296e7474697296d1b511e",
          "sha1": "825ab6b1f0be09b6dc1e48a35febc18c9e01fde1",
          "md5": "384ad5c8c8223d6822f6806dee65d30e"
        }
      ]
    }
  ]
}
