{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "size": 295193,
          "sha512": "3e4d45010ffcfbaf4b7fb4d106a2699a875fdc4a320c7226548d1c86677d70ec68681b4e652d25fdad49936ca01095038a7bb96fc1989af4886e270b0a2c4ac1",
          "sha256": "9d0b8bac9a5d5db060c31e72497b3aee6d9e44258c093b344d920bfc77eeed44",
          "sha1": "bac7550d17e3f7c0e54361ef4745eb2f283dede7",
          "md5": "70f403d8778d9fa2e538f9d0e950d70e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "size": 295193,
          "sha512": "3e4d45010ffcfbaf4b7fb4d106a2699a875fdc4a320c7226548d1c86677d70ec68681b4e652d25fdad49936ca01095038a7bb96fc1989af4886e270b0a2c4ac1",
          "sha256": "9d0b8bac9a5d5db060c31e72497b3aee6d9e44258c093b344d920bfc77eeed44",
          "sha1": "bac7550d17e3f7c0e54361ef4745eb2f283dede7",
          "md5": "70f403d8778d9fa2e538f9d0e950d70e"
        }
      ]
    }
  ]
}
