{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "size": 308625,
          "sha512": "68cc920329536c952475796306aa98e54ef27f47bb93104eb167305cfb0404aaa108f010ae837b920784ed5d5c11fa06f019a6871b753df5b96d81f41261de57",
          "sha256": "f853710ad0311e91bbb64546e14e76f9b9aa934c9d2d33667084ff2b19b26646",
          "sha1": "e9ea525e3193d9bb1ef4c56b4cf89dd8b44382be",
          "md5": "be4bf43bd32d678ee0b0a82a85cc7ab8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "size": 308625,
          "sha512": "68cc920329536c952475796306aa98e54ef27f47bb93104eb167305cfb0404aaa108f010ae837b920784ed5d5c11fa06f019a6871b753df5b96d81f41261de57",
          "sha256": "f853710ad0311e91bbb64546e14e76f9b9aa934c9d2d33667084ff2b19b26646",
          "sha1": "e9ea525e3193d9bb1ef4c56b4cf89dd8b44382be",
          "md5": "be4bf43bd32d678ee0b0a82a85cc7ab8"
        }
      ]
    }
  ]
}
