{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "size": 295193,
          "sha512": "58af4e559ffbeed2e55b157a9bbf36443780b84bc31047adce49d5df2d797ab762a6a80c322ae994a0b20194437ffd82a12c58e93979e981eab35cffcb54713d",
          "sha256": "94e432e46b1dc0e4e5c437718a050205aefbd0a88c2e379777fdfb58df1347c3",
          "sha1": "86a300f3289aea180115ff2b26e2e07ca6f7758c",
          "md5": "cd5b3af79d7cd8273e31a1fd26047620"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "size": 295193,
          "sha512": "58af4e559ffbeed2e55b157a9bbf36443780b84bc31047adce49d5df2d797ab762a6a80c322ae994a0b20194437ffd82a12c58e93979e981eab35cffcb54713d",
          "sha256": "94e432e46b1dc0e4e5c437718a050205aefbd0a88c2e379777fdfb58df1347c3",
          "sha1": "86a300f3289aea180115ff2b26e2e07ca6f7758c",
          "md5": "cd5b3af79d7cd8273e31a1fd26047620"
        }
      ]
    }
  ]
}
