{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "size": 335472,
          "sha512": "7fab2a4b1856c68213ec6e62cc81d8f7aa86681b34e1bd27850d6d025d130b8f28d1e4591e1a8124b3de78788bc7aa73d4f6ddf00f015dac8aca1abee2418d4d",
          "sha256": "3ed9b0fc6edc2a30a3237284452289f7bee336c980a5f1b3959c7a4b2c8daafc",
          "sha1": "036e7974f1098ebd026fa279f43ad9a7213dd841",
          "md5": "9a7de3347d231c09d0290cc4cbd1f67d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "size": 335472,
          "sha512": "7fab2a4b1856c68213ec6e62cc81d8f7aa86681b34e1bd27850d6d025d130b8f28d1e4591e1a8124b3de78788bc7aa73d4f6ddf00f015dac8aca1abee2418d4d",
          "sha256": "3ed9b0fc6edc2a30a3237284452289f7bee336c980a5f1b3959c7a4b2c8daafc",
          "sha1": "036e7974f1098ebd026fa279f43ad9a7213dd841",
          "md5": "9a7de3347d231c09d0290cc4cbd1f67d"
        }
      ]
    }
  ]
}
