{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "size": 331757,
          "sha512": "762d4e3dba35a67f1803df35cc9c6e755ada473fcba54b7cf4634feb09e58c7cfa2684ab0e91626e7653e3e7fd9d5f4037d998419dc7161aa79362cfea689b40",
          "sha256": "501d32e196c5ac96d935ff56cff85a4993dfe5d2c4e20dc6683ee38e17f93e0c",
          "sha1": "b89c93ee3c8e169924868a596be3a549b280ca13",
          "md5": "6f683ef08536f64909e80a263bcc8462"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "size": 331757,
          "sha512": "762d4e3dba35a67f1803df35cc9c6e755ada473fcba54b7cf4634feb09e58c7cfa2684ab0e91626e7653e3e7fd9d5f4037d998419dc7161aa79362cfea689b40",
          "sha256": "501d32e196c5ac96d935ff56cff85a4993dfe5d2c4e20dc6683ee38e17f93e0c",
          "sha1": "b89c93ee3c8e169924868a596be3a549b280ca13",
          "md5": "6f683ef08536f64909e80a263bcc8462"
        }
      ]
    }
  ]
}
