{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "size": 292505,
          "sha512": "63b52e61c32e6cfb6ce95ebb18f1f5be32f191afd4622ce7fbeb405fc353e86cf4086021473eccbd1f2f4690010ecd1b27c9c94989e1100ff8a7298c0f634c0a",
          "sha256": "ab9be0ed899b90265e28a58d2614f23697cfba86e3c6c907ea4b422d91f3f43e",
          "sha1": "46acb7884c7de8e00f798845a7d52ff56d89065e",
          "md5": "c736ea1ff5b122e20e7a17238411330c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "size": 292505,
          "sha512": "63b52e61c32e6cfb6ce95ebb18f1f5be32f191afd4622ce7fbeb405fc353e86cf4086021473eccbd1f2f4690010ecd1b27c9c94989e1100ff8a7298c0f634c0a",
          "sha256": "ab9be0ed899b90265e28a58d2614f23697cfba86e3c6c907ea4b422d91f3f43e",
          "sha1": "46acb7884c7de8e00f798845a7d52ff56d89065e",
          "md5": "c736ea1ff5b122e20e7a17238411330c"
        }
      ]
    }
  ]
}
