{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "size": 381472,
          "sha512": "2ac63952a335f726d0453f9977dc1af4875fa105a5c84228adc057301c34a80b9b9051a0907ab5f26eeeaf6e98879c8c7eb2578de8dc2d524c109e1015796be6",
          "sha256": "72850996f09bd678456591fa338460166a9befab2954622b130769c4c116c354",
          "sha1": "a24a67b154571968918a808ad5f70d0ae34b4dcd",
          "md5": "9e16124b00ce026367fa9c02063388e2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "size": 381472,
          "sha512": "2ac63952a335f726d0453f9977dc1af4875fa105a5c84228adc057301c34a80b9b9051a0907ab5f26eeeaf6e98879c8c7eb2578de8dc2d524c109e1015796be6",
          "sha256": "72850996f09bd678456591fa338460166a9befab2954622b130769c4c116c354",
          "sha1": "a24a67b154571968918a808ad5f70d0ae34b4dcd",
          "md5": "9e16124b00ce026367fa9c02063388e2"
        }
      ]
    }
  ]
}
