{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "size": 350707,
          "sha512": "ac0f2466e8fe5db84bddaa130df0c14ec4cb3a7b7f9f20c7801ddaf8813a9cd2ae2348055a4d0998c8237b3787f1c16e3fbce59259a8dac22264f78fa0520682",
          "sha256": "b409811915862510085d03e77d8a8575f0115ce516fecc53fc78592bf770db12",
          "sha1": "51d05f10132084975d0e9eb5232e7ad2870dfb81",
          "md5": "db20e84f83d261195920b176e46e2d86"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-SNAPSHOT.jar",
          "size": 350707,
          "sha512": "ac0f2466e8fe5db84bddaa130df0c14ec4cb3a7b7f9f20c7801ddaf8813a9cd2ae2348055a4d0998c8237b3787f1c16e3fbce59259a8dac22264f78fa0520682",
          "sha256": "b409811915862510085d03e77d8a8575f0115ce516fecc53fc78592bf770db12",
          "sha1": "51d05f10132084975d0e9eb5232e7ad2870dfb81",
          "md5": "db20e84f83d261195920b176e46e2d86"
        }
      ]
    }
  ]
}
