{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/0a268dd/test-utils-0a268dd.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "0a268dd",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js.klib",
          "url": "test-utils-js-0a268dd.klib",
          "size": 11900,
          "sha512": "e4bf2aec717621304440361eae1d2c8f80e2c31f8862ebf547e074d6f8bd10e31ccd4290c3617eff563366794d03ece57c669b0f119fdf6716a270cc2a960189",
          "sha256": "c41d8211aa238d7f87808be17710ce7e5220a10d25077d0b80bd7c17073e8ad1",
          "sha1": "79f5a18a886652dbb9452ee5b725a1e476ff96dc",
          "md5": "5472e91970990cdfb444d380414a8004"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js.klib",
          "url": "test-utils-js-0a268dd.klib",
          "size": 11900,
          "sha512": "e4bf2aec717621304440361eae1d2c8f80e2c31f8862ebf547e074d6f8bd10e31ccd4290c3617eff563366794d03ece57c669b0f119fdf6716a270cc2a960189",
          "sha256": "c41d8211aa238d7f87808be17710ce7e5220a10d25077d0b80bd7c17073e8ad1",
          "sha1": "79f5a18a886652dbb9452ee5b725a1e476ff96dc",
          "md5": "5472e91970990cdfb444d380414a8004"
        }
      ]
    }
  ]
}
