{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "6731cef",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-6731cef.jar",
          "url": "antibytes-grammar-tools-6731cef.jar",
          "size": 39410,
          "sha512": "58b7189be511b0fb8b80f0f6c0e3d895d64143d25ba331866bcca8c9f839a0975f1a58dfbf756154745500a5d74b2cc745b365e4128150cc18a6c8596b0298ad",
          "sha256": "205cf5d83090282da1fd914d135c02350d7241c965741bf600dbd8f9eea835e1",
          "sha1": "9e7f3893b550d1c254e909fc097a6e55462ff2ea",
          "md5": "747e8e3cc065d8cc2e441b64dbd384f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-6731cef.jar",
          "url": "antibytes-grammar-tools-6731cef.jar",
          "size": 39410,
          "sha512": "58b7189be511b0fb8b80f0f6c0e3d895d64143d25ba331866bcca8c9f839a0975f1a58dfbf756154745500a5d74b2cc745b365e4128150cc18a6c8596b0298ad",
          "sha256": "205cf5d83090282da1fd914d135c02350d7241c965741bf600dbd8f9eea835e1",
          "sha1": "9e7f3893b550d1c254e909fc097a6e55462ff2ea",
          "md5": "747e8e3cc065d8cc2e441b64dbd384f9"
        }
      ]
    }
  ]
}
