{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/b9030f2/test-utils-ktor-b9030f2.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "b9030f2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.8"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iossimulatorarm64-b9030f2.klib",
          "size": 15587,
          "sha512": "8d51c2c771f4aef866080be7ace4e06014ede8501e87bc38def6240fdb515a7f760997b328d54e7ae6f0136a34df2c8c285c81b6dd859a425a2915214fce83cb",
          "sha256": "cfea4d332cb3684989902318f8a2b69cf461a11f75b1c656ddc9fccd9b9e8227",
          "sha1": "533f1a8bb7a68ab952c044efb86c0b8aa9e732e7",
          "md5": "7b95c1786b388cf39816b758e0bd4351"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-ktor-iossimulatorarm64-b9030f2-sources.jar",
          "url": "test-utils-ktor-iossimulatorarm64-b9030f2-sources.jar",
          "size": 2872,
          "sha512": "2268f2772929e73f6f4cccb0ebfc887c2fca1a9a7518d50c3a0cd6141b1615740b1bbe8f39f3ae9045c34e283023352c23e1943c8c39a58f65cc05243bf01a94",
          "sha256": "6d96d8b473fe6fa2ee93d7c4ac375d0570434c9ab65c01bae96d632733a9d562",
          "sha1": "95f77daf58aa6a77bf8927057cd070da7b9b3409",
          "md5": "2b46f609ce899dc78e54dabcd42dec8a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.8"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iossimulatorarm64-b9030f2-metadata.jar",
          "url": "test-utils-ktor-iossimulatorarm64-b9030f2-metadata.jar",
          "size": 261,
          "sha512": "470e2de9af35d9739e3e0a36b865ae1a014844e6606027ec21a5f9b02cd1b3e417843881712e9b000f048be8c88d6dc84cb26c9e1bd4e2b7cc3564b97043e431",
          "sha256": "90698e3428919bf361e54d4b754e1293ef437a2c89f3c436e8904bb292dfaeec",
          "sha1": "6df3a2d4725a2f32bbb60d5d84f0bf8cf8dbae20",
          "md5": "643f4a836a0da79497cb4e5968348bad"
        }
      ]
    }
  ]
}
