{
  "formatVersion": "1.1",
  "component": {
    "url": "../../clientSDK/9d5fb73/clientSDK-9d5fb73.module",
    "group": "tech.antibytes.awesomecats",
    "module": "clientSDK",
    "version": "9d5fb73",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "clientSDK-jvm-9d5fb73.jar",
          "url": "clientSDK-jvm-9d5fb73.jar",
          "size": 70086,
          "sha512": "7824e16f4bb46729eb7f1107ef9e20cb3dc95d3f3461c1d45417da57a13499b7e74538b645f25ed2ea76fee79bd9939b9a3e78beb024c82039de17fb95c95db6",
          "sha256": "5fd94b729936b91332a2d3fbaff8d268169b2c79431dd7a278ce554988c31ceb",
          "sha1": "12ca29c69d3783811694000fe167f6e0464bd389",
          "md5": "0c5720ae9c84b8cc7443c19a2abe4fb2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result",
          "version": {
            "requires": "1.1.16"
          }
        }
      ],
      "files": [
        {
          "name": "clientSDK-jvm-9d5fb73.jar",
          "url": "clientSDK-jvm-9d5fb73.jar",
          "size": 70086,
          "sha512": "7824e16f4bb46729eb7f1107ef9e20cb3dc95d3f3461c1d45417da57a13499b7e74538b645f25ed2ea76fee79bd9939b9a3e78beb024c82039de17fb95c95db6",
          "sha256": "5fd94b729936b91332a2d3fbaff8d268169b2c79431dd7a278ce554988c31ceb",
          "sha1": "12ca29c69d3783811694000fe167f6e0464bd389",
          "md5": "0c5720ae9c84b8cc7443c19a2abe4fb2"
        }
      ]
    }
  ]
}
