{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "022f831",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-022f831.jar",
          "url": "antibytes-versioning-022f831.jar",
          "size": 21893,
          "sha512": "6e7fd4b575a1059a88c4e523c0ae484ebef1a01603f0b218abf8c65da983461241f9eff80e52c1161afb686a8cae403760999cf33dbea49453a6c881b67f13a2",
          "sha256": "5ee4a1f9c02d05d4054f47a139cda38c2c3a4dd0228e6e6f074b082b5ea1c339",
          "sha1": "54f0596f27719f7f849072a46741cdc5ff23c9aa",
          "md5": "f9a366e97af08345f5998d06b582f23f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-022f831.jar",
          "url": "antibytes-versioning-022f831.jar",
          "size": 21893,
          "sha512": "6e7fd4b575a1059a88c4e523c0ae484ebef1a01603f0b218abf8c65da983461241f9eff80e52c1161afb686a8cae403760999cf33dbea49453a6c881b67f13a2",
          "sha256": "5ee4a1f9c02d05d4054f47a139cda38c2c3a4dd0228e6e6f074b082b5ea1c339",
          "sha1": "54f0596f27719f7f849072a46741cdc5ff23c9aa",
          "md5": "f9a366e97af08345f5998d06b582f23f"
        }
      ]
    }
  ]
}
