{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/e2b0926/test-utils-ktor-e2b0926.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "e2b0926",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-e2b0926.jar",
          "size": 27246,
          "sha512": "9eadfaf2023f51749d148cca70e6b77e77aa5aa1cb3931d9027098132d54d03a10b1c56102e4b4ff46a82ff155684572f4d636ef35fabd663b613118755f2fe3",
          "sha256": "94331be42b1c9ca97e1eba2fe6680550ca11312b203e512f659ba280b5320611",
          "sha1": "ffe53dff2c29d7d07c3f3ec3238c20b990949529",
          "md5": "7eb2784ece6804b023d45a33649f6673"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "1.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-e2b0926.jar",
          "size": 27246,
          "sha512": "9eadfaf2023f51749d148cca70e6b77e77aa5aa1cb3931d9027098132d54d03a10b1c56102e4b4ff46a82ff155684572f4d636ef35fabd663b613118755f2fe3",
          "sha256": "94331be42b1c9ca97e1eba2fe6680550ca11312b203e512f659ba280b5320611",
          "sha1": "ffe53dff2c29d7d07c3f3ec3238c20b990949529",
          "md5": "7eb2784ece6804b023d45a33649f6673"
        }
      ]
    }
  ]
}
