{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "b1373c3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-b1373c3.jar",
          "url": "antibytes-gradle-utils-b1373c3.jar",
          "size": 9568,
          "sha512": "17819187564f829a307473ea9430a63be1df31f6b74733a84ba59a8b3afa9d722dcaccffd148247590d8644d5ee1cfd613fff4dcb3dc8a8a550da793257099e0",
          "sha256": "84d3791509bb7499d86d1fdde63179cfcab5a05d0a94d75a78f8f19ef9025510",
          "sha1": "888494a1de86af20dd21b88d846f1e34e35e1db2",
          "md5": "b1e90f78bfae5e6b8e0ea28b2e028473"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-b1373c3.jar",
          "url": "antibytes-gradle-utils-b1373c3.jar",
          "size": 9568,
          "sha512": "17819187564f829a307473ea9430a63be1df31f6b74733a84ba59a8b3afa9d722dcaccffd148247590d8644d5ee1cfd613fff4dcb3dc8a8a550da793257099e0",
          "sha256": "84d3791509bb7499d86d1fdde63179cfcab5a05d0a94d75a78f8f19ef9025510",
          "sha1": "888494a1de86af20dd21b88d846f1e34e35e1db2",
          "md5": "b1e90f78bfae5e6b8e0ea28b2e028473"
        }
      ]
    }
  ]
}
