{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/b7a1e13/kmock-b7a1e13.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "b7a1e13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-b7a1e13.klib",
          "url": "kmock-js-b7a1e13.klib",
          "size": 124135,
          "sha512": "cacf855ba88d5a209c6ae9438de99853fb3b0682c4f7eca7798d2bcefa999f9b04b54febabd7fcf21ad3950ab76c87d286b279fbb75710557725558ad6d68c00",
          "sha256": "1d0266c910b2ea2b268c37ba8a00a4536132b31d8c89f819173473857b677377",
          "sha1": "49bd851e7aaa697f783ebada87651b22fb76de23",
          "md5": "b6ee0cccd644ca023bcf0cb8dc62f04d"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-b7a1e13.klib",
          "url": "kmock-js-b7a1e13.klib",
          "size": 124135,
          "sha512": "cacf855ba88d5a209c6ae9438de99853fb3b0682c4f7eca7798d2bcefa999f9b04b54febabd7fcf21ad3950ab76c87d286b279fbb75710557725558ad6d68c00",
          "sha256": "1d0266c910b2ea2b268c37ba8a00a4536132b31d8c89f819173473857b677377",
          "sha1": "49bd851e7aaa697f783ebada87651b22fb76de23",
          "md5": "b6ee0cccd644ca023bcf0cb8dc62f04d"
        }
      ]
    }
  ]
}
