{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/1b54cfa/test-utils-fixture-1b54cfa.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "1b54cfa",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-release.aar",
          "url": "test-utils-fixture-android-1b54cfa.aar",
          "size": 35598,
          "sha512": "3a3df9160411565b39a702590aff1751046e350718508afb68ce95d47b389d56dbb23e2f13489c96b608c42451cd41eff6861323e0fbb105952637489d380a80",
          "sha256": "9a418f025200f69c9f9d4d897b686b800186d74f6fbecce3f024193f58a3e6d8",
          "sha1": "cc6b1e1208ea317fbbc853b8087f55e5bd5820a0",
          "md5": "78001a2deb90b37b1c61e4531215566b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-release.aar",
          "url": "test-utils-fixture-android-1b54cfa.aar",
          "size": 35598,
          "sha512": "3a3df9160411565b39a702590aff1751046e350718508afb68ce95d47b389d56dbb23e2f13489c96b608c42451cd41eff6861323e0fbb105952637489d380a80",
          "sha256": "9a418f025200f69c9f9d4d897b686b800186d74f6fbecce3f024193f58a3e6d8",
          "sha1": "cc6b1e1208ea317fbbc853b8087f55e5bd5820a0",
          "md5": "78001a2deb90b37b1c61e4531215566b"
        }
      ]
    }
  ]
}
