{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "58e1b20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-58e1b20.jar",
          "url": "antibytes-publishing-58e1b20.jar",
          "size": 100331,
          "sha512": "15fe322ef6ff956a8ae4d7753c643eb27c72f86a9c3edab57f3ea5be424e394a0a360a448bc9893fc1bacb21cd41e2b1eb239493ff9759bc2738cfb7ec5db492",
          "sha256": "e3100a17d98b63ae8e5504f556b2eec7b3d6d46cab8d2b149122bfa92bd1cded",
          "sha1": "d0867ddac8ce47d995620fb57f0fe2755e26edfe",
          "md5": "b2f3ab0ec9074b4b234476031c332f27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.11.0.202103091610-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-58e1b20.jar",
          "url": "antibytes-publishing-58e1b20.jar",
          "size": 100331,
          "sha512": "15fe322ef6ff956a8ae4d7753c643eb27c72f86a9c3edab57f3ea5be424e394a0a360a448bc9893fc1bacb21cd41e2b1eb239493ff9759bc2738cfb7ec5db492",
          "sha256": "e3100a17d98b63ae8e5504f556b2eec7b3d6d46cab8d2b149122bfa92bd1cded",
          "sha1": "d0867ddac8ce47d995620fb57f0fe2755e26edfe",
          "md5": "b2f3ab0ec9074b4b234476031c332f27"
        }
      ]
    }
  ]
}
