{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/86ec4d6/test-utils-resourceloader-86ec4d6.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "86ec4d6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iosx64-86ec4d6.klib",
          "size": 14196,
          "sha512": "7bad3f7aa8cae2db8afc2c75d4542fc38ad3d1aee229042baf224cb72de53c42a8072fc410aaca4a8a159dc4a9b0d3b58d03ef4d3bdb35b970e4a2657ec00bbc",
          "sha256": "2a541b6b35ddde41704d8ff9f1f7e7c0ef4cf57d9ac47af96f14ad97b9b33f68",
          "sha1": "2bb459e5d19a9bb086bccc82242193ab9d65388d",
          "md5": "897b5fbc05c0c8bb489f3f4962643780"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-iosx64-86ec4d6-sources.jar",
          "url": "test-utils-resourceloader-iosx64-86ec4d6-sources.jar",
          "size": 4241,
          "sha512": "284172150658cfb9dae6c2bb10bbd5de382a8193d892540a4de60322cb16b05740a160fc4f827c092194ab0e3983419cb75c9d52eee7cf9cf1ac22b32a8f7d7b",
          "sha256": "28c33fb0c5429879a7515dfb1ee5400a354f30a17cda3a32c13cec2fd413b7da",
          "sha1": "e6bc305f912fc8fc1e733215728491f83d594bd4",
          "md5": "935272aedc89d60202c3ad87a167495a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iosx64-86ec4d6-metadata.jar",
          "url": "test-utils-resourceloader-iosx64-86ec4d6-metadata.jar",
          "size": 261,
          "sha512": "13708f542c5b79a148a40fca18f289996a427c61648335d51bd51bd1deef421f0732c39477918e0b0f9f1f1999340d73deda0d191f6ac5c57f0072edee280a1b",
          "sha256": "21d91f8bbb638b5b4278d223f77fef126d280aa3ed5bd2411ee9488feb4a9cb1",
          "sha1": "1a0054cb7f61424885277a6a2465cf536d797292",
          "md5": "6821bf94ed2b49cb8a519b9e587a52fe"
        }
      ]
    }
  ]
}
