{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "e146a41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-e146a41.jar",
          "url": "antibytes-gradle-utils-e146a41.jar",
          "size": 9471,
          "sha512": "b140db2041d14ec32d2a4831822ee892434345140d609906f002f68a2504cb8e46ad5cbc46c929255faa2305b8bb4d78c0f0da509c1c4ea5c25d6e8638b622e2",
          "sha256": "2137f6eec4bc4dac82c2458846079bb486518490bac2c89e737122e83572cb0b",
          "sha1": "e158739ec73de7447310fddf3091ad6dc56f9445",
          "md5": "a0ea4382947ca60d4c6a24defd66754a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-e146a41.jar",
          "url": "antibytes-gradle-utils-e146a41.jar",
          "size": 9471,
          "sha512": "b140db2041d14ec32d2a4831822ee892434345140d609906f002f68a2504cb8e46ad5cbc46c929255faa2305b8bb4d78c0f0da509c1c4ea5c25d6e8638b622e2",
          "sha256": "2137f6eec4bc4dac82c2458846079bb486518490bac2c89e737122e83572cb0b",
          "sha1": "e158739ec73de7447310fddf3091ad6dc56f9445",
          "md5": "a0ea4382947ca60d4c6a24defd66754a"
        }
      ]
    }
  ]
}
