{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.2.0-SNAPSHOT.jar",
          "url": "kmock-processor-0.2.0-SNAPSHOT.jar",
          "size": 356037,
          "sha512": "f18e1f811e1ff556a9a164a3c3b911016767ebc95f4653bb4eeec2f941f3a24bf2a48091d9d786e8b04962fcd22c566bdd660c7c37b202b5814dc46743e25754",
          "sha256": "7f406e203f3eb512fc660bb5f54182fa19e491fd2f91b8f6576e40e702d175ca",
          "sha1": "6595074d8ac973b70258a3400f77281f3c6b8c29",
          "md5": "a2e02e4d5bb7f017b6c5fa1c1f656165"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.2.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.2.0-SNAPSHOT.jar",
          "url": "kmock-processor-0.2.0-SNAPSHOT.jar",
          "size": 356037,
          "sha512": "f18e1f811e1ff556a9a164a3c3b911016767ebc95f4653bb4eeec2f941f3a24bf2a48091d9d786e8b04962fcd22c566bdd660c7c37b202b5814dc46743e25754",
          "sha256": "7f406e203f3eb512fc660bb5f54182fa19e491fd2f91b8f6576e40e702d175ca",
          "sha1": "6595074d8ac973b70258a3400f77281f3c6b8c29",
          "md5": "a2e02e4d5bb7f017b6c5fa1c1f656165"
        }
      ]
    }
  ]
}
