{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/5318a03/test-utils-5318a03.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "5318a03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-5318a03.jar",
          "size": 8776,
          "sha512": "df3d480c472bcd965895c7d7f87f90f3325743b2169b97e04803625c9fab61208189489ef14370c3afc6f3a46d55136ceeef112114c00012f86edc790d2dc33d",
          "sha256": "027bc528a6f317fd7cf2bb1f82fa2124f1e85158ae85b879b8a60000d6e8910d",
          "sha1": "c3f777d872b12aacb2e29a80581dfebc82f0b5ab",
          "md5": "12aea15eec8a42873a4db668ab252a6f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-5318a03.jar",
          "size": 8776,
          "sha512": "df3d480c472bcd965895c7d7f87f90f3325743b2169b97e04803625c9fab61208189489ef14370c3afc6f3a46d55136ceeef112114c00012f86edc790d2dc33d",
          "sha256": "027bc528a6f317fd7cf2bb1f82fa2124f1e85158ae85b879b8a60000d6e8910d",
          "sha1": "c3f777d872b12aacb2e29a80581dfebc82f0b5ab",
          "md5": "12aea15eec8a42873a4db668ab252a6f"
        }
      ]
    }
  ]
}
