{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.publishing",
    "module": "antibytes-publishing",
    "version": "65d8995",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "65d8995"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-65d8995.jar",
          "url": "antibytes-publishing-65d8995.jar",
          "size": 130790,
          "sha512": "b93bb3229c5648a5d4c632a931ce768266ea104d6022160be59bccdb7d1cb5b5e8d3ea24ed0b5caf92d76af075679a59e2aea4c2747c1c0146bba25957ea73a9",
          "sha256": "a8e47647511204a281a62e7f1984869260936618d4317e573d6be5dee537e53a",
          "sha1": "77e7c835e936d3f1940f1cbb2bc17ef80647de83",
          "md5": "b4ca1a46d7cabfed2a2081bdf37e7409"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.3.0.202209071007-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "65d8995"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "65d8995"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-65d8995.jar",
          "url": "antibytes-publishing-65d8995.jar",
          "size": 130790,
          "sha512": "b93bb3229c5648a5d4c632a931ce768266ea104d6022160be59bccdb7d1cb5b5e8d3ea24ed0b5caf92d76af075679a59e2aea4c2747c1c0146bba25957ea73a9",
          "sha256": "a8e47647511204a281a62e7f1984869260936618d4317e573d6be5dee537e53a",
          "sha1": "77e7c835e936d3f1940f1cbb2bc17ef80647de83",
          "md5": "b4ca1a46d7cabfed2a2081bdf37e7409"
        }
      ]
    }
  ]
}
