{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "1e6584f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "1e6584f"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-1e6584f.jar",
          "url": "antibytes-mkdocs-1e6584f.jar",
          "size": 12083,
          "sha512": "1b44de9d42217a8d40fc85ce2a0500974b495c9dabd42f1d0c975e3b7dbd019649cf3f45648bb8a96d6109938ee6c73c986ede4bae1c778ada425a8a4fd9fb58",
          "sha256": "ff4793a9ef8739e667bed010f6778dd094c3d4800b1b352bf3fcf8f5a677b6c1",
          "sha1": "090fc354e190b6ccfe634c618d6479822b41adb1",
          "md5": "2249c45c91f7126231605181a435aa22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "1e6584f"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "1e6584f"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-1e6584f.jar",
          "url": "antibytes-mkdocs-1e6584f.jar",
          "size": 12083,
          "sha512": "1b44de9d42217a8d40fc85ce2a0500974b495c9dabd42f1d0c975e3b7dbd019649cf3f45648bb8a96d6109938ee6c73c986ede4bae1c778ada425a8a4fd9fb58",
          "sha256": "ff4793a9ef8739e667bed010f6778dd094c3d4800b1b352bf3fcf8f5a677b6c1",
          "sha1": "090fc354e190b6ccfe634c618d6479822b41adb1",
          "md5": "2249c45c91f7126231605181a435aa22"
        }
      ]
    }
  ]
}
