{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.publishing",
    "module": "antibytes-publishing",
    "version": "0638349",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "0638349"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-0638349.jar",
          "url": "antibytes-publishing-0638349.jar",
          "size": 136063,
          "sha512": "e955676aead20c261ef05345078edbe7711661efeae31be0f1bb5d318e63d64a55ef85654015ff16a24c9cf60b36f6695119a48cded8b0eb004dca75b7be7b47",
          "sha256": "42ab34c16d432a7ee36d90595dc6055db7993dda616096c77c4fff6e565b50cb",
          "sha1": "ff9ec29d4634f2c8243bc3a3bd38f3a44991dd90",
          "md5": "5c91b0fa9450796ae50b93c47b633184"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.3.0.202209071007-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "0638349"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "0638349"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-0638349.jar",
          "url": "antibytes-publishing-0638349.jar",
          "size": 136063,
          "sha512": "e955676aead20c261ef05345078edbe7711661efeae31be0f1bb5d318e63d64a55ef85654015ff16a24c9cf60b36f6695119a48cded8b0eb004dca75b7be7b47",
          "sha256": "42ab34c16d432a7ee36d90595dc6055db7993dda616096c77c4fff6e565b50cb",
          "sha1": "ff9ec29d4634f2c8243bc3a3bd38f3a44991dd90",
          "md5": "5c91b0fa9450796ae50b93c47b633184"
        }
      ]
    }
  ]
}
