{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/7c33147/fixture-7c33147.module",
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "7c33147",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture.klib",
          "url": "fixture-iossimulatorarm64-7c33147.klib",
          "size": 49037,
          "sha512": "fa09f73ca660e48aa2f5748dd983b034cc01513701318f620f4ace477d45e277f3bb4eb28b64bf86e8b843b0fc8cf39595d9b2d315917c355ab3d43c6d4a66ba",
          "sha256": "fe3d4e2faeb1c560903343f568d74f9497969d4150b222020c4d674ee6eab908",
          "sha1": "664dab0e431b766deacc5259679cd198f7a5dbe5",
          "md5": "d6f9fab68ac6c681f3b6012bc14fd990"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-iossimulatorarm64-7c33147-metadata.jar",
          "url": "fixture-iossimulatorarm64-7c33147-metadata.jar",
          "size": 261,
          "sha512": "60329f636ea4978573e6659fd61911b9ebf7655ea5ebfa1933b9b5535dce5b6c1545a8374f4bc8213658e2214e973a3830d131e544bb2ecbe5260368776c5d34",
          "sha256": "061bed1903140d029612aabc6dec9ef8bb655799e48cef024b63bd884121006a",
          "sha1": "22303e58499495b0d16810c07919caabeff3ef15",
          "md5": "977d043cf17752249ff304e2af3dddff"
        }
      ]
    }
  ]
}
