{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01-SNAPSHOT/kmock-0.3.0-rc01-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iossimulatorarm64-0.3.0-rc01-SNAPSHOT.klib",
          "size": 202924,
          "sha512": "a3c7fb41fd5a044e3b65a768aa226a2359e2a1e830fdc07f001e399cd8685fc9efecfa9fc01098d938c861cfd95bd8e69ca1d131b42842e1ae3f7e58b6e42778",
          "sha256": "a9914f7acdcd8ce3c68e1fba0a901e73a8f2b9dd1488c0b9901386de489bc94b",
          "sha1": "70bd7022cd54cbe1d0ac3ecc06797be299bb6652",
          "md5": "6727871b0342fcc2ca3285f59a46cd6e"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iossimulatorarm64-0.3.0-rc01-SNAPSHOT-metadata.jar",
          "url": "kmock-iossimulatorarm64-0.3.0-rc01-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "dc223c0d1bc05faf92973e6a435739e2d950991ad9dab36a30e41d9e58a0521bad352fe1a2550f9953b9ead66649d83baf70906f593697e0757f0b5962db43d1",
          "sha256": "887b56098b80e4996cf63bb5fd7ba136a20020682d83f37730608bdaf2a29246",
          "sha1": "a3ce8170a64ea43920c8b0e28e29de81de02b7bd",
          "md5": "b78768720d5e20eb7d369f21dce8e5b7"
        }
      ]
    }
  ]
}
