{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "78b7bfc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "78b7bfc"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-78b7bfc.jar",
          "url": "antibytes-mkdocs-78b7bfc.jar",
          "size": 12151,
          "sha512": "e80443d47b807ef5461c1ff305a185470112fc0facff7a0ebf885020166c28962620b6f52c1c362136fa9a1525aa83d816fb6ae6cfced8910f074576d9462b53",
          "sha256": "a1dd2533db134a2dbf339a3fd05abbd7ce26f4a36c69a3b9ae43c9a32703fd8c",
          "sha1": "b532261b60848692547769305f8f097db5e39f95",
          "md5": "f5f9e65539d5281570e2fc7589b3119c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "78b7bfc"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "78b7bfc"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-78b7bfc.jar",
          "url": "antibytes-mkdocs-78b7bfc.jar",
          "size": 12151,
          "sha512": "e80443d47b807ef5461c1ff305a185470112fc0facff7a0ebf885020166c28962620b6f52c1c362136fa9a1525aa83d816fb6ae6cfced8910f074576d9462b53",
          "sha256": "a1dd2533db134a2dbf339a3fd05abbd7ce26f4a36c69a3b9ae43c9a32703fd8c",
          "sha1": "b532261b60848692547769305f8f097db5e39f95",
          "md5": "f5f9e65539d5281570e2fc7589b3119c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-mkdocs-78b7bfc-javadoc.jar",
          "url": "antibytes-mkdocs-78b7bfc-javadoc.jar",
          "size": 261,
          "sha512": "501201928457cf7e3300cb0d8f54d94983e9946964aa3adeb60caa4515320eecda065a4edd332feca00fce3e65d3a7ce8b7b26abd14c3ef596dc87865ce8e3a7",
          "sha256": "970ab8b65ada31e827079b16e06dd496dffe387aab3f929666cb779954febd4f",
          "sha1": "71cf8fa32817b5c32d7291655d7576972f775bf3",
          "md5": "6705a7d3f13e609b459eba327e8c59a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-mkdocs-78b7bfc-sources.jar",
          "url": "antibytes-mkdocs-78b7bfc-sources.jar",
          "size": 3210,
          "sha512": "6d544ff7a9296d98466c6e0edbce237cdd0e10a1ebf7c7b3f55e07c055a3e4c0d370cef3743e597e5a9a32e0dd67d3ea337797e2831c3219d4af4182877e314d",
          "sha256": "e5f659e51e5f2c68e3370fd2eaddba1f80997adb258d16daecba7a2f635208d0",
          "sha1": "32692250401026345287b615e60fd5bc9d4f8eaa",
          "md5": "b986e699b90e80f31dea594674eb9c0b"
        }
      ]
    }
  ]
}
