{
  "formatVersion": "1.1",
  "component": {
    "url": "../../banana-i18n/069d073/banana-i18n-069d073.module",
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "069d073",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "banana-i18n-release.aar",
          "url": "banana-i18n-android-069d073.aar",
          "size": 51381,
          "sha512": "6b21e55678932b8dff9296eea1edfea9320d8b85eb46c8c24a07b8fe572b6092897589f80aee1f6d949f11b2a6e6a6e8c167b495882aba806028dcb7768d1a0a",
          "sha256": "7f7d61af221160af8074050134c06ae600bd00acdaf258297a7fc583aac91160",
          "sha1": "53c1a097110cccf8f801dbda4868056d81787644",
          "md5": "135a07aad9d710e4d82637dabbe26bb8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "banana-i18n-release.aar",
          "url": "banana-i18n-android-069d073.aar",
          "size": 51381,
          "sha512": "6b21e55678932b8dff9296eea1edfea9320d8b85eb46c8c24a07b8fe572b6092897589f80aee1f6d949f11b2a6e6a6e8c167b495882aba806028dcb7768d1a0a",
          "sha256": "7f7d61af221160af8074050134c06ae600bd00acdaf258297a7fc583aac91160",
          "sha1": "53c1a097110cccf8f801dbda4868056d81787644",
          "md5": "135a07aad9d710e4d82637dabbe26bb8"
        }
      ]
    }
  ]
}
