{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "bf076e1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "bf076e1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-bf076e1.jar",
          "url": "antibytes-mkdocs-bf076e1.jar",
          "size": 12083,
          "sha512": "f6fb953f39737c6aa1e78b8a283f6250ba1d655fbbdd2adf306838326bf0741727db8196971c47600c9f51ce90845e6fb06d4316bc7b168312ea37a7c83e2850",
          "sha256": "b824c341fccd83f549c94a0899812528b3fca895f8c0d144af7174d9ae03b751",
          "sha1": "55e7d06585b56f9c06cee4c8a63cc30d413f6c1e",
          "md5": "8e6c7b0609ec3871511a666637e96793"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "bf076e1"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "bf076e1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-bf076e1.jar",
          "url": "antibytes-mkdocs-bf076e1.jar",
          "size": 12083,
          "sha512": "f6fb953f39737c6aa1e78b8a283f6250ba1d655fbbdd2adf306838326bf0741727db8196971c47600c9f51ce90845e6fb06d4316bc7b168312ea37a7c83e2850",
          "sha256": "b824c341fccd83f549c94a0899812528b3fca895f8c0d144af7174d9ae03b751",
          "sha1": "55e7d06585b56f9c06cee4c8a63cc30d413f6c1e",
          "md5": "8e6c7b0609ec3871511a666637e96793"
        }
      ]
    }
  ]
}
