{
  "formatVersion": "1.1",
  "component": {
    "url": "../../banana-i18n/d0078d3/banana-i18n-d0078d3.module",
    "group": "tech.antibytes",
    "module": "banana-i18n",
    "version": "d0078d3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-d0078d3.jar",
          "size": 29419,
          "sha512": "0866753904bb950ec5811e241211948d576296896ec543bca80c9ea31316f20f29c8a178ffd2b23f60ace89e4999fbdca91c21c2dd6174a6fcaef13f64e4b96a",
          "sha256": "ecc3e049dbe4d651e30ac0328f01ffce7c2999e4aee701fe820e49d9198be68a",
          "sha1": "a89b24f529549c59cc147eca5179d404773f4ad6",
          "md5": "f3b8689e98c5a0abd4f74a760e5680ff"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-d0078d3.jar",
          "size": 29419,
          "sha512": "0866753904bb950ec5811e241211948d576296896ec543bca80c9ea31316f20f29c8a178ffd2b23f60ace89e4999fbdca91c21c2dd6174a6fcaef13f64e4b96a",
          "sha256": "ecc3e049dbe4d651e30ac0328f01ffce7c2999e4aee701fe820e49d9198be68a",
          "sha1": "a89b24f529549c59cc147eca5179d404773f4ad6",
          "md5": "f3b8689e98c5a0abd4f74a760e5680ff"
        }
      ]
    }
  ]
}
