{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "f6a864b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-f6a864b.jar",
          "url": "antibytes-custom-component-f6a864b.jar",
          "size": 16534,
          "sha512": "cbd7d6276d2bbc3ab42592f96bc48b695d5c23ff26f0d5a72a20c791e25fca84050c6161f71a48803ebcf7966f8419450295077eb8ffafe564e2df30a7e58761",
          "sha256": "a4f7df7f72c958e1b0c27ef6e4be9069194f1b76863b6466418da450d7bed9f9",
          "sha1": "964e82d2e878f76662a78d9d27c4dee5fbb2cce2",
          "md5": "1c32db13c27dbcd6c0f2015a8e0a7182"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-f6a864b.jar",
          "url": "antibytes-custom-component-f6a864b.jar",
          "size": 16534,
          "sha512": "cbd7d6276d2bbc3ab42592f96bc48b695d5c23ff26f0d5a72a20c791e25fca84050c6161f71a48803ebcf7966f8419450295077eb8ffafe564e2df30a7e58761",
          "sha256": "a4f7df7f72c958e1b0c27ef6e4be9069194f1b76863b6466418da450d7bed9f9",
          "sha1": "964e82d2e878f76662a78d9d27c4dee5fbb2cce2",
          "md5": "1c32db13c27dbcd6c0f2015a8e0a7182"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-custom-component-f6a864b-javadoc.jar",
          "url": "antibytes-custom-component-f6a864b-javadoc.jar",
          "size": 261,
          "sha512": "2fa68d19a5791168de061d6892fa9a6e0b555d379388e329fb591d66bb0e65c741bf038274429535ab3398f0c515f1d05b10845e6fa1f4c39335aac9cb0ec9d3",
          "sha256": "d5fd87bb3902a2f78934d7e51f4feb7256b61db26c5a6aa71e40f08de8b87f96",
          "sha1": "21db0a2a2de975a6d9d468510a8931f49195c527",
          "md5": "e6578cde71807b6d27eda151c0dc8a78"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-custom-component-f6a864b-sources.jar",
          "url": "antibytes-custom-component-f6a864b-sources.jar",
          "size": 3352,
          "sha512": "5595a23d78ffcb559d163fa50781fa30a5e4f4e977f9047c196a961707a33fed143f79f45c8397cf141fcaaefcc2cd5ed3bd0c68187c057832c941590a54fadf",
          "sha256": "c14060873412339073cd0938788433d8db36d632a322f6b4c4792fa3229e79aa",
          "sha1": "dd80e2bb450d34f67bae957986437a838aa79994",
          "md5": "d81c9f50f6f2c647b16fe68ea6a28cb7"
        }
      ]
    }
  ]
}
