{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-bridge",
    "version": "65d8995",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-bridge-65d8995.jar",
          "url": "antibytes-dependency-bridge-65d8995.jar",
          "size": 38501,
          "sha512": "8b2be7e7c4e0099253b8e14529582c444669704c4c5fd968ddbc808199e94e7a54103f29d1ad5e485f6e99c3ba479fed13483f5b83081001fdbf5cf56ae381b1",
          "sha256": "8060ae3697f0199e4640126eb78a2bac78a503f34ffe4cfd9acb213674a34034",
          "sha1": "a686a20e526b74090097a3433fb237b86a56d161",
          "md5": "684bdfb204c5fd1e8019ec19cd23fad0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-bridge-65d8995.jar",
          "url": "antibytes-dependency-bridge-65d8995.jar",
          "size": 38501,
          "sha512": "8b2be7e7c4e0099253b8e14529582c444669704c4c5fd968ddbc808199e94e7a54103f29d1ad5e485f6e99c3ba479fed13483f5b83081001fdbf5cf56ae381b1",
          "sha256": "8060ae3697f0199e4640126eb78a2bac78a503f34ffe4cfd9acb213674a34034",
          "sha1": "a686a20e526b74090097a3433fb237b86a56d161",
          "md5": "684bdfb204c5fd1e8019ec19cd23fad0"
        }
      ]
    }
  ]
}
