{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/5238ed6/test-utils-5238ed6.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "5238ed6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-5238ed6.klib",
          "url": "test-utils-js-5238ed6.klib",
          "size": 12083,
          "sha512": "e09ef464825ab2b99a15b1582197aa413ae2b694eca6fa0e9ed410c09391657f8895f3a0ce4bf84ed5a80dcb9521b52f6c2438b825cab3c036e46941033ffa8c",
          "sha256": "66306f429e8e51ca69fb966191591f9d08590fcee6186c59f0c314f35e257369",
          "sha1": "5393f6a2d572091944d9b38ca15826b6e7256f66",
          "md5": "1ef0d92a398741857f6e628aa6ea44eb"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-5238ed6.klib",
          "url": "test-utils-js-5238ed6.klib",
          "size": 12083,
          "sha512": "e09ef464825ab2b99a15b1582197aa413ae2b694eca6fa0e9ed410c09391657f8895f3a0ce4bf84ed5a80dcb9521b52f6c2438b825cab3c036e46941033ffa8c",
          "sha256": "66306f429e8e51ca69fb966191591f9d08590fcee6186c59f0c314f35e257369",
          "sha1": "5393f6a2d572091944d9b38ca15826b6e7256f66",
          "md5": "1ef0d92a398741857f6e628aa6ea44eb"
        }
      ]
    }
  ]
}
