{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/8c5f468/test-utils-coroutine-8c5f468.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "8c5f468",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-8c5f468.klib",
          "url": "test-utils-coroutine-js-8c5f468.klib",
          "size": 10181,
          "sha512": "b0ba2f8d3a4708aa9723e2c3fa4f6faf799e666d38d6787aa6d78f7da64ea054df7729bacae2dc14128f79ec73c56a292070188fb73c6cb7cb556d560e4724d2",
          "sha256": "202d3732f6f6a5af57beb27d95230f916dc4e84888b9bb0864e65755bbff644f",
          "sha1": "20435b23c9b4f8a5cb8aff39cbc7285e739db571",
          "md5": "dcc80479c156b4ea64df191a78b99a20"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-8c5f468.klib",
          "url": "test-utils-coroutine-js-8c5f468.klib",
          "size": 10181,
          "sha512": "b0ba2f8d3a4708aa9723e2c3fa4f6faf799e666d38d6787aa6d78f7da64ea054df7729bacae2dc14128f79ec73c56a292070188fb73c6cb7cb556d560e4724d2",
          "sha256": "202d3732f6f6a5af57beb27d95230f916dc4e84888b9bb0864e65755bbff644f",
          "sha1": "20435b23c9b4f8a5cb8aff39cbc7285e739db571",
          "md5": "dcc80479c156b4ea64df191a78b99a20"
        }
      ]
    }
  ]
}
