{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/fc88d6a/test-utils-coroutine-fc88d6a.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "fc88d6a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-watchossimulatorarm64-fc88d6a.klib",
          "size": 10251,
          "sha512": "2677ddc6bf842f9e9a0e6730316aaefeb3b29b615e177fca6f9ae76409226749de4da390e0a869bb6527438e09868552e2a1efee35ff6f97586309ec9ae2a360",
          "sha256": "b0b6961753bd92f9eb1b6d6dc9d8ee017f11bf9f49ab2c6df541de4acc5586ed",
          "sha1": "3459a407654355b2fe5ec7bba6916b60ddeb30d6",
          "md5": "e56ef68d99d3d9c8272d8e2dcba8d6b6"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-watchossimulatorarm64-fc88d6a-metadata.jar",
          "url": "test-utils-coroutine-watchossimulatorarm64-fc88d6a-metadata.jar",
          "size": 261,
          "sha512": "9dfdd5ae947caaa09e2a3362cda6d7089929e73a03c339d3bdfcac4dcbc3a3a5beb6f1a8a481fa3e89b31f4efd88596eb188a3eea24ccb6aae83a9d39c349827",
          "sha256": "a99e77b85e0983bf06b52f4e3c68d19e7f534a521abe39e65506a94ce93fc30e",
          "sha1": "8a1b8bab5520cdcbefb4f8ec1c27e956e0bc378b",
          "md5": "c67532b7922562d6c7f76f8ee80096da"
        }
      ]
    }
  ]
}
