{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-catalog",
    "version": "3a72bda",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-3a72bda.toml",
          "url": "antibytes-dependency-catalog-3a72bda.toml",
          "size": 228942,
          "sha512": "ce9a6e004d3aeaa7b96fa41a74e6ddd86444c736b6af6dd0e9b5f0ae653d5a30e50290371750e2f2c6b8926c6dad2da838c297657a12ba7cf5ef7819b909046f",
          "sha256": "2384f495f4a724388ab6a88a60103f82fb332b7785c6a8692644a646988a05da",
          "sha1": "5caf4a46cbe0e288fdaf44817172420f1b1d0ce6",
          "md5": "419f5bd740027f7a4a1942027cca7cfd"
        }
      ]
    }
  ]
}
