{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/b9030f2/test-utils-annotations-junit4-b9030f2.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "b9030f2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-macosarm64-b9030f2.klib",
          "size": 11721,
          "sha512": "d59468c3192e0a8200f7a6f534bd42b6f879af34946fb4fdd58ab00d708a1e6fe6d14dcc493a011612ec1a94490ff87cdfdae7082cb880b8c7f54fb72ae5b245",
          "sha256": "a62367bdc2cbf724c113e2d143029549359c33b3c247b33d06bd3621003fc89f",
          "sha1": "d6cabbd8c9ac04af0b3cf6df94840ddfeb27c71f",
          "md5": "8a86ea76deaa1bd84096c81934c29b09"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-annotations-junit4-macosarm64-b9030f2-sources.jar",
          "url": "test-utils-annotations-junit4-macosarm64-b9030f2-sources.jar",
          "size": 4896,
          "sha512": "2fe566b164f18a378d2c2daef090e149e0410a28bce2fd8eb67e9c81f2f2829b88cd4d3144e475fd0e8bd4d1e875624f6a42181ca5c272ee8cb3c5120df576b8",
          "sha256": "ce6588d8cdfe151428ad5243f3789335be34b41a39afba73df51f6509fb505d9",
          "sha1": "b969be4de0cad713d3e23159129ccc7f8256d550",
          "md5": "7378c76f616bc582b49cf2cf7b9d2f0a"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-macosarm64-b9030f2-metadata.jar",
          "url": "test-utils-annotations-junit4-macosarm64-b9030f2-metadata.jar",
          "size": 261,
          "sha512": "0e07c865cd9fc2d2fef75dfcce244d4567b73f0482d61d409ddd8e732d10388ce3fefc22a2bbc13bd0a9b576714d0061917d62d4abf2171772cf7563d23cad9f",
          "sha256": "dec869e4887d7bffd7bc6bc025c76cbabc96360d610ca202cff46ab4c41868fa",
          "sha1": "702fbdf550a033f30cc911ea3f2e43c1e4f899b2",
          "md5": "0d04129882fa5434d1396266745acce9"
        }
      ]
    }
  ]
}
