{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/eb1dade/kmock-eb1dade.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "eb1dade",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-eb1dade.jar",
          "url": "kmock-jvm-eb1dade.jar",
          "size": 197355,
          "sha512": "375fb53f5282576000bdf94366208ff40e138731481019802e8e9f8b3f4dbd78b038a07ac4b66bf13e980dc3ad0ab7902ee71a20649e6241bdf63c5be9e03f52",
          "sha256": "1b4c6440b335cf78b2e22170fa2c3ff214cc57338f8b7ae73460c9a9afb12f89",
          "sha1": "8e71743efe2c15009c578d487a546d739842229e",
          "md5": "fa6f6f4b4d1d19e88e51311fb81a730f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-eb1dade.jar",
          "url": "kmock-jvm-eb1dade.jar",
          "size": 197355,
          "sha512": "375fb53f5282576000bdf94366208ff40e138731481019802e8e9f8b3f4dbd78b038a07ac4b66bf13e980dc3ad0ab7902ee71a20649e6241bdf63c5be9e03f52",
          "sha256": "1b4c6440b335cf78b2e22170fa2c3ff214cc57338f8b7ae73460c9a9afb12f89",
          "sha1": "8e71743efe2c15009c578d487a546d739842229e",
          "md5": "fa6f6f4b4d1d19e88e51311fb81a730f"
        }
      ]
    }
  ]
}
