{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-quality",
    "version": "b12f9e2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-quality-b12f9e2.jar",
          "url": "antibytes-quality-b12f9e2.jar",
          "size": 62593,
          "sha512": "1d53e6377c8218f9744a06074548f31e2b9e8905f86003d996c779f331563f176a283cf43f54a7af2692b2f0779554652aa4cbf1d64bbe35f072781dda468c05",
          "sha256": "6325ae8e70288773c6d0212e4b2fd64a76e5ebbcbb53c3347ab4ffa9bad20fb3",
          "sha1": "409365b2306233716ba681f6c1763d9d1c5f6f08",
          "md5": "c9e84b28f5f71b271d6809a52662afb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.21.0"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "b12f9e2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-dependency-helper",
          "version": {
            "requires": "b12f9e2"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-b12f9e2.jar",
          "url": "antibytes-quality-b12f9e2.jar",
          "size": 62593,
          "sha512": "1d53e6377c8218f9744a06074548f31e2b9e8905f86003d996c779f331563f176a283cf43f54a7af2692b2f0779554652aa4cbf1d64bbe35f072781dda468c05",
          "sha256": "6325ae8e70288773c6d0212e4b2fd64a76e5ebbcbb53c3347ab4ffa9bad20fb3",
          "sha1": "409365b2306233716ba681f6c1763d9d1c5f6f08",
          "md5": "c9e84b28f5f71b271d6809a52662afb2"
        }
      ]
    }
  ]
}
