{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "1887fc4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-1887fc4-all.jar",
          "url": "core-1887fc4-all.jar",
          "size": 14783,
          "sha512": "bd4e480c0f975bf15df9b03c85a34c5a5ef45e382aa2765a1eb1eb5708247cbf1e590d5cd40c057356585ace8f95d050dd388d75b37589a42a0e3ab4a4d85445",
          "sha256": "afd266e28dfd59ade48796ee514361868354cb44f02d122bfcd2b8e6defdef99",
          "sha1": "318903bf126ea6dc1ad0445317d7f1ce5737f51f",
          "md5": "422b22289c4f4aee94e08d4e34c789dc"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-1887fc4.jar",
          "url": "core-1887fc4.jar",
          "size": 20255,
          "sha512": "0687218ac7d4d631b316b0e9f48bcd5eddb07456fbfa91e0d8da8c4d0ea05f53ab08af6a7a4c4e478834cb0c83b09bd42c7d1929313696129f885315a7cfebe7",
          "sha256": "aa465acbec57bce18820decf12a08080f831777ea0579d3d44a293acbe177406",
          "sha1": "15c205dc6cdbe4d58b9ed5e223a8164db12d17ec",
          "md5": "68f0461182c56e0b746380ee76fd244c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1887fc4/core-android-1887fc4.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-android",
        "version": "1887fc4"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1887fc4/core-android-1887fc4.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-android",
        "version": "1887fc4"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/1887fc4/core-iosarm64-1887fc4.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosarm64",
        "version": "1887fc4"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/1887fc4/core-iosarm64-1887fc4.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosarm64",
        "version": "1887fc4"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/1887fc4/core-iossimulatorarm64-1887fc4.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iossimulatorarm64",
        "version": "1887fc4"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/1887fc4/core-iossimulatorarm64-1887fc4.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iossimulatorarm64",
        "version": "1887fc4"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/1887fc4/core-iosx64-1887fc4.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosx64",
        "version": "1887fc4"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/1887fc4/core-iosx64-1887fc4.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosx64",
        "version": "1887fc4"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/1887fc4/core-js-1887fc4.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-js",
        "version": "1887fc4"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/1887fc4/core-js-1887fc4.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-js",
        "version": "1887fc4"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/1887fc4/core-jvm-1887fc4.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-jvm",
        "version": "1887fc4"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/1887fc4/core-jvm-1887fc4.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-jvm",
        "version": "1887fc4"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-linuxx64/1887fc4/core-linuxx64-1887fc4.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-linuxx64",
        "version": "1887fc4"
      }
    }
  ]
}
