{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "601dc8e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-601dc8e.jar",
          "url": "antibytes-dependency-helper-601dc8e.jar",
          "size": 69703,
          "sha512": "01a15160976236a3a7d982ed3769c5c42c18e675bd5c744b4609768a64367b8ed7bb37d834d29401d959a52d65b34755a2c5c8525cf39fc03899df85e56db9d5",
          "sha256": "e718f5a5e0c37032e76d1f412c707b88c2c534b60a3f8de7db07037b44908c27",
          "sha1": "677410d0eaf3672015f08da70bd0605fe3c67d2e",
          "md5": "2d04c3a5c2b7d7b6035ad53ed20e3197"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.51.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "9.0.9"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "601dc8e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-601dc8e.jar",
          "url": "antibytes-dependency-helper-601dc8e.jar",
          "size": 69703,
          "sha512": "01a15160976236a3a7d982ed3769c5c42c18e675bd5c744b4609768a64367b8ed7bb37d834d29401d959a52d65b34755a2c5c8525cf39fc03899df85e56db9d5",
          "sha256": "e718f5a5e0c37032e76d1f412c707b88c2c534b60a3f8de7db07037b44908c27",
          "sha1": "677410d0eaf3672015f08da70bd0605fe3c67d2e",
          "md5": "2d04c3a5c2b7d7b6035ad53ed20e3197"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-601dc8e-javadoc.jar",
          "url": "antibytes-dependency-helper-601dc8e-javadoc.jar",
          "size": 261,
          "sha512": "fb991a8f219f43012456558d1244eb5478b2dd12c0a232bd3c19c1cc0a2615318ab87fbeacfc42dda7a59d1e2dfa3832a2dfc0616a123d876b3dd7031b057524",
          "sha256": "1fe9eda8e00e0366ffe2797d940fc0be82eeee572f3f8b4102994b9195c440c2",
          "sha1": "3112aeb42aec754e8ab9474f630564f5901eb855",
          "md5": "70474a95dc0e1fe54eb38a5a9e10aefa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-601dc8e-sources.jar",
          "url": "antibytes-dependency-helper-601dc8e-sources.jar",
          "size": 9186,
          "sha512": "ac5000a48f4f19964091cc8e6bfa009ba84e0cb8cb8e5cb34007a41626b77f3b4804885504b4704aa0409ce6aca75f2fd10570bee1c1be60d62c7a38007edce6",
          "sha256": "4c45d0cec1d30ffc10ca07b183b868b503f9198c2c9f216ff448a926983f90a7",
          "sha1": "213912fb3ba63fe75382353df18781eb7c9e8e86",
          "md5": "5eaae6389f62c874eeb7297db21d21a6"
        }
      ]
    }
  ]
}
