{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc07-SNAPSHOT/kmock-0.3.0-rc07-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc07-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-watchosx86-0.3.0-rc07-SNAPSHOT.klib",
          "size": 203034,
          "sha512": "fcfb22e1fed7e27d2e8fe76a6ac7b88b6f1f91f3ea9da3cbf793c74ed6604b873b7eee29da428f1d540d6271a4b1b1cfbce55034f62e6d17b0d139ac7cf653f7",
          "sha256": "3c150aafd42291f27bb10329ca3afd6a0a9510837af193d76674a82e3b53c9ad",
          "sha1": "eebbb058f99da6c1d410831392040e6a51f06a7f",
          "md5": "47a3e75ba22177dce6d24b793df7a1bd"
        }
      ]
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-watchosx86-0.3.0-rc07-SNAPSHOT-metadata.jar",
          "url": "kmock-watchosx86-0.3.0-rc07-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "766018c0ae8cdf881f30b154f638c82095941e5b7d6cdd066d28cca5dca6d5553cc9a1c94b257bdf170eb74269a8ce1fe6dac09d5bc5b80df899967116a233fd",
          "sha256": "8da109fba713948f8ac18f2d14f8fbce780fd0bd14c4f38d9912cb89487caec3",
          "sha1": "3e4309c9d4439f7b31d934b60371b303b48f7dd2",
          "md5": "75d4256a2bf040df5dadfab6103f3bd2"
        }
      ]
    }
  ]
}
