{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/b0f1bff/test-utils-annotations-b0f1bff.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "b0f1bff",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-b0f1bff.klib",
          "url": "test-utils-annotations-js-b0f1bff.klib",
          "size": 9629,
          "sha512": "8c71276d3b2427c022dc73a95efba4cc930dafd9d7c6a280e893e93fe04c602edc4550522e617d9d165e72abee74ca90060f1fb9b203380099d3362acfb7dafb",
          "sha256": "8905454877ecb355bdef02def18cedab2465983fa93b40e2f203ff9cdee8a615",
          "sha1": "16deff2a1b6d1ceb5196dc1c20c9d2effd60076a",
          "md5": "aaaa581d63e243ed7d32545979a37946"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-b0f1bff.klib",
          "url": "test-utils-annotations-js-b0f1bff.klib",
          "size": 9629,
          "sha512": "8c71276d3b2427c022dc73a95efba4cc930dafd9d7c6a280e893e93fe04c602edc4550522e617d9d165e72abee74ca90060f1fb9b203380099d3362acfb7dafb",
          "sha256": "8905454877ecb355bdef02def18cedab2465983fa93b40e2f203ff9cdee8a615",
          "sha1": "16deff2a1b6d1ceb5196dc1c20c9d2effd60076a",
          "md5": "aaaa581d63e243ed7d32545979a37946"
        }
      ]
    }
  ]
}
