{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "2d16671",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-2d16671.jar",
          "url": "antibytes-custom-component-2d16671.jar",
          "size": 16534,
          "sha512": "faae6259d25cc4af2529119f668178059dfdcf5ba51f695d4301a1b468a0ef134b1535bfcbdfd90f1c273384594b46753c4217df275e145cf25a33cbf8a382df",
          "sha256": "e1bf8312ba0fd0266aaac6ecc7aedf721558a9c033823bfb754a7cb7b72ca6fc",
          "sha1": "afb954ceedbb69387288604595b5dc1420938fb8",
          "md5": "aeaefbb2a32b8758381fead989d0e797"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-2d16671.jar",
          "url": "antibytes-custom-component-2d16671.jar",
          "size": 16534,
          "sha512": "faae6259d25cc4af2529119f668178059dfdcf5ba51f695d4301a1b468a0ef134b1535bfcbdfd90f1c273384594b46753c4217df275e145cf25a33cbf8a382df",
          "sha256": "e1bf8312ba0fd0266aaac6ecc7aedf721558a9c033823bfb754a7cb7b72ca6fc",
          "sha1": "afb954ceedbb69387288604595b5dc1420938fb8",
          "md5": "aeaefbb2a32b8758381fead989d0e797"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-custom-component-2d16671-javadoc.jar",
          "url": "antibytes-custom-component-2d16671-javadoc.jar",
          "size": 261,
          "sha512": "cb530bb979660518d0cce7388f6d0af3833c67b274af82e37fc72dbb3259b93d740cf69311d488e0640fcff4b835591db81387aa1fba5b8546e65c2d47c15894",
          "sha256": "042d16b909b7590c773683ccfcce68d5cd791f783dc8d33b45799fc8f2364d4c",
          "sha1": "b213770a4f6e296888f677ee1430220997d1875f",
          "md5": "90d090b2f959a3d23e6ce6088f66a25b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-custom-component-2d16671-sources.jar",
          "url": "antibytes-custom-component-2d16671-sources.jar",
          "size": 3352,
          "sha512": "b217ef323c731ae67075df0665d4925881d475dc0fb3e9310e7e204edb096dea49b488777e57598973c97f2d8e5276ea7619d168eb0e5e23fccdc76e9227fffa",
          "sha256": "60b1991d2e56a5337dd76f8fd61a86efc4f8299a36166f6f969d1271c03b9c0b",
          "sha1": "aff3fe641b18faf7a016a3f7af18b6c95c63aa6d",
          "md5": "b19c728c940c7c25ecf5d6614a8fd618"
        }
      ]
    }
  ]
}
