{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "1e778fb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-1e778fb.jar",
          "url": "antibytes-gradle-test-utils-1e778fb.jar",
          "size": 16830,
          "sha512": "747d6486ffd647724c2443f30864defaaf31efbfd0d6d65e5a03cee20bda1b48452dbe801c6828564906a5f670c5caee3b9e8ccf9e73ead1d7143078043f7d2f",
          "sha256": "97c408ae7661b8f0564e7b98e287d90577b0d03ec7b8d5dd9882c6f2b585118d",
          "sha1": "e2cf256daf8770229b6924679efea314ba7a9849",
          "md5": "4692f840f14cd04682fdbed7aae39cd3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-1e778fb.jar",
          "url": "antibytes-gradle-test-utils-1e778fb.jar",
          "size": 16830,
          "sha512": "747d6486ffd647724c2443f30864defaaf31efbfd0d6d65e5a03cee20bda1b48452dbe801c6828564906a5f670c5caee3b9e8ccf9e73ead1d7143078043f7d2f",
          "sha256": "97c408ae7661b8f0564e7b98e287d90577b0d03ec7b8d5dd9882c6f2b585118d",
          "sha1": "e2cf256daf8770229b6924679efea314ba7a9849",
          "md5": "4692f840f14cd04682fdbed7aae39cd3"
        }
      ]
    }
  ]
}
