{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/b6c6e6c/test-utils-ktor-b6c6e6c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "b6c6e6c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.8"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iossimulatorarm64-b6c6e6c.klib",
          "size": 15587,
          "sha512": "8d51c2c771f4aef866080be7ace4e06014ede8501e87bc38def6240fdb515a7f760997b328d54e7ae6f0136a34df2c8c285c81b6dd859a425a2915214fce83cb",
          "sha256": "cfea4d332cb3684989902318f8a2b69cf461a11f75b1c656ddc9fccd9b9e8227",
          "sha1": "533f1a8bb7a68ab952c044efb86c0b8aa9e732e7",
          "md5": "7b95c1786b388cf39816b758e0bd4351"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-ktor-iossimulatorarm64-b6c6e6c-sources.jar",
          "url": "test-utils-ktor-iossimulatorarm64-b6c6e6c-sources.jar",
          "size": 2872,
          "sha512": "2268f2772929e73f6f4cccb0ebfc887c2fca1a9a7518d50c3a0cd6141b1615740b1bbe8f39f3ae9045c34e283023352c23e1943c8c39a58f65cc05243bf01a94",
          "sha256": "6d96d8b473fe6fa2ee93d7c4ac375d0570434c9ab65c01bae96d632733a9d562",
          "sha1": "95f77daf58aa6a77bf8927057cd070da7b9b3409",
          "md5": "2b46f609ce899dc78e54dabcd42dec8a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.8"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iossimulatorarm64-b6c6e6c-metadata.jar",
          "url": "test-utils-ktor-iossimulatorarm64-b6c6e6c-metadata.jar",
          "size": 261,
          "sha512": "6780e6879a142cd578e84cde7cb41da2ca05057b9b60513440108a5875ea2c823797783bdd155e73b89eeab8ab817aa233ebbf0e314d2e482cd189d7021d0d1b",
          "sha256": "0bf7dee894db02961ed1be2305688e9fc98d92221bf67d3eaae9620a79ade17d",
          "sha1": "3b08ae3127507b853525cca456de34fcddc23845",
          "md5": "f15bbc01ce81f8e85bf2dc4f47b63315"
        }
      ]
    }
  ]
}
