{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-mkdocs",
    "version": "ec7ea01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "ec7ea01"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-ec7ea01.jar",
          "url": "antibytes-mkdocs-ec7ea01.jar",
          "size": 11951,
          "sha512": "003857d1b356c4fa12a721db960bd10874f5bcf2f98b61ae115defdfc2ed4c17b76ca6c1fcafdc8fbb6833547724deb825859c62cca8b3a63e46097c4f875e44",
          "sha256": "69c4d5873a57e8ff93f0719dff7d90ae472c6f814bef8cb3da46ce9370083e86",
          "sha1": "3c557a80d0f48b0a8c13397889500479c6ffd445",
          "md5": "4b454ba377529e53a9cfc17cfd82a00f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "ec7ea01"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "ec7ea01"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-ec7ea01.jar",
          "url": "antibytes-mkdocs-ec7ea01.jar",
          "size": 11951,
          "sha512": "003857d1b356c4fa12a721db960bd10874f5bcf2f98b61ae115defdfc2ed4c17b76ca6c1fcafdc8fbb6833547724deb825859c62cca8b3a63e46097c4f875e44",
          "sha256": "69c4d5873a57e8ff93f0719dff7d90ae472c6f814bef8cb3da46ce9370083e86",
          "sha1": "3c557a80d0f48b0a8c13397889500479c6ffd445",
          "md5": "4b454ba377529e53a9cfc17cfd82a00f"
        }
      ]
    }
  ]
}
