{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "1540b3c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-1540b3c.jar",
          "url": "kmock-processor-1540b3c.jar",
          "size": 105503,
          "sha512": "0598c9cfff1f7c59312863d9b1c80ec9d7e73feb0b7af165de375f2a5265ceb5565a6a44d925f126b7fff434ab56502fad7061f81116e907109f5226ab5430d7",
          "sha256": "ef9396942fd419ac00ce41b1bdd64d6727258b5c3faeb4459e8e39ac6d275e4e",
          "sha1": "ba0954790e0d9f9d6a9556f538757673215570e4",
          "md5": "2d6095379a3df82569702d65f7c1d174"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "1540b3c"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-1540b3c.jar",
          "url": "kmock-processor-1540b3c.jar",
          "size": 105503,
          "sha512": "0598c9cfff1f7c59312863d9b1c80ec9d7e73feb0b7af165de375f2a5265ceb5565a6a44d925f126b7fff434ab56502fad7061f81116e907109f5226ab5430d7",
          "sha256": "ef9396942fd419ac00ce41b1bdd64d6727258b5c3faeb4459e8e39ac6d275e4e",
          "sha1": "ba0954790e0d9f9d6a9556f538757673215570e4",
          "md5": "2d6095379a3df82569702d65f7c1d174"
        }
      ]
    }
  ]
}
