{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/dbba7bb/test-utils-dbba7bb.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "dbba7bb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "mingwX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-mingwx86-dbba7bb.klib",
          "size": 7963,
          "sha512": "6c40d5b61571661803d01decae86ff496d87167ae82a1ccceab30625ce05422c3e341c395c1abce40148e8199497bbe303b72af047d8b6a40a47e4af5aa43c9a",
          "sha256": "07222af66e410d8241f17ba092fdda451bd15a5d20edcf8573ab3854ea645ca0",
          "sha1": "4feee838103edbfff4a86fda896a72f688303eae",
          "md5": "eafe5a2c31d19bf3c533d1e2607b1761"
        }
      ]
    }
  ]
}
