{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/dbba7bb/test-utils-annotations-junit4-dbba7bb.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "dbba7bb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-tvosarm64-dbba7bb.klib",
          "size": 11362,
          "sha512": "761afda9974c6eec9de1127cb5f54857e22583b9da741239ba3e4f1a9a6a53a940a24d7c7cf7cba74d1256d5ef46b934da6702119ec06837ffefec3739b0d59a",
          "sha256": "a8db34652bf5fb9b8fcb2fa9d314e92523afed4f8ed5bce1c389d9e5ea9be9ea",
          "sha1": "0ef1776028019f96993890ee25dc8230752fa5fc",
          "md5": "8fc3d1db6ebc267d998f39447659336d"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-tvosarm64-dbba7bb-metadata.jar",
          "url": "test-utils-annotations-junit4-tvosarm64-dbba7bb-metadata.jar",
          "size": 261,
          "sha512": "09671da7fba6038be2d4bb5e757aae7199e15235d4a7520b4dfa0a329ea236cff6f2f371975fadf774af3ec04355fc70e9d8cdcc192fd92454b09c4e440060eb",
          "sha256": "94e8e9f90f3b681e52682d3cc71b6d2362d886e30d44b01a3f93de8ac987e074",
          "sha1": "a19c3bface7baaca2a561d5756a1dfb1bc037c82",
          "md5": "918c6f298c9213670740f93d984fb9cb"
        }
      ]
    }
  ]
}
