{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "a1b98b8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-a1b98b8.jar",
          "url": "antibytes-custom-component-a1b98b8.jar",
          "size": 16534,
          "sha512": "4457ef00d0bf34d8a8544ba8aef96e9623dd53d329918e0fb57ab91b7c94cc4606e5378c4db0a73898c3de01a0f8eb3ea34ed7e475029ae7a514a1f9ec4534b4",
          "sha256": "eb3f0eaff6b469acd96891fc8f52eb40cce51eac885f14413a3987d785935d13",
          "sha1": "b6a1bece5802796fe4a760e8f2bb62ee6fd13bbb",
          "md5": "fbc5801d69e72c950053c545475fa200"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-a1b98b8.jar",
          "url": "antibytes-custom-component-a1b98b8.jar",
          "size": 16534,
          "sha512": "4457ef00d0bf34d8a8544ba8aef96e9623dd53d329918e0fb57ab91b7c94cc4606e5378c4db0a73898c3de01a0f8eb3ea34ed7e475029ae7a514a1f9ec4534b4",
          "sha256": "eb3f0eaff6b469acd96891fc8f52eb40cce51eac885f14413a3987d785935d13",
          "sha1": "b6a1bece5802796fe4a760e8f2bb62ee6fd13bbb",
          "md5": "fbc5801d69e72c950053c545475fa200"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-custom-component-a1b98b8-javadoc.jar",
          "url": "antibytes-custom-component-a1b98b8-javadoc.jar",
          "size": 261,
          "sha512": "94d5bdd43819401d1a0deae4168151e75ccb8af1f86c03c3153a9ca9ead1b6284496bb5288a934dd460786aa080992b325134066473d70473b77534790e265a3",
          "sha256": "6fc9b57b3a6934bb2918f7eb5326dfe5f937add79d4471407e0acae641215906",
          "sha1": "883dd52932adc2c308f14be6613643d79ee9ee36",
          "md5": "6a3bf833039064c076c2e149ba4f793c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-custom-component-a1b98b8-sources.jar",
          "url": "antibytes-custom-component-a1b98b8-sources.jar",
          "size": 3352,
          "sha512": "b2dec4cca8a7e8321b3f8545605ac2de3d42392665c7aebd5ceb8ceb07401aa2727d1a28da66d3e4a0aedc2babefbc4b30af944de73a061a91fce781614d947e",
          "sha256": "051f9603d591ad1401418b578d91cf8f3256ec0892d381809cb0a746a12a395d",
          "sha1": "9b910a47ead7782ffb2f72c5da96cc31cc9dc339",
          "md5": "09e9c5bd4fcbabb8de5a72e59cc9a524"
        }
      ]
    }
  ]
}
