{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "183d5f4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-183d5f4.jar",
          "url": "antibytes-versioning-183d5f4.jar",
          "size": 22487,
          "sha512": "d371ceed871951ae293d3a810585cf0f6aee519717cd991d3c18a5ee829a88e4ffc407de242f39aaf8b69fafc49b683b03b69d6cee7c4aa67e3718561538ad5a",
          "sha256": "c104ebd6c2cddfd2c9d02d4befffbddd36bb098e9e5c3fb8bddef452159514be",
          "sha1": "379dcefe23870ad6029f9b48b637e05d9c1899f8",
          "md5": "388946cdccaacc5d0b3372293ded9375"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-183d5f4.jar",
          "url": "antibytes-versioning-183d5f4.jar",
          "size": 22487,
          "sha512": "d371ceed871951ae293d3a810585cf0f6aee519717cd991d3c18a5ee829a88e4ffc407de242f39aaf8b69fafc49b683b03b69d6cee7c4aa67e3718561538ad5a",
          "sha256": "c104ebd6c2cddfd2c9d02d4befffbddd36bb098e9e5c3fb8bddef452159514be",
          "sha1": "379dcefe23870ad6029f9b48b637e05d9c1899f8",
          "md5": "388946cdccaacc5d0b3372293ded9375"
        }
      ]
    }
  ]
}
