{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/56c4547/test-utils-annotations-junit4-56c4547.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "56c4547",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-jvm-56c4547.jar",
          "url": "test-utils-annotations-junit4-jvm-56c4547.jar",
          "size": 10931,
          "sha512": "92f8d2d842da40299a216c234daca3be08f5f43cd777b760f310e74a50e1682e739c95d0a9713d02560d233c8e47b356d5c3555b11107c0c387369ebdeede839",
          "sha256": "2b6d1a2dbb56883611a431c139c121deb56043df895507b285016d7bcf58de44",
          "sha1": "b4681de4902f9531308f00c755eb46b19b46b8b8",
          "md5": "6572c127c588cfce295edcc8fae89ea7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-jvm-56c4547.jar",
          "url": "test-utils-annotations-junit4-jvm-56c4547.jar",
          "size": 10931,
          "sha512": "92f8d2d842da40299a216c234daca3be08f5f43cd777b760f310e74a50e1682e739c95d0a9713d02560d233c8e47b356d5c3555b11107c0c387369ebdeede839",
          "sha256": "2b6d1a2dbb56883611a431c139c121deb56043df895507b285016d7bcf58de44",
          "sha1": "b4681de4902f9531308f00c755eb46b19b46b8b8",
          "md5": "6572c127c588cfce295edcc8fae89ea7"
        }
      ]
    }
  ]
}
