{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "11324f8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "11324f8"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-11324f8.jar",
          "url": "antibytes-mkdocs-11324f8.jar",
          "size": 12083,
          "sha512": "f21731673e45e2a2baf0484fc956066cec7c1d940e2f02ec4e907d9bb9c6fab12435bef174e516b701496a7723244fc23c9f7679d9b813006b587db9587b0469",
          "sha256": "210a879406fb9a3eec10e3b9aef9e5e385cfa5b7fc3c754ef3f7a58ec82e6028",
          "sha1": "ccdd983cdca5dbc7c4078d408ce6fa2e8ec71c64",
          "md5": "3694001a6302d5ed7ddc6b3b9882db43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "11324f8"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "11324f8"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-11324f8.jar",
          "url": "antibytes-mkdocs-11324f8.jar",
          "size": 12083,
          "sha512": "f21731673e45e2a2baf0484fc956066cec7c1d940e2f02ec4e907d9bb9c6fab12435bef174e516b701496a7723244fc23c9f7679d9b813006b587db9587b0469",
          "sha256": "210a879406fb9a3eec10e3b9aef9e5e385cfa5b7fc3c754ef3f7a58ec82e6028",
          "sha1": "ccdd983cdca5dbc7c4078d408ce6fa2e8ec71c64",
          "md5": "3694001a6302d5ed7ddc6b3b9882db43"
        }
      ]
    }
  ]
}
