{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "dfa7e53",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-dfa7e53.jar",
          "url": "antibytes-versioning-dfa7e53.jar",
          "size": 24262,
          "sha512": "bff8d64878426a3ee14bf17913a90934a8a6664c8ec85fd447b88a1273d768b42ec9553089ebd6a963f562bf9a656d60cadf26b2e574ad44ec154e02c5bc6d4d",
          "sha256": "b9951312312995b1af0204c38a0c054d925210fea725d962545926924995a820",
          "sha1": "6d7beb185c3ba61fe5ccee847ba4925c1eab5a32",
          "md5": "c9787add7fffef2c450c8ad70df3cf73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-dfa7e53.jar",
          "url": "antibytes-versioning-dfa7e53.jar",
          "size": 24262,
          "sha512": "bff8d64878426a3ee14bf17913a90934a8a6664c8ec85fd447b88a1273d768b42ec9553089ebd6a963f562bf9a656d60cadf26b2e574ad44ec154e02c5bc6d4d",
          "sha256": "b9951312312995b1af0204c38a0c054d925210fea725d962545926924995a820",
          "sha1": "6d7beb185c3ba61fe5ccee847ba4925c1eab5a32",
          "md5": "c9787add7fffef2c450c8ad70df3cf73"
        }
      ]
    }
  ]
}
