{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "8068699",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-8068699.jar",
          "url": "antibytes-versioning-8068699.jar",
          "size": 21893,
          "sha512": "25d6e280aef4ee172c95a4e04227c82e8f90477bab4850d4008677891b75fd4fa3fafb56ba6ffbf6fe7aa914c49eec04015130aceae1960bf13bc810ff946bee",
          "sha256": "625c5c31e52431aea306b4ac771b1b427bba387099c4f2de670734665fda3287",
          "sha1": "3433884abde62c8b4d1110f298339a527c96871e",
          "md5": "f111ba510e5ee381f2e703b34afda9d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-8068699.jar",
          "url": "antibytes-versioning-8068699.jar",
          "size": 21893,
          "sha512": "25d6e280aef4ee172c95a4e04227c82e8f90477bab4850d4008677891b75fd4fa3fafb56ba6ffbf6fe7aa914c49eec04015130aceae1960bf13bc810ff946bee",
          "sha256": "625c5c31e52431aea306b4ac771b1b427bba387099c4f2de670734665fda3287",
          "sha1": "3433884abde62c8b4d1110f298339a527c96871e",
          "md5": "f111ba510e5ee381f2e703b34afda9d4"
        }
      ]
    }
  ]
}
