{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/b9030f2/test-utils-annotations-junit5-b9030f2.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "b9030f2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-tvossimulatorarm64-b9030f2.klib",
          "size": 7173,
          "sha512": "e5903900229ab66e1dc6b78841a1f6f39aa8d98f6bb1dec2e72dcb2f02b2c65494a7722bab1a3ab6240f2e99af0b232194364502f338cdf83934552592db15c5",
          "sha256": "46260595b5bb0cc89c1e6f7a07e9b05ac84d26604d7c4fdb088217bf55ea7526",
          "sha1": "c7f6a44470bed3e982e8bd550b7c64a30db29332",
          "md5": "0f65c9f8e710c350e2b361431e9b8e44"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-annotations-junit5-tvossimulatorarm64-b9030f2-sources.jar",
          "url": "test-utils-annotations-junit5-tvossimulatorarm64-b9030f2-sources.jar",
          "size": 3477,
          "sha512": "8910488f2acc4f4c669bf3e6a74835e60ede75d2286f44304a32d7435e9374f50e400ec91ccdc9fcab868fe57ac79f9cc99c5183a87396417d48b059ee008e7f",
          "sha256": "9f2d1a8fe1210ea25bd9b54214171ccdd8f68d07f8c4c7bf4fdaa277b2d059e9",
          "sha1": "c0915589af235519923fb41575cb1d6e37f9dedf",
          "md5": "b993ac9b3bda4583966bb9266ec6da60"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-tvossimulatorarm64-b9030f2-metadata.jar",
          "url": "test-utils-annotations-junit5-tvossimulatorarm64-b9030f2-metadata.jar",
          "size": 261,
          "sha512": "278c10194219e61760edd7a9af004c245330707fed322771592993b3249cd63fe0b44293ef9cbba5d68902ac4ebdc67a9702ef6eb3609fcc4c2fc39ffd6c7fe0",
          "sha256": "57cd24e79013699817f73330de156d8a05c575ba60bcdba6fd5bc96862495d69",
          "sha1": "f819cd28e8ecb23642883e1a6a0d5b6ce6de23ad",
          "md5": "8547659544a46d81201d6013f38e4e28"
        }
      ]
    }
  ]
}
