{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "61a30a2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-metadata-61a30a2.jar",
          "url": "kmock-61a30a2.jar",
          "size": 19911,
          "sha512": "2bc2e20a6ef89a4fa21288f33dc84594efb1fc0b70164fb25d8424a13452063f96096573ffd3a98183fbe7fc78b911067901f810d8dbbf9d82b449f77fb93c69",
          "sha256": "60b3b89a23555c802b678bd651fdd1801a7cea1e8ca1398aa7dc582e7651211d",
          "sha1": "fe04abf9106019b25ed4bb92240aa6b2d67fdf53",
          "md5": "78f896a1d700c2099f3cdd566a9bf67e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/61a30a2/kmock-android-61a30a2.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "61a30a2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/61a30a2/kmock-android-61a30a2.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "61a30a2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/61a30a2/kmock-iosarm64-61a30a2.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "61a30a2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/61a30a2/kmock-iosx64-61a30a2.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "61a30a2"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/61a30a2/kmock-js-61a30a2.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "61a30a2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/61a30a2/kmock-js-61a30a2.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "61a30a2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/61a30a2/kmock-jvm-61a30a2.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "61a30a2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/61a30a2/kmock-jvm-61a30a2.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "61a30a2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/61a30a2/kmock-linuxx64-61a30a2.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "61a30a2"
      }
    }
  ]
}
