{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-runtime-configuration",
    "version": "d50fcae",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-d50fcae.jar",
          "url": "antibytes-runtime-configuration-d50fcae.jar",
          "size": 9073,
          "sha512": "416c1d98f3d37ad33cb456bd26cee49d5396a07d6a513642e5a9b896af0279f3b2648b1ecb56ec5d35158863911743f705c2bfc3f4832a0223f31b50a4072bcc",
          "sha256": "9f1599ad3d0f1657dc39b6ef15fd6b7996c916bbf1b3fbe938e8d0446db87b91",
          "sha1": "542e3dc273fbf9acfb0ac5ca822f06bbccf2f998",
          "md5": "97ebbf14fe3aee83b86b6df013c792aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "d50fcae"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-d50fcae.jar",
          "url": "antibytes-runtime-configuration-d50fcae.jar",
          "size": 9073,
          "sha512": "416c1d98f3d37ad33cb456bd26cee49d5396a07d6a513642e5a9b896af0279f3b2648b1ecb56ec5d35158863911743f705c2bfc3f4832a0223f31b50a4072bcc",
          "sha256": "9f1599ad3d0f1657dc39b6ef15fd6b7996c916bbf1b3fbe938e8d0446db87b91",
          "sha1": "542e3dc273fbf9acfb0ac5ca822f06bbccf2f998",
          "md5": "97ebbf14fe3aee83b86b6df013c792aa"
        }
      ]
    }
  ]
}
