{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-quality",
    "version": "ec7ea01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-quality-ec7ea01.jar",
          "url": "antibytes-quality-ec7ea01.jar",
          "size": 62592,
          "sha512": "e43440ccbb148d527ea38fa384dba5ebd958e342fedb441a2a8d3cc1c678f4bece1fc7440130b243cda9ad7b8ad7e7f392b26efa92a9bfded92462cb6576f84d",
          "sha256": "cef1de5046b699fd55844b8cd60ac97ad0dd9a9eed4b98b9cfc8f3a5cb37ac10",
          "sha1": "ddbb6912e2b124d52341dba2769f8e22a4b9ac89",
          "md5": "54855bab2de241bc5dd78490a171dc41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.21.0"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "ec7ea01"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-dependency-helper",
          "version": {
            "requires": "ec7ea01"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-ec7ea01.jar",
          "url": "antibytes-quality-ec7ea01.jar",
          "size": 62592,
          "sha512": "e43440ccbb148d527ea38fa384dba5ebd958e342fedb441a2a8d3cc1c678f4bece1fc7440130b243cda9ad7b8ad7e7f392b26efa92a9bfded92462cb6576f84d",
          "sha256": "cef1de5046b699fd55844b8cd60ac97ad0dd9a9eed4b98b9cfc8f3a5cb37ac10",
          "sha1": "ddbb6912e2b124d52341dba2769f8e22a4b9ac89",
          "md5": "54855bab2de241bc5dd78490a171dc41"
        }
      ]
    }
  ]
}
