{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-metadata-0.1.1-SNAPSHOT.jar",
          "url": "kmock-0.1.1-SNAPSHOT.jar",
          "size": 34428,
          "sha512": "9f8a51b714b5ca2cfc01faffae5b8f3edb9f15f7d9f284b38dd471678f51dbb6b33bf13642a85065914fa9b2490e82e8cba00cb2a00850e34d417ab3524e43ed",
          "sha256": "d7fbe350ea469cee3d56dc7e9e5b66f3e3362dd4d7323b7c642d6f74549d8fef",
          "sha1": "196c46b2dded10f32fc291bf89ec802e698d6788",
          "md5": "15ba83707c0bf07182bbc88ba804bd8b"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.1.1-SNAPSHOT/kmock-android-0.1.1-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.1.1-SNAPSHOT/kmock-android-0.1.1-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/0.1.1-SNAPSHOT/kmock-iosarm64-0.1.1-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iossimulatorarm64/0.1.1-SNAPSHOT/kmock-iossimulatorarm64-0.1.1-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iossimulatorarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/0.1.1-SNAPSHOT/kmock-iosx64-0.1.1-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.1.1-SNAPSHOT/kmock-js-0.1.1-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.1.1-SNAPSHOT/kmock-js-0.1.1-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.1.1-SNAPSHOT/kmock-jvm-0.1.1-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.1.1-SNAPSHOT/kmock-jvm-0.1.1-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/0.1.1-SNAPSHOT/kmock-linuxx64-0.1.1-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
