{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "03118a6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-03118a6.jar",
          "url": "antibytes-coverage-03118a6.jar",
          "size": 135215,
          "sha512": "84bc4d145027e90d777f5f80eb76847b35bec2afd2c8c26a9be0ab181dddbfdc502056e69b4d0ff4b3b2755f1a6c3e47ab7758fea89e8c97777862edab413887",
          "sha256": "8d12358b727bb3ad5b14f489734ca27e6f6723b45708327d4c9ab84d3e89b28c",
          "sha1": "0ae9fa462040e6331e62e140ef4174d97a812b4a",
          "md5": "cad9f4c5aae9c237d86d199faabdcdb1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "03118a6"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-03118a6.jar",
          "url": "antibytes-coverage-03118a6.jar",
          "size": 135215,
          "sha512": "84bc4d145027e90d777f5f80eb76847b35bec2afd2c8c26a9be0ab181dddbfdc502056e69b4d0ff4b3b2755f1a6c3e47ab7758fea89e8c97777862edab413887",
          "sha256": "8d12358b727bb3ad5b14f489734ca27e6f6723b45708327d4c9ab84d3e89b28c",
          "sha1": "0ae9fa462040e6331e62e140ef4174d97a812b4a",
          "md5": "cad9f4c5aae9c237d86d199faabdcdb1"
        }
      ]
    }
  ]
}
