{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/4f11117/test-utils-annotations-junit5-4f11117.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "4f11117",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-watchosarm64-4f11117.klib",
          "size": 7086,
          "sha512": "5375c934c293382a66ed350449d350206980273045a93130135db1067ee4d254812b2b34ea02d72617f5ff8f82f597b7eab8b7b3f8c4c822bdd3607c34c249a6",
          "sha256": "1432ca394b02f768ce4d7c31117de8116da79ade416cc2a79c33875f09ce239a",
          "sha1": "dccf6ffa23d7083d2b04feaba2746674f7b48b99",
          "md5": "30a4505ceaa9c4c1e2810c9254ef6461"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-watchosarm64-4f11117-metadata.jar",
          "url": "test-utils-annotations-junit5-watchosarm64-4f11117-metadata.jar",
          "size": 261,
          "sha512": "d6bf33f73730f106a256568c1b158742573bfa4821cdbaf48317e304ff8181735aabcc13fbcd6c8cd2b2a5def70cc4ca8c49b2ade00231c2e45c81956d3140a5",
          "sha256": "b969bcf5f5c0f4c3cc6a0e457a389fdc218bd2ff73f55879f83b6de98731ac62",
          "sha1": "6d29f90123be3aec48a8b6c1058b9f0d6420d2cf",
          "md5": "c265bcf5f3ba537f9df07fc6bb58cb02"
        }
      ]
    }
  ]
}
