{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/735eeec/test-utils-ktor-735eeec.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "735eeec",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iosarm64-735eeec.klib",
          "size": 15024,
          "sha512": "3fc74de29cdcfeb51e5f3d088f029442a6394c0ea2c9d69e03d98de2d9b24e8c8062e4ade5b8867fb720307825d41c9f6deee220f2757f7ec03258ae0e5d1390",
          "sha256": "2c9d531555e863a1d053526218e12b434af87dcb03683df053bf5ad2568a6dc8",
          "sha1": "1d2cf4e3f0400e18fd8068af07e463d87ca11339",
          "md5": "ed8c3d163f74fa45075d9eb656c3e273"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iosarm64-735eeec-metadata.jar",
          "url": "test-utils-ktor-iosarm64-735eeec-metadata.jar",
          "size": 261,
          "sha512": "30132d527e369f26b7a98799cd37dcbb1d0818c518631ec4ebd503cc1c05b7e907d8749b365380228e3ea459cf291a74d61688d29904f2f5ee44d24582e6dd39",
          "sha256": "d8747f9d018464b34e43e87a1fb2b21283fe2d876e4bb54bb498d23aeeb11971",
          "sha1": "a4e4e6ca2544fa62a7d387f716c7182e40c72104",
          "md5": "b621361db1db19e964428fefa0745df8"
        }
      ]
    }
  ]
}
