{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "fc0a3f0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-fc0a3f0.jar",
          "url": "antibytes-dependency-fc0a3f0.jar",
          "size": 71898,
          "sha512": "e673ef3aa3f521717e40c6d2f3040850fb0dedf89e3cfc2f4cb2917d457f451507b89046519b731c1e751cdf60f706f78cdfa9a56c160bbb30332a587f99a5e8",
          "sha256": "31cdac1d0a62578039c66cf26778af2b8a8b8fb1a3e356beadf0a91dcd88d18e",
          "sha1": "abd9956d05c3de5bdc4712b44c6563f04c8912ca",
          "md5": "fc22865bff5ef0edfbc3e55c5c641520"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-gradle-plugin",
          "version": {
            "requires": "0.17.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.0.4.1"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.44.0"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "fc0a3f0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-fc0a3f0.jar",
          "url": "antibytes-dependency-fc0a3f0.jar",
          "size": 71898,
          "sha512": "e673ef3aa3f521717e40c6d2f3040850fb0dedf89e3cfc2f4cb2917d457f451507b89046519b731c1e751cdf60f706f78cdfa9a56c160bbb30332a587f99a5e8",
          "sha256": "31cdac1d0a62578039c66cf26778af2b8a8b8fb1a3e356beadf0a91dcd88d18e",
          "sha1": "abd9956d05c3de5bdc4712b44c6563f04c8912ca",
          "md5": "fc22865bff5ef0edfbc3e55c5c641520"
        }
      ]
    }
  ]
}
