{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "abee219",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-abee219-all.jar",
          "url": "core-abee219-all.jar",
          "size": 14783,
          "sha512": "f2fc565e82ab98403d9bd6c638480503d6bd0b748235cbbb1c9fc6173800e9b87216d400d512348c783c2a490f454d6156490919c7be8086b43e5a43d2be80d2",
          "sha256": "b45a05ddc18782ecb117fc5b2ffd3c784c0b9b744365c1c080d992bb90758f4c",
          "sha1": "03f4e5f593ea69f6f20495cf532ec9420b29f591",
          "md5": "c1ac808df96475f1e69a0f05aa894566"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-abee219.jar",
          "url": "core-abee219.jar",
          "size": 20255,
          "sha512": "09bccfc3415335c98c2b7d7b4f4b09a20d54efebe9ca9e606fe82b8fff1215b24385d4b22d258247d3bce2ba585580e6db424355e157ace841490fb7d2adf382",
          "sha256": "312b303c7802e35e42c0b0523e49b36e4074454538e557dcc0c6e98f3cb737aa",
          "sha1": "4e10efdcf8e7f6bb5c17d1147f1f89a1436e1d74",
          "md5": "98787be1ef37f3c3fb37e9ede85d693f"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/abee219/core-android-abee219.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-android",
        "version": "abee219"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/abee219/core-android-abee219.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-android",
        "version": "abee219"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/abee219/core-iosarm64-abee219.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosarm64",
        "version": "abee219"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/abee219/core-iosarm64-abee219.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosarm64",
        "version": "abee219"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/abee219/core-iossimulatorarm64-abee219.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iossimulatorarm64",
        "version": "abee219"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/abee219/core-iossimulatorarm64-abee219.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iossimulatorarm64",
        "version": "abee219"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/abee219/core-iosx64-abee219.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosx64",
        "version": "abee219"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/abee219/core-iosx64-abee219.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosx64",
        "version": "abee219"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/abee219/core-js-abee219.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-js",
        "version": "abee219"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/abee219/core-js-abee219.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-js",
        "version": "abee219"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/abee219/core-jvm-abee219.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-jvm",
        "version": "abee219"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/abee219/core-jvm-abee219.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-jvm",
        "version": "abee219"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-linuxx64/abee219/core-linuxx64-abee219.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-linuxx64",
        "version": "abee219"
      }
    }
  ]
}
