{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "423842c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-423842c.jar",
          "url": "antibytes-versioning-423842c.jar",
          "size": 21893,
          "sha512": "18c1bb21753bcbe7d8717c2ba7e7587a270d926e15d2b933056265f99ad19fa8d6d5a72e1ec70b614e2f3bf4e8be3f06282581d42b7c118c51e98eeaa61a942c",
          "sha256": "ed6970df5ca1af68f449ec2f453fbe5c8df68b26aaffb1d804a7ec2012938e6b",
          "sha1": "f01cb0a8738bd27e51af7a2953f4da69bf4c5de4",
          "md5": "06eea5c2ac5c52be1cce442523ff2acf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-423842c.jar",
          "url": "antibytes-versioning-423842c.jar",
          "size": 21893,
          "sha512": "18c1bb21753bcbe7d8717c2ba7e7587a270d926e15d2b933056265f99ad19fa8d6d5a72e1ec70b614e2f3bf4e8be3f06282581d42b7c118c51e98eeaa61a942c",
          "sha256": "ed6970df5ca1af68f449ec2f453fbe5c8df68b26aaffb1d804a7ec2012938e6b",
          "sha1": "f01cb0a8738bd27e51af7a2953f4da69bf4c5de4",
          "md5": "06eea5c2ac5c52be1cce442523ff2acf"
        }
      ]
    }
  ]
}
