{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "bf5cf3e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-bf5cf3e.jar",
          "url": "antibytes-grammar-tools-bf5cf3e.jar",
          "size": 59182,
          "sha512": "f094647a590104524891ef1b25ba5a19bfba14663313680c146defbe13c7e8014d6ff3821067c238c1c888000b67c20e9a39a18df045dac1e8c3bbbf26a48b7c",
          "sha256": "6d16d38d218852c63b89af7b594b86ad3382fc616e9c87ba05b7560d7ba29055",
          "sha1": "d9f00f9c90733afde50193412ed2521dd935b068",
          "md5": "c86bcc6a22757f1314bceb1edc3b69eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-bf5cf3e.jar",
          "url": "antibytes-grammar-tools-bf5cf3e.jar",
          "size": 59182,
          "sha512": "f094647a590104524891ef1b25ba5a19bfba14663313680c146defbe13c7e8014d6ff3821067c238c1c888000b67c20e9a39a18df045dac1e8c3bbbf26a48b7c",
          "sha256": "6d16d38d218852c63b89af7b594b86ad3382fc616e9c87ba05b7560d7ba29055",
          "sha1": "d9f00f9c90733afde50193412ed2521dd935b068",
          "md5": "c86bcc6a22757f1314bceb1edc3b69eb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-bf5cf3e-javadoc.jar",
          "url": "antibytes-grammar-tools-bf5cf3e-javadoc.jar",
          "size": 261,
          "sha512": "cd517f0c18b809a1b2136bd90ac42db0d8588eb833f52ed7a823edd8e2dada6c7758d375ff7fb16f533ba52c40db2cd438d14192cf451a687cc3d429fbcfe5b9",
          "sha256": "77ce7fa64e5fbfec12020e7de1e43f2c464582536703c7064e4ad0b71cae6cab",
          "sha1": "6cf4d9f25c7c6b863cb8a71b5b78e7b7ab91630e",
          "md5": "393d00fa83db1a2a4277bd7a831bfc4f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-bf5cf3e-sources.jar",
          "url": "antibytes-grammar-tools-bf5cf3e-sources.jar",
          "size": 12245,
          "sha512": "95cf49a4976cf22c29f01728ff09faa8db908f6327dc46ad8069243c5fd9f8f6b8e3b9cb6d62cac42daf27c48d7f5d0066c7b69340f6b4f4404f365495e67559",
          "sha256": "c44a23f51935b6f16094e9c9a55f15be3029d690b486edffc6278d79f01198c8",
          "sha1": "c1638aa318ef5295588a5e1be5ab194ea9919bb7",
          "md5": "8aadfb9d036eeddf647c404a2b6f7f78"
        }
      ]
    }
  ]
}
