{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "3764d82",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-metadata.jar",
          "url": "test-utils-3764d82.jar",
          "size": 9080,
          "sha512": "ca9d91ba69cf518e7b30d75f37de3d99b9b22ee3e6061f99bce2ad9602efd79418b57a60c7a73816222758e5ee6c63d722a62cbd144def4406c5433440c08358",
          "sha256": "e23f2f07006fd2c73b9eb03e9f7dc8c1e4f97a23ef7676e4c7eb426c36ad8175",
          "sha1": "8831b73628e7a13c70a2d9241e14df0a2da50fdb",
          "md5": "a31d0c7e87c673fe903c43238db42f1e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/3764d82/test-utils-android-3764d82.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "3764d82"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/3764d82/test-utils-android-3764d82.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "3764d82"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/3764d82/test-utils-jvm-3764d82.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "3764d82"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/3764d82/test-utils-jvm-3764d82.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "3764d82"
      }
    }
  ]
}
