{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/dbba7bb/test-utils-annotations-junit5-dbba7bb.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "dbba7bb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-macosarm64-dbba7bb.klib",
          "size": 7066,
          "sha512": "3fce6cf4de8d7383b91fad3cedc3f5f321362fd242520ea5a9008c15c2fcc89219658403d7f1e14a33e15f9b2ceb177bfff5320ce8457178764dd22b6d4fe773",
          "sha256": "4af6d8dddb24f2b1b6e7e59f6b0b7f829f6378df4df88fad0064575e04426645",
          "sha1": "73563497243133e01d5e219452f81c33438f89f8",
          "md5": "ed8e72481b264e64f14783d1ff15f3e1"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-macosarm64-dbba7bb-metadata.jar",
          "url": "test-utils-annotations-junit5-macosarm64-dbba7bb-metadata.jar",
          "size": 261,
          "sha512": "075e1127dc62ee01f566106686251cddec6ebf9f0cd26d96f2594e952af0c6deff1a7745b21bf31b3cc908f6d9fe7eb3aa22f658a1f2266412f7b4d92b8f918a",
          "sha256": "0450a2adc337bc417c695fcf526167b04e5e4b646a62f87f86f91b0af12309f1",
          "sha1": "90e27c38fec2079ca12c674564276803b819397b",
          "md5": "018ba35474fa56b97c7a1e6007f5d2f7"
        }
      ]
    }
  ]
}
