{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "dc2c41a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-dc2c41a.jar",
          "url": "antibytes-versioning-dc2c41a.jar",
          "size": 24262,
          "sha512": "90633142a97acc224c7af8a481950b5b2f383b4ea5a3847eb822f560a5894926fd54caefabf6b60e2a6035fcff7f946bc4141d751a5dabe9c0b7549648832dd1",
          "sha256": "76b7a74fa9c76f03f112cb68c05c951460141c63ebabec298c2db24a32729ce7",
          "sha1": "4ef5b6dfec33efb052a100aa18b77e85e894de16",
          "md5": "238a36cfd1eb795e20dc06b204618307"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-dc2c41a.jar",
          "url": "antibytes-versioning-dc2c41a.jar",
          "size": 24262,
          "sha512": "90633142a97acc224c7af8a481950b5b2f383b4ea5a3847eb822f560a5894926fd54caefabf6b60e2a6035fcff7f946bc4141d751a5dabe9c0b7549648832dd1",
          "sha256": "76b7a74fa9c76f03f112cb68c05c951460141c63ebabec298c2db24a32729ce7",
          "sha1": "4ef5b6dfec33efb052a100aa18b77e85e894de16",
          "md5": "238a36cfd1eb795e20dc06b204618307"
        }
      ]
    }
  ]
}
