{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "afcad58",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-afcad58.jar",
          "url": "antibytes-versioning-afcad58.jar",
          "size": 24262,
          "sha512": "21717e3a675e298059feb4fb5742e397d0a97dca89aaf381cc412fe47edb7a240887d0e1c4fa909784ff106781e9fb97ac7ff8df0c6329f8b35c8bd27fbc2195",
          "sha256": "296619b979f6de62d0151fb8c27d5a07cf9b842b932455c5766419dfaa86112a",
          "sha1": "1fb8555049766f8435b9de031ce10bbca6405ad0",
          "md5": "65a43e83ad0f1516856c94fa9951c4ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-afcad58.jar",
          "url": "antibytes-versioning-afcad58.jar",
          "size": 24262,
          "sha512": "21717e3a675e298059feb4fb5742e397d0a97dca89aaf381cc412fe47edb7a240887d0e1c4fa909784ff106781e9fb97ac7ff8df0c6329f8b35c8bd27fbc2195",
          "sha256": "296619b979f6de62d0151fb8c27d5a07cf9b842b932455c5766419dfaa86112a",
          "sha1": "1fb8555049766f8435b9de031ce10bbca6405ad0",
          "md5": "65a43e83ad0f1516856c94fa9951c4ab"
        }
      ]
    }
  ]
}
