{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.3.0-rc02-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc02-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc02-SNAPSHOT.jar",
          "size": 68934,
          "sha512": "910b456f8bc36996ac5cbbd95cc754c81d6fdd1f76c890f98148ed974b5b4ac853af1d44665b2fb2e9b13a63a5a7b58fe89b7cc3b2545e4d8379e02731e4d51c",
          "sha256": "2887eaa39dde7e068919de6f2b32e8344f1dbfcbff32fa6df375e1a4c88e211d",
          "sha1": "ec53378d8719afdc60752153297f9c6ef5e814ad",
          "md5": "8a9953aecede88fef26911026d2335bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.21-1.0.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc02-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc02-SNAPSHOT.jar",
          "size": 68934,
          "sha512": "910b456f8bc36996ac5cbbd95cc754c81d6fdd1f76c890f98148ed974b5b4ac853af1d44665b2fb2e9b13a63a5a7b58fe89b7cc3b2545e4d8379e02731e4d51c",
          "sha256": "2887eaa39dde7e068919de6f2b32e8344f1dbfcbff32fa6df375e1a4c88e211d",
          "sha1": "ec53378d8719afdc60752153297f9c6ef5e814ad",
          "md5": "8a9953aecede88fef26911026d2335bd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc02-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.3.0-rc02-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "32abb10853dc777d8f9fdf8297e2fa66929d9a9054dc3a5955edfca248cc131015150927c34db3e07d77f32f9cfd368586e3863e5135b3f0d2324d1c8f20f627",
          "sha256": "f217259784211b467eb81de9a45ed3bdaa73d2b9bba1d42a12c759d0f80cec12",
          "sha1": "b9d29c0095fced6880db032cde3d23856f13a27c",
          "md5": "d7cd928f678f9ef5db8deb969503d4a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc02-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.3.0-rc02-SNAPSHOT-sources.jar",
          "size": 14291,
          "sha512": "2e0fea913ef07293eb5bc81c4146f5d611e71cbecaf5c58e0a6c85621196a3aa6f44c2f7d8d9adb22c9a06e7f06df6532d06a55b322fac33b5e5ce6361c0ded8",
          "sha256": "ac454f0edcbbd01b556d5a1569edbb44cc4d2fd477504e6755130487ad4f5bdb",
          "sha1": "8d693ebec030c9ffaee77198b4e5cedb501dc8df",
          "md5": "dd85e0adf5d6a278c46e431890a096a3"
        }
      ]
    }
  ]
}
