{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.3.0-rc02-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc02-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc02-SNAPSHOT.jar",
          "size": 68934,
          "sha512": "46c9f5bc70d745a07e3cf78979e07bfcd3370a79f5345b6199037e17c0164c7c831192905abff2d5cf2d6412900df29152897da9790890807ddca71a34c05cc5",
          "sha256": "6df588ed86d0890fe4b4cf9a88b3f8a82f9bef2a965ced8a730e06c3ac7058ef",
          "sha1": "50199eaccf93755f6203e17174096f700ab84d71",
          "md5": "7926d6a3405074f85fd111557184dbf9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.21-1.0.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc02-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc02-SNAPSHOT.jar",
          "size": 68934,
          "sha512": "46c9f5bc70d745a07e3cf78979e07bfcd3370a79f5345b6199037e17c0164c7c831192905abff2d5cf2d6412900df29152897da9790890807ddca71a34c05cc5",
          "sha256": "6df588ed86d0890fe4b4cf9a88b3f8a82f9bef2a965ced8a730e06c3ac7058ef",
          "sha1": "50199eaccf93755f6203e17174096f700ab84d71",
          "md5": "7926d6a3405074f85fd111557184dbf9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc02-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.3.0-rc02-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "e17575fc578146eb1b22d5cca9e070d538817879288228906b9d7e41f53121c0245d07cabeeaa5a09f9c11c6b6fa718d2fa5a3c803da74f628332763011bca92",
          "sha256": "0ba39d2ae7f255065c74e49f756820d28eafdbe97985340666b3211095988f7e",
          "sha1": "47d03278428bba07cced4c65374bd224e4ff6867",
          "md5": "9fbb56b34bbaf6de8918886d6f89ca55"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc02-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.3.0-rc02-SNAPSHOT-sources.jar",
          "size": 14291,
          "sha512": "721cb5fb482a440b2f88b0d231b92cb5047210c719a10a34065f0e17bf8b7be8327096e6c39f1a337ff8c491f17a32290db5255cb16a154c5afb344c5d688889",
          "sha256": "abfb8c22e493e8ea3f5bd6334485aab847b440604c44c9decbab0438cedf2a9a",
          "sha1": "da709dc18db3ffcf56124fa1393ef7276cfde0bd",
          "md5": "1bae289f0c5d43970d49377683b3a614"
        }
      ]
    }
  ]
}
