{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "d50bc26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "d50bc26"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-d50bc26.jar",
          "url": "antibytes-mkdocs-d50bc26.jar",
          "size": 11930,
          "sha512": "b0f22a21c7ed7fad287e2585fb3d3539d996fbabdbbd653888ad495097cc19514b559501ee9d753f0bafb55e506ce3792ee3146c29702a4d57857edbc059f0d3",
          "sha256": "775aeffa2b57fada88b9d13bee010237a4c833848f09013f1c7b63d134994af7",
          "sha1": "aebbbe69a0f3f28fd5f4f1b5698e23f00a4ec68f",
          "md5": "fa09a200a7d7b16a47e52d6e02476f8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "d50bc26"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "d50bc26"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-d50bc26.jar",
          "url": "antibytes-mkdocs-d50bc26.jar",
          "size": 11930,
          "sha512": "b0f22a21c7ed7fad287e2585fb3d3539d996fbabdbbd653888ad495097cc19514b559501ee9d753f0bafb55e506ce3792ee3146c29702a4d57857edbc059f0d3",
          "sha256": "775aeffa2b57fada88b9d13bee010237a4c833848f09013f1c7b63d134994af7",
          "sha1": "aebbbe69a0f3f28fd5f4f1b5698e23f00a4ec68f",
          "md5": "fa09a200a7d7b16a47e52d6e02476f8f"
        }
      ]
    }
  ]
}
