{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/1540b3c/kmock-1540b3c.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "1540b3c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-1540b3c.jar",
          "url": "kmock-jvm-1540b3c.jar",
          "size": 257638,
          "sha512": "a382ea1fa6418e31c92bcdbc8a19a2c95758d138ae0d83dec833ecb69b3403e29bc463623676c198c4b20960f8b3f3b6b6acb8e3960052b92710c6861a208f3e",
          "sha256": "17bb275faa790516a488250acbdd5f963b41c1d243c86f6de0427377bfe7eca4",
          "sha1": "e815b6ab1b00bcd3a8da9e42c6310e88cb8e1e67",
          "md5": "02ea27988eca384514a3d1974df31dac"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-1540b3c.jar",
          "url": "kmock-jvm-1540b3c.jar",
          "size": 257638,
          "sha512": "a382ea1fa6418e31c92bcdbc8a19a2c95758d138ae0d83dec833ecb69b3403e29bc463623676c198c4b20960f8b3f3b6b6acb8e3960052b92710c6861a208f3e",
          "sha256": "17bb275faa790516a488250acbdd5f963b41c1d243c86f6de0427377bfe7eca4",
          "sha1": "e815b6ab1b00bcd3a8da9e42c6310e88cb8e1e67",
          "md5": "02ea27988eca384514a3d1974df31dac"
        }
      ]
    }
  ]
}
