{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.2.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.2.0-rc01-SNAPSHOT.jar",
          "url": "kmock-gradle-0.2.0-rc01-SNAPSHOT.jar",
          "size": 56327,
          "sha512": "3a65f2bc0c5bed82581baea111b02948a57a48804be1e349f504b550cea6552b03907f56eddcc3ce1c02b37fa3afd258fbceb42e62a1c2c32469c7a2b80acaa1",
          "sha256": "701482b22c18676a8b063a93339fdba7f81001bde6e537c3821f207d9d84eceb",
          "sha1": "64fa47a73c502604101ce7c9b8ed95b78d5ba1b6",
          "md5": "25e8dd4abe6369b096c5bd2271ea448e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.2.0-rc01-SNAPSHOT.jar",
          "url": "kmock-gradle-0.2.0-rc01-SNAPSHOT.jar",
          "size": 56327,
          "sha512": "3a65f2bc0c5bed82581baea111b02948a57a48804be1e349f504b550cea6552b03907f56eddcc3ce1c02b37fa3afd258fbceb42e62a1c2c32469c7a2b80acaa1",
          "sha256": "701482b22c18676a8b063a93339fdba7f81001bde6e537c3821f207d9d84eceb",
          "sha1": "64fa47a73c502604101ce7c9b8ed95b78d5ba1b6",
          "md5": "25e8dd4abe6369b096c5bd2271ea448e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.2.0-rc01-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.2.0-rc01-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "99321f23ea5aff9be34ee9528a0715e245bcf16809330fec99392b82cebd526aaeaa57c5e24e7b007ba6ffd87dc61075e710bf6174ca5507d0adc95aa0fec42a",
          "sha256": "9f025d489d71a1f0e15d3d5e373e1e4be0d85af7fdf166cb6464354969a26516",
          "sha1": "d05365597198f9c43b8c0a5f15afa5e43935eda5",
          "md5": "d940f11ce4625f27cefeef9336540e51"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.2.0-rc01-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.2.0-rc01-SNAPSHOT-sources.jar",
          "size": 11765,
          "sha512": "dff8eaf389c8de38f9b593cc87d3a21a064b045535cec373b3d0624b3c99fb30b44efa86c7ba978c01bc6b28e4fc1ee8c8f60fba98b9cae6519ddb9345cfed13",
          "sha256": "a0e755fb63092e05481a7ba251a52987943d9b84beaa02e97927fd92dde8b7e4",
          "sha1": "570be1f65a1f4b7b959515cfc930b477b6427713",
          "md5": "e6671cdc80201a3a9e1cda2f79e8400b"
        }
      ]
    }
  ]
}
