{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.2.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.2.0-rc01-SNAPSHOT.jar",
          "url": "kmock-gradle-0.2.0-rc01-SNAPSHOT.jar",
          "size": 56327,
          "sha512": "6d58c542084833cf211045833d88e213c0f0c5e4a078a93f8fe6aab3415b6970fc5dd5ba8cf386fe9609becb72bce457d7bca29f455b7c3142f2e3e2b17716c4",
          "sha256": "539682ce103e757821e02a83406182a2c184efe94d07ca85a54408010f86693f",
          "sha1": "fb8344b5d9521d622b2cf8620f31af879af3bce6",
          "md5": "24662254af0956b0e88dbf7717247754"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.2.0-rc01-SNAPSHOT.jar",
          "url": "kmock-gradle-0.2.0-rc01-SNAPSHOT.jar",
          "size": 56327,
          "sha512": "6d58c542084833cf211045833d88e213c0f0c5e4a078a93f8fe6aab3415b6970fc5dd5ba8cf386fe9609becb72bce457d7bca29f455b7c3142f2e3e2b17716c4",
          "sha256": "539682ce103e757821e02a83406182a2c184efe94d07ca85a54408010f86693f",
          "sha1": "fb8344b5d9521d622b2cf8620f31af879af3bce6",
          "md5": "24662254af0956b0e88dbf7717247754"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.2.0-rc01-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.2.0-rc01-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "c76036b947c707ec5b16296b0195e960aa1657de88f0603e77c6bfea5cc4a8fade008a24e18bb7a07f5fedf587c73e00cc32fb390f7037c08e5a585dada11866",
          "sha256": "d5be41d74997ca48b97454c507171d65f07c959e7baead15238d6232576b3919",
          "sha1": "424aed84b301a1a330ea6a2b9ac28d706ef6d6f4",
          "md5": "f5eaf54e281d559466dcff9632c9ec4d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.2.0-rc01-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.2.0-rc01-SNAPSHOT-sources.jar",
          "size": 11765,
          "sha512": "eb514b99eb7c8c7caedd8178b9b8c3ff0c7d4a3135108cdbada199b0a62e0773a899bd6d0a7d0aab2df0d68134c5c5e23433b4ec06da1ee22dcedd5753135da2",
          "sha256": "26af1a043872e6db8c37f2581916a9943ca8342c5ecc65e78d0a118bcf6e4e9d",
          "sha1": "9fd5fd810f87b923517435b806b3e3e7e27fe695",
          "md5": "414bca610bdbd725a6eceb7527f0ad3c"
        }
      ]
    }
  ]
}
