{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.2.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.2.0-rc01-SNAPSHOT.jar",
          "url": "kmock-gradle-0.2.0-rc01-SNAPSHOT.jar",
          "size": 56327,
          "sha512": "51a96405b982f1184dec60abf18cbba01632bc5ece6bc095d6347c46483529bfca975edb01a2d605aff7066f22c15acdfa12180f797ca3c69dd7d04fd6da13be",
          "sha256": "14ef61581ac1ede97d386c20470a680910dd05d908cda30fea63a222ebcd7e99",
          "sha1": "e4ba9336c04a7015a07117ac435f5a27dbdd3347",
          "md5": "62d40ddb0201b2636985da1a37580716"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.2.0-rc01-SNAPSHOT.jar",
          "url": "kmock-gradle-0.2.0-rc01-SNAPSHOT.jar",
          "size": 56327,
          "sha512": "51a96405b982f1184dec60abf18cbba01632bc5ece6bc095d6347c46483529bfca975edb01a2d605aff7066f22c15acdfa12180f797ca3c69dd7d04fd6da13be",
          "sha256": "14ef61581ac1ede97d386c20470a680910dd05d908cda30fea63a222ebcd7e99",
          "sha1": "e4ba9336c04a7015a07117ac435f5a27dbdd3347",
          "md5": "62d40ddb0201b2636985da1a37580716"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.2.0-rc01-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.2.0-rc01-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "a171065eeb291a11cf891333bf519253bca0ce34c288737c13ab6013d67e358922548cf8a37dba27abb36c5e8f5a4d1ce6677001b54ec1e21184e81ef69813d1",
          "sha256": "639cf384d60a349561d9e8fc3211313d913f62abd3cb2ad86746ba0fe13962c3",
          "sha1": "ba63e1758573086b03962446f075681f7d62724e",
          "md5": "6087b676573aeeae3234e729bf8764bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.2.0-rc01-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.2.0-rc01-SNAPSHOT-sources.jar",
          "size": 11765,
          "sha512": "b4361f6cf3e989e40f8fce51f9535c4b78b0aa69c2b05e172234d0ce6805887b06535dd0c299219d5606471623290e67aaab4eee440ab6235ae430d4e96c4d77",
          "sha256": "e38d071db35409f7c6ffdbb6c22eaadeeb5ca63a46a88ef9793ba29c5953682d",
          "sha1": "1431f102b91a412cbdfe6dd7b4ca7c8072ccf2da",
          "md5": "94ec860e94a54f6e65a8a4cc7fc5b205"
        }
      ]
    }
  ]
}
