{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/735eeec/test-utils-ktor-735eeec.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "735eeec",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iosx64-735eeec.klib",
          "size": 15007,
          "sha512": "a8574551127dbecb2bb4acee1f464294509288aaaf68535e0794384177dc2c8435e6725a8b5a182b9f97b376bec5e18f7530d862f2c7dc017f372bb29e70e3e0",
          "sha256": "05cac543827738cab25c67e8b839835581979b34f216c0359407fba6fd0cb94d",
          "sha1": "174d7fe0cd56bcdda3c1610721bd97b430b89c7f",
          "md5": "db0f2441cc04230badc5fd971584edbc"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iosx64-735eeec-metadata.jar",
          "url": "test-utils-ktor-iosx64-735eeec-metadata.jar",
          "size": 261,
          "sha512": "30132d527e369f26b7a98799cd37dcbb1d0818c518631ec4ebd503cc1c05b7e907d8749b365380228e3ea459cf291a74d61688d29904f2f5ee44d24582e6dd39",
          "sha256": "d8747f9d018464b34e43e87a1fb2b21283fe2d876e4bb54bb498d23aeeb11971",
          "sha1": "a4e4e6ca2544fa62a7d387f716c7182e40c72104",
          "md5": "b621361db1db19e964428fefa0745df8"
        }
      ]
    }
  ]
}
