{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "cfd6317",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-cfd6317.jar",
          "url": "antibytes-gradle-utils-cfd6317.jar",
          "size": 11416,
          "sha512": "81d7e561958f9ada05472f7837dd59848fbb589c7f5e5775f09444b69567b18f99a2d866472ea70a88ad96f20c737e08e5f66778a6a91faca8b7a2a2aff105a7",
          "sha256": "6183ccbf801f8f7a757bf64da65b8b3d7cb0bbb2eb9b3834f5c8c3a64ef8b41e",
          "sha1": "88e673df303d307c24665aa300dff1d4210e3d13",
          "md5": "7a9b0d181b512f0cf7187a64e848a787"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-cfd6317.jar",
          "url": "antibytes-gradle-utils-cfd6317.jar",
          "size": 11416,
          "sha512": "81d7e561958f9ada05472f7837dd59848fbb589c7f5e5775f09444b69567b18f99a2d866472ea70a88ad96f20c737e08e5f66778a6a91faca8b7a2a2aff105a7",
          "sha256": "6183ccbf801f8f7a757bf64da65b8b3d7cb0bbb2eb9b3834f5c8c3a64ef8b41e",
          "sha1": "88e673df303d307c24665aa300dff1d4210e3d13",
          "md5": "7a9b0d181b512f0cf7187a64e848a787"
        }
      ]
    }
  ]
}
