{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc04-SNAPSHOT/kmock-0.3.0-rc04-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc04-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iossimulatorarm64-0.3.0-rc04-SNAPSHOT.klib",
          "size": 202582,
          "sha512": "0926c1b9d60a4eff717d47f56dfaa941668d4b953a01beb174f9750da33bb25909b0b2e27922ff21ea04042dbea97a85ef75201bb848dfa2d865b364d07d70e1",
          "sha256": "54b3fe661c7f4b656ee43f6c787ff0ef6c6f22d39dcbcfa1a17f48ce5fd185e7",
          "sha1": "1a0f32ca28f8d3829b68cf78fbd24035882deaa3",
          "md5": "7a9ba0b9eea295703c7575febdf389f1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iossimulatorarm64-0.3.0-rc04-SNAPSHOT-metadata.jar",
          "url": "kmock-iossimulatorarm64-0.3.0-rc04-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "5191b2b024489aac609aefab02cd30f757b1e7290aefdfd2e8c25b6cbd7043e0c45b545c6b2d4663716c004e7c233cd0da73fd353bc21e90dac3e605445e8b7c",
          "sha256": "122f3032527eed923a6346fef2f14b1c3ad5c0c73af16c64f53d631760fcbdb7",
          "sha1": "fe725c6e87b1abc00b96414b18fcd501a274a323",
          "md5": "88fb43361016f3b50a13f32879f6e17d"
        }
      ]
    }
  ]
}
