{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc04-SNAPSHOT/kmock-0.3.0-rc04-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc04-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iossimulatorarm64-0.3.0-rc04-SNAPSHOT.klib",
          "size": 202582,
          "sha512": "f03aed2e32829739c47af4ddcdf1a3b9ae32248aedbcf72f90b3c0502267983157f333ad0a474dc5862d6c2207d49508c2ddf5a9641b5017e1ec99d62b2ef928",
          "sha256": "0b0fc4e56b0f84ec56711ce518e821732601f9ac873a5edd5d876c830abbd995",
          "sha1": "debc903298e51733c2e90b370f26b4ad7ddba3d0",
          "md5": "a1dd230dbb16d0199c8a3053212483e1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iossimulatorarm64-0.3.0-rc04-SNAPSHOT-metadata.jar",
          "url": "kmock-iossimulatorarm64-0.3.0-rc04-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "3fcd9cf4a8604971980f662899df208afa52d12760ead8a7db76cf5653e6b552431c5b09e523ea39ff42d75096c152d6307cf446ec2d35750dd0d68e7a83c883",
          "sha256": "911a89d50fd02d60946234e5850ad43880d5fac56c0faeafff753528b5b61660",
          "sha1": "ccfb9de97b838330882e15c265f8127b2e6b29e6",
          "md5": "b9e56475190ad59c2204ac75b44add5e"
        }
      ]
    }
  ]
}
