{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "2d16671",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-2d16671.jar",
          "url": "antibytes-gradle-utils-2d16671.jar",
          "size": 11392,
          "sha512": "388a8a5807a84a36afe8f951e24ed08f2903c4a8a2a5abf540abab6d155b9b20e5c13ce846b40083553a5a705b9a2a84fb4ee7515ae8feefd48a57654ab98401",
          "sha256": "8df06c2d00a3ce144a6a907b6d4a6bb526d12478fd82a7050d7317e3843318d4",
          "sha1": "39a4197ae3fef86bdd9162a8d15e90bfe41865a0",
          "md5": "811b4d30164a306e8c0d16e865ae8ed9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-2d16671.jar",
          "url": "antibytes-gradle-utils-2d16671.jar",
          "size": 11392,
          "sha512": "388a8a5807a84a36afe8f951e24ed08f2903c4a8a2a5abf540abab6d155b9b20e5c13ce846b40083553a5a705b9a2a84fb4ee7515ae8feefd48a57654ab98401",
          "sha256": "8df06c2d00a3ce144a6a907b6d4a6bb526d12478fd82a7050d7317e3843318d4",
          "sha1": "39a4197ae3fef86bdd9162a8d15e90bfe41865a0",
          "md5": "811b4d30164a306e8c0d16e865ae8ed9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-2d16671-javadoc.jar",
          "url": "antibytes-gradle-utils-2d16671-javadoc.jar",
          "size": 261,
          "sha512": "7cf1d58a9c374d89f119ff29b5c2bedf94a3ff7a001c3c0652f52606d3b4980359b63f9ca0364f4e864b0cd77eff01dbd8362b6bb53267d7f45b210aa38f3534",
          "sha256": "8974fb3cdc9d756bb99b896d5f88ad8a73669fd92a37717013cb5a83a895cab2",
          "sha1": "4126c12385549fe65ebe1a560ff8c3827c9f853c",
          "md5": "1b8435a63ee77b546b62c8301df70e9c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-2d16671-sources.jar",
          "url": "antibytes-gradle-utils-2d16671-sources.jar",
          "size": 3524,
          "sha512": "b010999dd29ddaaa29adf34f5794e6d1c6fc817aa0ba3ad995091f2bac7e050df62664a9458fae7baddf11128fec4cb1c97b6ea918e6a60720c445c36aaeb264",
          "sha256": "7eae0d383de04f0815650c477baa34d8c2887104b7910ef73db5fcda40f40a4d",
          "sha1": "e899274d7b16b5c660eb29b2f67290fce261e1ac",
          "md5": "f8961dab7e7c59c80f5555b2a558982b"
        }
      ]
    }
  ]
}
