{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm32-0.4.0-SNAPSHOT.klib",
          "size": 105834,
          "sha512": "c3d2dfc5a6702050657a03d5351391e4bdb26926a195154abbf6e85269578658faacc631b493fc9159a8d567e7d4ba34cc24380ceedc043f72a21968dfcbbdbc",
          "sha256": "2f9b59c1de4f75965ecb2465ab2ebbaed21d7d005fe1b8f58c7664df8a0b42fb",
          "sha1": "c362d854ad4aca10ad5550c7a67ef1e21ca491e5",
          "md5": "c3d62e1366cf8ee2f4116b9d562930fb"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm32-0.4.0-SNAPSHOT-metadata.jar",
          "url": "core-iosarm32-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "33a73317c29e2085b6b44a23f761d516e63cc55e8e2a5584c1e2983b366c0804beecc7e233e75144e5b06a9aa25a3ba22119754fb4612c63eea42a6f3a6e0afe",
          "sha256": "e578ae6aafef83996ecf3b66382db3bea76faf915fad8bf1bae0d25591ed8678",
          "sha1": "975f51aa7d3a1298e1b79469f723016d2162a188",
          "md5": "f84ab79471928f09996064f2a4b21b1e"
        }
      ]
    }
  ]
}
