{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/86ec4d6/test-utils-resourceloader-86ec4d6.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "86ec4d6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-linuxx64-86ec4d6.klib",
          "size": 14218,
          "sha512": "e9c3ca3d50c58dc90bcaf2e3ddfa314ecd674fcaca52677ea1318f678757cac60624114d931403c43862db757dc48da4afbbcf8064d1335bc2d804b82c0ef56a",
          "sha256": "fcc31f8af592615a3135f2a93c2f86ac5ec5716c723b01c23a3432bb91823a36",
          "sha1": "66a48bc5a883e18f0a7f0aa9282eea02003bc177",
          "md5": "be36ab2ccaa3eb3ea5e9c3243d44e3de"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-linuxx64-86ec4d6-sources.jar",
          "url": "test-utils-resourceloader-linuxx64-86ec4d6-sources.jar",
          "size": 4241,
          "sha512": "284172150658cfb9dae6c2bb10bbd5de382a8193d892540a4de60322cb16b05740a160fc4f827c092194ab0e3983419cb75c9d52eee7cf9cf1ac22b32a8f7d7b",
          "sha256": "28c33fb0c5429879a7515dfb1ee5400a354f30a17cda3a32c13cec2fd413b7da",
          "sha1": "e6bc305f912fc8fc1e733215728491f83d594bd4",
          "md5": "935272aedc89d60202c3ad87a167495a"
        }
      ]
    }
  ]
}
