{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "150b2e1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-150b2e1.jar",
          "url": "antibytes-dependency-150b2e1.jar",
          "size": 88198,
          "sha512": "f43d1f4dd91fff0ae11f595ea16ae2ced3ae25b6052800eb1213c8763c70ad19bca9f6cc4ebd6d90532f84e398a9c2e81814c123ecd53e81764241b2002702d1",
          "sha256": "bb54c89fa6d60fff28b92eb6f757becc4c019f43b16c10ba1086c57375896969",
          "sha1": "69886917a41591b0d3f190842e3596773b4cfb60",
          "md5": "c7a36fccb667723ac15542ddf262e466"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          },
          "excludes": [
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-xml"
            }
          ]
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "150b2e1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-150b2e1.jar",
          "url": "antibytes-dependency-150b2e1.jar",
          "size": 88198,
          "sha512": "f43d1f4dd91fff0ae11f595ea16ae2ced3ae25b6052800eb1213c8763c70ad19bca9f6cc4ebd6d90532f84e398a9c2e81814c123ecd53e81764241b2002702d1",
          "sha256": "bb54c89fa6d60fff28b92eb6f757becc4c019f43b16c10ba1086c57375896969",
          "sha1": "69886917a41591b0d3f190842e3596773b4cfb60",
          "md5": "c7a36fccb667723ac15542ddf262e466"
        }
      ]
    }
  ]
}
