{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "862b3a7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-862b3a7.jar",
          "url": "antibytes-versioning-862b3a7.jar",
          "size": 22487,
          "sha512": "cdf5b88ea3e9199d8d52666bab0afb595bcc51f9c7d91f60fde060c8ecf90307aa87da6c0972a67fab0afd035c045e8934f8afebe0ff01b289389e732df5dd77",
          "sha256": "74ad028a639dca6dbae6f4a52426d78fbfa759de58a9f5f8f385dc5978e39d8e",
          "sha1": "490694b96d79ee1e58345d4b9d29b1d0e3036fa5",
          "md5": "9e55820bcbac509732c817e41e7be912"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-862b3a7.jar",
          "url": "antibytes-versioning-862b3a7.jar",
          "size": 22487,
          "sha512": "cdf5b88ea3e9199d8d52666bab0afb595bcc51f9c7d91f60fde060c8ecf90307aa87da6c0972a67fab0afd035c045e8934f8afebe0ff01b289389e732df5dd77",
          "sha256": "74ad028a639dca6dbae6f4a52426d78fbfa759de58a9f5f8f385dc5978e39d8e",
          "sha1": "490694b96d79ee1e58345d4b9d29b1d0e3036fa5",
          "md5": "9e55820bcbac509732c817e41e7be912"
        }
      ]
    }
  ]
}
