{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc07-SNAPSHOT/kmock-0.3.0-rc07-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc07-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-macosarm64-0.3.0-rc07-SNAPSHOT.klib",
          "size": 203092,
          "sha512": "b15abb3127a442f8114acc5be54c5ace031a66390f5ac17112a00ccca9ab8862f228a62e97730a18a7847fcf6963075c62e781e6723e20e9a94fa5f96f1e2743",
          "sha256": "8101a551a4f4e7eb2792c0ead1bad5c3b9c1043f0b6272bb6b782cc3d0525a5c",
          "sha1": "9004cfe8e4eb570c574361fe813a6910c00dabf1",
          "md5": "629da6c4265ba3ba6b15ea7780cca7e8"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-macosarm64-0.3.0-rc07-SNAPSHOT-metadata.jar",
          "url": "kmock-macosarm64-0.3.0-rc07-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "2d6404953cb9849fb3dabb7e686c768a75a4bb4a4f35e204426069edfb3917d2b77476b92ad268e848b6ee0716f5273ff8742b946191acf731bf0b6ba39096b9",
          "sha256": "91e19eca6294bb5c26471070a8402a279796d7187ff29b0cbfd69d1f3c5becdf",
          "sha1": "836830296e3d3d2ed287a1d5d83e2f9f98d36bfb",
          "md5": "85185f191901928fa2b0a81fdbfdd628"
        }
      ]
    }
  ]
}
