{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "c189d8a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-c189d8a.jar",
          "url": "antibytes-gradle-utils-c189d8a.jar",
          "size": 9568,
          "sha512": "7bc3ca967f049eb0215066830718b45358c404f73ddb7eada0cce61a5938b30857d933f9ef81b68c1d0d7c17d02f84ec0b05cd14a1b5244b6bd9ce23f1a4d924",
          "sha256": "5ee34f46b0ad8db3e6e5e8d0fc5d9402c33f6fe4ea7b16b042dcff4cec37b147",
          "sha1": "ea62a7ce77e0060cd8f009e9ba26e6300c92b07d",
          "md5": "8b3e3624a987a1706a915dc22f544a52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-c189d8a.jar",
          "url": "antibytes-gradle-utils-c189d8a.jar",
          "size": 9568,
          "sha512": "7bc3ca967f049eb0215066830718b45358c404f73ddb7eada0cce61a5938b30857d933f9ef81b68c1d0d7c17d02f84ec0b05cd14a1b5244b6bd9ce23f1a4d924",
          "sha256": "5ee34f46b0ad8db3e6e5e8d0fc5d9402c33f6fe4ea7b16b042dcff4cec37b147",
          "sha1": "ea62a7ce77e0060cd8f009e9ba26e6300c92b07d",
          "md5": "8b3e3624a987a1706a915dc22f544a52"
        }
      ]
    }
  ]
}
