{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "bf076e1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-bf076e1.jar",
          "url": "antibytes-grammar-tools-bf076e1.jar",
          "size": 59182,
          "sha512": "cba774c4e337943e9702b37e10266e7e9738e762fd2288dd501ce6f90d48dfc34aedac4d1f704c1a6fb5f009c520fbfc14c86ee73365a867bacb8bfae7c1ff3f",
          "sha256": "74054720133d415c86cf741110f3d5e53c324dc48e15df2a1d6f2bf2704e7eea",
          "sha1": "916d1e960e95d42f4a743b43409ae1fc1aafc251",
          "md5": "b7e1c23b936ffcd095ead7e75047ad1d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-bf076e1.jar",
          "url": "antibytes-grammar-tools-bf076e1.jar",
          "size": 59182,
          "sha512": "cba774c4e337943e9702b37e10266e7e9738e762fd2288dd501ce6f90d48dfc34aedac4d1f704c1a6fb5f009c520fbfc14c86ee73365a867bacb8bfae7c1ff3f",
          "sha256": "74054720133d415c86cf741110f3d5e53c324dc48e15df2a1d6f2bf2704e7eea",
          "sha1": "916d1e960e95d42f4a743b43409ae1fc1aafc251",
          "md5": "b7e1c23b936ffcd095ead7e75047ad1d"
        }
      ]
    }
  ]
}
