{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-0.2.0-SNAPSHOT.klib",
          "size": 76026,
          "sha512": "72b54b3cc34705363663b5121df394b5186293962404e5cf436bd311d9c192ffcf685ea61877aa70a06f7ad752b5d51af58d39e6c4fe6405c4eb915e8abb8e7d",
          "sha256": "2347a432af6bf20961cbb0c10706e0bccbb4ab6d86b712bd49d4b515457efc57",
          "sha1": "7a52ab6032e6527ed099c7f4faf61a1f1eacd87c",
          "md5": "0536fd606d6e7a77d8af0549b0e3938b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.2.0-SNAPSHOT-metadata.jar",
          "url": "core-iosarm64-0.2.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "5b4672d30b215ee72cdd3caee710d2c4efdf657be11d0fe02b90acf1e30cf3f1a999838c97352b4bc3f106928205e7d20222bb1034865531e83961d2f92bf8cd",
          "sha256": "9e9f2dde92611eceb52e681021cb4706100794f48fa4b34742faffe3cb1709c2",
          "sha1": "d12c046ce790d91c4a7bf6594a773d23b3505ee8",
          "md5": "c0f0385ba4deb7aa3c8a182e080cbead"
        }
      ]
    }
  ]
}
