{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-0.2.0-SNAPSHOT.klib",
          "size": 99029,
          "sha512": "44af5e67dadc3fc671ccfd3391c25d604d67fe10b24c4d5b8f94666e167f47eaf60503333a93fb6c5d52e0aff865ba6b337a77aa2f1646fb8dab740616272769",
          "sha256": "f2bced0a09e4c55e97d9910e5db46db68155e27b5c53ff80a375e579935756f6",
          "sha1": "8120e7abfc6df7e59a378b75ea126b0915fff1b2",
          "md5": "60cf57e75bf4d654ab1b5ce3bccd5365"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.2.0-SNAPSHOT-metadata.jar",
          "url": "core-iosarm64-0.2.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "8c1ef673cb059d387c1a314f1b3dc2b248e96e489427522bd36a2d06d6212b44c1c1a04aa0377c22ceddc4a95f71ecb5b747fb7e94b85f7675c31f1b30deeafc",
          "sha256": "aaefb920ba0d9c85327bb1750ee0386f8ee373007250cb7682f5d851fb5c0a43",
          "sha1": "d35d8c4fff768222a68ea0a9fb77567c23ef6e4b",
          "md5": "dee89ed59ff834bbb52ea4ee631e6799"
        }
      ]
    }
  ]
}
