{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "7dd640e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n-metadata-7dd640e-all.jar",
          "url": "banana-i18n-7dd640e-all.jar",
          "size": 670,
          "sha512": "16bf42c785fdd7f59d1ff7fb80757c335fc8afbbd0b4e0303e91ba4a6ff5e79d6a4abd10e0d5b377810c9223ee75b7ddf179f4ce3227ce9f24a082ddca302f56",
          "sha256": "4c535ec1c3845bc4c17bcfef2a9258938b59918f0c8b32a03c42feb6429d1c48",
          "sha1": "8b3e26d36186168055d40d2a6beb025ff3d16f8a",
          "md5": "9ab84e01f302d07aa872f93b5eb88ed5"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n-7dd640e.jar",
          "url": "banana-i18n-7dd640e.jar",
          "size": 26844,
          "sha512": "359112977e5cb544c2ba2129016dbabba30d2cbd8e5a9acf694b8b916352ea45f0ac1c74fd7a8d5083217ab067aa04368321c52b83ae6fb5f24979a8a39c03b4",
          "sha256": "822e399c57a0abbee637a3368f6bb6385a12910c304e33ca26f0a9cd8c7220f0",
          "sha1": "2fdee2a46c6ea688dc59d1a99cdb1b7d7aabd0aa",
          "md5": "baa58dc82ec61aa75fe56e89cfa63fc4"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/7dd640e/banana-i18n-android-7dd640e.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "7dd640e"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/7dd640e/banana-i18n-android-7dd640e.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "7dd640e"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/7dd640e/banana-i18n-jvm-7dd640e.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "7dd640e"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/7dd640e/banana-i18n-jvm-7dd640e.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "7dd640e"
      }
    }
  ]
}
