{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/d2c62a3/test-utils-annotations-d2c62a3.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "d2c62a3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-d2c62a3.klib",
          "url": "test-utils-annotations-js-d2c62a3.klib",
          "size": 9629,
          "sha512": "9636567cdeb9e3bdf398e0b48ddb2467032390032212bf8d21fbf53d77e75ea484767f889a759b43f9549cd472a5908b36f09dcd14c09e14461bf762cf8aff94",
          "sha256": "13ec3168f97d4356d791ea39b328b5a1db6ceee6f46ee285b960f1cfe011ca2b",
          "sha1": "511d9bd5f14c4ca6ca2a88e1ae20811826d23a98",
          "md5": "0139bbfccd7fcde0eb6cde618c9ec508"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-d2c62a3.klib",
          "url": "test-utils-annotations-js-d2c62a3.klib",
          "size": 9629,
          "sha512": "9636567cdeb9e3bdf398e0b48ddb2467032390032212bf8d21fbf53d77e75ea484767f889a759b43f9549cd472a5908b36f09dcd14c09e14461bf762cf8aff94",
          "sha256": "13ec3168f97d4356d791ea39b328b5a1db6ceee6f46ee285b960f1cfe011ca2b",
          "sha1": "511d9bd5f14c4ca6ca2a88e1ae20811826d23a98",
          "md5": "0139bbfccd7fcde0eb6cde618c9ec508"
        }
      ]
    }
  ]
}
