{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "e95a92e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-e95a92e.jar",
          "url": "antibytes-gradle-test-utils-e95a92e.jar",
          "size": 15099,
          "sha512": "0eb678b00f5ebce0fad4d70e95130db01f26cd58d1b6c2502d14ddbcc02bf79bd408db648fc92b7c287096b47b2c68cdef39b33f899d2e26610296f021a169a2",
          "sha256": "70405a97078c0fe230ee666602dacf319cfce0033f0a6e0ad118ddaa2cd9d6cd",
          "sha1": "13fd3461056dab8093a0e4ecf7c4e54a98c9049e",
          "md5": "dbdea5b042531ee7a7020ba6593d04d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-e95a92e.jar",
          "url": "antibytes-gradle-test-utils-e95a92e.jar",
          "size": 15099,
          "sha512": "0eb678b00f5ebce0fad4d70e95130db01f26cd58d1b6c2502d14ddbcc02bf79bd408db648fc92b7c287096b47b2c68cdef39b33f899d2e26610296f021a169a2",
          "sha256": "70405a97078c0fe230ee666602dacf319cfce0033f0a6e0ad118ddaa2cd9d6cd",
          "sha1": "13fd3461056dab8093a0e4ecf7c4e54a98c9049e",
          "md5": "dbdea5b042531ee7a7020ba6593d04d4"
        }
      ]
    }
  ]
}
