{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.0-SNAPSHOT/core-0.3.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.3.0-SNAPSHOT.klib",
          "size": 100062,
          "sha512": "af0e4ad91f1217859768632521c0e9ad494e0a763259bcdca9db9d63a55e6f572564a604efdb1496ce73cbb46d9e31ce8303f90089555ff053ece704e1914264",
          "sha256": "11ef00edd846c1b35748c20d88d969d7bd427b418b19ac1b234b734eca2648b1",
          "sha1": "d7a8516b83302aee111e62140d77fc49dd1c7243",
          "md5": "7a5c06aabb662bab856d62c9df04d38b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.3.0-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.3.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4257aa38a59518b889f97f434b85533850f087ab62b79bc6448b8fe9773d6d37859d2036b58f4f2f2568090ad4077a96c4110d7852789c219ef1c97e4fc09d0a",
          "sha256": "b54ed4870d3815d18c24342ef0b00aa83436f8d7cc00ddaf8b734c9272cb2ccf",
          "sha1": "f1dd398c501d9cf4ff9fbde0c22340ade99ea645",
          "md5": "88e73ed7f48c704857c2d80f258ec7af"
        }
      ]
    }
  ]
}
