{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "linuxMips32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-linuxmips32-0.4.0-SNAPSHOT.klib",
          "size": 105861,
          "sha512": "1a3b61a6ea3f87be15ae44e19d6827bc2954a54d4c754ed756fb30da5cc1e3549c97883434c9a916d94275f758b5d60adfbf958ce8a7ba28fe776102021c1953",
          "sha256": "7a9fdba5f18e8a8d5527dd3e28f4a0ae32e4f0dab53c75e96c40c07047b7849e",
          "sha1": "5ea11d9f6cef264835a82ce25c7b1184fac7d757",
          "md5": "3aa3574aa6291eb938958459fb92e372"
        }
      ]
    },
    {
      "name": "linuxMips32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-linuxmips32-0.4.0-SNAPSHOT-metadata.jar",
          "url": "core-linuxmips32-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "cf3b2ceabe0a07c4b6b7640061d79c0b3eda2364f608cfd375d91576c6bd6a4f4a3866377f6486c2f1d4bcb6643be595ad551150d43acdbbb609c0f599f7f14d",
          "sha256": "edd8bd27282e9e00fb971cdc645bb998d5a52e105c4bbfe7bb6c5d6ca0dfb310",
          "sha1": "a748808a1db44f8396e632d44b0cd3225bfa45c6",
          "md5": "4689031e5752e361196e1e21958d16ac"
        }
      ]
    }
  ]
}
