{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "d40a207",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-d40a207.jar",
          "url": "antibytes-coverage-d40a207.jar",
          "size": 133706,
          "sha512": "b2eef8c5696ae33782473c3f28af15b3f06ee2e8136d2eea29ea85104f527225616fac961a9d0f859aca102b319eec60b56821d764c1a3ef40aa887cdc2ed2ac",
          "sha256": "3b824f1f1729b8b449d863fa7f5116f2cd973350a1d1c9a34aba14a6c1938715",
          "sha1": "ead9eac604224757b4f20b8901fbaab8aa0b2922",
          "md5": "f3662ff32dd4e797f69e01617536e888"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "d40a207"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-d40a207.jar",
          "url": "antibytes-coverage-d40a207.jar",
          "size": 133706,
          "sha512": "b2eef8c5696ae33782473c3f28af15b3f06ee2e8136d2eea29ea85104f527225616fac961a9d0f859aca102b319eec60b56821d764c1a3ef40aa887cdc2ed2ac",
          "sha256": "3b824f1f1729b8b449d863fa7f5116f2cd973350a1d1c9a34aba14a6c1938715",
          "sha1": "ead9eac604224757b4f20b8901fbaab8aa0b2922",
          "md5": "f3662ff32dd4e797f69e01617536e888"
        }
      ]
    }
  ]
}
