{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "3e2b68f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-3e2b68f.jar",
          "url": "antibytes-gradle-test-utils-3e2b68f.jar",
          "size": 17888,
          "sha512": "d52181bfcd17bb97c874876609a3bf92bdc8ac42400e2e5ad9b3a0eb5e3da80763f2d14df6f55c747e1623c5818100990229021ac5328f16562f610fe292061a",
          "sha256": "6307a6be1ea5ba55777eb46ee1ea33f7fe1d9f370d757404f8c2b7d0f18cc83c",
          "sha1": "9992f2760a3245af7d71fdd99a899f87b8fd5635",
          "md5": "dda83cee44c97418f6815d323101cde2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-3e2b68f.jar",
          "url": "antibytes-gradle-test-utils-3e2b68f.jar",
          "size": 17888,
          "sha512": "d52181bfcd17bb97c874876609a3bf92bdc8ac42400e2e5ad9b3a0eb5e3da80763f2d14df6f55c747e1623c5818100990229021ac5328f16562f610fe292061a",
          "sha256": "6307a6be1ea5ba55777eb46ee1ea33f7fe1d9f370d757404f8c2b7d0f18cc83c",
          "sha1": "9992f2760a3245af7d71fdd99a899f87b8fd5635",
          "md5": "dda83cee44c97418f6815d323101cde2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-3e2b68f-javadoc.jar",
          "url": "antibytes-gradle-test-utils-3e2b68f-javadoc.jar",
          "size": 261,
          "sha512": "ce6cb2ec33995d90e069322cec32fcf9d9c6dc03031f76c800e79be3946429c46c7b2edbfc6f3e3d952b412021a0c842c2c553b28da7706ae8cb723b8e43f0c6",
          "sha256": "b78a00bc7ed4172a991e5d492bd57ed7b9b4746022a0019b1de29529fcb94df5",
          "sha1": "e695cea08cc54dec19ecc4c54062df51e3e4229c",
          "md5": "d2136222ea364cdc0948dd5e3b4f0c01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-3e2b68f-sources.jar",
          "url": "antibytes-gradle-test-utils-3e2b68f-sources.jar",
          "size": 3097,
          "sha512": "11b2380dcc1426e3328a46cfcf1c7ce230f7f60d49cd24dc15ae04036439b6efb4dba57d60178e13c68caea0d6d5b15a42e7d435ab6f2338de8981bc4e2ba1ee",
          "sha256": "84449ef604717ba1f93a930ef91b327d30576e87fc7e084339f4aa35bfd88878",
          "sha1": "963a93034dcf83b70cfded8b90be39c53c95e1a6",
          "md5": "6f5bb2a129d6cc2a69c92349e5673c2b"
        }
      ]
    }
  ]
}
