{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-SNAPSHOT/ktx-datetime-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-macosx64-0.4.0-SNAPSHOT.klib",
          "size": 37026,
          "sha512": "16fb022bfd4f4a0cfbdfa7dd9e3fcd34435e97431c03867815b40ad60f3197b694270108dcbf7a8efe2520f025b45fd1bf8ca267b3c241df5daa4422453b1da6",
          "sha256": "f6451b11d31358cf433be8bc539308928ff16e9c0b04161691848207b29e759e",
          "sha1": "de4e6894a229d4b9bff5d4fb53fab14d59ad42bb",
          "md5": "569eee454173205eb09048d2f589cedd"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktx-datetime-macosx64-0.4.0-SNAPSHOT-sources.jar",
          "url": "ktx-datetime-macosx64-0.4.0-SNAPSHOT-sources.jar",
          "size": 16088,
          "sha512": "2fd1093b4f66fb86460e0e5fc46d3c82d6d649e51f6fa67d86c49ee2405d528475c31f450f406b1a2be2e691d1f52d71036cf571bf342b1c7bbfdb18aacafc58",
          "sha256": "ddfeada0f92e68af51cd57f3ddcf63f5349e6ad12c9b5c93c0313015c5cc3e8e",
          "sha1": "e3f7b5b02498f31f31ff09a28221f9502399b3a2",
          "md5": "b2ce74b02e7d0b4b4cf6bb0c3c064bd4"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-macosx64-0.4.0-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-macosx64-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "52f5e546c467221e08a0a079597584bdd187954a0b7848b11c159803e6b5ef6045aa1beeed3fae53d7e27ef5666d8a1e9b2116dd165a5be78ef68c0d8a046a10",
          "sha256": "b17515f3cd62b2f7a59f1e6bb1600b797363472fe4143affa3242a5913d8ee31",
          "sha1": "bf92a563b915a49576bfaa3558e1d5364a321c8a",
          "md5": "61aff96861c1fcb136356ec342e45ae9"
        }
      ]
    }
  ]
}
