{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.dokka",
    "module": "antibytes-dokka-configuration",
    "version": "981a535",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dokka-configuration-981a535.jar",
          "url": "antibytes-dokka-configuration-981a535.jar",
          "size": 7889,
          "sha512": "c5c45fe9cbb3f08af4d37e21767402c9468f4c1f57b625ba71f8c8065a3ffe33206b138fe3fbb13e6aae445552dc4b002e7df4a7b2b7dc52155b348a007f9a29",
          "sha256": "c8a46da2c34e4f298d21913b53c32a539a364b9262a151420845066ca5c39bf9",
          "sha1": "a7e534bd7b58fe8829f4822d4c5f96042b63ecde",
          "md5": "48ed2e475414760e72ae9243059d17a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "981a535"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dokka-configuration-981a535.jar",
          "url": "antibytes-dokka-configuration-981a535.jar",
          "size": 7889,
          "sha512": "c5c45fe9cbb3f08af4d37e21767402c9468f4c1f57b625ba71f8c8065a3ffe33206b138fe3fbb13e6aae445552dc4b002e7df4a7b2b7dc52155b348a007f9a29",
          "sha256": "c8a46da2c34e4f298d21913b53c32a539a364b9262a151420845066ca5c39bf9",
          "sha1": "a7e534bd7b58fe8829f4822d4c5f96042b63ecde",
          "md5": "48ed2e475414760e72ae9243059d17a1"
        }
      ]
    }
  ]
}
