{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/6c6db5c/kmock-6c6db5c.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "6c6db5c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-linuxx64-6c6db5c.klib",
          "size": 113365,
          "sha512": "1b1b5c60ad8bae8895c523e0045c640ed8e6a256a3f231e049e78fec6872f5f9a177174aa80c60e562dd63c31bdc9bce51ed49b99ba5f80d9253d76d1ed717d4",
          "sha256": "11f68d671951e5cb7bdcbf53e732fb2be84a6a77babe265ab1f506a4b5ae3437",
          "sha1": "eaaaf26b048bc9fb370576784aefb384dfc481a7",
          "md5": "6aaf257df248a0151d1bd116fa921993"
        }
      ]
    }
  ]
}
