{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-c9500aecac-SNAPSHOT/kmock-0.1.1-c9500aecac-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-c9500aecac-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosarm64-0.1.1-c9500aecac-SNAPSHOT.klib",
          "size": 196231,
          "sha512": "ed4e6cd38d2a31185de6f40872b91b9956870f5bd492152fba230ef4f26bfb47c57a20b83171aaba73455c4bf291ad3477df62612ee0da392c4d7fce6ada2dde",
          "sha256": "60ed0f935a3768dc0665f6b2f4e1d65e9facdf38f10d3b83f488a705858d4bd2",
          "sha1": "25028d1f6b7e96efbc5313ae2af4723d9b92a2dd",
          "md5": "912e57b03459c128befca344484ba21d"
        }
      ]
    }
  ]
}
