{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/56c4547/test-utils-56c4547.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "56c4547",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm32-56c4547.klib",
          "size": 7962,
          "sha512": "2fc4ccee1addc3cb32356a025da5297edaed25947e4bfac9c334afc2882db9ce82c47607bbe56845bb5c6b570243e373989f2ed0c003c4b3cf346d44548536b4",
          "sha256": "c2b570c058f2f6a9f061c1802776841938a08d50f0d1f7815552290c4290088a",
          "sha1": "3d5c5b4cf5e2b9e21abe9bef700f8d4f3fa0169d",
          "md5": "103fede5a6124eb790461fde2db1573c"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm32-56c4547-metadata.jar",
          "url": "test-utils-iosarm32-56c4547-metadata.jar",
          "size": 261,
          "sha512": "596b0be18671ad74ad50e2a5d819253b3af4d2300ee5f5d0a7e72e29dee54918bea4480a170c372deb126d0b5bab5df9b14b1f30fce8fba0ee1d0b580b15ad8f",
          "sha256": "fd61c74f64530e77ec2a03067a76fe3ef5280904360aed319240ac3c7603402d",
          "sha1": "ea00458bab556347db6f7c7a9140ca2de168c650",
          "md5": "22d3647ad6cd7ddd8d0887a9fc2cae2a"
        }
      ]
    }
  ]
}
