{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "3e2b68f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-3e2b68f.jar",
          "url": "antibytes-dependency-helper-3e2b68f.jar",
          "size": 69703,
          "sha512": "6f2d85115bed60988a2f24ea1a820f06ce2b13ebd6a07a9881ac210fc6cefa4dce244b32cd5623d5fb2af7c7129e3c70c3e1994c8522c00a64b4a19f6d35f88a",
          "sha256": "760939c0a17492ec40257990bb34f47f24a209b54eed629f9190a0e24a97be12",
          "sha1": "ac60b99a23a8cf69cb802758912e17e9cd08d938",
          "md5": "506eef5d101f973fcde8ddab25af255d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.51.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "9.0.9"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "3e2b68f"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-3e2b68f.jar",
          "url": "antibytes-dependency-helper-3e2b68f.jar",
          "size": 69703,
          "sha512": "6f2d85115bed60988a2f24ea1a820f06ce2b13ebd6a07a9881ac210fc6cefa4dce244b32cd5623d5fb2af7c7129e3c70c3e1994c8522c00a64b4a19f6d35f88a",
          "sha256": "760939c0a17492ec40257990bb34f47f24a209b54eed629f9190a0e24a97be12",
          "sha1": "ac60b99a23a8cf69cb802758912e17e9cd08d938",
          "md5": "506eef5d101f973fcde8ddab25af255d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-3e2b68f-javadoc.jar",
          "url": "antibytes-dependency-helper-3e2b68f-javadoc.jar",
          "size": 261,
          "sha512": "5de492c414e19050c65d99ff5e7566d9e471d2783ce2a9ebbd15e1bd14686d7b8b03a95d412ced9db6836a7bf6bb8f02e0a3ce295f8250aacb201b61cfd41b5f",
          "sha256": "1a95336f1d864205519d2eb01c7b509a2820a04a78fdf3c983a9b9c6ace88cbb",
          "sha1": "e5df7c85531d50074f037d9a7c759111b1267153",
          "md5": "bdeaca3885ec34816e6d9af750ee273a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-3e2b68f-sources.jar",
          "url": "antibytes-dependency-helper-3e2b68f-sources.jar",
          "size": 9186,
          "sha512": "9bf670be408f63271cd3b1e2f2028a9d95410535c0f1e2485fa694d7253c22baf97cb9acc2a57cd6c3aff1d752489d438fe561e5e0feb6c2f60d06d0504c8d06",
          "sha256": "5e1c96ac213777dd2bf5a8cd517d80ad43fb9a3aebaaba6004dedab0afa90373",
          "sha1": "02dc4bf12a4d28c4d25c422e1805b7cd28c093d7",
          "md5": "ac53fe7e60d2cf980e79812120f6e762"
        }
      ]
    }
  ]
}
