{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "c657a3f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-c657a3f.jar",
          "url": "antibytes-android-application-configuration-c657a3f.jar",
          "size": 63996,
          "sha512": "859544c8879ba67e8c796db483bff73396b9a257f84e937b663402fdf84f5e6bdae19df7b68d4d58701a718f607dbb34c5b40743b3b1e10f8026ebaaeb347c72",
          "sha256": "921cfc128b05ea1799faa301ae9ed2778defde57efd129e68240fa73c9ecabda",
          "sha1": "0cc62ee4403d8519e27529ead92fc89b9fdac326",
          "md5": "16841096f3e0b27bb71459d73b114475"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "c657a3f"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-c657a3f.jar",
          "url": "antibytes-android-application-configuration-c657a3f.jar",
          "size": 63996,
          "sha512": "859544c8879ba67e8c796db483bff73396b9a257f84e937b663402fdf84f5e6bdae19df7b68d4d58701a718f607dbb34c5b40743b3b1e10f8026ebaaeb347c72",
          "sha256": "921cfc128b05ea1799faa301ae9ed2778defde57efd129e68240fa73c9ecabda",
          "sha1": "0cc62ee4403d8519e27529ead92fc89b9fdac326",
          "md5": "16841096f3e0b27bb71459d73b114475"
        }
      ]
    }
  ]
}
