{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.coverage",
    "module": "antibytes-coverage",
    "version": "15fbbaa",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-15fbbaa.jar",
          "url": "antibytes-coverage-15fbbaa.jar",
          "size": 135187,
          "sha512": "841d3f4a81bff881e386b8b210a904d4ba510d1cc02444cf001034c617780890b005896ef1389922a95b1a61d64442db3ee50270e642391353b194b0e8738e10",
          "sha256": "97a9b4bb77a66b0b374ae301f93e450218685cc21d7f480bf278a295ce38bb9c",
          "sha1": "575c60d6f6fc12cade7b24ebed2f85046b6ac51f",
          "md5": "5e0b4f6897aa4ff88e6fce01a92023f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "15fbbaa"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-15fbbaa.jar",
          "url": "antibytes-coverage-15fbbaa.jar",
          "size": 135187,
          "sha512": "841d3f4a81bff881e386b8b210a904d4ba510d1cc02444cf001034c617780890b005896ef1389922a95b1a61d64442db3ee50270e642391353b194b0e8738e10",
          "sha256": "97a9b4bb77a66b0b374ae301f93e450218685cc21d7f480bf278a295ce38bb9c",
          "sha1": "575c60d6f6fc12cade7b24ebed2f85046b6ac51f",
          "md5": "5e0b4f6897aa4ff88e6fce01a92023f4"
        }
      ]
    }
  ]
}
