{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/8a321a1/test-utils-annotations-junit4-8a321a1.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "8a321a1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-iossimulatorarm64-8a321a1.klib",
          "size": 11438,
          "sha512": "5700ba1a32678fc80c38f747337de30ce4835055c7169a46ec00940499756eae4190bdb9378de5deb02e77521a13a55900c2cdc615d1a53e28932fd92b9ffc70",
          "sha256": "c839fe2faf3ddf73845d5dcdff0c9c283a6e2bfc9cf05544ff8e35cbc1107a5f",
          "sha1": "1cecf9b278f26825878551578a6ce863a1497ab4",
          "md5": "5a4768817d18ac1138b6e5e9f61ba9cb"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-iossimulatorarm64-8a321a1-metadata.jar",
          "url": "test-utils-annotations-junit4-iossimulatorarm64-8a321a1-metadata.jar",
          "size": 261,
          "sha512": "62f1ec2e4f9ddd394d3fe0bb1cdd32832c982e5f811a855e72eb693753e448add47b138ede752da652834e10dadfaf211a2c085518e17931f421b207f610ed37",
          "sha256": "363bd3fd8bcd1d80a6450fcb76d4c989499e8047b4d7d32a0f2e66a2645a6c02",
          "sha1": "2d20bef596f097d6bdd8113dfa241a484bd46f0d",
          "md5": "74359cb4137de1bd3a6b0b29dec1122b"
        }
      ]
    }
  ]
}
