{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.kmp",
    "module": "antibytes-kmp-configuration",
    "version": "8068699",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-8068699.jar",
          "url": "antibytes-kmp-configuration-8068699.jar",
          "size": 67704,
          "sha512": "a67cd2fc2799ddf072680c21cbdfa5b0d6d952be4210e7d66060e61c97fb02e046684a403f85a507460c1854b7e7f512d89302d9dcb256ddb37aeaa4f2c2008e",
          "sha256": "9518e203caf215381c0ba2d409676e3e2401e921d12128e085cd18edb58644d6",
          "sha1": "517b32df0c9775ffc45c0bdb8b76dc9ea132bffd",
          "md5": "9a346ab3bd9872df07019d73d4fb7405"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "8068699"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-kmp-configuration-8068699.jar",
          "url": "antibytes-kmp-configuration-8068699.jar",
          "size": 67704,
          "sha512": "a67cd2fc2799ddf072680c21cbdfa5b0d6d952be4210e7d66060e61c97fb02e046684a403f85a507460c1854b7e7f512d89302d9dcb256ddb37aeaa4f2c2008e",
          "sha256": "9518e203caf215381c0ba2d409676e3e2401e921d12128e085cd18edb58644d6",
          "sha1": "517b32df0c9775ffc45c0bdb8b76dc9ea132bffd",
          "md5": "9a346ab3bd9872df07019d73d4fb7405"
        }
      ]
    }
  ]
}
