{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.settings",
    "module": "antibytes-dependency-settings",
    "version": "b821e91",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "b821e91"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-b821e91.jar",
          "url": "antibytes-dependency-settings-b821e91.jar",
          "size": 15130,
          "sha512": "408cef810aa10c76cada38f5ccbee1da0aa0785dafec0258864a5124d36ea2db6afb824dfc8edaba320234a0b18eed31c1d925fabc762ac81bcccbb402722509",
          "sha256": "9c374c63915acb0f8bf2db1fe18698df574a394277b9260b0db217024f27c98e",
          "sha1": "13f18d2ee8e4cd4c342b72621976db63f48ec56e",
          "md5": "68e957a7dd08db6a8b82b2897e4e2be6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "b821e91"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-b821e91.jar",
          "url": "antibytes-dependency-settings-b821e91.jar",
          "size": 15130,
          "sha512": "408cef810aa10c76cada38f5ccbee1da0aa0785dafec0258864a5124d36ea2db6afb824dfc8edaba320234a0b18eed31c1d925fabc762ac81bcccbb402722509",
          "sha256": "9c374c63915acb0f8bf2db1fe18698df574a394277b9260b0db217024f27c98e",
          "sha1": "13f18d2ee8e4cd4c342b72621976db63f48ec56e",
          "md5": "68e957a7dd08db6a8b82b2897e4e2be6"
        }
      ]
    }
  ]
}
