{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/6be4f13/test-utils-6be4f13.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "6be4f13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iossimulatorarm64-6be4f13.klib",
          "size": 14402,
          "sha512": "6ccf77678659d6aa7a19d5804f04f15e1ffbb19da6f07aa411fc20dc8fb1d25a8ae544f9b5c38b895f230349b93bab81bfaa1679d7e96de9aea56cbb9c293f6f",
          "sha256": "2842406ee09b5960ca932349a9dd9f950c7a6972f99b0664f413038235605023",
          "sha1": "f2bdb6636ad7f58af21706f085e0000c009b3b7a",
          "md5": "2653a2e2afd8371c43126d57e0d0ac8a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iossimulatorarm64-6be4f13-metadata.jar",
          "url": "test-utils-iossimulatorarm64-6be4f13-metadata.jar",
          "size": 261,
          "sha512": "d55194b9e9966daaae6c7b4be7f9428f0b8285c137cae115f757109ffbd5f25fff6f167b9fad1d03139c11b1c6a8d3f38e12132ad32c94f1f371fb8e522e4c5f",
          "sha256": "08bec2e6f386a3f563a772b801d8aebe6daf9ce366b9c9d501ebefa3d7a00c7f",
          "sha1": "69bca74625c1843992783363842f346a457befa0",
          "md5": "c846f23567dc5eb25bd01361b3a706be"
        }
      ]
    }
  ]
}
