{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "fb654eb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-metadata-fb654eb.jar",
          "url": "kmock-fb654eb.jar",
          "size": 20404,
          "sha512": "6b4b5b9768ba52f10db345b6f2eb8f9acecd631871b1d160e0a1c1c3808ea7b55c243d251cadff384752dedf2925a5c64855a5069c893336e9e0413f49fffdb6",
          "sha256": "3111cf2aa666b0e0f71b27c309eae5b45d5d78392410c72da65a22e0c8d83c50",
          "sha1": "7ab26dcdede9f7a4902d6f41b173d86c703538f4",
          "md5": "6ba30d53fde949f44160cd660f7e36b6"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/fb654eb/kmock-android-fb654eb.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "fb654eb"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/fb654eb/kmock-android-fb654eb.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "fb654eb"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/fb654eb/kmock-iosarm64-fb654eb.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "fb654eb"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/fb654eb/kmock-iosx64-fb654eb.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "fb654eb"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/fb654eb/kmock-js-fb654eb.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "fb654eb"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/fb654eb/kmock-js-fb654eb.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "fb654eb"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/fb654eb/kmock-jvm-fb654eb.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "fb654eb"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/fb654eb/kmock-jvm-fb654eb.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "fb654eb"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/fb654eb/kmock-linuxx64-fb654eb.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "fb654eb"
      }
    }
  ]
}
