{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "c657a3f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-c657a3f.jar",
          "url": "antibytes-grammar-tools-c657a3f.jar",
          "size": 59182,
          "sha512": "300b62b53ea27dc3be26e5d39b6b1ae16821665a81d9e7d1cd1eeea2f94af0f462aa87109c88db4bdee7c8b429320689a4a5751c946b4fc0415b3d782d6d016c",
          "sha256": "82df903bb3116d4b2b957540cdcc08a5de9fc0667f9732a99b2754b2108cf657",
          "sha1": "aa9ad353550c1e7f5115569148b21e2ae1985f6f",
          "md5": "36f951f566acbfe855fc6e3dd470a373"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-c657a3f.jar",
          "url": "antibytes-grammar-tools-c657a3f.jar",
          "size": 59182,
          "sha512": "300b62b53ea27dc3be26e5d39b6b1ae16821665a81d9e7d1cd1eeea2f94af0f462aa87109c88db4bdee7c8b429320689a4a5751c946b4fc0415b3d782d6d016c",
          "sha256": "82df903bb3116d4b2b957540cdcc08a5de9fc0667f9732a99b2754b2108cf657",
          "sha1": "aa9ad353550c1e7f5115569148b21e2ae1985f6f",
          "md5": "36f951f566acbfe855fc6e3dd470a373"
        }
      ]
    }
  ]
}
