{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/f384302/test-utils-annotations-junit5-f384302.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "f384302",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-macosarm64-f384302.klib",
          "size": 7066,
          "sha512": "3fce6cf4de8d7383b91fad3cedc3f5f321362fd242520ea5a9008c15c2fcc89219658403d7f1e14a33e15f9b2ceb177bfff5320ce8457178764dd22b6d4fe773",
          "sha256": "4af6d8dddb24f2b1b6e7e59f6b0b7f829f6378df4df88fad0064575e04426645",
          "sha1": "73563497243133e01d5e219452f81c33438f89f8",
          "md5": "ed8e72481b264e64f14783d1ff15f3e1"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-macosarm64-f384302-metadata.jar",
          "url": "test-utils-annotations-junit5-macosarm64-f384302-metadata.jar",
          "size": 261,
          "sha512": "2060cbd9d52aef76bcf827df5a60fe11907e5b6a8c2695ba545aac2e72040df731c199adb6baa4a00980166b7766754d66656fd547cd61e919a282b9b1735b8d",
          "sha256": "5577626f533917d51d93ab064ee3a4bace2845845364f2cbc51843c721be1d78",
          "sha1": "8bf3d85fdbc710241eba0e3bc8be56ff6db57474",
          "md5": "071c0b422ec06b446e450d7c375cf84f"
        }
      ]
    }
  ]
}
