{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.2.2-SNAPSHOT/kmock-0.2.2-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.2.2-SNAPSHOT.klib",
          "url": "kmock-js-0.2.2-SNAPSHOT.klib",
          "size": 216790,
          "sha512": "0dc292312355608fe77cc30d5a8b44e88b81b10c61b8f61101267582262a4caf9ab2c660f3a315f86bb2672ebca460bea11280610b83c55012589b435f251060",
          "sha256": "e1580792f92ac937a12c83ea0db89111b5ad36b680e4faaf360fb48ff13a86d5",
          "sha1": "8c6655cf54c9c6ee622af57589bfcfe8250a69aa",
          "md5": "040bb32af16e9c70d2da58785d9fdd6c"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.2.2-SNAPSHOT.klib",
          "url": "kmock-js-0.2.2-SNAPSHOT.klib",
          "size": 216790,
          "sha512": "0dc292312355608fe77cc30d5a8b44e88b81b10c61b8f61101267582262a4caf9ab2c660f3a315f86bb2672ebca460bea11280610b83c55012589b435f251060",
          "sha256": "e1580792f92ac937a12c83ea0db89111b5ad36b680e4faaf360fb48ff13a86d5",
          "sha1": "8c6655cf54c9c6ee622af57589bfcfe8250a69aa",
          "md5": "040bb32af16e9c70d2da58785d9fdd6c"
        }
      ]
    }
  ]
}
