{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.2.0-rc01-SNAPSHOT/kmock-0.2.0-rc01-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.2.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-0.2.0-rc01-SNAPSHOT.aar",
          "size": 347722,
          "sha512": "aaacc8a57a3554822c9a303055c8d7351592212674106db5a8ee1530a16ae6aa686c0ae7e7da1ea3db9880c311348144600c65cabc4ebc4959c6a7c0421f9752",
          "sha256": "2452f12785c95225ee19826cd82f0ef089fef8da81c4618b41c683db52e284fd",
          "sha1": "408a7c348ac2eca47249d6653f7cb220c0641f6a",
          "md5": "78152274b57f5115f716d57b5c1e2e02"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-0.2.0-rc01-SNAPSHOT.aar",
          "size": 347722,
          "sha512": "aaacc8a57a3554822c9a303055c8d7351592212674106db5a8ee1530a16ae6aa686c0ae7e7da1ea3db9880c311348144600c65cabc4ebc4959c6a7c0421f9752",
          "sha256": "2452f12785c95225ee19826cd82f0ef089fef8da81c4618b41c683db52e284fd",
          "sha1": "408a7c348ac2eca47249d6653f7cb220c0641f6a",
          "md5": "78152274b57f5115f716d57b5c1e2e02"
        }
      ]
    }
  ]
}
