{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.2.0-rc01-SNAPSHOT/kmock-0.2.0-rc01-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.2.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-0.2.0-rc01-SNAPSHOT.aar",
          "size": 352557,
          "sha512": "ad9f538646269d84297a4c8173664ef292074d5a3e1df0a1c7e130bc8f5371644545661b4de5ad2942f6ec6d4fffd2589bf9e68764272d29ef88c4e7826380ae",
          "sha256": "aac6dfc9ddc0537e9af95cd0326cebc2d3e9ec2e2a56cb31fb95b7a4e3269026",
          "sha1": "977845bb5e3aa4ffb6ee5276854d8cef6d048d54",
          "md5": "f7080d62f3a33c19717e5b9e59ae037c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-0.2.0-rc01-SNAPSHOT.aar",
          "size": 352557,
          "sha512": "ad9f538646269d84297a4c8173664ef292074d5a3e1df0a1c7e130bc8f5371644545661b4de5ad2942f6ec6d4fffd2589bf9e68764272d29ef88c4e7826380ae",
          "sha256": "aac6dfc9ddc0537e9af95cd0326cebc2d3e9ec2e2a56cb31fb95b7a4e3269026",
          "sha1": "977845bb5e3aa4ffb6ee5276854d8cef6d048d54",
          "md5": "f7080d62f3a33c19717e5b9e59ae037c"
        }
      ]
    }
  ]
}
