{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "a3799ae",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-a3799ae.jar",
          "url": "antibytes-versioning-a3799ae.jar",
          "size": 24286,
          "sha512": "77d9f1a8d66a467029c0afae721de8793301e2d5c819de010f80d37ec39cdca563a1768b9beecd91204434871c12ef1aadedd70b036c40f80f36ce697fd0a5bf",
          "sha256": "ef621ad549bc280374fade96bf2d3893f9180275681ad6f5bc932db284514483",
          "sha1": "7f9ad71370f2e9d8bbcc3f02c40f453cf17afa01",
          "md5": "7d288b73b429ae515d2ec412874b8de3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-a3799ae.jar",
          "url": "antibytes-versioning-a3799ae.jar",
          "size": 24286,
          "sha512": "77d9f1a8d66a467029c0afae721de8793301e2d5c819de010f80d37ec39cdca563a1768b9beecd91204434871c12ef1aadedd70b036c40f80f36ce697fd0a5bf",
          "sha256": "ef621ad549bc280374fade96bf2d3893f9180275681ad6f5bc932db284514483",
          "sha1": "7f9ad71370f2e9d8bbcc3f02c40f453cf17afa01",
          "md5": "7d288b73b429ae515d2ec412874b8de3"
        }
      ]
    }
  ]
}
