{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/231a33c/test-utils-231a33c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "231a33c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-231a33c.klib",
          "url": "test-utils-js-231a33c.klib",
          "size": 5477,
          "sha512": "c1a5009a0c6b962e327daee0ca5e968b8064c7702c6ed6ee60952aec14897d30609382631fb96d3d9ea6e5e1b11bafa22523173c57939eb69bf83332a442e932",
          "sha256": "1d7c07eac0fb02940096c174f2e99c3f7af576b003ccae60d8798114e2fde368",
          "sha1": "3f746d59395616008c3cb4dfe66d749b4040d8b7",
          "md5": "d387c485ed471a3c581dac84514abeac"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-231a33c.klib",
          "url": "test-utils-js-231a33c.klib",
          "size": 5477,
          "sha512": "c1a5009a0c6b962e327daee0ca5e968b8064c7702c6ed6ee60952aec14897d30609382631fb96d3d9ea6e5e1b11bafa22523173c57939eb69bf83332a442e932",
          "sha256": "1d7c07eac0fb02940096c174f2e99c3f7af576b003ccae60d8798114e2fde368",
          "sha1": "3f746d59395616008c3cb4dfe66d749b4040d8b7",
          "md5": "d387c485ed471a3c581dac84514abeac"
        }
      ]
    }
  ]
}
