{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "f266a0f-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-f266a0f-SNAPSHOT.jar",
          "url": "antibytes-gradle-utils-f266a0f-SNAPSHOT.jar",
          "size": 9568,
          "sha512": "0a8567d8fc09d29246c7a26937742036b2bc1d10662e092b3abcee4d2dfa561719e62a5dfa5e804193d08e41a918e49d1ebdde215a303c49b7ecbc82457749b8",
          "sha256": "5d03670f373b6fd89ce2a1b12e659d88a20340917c37b8d1f8f6bc7e7e2aa421",
          "sha1": "bc814c87d7fea3f0681187c1b5ed2617d903e31a",
          "md5": "998a7e440d9dc4154d531f9c37a6af79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-f266a0f-SNAPSHOT.jar",
          "url": "antibytes-gradle-utils-f266a0f-SNAPSHOT.jar",
          "size": 9568,
          "sha512": "0a8567d8fc09d29246c7a26937742036b2bc1d10662e092b3abcee4d2dfa561719e62a5dfa5e804193d08e41a918e49d1ebdde215a303c49b7ecbc82457749b8",
          "sha256": "5d03670f373b6fd89ce2a1b12e659d88a20340917c37b8d1f8f6bc7e7e2aa421",
          "sha1": "bc814c87d7fea3f0681187c1b5ed2617d903e31a",
          "md5": "998a7e440d9dc4154d531f9c37a6af79"
        }
      ]
    }
  ]
}
