{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "79a4505",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-79a4505.jar",
          "url": "antibytes-coverage-79a4505.jar",
          "size": 128528,
          "sha512": "b581dbc0748b2d91587a9f56cbd053a354737ff7c42add48b29e931321b4194124b50d5f002f8c8c09a869ae68659b8e0c2e79ecddfbd86c983e9f5cf3a7b6aa",
          "sha256": "06cf5191bb05911e72da8949ad562fde71178470e4501dfe2386ee1fe5b6e1c6",
          "sha1": "cb46c031a292894a871ea6f504c940d4ea0b1953",
          "md5": "6c9aca8282f06e282d5dc990d2f82264"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "79a4505"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-79a4505.jar",
          "url": "antibytes-coverage-79a4505.jar",
          "size": 128528,
          "sha512": "b581dbc0748b2d91587a9f56cbd053a354737ff7c42add48b29e931321b4194124b50d5f002f8c8c09a869ae68659b8e0c2e79ecddfbd86c983e9f5cf3a7b6aa",
          "sha256": "06cf5191bb05911e72da8949ad562fde71178470e4501dfe2386ee1fe5b6e1c6",
          "sha1": "cb46c031a292894a871ea6f504c940d4ea0b1953",
          "md5": "6c9aca8282f06e282d5dc990d2f82264"
        }
      ]
    }
  ]
}
