{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "54a39ff",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-54a39ff.jar",
          "url": "kmock-gradle-54a39ff.jar",
          "size": 49471,
          "sha512": "f3e448004c7710170b927c7d71306848e373ab78641a7c584741b3c4434b6eb0e7024ebb02bf1a420b2ce137e7178c2a5fb4bc6cf986a9936c33206c67b2d642",
          "sha256": "0dbc368c7767771ab24cf84fad75ccbe58911d96ac14a08b799649f56ee6ba0d",
          "sha1": "c648ad8eaabb09b6c0b6ac5e786b87221a3366d2",
          "md5": "f8b3109f1f9e71adb71c6e87d57e7d9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-54a39ff.jar",
          "url": "kmock-gradle-54a39ff.jar",
          "size": 49471,
          "sha512": "f3e448004c7710170b927c7d71306848e373ab78641a7c584741b3c4434b6eb0e7024ebb02bf1a420b2ce137e7178c2a5fb4bc6cf986a9936c33206c67b2d642",
          "sha256": "0dbc368c7767771ab24cf84fad75ccbe58911d96ac14a08b799649f56ee6ba0d",
          "sha1": "c648ad8eaabb09b6c0b6ac5e786b87221a3366d2",
          "md5": "f8b3109f1f9e71adb71c6e87d57e7d9e"
        }
      ]
    }
  ]
}
