{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.3.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc01-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc01-SNAPSHOT.jar",
          "size": 67326,
          "sha512": "9e157738cb84ad6ecd97dec83b0d546837161cddd895efccd8d67f2e963a4a4eaa129322df84ce982fb89a71b91a43123882357faae39604b0b4f9637069f940",
          "sha256": "98a2d4ebce3d4478ee0e0ecdcef27d497e74880a00fe29d354b349ce3fbd8dec",
          "sha1": "73ee784867938af80ac92e41f24e7362d2b6f2c4",
          "md5": "c52a860c55b8c295192121e2686b489b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.21-1.0.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc01-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc01-SNAPSHOT.jar",
          "size": 67326,
          "sha512": "9e157738cb84ad6ecd97dec83b0d546837161cddd895efccd8d67f2e963a4a4eaa129322df84ce982fb89a71b91a43123882357faae39604b0b4f9637069f940",
          "sha256": "98a2d4ebce3d4478ee0e0ecdcef27d497e74880a00fe29d354b349ce3fbd8dec",
          "sha1": "73ee784867938af80ac92e41f24e7362d2b6f2c4",
          "md5": "c52a860c55b8c295192121e2686b489b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc01-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.3.0-rc01-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "6d8ba90f8f4872fde12cf28864a2495019db632f0efec44198c55295c3d075c0bc11df28ef41e08a77fa569e539dc1620461928f746d473e80d89c07a1db4921",
          "sha256": "5d0c8abfffafe19b38bf4f0c47065146a879fc4acecaacd4375c4b7bcbe0a2ac",
          "sha1": "f64b8505c85aee9b40d4500719c6b587fd1df95c",
          "md5": "a12f24d218bea61acb41ca768c8858ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc01-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.3.0-rc01-SNAPSHOT-sources.jar",
          "size": 13671,
          "sha512": "eca92dec3d9ec85986393ed8f119cc8f54b59e304a6a709714d738da802d1e4f3ed242b6329e3187215bd302054caaeaa9176a36012f9babd313573d9f52a81d",
          "sha256": "efe488dc786b6b9e469ba21d12182391a2249200be7ad20676ce768d3c441a3f",
          "sha1": "94663931544e869aaa1678399a77f7a0f24e5a4e",
          "md5": "b3e6e5b8bc2ee1287050e4bdaf106c31"
        }
      ]
    }
  ]
}
