{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "99646d5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-99646d5.jar",
          "url": "antibytes-gradle-test-utils-99646d5.jar",
          "size": 15071,
          "sha512": "ba46df5e45786da692825ceaa1c583ef9633afab854d1fdb21e2cd57847bcba0591d6ea1514bf5eeced645b51cf1b559256f28a08ba3312ea817299c8ab1239d",
          "sha256": "c17843ba867c799bf4be0e1765d3bc8ffe874dd8282e3adb9ca883c0b9d1b1bc",
          "sha1": "e38aff0dceb59eb76e88fcc9a19a62afd7f39e99",
          "md5": "c4513228f49d760fd850264f4d4fdcaa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-99646d5.jar",
          "url": "antibytes-gradle-test-utils-99646d5.jar",
          "size": 15071,
          "sha512": "ba46df5e45786da692825ceaa1c583ef9633afab854d1fdb21e2cd57847bcba0591d6ea1514bf5eeced645b51cf1b559256f28a08ba3312ea817299c8ab1239d",
          "sha256": "c17843ba867c799bf4be0e1765d3bc8ffe874dd8282e3adb9ca883c0b9d1b1bc",
          "sha1": "e38aff0dceb59eb76e88fcc9a19a62afd7f39e99",
          "md5": "c4513228f49d760fd850264f4d4fdcaa"
        }
      ]
    }
  ]
}
