{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/fc88d6a/test-utils-annotations-junit4-fc88d6a.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "fc88d6a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "linuxMipsel32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-linuxmipsel32-fc88d6a.klib",
          "size": 11397,
          "sha512": "04f7531df1f89685f2a2c0c06129e423219ba5f56467e8ebb0a07e17a27ad69234bb11d5ed0ff107ad7ef6620df4ca5d12046c33b5b16e50627cce807724fb4a",
          "sha256": "d0ac6dda455b39d38781efb76cfa7636eb055255d33426d7b2cc94e72a4506bf",
          "sha1": "063ae5f60d5f7f7c10867f245bcbb4da89b0c344",
          "md5": "52bf6d1e731c05b11c42afb644f0fbe3"
        }
      ]
    },
    {
      "name": "linuxMipsel32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-linuxmipsel32-fc88d6a-metadata.jar",
          "url": "test-utils-annotations-junit4-linuxmipsel32-fc88d6a-metadata.jar",
          "size": 261,
          "sha512": "80c09a620f42de989339343b5160ba46cdb4a0c47333adcf22bb5223a40a172988913ec5d54935d2327527d2c99f292c0df6c2bb33404f67ceae35aa4d2766ca",
          "sha256": "d4474eee3ffefda5a51a4d621259ebf21e9d8b55473e0d9a66cbbd81455b9a81",
          "sha1": "5fa3a8e1f9228a1af423b1cdeaf01f508b5acada",
          "md5": "355f6aa5f421a48a64e7a95d379e3d60"
        }
      ]
    }
  ]
}
