{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/2271584/kmock-2271584.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "2271584",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "c3e5acf"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-linuxx64-2271584.klib",
          "size": 102143,
          "sha512": "db79e4333157654b8b974f4441c86fe16e0eb36a03509ae0c734630cf05c59a3ff966da3a676c2a2d7c869b4a468d05b183ae83c6a5a4048fc104ab119209253",
          "sha256": "e6061ef36adb3f687e8f7d76419739274edbf51c849b547f00389b13052b2953",
          "sha1": "781bcf6e6f453e2b640aa8ff7321a5ab00fe2e55",
          "md5": "270f2ac21952d8d0e29c700beef73380"
        }
      ]
    }
  ]
}
