{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-SNAPSHOT/ktx-datetime-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-watchosx86-0.4.0-SNAPSHOT.klib",
          "size": 34668,
          "sha512": "83039bb569b65ae83ccd25f1105acdc30ef5b45b8d9a58dd4a5f2e24c7d8da260b9def4dffa06f442d668821277dcfddcae9b24bab937cb8412c1baf30571e4c",
          "sha256": "4cd1a2cfdd3e6b229c9f9a771aed948d5e3cdb55953ad8df08f19294765e4f4a",
          "sha1": "5247d994d7267013c1984b0dce2bc3c6e9f42a3d",
          "md5": "07876aec2006dd07a1e66c365be2b7bb"
        }
      ]
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-watchosx86-0.4.0-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-watchosx86-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "db448d1abcdce98da0632dd1cd18c84df7dcbe132f2e5184f54bcb74cedcffc11e9164781a51f4af8d546b362c9fc21e495761e56aa45f4a9f3ecc4666efdef2",
          "sha256": "552904ba0e8f31814b4e41ec9a42a8d66b1552dfba32e143423b49bd5dafe985",
          "sha1": "1fddadd6b44050570085277b9e0b2a4fb86e8739",
          "md5": "b44fb092cbd3d11c7d86bda982209f91"
        }
      ]
    }
  ]
}
