{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/8066bd0/test-utils-annotations-junit4-8066bd0.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "8066bd0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-tvosarm64-8066bd0.klib",
          "size": 11362,
          "sha512": "761afda9974c6eec9de1127cb5f54857e22583b9da741239ba3e4f1a9a6a53a940a24d7c7cf7cba74d1256d5ef46b934da6702119ec06837ffefec3739b0d59a",
          "sha256": "a8db34652bf5fb9b8fcb2fa9d314e92523afed4f8ed5bce1c389d9e5ea9be9ea",
          "sha1": "0ef1776028019f96993890ee25dc8230752fa5fc",
          "md5": "8fc3d1db6ebc267d998f39447659336d"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-tvosarm64-8066bd0-metadata.jar",
          "url": "test-utils-annotations-junit4-tvosarm64-8066bd0-metadata.jar",
          "size": 261,
          "sha512": "79736e0132a7d01e43d193819e3f8ede2e82dcfdd9b7d6d0ae8eb240a61d35e3e2a7a21e79b6c09fc53ebf995d8c87d84dde1a4135a08d508f18bd6982a19852",
          "sha256": "bb05e439d1dcf66b8bb7388eb583283a1f164f0370349276de2130012788754f",
          "sha1": "c8ad4898c3d6dbad3b59fae5a659fc43ab446d8b",
          "md5": "dd89ab2cb91dd625099a5e8cd7f3d7c0"
        }
      ]
    }
  ]
}
