{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "a5c3c8a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-a5c3c8a.jar",
          "url": "kmock-gradle-a5c3c8a.jar",
          "size": 33058,
          "sha512": "46be337f4d68cbc96de24c95288ca78aee6478c0b9de35ed84e6417a0a8ce03573df340e363bca8a0de20d3bd0bd6b3baceae68b0e0f302f24256fabfe34c331",
          "sha256": "aa0b83f9cc5871eb46b9e7708ca6e527e7288a9609bb9fe358a58b2de3911f40",
          "sha1": "4df004de86fc7b5a0eb97f0d4a2559f45f12c164",
          "md5": "c8ca0f8e366d8d3a024914217f29c711"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-a5c3c8a.jar",
          "url": "kmock-gradle-a5c3c8a.jar",
          "size": 33058,
          "sha512": "46be337f4d68cbc96de24c95288ca78aee6478c0b9de35ed84e6417a0a8ce03573df340e363bca8a0de20d3bd0bd6b3baceae68b0e0f302f24256fabfe34c331",
          "sha256": "aa0b83f9cc5871eb46b9e7708ca6e527e7288a9609bb9fe358a58b2de3911f40",
          "sha1": "4df004de86fc7b5a0eb97f0d4a2559f45f12c164",
          "md5": "c8ca0f8e366d8d3a024914217f29c711"
        }
      ]
    }
  ]
}
