{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "e2ca35b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-e2ca35b.jar",
          "url": "antibytes-configuration-e2ca35b.jar",
          "size": 49663,
          "sha512": "1b34f3f0fb20a57258c64c5ad43db16f6dacf4f17a6f6f9972cdcc3639dc9cdd32378e7363e6b6e8bcfdc93ef883e7f14f2cad55bc90f0bfcec8581e16391eda",
          "sha256": "ee2d04f67accc17d90bd34715e1968cda0ffcaced415d4715c0c7fbc55d3667f",
          "sha1": "accf4a5420bac61fb6ddb6e080822e569298b8d6",
          "md5": "32089272fd05ead588f47cc162194f6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "e2ca35b"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-e2ca35b.jar",
          "url": "antibytes-configuration-e2ca35b.jar",
          "size": 49663,
          "sha512": "1b34f3f0fb20a57258c64c5ad43db16f6dacf4f17a6f6f9972cdcc3639dc9cdd32378e7363e6b6e8bcfdc93ef883e7f14f2cad55bc90f0bfcec8581e16391eda",
          "sha256": "ee2d04f67accc17d90bd34715e1968cda0ffcaced415d4715c0c7fbc55d3667f",
          "sha1": "accf4a5420bac61fb6ddb6e080822e569298b8d6",
          "md5": "32089272fd05ead588f47cc162194f6d"
        }
      ]
    }
  ]
}
