{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/039adf2/test-utils-039adf2.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "039adf2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-039adf2.jar",
          "size": 17516,
          "sha512": "a8fc52d8455d8a0884b0ffaf48e8138294d2159e19e3a6ae7c95b91a9f23268c0af19821a6cd2b39db2a694fba459a5dacfb9072640fc433a03885e8e8351e7f",
          "sha256": "f88d9b8096db43991bb2e430f625beb919fc7766d7d837de6d824960891a7dbd",
          "sha1": "f10f34902e0beb19ce8d5a26ca8a951db89f2604",
          "md5": "d012160c05e6736096096fff7641f14d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-039adf2.jar",
          "size": 17516,
          "sha512": "a8fc52d8455d8a0884b0ffaf48e8138294d2159e19e3a6ae7c95b91a9f23268c0af19821a6cd2b39db2a694fba459a5dacfb9072640fc433a03885e8e8351e7f",
          "sha256": "f88d9b8096db43991bb2e430f625beb919fc7766d7d837de6d824960891a7dbd",
          "sha1": "f10f34902e0beb19ce8d5a26ca8a951db89f2604",
          "md5": "d012160c05e6736096096fff7641f14d"
        }
      ]
    }
  ]
}
