{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-versioning",
    "version": "e95a92e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-e95a92e.jar",
          "url": "antibytes-versioning-e95a92e.jar",
          "size": 15815,
          "sha512": "8098af3b1af5826306329758a9fe8eb9ac2b309dd4d6cd8165c5c1a70efe5fe885981a61eec6d0e2eed78a474e5872a7a52460dbd4b9e771fa78cdb88a2fb862",
          "sha256": "bc4a7c405edc35e3ce4cf2eeaee575add81e1fcd144118efac588c169ca17d1f",
          "sha1": "15f365386c16e304135a2f94fdf1b98244abb138",
          "md5": "db13aa67b0c1675e1c55f536e77508d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-e95a92e.jar",
          "url": "antibytes-versioning-e95a92e.jar",
          "size": 15815,
          "sha512": "8098af3b1af5826306329758a9fe8eb9ac2b309dd4d6cd8165c5c1a70efe5fe885981a61eec6d0e2eed78a474e5872a7a52460dbd4b9e771fa78cdb88a2fb862",
          "sha256": "bc4a7c405edc35e3ce4cf2eeaee575add81e1fcd144118efac588c169ca17d1f",
          "sha1": "15f365386c16e304135a2f94fdf1b98244abb138",
          "md5": "db13aa67b0c1675e1c55f536e77508d9"
        }
      ]
    }
  ]
}
