{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc05-SNAPSHOT/kmock-0.3.0-rc05-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc05-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-tvossimulatorarm64-0.3.0-rc05-SNAPSHOT.klib",
          "size": 202591,
          "sha512": "69208552e565f735f39e7da1108b70d7226d0f7c0ee2e7e58f965bcc0fa889157dfeb0cf8993c9c5d1d7cbc4a4d126408214c82cd96828d994b08efd16375236",
          "sha256": "2f3e1b2f8e0211a67819b60c279702b116367b293116b5440909b59ad7df370e",
          "sha1": "f8be3fe63d7a689e35366437ea5bac0435f54680",
          "md5": "3ff5eb6bcc766a155ed7669227b130b4"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-tvossimulatorarm64-0.3.0-rc05-SNAPSHOT-metadata.jar",
          "url": "kmock-tvossimulatorarm64-0.3.0-rc05-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "f5c2a547afd4cae63da51f2c1cd20cd015e0c5b772e7b41bdd01f96d3e93488403b841e51658628d7bb34d73edcc31a58e485afd2687c61b1381edfce91101d8",
          "sha256": "760e49e90cf4ca0b411f7b2ffec95c9305c6226169374bc46a24e35860c38fbb",
          "sha1": "14b4e245404f2c984ce2c51ab5e532082cd7d7c9",
          "md5": "7b39c481e977c4378b069fc4d04ea11c"
        }
      ]
    }
  ]
}
