{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "573821d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-573821d.jar",
          "url": "kmock-gradle-573821d.jar",
          "size": 33059,
          "sha512": "ff48261e01dbd2a0e000577fca3f7409ef477a4eb1d46e2f6bcd5d2d34fea051f43a70710517d2ef445928a61da8451ba9b7af177c42e70ff4481109e7c349db",
          "sha256": "6efbff506ef13551764bb6fc35874bbe068a02a9b2e9c67c38a226521df81131",
          "sha1": "62be2b4c81cfa62d308049ac882e4ac007231863",
          "md5": "a6b9d0cd98554ebd77d90e8c4750decd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-573821d.jar",
          "url": "kmock-gradle-573821d.jar",
          "size": 33059,
          "sha512": "ff48261e01dbd2a0e000577fca3f7409ef477a4eb1d46e2f6bcd5d2d34fea051f43a70710517d2ef445928a61da8451ba9b7af177c42e70ff4481109e7c349db",
          "sha256": "6efbff506ef13551764bb6fc35874bbe068a02a9b2e9c67c38a226521df81131",
          "sha1": "62be2b4c81cfa62d308049ac882e4ac007231863",
          "md5": "a6b9d0cd98554ebd77d90e8c4750decd"
        }
      ]
    }
  ]
}
