{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-tvosx64-0.4.0-SNAPSHOT.klib",
          "size": 105826,
          "sha512": "7c96fe4649b351813825ad345d0393d980b57ac7426437a977ce9b9c53739a0f06fa42c9eb5768bbf3a216e747e758209e1531f4bf00455bf59e34c8da83294d",
          "sha256": "a7e846f9ae6e8deb48faf66edb000630da782d13cd2a2c78a28ec6e5022fdfa4",
          "sha1": "092cf759437a00c21badff9bf3e52878af235df6",
          "md5": "52930e08e1753341db938cc862a54a62"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-tvosx64-0.4.0-SNAPSHOT-metadata.jar",
          "url": "core-tvosx64-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "629c0a3aebfbd31281aadbb96338662059b42bde13d06dff86c7d6634e7ac9f053a2466c6fc5c21a05148119cf678f1f8b414be4af56f2e070582a41a3668630",
          "sha256": "8ab4190e88d570691d4bf897f0d4bf3083c67f165ea1f3cbc23769933ae609c0",
          "sha1": "f63d41b6c14ea9d68172502d81b39d0ed0e31472",
          "md5": "f09debb6d0927efca8ed7438e741835f"
        }
      ]
    }
  ]
}
