{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-SNAPSHOT/ktx-datetime-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iosx64-0.4.0-SNAPSHOT.klib",
          "size": 34633,
          "sha512": "c88e5c39cd1d3e436131eac99b36142e79cbc5e0ae602f2587b2ec563cc58d2373dffc114763b6b4450f6d91a98b389002d0abee158d707717cd806b4823c552",
          "sha256": "e0d4b1f27a981f5784e9f1e2b7b2373ad26bc1320683f17d66fe5f539e2df58b",
          "sha1": "2ee6f98d5effa1e56e9ddc3c912b09efb80a7ea2",
          "md5": "876dbe675d595e0b819f4e3e3b9b7f2f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iosx64-0.4.0-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iosx64-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "c51b72af51219e85f019bec34c115c6e198a52277984a63a08abd3f47c1f1dc80931087488108600e046ab1e62110336dd380cdb95c3dd62b793331a47516629",
          "sha256": "355f7ae33906593daaccd7dc2e8df24dc8746cd02dd8ab8b143c3461cb14dc4b",
          "sha1": "63098a114ca7a7b601fd26ecfe5783e9f1bd34fc",
          "md5": "46893794e9b55d6c7a77098986f93148"
        }
      ]
    }
  ]
}
