{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/6c316c5/test-utils-ktor-6c316c5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "6c316c5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm-6c316c5.jar",
          "url": "test-utils-ktor-jvm-6c316c5.jar",
          "size": 26352,
          "sha512": "42093e74525cf1a4fd91da8ad4ad446ef9279ffe452c3e068aa5aa238cd09c4d2ca9a4c6514d2b3636b7d598aef3776602ba74d86949c835845a2e538fa9968b",
          "sha256": "8bf8d1064d09d4dbc40e3fccda0740b4949157faf7c18730771e268a858bd767",
          "sha1": "79efad01ba97f1b13bd685754baa1a5d29c61b6b",
          "md5": "0d8d2f7cba76d0369bbd9c127db1b605"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-6c316c5.jar",
          "url": "test-utils-ktor-jvm-6c316c5.jar",
          "size": 26352,
          "sha512": "42093e74525cf1a4fd91da8ad4ad446ef9279ffe452c3e068aa5aa238cd09c4d2ca9a4c6514d2b3636b7d598aef3776602ba74d86949c835845a2e538fa9968b",
          "sha256": "8bf8d1064d09d4dbc40e3fccda0740b4949157faf7c18730771e268a858bd767",
          "sha1": "79efad01ba97f1b13bd685754baa1a5d29c61b6b",
          "md5": "0d8d2f7cba76d0369bbd9c127db1b605"
        }
      ]
    }
  ]
}
