{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.publishing",
    "module": "antibytes-publishing-configuration",
    "version": "87f0ce6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-configuration-87f0ce6.jar",
          "url": "antibytes-publishing-configuration-87f0ce6.jar",
          "size": 4888,
          "sha512": "e994d29c43aaddac3130a051d68683da51c58ef7e538a3dfecf58646e8e9a6f0ca3fc5f5ded51b165d043013d09a018e3b1c0239dfa4f491428727d70dc0c971",
          "sha256": "47c43c86e841c96ca0df1ed05831eb2ab4a491f3250a41f77dcafab005a83cc4",
          "sha1": "c80cd7bdc57e4ceaf22e7dca3252b9ae9964cb4c",
          "md5": "75f467fd02b88e1853f6fd726d00cfe5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.publishing",
          "module": "antibytes-publishing",
          "version": {
            "requires": "87f0ce6"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-configuration-87f0ce6.jar",
          "url": "antibytes-publishing-configuration-87f0ce6.jar",
          "size": 4888,
          "sha512": "e994d29c43aaddac3130a051d68683da51c58ef7e538a3dfecf58646e8e9a6f0ca3fc5f5ded51b165d043013d09a018e3b1c0239dfa4f491428727d70dc0c971",
          "sha256": "47c43c86e841c96ca0df1ed05831eb2ab4a491f3250a41f77dcafab005a83cc4",
          "sha1": "c80cd7bdc57e4ceaf22e7dca3252b9ae9964cb4c",
          "md5": "75f467fd02b88e1853f6fd726d00cfe5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-publishing-configuration-87f0ce6-javadoc.jar",
          "url": "antibytes-publishing-configuration-87f0ce6-javadoc.jar",
          "size": 261,
          "sha512": "4a059cd431bacd232eb07a4dea0ab69a9d709ae26bac7a34fc3b4ce1649a9a6b922ac989fd90e064d6ebdc9fabc93e54b59dc4960f71070502afc033bf8b6e9b",
          "sha256": "ddc97ed37cc31fc4e738c7668fe4bf599b19ea25112de8700bcacd80c26c29bb",
          "sha1": "649d043674b557db68b35126c815327854b1f558",
          "md5": "cb19bb0cdc1d91bd22476fb157b0084d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-publishing-configuration-87f0ce6-sources.jar",
          "url": "antibytes-publishing-configuration-87f0ce6-sources.jar",
          "size": 2031,
          "sha512": "e1c56b8bcacc9a12a5e401f7366ec54a03537249b536698b6cacd21201a3ae72bedd2a9b2c1963ffea8ddb55db2a6643aa1b493d7815397b4a3a94e9d0389f17",
          "sha256": "4a2eb733ad643cee6b67b60a4f54b4fbdba2a6845642a511096b6688ad3e1cc2",
          "sha1": "619437e2701cc4e3a37eec1a861512ddec602209",
          "md5": "814bc799ef4341ce2770f85a27b02cb2"
        }
      ]
    }
  ]
}
