{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/cf35c27/test-utils-cf35c27.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "cf35c27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosx64-cf35c27.klib",
          "size": 14297,
          "sha512": "b2a60f82d7d49e65182861281bac176425ea6cd314ea6d5734aaa89001fae3876106ae1b1d3fa36318b1cd60a2139736611e4bb12fecab89bdf692cdb8b541a5",
          "sha256": "c8d56e34fbef56e6e988e17cf2efe0223f8ab9966497b527415b25eb7924e0f3",
          "sha1": "71413c7535c784cd5c63450f6a50c7832aee5809",
          "md5": "53dbe616f8bc3fdb80fb577fac10a62c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosx64-cf35c27-metadata.jar",
          "url": "test-utils-iosx64-cf35c27-metadata.jar",
          "size": 261,
          "sha512": "82728983832a2ace0ef5c72630592f4f683f9923d6e888b4d53e6a4f5c2560421a4e40b03980ccf4decdedbc2b53faa92fd01d18ee00efb7cb4f7827cfa58c1c",
          "sha256": "1a78c13651a4fa7d354c09f3c31020a65a8c51c3d240f369adb203a1262c788c",
          "sha1": "87059b8918c6088d07658011ea2cf0b0080212a9",
          "md5": "39d0b99c07e83f98c4e403b4e2331d73"
        }
      ]
    }
  ]
}
