{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "d273191",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-d273191.jar",
          "url": "antibytes-configuration-d273191.jar",
          "size": 50694,
          "sha512": "accd41a94e05384d71f877e9b7cf5ee43914cfd10c2b7a8bf041f8257f31848a2b435169c9190476c4df34d08b24db5e094ea2cf7670a83654ec51b7798a3dbf",
          "sha256": "becf9f23036cc6c6043562b8894e3b39c566a5f90d2c5b54b446166ceeca817b",
          "sha1": "098142feb3bdb0b1f9bccccc9f51ab935d011192",
          "md5": "7ef45c6dc3bba8eeb4a60d05269500bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "d273191"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-d273191.jar",
          "url": "antibytes-configuration-d273191.jar",
          "size": 50694,
          "sha512": "accd41a94e05384d71f877e9b7cf5ee43914cfd10c2b7a8bf041f8257f31848a2b435169c9190476c4df34d08b24db5e094ea2cf7670a83654ec51b7798a3dbf",
          "sha256": "becf9f23036cc6c6043562b8894e3b39c566a5f90d2c5b54b446166ceeca817b",
          "sha1": "098142feb3bdb0b1f9bccccc9f51ab935d011192",
          "md5": "7ef45c6dc3bba8eeb4a60d05269500bb"
        }
      ]
    }
  ]
}
