{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "a9d047f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "a9d047f"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-a9d047f.jar",
          "url": "antibytes-mkdocs-a9d047f.jar",
          "size": 12083,
          "sha512": "4705c21221dc0284f251f1ec548aeb20e290d2cb4717aac8f20ca65edb3bbf3d3d484327a10ac3dadce1d0d3fdd884f34f2048c7c4e933673aa59cd7196dd386",
          "sha256": "9e26b43c9df9da5f04e52237716050492f470e2d4016a1a14bd16da11b4c5f63",
          "sha1": "f042f68fd55ce03ba2cfecddc71a599ecc44e1a1",
          "md5": "038384f81bcb144a44a0b63beb167af1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "a9d047f"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "a9d047f"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-a9d047f.jar",
          "url": "antibytes-mkdocs-a9d047f.jar",
          "size": 12083,
          "sha512": "4705c21221dc0284f251f1ec548aeb20e290d2cb4717aac8f20ca65edb3bbf3d3d484327a10ac3dadce1d0d3fdd884f34f2048c7c4e933673aa59cd7196dd386",
          "sha256": "9e26b43c9df9da5f04e52237716050492f470e2d4016a1a14bd16da11b4c5f63",
          "sha1": "f042f68fd55ce03ba2cfecddc71a599ecc44e1a1",
          "md5": "038384f81bcb144a44a0b63beb167af1"
        }
      ]
    }
  ]
}
