{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.quality",
    "module": "antibytes-quality",
    "version": "a68f09c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-quality-a68f09c.jar",
          "url": "antibytes-quality-a68f09c.jar",
          "size": 62612,
          "sha512": "3fb10a54dbc747c801d6ab60c45d19f827ee0b4ec83008d17d9eb10fffdb0d2ae6a8cfe4d766b5d287d0e892eb898691563da02432de18fa6943e00cec9ed911",
          "sha256": "2d0c3a54a06776b2d76d5d293e849e01ef8755c163436731e0f38655c2c70aea",
          "sha1": "4b3ab218d425706db4cb66d83f801cbbf74aaa82",
          "md5": "015190d88b22d1334e680c1c2b624c1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.22.0"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "a68f09c"
          }
        },
        {
          "group": "tech.antibytes.gradle.dependency.helper",
          "module": "antibytes-dependency-helper",
          "version": {
            "requires": "a68f09c"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-a68f09c.jar",
          "url": "antibytes-quality-a68f09c.jar",
          "size": 62612,
          "sha512": "3fb10a54dbc747c801d6ab60c45d19f827ee0b4ec83008d17d9eb10fffdb0d2ae6a8cfe4d766b5d287d0e892eb898691563da02432de18fa6943e00cec9ed911",
          "sha256": "2d0c3a54a06776b2d76d5d293e849e01ef8755c163436731e0f38655c2c70aea",
          "sha1": "4b3ab218d425706db4cb66d83f801cbbf74aaa82",
          "md5": "015190d88b22d1334e680c1c2b624c1b"
        }
      ]
    }
  ]
}
