{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/c78d849/test-utils-fixture-c78d849.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "c78d849",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-c78d849.klib",
          "url": "test-utils-fixture-js-c78d849.klib",
          "size": 36097,
          "sha512": "e736cf833b6964a2e3964ca6ed14c488cf36ba0f3c5d19b5294507b28a0e1bfdd9191bfb1123b05e7c4c86ce664e91c1290dc201fe9eb7092bdb2d9ebc68ccfa",
          "sha256": "604e100fb4c94d70803eb808f3c55c16d728d1300d2757192a471957f372e2e3",
          "sha1": "efb087a884ad592d85e7a947815fde1d872250df",
          "md5": "191060fa247d8248857db154602d90da"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-c78d849.klib",
          "url": "test-utils-fixture-js-c78d849.klib",
          "size": 36097,
          "sha512": "e736cf833b6964a2e3964ca6ed14c488cf36ba0f3c5d19b5294507b28a0e1bfdd9191bfb1123b05e7c4c86ce664e91c1290dc201fe9eb7092bdb2d9ebc68ccfa",
          "sha256": "604e100fb4c94d70803eb808f3c55c16d728d1300d2757192a471957f372e2e3",
          "sha1": "efb087a884ad592d85e7a947815fde1d872250df",
          "md5": "191060fa247d8248857db154602d90da"
        }
      ]
    }
  ]
}
