{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc03-SNAPSHOT/kmock-0.3.0-rc03-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc03-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-0.3.0-rc03-SNAPSHOT.aar",
          "size": 360884,
          "sha512": "21ecfa6f9d2274404b462546ae77cf2c78671b2b882f18e7d77d386a5c0eb7ad34c808c3d677ba121604d7d12d58fb9343c97feb746118632224db86e1741c8c",
          "sha256": "4d0328dcda6e0be3bb2da120a550978759e54d030d6a3e412660a289ba2cdb14",
          "sha1": "21b1fed82e4a8ed495aaa14936341872f024c2ee",
          "md5": "41ce5e1d18700a113e6a448c30884c1e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kmock-release.aar",
          "url": "kmock-android-0.3.0-rc03-SNAPSHOT.aar",
          "size": 360884,
          "sha512": "21ecfa6f9d2274404b462546ae77cf2c78671b2b882f18e7d77d386a5c0eb7ad34c808c3d677ba121604d7d12d58fb9343c97feb746118632224db86e1741c8c",
          "sha256": "4d0328dcda6e0be3bb2da120a550978759e54d030d6a3e412660a289ba2cdb14",
          "sha1": "21b1fed82e4a8ed495aaa14936341872f024c2ee",
          "md5": "41ce5e1d18700a113e6a448c30884c1e"
        }
      ]
    }
  ]
}
