{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "807f122",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-807f122.jar",
          "url": "antibytes-gradle-test-utils-807f122.jar",
          "size": 16830,
          "sha512": "2be17e3de43d0860a189d60df1f182d4ae7fe2d289d7ae782ce07a5ce6685a475ab6f250bc65bad506fdd528f1df06a45cbe891c2c34de3d987b9c33e374fd64",
          "sha256": "9520e89fe694b2708afa502d97cbd6024ec3a259cbacb836713ca08f9493dd23",
          "sha1": "fac433d0d39831bb44eb6ca8fe767798466e628e",
          "md5": "a73cd6f5737b377f054d5c6dd645731a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-807f122.jar",
          "url": "antibytes-gradle-test-utils-807f122.jar",
          "size": 16830,
          "sha512": "2be17e3de43d0860a189d60df1f182d4ae7fe2d289d7ae782ce07a5ce6685a475ab6f250bc65bad506fdd528f1df06a45cbe891c2c34de3d987b9c33e374fd64",
          "sha256": "9520e89fe694b2708afa502d97cbd6024ec3a259cbacb836713ca08f9493dd23",
          "sha1": "fac433d0d39831bb44eb6ca8fe767798466e628e",
          "md5": "a73cd6f5737b377f054d5c6dd645731a"
        }
      ]
    }
  ]
}
