{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/8066bd0/test-utils-coroutine-8066bd0.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "8066bd0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-watchosx64-8066bd0.klib",
          "size": 10147,
          "sha512": "87a5467c6235dc3e304479d2ff3678ea871c8f2fcdf787545aa0d61a43c9211ec688e4ae3e08b14926c679c442c32459523ec365192759c4f03f8484fb955f6c",
          "sha256": "d59a16ba41f84bfe1b6c0db8c657a8417b091641bb1b96d01fde7149346a271d",
          "sha1": "118ec474eba6a92115897d217f2e1e8490019a06",
          "md5": "412922ac17140413585c398fdb6d1b10"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-watchosx64-8066bd0-metadata.jar",
          "url": "test-utils-coroutine-watchosx64-8066bd0-metadata.jar",
          "size": 261,
          "sha512": "e5cb51993887f87d385e499728224ef32ed4d6651c71f8d1a9cadfd608dbeae372c671c8dd6f6eab4aa4bdd4e31cfeefa18c86b2daeec5146ef2beaa98c870e5",
          "sha256": "d943b92a456183f8bfe9160fd0bc96d880101ce47b15d90dbce917deec845c73",
          "sha1": "08dab876f1c0d115dd5e5b2b6fe9e02273337225",
          "md5": "f29b470391573b9a5b2c47f247b7be4e"
        }
      ]
    }
  ]
}
