{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-SNAPSHOT/ktx-datetime-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-tvosarm64-0.4.0-SNAPSHOT.klib",
          "size": 36961,
          "sha512": "0f2c66b43bab48a3b257842e2d4b66048f817ac485e239281ce40681a3f7b931666c5eb6358d6e109d5469942e9e33fae6fd761dbf2b7f29cf11cf4bc339249e",
          "sha256": "65d41b7afce359132ce07df5497f6bdaf51f56598e6a41d2777bbd56e98b1a85",
          "sha1": "6ffe620cd485bd95afc0215add4996446d552291",
          "md5": "b2dcd69c7a2744b57a65cf4a8f860905"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktx-datetime-tvosarm64-0.4.0-SNAPSHOT-sources.jar",
          "url": "ktx-datetime-tvosarm64-0.4.0-SNAPSHOT-sources.jar",
          "size": 16088,
          "sha512": "2fd1093b4f66fb86460e0e5fc46d3c82d6d649e51f6fa67d86c49ee2405d528475c31f450f406b1a2be2e691d1f52d71036cf571bf342b1c7bbfdb18aacafc58",
          "sha256": "ddfeada0f92e68af51cd57f3ddcf63f5349e6ad12c9b5c93c0313015c5cc3e8e",
          "sha1": "e3f7b5b02498f31f31ff09a28221f9502399b3a2",
          "md5": "b2ce74b02e7d0b4b4cf6bb0c3c064bd4"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-tvosarm64-0.4.0-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-tvosarm64-0.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "9c62640384382f8a095fefd7901ec1394e7794e049301019a943b2cccd545ee6ead0e746c299a70f8b707f33c0a5094597e292f7f704858870eef5acc8862487",
          "sha256": "a2bb90731e8466377fedc6e1b17c5e14449040d0a11bae4dab09badbfb4e9b58",
          "sha1": "2b01d2e7091830d8dfc1e8fc5b33465379ff2fdb",
          "md5": "70ba8954fc36aa0351ffc993507383b6"
        }
      ]
    }
  ]
}
