{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "a1b98b8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-a1b98b8.jar",
          "url": "antibytes-dependency-helper-a1b98b8.jar",
          "size": 69704,
          "sha512": "dcfc032b6915bcb328e1d614dc3150b736b7e062ef8f999e7889a2ccdb860c1a23c101cd601be2f02f69cb0837bd59c5bb7132652a17d0a9355d3452347ff735",
          "sha256": "243d249435fe1081cd8d68476323142dc042535d08b681eff82ceeda7737229f",
          "sha1": "cf6c6af5812d97a7394a1a5b3ca92e96daeba8a5",
          "md5": "afc10a214a0d0fe666d4e00c29a7760c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.51.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "9.0.9"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "a1b98b8"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-a1b98b8.jar",
          "url": "antibytes-dependency-helper-a1b98b8.jar",
          "size": 69704,
          "sha512": "dcfc032b6915bcb328e1d614dc3150b736b7e062ef8f999e7889a2ccdb860c1a23c101cd601be2f02f69cb0837bd59c5bb7132652a17d0a9355d3452347ff735",
          "sha256": "243d249435fe1081cd8d68476323142dc042535d08b681eff82ceeda7737229f",
          "sha1": "cf6c6af5812d97a7394a1a5b3ca92e96daeba8a5",
          "md5": "afc10a214a0d0fe666d4e00c29a7760c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-a1b98b8-javadoc.jar",
          "url": "antibytes-dependency-helper-a1b98b8-javadoc.jar",
          "size": 261,
          "sha512": "3f6284c1f7f324198ad6f90e2a8ae14285500457d1658c945da2b8dd8f20646b0aa27c7ac0bbaffb1514df71227426663bedee1f1e52164e76aaac91c7bfe457",
          "sha256": "900e34cf84b81e96a24314a0e13f8c327e8b40952ba9b8c892a7c780541cbe11",
          "sha1": "0afc939c98005797dc427563988cc7ea4284254a",
          "md5": "eda3f881f3402068d67e909039684b2c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-a1b98b8-sources.jar",
          "url": "antibytes-dependency-helper-a1b98b8-sources.jar",
          "size": 9187,
          "sha512": "5320b9cdb380be7c8226125f2d72211bd1acc777047c83696320fb71fbb4c6b566c131b631260f4d183a314e607c187bebde9c9405b0f297b8dc61371c815b17",
          "sha256": "3602040323186f1a78732e909768ef826ad5c46ceb7ffe289bb62f67d3deabaf",
          "sha1": "b7ca28ad145b2e678a9d0ff0a0d267ce4b6ee83d",
          "md5": "513a1c5a0cc8baba536d9bbecf6714e2"
        }
      ]
    }
  ]
}
