{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/f7c1da7/test-utils-f7c1da7.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "f7c1da7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iossimulatorarm64-f7c1da7.klib",
          "size": 14392,
          "sha512": "54b4c41b37988353242b89e8a6bfcb466f77b1a456bfb93b58ed680803ab0e1676e2b0a5c6496672cc285bdc696953cee597d18612a302728cf069d9df208d85",
          "sha256": "06f0963f0a04d6db2cc56e2de65bf648cfabdc955678ae4ac7d518a468d66be3",
          "sha1": "5954006f2b7c0a45146cc8f5366f108e5f4fe073",
          "md5": "29d176ce0743f5bc6170b2f582b74d0b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iossimulatorarm64-f7c1da7-metadata.jar",
          "url": "test-utils-iossimulatorarm64-f7c1da7-metadata.jar",
          "size": 261,
          "sha512": "d5a1e2a9ebd0dc1b455e7de7e023eebb55d08e1a5dce5ac7cbe2832e42c2ce3da418f169eb353a9fae437587fea6817994996438603bf992fd9910cfcdd60314",
          "sha256": "9518f7649623843f1414944e9d1d7e5dcc7c1c4b5646547bc0de7acaa1de82ee",
          "sha1": "621cd4ced2909b35f95fed4abf9d951d73b9b866",
          "md5": "a3095b463aedea7935adcc6d1c5465d7"
        }
      ]
    }
  ]
}
