{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "f266a0f-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-f266a0f-SNAPSHOT.jar",
          "url": "antibytes-dependency-f266a0f-SNAPSHOT.jar",
          "size": 88198,
          "sha512": "8e01cc794c88b003b2cd427c59f4b8b666aaec8a2e0dad5051077f436ea56439997cae1570a037612b77420bf9e529c0d51512c78544745ee0de1febf719968f",
          "sha256": "98e1e6cea5710b77b6258eefdb9c3e8090b080626d9e41465a5c25b7c9967749",
          "sha1": "87adc4b89ff24a16987962b450b337e46959d6ab",
          "md5": "a4e66259a93b9b97288ff02268668ed2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          },
          "excludes": [
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-xml"
            }
          ]
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "f266a0f-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-f266a0f-SNAPSHOT.jar",
          "url": "antibytes-dependency-f266a0f-SNAPSHOT.jar",
          "size": 88198,
          "sha512": "8e01cc794c88b003b2cd427c59f4b8b666aaec8a2e0dad5051077f436ea56439997cae1570a037612b77420bf9e529c0d51512c78544745ee0de1febf719968f",
          "sha256": "98e1e6cea5710b77b6258eefdb9c3e8090b080626d9e41465a5c25b7c9967749",
          "sha1": "87adc4b89ff24a16987962b450b337e46959d6ab",
          "md5": "a4e66259a93b9b97288ff02268668ed2"
        }
      ]
    }
  ]
}
