{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "f2c3d06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-f2c3d06.jar",
          "url": "antibytes-custom-component-f2c3d06.jar",
          "size": 16177,
          "sha512": "28ebc65c27299011bc9f3954f3d783536d815b01bf7c6998fa54713e9a01b2e79c1139508f32a14f33a7579b6e8bc7c78d2085a8f818f70520a653d330ecde8a",
          "sha256": "2d019ec33b0e200471319fce4e94821343e9fe6c38a175f8f5b4896c9696db29",
          "sha1": "914ff9bbb049ec236b4ce029838ce64533cb7f42",
          "md5": "3cbe35ec2f492c5d5e475360dc546081"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-f2c3d06.jar",
          "url": "antibytes-custom-component-f2c3d06.jar",
          "size": 16177,
          "sha512": "28ebc65c27299011bc9f3954f3d783536d815b01bf7c6998fa54713e9a01b2e79c1139508f32a14f33a7579b6e8bc7c78d2085a8f818f70520a653d330ecde8a",
          "sha256": "2d019ec33b0e200471319fce4e94821343e9fe6c38a175f8f5b4896c9696db29",
          "sha1": "914ff9bbb049ec236b4ce029838ce64533cb7f42",
          "md5": "3cbe35ec2f492c5d5e475360dc546081"
        }
      ]
    }
  ]
}
