{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "d1578d9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n-metadata-all.jar",
          "url": "banana-i18n-d1578d9-all.jar",
          "size": 670,
          "sha512": "46def594f5772b689b04feb382b1c5c0f6e65ced4b498e04bc4aa70532e125202a5262e7250378281b16178fc77d2de1d4422fb87a9fc102723f93f0297f8cf0",
          "sha256": "4b53983c35e40edd45a907ebfc2bfde3d0f55357e78a7e902644dfa81ec52c58",
          "sha1": "6eb85b9fb975bd29bfce25f89d5c05229626e515",
          "md5": "4128b2dc8ca3b56c379c24d4402e1433"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n.jar",
          "url": "banana-i18n-d1578d9.jar",
          "size": 8908,
          "sha512": "0580ea90bf2179e47247cbaf218f467ed4d29eb2f13fed75dbc5ef8da816291a96c1dfa30026b50a8ae4b1042d0e765490182c85a600bba5bde42633aae7db38",
          "sha256": "4fe5950b80937eb6b7e63857e66dd8034faccb6942f7d8493de01d55cd761296",
          "sha1": "87d27b1903310d1e7f8826a0a681b7cacc0ba1ed",
          "md5": "0b5a0f42ab62c2a5647af5785bb19083"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/d1578d9/banana-i18n-android-d1578d9.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "d1578d9"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/d1578d9/banana-i18n-android-d1578d9.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "d1578d9"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/d1578d9/banana-i18n-jvm-d1578d9.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "d1578d9"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/d1578d9/banana-i18n-jvm-d1578d9.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "d1578d9"
      }
    }
  ]
}
