{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "080e68f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-080e68f.jar",
          "url": "antibytes-android-application-configuration-080e68f.jar",
          "size": 58233,
          "sha512": "23f672ca2d241c5b015f38b1c8d27e2ee653158ce69e5a86b6bec13ee2e71abb020684cb663284a723dd2fb4f79dea15da5e94c879a9da71fc8f190092da0d4f",
          "sha256": "60f2d3a8cfdd62c2bc84ffe67876da56d385e3104b162552e5d16049edcaac80",
          "sha1": "fa10e020ad0d620a75841781e1e7bace70563abb",
          "md5": "2fec1b2ab553f44056e2b9c0579aa88f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "080e68f"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-080e68f.jar",
          "url": "antibytes-android-application-configuration-080e68f.jar",
          "size": 58233,
          "sha512": "23f672ca2d241c5b015f38b1c8d27e2ee653158ce69e5a86b6bec13ee2e71abb020684cb663284a723dd2fb4f79dea15da5e94c879a9da71fc8f190092da0d4f",
          "sha256": "60f2d3a8cfdd62c2bc84ffe67876da56d385e3104b162552e5d16049edcaac80",
          "sha1": "fa10e020ad0d620a75841781e1e7bace70563abb",
          "md5": "2fec1b2ab553f44056e2b9c0579aa88f"
        }
      ]
    }
  ]
}
