{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/56c5f3f/test-utils-fixture-56c5f3f.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "56c5f3f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-56c5f3f.klib",
          "url": "test-utils-fixture-js-56c5f3f.klib",
          "size": 38261,
          "sha512": "46e2b3d4d72a21ee8615e476a63e621361155672c13599a021272e11171c4cbbb3cd9dfb1988addc391b18b0675308e988524731499ab2536223172d6fba7bd3",
          "sha256": "4670e308f91019cbe9b0b56492aa16b8e062ef808d67b19773db25eeb146c8d7",
          "sha1": "92b7955051a23d8e10b8cc6125b8cba8ad2af261",
          "md5": "06a7dea1b28649a2cdf6b308028e7a73"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-56c5f3f.klib",
          "url": "test-utils-fixture-js-56c5f3f.klib",
          "size": 38261,
          "sha512": "46e2b3d4d72a21ee8615e476a63e621361155672c13599a021272e11171c4cbbb3cd9dfb1988addc391b18b0675308e988524731499ab2536223172d6fba7bd3",
          "sha256": "4670e308f91019cbe9b0b56492aa16b8e062ef808d67b19773db25eeb146c8d7",
          "sha1": "92b7955051a23d8e10b8cc6125b8cba8ad2af261",
          "md5": "06a7dea1b28649a2cdf6b308028e7a73"
        }
      ]
    }
  ]
}
