{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.publishing",
    "module": "antibytes-publishing",
    "version": "3efd24e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "3efd24e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-3efd24e.jar",
          "url": "antibytes-publishing-3efd24e.jar",
          "size": 141212,
          "sha512": "6904acdb75aeda174cfb49fcdd2cb32b52d0d682819adea0e7881b97656542af36f8b9553d74de09ca0f16b849f85d150dea33072973539584e8f048ca59a8a6",
          "sha256": "2aeca64e0fcfac86724b40f9ca87875fcbb8e1a043069017a07a93ac0318b390",
          "sha1": "84f866494334911c35eb5f19a6dd5326564446a9",
          "md5": "91f8d06de63161847a851c26cb9df23b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.8.0.202311291450-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "3efd24e"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "3efd24e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-3efd24e.jar",
          "url": "antibytes-publishing-3efd24e.jar",
          "size": 141212,
          "sha512": "6904acdb75aeda174cfb49fcdd2cb32b52d0d682819adea0e7881b97656542af36f8b9553d74de09ca0f16b849f85d150dea33072973539584e8f048ca59a8a6",
          "sha256": "2aeca64e0fcfac86724b40f9ca87875fcbb8e1a043069017a07a93ac0318b390",
          "sha1": "84f866494334911c35eb5f19a6dd5326564446a9",
          "md5": "91f8d06de63161847a851c26cb9df23b"
        }
      ]
    }
  ]
}
