{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "9d80d4b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-9d80d4b.jar",
          "url": "antibytes-dependency-node-9d80d4b.jar",
          "size": 21473,
          "sha512": "4be2a2ab03d6730052f4515a7de2d2b470c77b63f395d7195c32ac04df6f3e6bc37f0a431e9731a56cf520a441a7cf0cf70af5d30b70b2612115bf522a72196f",
          "sha256": "4bdbbd353572b97a4a345b7194c53523ce7e7ad7c3bc625e577206589199949e",
          "sha1": "1d73e0b7e76885f8752ad8fb28d479eb88f26692",
          "md5": "7da1f7818051f4b31d261fca8738cb24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-9d80d4b.jar",
          "url": "antibytes-dependency-node-9d80d4b.jar",
          "size": 21473,
          "sha512": "4be2a2ab03d6730052f4515a7de2d2b470c77b63f395d7195c32ac04df6f3e6bc37f0a431e9731a56cf520a441a7cf0cf70af5d30b70b2612115bf522a72196f",
          "sha256": "4bdbbd353572b97a4a345b7194c53523ce7e7ad7c3bc625e577206589199949e",
          "sha1": "1d73e0b7e76885f8752ad8fb28d479eb88f26692",
          "md5": "7da1f7818051f4b31d261fca8738cb24"
        }
      ]
    }
  ]
}
