{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/b9030f2/test-utils-resourceloader-b9030f2.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "b9030f2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-macosx64-b9030f2.klib",
          "size": 14213,
          "sha512": "201f0a5b6edccda6de3b0539104bf92e4a1b79ab7ec03e4829fffdca5ad7087d0c72b32a573be7d4db11d8f03774a1317eb12cb7ebbbcd0d3e51154b1bb66691",
          "sha256": "6eecfe5966fe2565ba39d049fb09ada782d4d05ef807619068493ea82cca564b",
          "sha1": "f203ec652e504ff4f5017f5b2317d71124c0ef28",
          "md5": "55ad3b9f731aca9222f9a8684e65dbec"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-macosx64-b9030f2-sources.jar",
          "url": "test-utils-resourceloader-macosx64-b9030f2-sources.jar",
          "size": 4241,
          "sha512": "284172150658cfb9dae6c2bb10bbd5de382a8193d892540a4de60322cb16b05740a160fc4f827c092194ab0e3983419cb75c9d52eee7cf9cf1ac22b32a8f7d7b",
          "sha256": "28c33fb0c5429879a7515dfb1ee5400a354f30a17cda3a32c13cec2fd413b7da",
          "sha1": "e6bc305f912fc8fc1e733215728491f83d594bd4",
          "md5": "935272aedc89d60202c3ad87a167495a"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-macosx64-b9030f2-metadata.jar",
          "url": "test-utils-resourceloader-macosx64-b9030f2-metadata.jar",
          "size": 261,
          "sha512": "1885b886c43620a38abd7931bbd799bf4c13c4955851bb8afe11dfdd359b4d46d364c827013bf3ba76b59c5a05280c2f684f95fa0c62fc8b16990e1bff809d78",
          "sha256": "67d86a2129cb2ad2a916c5667a330c482ccd521454d20860e31f30d01195d78f",
          "sha1": "3ab2046114ffd3a083f9c30dc14119f2407be435",
          "md5": "caf04ea7a4f832df910f8ded55cfb3af"
        }
      ]
    }
  ]
}
