{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/98f5a1d/test-utils-coroutine-98f5a1d.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "98f5a1d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosx64-98f5a1d.klib",
          "size": 10106,
          "sha512": "4a9b0d8c6bbf29ff8559ce506c4140361e592a3810e352628bab3fd6f9c249c12dfcb69848e604020a0e587822b6c5f99ade82bdeaec71415f0726a3e008888a",
          "sha256": "c3bea4f9fd5a4e958a9a1b6d1f53c9d203f36f6249be2a6bcca2b1958635377d",
          "sha1": "ab8b1719020ab655506f34a4b6f2ef27d35a9acf",
          "md5": "c00982d032e9baadf7a58f15156d1104"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosx64-98f5a1d-metadata.jar",
          "url": "test-utils-coroutine-iosx64-98f5a1d-metadata.jar",
          "size": 261,
          "sha512": "64f154504a1130e8e24e88697dac85dffd8c4186696d8c5135b5e5ed0f7dea9e211cea3ca34916685518f76ac6cbf1e48e0d928756ba7d690eaba2221330228f",
          "sha256": "9d40b00e0b15827df155255421fbfb1ab71519c8d925c39de91fdc8d8c85ef7e",
          "sha1": "7e033de4bd0f0e5c65bc8beac92f80b6cc1d5745",
          "md5": "9bad096d3d3643d56f476d55d51aadf2"
        }
      ]
    }
  ]
}
