{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/86ec4d6/test-utils-annotations-junit5-86ec4d6.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "86ec4d6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-watchosarm64-86ec4d6.klib",
          "size": 7112,
          "sha512": "1201b164967e21918f3cd5e12e088778664c5e5e39a33d579161aefe2585246744b32506b6a877f68a4c6fdb63102d702e98114bcb77497c3b3cd73540543d88",
          "sha256": "171be96300ecf3cc25cf18550d6fb40794278805b838f8945c50b0b4ac3c4fff",
          "sha1": "aed777c347de3f200b9262c7a714558a7ae0a9a7",
          "md5": "fd076773afc279218875e136f6e44eef"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-annotations-junit5-watchosarm64-86ec4d6-sources.jar",
          "url": "test-utils-annotations-junit5-watchosarm64-86ec4d6-sources.jar",
          "size": 3477,
          "sha512": "8910488f2acc4f4c669bf3e6a74835e60ede75d2286f44304a32d7435e9374f50e400ec91ccdc9fcab868fe57ac79f9cc99c5183a87396417d48b059ee008e7f",
          "sha256": "9f2d1a8fe1210ea25bd9b54214171ccdd8f68d07f8c4c7bf4fdaa277b2d059e9",
          "sha1": "c0915589af235519923fb41575cb1d6e37f9dedf",
          "md5": "b993ac9b3bda4583966bb9266ec6da60"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-watchosarm64-86ec4d6-metadata.jar",
          "url": "test-utils-annotations-junit5-watchosarm64-86ec4d6-metadata.jar",
          "size": 261,
          "sha512": "11f157ed030a8412b40caec55bbf588a8c5b9e929c4a45cf3f960ff963ef0efbec17426ddf55f6e2c0ba9d22c032137fa707e6614d752233f15a70f4795be9cf",
          "sha256": "7b6825b3b69631ab0b28b22eed71b1a4b540d7bb6d16174620b1a97d065dd648",
          "sha1": "96775ddbf65c86def565d42208a39710cbd39643",
          "md5": "01caeec76d92d058980a44a4d3616af7"
        }
      ]
    }
  ]
}
