{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "933c5f7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-933c5f7.jar",
          "url": "antibytes-gradle-utils-933c5f7.jar",
          "size": 9577,
          "sha512": "2357580ac44c855b5e57de0909cfdbf8100fb8b44c51269d5fa2bbbc4eb0ae0e0a0e99a0001c8db8a80ddb56558dac8fd2a228359f676f67565a15e4227f8db7",
          "sha256": "c2aa6c05bfbaf83a58cdef567a492e0893cad0e4d45fc76eca6f797a37778f70",
          "sha1": "f2b4aadc69425c1d96b89d9db8c4c026cb77f90c",
          "md5": "091c45c23986dcb4d5019395550a1235"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-933c5f7.jar",
          "url": "antibytes-gradle-utils-933c5f7.jar",
          "size": 9577,
          "sha512": "2357580ac44c855b5e57de0909cfdbf8100fb8b44c51269d5fa2bbbc4eb0ae0e0a0e99a0001c8db8a80ddb56558dac8fd2a228359f676f67565a15e4227f8db7",
          "sha256": "c2aa6c05bfbaf83a58cdef567a492e0893cad0e4d45fc76eca6f797a37778f70",
          "sha1": "f2b4aadc69425c1d96b89d9db8c4c026cb77f90c",
          "md5": "091c45c23986dcb4d5019395550a1235"
        }
      ]
    }
  ]
}
