{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc03-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-metadata-0.3.0-rc03-SNAPSHOT-all.jar",
          "url": "kmock-0.3.0-rc03-SNAPSHOT-all.jar",
          "size": 28039,
          "sha512": "1f91d44575d815c27bd38e1ceff8cf10c267d7f440ff5a5f5ed82bdf2a563f4ef9d18567a7057374987cd19c9a5733b3aba87e1a8aa97281c7645158965a5bc2",
          "sha256": "82282bab47042e99aeab4100da37bcb9fa7ab2537369ec77a4a766f13e1b2d16",
          "sha1": "92c4eda4aa3f69658144492007dfc9718661574c",
          "md5": "961f6b9879f0bcba6a75ffacfbb307aa"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-0.3.0-rc03-SNAPSHOT.jar",
          "url": "kmock-0.3.0-rc03-SNAPSHOT.jar",
          "size": 47917,
          "sha512": "96c758228727fcf29bb986106deda54844106f18faa1aad7c01a98365d0bed3a871dd57c90be9f7c405cbe828f4916c7a207182f26f8e42749751665c3169323",
          "sha256": "24c373fb6b707aa39cb78d5c581ccec2ae65a073f6033f1357d1b79974e92bf7",
          "sha1": "62e9c11a11f04e9ba0742ec2df39d667f5467f2f",
          "md5": "8ac830642676f40c39bc83bc1945852d"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.3.0-rc03-SNAPSHOT/kmock-android-0.3.0-rc03-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.3.0-rc03-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.3.0-rc03-SNAPSHOT/kmock-android-0.3.0-rc03-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.3.0-rc03-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/0.3.0-rc03-SNAPSHOT/kmock-iosarm64-0.3.0-rc03-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "0.3.0-rc03-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/0.3.0-rc03-SNAPSHOT/kmock-iosarm64-0.3.0-rc03-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "0.3.0-rc03-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iossimulatorarm64/0.3.0-rc03-SNAPSHOT/kmock-iossimulatorarm64-0.3.0-rc03-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iossimulatorarm64",
        "version": "0.3.0-rc03-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iossimulatorarm64/0.3.0-rc03-SNAPSHOT/kmock-iossimulatorarm64-0.3.0-rc03-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iossimulatorarm64",
        "version": "0.3.0-rc03-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/0.3.0-rc03-SNAPSHOT/kmock-iosx64-0.3.0-rc03-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "0.3.0-rc03-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/0.3.0-rc03-SNAPSHOT/kmock-iosx64-0.3.0-rc03-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "0.3.0-rc03-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.3.0-rc03-SNAPSHOT/kmock-js-0.3.0-rc03-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.3.0-rc03-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.3.0-rc03-SNAPSHOT/kmock-js-0.3.0-rc03-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.3.0-rc03-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.3.0-rc03-SNAPSHOT/kmock-jvm-0.3.0-rc03-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.3.0-rc03-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.3.0-rc03-SNAPSHOT/kmock-jvm-0.3.0-rc03-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.3.0-rc03-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/0.3.0-rc03-SNAPSHOT/kmock-linuxx64-0.3.0-rc03-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "0.3.0-rc03-SNAPSHOT"
      }
    }
  ]
}
