{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/9294166/test-utils-fixture-9294166.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "9294166",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-9294166.klib",
          "url": "test-utils-fixture-js-9294166.klib",
          "size": 38261,
          "sha512": "19551697eecf9c4b4ccc8414352caa26b9764651734cd9b1f8ac565fc4d6f5ab9caf9659b0010850fd443bbf44fdd0f4d41957312eea18f95ecf1bbc373252d8",
          "sha256": "128c1996ef6b287cf60f0d4186aa8c555b8ac993d6214ea4799343186bd8d774",
          "sha1": "840e008d1b46eee83cad884bb88c8a6fab047e71",
          "md5": "4714b43bac4ef8cb16837faa69b10330"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-9294166.klib",
          "url": "test-utils-fixture-js-9294166.klib",
          "size": 38261,
          "sha512": "19551697eecf9c4b4ccc8414352caa26b9764651734cd9b1f8ac565fc4d6f5ab9caf9659b0010850fd443bbf44fdd0f4d41957312eea18f95ecf1bbc373252d8",
          "sha256": "128c1996ef6b287cf60f0d4186aa8c555b8ac993d6214ea4799343186bd8d774",
          "sha1": "840e008d1b46eee83cad884bb88c8a6fab047e71",
          "md5": "4714b43bac4ef8cb16837faa69b10330"
        }
      ]
    }
  ]
}
