{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "fa9f81c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-fa9f81c.toml",
          "url": "antibytes-dependency-catalog-fa9f81c.toml",
          "size": 232720,
          "sha512": "3f0da9f4cd94dde52052974f8bf207dd41c4aa650cf33d8bc64f53f166672382e9b93908e9fb3387ea05bbd9f0d890515e97d55f39b00de17e28dc980b59b8fb",
          "sha256": "451a7a5f5f1b3f464148920482a3dba56a4674a11420c8dcff0f01af5123eb65",
          "sha1": "3c2ceca8dee06dbece640734acabbc2af03d6da6",
          "md5": "55e96ac0a483049878447113598832f9"
        }
      ]
    }
  ]
}
