{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/6c316c5/test-utils-coroutine-6c316c5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "6c316c5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-6c316c5.klib",
          "url": "test-utils-coroutine-js-6c316c5.klib",
          "size": 10178,
          "sha512": "0d73054f09d31d0a118ae4c3a6273e3a5a83b3f0e19d96af6dae1f5754bcbc1f1a4700e7e50536436c57f9be288539bf53d6760a0c31bb3c8a64cdb026abf3bb",
          "sha256": "98013acfd47c22bfec5100a7bb8ddefc84c7ef8e124261f0274ff587a2c5daab",
          "sha1": "317789781dea06da63e160340bbeef6407435322",
          "md5": "657c5ef1ac41acf06d4bf365e393393a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-6c316c5.klib",
          "url": "test-utils-coroutine-js-6c316c5.klib",
          "size": 10178,
          "sha512": "0d73054f09d31d0a118ae4c3a6273e3a5a83b3f0e19d96af6dae1f5754bcbc1f1a4700e7e50536436c57f9be288539bf53d6760a0c31bb3c8a64cdb026abf3bb",
          "sha256": "98013acfd47c22bfec5100a7bb8ddefc84c7ef8e124261f0274ff587a2c5daab",
          "sha1": "317789781dea06da63e160340bbeef6407435322",
          "md5": "657c5ef1ac41acf06d4bf365e393393a"
        }
      ]
    }
  ]
}
