{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "a922019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-metadata-a922019-all.jar",
          "url": "fixture-a922019-all.jar",
          "size": 14524,
          "sha512": "d4be1c6151836b0cb98f58e6e213327d339143830c833c291699c0fa132426b0cf65cbdf32f904ca002c61665e939fd2b58e9271c8d75ebeb4bc8903f6d167bd",
          "sha256": "ee0dd4e219d3a5759769d2761864fa78b50f4aba51f0e09b302cc3200be34751",
          "sha1": "dd35802d50e1515d9526f60e7c5bb27d279547c7",
          "md5": "b729ccd9799be0b3fbef0e3f4168ce74"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fixture-a922019.jar",
          "url": "fixture-a922019.jar",
          "size": 21286,
          "sha512": "270379b951d5b03056f70c5f0f6c8905d50ad2f6c45d7f2e67fe76ff2625719e48f3ebbdd37d7f514829a42effbdb2fe4594edc2b1b6eecd25a685895b3e4e8c",
          "sha256": "daa31a06665f77c30478aecee1877ffcb4359ef13fc15efb544c8e66b2666303",
          "sha1": "16f88c97b4ec524cf67dad5b56d6c5e37bc6c98f",
          "md5": "d1cc9016a84f68a434d6e3f996bdfce4"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fixture-android/a922019/fixture-android-a922019.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-android",
        "version": "a922019"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fixture-android/a922019/fixture-android-a922019.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-android",
        "version": "a922019"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-iosarm64/a922019/fixture-iosarm64-a922019.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-iosarm64",
        "version": "a922019"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-iosarm64/a922019/fixture-iosarm64-a922019.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-iosarm64",
        "version": "a922019"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-iossimulatorarm64/a922019/fixture-iossimulatorarm64-a922019.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-iossimulatorarm64",
        "version": "a922019"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-iossimulatorarm64/a922019/fixture-iossimulatorarm64-a922019.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-iossimulatorarm64",
        "version": "a922019"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-iosx64/a922019/fixture-iosx64-a922019.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-iosx64",
        "version": "a922019"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-iosx64/a922019/fixture-iosx64-a922019.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-iosx64",
        "version": "a922019"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../fixture-js/a922019/fixture-js-a922019.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-js",
        "version": "a922019"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../fixture-js/a922019/fixture-js-a922019.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-js",
        "version": "a922019"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fixture-jvm/a922019/fixture-jvm-a922019.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-jvm",
        "version": "a922019"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fixture-jvm/a922019/fixture-jvm-a922019.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-jvm",
        "version": "a922019"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-linuxx64/a922019/fixture-linuxx64-a922019.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-linuxx64",
        "version": "a922019"
      }
    }
  ]
}
