{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/9294166/test-utils-9294166.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "9294166",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm-9294166.jar",
          "url": "test-utils-jvm-9294166.jar",
          "size": 8803,
          "sha512": "9fcee38a0b16f32961cb5c3bc696cd61f6b59735f40be107d1b6fd2b31e179efd2d9c34e2a11a7e299ff40f4ec24195cd73bbdb88670306e5aa352e6568d8fa8",
          "sha256": "b57f2c3b3068052aee5ff77a57573a76939b51c2952207beeabaa00b8d525399",
          "sha1": "7a8c7f62b77586e134f4266b1593438b4ddd9148",
          "md5": "0ec6b1be5f5e627e3d0e4fa6d5946e1f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-9294166.jar",
          "url": "test-utils-jvm-9294166.jar",
          "size": 8803,
          "sha512": "9fcee38a0b16f32961cb5c3bc696cd61f6b59735f40be107d1b6fd2b31e179efd2d9c34e2a11a7e299ff40f4ec24195cd73bbdb88670306e5aa352e6568d8fa8",
          "sha256": "b57f2c3b3068052aee5ff77a57573a76939b51c2952207beeabaa00b8d525399",
          "sha1": "7a8c7f62b77586e134f4266b1593438b4ddd9148",
          "md5": "0ec6b1be5f5e627e3d0e4fa6d5946e1f"
        }
      ]
    }
  ]
}
