{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/c37cc63/test-utils-coroutine-c37cc63.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "c37cc63",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-coroutine-jvm-c37cc63.jar",
          "url": "test-utils-coroutine-jvm-c37cc63.jar",
          "size": 12013,
          "sha512": "4bdc712287aa0a1468382ecb835537065d8fa876eba3a598ec659bba4a65972184baa726b5a480238421fc0763836fb962f3306faf115216597d03baadc954ee",
          "sha256": "b62492c624048a37809ba1181ef3d180fde7ad0b2e5ee2cdda9169d9b807961f",
          "sha1": "c31a0c59663e61bb532b564dc299f74796781cfd",
          "md5": "84758b8077a3abc2c3c8d4e6dea1b2be"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-c37cc63.jar",
          "url": "test-utils-coroutine-jvm-c37cc63.jar",
          "size": 12013,
          "sha512": "4bdc712287aa0a1468382ecb835537065d8fa876eba3a598ec659bba4a65972184baa726b5a480238421fc0763836fb962f3306faf115216597d03baadc954ee",
          "sha256": "b62492c624048a37809ba1181ef3d180fde7ad0b2e5ee2cdda9169d9b807961f",
          "sha1": "c31a0c59663e61bb532b564dc299f74796781cfd",
          "md5": "84758b8077a3abc2c3c8d4e6dea1b2be"
        }
      ]
    }
  ]
}
