{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "694a031",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-694a031.jar",
          "url": "antibytes-android-application-configuration-694a031.jar",
          "size": 58039,
          "sha512": "380dcdce25d2bc5fcf1050c163b13c5f09a966935fd260ea4f7bc638cb196a66c80619189356d99d9f39e6cb8ad1cc9f666a6acd532e51edd5770aaf9d58634b",
          "sha256": "5357daff3d236806bf09e329665e08bda819263d0e2ac0cd091cdeb60169c922",
          "sha1": "3cb90fa6345bd2eb9029aa18845ab6ba3030affa",
          "md5": "68db674881bd0b8d3ae156fef79858f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "694a031"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-694a031.jar",
          "url": "antibytes-android-application-configuration-694a031.jar",
          "size": 58039,
          "sha512": "380dcdce25d2bc5fcf1050c163b13c5f09a966935fd260ea4f7bc638cb196a66c80619189356d99d9f39e6cb8ad1cc9f666a6acd532e51edd5770aaf9d58634b",
          "sha256": "5357daff3d236806bf09e329665e08bda819263d0e2ac0cd091cdeb60169c922",
          "sha1": "3cb90fa6345bd2eb9029aa18845ab6ba3030affa",
          "md5": "68db674881bd0b8d3ae156fef79858f7"
        }
      ]
    }
  ]
}
