{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iossimulatorarm64-0.1.1-SNAPSHOT.klib",
          "size": 155552,
          "sha512": "e56174bfaa55b94f4face92b2b2dcfcbc080e4339cce3d24f6e4f03f79cf82ae7ecfdcfe7d7aafacfefb4cd06ac44a7c300c8f1b8e2bbbccd53832c6ba0de220",
          "sha256": "35ffa9c8cccefc8fa306e066fe4b6ccd3a2f14c9fd67157dff43e95eafe66081",
          "sha1": "fe07cae982af1b3caf76fdbd9865b9e684c3db5c",
          "md5": "8b47b5983482779809f00264e10b5cd5"
        }
      ]
    }
  ]
}
