{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iossimulatorarm64-0.1.1-SNAPSHOT.klib",
          "size": 158041,
          "sha512": "db6d2f7de681bff1cf8b1af27396e952b61d4f26a8bcbecd223a9d12e5dfb2d9ce83cf97d99e7fa5229125a25cdb676a8d65049d5b5f289694d905a00827051a",
          "sha256": "d03eb2dfc09aae2dc0a1b7582c0de55f154e7baa3bb0dd901e791d61cf8066f8",
          "sha1": "1343bd71758ae89dad96da8b1325a6c738703ba7",
          "md5": "0ecf2bf6af0ff154a03ec775ff25dc67"
        }
      ]
    }
  ]
}
