{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iossimulatorarm64-0.1.1-SNAPSHOT.klib",
          "size": 154383,
          "sha512": "70ff3a775b78a8093895fe686e612beee9b8a7c6e94ef95c6cd651530c102d47007270b92c741d94f7c5b5749382a0ba6a9b92d6fc94be1686ce1e42a7f963f7",
          "sha256": "a8c1cda24e6ad1944d8ad125ce9b0e6efda9f15bb5186d27f239c32f465ff69b",
          "sha1": "134f9414dcaa7d146e76dcd76b05a8b9a7bf1c40",
          "md5": "8bdaec9717526dc5853cc01d791cc8f4"
        }
      ]
    }
  ]
}
