{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/24bf67b/test-utils-coroutine-24bf67b.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "24bf67b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js.klib",
          "url": "test-utils-coroutine-js-24bf67b.klib",
          "size": 7223,
          "sha512": "b81e3b5d9601c64c05064ff28538bb531cff986bbc686bdebab372ab4bebbf6b50ec8ba24633e5baef2f5b5553c861228005902c434225334eccdbf2a425a278",
          "sha256": "2c3412180b7999b9b23f8712ef023cdecd6a823d6994dc87762ce5e3555edf56",
          "sha1": "07fd157c3fd1737710b20cb09a6202914081c0e6",
          "md5": "65815d58404645da446f12c9aef6ab42"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js.klib",
          "url": "test-utils-coroutine-js-24bf67b.klib",
          "size": 7223,
          "sha512": "b81e3b5d9601c64c05064ff28538bb531cff986bbc686bdebab372ab4bebbf6b50ec8ba24633e5baef2f5b5553c861228005902c434225334eccdbf2a425a278",
          "sha256": "2c3412180b7999b9b23f8712ef023cdecd6a823d6994dc87762ce5e3555edf56",
          "sha1": "07fd157c3fd1737710b20cb09a6202914081c0e6",
          "md5": "65815d58404645da446f12c9aef6ab42"
        }
      ]
    }
  ]
}
