{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/8066bd0/test-utils-8066bd0.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "8066bd0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosx64-8066bd0.klib",
          "size": 7944,
          "sha512": "25f3a71877f32cf043dac487ebbb53d8da138e0ff58242b257dacc6cf1bffda14f850caf2c5713010be077c95100cdb40bb5033d18e37f52a1886c97a016e47d",
          "sha256": "619be0373b05e0e14ec541377c98618efb15f0cd650e2d89149c0d6ec2a582a7",
          "sha1": "55dd25723d1e0c3bf49f99524aff65c338fdf96a",
          "md5": "8e559a5c6968296c38bd2f011da07083"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosx64-8066bd0-metadata.jar",
          "url": "test-utils-iosx64-8066bd0-metadata.jar",
          "size": 261,
          "sha512": "e7fd671cc351f850fdfb6c06f22135619c4b5122365fb57833db53092be4a6ec531e1a328e35e820e050126b6f3aa84ce76741d58f8dae8e455530f023ce7f4a",
          "sha256": "221ef2949440bd850aad7151ed81568dcfa31a224038a42d1f998477f6dad8d4",
          "sha1": "b3ef05e225121a5d71032c8a637c379f2a274683",
          "md5": "cc82488c708e4d5cba8c981045fd2968"
        }
      ]
    }
  ]
}
