{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "c005b75",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-c005b75.jar",
          "url": "kmock-processor-c005b75.jar",
          "size": 31931,
          "sha512": "27a396581e523fb09b3afbb0d27e3de6fa1ebd4a58aa5503dc4cde1b26e52591c9def8a7e6ff92f82576ebab252a356069fe893dfe2d14c1210b8b1ac1fddb87",
          "sha256": "c6ca0378899ca6c9f762afaf1751711c5199a418de824af4c51f2c121c04625e",
          "sha1": "dff958795e063577af85a1cf16b94816034b5c02",
          "md5": "6eabdc68ed193b295026513089caf2f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "c005b75"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-c005b75.jar",
          "url": "kmock-processor-c005b75.jar",
          "size": 31931,
          "sha512": "27a396581e523fb09b3afbb0d27e3de6fa1ebd4a58aa5503dc4cde1b26e52591c9def8a7e6ff92f82576ebab252a356069fe893dfe2d14c1210b8b1ac1fddb87",
          "sha256": "c6ca0378899ca6c9f762afaf1751711c5199a418de824af4c51f2c121c04625e",
          "sha1": "dff958795e063577af85a1cf16b94816034b5c02",
          "md5": "6eabdc68ed193b295026513089caf2f3"
        }
      ]
    }
  ]
}
