{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/789d509/test-utils-789d509.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "789d509",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-789d509.jar",
          "size": 17516,
          "sha512": "b36d36ca7dc13e8033343ea86d7f30f1586263120a1aecb87b8c2a08367edf0e840feb9f790539168c0aded61abd09c0b82cc0557fdc1d59b8f240c654446754",
          "sha256": "9f3757c002f66d5f05194103cdce38ce7238d78dca08ce70211b03fd5109bcac",
          "sha1": "253e915feaed36616c76dd639de17948198f17cb",
          "md5": "56ee4aa309db4f193129dd4e253ac95f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-789d509.jar",
          "size": 17516,
          "sha512": "b36d36ca7dc13e8033343ea86d7f30f1586263120a1aecb87b8c2a08367edf0e840feb9f790539168c0aded61abd09c0b82cc0557fdc1d59b8f240c654446754",
          "sha256": "9f3757c002f66d5f05194103cdce38ce7238d78dca08ce70211b03fd5109bcac",
          "sha1": "253e915feaed36616c76dd639de17948198f17cb",
          "md5": "56ee4aa309db4f193129dd4e253ac95f"
        }
      ]
    }
  ]
}
