{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/10714ef/kmock-10714ef.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "10714ef",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-10714ef.klib",
          "url": "kmock-js-10714ef.klib",
          "size": 121173,
          "sha512": "0b9d841b75cb2da475d8e76e7e9b9987d88d30580bbc065d9f86c1d90159da831d92f8c0c583509d6286cf1332e712497c6264264cb32d14b2677fbd9f2a4aa3",
          "sha256": "596bac0753dcf5ac1b02687d66c5fd6a59c727277d828984a5f43bfb0e6452c3",
          "sha1": "e05fc888b38b130e04bf307717d14f4efa2fec66",
          "md5": "96ad98dcb7bf9a5745f9eabe3c40765d"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-10714ef.klib",
          "url": "kmock-js-10714ef.klib",
          "size": 121173,
          "sha512": "0b9d841b75cb2da475d8e76e7e9b9987d88d30580bbc065d9f86c1d90159da831d92f8c0c583509d6286cf1332e712497c6264264cb32d14b2677fbd9f2a4aa3",
          "sha256": "596bac0753dcf5ac1b02687d66c5fd6a59c727277d828984a5f43bfb0e6452c3",
          "sha1": "e05fc888b38b130e04bf307717d14f4efa2fec66",
          "md5": "96ad98dcb7bf9a5745f9eabe3c40765d"
        }
      ]
    }
  ]
}
