{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "2d16671",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-2d16671.jar",
          "url": "antibytes-dependency-node-2d16671.jar",
          "size": 21473,
          "sha512": "2ce8887bf2906559db574931027913065bc3eb9b8bbe7397945778d1999f28f821b3a2187e644036d1be1691ed44a0ac5794dbf8dc240ef1f34cabc8817483e7",
          "sha256": "e4ae07b136a0155dda14e2e340cce7cad15ae134563b70cb32363bd62897c67b",
          "sha1": "986968264436201a5763a7d06f80f95b45b94c77",
          "md5": "755e45660b3a5931d1bb9c3628a945cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-2d16671.jar",
          "url": "antibytes-dependency-node-2d16671.jar",
          "size": 21473,
          "sha512": "2ce8887bf2906559db574931027913065bc3eb9b8bbe7397945778d1999f28f821b3a2187e644036d1be1691ed44a0ac5794dbf8dc240ef1f34cabc8817483e7",
          "sha256": "e4ae07b136a0155dda14e2e340cce7cad15ae134563b70cb32363bd62897c67b",
          "sha1": "986968264436201a5763a7d06f80f95b45b94c77",
          "md5": "755e45660b3a5931d1bb9c3628a945cc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-2d16671-javadoc.jar",
          "url": "antibytes-dependency-node-2d16671-javadoc.jar",
          "size": 261,
          "sha512": "697485100bd9718ec4f3d3e7ce95ae11dd9b03a21cc4a150bc8d6796024485884e85d37d6a059bc75bfad14e5b4cb72089b7e6976cd53c53bfe8078d73153878",
          "sha256": "7af396f05ea6be9844db01e6dc0d5ee22d950512b345ef9f3d40c54379098b94",
          "sha1": "20abef31fe822b2b4564d04cd885122ba5865981",
          "md5": "f9ddaf0ccb31604b65cb2a1dc706f6d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-2d16671-sources.jar",
          "url": "antibytes-dependency-node-2d16671-sources.jar",
          "size": 4172,
          "sha512": "13884cf21530be484d1600e689af2cd22b0c80990231d8b754ca61ad8bd8f9c209de6b2db976558886c8d7d3cfffe98566d6e9bacc648d151ee3af9fa401babc",
          "sha256": "6fe17735b0331a26f0d4ba98030e0aaa8eda8c486bc0ef8cda4a40f7ab1f256a",
          "sha1": "c40157e86624fc245f3b5a5c860122b048f02d7a",
          "md5": "7d5ac754af0745081aa563e31ab52d60"
        }
      ]
    }
  ]
}
