{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/b9030f2/test-utils-b9030f2.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "b9030f2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-watchosx64-b9030f2.klib",
          "size": 8362,
          "sha512": "b2bb27f51766fe9910275517d0855289da63ef0fafdfb4a6bb7eabb577a1d56d59ca14f3964447a3718daa86e003d0246f4bf455a5c1ea65562f1eace6eb5c61",
          "sha256": "0b9437836fe7adeb07869f94a8f43667cb8c2b656661c6dc45519acd0b3d13cb",
          "sha1": "091a506be1dabc469cdfc8df1c6e8400a348ea73",
          "md5": "06864aba20c262d422e8a3dc990c7139"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-watchosx64-b9030f2-sources.jar",
          "url": "test-utils-watchosx64-b9030f2-sources.jar",
          "size": 2202,
          "sha512": "200f256b59ba175210138bed146ee54ab58c9bb91f071774698eb6b3f4920f792214d2d44a1cc764422cb2c09da1a0773d4d288080e067e60263b96f2ed68050",
          "sha256": "9e0bd104bc203c511c12aaf2143514ee32a59c775ece92a04e7ee764ee60affa",
          "sha1": "773bcb344a1f6fd820f6ee6e62aea2b59ecfa180",
          "md5": "8b3c7f259a640a3d1e2ffd34b7f29645"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-watchosx64-b9030f2-metadata.jar",
          "url": "test-utils-watchosx64-b9030f2-metadata.jar",
          "size": 261,
          "sha512": "9fae20ecafd86675299d11c8e76221dac4394235c4d874f36b608678fa21588394f4f328792af9deca5e65560c9c8989d5f79e26386d3836ed5950b6878cab2a",
          "sha256": "416a367c0b46399833e60326a7405f4fe1c83520a238cc9b097275c630eba75a",
          "sha1": "5c6b158bcb9cdec8e50fd76e973f371ffdf740cc",
          "md5": "d237b7ef8da25074d7d977ece565f0db"
        }
      ]
    }
  ]
}
