{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/56c4547/test-utils-coroutine-56c4547.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "56c4547",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-watchosarm32-56c4547.klib",
          "size": 10164,
          "sha512": "2fb7cd776c1660d5648efaa4036c8d7ad1730e862b34b5a4eb64639d32d8c59a59ff868da2212593f9f3058af89d61bae6c82a53fef3093e15760de0d773f88b",
          "sha256": "5a5b0ea09a6a4c57f7123ecd687e777a3e02210e37449d91da11d4996b35a215",
          "sha1": "5d0681f27128c0942d77dc89c08dc2e94b53b672",
          "md5": "7cd70034613cfc6520c2eca14803f014"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-watchosarm32-56c4547-metadata.jar",
          "url": "test-utils-coroutine-watchosarm32-56c4547-metadata.jar",
          "size": 261,
          "sha512": "5d2dbfa6b5325b4b2b7bc6b85ba887f84cb7c3bb5733964df861eabab995fb32485aef1a3bb3353180160ff24daf46f6c9b0364c9b9b3b0f4d488ffdd6be37ff",
          "sha256": "5032c852916cd646ae4e92cb50b964377704c36e235474dde3a973c2f965ba22",
          "sha1": "68b128870a6f9d57c0079b24e6980b40f405b92d",
          "md5": "19926347ddbcf6302baeb62f6a4de503"
        }
      ]
    }
  ]
}
