{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-78602a6661-SNAPSHOT/kmock-0.1.1-78602a6661-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-78602a6661-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-78602a6661-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-78602a6661-SNAPSHOT.klib",
          "size": 209672,
          "sha512": "fd43e3f44d61f12c34536f18d3022f827963a3237f19b8477a2001778bdc5c43572015dccb14a39b87f538a8280c9658868928c20120a7f726821f1cdfb46acf",
          "sha256": "80e0e5ecb160240d5b38da07e4ab325032b97bcfa9d13806b9bc1d1a87a8199f",
          "sha1": "02247112c13d37211bc5732eb1395b112d7de736",
          "md5": "95ef5712eea8f25822336f402a6d1611"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-78602a6661-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-78602a6661-SNAPSHOT.klib",
          "size": 209672,
          "sha512": "fd43e3f44d61f12c34536f18d3022f827963a3237f19b8477a2001778bdc5c43572015dccb14a39b87f538a8280c9658868928c20120a7f726821f1cdfb46acf",
          "sha256": "80e0e5ecb160240d5b38da07e4ab325032b97bcfa9d13806b9bc1d1a87a8199f",
          "sha1": "02247112c13d37211bc5732eb1395b112d7de736",
          "md5": "95ef5712eea8f25822336f402a6d1611"
        }
      ]
    }
  ]
}
