{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.kmp",
    "module": "antibytes-kmp-configuration",
    "version": "fcf90ae",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-fcf90ae.jar",
          "url": "antibytes-kmp-configuration-fcf90ae.jar",
          "size": 73528,
          "sha512": "bce882bd1d122fc288ee44cc77c6111dc38279c9d580f2e8dc813ea1a1a222889ef2e40daa2addf5083406bb36fd33f7e6f8ee7a28b5aa355825a550acd78e95",
          "sha256": "a820993bb4a1c4b2edf1198f18811fc64330e55aeafc82a6f503936c60e04293",
          "sha1": "4b338e3f56043c6bf5763cd07a495d8cfb203d2f",
          "md5": "67a3a36780bfaf61968cff3192a768c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "fcf90ae"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-kmp-configuration-fcf90ae.jar",
          "url": "antibytes-kmp-configuration-fcf90ae.jar",
          "size": 73528,
          "sha512": "bce882bd1d122fc288ee44cc77c6111dc38279c9d580f2e8dc813ea1a1a222889ef2e40daa2addf5083406bb36fd33f7e6f8ee7a28b5aa355825a550acd78e95",
          "sha256": "a820993bb4a1c4b2edf1198f18811fc64330e55aeafc82a6f503936c60e04293",
          "sha1": "4b338e3f56043c6bf5763cd07a495d8cfb203d2f",
          "md5": "67a3a36780bfaf61968cff3192a768c3"
        }
      ]
    }
  ]
}
