{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/1887fc4/core-1887fc4.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "1887fc4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-linuxx64-1887fc4.klib",
          "size": 50664,
          "sha512": "0401a3a10850d0623ef45de055bd25c5c1e04390c0a0ad6a3385449a79dbf6f9eb2285c6953e751c38e0bee8b81aa81a14fbfbf8d533a7d09e4a2a75e567b4a9",
          "sha256": "6f456597233db3ee4e252771f6ac54e30042e16d6cdd0e41df5878fb494e5f49",
          "sha1": "6ccf54f88a115157fd0a84f45285ff4991ebd413",
          "md5": "2d88380bf54d6afb1def1ccb23182571"
        }
      ]
    }
  ]
}
