{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "9388cf9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-9388cf9.jar",
          "url": "antibytes-gradle-utils-9388cf9.jar",
          "size": 9471,
          "sha512": "2c84bfaeb1423350990bf81b9ff79a0f77da0fe3719af464b26eafccfb38da9ca1bc476103a86e88827019d4414094a1d321c30833b2bea3bf85d657cf77493a",
          "sha256": "6026697de27d3c693f23fa2d5426e5d5937002841961d30fc0fb7fbe0b736813",
          "sha1": "d0e4f341b7a0c40dcb70a1bc403a68bded553612",
          "md5": "dedd389aa547a8e08c0f37ba87ea4b18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-9388cf9.jar",
          "url": "antibytes-gradle-utils-9388cf9.jar",
          "size": 9471,
          "sha512": "2c84bfaeb1423350990bf81b9ff79a0f77da0fe3719af464b26eafccfb38da9ca1bc476103a86e88827019d4414094a1d321c30833b2bea3bf85d657cf77493a",
          "sha256": "6026697de27d3c693f23fa2d5426e5d5937002841961d30fc0fb7fbe0b736813",
          "sha1": "d0e4f341b7a0c40dcb70a1bc403a68bded553612",
          "md5": "dedd389aa547a8e08c0f37ba87ea4b18"
        }
      ]
    }
  ]
}
