{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/d2c62a3/test-utils-annotations-d2c62a3.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "d2c62a3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-iosx64-d2c62a3.klib",
          "size": 11190,
          "sha512": "7636affaa2508e0641fd82b7b5312f754be431877d8ba8ccf48ce3e3cbb7c69b2877a3d5968896c05cb85068366fbd8be3d98d4b5d76b24f24e0667ecb15a954",
          "sha256": "600ab0112815257158cd95518792fa5f376bb19b4912b0d02f5d8eb95c43cb00",
          "sha1": "f299b0776b29df3292eefb2000e37152e09dd6f6",
          "md5": "b593084051b99e0e2280d02971e86651"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-iosx64-d2c62a3-metadata.jar",
          "url": "test-utils-annotations-iosx64-d2c62a3-metadata.jar",
          "size": 261,
          "sha512": "08230caef65ef181f31dba358db7f6920b5154da455c0d02c5b38823bbfe6d3f0e68129f8ada048b1c1f090b6b22f311413ef3660b0c1b4edc0d48dac851185b",
          "sha256": "a80bf1d9713e5668f068b4b37a9c97200d94f6f64887bf5dd2b9fa12f6937a42",
          "sha1": "e68ed34b9110efca7586ba3cb8dc245c63ee4849",
          "md5": "5b2308b38a8dfd16ef20159f4bc8a4ab"
        }
      ]
    }
  ]
}
