{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc02-SNAPSHOT/kmock-0.3.0-rc02-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc02-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosx64-0.3.0-rc02-SNAPSHOT.klib",
          "size": 202478,
          "sha512": "d7ae43050a139002a22e8329c426a9535b320f2d89107147fffc64398c5312501f5d1d3ec36ab2b48b1ca0b476806e70352c17221a276721bc6660ad80f0fa6e",
          "sha256": "f38ec759a1cb6eb75d0554d353cc7256e68c2aaf9f3ef3eb1196c3fd28cd9f21",
          "sha1": "09eefe70f3fcedf3ed7e20bbc08efbd627b263db",
          "md5": "170fedad2da8dc8de87c0ab695a63741"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosx64-0.3.0-rc02-SNAPSHOT-metadata.jar",
          "url": "kmock-iosx64-0.3.0-rc02-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "db721e2a9dd0ead059566d0ec3bfc8c527f5c6573ef6f55854c147e1f1987eaca28d8ae9b50de8773b2710b3f39ed62fd6be80618e64bafa6e3155f5c9a98a2d",
          "sha256": "20d8da17622dd215adf7cfda672932198f6dfa4dd7a97d218c1aa1bc2c7ce8c3",
          "sha1": "af5e2ade61e2005d50d1e25384b9aa3342f34211",
          "md5": "bf3838799d02bfecbed607e30fb4f36c"
        }
      ]
    }
  ]
}
