{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "db3eb1b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-db3eb1b.jar",
          "url": "antibytes-dependency-helper-db3eb1b.jar",
          "size": 69703,
          "sha512": "b41accbcb0e814e3739f2ed31d5cd17e57b2fe108f73bd0d8d48c476c77ce3d5a50bcd1475cf2b4292ed8bb35d34230a8c6af7a02d4533da236a282e2ae51343",
          "sha256": "b5cb59d5db6744dda590d5c9f1276b826fdad1a8b103fe387d5adb3dbc04bac7",
          "sha1": "9f86547641b6d06f27042924430b69285975d07c",
          "md5": "fd079ced2dd02cef4a1e602d07b8da6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.51.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "9.0.9"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "db3eb1b"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-db3eb1b.jar",
          "url": "antibytes-dependency-helper-db3eb1b.jar",
          "size": 69703,
          "sha512": "b41accbcb0e814e3739f2ed31d5cd17e57b2fe108f73bd0d8d48c476c77ce3d5a50bcd1475cf2b4292ed8bb35d34230a8c6af7a02d4533da236a282e2ae51343",
          "sha256": "b5cb59d5db6744dda590d5c9f1276b826fdad1a8b103fe387d5adb3dbc04bac7",
          "sha1": "9f86547641b6d06f27042924430b69285975d07c",
          "md5": "fd079ced2dd02cef4a1e602d07b8da6f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-db3eb1b-javadoc.jar",
          "url": "antibytes-dependency-helper-db3eb1b-javadoc.jar",
          "size": 261,
          "sha512": "61eba1254ef602931262fdbb731014186a0f4e41772edf21097b0b6d6b90a72782e1cf1c750577e0c13e87758b6b3da4e26ae8d1a1f4657ec120e56269be4ed8",
          "sha256": "52b875663e2cd9a362ea27b5384816971c2f3494b1aa025d3c4e5f4b17d02bcb",
          "sha1": "9f735c29c5afcbf0c814aeb1b213841b94e3b864",
          "md5": "26c3c0b4bb6e1b3b9da58d77b2c50baa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-db3eb1b-sources.jar",
          "url": "antibytes-dependency-helper-db3eb1b-sources.jar",
          "size": 9186,
          "sha512": "1758460473aa3f14d214cf6dd5960dab5fce8bfa4739380b15107123ee368545c7ca7b97efe4eebf748710f63af8879597f224626391bbd643f6642f3a097fdc",
          "sha256": "78d77e4f6eee3827ef55480495297603ff504014a6eda1c88bdf54e90392767d",
          "sha1": "4aff1957897fbfb16db965e2601eae25d03f2dcd",
          "md5": "166d3798bce0c5a0aa093185d4a28c55"
        }
      ]
    }
  ]
}
