{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "5318a03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-fixture-metadata-all.jar",
          "url": "test-utils-fixture-5318a03-all.jar",
          "size": 10303,
          "sha512": "e43614f2db5c35cd3914116d83c952b3393498f5236b37ee0863d8353d01bd49ae894a3ccd2c3a768d75a62b814b9cfcf8428ce7d21c041e14c353282823371c",
          "sha256": "9405c21ea0d43d2e66e6aaa9c1a6ab1111032ba7f00d5ac2e17fe39dccadb3c2",
          "sha1": "912cc10d4cf56223429aed0de3c30640365dd45f",
          "md5": "5f7d96704fe1a054b054779a6f9f4681"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-fixture.jar",
          "url": "test-utils-fixture-5318a03.jar",
          "size": 14716,
          "sha512": "36700a929a538d5e1a2687fba0249d6704f15c8792c159905eb6a59215dd8dd4f407d47a32a84fa5aed1d03699299ab9bdbc96d54cadb4bf96d034ea012a3ee2",
          "sha256": "b930944d0fe945d38402a071a6edaab8390d15f5cd3c13241f2b68508a26490d",
          "sha1": "d4160fbee720dcf5cf42b43c504f2cbddb96ae7d",
          "md5": "8b2f8b209527a31be7155ec57ddd64f5"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-android/5318a03/test-utils-fixture-android-5318a03.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-android",
        "version": "5318a03"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-android/5318a03/test-utils-fixture-android-5318a03.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-android",
        "version": "5318a03"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-fixture-js/5318a03/test-utils-fixture-js-5318a03.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-js",
        "version": "5318a03"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-fixture-js/5318a03/test-utils-fixture-js-5318a03.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-js",
        "version": "5318a03"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-jvm/5318a03/test-utils-fixture-jvm-5318a03.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-jvm",
        "version": "5318a03"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-jvm/5318a03/test-utils-fixture-jvm-5318a03.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-jvm",
        "version": "5318a03"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-linuxx64/5318a03/test-utils-fixture-linuxx64-5318a03.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-linuxx64",
        "version": "5318a03"
      }
    }
  ]
}
