{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-SNAPSHOT/ktx-datetime-0.3.1-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-linuxx64-0.3.1-SNAPSHOT.klib",
          "size": 12943,
          "sha512": "bba9909a0b931bcfb8a5f3d298f2fda508fa5746fb26e19cf99e4b0d8c6e2bd356c776873ee26f4f76c4b0ff5934876d62b31bef604990066265c30e7ce6ae8a",
          "sha256": "d7470cbd1b57dc0dd0c97487f1a86eda11ee7b0abdc3d97eb328f1ce591c45b4",
          "sha1": "5cbd3967014a2edb495d0ae138086a8e4dcdb9bf",
          "md5": "83ba2d9eebfda3bc3c0d2774df914c34"
        }
      ]
    }
  ]
}
