{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "8686647",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-8686647.jar",
          "url": "antibytes-custom-component-8686647.jar",
          "size": 16190,
          "sha512": "b4249c78da9ff687c4f40670fe03b14b57c6c04c7c9036c6cc032c80f393974a6a8f2a1e72a6787699ece1d74c049bdb8f8302ef2da8a75fc011ebe19ca57643",
          "sha256": "47b541abccb1a52e99a9c09a85d6fc19ce0601a0e2c0b32c24226a7af5d29652",
          "sha1": "2353c14079d4311298ad0c5e1698c1f4fa33ea02",
          "md5": "e76473b206007c6ce27160239424f1a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-8686647.jar",
          "url": "antibytes-custom-component-8686647.jar",
          "size": 16190,
          "sha512": "b4249c78da9ff687c4f40670fe03b14b57c6c04c7c9036c6cc032c80f393974a6a8f2a1e72a6787699ece1d74c049bdb8f8302ef2da8a75fc011ebe19ca57643",
          "sha256": "47b541abccb1a52e99a9c09a85d6fc19ce0601a0e2c0b32c24226a7af5d29652",
          "sha1": "2353c14079d4311298ad0c5e1698c1f4fa33ea02",
          "md5": "e76473b206007c6ce27160239424f1a4"
        }
      ]
    }
  ]
}
