{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "199297a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-199297a.jar",
          "url": "antibytes-gradle-utils-199297a.jar",
          "size": 9577,
          "sha512": "34325c8cc122db23e80a0f40182119eb7c68ae8cc90333a650a94e2b37f17e31fe5ed10032a5c3cb7afab86eb7def8ad0ab5de5aea238f9923278ad2e1015f76",
          "sha256": "5fdf64aa74476af593f5208176558ce868a24fe5bba999c501895d4559e9564b",
          "sha1": "2e512389286c1fbc05eb217831d12139f1dea202",
          "md5": "bb7acecd1fd776c243f030435ef7467d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-199297a.jar",
          "url": "antibytes-gradle-utils-199297a.jar",
          "size": 9577,
          "sha512": "34325c8cc122db23e80a0f40182119eb7c68ae8cc90333a650a94e2b37f17e31fe5ed10032a5c3cb7afab86eb7def8ad0ab5de5aea238f9923278ad2e1015f76",
          "sha256": "5fdf64aa74476af593f5208176558ce868a24fe5bba999c501895d4559e9564b",
          "sha1": "2e512389286c1fbc05eb217831d12139f1dea202",
          "md5": "bb7acecd1fd776c243f030435ef7467d"
        }
      ]
    }
  ]
}
