{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "431afe3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-431afe3.jar",
          "url": "antibytes-gradle-utils-431afe3.jar",
          "size": 9421,
          "sha512": "26e889423616a16bde31fd5dff2a693dabca029dcbf6600a8e34377ee745d50798f0fd1b45b2c4020a82b08550847401d41ae39da688b79e6214200d1171071b",
          "sha256": "994e4f7e034bd746794ab6aab371c3c688d8649f550ec3a240779f07326f277b",
          "sha1": "254f907874df76e05315a74a1c54857f450024e9",
          "md5": "110726c744a9d68c12e65c4c9f560f00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-431afe3.jar",
          "url": "antibytes-gradle-utils-431afe3.jar",
          "size": 9421,
          "sha512": "26e889423616a16bde31fd5dff2a693dabca029dcbf6600a8e34377ee745d50798f0fd1b45b2c4020a82b08550847401d41ae39da688b79e6214200d1171071b",
          "sha256": "994e4f7e034bd746794ab6aab371c3c688d8649f550ec3a240779f07326f277b",
          "sha1": "254f907874df76e05315a74a1c54857f450024e9",
          "md5": "110726c744a9d68c12e65c4c9f560f00"
        }
      ]
    }
  ]
}
