{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-custom-component",
    "version": "150b2e1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-150b2e1.jar",
          "url": "antibytes-custom-component-150b2e1.jar",
          "size": 16176,
          "sha512": "da6b01344811821dad22e5a7b1cb35adf48782a0e6aea2b84bba392f60068be6a001b87c700811f2bc756612c322981bba180e6c376a69be79fb95e647dd53bd",
          "sha256": "ed19bf05ded5fe0ec9f7312e095af75ae0b491a66ff20df9f56cd87c1fb237b3",
          "sha1": "72771393ad138bc3ae55c3928f5363bccf1739bd",
          "md5": "a805acbbe46916da2106f334d3e259e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-150b2e1.jar",
          "url": "antibytes-custom-component-150b2e1.jar",
          "size": 16176,
          "sha512": "da6b01344811821dad22e5a7b1cb35adf48782a0e6aea2b84bba392f60068be6a001b87c700811f2bc756612c322981bba180e6c376a69be79fb95e647dd53bd",
          "sha256": "ed19bf05ded5fe0ec9f7312e095af75ae0b491a66ff20df9f56cd87c1fb237b3",
          "sha1": "72771393ad138bc3ae55c3928f5363bccf1739bd",
          "md5": "a805acbbe46916da2106f334d3e259e4"
        }
      ]
    }
  ]
}
