{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/64c6243/test-utils-annotations-64c6243.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "64c6243",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-linuxx64-64c6243.klib",
          "size": 11207,
          "sha512": "f6a84964b6ff471429126ee646aff065f435f8423ba194750d8353c6a3ebdffedf1e94e33ff5e43a780abac8c9fbe175c61304a5104206951be4416ae28723b2",
          "sha256": "341c68b17c03e968735c8cc70d1ca4151ae7712bac0ab7485d3803eec7ea649f",
          "sha1": "758a57325c8035bd49c600d4a02a14a8f03787ad",
          "md5": "38488a7b1d12ef872ed7673caca85a15"
        }
      ]
    }
  ]
}
