{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/fc88d6a/test-utils-ktor-fc88d6a.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "fc88d6a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-watchossimulatorarm64-fc88d6a.klib",
          "size": 15147,
          "sha512": "7e4c229e9a77a84cbeb057eb612546d5d21b3982ce5656b8564674df622a9f545037ec466e97a4f26b0ec06f58967ee3108512aed3fad6cd2cf85475ea96dc77",
          "sha256": "141250f441b5362f48083257d19a7f29b6fd59fd093e2ecf423a6cc1357d5b9c",
          "sha1": "fb4dae06a16609ac6be24a724fcb898dd66fc702",
          "md5": "ac86fad515ace0fde907e57ac1666739"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-watchossimulatorarm64-fc88d6a-metadata.jar",
          "url": "test-utils-ktor-watchossimulatorarm64-fc88d6a-metadata.jar",
          "size": 261,
          "sha512": "b41d90e4be1da78f19a1df46f6fde583b4bdf623158c0b2f65c9f5ecd7a0d6451fb62f83db59cba27e9a7de183f4554049084048b4fff9c7afbc9def4a4052dc",
          "sha256": "10c54be13047886413a4e3850c31ff940c2857545b71ada0f173fbe5bbe93114",
          "sha1": "5e09aae6d3eb65b5902ffca9d9882aae1b302587",
          "md5": "a01d4bd5f639e66a009a17d1eb628360"
        }
      ]
    }
  ]
}
