{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/b6c6e6c/test-utils-annotations-junit5-b6c6e6c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "b6c6e6c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-tvosarm64-b6c6e6c.klib",
          "size": 7086,
          "sha512": "96c73ecaf05bed31dba0e1bfb393b0952799c6a9737b998fb40639d6c507f82679f4a6d37959ed5cc4f1c19f7bc1f0b77bf4c3ef492371ec8da05721bf05edf4",
          "sha256": "e605eb3e96381b4d6620fc856b51f07b6dab526d10483e05be70c9897554bd5b",
          "sha1": "b8c15e0d04d6849b325852b95d34195a0c46d639",
          "md5": "4cf3561a74fcb635df11fe261c618d0f"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-annotations-junit5-tvosarm64-b6c6e6c-sources.jar",
          "url": "test-utils-annotations-junit5-tvosarm64-b6c6e6c-sources.jar",
          "size": 3477,
          "sha512": "8910488f2acc4f4c669bf3e6a74835e60ede75d2286f44304a32d7435e9374f50e400ec91ccdc9fcab868fe57ac79f9cc99c5183a87396417d48b059ee008e7f",
          "sha256": "9f2d1a8fe1210ea25bd9b54214171ccdd8f68d07f8c4c7bf4fdaa277b2d059e9",
          "sha1": "c0915589af235519923fb41575cb1d6e37f9dedf",
          "md5": "b993ac9b3bda4583966bb9266ec6da60"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-tvosarm64-b6c6e6c-metadata.jar",
          "url": "test-utils-annotations-junit5-tvosarm64-b6c6e6c-metadata.jar",
          "size": 261,
          "sha512": "8b688f3abd4224d87068b74f4081b5fb4a5d64b9ebae105813b4d7abd344ce72a2be70db101e1ff8b8596924842418c6773c122ae8d035a122801a5f01e5c6b5",
          "sha256": "752818039928da2e7982c5daba71dd5146c0ca47038f2df94944630449a25c05",
          "sha1": "d69eb5657d031db62bcedf6707e2ab644226fa84",
          "md5": "eb5ac7c501fb8a60a8831f71e0e2c619"
        }
      ]
    }
  ]
}
