{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "999693f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-999693f.jar",
          "url": "antibytes-gradle-test-utils-999693f.jar",
          "size": 17243,
          "sha512": "b1d6c83265296fc3bda4afedd549200f1f5352d4397aef6ead8dcd253afea24c8a2c0abcddd0f7bb664a885131a8f2620424ed841c9754b97e9602ee6fecb4cf",
          "sha256": "37c305f4c9233faabf2582cc55d07c3ea282bebe8fefa6cea933a602bb4fa16f",
          "sha1": "5b91cbe4778a22a860e6ef5361b7f61a8489df22",
          "md5": "b33f9c272947154d0af5c2d7fbb105e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-999693f.jar",
          "url": "antibytes-gradle-test-utils-999693f.jar",
          "size": 17243,
          "sha512": "b1d6c83265296fc3bda4afedd549200f1f5352d4397aef6ead8dcd253afea24c8a2c0abcddd0f7bb664a885131a8f2620424ed841c9754b97e9602ee6fecb4cf",
          "sha256": "37c305f4c9233faabf2582cc55d07c3ea282bebe8fefa6cea933a602bb4fa16f",
          "sha1": "5b91cbe4778a22a860e6ef5361b7f61a8489df22",
          "md5": "b33f9c272947154d0af5c2d7fbb105e4"
        }
      ]
    }
  ]
}
