{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "2fa240c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-2fa240c.jar",
          "url": "antibytes-dependency-2fa240c.jar",
          "size": 71463,
          "sha512": "207612b9f6e30e9ce3863aaff2ec8d5c8a4b5d00fb164e2c0779fecb3564326e3dbf94fb066b84961af22c2d6b303f92f8fa6b45ab8a748f91ceae35492467f5",
          "sha256": "d9331dc2c29d9d28a151f0137dace15ce14b16b86489104425fd5b959950e12e",
          "sha1": "46921b1fac6a274963776a759e5e928a75cc3c6e",
          "md5": "06691329e79bb9f25c1bf74fc89f6bae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-gradle-plugin",
          "version": {
            "requires": "0.17.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.0.4.1"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.44.0"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "2fa240c"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-2fa240c.jar",
          "url": "antibytes-dependency-2fa240c.jar",
          "size": 71463,
          "sha512": "207612b9f6e30e9ce3863aaff2ec8d5c8a4b5d00fb164e2c0779fecb3564326e3dbf94fb066b84961af22c2d6b303f92f8fa6b45ab8a748f91ceae35492467f5",
          "sha256": "d9331dc2c29d9d28a151f0137dace15ce14b16b86489104425fd5b959950e12e",
          "sha1": "46921b1fac6a274963776a759e5e928a75cc3c6e",
          "md5": "06691329e79bb9f25c1bf74fc89f6bae"
        }
      ]
    }
  ]
}
