{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/85c7d84/fixture-85c7d84.module",
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "85c7d84",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture.klib",
          "url": "fixture-iossimulatorarm64-85c7d84.klib",
          "size": 32971,
          "sha512": "136db52552f5b2ae1925607857197300c4afc4d7740d7dd0d72ab12913cf9987c0e4db1b785e1eb94f17910e25ec69edcb5464219b1d0f82c1562b75c7c15057",
          "sha256": "1b44e98cccbd8c61eef731e64a9f388cb209143d92e79bbcceef7b8e1433fc0e",
          "sha1": "0d876f60a60d94eb5db7b7e83ca1ad31ce2c9073",
          "md5": "f4e06af2fc802b3f3005f457e202d3d4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-iossimulatorarm64-85c7d84-metadata.jar",
          "url": "fixture-iossimulatorarm64-85c7d84-metadata.jar",
          "size": 261,
          "sha512": "57270a5101950afe9b503abef90fa9be1ebc9fef0921fc08d2a12eb8dad4da4f55d70c75a6254bc809da5b945f7c3a2ed945c7a6ac38f30fecda8a959d97544c",
          "sha256": "854aaa7062f8b09651acfa5229ff144eda23ed39cc6729fa15deaf107c8cffa4",
          "sha1": "4084bc9b818666577c3ec51de8d1099c021df016",
          "md5": "180ba2c6342fd62c86d4a3849e735b0c"
        }
      ]
    }
  ]
}
