{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "clientSDK",
    "version": "bf3391d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "clientSDK-metadata-bf3391d-all.jar",
          "url": "clientSDK-bf3391d-all.jar",
          "size": 11843,
          "sha512": "5a0ceefa9f470c92236503bec49b0401641d0b9a758bc27f9cf35986ea3e2524ad6d52cbd050e9e8497317d8418ada186723f8388b84fb3a966e39635c55e04d",
          "sha256": "e909bbb2ff000d899a8fe2c398133c682837dc354f9dbf43de155b13b9503e54",
          "sha1": "25053eaa680ad9ec7b4634969216c9730a2118e0",
          "md5": "304a321370ccbc27b738ea9a71e09f5c"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "clientSDK-bf3391d.jar",
          "url": "clientSDK-bf3391d.jar",
          "size": 13629,
          "sha512": "22893eb14c22be4d9e2689469810704c26907d7119a1c7876f3991d426c6012f2f98629bd92e3125873dfd770565dbb8d45daddf63a1647243f111ecbf6c68f7",
          "sha256": "7be758b6b28dbc4e4c1f4ddf2b483bec7352189ac55dc4e9564bfa79edb642a9",
          "sha1": "db449a1af50e00b1e79627b164213f3128da16da",
          "md5": "3fbb22cfe45c19d3599db00814921a0f"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../clientSDK-android/bf3391d/clientSDK-android-bf3391d.module",
        "group": "tech.antibytes.kmock",
        "module": "clientSDK-android",
        "version": "bf3391d"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../clientSDK-android/bf3391d/clientSDK-android-bf3391d.module",
        "group": "tech.antibytes.kmock",
        "module": "clientSDK-android",
        "version": "bf3391d"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../clientSDK-js/bf3391d/clientSDK-js-bf3391d.module",
        "group": "tech.antibytes.kmock",
        "module": "clientSDK-js",
        "version": "bf3391d"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../clientSDK-js/bf3391d/clientSDK-js-bf3391d.module",
        "group": "tech.antibytes.kmock",
        "module": "clientSDK-js",
        "version": "bf3391d"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../clientSDK-jvm/bf3391d/clientSDK-jvm-bf3391d.module",
        "group": "tech.antibytes.kmock",
        "module": "clientSDK-jvm",
        "version": "bf3391d"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../clientSDK-jvm/bf3391d/clientSDK-jvm-bf3391d.module",
        "group": "tech.antibytes.kmock",
        "module": "clientSDK-jvm",
        "version": "bf3391d"
      }
    }
  ]
}
