{
  "formatVersion": "1.1",
  "component": {
    "url": "../../banana-i18n/d1578d9/banana-i18n-d1578d9.module",
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "d1578d9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-d1578d9.jar",
          "size": 32442,
          "sha512": "41d9fef04ef73e6ea4547e580947e0538ae5dc30e4a6230c96e5a8f439e811c0a17361480e591696ea229868c487bc7cc873d5e79bb4bb521b5d146c3cf0e919",
          "sha256": "3bf583a274057dcc474e18deb4f471e68660f2f1659a203333da0d6848708601",
          "sha1": "832283103e77b0e2eab279fc304036f89eb6211d",
          "md5": "6424bdf4b6d7f19e6b318d46acc66633"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-d1578d9.jar",
          "size": 32442,
          "sha512": "41d9fef04ef73e6ea4547e580947e0538ae5dc30e4a6230c96e5a8f439e811c0a17361480e591696ea229868c487bc7cc873d5e79bb4bb521b5d146c3cf0e919",
          "sha256": "3bf583a274057dcc474e18deb4f471e68660f2f1659a203333da0d6848708601",
          "sha1": "832283103e77b0e2eab279fc304036f89eb6211d",
          "md5": "6424bdf4b6d7f19e6b318d46acc66633"
        }
      ]
    }
  ]
}
