{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/fc88d6a/test-utils-annotations-junit5-fc88d6a.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "fc88d6a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-iosarm64-fc88d6a.klib",
          "size": 7049,
          "sha512": "e82644416b7480c0e1e297e8b55903278dd59dcbe80a4aba35c969a5d55202c1b0fcb1a6cf5fac3b3cee4945a57f44ba15fcfdd82d726015f92482799375c2a1",
          "sha256": "cf3ab81b6becab5c1e36f156abf3ed0cac8ea12777f2a8d7242ca76b377c13df",
          "sha1": "f2399643618d581a8b56df40dbfe051f03472ef1",
          "md5": "8e92a1493a8e1a501e163317c9ffd25e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-iosarm64-fc88d6a-metadata.jar",
          "url": "test-utils-annotations-junit5-iosarm64-fc88d6a-metadata.jar",
          "size": 261,
          "sha512": "46884ac66fab465c9f9a19112adb843dab85d4259eb27029fa04329ff290a44e49ebe296ae4e4c6e1c1a6574b478a250b7f68ce6b0702b0b8f193f67945df770",
          "sha256": "d470dc6054117590cb4ef1831d90f996bf830834adb62fd64ce449e5be56f7c1",
          "sha1": "554ce9292e042db95fbfb0720b02ccf2e3fcf63d",
          "md5": "80bd933dd0faba424c210d23243dd92f"
        }
      ]
    }
  ]
}
