{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "d7af18f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-d7af18f.jar",
          "url": "antibytes-dependency-d7af18f.jar",
          "size": 45956,
          "sha512": "3a650e248e36d9540e081d31772570d01eb75238dbd10737c648dc3fa658c764addec858b7968d2120857d49e6768328a66601e7eba76d6f50c35b852302e72b",
          "sha256": "83f1fb4c081cd4edd265411db6621477d5b4aed6d5b66cc20ef6ed79e8be2692",
          "sha1": "01322670b7d4800b2eacbb991e3883275aee08e5",
          "md5": "d82e8c89831f3379d2b8b63e9916bca8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.39.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "6.5.1"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.43.2"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "d7af18f"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-d7af18f.jar",
          "url": "antibytes-dependency-d7af18f.jar",
          "size": 45956,
          "sha512": "3a650e248e36d9540e081d31772570d01eb75238dbd10737c648dc3fa658c764addec858b7968d2120857d49e6768328a66601e7eba76d6f50c35b852302e72b",
          "sha256": "83f1fb4c081cd4edd265411db6621477d5b4aed6d5b66cc20ef6ed79e8be2692",
          "sha1": "01322670b7d4800b2eacbb991e3883275aee08e5",
          "md5": "d82e8c89831f3379d2b8b63e9916bca8"
        }
      ]
    }
  ]
}
