{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/56c4547/test-utils-annotations-junit5-56c4547.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "56c4547",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-iosarm32-56c4547.klib",
          "size": 7049,
          "sha512": "a6dd9a3a567969fd9905cf0dc9f50114fc03c7a85b8f938d941aa9665506cfc3db3835ae1a64349083578a4cb8e1de347ad7a490a65b3894a93dcf9bd2e8083e",
          "sha256": "ca0e705b9ff325a7b3e27229d3ab104d7c6721214f280317d76ed3103f0dc2e1",
          "sha1": "367df46f17bb68f601df4927fd31b10bc95274b8",
          "md5": "5ed3b3657b59e066ccc9e2a8a6934bed"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-iosarm32-56c4547-metadata.jar",
          "url": "test-utils-annotations-junit5-iosarm32-56c4547-metadata.jar",
          "size": 261,
          "sha512": "60a5f35c9ed365545a0ad078eea44588014dbb9fbf38b028b9184d8f9be5c0b14b762d06ce1219452d92186512c970ae681de0e0e8593b717ab8c304c7666f0a",
          "sha256": "ef90a239000c69d9cdccc3243dee13bef1663288d6c2e5ed3932d98a7873226b",
          "sha1": "55dd6ad5fbda47435ac36672852baac3671c2d09",
          "md5": "0231404f417c5a5c4e2609948883da07"
        }
      ]
    }
  ]
}
