{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/b6c6e6c/test-utils-resourceloader-b6c6e6c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "b6c6e6c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-mingwx64-b6c6e6c.klib",
          "size": 13556,
          "sha512": "cedfec5725e22e4f401d4bb94228d0d09ce596c2e40a7dc7a89701693408f432f5b23279b0703c3982e61087de890785eb1084ba65eb56e5747750d7723d91ec",
          "sha256": "f4c4179dad07287641d058ba189ce2b62c68a7f8e4d05b05c6d63a5ee4a873e3",
          "sha1": "03c47f9d0ebc9b434a35da1f44c8e3126ffb2ef6",
          "md5": "614712314a817cb04aa978ff7d33cc1d"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-mingwx64-b6c6e6c-sources.jar",
          "url": "test-utils-resourceloader-mingwx64-b6c6e6c-sources.jar",
          "size": 4204,
          "sha512": "c70fd08cf38ce00e62349843747847484618f84f805329d7b3a96e9da4c5ffa7985a59b7d39451f41378cb78dea05d762f26b9dfe1d746554543c97b1f4536e1",
          "sha256": "5b8fa5be6494196d10ba709b586e0bce719d7bcdb1d650ec2ee204e3bcfbce96",
          "sha1": "4de28980514374a11665737f18c4650b8179ff14",
          "md5": "9813e4a4fbbc0e94af294a4bd3b2196e"
        }
      ]
    }
  ]
}
