{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.kmp",
    "module": "antibytes-kmp-configuration",
    "version": "4827895",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-4827895.jar",
          "url": "antibytes-kmp-configuration-4827895.jar",
          "size": 72745,
          "sha512": "7ceda17c87aa8fc4dae738c08a0d0db948d85bd711651d0f8bd02879c615414493bd95bc00ac3cfded4ca4f7ccd6bbe5669ec17e0fe21f6dd4c5b61ec295e3f1",
          "sha256": "a98687f1266faa34dc3583b89fd1b3d1016ed6d5428274dd5be1b065724224a1",
          "sha1": "9149fab8c20e5981281a593025c74c68707df951",
          "md5": "007dd7598b56703f17c43fbaf439f689"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "4827895"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-kmp-configuration-4827895.jar",
          "url": "antibytes-kmp-configuration-4827895.jar",
          "size": 72745,
          "sha512": "7ceda17c87aa8fc4dae738c08a0d0db948d85bd711651d0f8bd02879c615414493bd95bc00ac3cfded4ca4f7ccd6bbe5669ec17e0fe21f6dd4c5b61ec295e3f1",
          "sha256": "a98687f1266faa34dc3583b89fd1b3d1016ed6d5428274dd5be1b065724224a1",
          "sha1": "9149fab8c20e5981281a593025c74c68707df951",
          "md5": "007dd7598b56703f17c43fbaf439f689"
        }
      ]
    }
  ]
}
