{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/3e118d0/test-utils-annotations-3e118d0.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "3e118d0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-3e118d0.klib",
          "url": "test-utils-annotations-js-3e118d0.klib",
          "size": 9733,
          "sha512": "494d8686a74a3a814460c524060f18e9f42388aa612dc51d5ee13bf0987985113f0fe2f4b9b1450f9b3e6d490701289a8ea4ccf9acd8025a081941308e318636",
          "sha256": "5d4e8862aec0e5696fb9ff6b82033b91a52b181f07ac7a76627d45bb93298a27",
          "sha1": "d78a68816565b2f5a32ab2fea1fd76c967b83a56",
          "md5": "c41853862a4f77d77d0656f8da17c472"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-3e118d0.klib",
          "url": "test-utils-annotations-js-3e118d0.klib",
          "size": 9733,
          "sha512": "494d8686a74a3a814460c524060f18e9f42388aa612dc51d5ee13bf0987985113f0fe2f4b9b1450f9b3e6d490701289a8ea4ccf9acd8025a081941308e318636",
          "sha256": "5d4e8862aec0e5696fb9ff6b82033b91a52b181f07ac7a76627d45bb93298a27",
          "sha1": "d78a68816565b2f5a32ab2fea1fd76c967b83a56",
          "md5": "c41853862a4f77d77d0656f8da17c472"
        }
      ]
    }
  ]
}
