{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/5318a03/test-utils-annotations-5318a03.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "5318a03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm.jar",
          "url": "test-utils-annotations-jvm-5318a03.jar",
          "size": 10872,
          "sha512": "ed9220bf8be10aa580505cc263b95105a162be490f115ac402d0e1c01628e9f3e00bc0b46b714a1f59013252f16c678c315e7fc4edc6ea1068bf77ee5a17ebfb",
          "sha256": "fc0b4eb7a50592ac5171d697ba9caad7c0f3a96795547e93d9770400e918b771",
          "sha1": "5330034a153eab055a651a4af4a196d4bd834867",
          "md5": "92572563ed15bf020fb6ac647eeecba4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm.jar",
          "url": "test-utils-annotations-jvm-5318a03.jar",
          "size": 10872,
          "sha512": "ed9220bf8be10aa580505cc263b95105a162be490f115ac402d0e1c01628e9f3e00bc0b46b714a1f59013252f16c678c315e7fc4edc6ea1068bf77ee5a17ebfb",
          "sha256": "fc0b4eb7a50592ac5171d697ba9caad7c0f3a96795547e93d9770400e918b771",
          "sha1": "5330034a153eab055a651a4af4a196d4bd834867",
          "md5": "92572563ed15bf020fb6ac647eeecba4"
        }
      ]
    }
  ]
}
