{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "a426ee6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-a426ee6.toml",
          "url": "antibytes-dependency-catalog-a426ee6.toml",
          "size": 249942,
          "sha512": "1d2ac385dae2a9afde5ffe6c26767685f713739a8d758aabea0936d22f0e71575a45eb1d8343f91fc3f3561dd8b20e7f381ace1446e21a558cba68423ade4f90",
          "sha256": "87436b96697cded2d23cc1872873c58f98c87c5709b0e3540911bf3fd4fb316a",
          "sha1": "2472fb44fe2964d12f8b9d7d40c19e37af7b5210",
          "md5": "8c28d311d3dba9366763d7e935ec08af"
        }
      ]
    }
  ]
}
