{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/dbba7bb/test-utils-resourceloader-dbba7bb.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "dbba7bb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-watchossimulatorarm64-dbba7bb.klib",
          "size": 12987,
          "sha512": "03f6ac1e3f8fa2103a667566aa55c217d37941df7843fa0161353db92cd593b9b51ff855b9ae4f0e8db5268e3f05d086dd6cad1dcad75359147f013781127086",
          "sha256": "822a62aa274eccaceb720db3a905492c267594ea28f947dd090ef5f49e72195a",
          "sha1": "4acb42eff9af631f38eef0dc10ad9cf0553a3a46",
          "md5": "13eab5c1282aa261e6ce17e79baf66f0"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-watchossimulatorarm64-dbba7bb-metadata.jar",
          "url": "test-utils-resourceloader-watchossimulatorarm64-dbba7bb-metadata.jar",
          "size": 261,
          "sha512": "b295053751b08c2aa298f99bc5862b5d2ac523c853bab165f048eb3db1e153f5dab371471dd2fad38d5ff3df64eaf1e2a64d53bec234a27f8e1b614e637ddd1f",
          "sha256": "8e379d4931be8174719b90f1996fd5aa0d9b4b239043689722d1d2e1a6fe7b34",
          "sha1": "e5b7e920257373a3187e61d90d6606bf214fc5bf",
          "md5": "f370fa3627fe04da22de5792f7353b9c"
        }
      ]
    }
  ]
}
