{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc07-SNAPSHOT/kmock-0.3.0-rc07-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc07-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosarm32-0.3.0-rc07-SNAPSHOT.klib",
          "size": 203016,
          "sha512": "a393f423952685a0792885404d70a3578ec08122a77292c5670cbcff98ac2606807fac80c73d59cf4ac62faf084654ec0a715ed6d3dd791a34b3c652a48933d9",
          "sha256": "43e1f2b5f8dd786427c158a73e6c0eda2bb58a3b91a4090adee93b99e1d6671f",
          "sha1": "51d7e980345e29aacfb518849def6f99165d95d7",
          "md5": "fe0c9cc38e1bdaa6e40c96b6e784ef74"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosarm32-0.3.0-rc07-SNAPSHOT-metadata.jar",
          "url": "kmock-iosarm32-0.3.0-rc07-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "dfbc7fb16340a220ec7fca2eca77f395d65e714ae7541600334692af7e35439f8ed4653955e08537e9d807558d3efc456b458e9521ac1f3c3c6045b3023de2b5",
          "sha256": "6fc9b799a07c1ea420595b56058fa1af2b4d42538c616f8209cf0c78ebdb3640",
          "sha1": "ac077a7818de79b8d4ae5abf90434fdc3e0563ae",
          "md5": "d649fe4d164bc7ea095491b8e902c2f4"
        }
      ]
    }
  ]
}
