{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "41c21f2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-41c21f2.jar",
          "url": "antibytes-grammar-tools-41c21f2.jar",
          "size": 39373,
          "sha512": "2955b8580b625b311f9b3bd90f352fa77060abf9a8024fcc7ed4517476ce6cd2336bf66abee170b48acbaaa962e917f636f6b02257e10f0fe3c2581c343b594f",
          "sha256": "6b34d7c76be6c85890786d91b296b54d574d60889463753a2a33ca23f1568123",
          "sha1": "a84e843f945d171412dc960161b817ffd374f7aa",
          "md5": "f969315388a0937f82a0342e57b7996c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-41c21f2.jar",
          "url": "antibytes-grammar-tools-41c21f2.jar",
          "size": 39373,
          "sha512": "2955b8580b625b311f9b3bd90f352fa77060abf9a8024fcc7ed4517476ce6cd2336bf66abee170b48acbaaa962e917f636f6b02257e10f0fe3c2581c343b594f",
          "sha256": "6b34d7c76be6c85890786d91b296b54d574d60889463753a2a33ca23f1568123",
          "sha1": "a84e843f945d171412dc960161b817ffd374f7aa",
          "md5": "f969315388a0937f82a0342e57b7996c"
        }
      ]
    }
  ]
}
