{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "eedd006",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-eedd006.jar",
          "url": "antibytes-coverage-eedd006.jar",
          "size": 135215,
          "sha512": "562f4c8567765588bf3256855b95760697972fa5c64a010e52121aa3ebebe44b6caa9e7096404a48d56782f820f0e1402a521c8e315232662fa7f86e6cf335cc",
          "sha256": "d3750719637bf24efaf2eab12d2fa362af1895f6d82c6c4d42626f094ab0b708",
          "sha1": "86cf1520c8d3db8a30487097c25764282cfe07e2",
          "md5": "734babe4e98a6ae06ac1e5bb2d4cc3a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "eedd006"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-eedd006.jar",
          "url": "antibytes-coverage-eedd006.jar",
          "size": 135215,
          "sha512": "562f4c8567765588bf3256855b95760697972fa5c64a010e52121aa3ebebe44b6caa9e7096404a48d56782f820f0e1402a521c8e315232662fa7f86e6cf335cc",
          "sha256": "d3750719637bf24efaf2eab12d2fa362af1895f6d82c6c4d42626f094ab0b708",
          "sha1": "86cf1520c8d3db8a30487097c25764282cfe07e2",
          "md5": "734babe4e98a6ae06ac1e5bb2d4cc3a1"
        }
      ]
    }
  ]
}
