{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "0638349",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-0638349.toml",
          "url": "antibytes-dependency-catalog-0638349.toml",
          "size": 232720,
          "sha512": "2ce97f5b8b8885f0f654ec7e57acf3738cc9dc2f415887da3a4135ad6dc3c3db08a98831186a9dac0e0d4e5c400aa5a127b0bd31be4af00ecbae7a01bd125bcf",
          "sha256": "34ac94350f9d209ab3fbdae57c22b3ebaf06a2a512601d3c34f6d8aae939f126",
          "sha1": "dae7e58e5f5493594bf5ad1a56bf7399d0c4ab4d",
          "md5": "74d89574d219c1d26dc08386e4f1c164"
        }
      ]
    }
  ]
}
