{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc02-SNAPSHOT/kmock-0.3.0-rc02-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc02-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosarm64-0.3.0-rc02-SNAPSHOT.klib",
          "size": 202494,
          "sha512": "e3df69e77657afa1122994eed0f82e84560e47e15b6a03251d00a2ba5953108b91a55a524f8e3d7a2d10a69c52fb16e71fa4674c6de9f96aa451a3d50148cf63",
          "sha256": "42735e49756ccd0c6eb78427af20039e664b69d22bdb2451f618fbe52a8d58c0",
          "sha1": "463022fcbd4d66ad66e5e5239ae6227faeae75e9",
          "md5": "c5c2bb5c4dbf58fcee38949e5f15da53"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosarm64-0.3.0-rc02-SNAPSHOT-metadata.jar",
          "url": "kmock-iosarm64-0.3.0-rc02-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "89f83c667ddb619f44678dd5d0183d6f6da1b3de502a9e1161e11fc0f4392eee96ee7fba781106dbaeaa55549e0b98a75ea5ba83c493e7701346f1ffa72b07a7",
          "sha256": "5fa32697d8583ba8982736abeb39cf033bc25fdf200d8e9970a9c3d0df2556f8",
          "sha1": "809d6ddc7ba7477c64adb8dbd8e97acaf069c180",
          "md5": "42fb680fe9fda02dfecd44f3aee54ed1"
        }
      ]
    }
  ]
}
