{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/56c5f3f/test-utils-56c5f3f.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "56c5f3f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-56c5f3f.klib",
          "url": "test-utils-js-56c5f3f.klib",
          "size": 11902,
          "sha512": "bdbdf42406667fbf5a3b757d7980a282d2fb61e21bbb3a1556358a2bdbe5e5a50e752d2ea49accc5066fffd912588cb4ba7761b2c7f86375866c01f6405fe98b",
          "sha256": "afec0343c3b28a39ddc2511d50ddd2e1b33538df1deccfbabd0d73fa1e40fedf",
          "sha1": "76c5a7ba08cc113c954f703b8bd0386061c9be0b",
          "md5": "ecedb1200b4f19bef80545fc273539ea"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-56c5f3f.klib",
          "url": "test-utils-js-56c5f3f.klib",
          "size": 11902,
          "sha512": "bdbdf42406667fbf5a3b757d7980a282d2fb61e21bbb3a1556358a2bdbe5e5a50e752d2ea49accc5066fffd912588cb4ba7761b2c7f86375866c01f6405fe98b",
          "sha256": "afec0343c3b28a39ddc2511d50ddd2e1b33538df1deccfbabd0d73fa1e40fedf",
          "sha1": "76c5a7ba08cc113c954f703b8bd0386061c9be0b",
          "md5": "ecedb1200b4f19bef80545fc273539ea"
        }
      ]
    }
  ]
}
