{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-custom-component",
    "version": "f266a0f-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-f266a0f-SNAPSHOT.jar",
          "url": "antibytes-custom-component-f266a0f-SNAPSHOT.jar",
          "size": 16176,
          "sha512": "7a0bb068bf6c4063a294b9dd180c79e43774e3d0797ee4190483220f26b4c32e36e661c3a127681c7bb712b6f1b2e6cbd80079479e1042fb50d0a558c5db37c6",
          "sha256": "3f4a4865089d07ae2b8539443f14936d2e492529c63e006976b8a4509b92df6a",
          "sha1": "215724f10055babc66f340824f698dbc7eedf36a",
          "md5": "b1f21b8e83edf26932dd80a69baee1b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-f266a0f-SNAPSHOT.jar",
          "url": "antibytes-custom-component-f266a0f-SNAPSHOT.jar",
          "size": 16176,
          "sha512": "7a0bb068bf6c4063a294b9dd180c79e43774e3d0797ee4190483220f26b4c32e36e661c3a127681c7bb712b6f1b2e6cbd80079479e1042fb50d0a558c5db37c6",
          "sha256": "3f4a4865089d07ae2b8539443f14936d2e492529c63e006976b8a4509b92df6a",
          "sha1": "215724f10055babc66f340824f698dbc7eedf36a",
          "md5": "b1f21b8e83edf26932dd80a69baee1b0"
        }
      ]
    }
  ]
}
