{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "a3799ae",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-a3799ae.jar",
          "url": "antibytes-gradle-test-utils-a3799ae.jar",
          "size": 17888,
          "sha512": "690a0824abbc9f121523b3e5fcd86a4db0dff629b26ac69992db6c444dad24b750d2bd5a2ae5c9d2dfadcd011b3d4e9cf8242ec8e0b1bab8bbe5f34f5f3d6df8",
          "sha256": "bc9277ead8fb5ca22f62a500d37d3599bd7c3ec0a2cfb587ce6454f1ce73f31c",
          "sha1": "4933cc64509aed3e9877b7e87d22ed3a4157bea8",
          "md5": "5ae2eea8f240c0338545937131328c62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-a3799ae.jar",
          "url": "antibytes-gradle-test-utils-a3799ae.jar",
          "size": 17888,
          "sha512": "690a0824abbc9f121523b3e5fcd86a4db0dff629b26ac69992db6c444dad24b750d2bd5a2ae5c9d2dfadcd011b3d4e9cf8242ec8e0b1bab8bbe5f34f5f3d6df8",
          "sha256": "bc9277ead8fb5ca22f62a500d37d3599bd7c3ec0a2cfb587ce6454f1ce73f31c",
          "sha1": "4933cc64509aed3e9877b7e87d22ed3a4157bea8",
          "md5": "5ae2eea8f240c0338545937131328c62"
        }
      ]
    }
  ]
}
