{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/8c5f468/test-utils-8c5f468.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "8c5f468",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-8c5f468.klib",
          "url": "test-utils-js-8c5f468.klib",
          "size": 12070,
          "sha512": "db38f309ccc60d235d6c7a1ec31e3e5828ca9c7b452d5ddff266a03be58acaf83a25c130bcb62b90f5a370275fc3d89605c0b955139c13ca4bf059a1eef0eeb0",
          "sha256": "ef3db93faea9bf45c5da2018f62bf2c7492e8aca4459dc048cf2b63292952308",
          "sha1": "4d460dde83e1cf4bd0bbe0af110b635ba5e7c77f",
          "md5": "6286b2aef75e58b3e4455a00b4ecd110"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-8c5f468.klib",
          "url": "test-utils-js-8c5f468.klib",
          "size": 12070,
          "sha512": "db38f309ccc60d235d6c7a1ec31e3e5828ca9c7b452d5ddff266a03be58acaf83a25c130bcb62b90f5a370275fc3d89605c0b955139c13ca4bf059a1eef0eeb0",
          "sha256": "ef3db93faea9bf45c5da2018f62bf2c7492e8aca4459dc048cf2b63292952308",
          "sha1": "4d460dde83e1cf4bd0bbe0af110b635ba5e7c77f",
          "md5": "6286b2aef75e58b3e4455a00b4ecd110"
        }
      ]
    }
  ]
}
