{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "dda2add",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-dda2add.toml",
          "url": "antibytes-dependency-catalog-dda2add.toml",
          "size": 248014,
          "sha512": "2833c025db97393be5aabab21e2ce0d70048873c8884ed206ed446ebdba1f4cf18049e72769b4eefa8085d84e5952ccacbe2cee1782eb6d56239f37ca14b56fc",
          "sha256": "ef8a0260e639d934febfea6ea60b3231589ea9b4da2a293c172d46016182eef3",
          "sha1": "e425c3af7a9ec76ac26a5a82f849dd2834b1162a",
          "md5": "05e062b152d6c2714307706d50bf0f07"
        }
      ]
    }
  ]
}
