{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/eaacea3/test-utils-fixture-eaacea3.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "eaacea3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-eaacea3.klib",
          "url": "test-utils-fixture-js-eaacea3.klib",
          "size": 38261,
          "sha512": "e72abaacab4a5f1424d8cfcf92f6fcb6683ee8e52ab07fd33c47c3525312a5ba71c74ac5ee0a9f6f85b9f31db6d05c7aa016dc128e832c018a9c272f87889e11",
          "sha256": "bc7bd77a14b7f3b80cfabc918dd89336ee8e54d7b3f6b46d4bd0ba89ffa9900c",
          "sha1": "018d8860af7ae86ca7f0885e059f818ac92667f1",
          "md5": "74b5a21e19ef885d76304681219e3076"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-eaacea3.klib",
          "url": "test-utils-fixture-js-eaacea3.klib",
          "size": 38261,
          "sha512": "e72abaacab4a5f1424d8cfcf92f6fcb6683ee8e52ab07fd33c47c3525312a5ba71c74ac5ee0a9f6f85b9f31db6d05c7aa016dc128e832c018a9c272f87889e11",
          "sha256": "bc7bd77a14b7f3b80cfabc918dd89336ee8e54d7b3f6b46d4bd0ba89ffa9900c",
          "sha1": "018d8860af7ae86ca7f0885e059f818ac92667f1",
          "md5": "74b5a21e19ef885d76304681219e3076"
        }
      ]
    }
  ]
}
