{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/d2c62a3/test-utils-fixture-d2c62a3.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "d2c62a3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm-d2c62a3.jar",
          "url": "test-utils-fixture-jvm-d2c62a3.jar",
          "size": 68983,
          "sha512": "b1971db19329f913449a36e2ee98c58a34e137092fb2222eb0a2db95f99f2d9da50e3271a7b845fed4388d40cf20825b2b5d7c54aad4c829ca59cad49e1309de",
          "sha256": "69a360dc3b84a8698f495ee9f9a28ee2deb1698d3d7089f8b2437cdddbae278e",
          "sha1": "fc8fb2cea9da2796188d6a87bed6d39f06cabe7c",
          "md5": "78210c84c789229a5e822029332e4d58"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm-d2c62a3.jar",
          "url": "test-utils-fixture-jvm-d2c62a3.jar",
          "size": 68983,
          "sha512": "b1971db19329f913449a36e2ee98c58a34e137092fb2222eb0a2db95f99f2d9da50e3271a7b845fed4388d40cf20825b2b5d7c54aad4c829ca59cad49e1309de",
          "sha256": "69a360dc3b84a8698f495ee9f9a28ee2deb1698d3d7089f8b2437cdddbae278e",
          "sha1": "fc8fb2cea9da2796188d6a87bed6d39f06cabe7c",
          "md5": "78210c84c789229a5e822029332e4d58"
        }
      ]
    }
  ]
}
