{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/d2c62a3/test-utils-d2c62a3.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "d2c62a3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm-d2c62a3.jar",
          "url": "test-utils-jvm-d2c62a3.jar",
          "size": 8848,
          "sha512": "9f9ad48db82c03d581b0cecbc489d20932f4f03ac4f03930bdcd60358f62dba22ef807dcbc45e27638b5f8b22991317be5d278c4aaca3974739a8696e418fc6b",
          "sha256": "0d81f432673b6dafcb68e171ebcb5bd6c9744399f5b6f0d32a6564066a685b28",
          "sha1": "e6988de91e30b2890dc18e3a3f616e910b480f1d",
          "md5": "75881b44e49273c8e7855c879395a655"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-d2c62a3.jar",
          "url": "test-utils-jvm-d2c62a3.jar",
          "size": 8848,
          "sha512": "9f9ad48db82c03d581b0cecbc489d20932f4f03ac4f03930bdcd60358f62dba22ef807dcbc45e27638b5f8b22991317be5d278c4aaca3974739a8696e418fc6b",
          "sha256": "0d81f432673b6dafcb68e171ebcb5bd6c9744399f5b6f0d32a6564066a685b28",
          "sha1": "e6988de91e30b2890dc18e3a3f616e910b480f1d",
          "md5": "75881b44e49273c8e7855c879395a655"
        }
      ]
    }
  ]
}
