{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/b6c6e6c/test-utils-ktor-b6c6e6c.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "b6c6e6c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.8"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-watchosx64-b6c6e6c.klib",
          "size": 15519,
          "sha512": "cd8e97332b0b081abf41d964cd2ef6df26c78d2ec4a81e78377b8358f7d5f08e685d4b86eab538aa260ad25f80332c2eadc80ce2570ea9a2c41e55dc2b62b93c",
          "sha256": "a380d3df7d59ab8ab3e1d3f924dd3714c077ebd8480a7fa04abb53176de1d49b",
          "sha1": "24810c8e47350a25a27e132439ad7ef9820c9259",
          "md5": "6a9d27b480416e150de3cee3cd0cb420"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-ktor-watchosx64-b6c6e6c-sources.jar",
          "url": "test-utils-ktor-watchosx64-b6c6e6c-sources.jar",
          "size": 2872,
          "sha512": "2268f2772929e73f6f4cccb0ebfc887c2fca1a9a7518d50c3a0cd6141b1615740b1bbe8f39f3ae9045c34e283023352c23e1943c8c39a58f65cc05243bf01a94",
          "sha256": "6d96d8b473fe6fa2ee93d7c4ac375d0570434c9ab65c01bae96d632733a9d562",
          "sha1": "95f77daf58aa6a77bf8927057cd070da7b9b3409",
          "md5": "2b46f609ce899dc78e54dabcd42dec8a"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.8"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-watchosx64-b6c6e6c-metadata.jar",
          "url": "test-utils-ktor-watchosx64-b6c6e6c-metadata.jar",
          "size": 261,
          "sha512": "629daae548cdca93345c07d47936fb3385af5882b50ba6d2a29fcbfc6593425dba62449c718b2e32734a0a9dd7237f0aed1165bd568d68cb5feeee2ca65787ed",
          "sha256": "fc04b357c8b0c6e109b87099bc91071752f44b4b16e43b5d5fe87e4121b20cbe",
          "sha1": "03b97281363e8442d1e86cbf89d5fb252f873448",
          "md5": "a34390bbcb0a610bcf0969a9b8f75c42"
        }
      ]
    }
  ]
}
