{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "c657a3f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-c657a3f.jar",
          "url": "antibytes-versioning-c657a3f.jar",
          "size": 24286,
          "sha512": "bfb93a7c653701a0249bbd6fc9346abb014a78c3fc9f90b4e4e4a676caf925814e43718006bdc7555816ba9066a1cad5cc59fea5c196fb9062f69d63b1e761cc",
          "sha256": "2027c1d5f95671399e3a460ab45aad880f1265fedc4f8b511c91ff58a24d55b0",
          "sha1": "3c98ea80a929deb322d8ac8d70889831173cd993",
          "md5": "c491f45ea75f4ad23ff17f861b69917c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-c657a3f.jar",
          "url": "antibytes-versioning-c657a3f.jar",
          "size": 24286,
          "sha512": "bfb93a7c653701a0249bbd6fc9346abb014a78c3fc9f90b4e4e4a676caf925814e43718006bdc7555816ba9066a1cad5cc59fea5c196fb9062f69d63b1e761cc",
          "sha256": "2027c1d5f95671399e3a460ab45aad880f1265fedc4f8b511c91ff58a24d55b0",
          "sha1": "3c98ea80a929deb322d8ac8d70889831173cd993",
          "md5": "c491f45ea75f4ad23ff17f861b69917c"
        }
      ]
    }
  ]
}
