{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/b67f120/test-utils-resourceloader-b67f120.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "b67f120",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iosarm64-b67f120.klib",
          "size": 12865,
          "sha512": "d4354a16ff4e7f671a885afb5bd50aa493618e58eb624522b6443a3e88c75c55809c4c7926e37e528f7ee3db77798347c8dfa0f0dfe19972f3324d577ca388db",
          "sha256": "34d19a0a80dbb12e2b11109e11dc0627ee8514043a2e6e69b536b6dfd94e211a",
          "sha1": "52b6a8fdf6b799f09150e4e5169200bdd7f836c4",
          "md5": "bf93c70f016dce7067f84b5922b6e864"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iosarm64-b67f120-metadata.jar",
          "url": "test-utils-resourceloader-iosarm64-b67f120-metadata.jar",
          "size": 261,
          "sha512": "5ba6747300db64cb4bc11414464640c7e2a9f8294c654239f27a09f6fe0693f34e4b34e437f6c5c614f2e5f6e376a288239f0e8ec7f2787bb05f50b76f2e2ac7",
          "sha256": "8cbb7141904f7c1f940dd1dfe17e555172a540a4715baf593d94c38692aed58c",
          "sha1": "c926e04c37d8de6bd97a9b46067723ee7da6f767",
          "md5": "89bb5ace9aecae66e73a8d328ed860da"
        }
      ]
    }
  ]
}
