{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "25e268f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-metadata-25e268f-all.jar",
          "url": "test-utils-coroutine-25e268f-all.jar",
          "size": 10583,
          "sha512": "59110cc700def45ff415eeff3adc2c21b184787963e452d4ee2544cd3bcc0d5ef5e77ce88cdcb5d94fccbea858f870c1d5007bd582bf783d28f0b6903f84c0f6",
          "sha256": "81f8204fe5f21b250b3135dff20f9a99f616b45133b3dfee93b0187ab958b938",
          "sha1": "a66378cbd3826064dacc529d35adc3a6985c1029",
          "md5": "82ad79bea9c0324cb7f9ee4358b573ab"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-coroutine-25e268f.jar",
          "url": "test-utils-coroutine-25e268f.jar",
          "size": 3033,
          "sha512": "0b83cfeb730dce7b3e06793e1ff07bbc59da05b1e99a5972b5e064722d4bd09fb40fb5db01ff098b65a357e842e8fc68ca2239cf6425a76f8ffd871440287ce1",
          "sha256": "706770728f178121f0822b1876b8b99d65e74dad99b3746970a0ae7a3b8584f9",
          "sha1": "219a2dd221b73276ec6294a7954e967f4e6bb292",
          "md5": "33ec75accdfe766fc3bd89ef0e769aef"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/25e268f/test-utils-coroutine-android-25e268f.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "25e268f"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/25e268f/test-utils-coroutine-android-25e268f.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "25e268f"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iosarm64/25e268f/test-utils-coroutine-iosarm64-25e268f.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iosarm64",
        "version": "25e268f"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iosarm64/25e268f/test-utils-coroutine-iosarm64-25e268f.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iosarm64",
        "version": "25e268f"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iossimulatorarm64/25e268f/test-utils-coroutine-iossimulatorarm64-25e268f.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iossimulatorarm64",
        "version": "25e268f"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iossimulatorarm64/25e268f/test-utils-coroutine-iossimulatorarm64-25e268f.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iossimulatorarm64",
        "version": "25e268f"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iosx64/25e268f/test-utils-coroutine-iosx64-25e268f.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iosx64",
        "version": "25e268f"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iosx64/25e268f/test-utils-coroutine-iosx64-25e268f.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iosx64",
        "version": "25e268f"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-js/25e268f/test-utils-coroutine-js-25e268f.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-js",
        "version": "25e268f"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-js/25e268f/test-utils-coroutine-js-25e268f.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-js",
        "version": "25e268f"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/25e268f/test-utils-coroutine-jvm-25e268f.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "25e268f"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/25e268f/test-utils-coroutine-jvm-25e268f.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "25e268f"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-linuxx64/25e268f/test-utils-coroutine-linuxx64-25e268f.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-linuxx64",
        "version": "25e268f"
      }
    }
  ]
}
