{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-SNAPSHOT.klib",
          "size": 170722,
          "sha512": "4d7646ab41f5894a632e20ad5eadc5490f853822bcb18d5fb29a78b4400675dccdc21940465b097c2d9462c6dd4bdb08c20f4670cb67e93e378edfafd1cf45fd",
          "sha256": "f071bc28fdd62589a9c7278ee29eeab4b4789bb446404127d86a879837938672",
          "sha1": "6721067930f9d39bc9193e37a6c44c72b98630a7",
          "md5": "48ee7c0dbad0afe129ccd4e30f74ab8e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-SNAPSHOT.klib",
          "size": 170722,
          "sha512": "4d7646ab41f5894a632e20ad5eadc5490f853822bcb18d5fb29a78b4400675dccdc21940465b097c2d9462c6dd4bdb08c20f4670cb67e93e378edfafd1cf45fd",
          "sha256": "f071bc28fdd62589a9c7278ee29eeab4b4789bb446404127d86a879837938672",
          "sha1": "6721067930f9d39bc9193e37a6c44c72b98630a7",
          "md5": "48ee7c0dbad0afe129ccd4e30f74ab8e"
        }
      ]
    }
  ]
}
