{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-SNAPSHOT.klib",
          "size": 168254,
          "sha512": "4a0139a255442e6773d2db6d4f56f6fe8bff123cadc8547f9ea86060ab90aebb698e1320d6a8215df64d8da999fd018bf77cbee9e8123b986aac0c19ed7dc671",
          "sha256": "3e78d18670dbd0ba3767de3fbe0fe0e68ca93e5837ce6f53391934993117c05f",
          "sha1": "84a47d0036ce8d62d37d7d47ccad834053a2a2d8",
          "md5": "746bd6c0a4bd04d87a3c415d45c21fe7"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-SNAPSHOT.klib",
          "size": 168254,
          "sha512": "4a0139a255442e6773d2db6d4f56f6fe8bff123cadc8547f9ea86060ab90aebb698e1320d6a8215df64d8da999fd018bf77cbee9e8123b986aac0c19ed7dc671",
          "sha256": "3e78d18670dbd0ba3767de3fbe0fe0e68ca93e5837ce6f53391934993117c05f",
          "sha1": "84a47d0036ce8d62d37d7d47ccad834053a2a2d8",
          "md5": "746bd6c0a4bd04d87a3c415d45c21fe7"
        }
      ]
    }
  ]
}
