{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-SNAPSHOT.klib",
          "size": 209151,
          "sha512": "ab69411a6a3c159297a553ed87543c12260a2a67019afb0803ee4f82dafea4de536d2f9ae65d359aab34a9945acd5f84b0228c22b003bc2f651653b41f349af2",
          "sha256": "6f6059e8c7d3b6629adade4c317756e4d8ea822a06be00e3ec3ede538ddf0190",
          "sha1": "2b3652cfc8952dfb4ec4e60b46f00a66281ca2be",
          "md5": "26572d8ff43efedfc74add5207729320"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-SNAPSHOT.klib",
          "size": 209151,
          "sha512": "ab69411a6a3c159297a553ed87543c12260a2a67019afb0803ee4f82dafea4de536d2f9ae65d359aab34a9945acd5f84b0228c22b003bc2f651653b41f349af2",
          "sha256": "6f6059e8c7d3b6629adade4c317756e4d8ea822a06be00e3ec3ede538ddf0190",
          "sha1": "2b3652cfc8952dfb4ec4e60b46f00a66281ca2be",
          "md5": "26572d8ff43efedfc74add5207729320"
        }
      ]
    }
  ]
}
