{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-SNAPSHOT.klib",
          "size": 168254,
          "sha512": "0b91bdbc422f5d8255825dfb48bc05a8636f659edda5132d19877421b94adbda217607d5ab7e72db1c1400c4e7d8c4e6198f9b37c4c367f9ae9fc3d51880f12d",
          "sha256": "a9512a03e4be3501e1f421e3a893a1590b088f916de595105f1d0e0bb9ace82a",
          "sha1": "67f4f2b1afae8a5c4487ccda058d67dc08d6e2ee",
          "md5": "8941dbeecb5cdc9ebf59ba4e5bf10bb9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-SNAPSHOT.klib",
          "size": 168254,
          "sha512": "0b91bdbc422f5d8255825dfb48bc05a8636f659edda5132d19877421b94adbda217607d5ab7e72db1c1400c4e7d8c4e6198f9b37c4c367f9ae9fc3d51880f12d",
          "sha256": "a9512a03e4be3501e1f421e3a893a1590b088f916de595105f1d0e0bb9ace82a",
          "sha1": "67f4f2b1afae8a5c4487ccda058d67dc08d6e2ee",
          "md5": "8941dbeecb5cdc9ebf59ba4e5bf10bb9"
        }
      ]
    }
  ]
}
