{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-SNAPSHOT/kmock-0.1.1-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-SNAPSHOT.klib",
          "size": 167081,
          "sha512": "8b96acfda64c7ca6833af664f6eb322b554dba624180f95893bc130643133cf133990d5d1a4faa8eaf3f6b03b444ec65ffce3b1fbbd60f9c9d134596aa955d14",
          "sha256": "47b10a454916d4dd95dc15e99edd307e3b8a33d4ea0626dabd4d20a9a08129db",
          "sha1": "395d0b3c9b757d31dd1bff14bec200c27ed2cae0",
          "md5": "74d4bf188b7af7df6000816491d51ce7"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-SNAPSHOT.klib",
          "size": 167081,
          "sha512": "8b96acfda64c7ca6833af664f6eb322b554dba624180f95893bc130643133cf133990d5d1a4faa8eaf3f6b03b444ec65ffce3b1fbbd60f9c9d134596aa955d14",
          "sha256": "47b10a454916d4dd95dc15e99edd307e3b8a33d4ea0626dabd4d20a9a08129db",
          "sha1": "395d0b3c9b757d31dd1bff14bec200c27ed2cae0",
          "md5": "74d4bf188b7af7df6000816491d51ce7"
        }
      ]
    }
  ]
}
